### ISSUE TITLE
regression on fully-qualified names

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#1000]
When one spoon https://github.com/spoon-bot/guava with the latest snapshot, `AbstractMapBasedMultimap.java` is not correctly rewritten.

     /builds/workspace/Guava/guava/target/generated-sources/spoon/com/google/common/collect/AbstractMapBasedMultimap.java:[656,16] error: AbstractMapBasedMultimap.WrappedList.WrappedListIterator is not abstract and does not override abstract method next() in ListIterator

@pvojtechovsky it's maybe due to your work on access path.

**Comment by pvojtechovsky** [comment]
Could you make a failing test case in spoon for that? I guess I would need much more time to understand and make spoon-bot/guava failing the same way. Thanks!

**Comment by monperrus** [comment]
quite easy. something like:

     git clone https://github.com/spoon-bot/guava
     java -jar spoon-snapshot.jar Launcher -i guava/src/main/java --compile

**Comment by pvojtechovsky** [comment]
I cannot reproduce it using spoon master. The spoon-bot/guava compiles well for me.
Please check that your sources in /guava/src/com/google/common/collect/AbstractMapBasedMultimap.java
are equal to guava master branch.

**Comment by monperrus** [comment]
so it means that bug comes from spooning the result of spoon on guava
(ie spooning a version with only fully qualified types). would you try that?

**Comment by pvojtechovsky** [comment]
I do not understand. Do you mean this?:

1) run Launcher with args: `-i .../guava/src --compile`
2) run Launcher with args: `-i .../spooned --compile`

I tried this too and it passed well. No problem is visible here...

The error you reported:
> [656,16] error: AbstractMapBasedMultimap.WrappedList.WrappedListIterator is not abstract and does not override abstract method next() in ListIterator

has no problem with access path. It complains that method `next` is not implemented in WrappedListIterator. In my case the `next` is implemented in WrappedIterator so it compiles well in all cases which I have tried
- spoon of origin guava sources without imports and then compile - OK
- spoon of origin guava sources with imports and then compile - OK
- spoon of spooned (no imports) guava sources without imports and then compile - OK

Please send me your origin AbstractMapBasedMultimap.java and the spooned one, whose compilation fails.

**Comment by monperrus** [comment]
To reproduce:

```
git clone https://github.com/spoon-bot/guava.git
cd guava/
git checkout .
curl http://spoon.gforge.inria.fr/jenkins/build.sh | stdbuf -i 50k bash
```
`build.sh` is the main no-regression script. It spoons the project, then compiles it, then runs the tests so see whether some behavior has changed.

**Comment by pvojtechovsky** [comment]
I reproduced it. The problem is that spoon now produces

> com.google.common.collect.AbstractMapBasedMultimap.WrappedList.WrappedIterator

but it should produce

> com.google.common.collect.AbstractMapBasedMultimap<K, V>.WrappedList.WrappedIterator
