### ISSUE TITLE
Issue when cloning methods that contain invocations to j.l.Object methods

### ISSUE THREAD

**Issue by seintur** [INRIA/spoon#1006]
Dear all,

When cloning methods that contain invocations to j.l.Object methods such as:

public void methodUsingjlObjectMethods() {
    notify();
}

Spoons returns a cloned method that, when pretty-printed reads like:

public void methodUsingjlObjectMethods() {
    java.lang.Object.this.notify();
}

The issue is that this code does not compile, and outputs the error "No enclosing instance of type Object is accessible in scope" for "java.lang.Object.this".

This issue is illustrated with the following (quickly written) test:

https://github.com/seintur/spoon/blob/42c597dade6795a6b48c99aa41a200b3058a7c69/src/test/java/spoon/test/method/MethodTest.java#L58

The issue is certainly related to recent commits since this is a new one that just appeared recently in the past days.

Cheers,
Lionel.

**Comment by monperrus** [comment]
Yes, we have a much better clone now :-) maybe too deep.

Let us see.

--Martin

**Comment by tdurieux** [comment]
> Yes, we have a much better clone now :-) maybe too deep.

In fact the implicit property does not seam to be cloned

**Comment by monperrus** [comment]
Yes, this is on purpose, for sake of easy debugging and least
astonishment, because what's implicit in one context is not necessarily
implicit in another context (the cloned object will likely be in another
context).

**Comment by seintur** [comment]
Sorry guys, seems like we need to reopen this one.

I bumped in a same kind of problem when cloning anonymous classes. E.g. the following method:

    public void a() {
    	new Thread() {
    		public void run() {
    		}
    	}.start();
    }

when cloned, is pretty-printed:

public void a() {
    new java.lang.Thread() {
        1() {
            super();
        }

        public void run() {
        }
    }.start();
}

Seems like the implicit constructor of the original anonymous class is no longer implicit in the clone. Of course this does not compile.

Cheers,
Lionel.
