### ISSUE TITLE
support for only parsing structural elements

### ISSUE THREAD

**Issue by NoizeMe** [INRIA/spoon#1009]
Hey,

I use spoon to generate a meta model of the type information of a Java domain project. It is all working good, but is kind of slow, when run on a large project.

I would like to know if there is a possibility to only parse and process structural elements and just skip any code elements?
I am also interessted in a way to set the output-type argument in a programmatic way, but was not able to find a setter for it.

With kind regards,
Jan

**Comment by monperrus** [comment]
> It is all working good, but is kind of slow, when run on a large project.

What part is slow? Building the model? Transforming it? or pretty-printing it to disk?

> I would like to know if there is a possibility to only parse and process structural elements and just skip any code elements?

Do you mean having only a partial model?

**Comment by monperrus** [comment]
> I was wondering if there is any way to tell Spoon or the underlying JDT to just not process code blocks

There is no such feature. 

However, it could be done in two ways:

1. telling JDT not to parse the code (how?)
1. telling Spoon not to build the code model but only the structural one.

The second one is probably quite easy to do by inserting an appropriate hook in the traversal of the JDT model (probably somewhere in JDTTreeBuilder or a related class)

Pull request welcome!

**Comment by monperrus** [comment]
A third option is to first compile the code and to use Spoon's runtime reflection:

```
CtType s = new TypeFactory().get(String.class);
System.out.println(s.getSimpleName());
```
