### ISSUE TITLE
 set the output-type argument in a programmatic way

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#1010]
from @NoizeMe

> I am also interessted in a way to set the output-type argument in a programmatic way, but was not able to find a setter for it.

**Comment by monperrus** [comment]
@NoizeMe, if you don't want to pretty-print:, use `buildModel`:

```
Launcher spoon = new Launcher();
spoon.addInputResource("src/test/resources/spoon/test/api");
spoon.buildModel();
CtModel model = spoon.getModel();
```

**Comment by NoizeMe** [comment]
Thanks for the hint, I will try that tomorrow. Would be still nice to just have a setter for that, like for all the other stuff :).

**Comment by monperrus** [comment]
> Would be still nice to just have a setter for that, like for all the other stuff :).

I agree. Pull request welcome :-)
