### ISSUE TITLE
Upgrade compatibility level spoon java sources from 7 to 8?

### ISSUE THREAD

**Issue by pvojtechovsky** [INRIA/spoon#1014]
In the refactoring and analyzing tasks, which needs a different ways of traversing of spoon model, there might be helpful to have java 8 lambdas. What about upgrade java sources to java 8?

**Comment by monperrus** [comment]
In principle why not. But we want to keep a binary compatibility with
Java 7 VMs still for some time. And lambdas and co are really bad at this.

**Comment by retuxx** [comment]
I think sticking with Java 7 is a good idea. Java 8 elements, like lambdas, are not feature relevant.

**Comment by pvojtechovsky** [comment]
ok, I understand

**Comment by seintur** [comment]
What about starting a branch with these Java 8 specific features in order to keep the main trunk Java 7 compliant and still anticipating with a branch dedicated to Java 8?

**Comment by pvojtechovsky** [comment]
I guess we can implement support for java 8 lambdas using java 7 compatible code in spoon. Only the client of spoon must use java 8 to maximize profit of this support.
I do not need branch now
