### ISSUE TITLE
store execution time for each test to detect performance regressions

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#1024]

**Comment by surli** [comment]
http://vesavanska.com/2014/keep-track-of-test-suite-run-duration-with-travis-ci

**Comment by monperrus** [comment]
For the record 

> We've just realized that the maven test plugin (surefire) already stores the execution time of each test in an xml file. To get the performance history, it seems one can simply upload them to a database at each build in the CI and to graph them afterwards.

**Comment by monperrus** [comment]
For the record thanks to @vmassol

> 2 options in Jenkins:
> 1) Build time history. For example: 
> http://ci.xwiki.org/job/xwiki-enterprise-test-selenium/buildTimeTrend
>
> 2) Test history per test. For example:
> http://ci.xwiki.org/job/xwiki-enterprise-test-selenium/org.xwiki.enterprise$xwiki-enterprise-test-selenium/2899/testReport/org.xwiki.test.selenium/AdministrationTest/testCodeToExecuteNotInline/history/

**Comment by surli** [comment]
Fix with standard view in Jenkins.
