### ISSUE TITLE
ClassCastException when using TemplateMatcher with a string literal parameter

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#1025]
see http://stackoverflow.com/questions/40964338/classcastexception-when-using-templatematcher-with-a-string-literal-parameter

**Comment by surli** [comment]
No answer concerning the fix proposed, neither here or on stackoverflow: do we close the ticket for now?

**Comment by surli** [comment]
I close the issue for now, don't hesitate to reopen it if the problem persists.
