### ISSUE TITLE
Template matcher also find itself when matching

### ISSUE THREAD

**Issue by surli** [INRIA/spoon#1033]
See https://github.com/surli/spoon/commit/1dd645d8907fbe6a228d2bcba7fd61a44557ba6c to reproduce the bug: currently it detects both `BTServiceImpl` and `SecurityCheckerTemplate`

**Comment by monperrus** [comment]
this is a bug. and also a nice dynamic contract to add.

each time we try to match, we test that the templates matches itself
(but don't return it of course). this costs a litlle bit, but we'll find
bugs with such a powerful dynamic contract.

--Martin
