### ISSUE TITLE
Visualization of the evolution of the Spoon code base

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#1043]
here are the cool plots of @erikbern 's [git-of-theseus](https://github.com/erikbern/git-of-theseus/) for Spoon.

Theseus plot (proportion of old code at time t)
---------------

First, we really see the renaissance of Spoon in 2014, thanks to @Inria 's funding, and the subsequent awesome work of @GerardPaligot . This new energy in the project has created code, and also impacted the existing code (old code from 2005-2006 being slowly deleted).
![stack_plot](https://cloud.githubusercontent.com/assets/803666/21255944/812b81fc-c36f-11e6-9bec-0605ceb43196.png)

Survival plot  (code old at least n years)
---------------
The survival plot is interesting as well. It's completely different from the examples given in https://erikbern.com/2016/12/05/the-half-life-of-code.html. It also reflects the different phases of the project.
Some old code still here (at the right-hand side) of the figure, some new code regularly evolving (at the left-hand side), and a plateau (code here between 2.5 and 6 years), corresponding to the great Spoon hibernation, when @petitpre and @renaudpawlak left the project for other great adventures. 
![survival_plot](https://cloud.githubusercontent.com/assets/803666/21256166/028b041a-c371-11e6-8cd7-4084f540e4a8.png)

What do you think?

**Comment by arnobl** [comment]
Interesting plots.
One question regarding the old code: Is the old code almost unused code or critical code (and/or code that nobody understand anymore and therefore fear to change)?

Correlations may be done with the test code coverage.

Do the plots include the test folder?

**Comment by monperrus** [comment]
> One question regarding the old code: Is the old code almost unused code or critical code?

I don't know. That would be an interesting thing to look at. For instance, we can compute the median age of lines per file.

> Do the plots include the test folder?

Yes, this partly explains the huge recent growth, when we started to <s>doubt </s> test in 2014 :-)
