### ISSUE TITLE
regression on fully-qualified names for constructor

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#1045]
see generated code in #1039 

regression spotted by the eagle eye of @tdurieux

**Comment by surli** [comment]
@monperrus could you just check if the fix proposed in #1048 changes anything for this issue?
And could you give me info how you call the generators exactly?
Thanks!

**Comment by monperrus** [comment]
>  And could you give me info how you call the generators exactly?

By simply running `CtGenerationTest`

**Comment by surli** [comment]
Wrong issue closed. #1048 was intended to fix #1044. It seems this bug is still open.
