### ISSUE TITLE
refactoring: CtReference extend CtNamedElement

### ISSUE THREAD

**Issue by surli** [INRIA/spoon#1047]
This is a general question about the metamodel.
It is explicitely specified that `CtReference` is a named element:

> This is the root interface for named program element references.

However it extends `CtElement` and specify the methods `getSimpleName` and `setSimpleName` which are defined in `CtNamedElement`. 
I assume this is because `CtNamedElement` also define the method `getReference` which we do not want in `CtReference`. But why not restrict `CtNamedElement` to the two previously mentionned methods and create another interface `CtElementWithReference` for `getReference`, then create another interface which inherits from `CtNamedElement` and `CtElementWithReference`?

**Comment by monperrus** [comment]
for historical reasons (code and reference elements were segregated for a long time).

a simple solution would be to put CtReference under CtNamedElement and that getReference simply returns `this`.

WDYT?

**Comment by surli** [comment]
Yes it's easier and more concise. I'll do the refactoring when the other bugs will be fixed.

**Comment by surli** [comment]
Finally after discussion with @monperrus it appears that `CtReference` should remain separated from `CtNamedElement` as those elements are "concrete" elements (like Class, Package, etc) in oposition with references which are pointers.
