### ISSUE TITLE
Question: Filter/QueryStep usage/implementation/architecture.

### ISSUE THREAD

**Issue by pvojtechovsky** [INRIA/spoon#1050]
There are Filters in spoon and there will be QuerySteps ( #1018 ). I would like to discuss complex QuerySteps (I will call CQS here), which are based on Filter and a new algorithm, which computes starting AST node(s) whose children will be filtered.

I will implement for example new CQS FieldReferenceFilter. It will consists of these two parts
* Filter, which matches reference to a field of an type
* algorithm, which detects where to search for these references (public fields are searched in root package,..., private fields are searched in current top level type.)

I expect more such CQS classes. The question is where to put that code and how to name class.

A) To have one class called FieldReferenceFilter
the problem is that it is not visible, for the clients of spoon, what this class does and how to use it. Why? Is it a Filter or CQS? You can write code like
```java
field.map(new FieldReferenceFilter())...
antype.filterChildren(new FieldRefernceFilter(field))
```
In case of Filter based class, only the second line will compile well, while in case of CQS both lines are possible.
The first line searches for **all** references of `field`, while second line searches for references of field **in scope** of the type `antype`. The results of these two lines are different!

Do we want to support both cases? I guess most of the clients will need the first one ( in case of FieldReferenceFilter), while in some rare cases the second one might be interesting too.

I have feeling like this way is confusing...

B) To have two classes FieldReferenceFilter and FieldReferencesQS
FieldReferenceFilter is just plain Filter (no CQS). The FieldReferenceQS does not implement Filter, it implements only CtQuerySetp. Now only this is compilable.
```java
field.map(new FieldReferencesQS())...
antype.filterChildren(new FieldRefernceFilter(field))
```
and it is clear, which class does what...

What way do you preffer? How to name CQS clases in case of B? Any other idea?

**Comment by pvojtechovsky** [comment]
Better way?
C) to have class FieldReferenceQS, which implements CtQueryStep and one public **nested** class FieldReferenceFilter, which implements Filter.
... just how to name the top level class?

**Comment by monperrus** [comment]
> What way do you prefer?

I clearly prefer solution B. There is no need to always support old-style filters and new-style queries in the same class.

> How to name CQS clases in case of B? 

FieldReferenceQuery

> Any other idea?

The notion of scope is rather implicit here, esp with only `map(CtFunction)`. Maybe we need something like `scopedMap(CtScopedFunction)` with `CtScopedFunction extends CtFunction)`.

Let's finish #1018 first?

**Comment by monperrus** [comment]
question answered, closing the issue.
