### ISSUE TITLE
Yet another bug spotted with static import

### ISSUE THREAD

**Issue by surli** [INRIA/spoon#1053]
Apparently some collision still occured with static imports, when using spoon on common-codecs project for example.

**Comment by ondrej-111** [comment]
I am using

<dependency>
            <groupId>fr.inria.gforge.spoon</groupId>
            <artifactId>spoon-core</artifactId>
            <version>5.5.0</version>
        </dependency>

and I got error if some static import is present:

spoon.compiler.ModelBuildingException: The import org.junit cannot be resolved at /Users/ondrejzoricak/Documents/intelliJprojects/JRoaster/tests/src/test/java/org/jboss/forge/test/roaster/model/PropertiesTest.java:9

line #9: import static org.junit.Assert.assertEquals;
...
...
...
When I commented all static imports then I got this error:

spoon.compiler.ModelBuildingException: The import org.junit cannot be resolved at /Users/ondrejzoricak/Documents/intelliJprojects/JRoaster/tests/src/test/java/org/jboss/forge/test/roaster/model/PropertiesTest.java:35


line #35: import org.junit.Before;

**Comment by surli** [comment]
> I am using
> fr.inria.gforge.spoon spoon-core 5.5.0

Hi, can you try with spoon-core 5.6.0-SNAPSHOT: this is the most updated one, just to be sure the bug hasn't been fixed yet.

**Comment by ondrej-111** [comment]
Now it is the same problem with static import but on the other place.

My dependencies(and repository):

        <repositories>```xml
        <repository>
            <id>gforge.inria.fr-snapshot</id>
            <name>Maven Repository for Spoon Snapshot</name>
            <url>http://spoon.gforge.inria.fr/repositories/snapshots/</url>
            <snapshots />
        </repository>
    </repositories>

    <dependencies>
        
        <dependency>
            <groupId>org.eclipse.tycho</groupId>
            <artifactId>org.eclipse.jdt.core</artifactId>
            <version>3.12.0.v20160516-2131</version>
        </dependency>
        <dependency>
            <groupId>fr.inria.gforge.spoon</groupId>
            <artifactId>spoon-core</artifactId>
            <version>5.6.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jdt</groupId>
            <artifactId>core</artifactId>
            <version>3.3.0-v_771</version>
        </dependency>
        </dependencies>```xml

my code:

private void makeAnalyse() {```java

        int i = 1;
        Launcher spoon = new Launcher();
        spoon.addInputResource("/Users/ondrejzoricak/Documents/intelliJprojects/JRoaster");
        spoon.buildModel();
        Factory factory = spoon.getFactory();
        for (CtType<?> type :
                factory.Class().getAll()) {
            if (type.isInterface() || type.isAnnotationType()) continue;
            CtClass clazz = (CtClass) type;
            Set<CtMethod> methodSet = clazz.getAllMethods();
            for (CtMethod method :
                    methodSet) {
                final List<CtInvocation<?>> elements = method.getElements(new AbstractFilter<CtInvocation<?>>() {
                    @Override
                    public boolean matches(CtInvocation<?> element) {
                        return super.matches(element);
                    }
                });
                for (Iterator<CtInvocation<?>> it = elements.iterator(); it.hasNext(); ) {
                    CtInvocation element = it.next();
                    System.out.println(i + ". " + clazz.getSimpleName() +
                            " - " + method.getSimpleName() + " = " + element.getExecutable().toString());
                    i++;
                }
            }
        }
    }```java

Analysed project: https://github.com/forge/roaster

error: 

Exception in thread "main" spoon.compiler.ModelBuildingException: The import org.junit cannot be resolved at /Users/ondrejzoricak/Documents/intelliJprojects/JRoaster/tests/src/test/java/org/jboss/forge/test/roaster/model/PropertiesTest.java:9


line #9 in PropertiesTest.java: import static org.junit.Assert.assertEquals;
environment: macOS, intelliJ IDEA

my test project: https://github.com/ondrej-111/testDependencyForSpoon.git

**Comment by surli** [comment]
The error happens because Spoon can't found junit, so I assume you did not pass the dependencie in the classpath.
Quick solution: 
```
spoon.setArgs(new String[] { "--noclasspath" }); // -x works too
```
it add the argument no-classpath to Spoon when building the model: it won't look for outside dependencies and your model will have less information but in most of cases it's enough. 

The other solution is to pass all dependencies in the source classpath when building the model with argument: "--source-classpath" and the list of dependencies to add to the classpath separated with ":".

**Comment by ondrej-111** [comment]
Empty output after added your suggestion: spoon.setArgs(new String[] { "--noclasspath" }); // -x works too

Program finished immediately with: Process finished with exit code 0

**Comment by surli** [comment]
> After i added dependencies for jUnit problem with static imports is gone.

So problem solved?

**Comment by ondrej-111** [comment]
Yes. Actually it was not problem with static imports.

**Comment by surli** [comment]
Don't hesitate to open another issue if there's still a problem somewhere :)
