### ISSUE TITLE
Values and print of CtAnnotation

### ISSUE THREAD

**Issue by danglotb** [INRIA/spoon#1066]
Hi all,

When spooning a Annotation with multiple values, they are ordered by natural order.

However, in [javapoet](https://github.com/square/javapoet/blob/master/src/test/java/com/squareup/javapoet/AnnotationSpecTest.java#L117) a test fail after spoon the test.

See this [commit](https://github.com/danglotb/spoon/commit/698c9c8004a3835198c5f5a037891fdbdb57b892) to reproduce it.

Benjamin.

**Comment by surli** [comment]
How did you spot the bug in javapoet? 'Cause I just get the version of javapoet with the test which should fail and after calling our build.sh command to spoon it and exec tests, everything is passing.

I agree the test you submit is failing, but even in keeping the order of annotations it will fail as the pretty print won't be exactly the same.

**Comment by surli** [comment]
Ok my bad the build.sh don't spoon the test.
