### ISSUE TITLE
discussion: possible performance improvements for generating a CtModel for large software systems

### ISSUE THREAD

**Issue by retuxx** [INRIA/spoon#1071]
When generating a `CtModel` for software systems with > 100k lines, Spoon requires a whole lot of time (~ 1 min). Do you thing it is possible to reduce this time? Maybe we can use this issue to collect ideas how to enhance the performance.

**Comment by surli** [comment]
Hi,
thanks for the feedback.
A first way to reduce this time may be to skip the model checks by using the `disable-model-self-checks` arguments.
Then do you have any idea to improve the performance?

**Comment by agiannone** [comment]
I have the same problem. Running Spoon against a project with 1300 files and it's taking ~7 minutes to execute.

**Comment by agiannone** [comment]
@surli How can the property be disabled using Maven?

**Comment by retuxx** [comment]
We could try to profile a Spoon run and detect the time consumers.

**Comment by surli** [comment]
@agiannone Just checked and it's not supported yet in the maven plugin. I'll open the issue.

**Comment by surli** [comment]
@retuxx good idea: do you know any tools we can use on our jenkins to profile it from build to build?

**Comment by retuxx** [comment]
Usually, I'm using [VisualVM](https://visualvm.github.io/) for profiling tasks but I don't know if you can integrate it into Jenkins.

**Comment by retuxx** [comment]
@surli With my test setup I get:

~ 80 seconds with self check
~ 77 seconds without self check

That still is very long.

**Comment by surli** [comment]
VisualVM can bring a first insight. On the long term we could use [spf4j](http://zolyfarkas.github.io/spf4j/) in combination with [JMH plugin](https://github.com/blackboard/jmh-jenkins) to keep track on performance.

**Comment by agiannone** [comment]
@surli So running with version 5.5.0-SNAPSHOT direct from Git the time is ~60 seconds so the problem might be only with 5.4.0

**Comment by surli** [comment]
Just to be sure: the project which used to take ~7 minutes in 5.4.0 now takes ~50 seconds in 5.5.0?

**Comment by agiannone** [comment]
> ~7 minutes in 5.4.0 now takes ~50 seconds in 5.5.0?
That's right

**Comment by monperrus** [comment]
That's pure Spoon swag!

**Comment by retuxx** [comment]
Now reducing ~50 seconds to ~10 would be awesome :)

**Comment by monperrus** [comment]
running Spoon on a quantum computer?

**Comment by agiannone** [comment]
There are some for loops which could be changed to streams and then make use of all the cores. This could probably increase the speed, just not sure by how much...

**Comment by surli** [comment]
@agiannone don't hesitate to propose a PR if you spot some possible changes to improve the performance !

**Comment by surli** [comment]
I close the discussion for now. Don't hesitate to reopen it.
