### ISSUE TITLE
Keep and point to the collection of changelogs for the different versions of Spoon

### ISSUE THREAD

**Issue by seintur** [INRIA/spoon#1083]
Dear all,

Unless I missed something, the changelogs for the different versions of Spoon are not well accessible. You can certainly mine the archive of the mailing list to find them. But...

What about collecting and managing a comprehensive history of the known changelogs for the, at least recent, versions of Spoon, e.g. in a text file stored in the source tree?

This would act as a testimony of the strong activity that exists around Spoon, and encourage users to, even more, engage in such an active project.

All the best for 2017.
Lionel.

**Comment by monperrus** [comment]
They are all on the release page of Github:
https://github.com/INRIA/spoon/releases

I will add a link in the README
