### ISSUE TITLE
How do I get an executable by qualified name?

### ISSUE THREAD

**Issue by retuxx** [INRIA/spoon#1117]
The TypeFactory allows me to fetch a class by its qualified name. Is there something similar for executables?

**Comment by surli** [comment]
I assume you can do it using lambda queries introduced by @pvojtechovsky 
```java
list3 = rootPackage.filterChildren((CtExecutable executable)->executable.getSimpleName.equals(yourExecutableName)).list();
```

See https://github.com/INRIA/spoon/blob/master/doc/filter.md for more information.

**Comment by retuxx** [comment]
I have a very large Model and a lot of methods to fetch. I think using a filter is not suitable in my case.

**Comment by retuxx** [comment]
It should be emphasized that I have the full signature of a method.

**Comment by surli** [comment]
> It should be emphasized that I have the full signature of a method.

I don't think there's currently a helper in Spoon to do that. From my perspective the easiest way if you have the full signature is first to get the class using TypeFactory and then to use a filter on that class to get the executable.

**Comment by retuxx** [comment]
Ok.

**Comment by pvojtechovsky** [comment]
If #1119 would return CtMethod instead of boolean, then it would be near to what you need here, would not?
