### ISSUE TITLE
feature: Find first element using query

### ISSUE THREAD

**Issue by pvojtechovsky** [INRIA/spoon#1120]
The problems like #1119 might be implemented using queries, but we need two extra features in queries:
* to tell the query evalutor to stop evaluation early - when searched element is found
* (optionaly) support for recursive mapping. It means for example query step N can send some values back to input of query step N-1.

**Comment by monperrus** [comment]
> to tell the query evalutor to stop evaluation early - when searched element is found

That would indeed be a special and interesting kind of query. Not sure how we would implement this. Maybe only with a new factory method `createFindFirstQuery`

**Comment by pvojtechovsky** [comment]
What about `T CtQuery#first()` and code like
```java
CtElement firstResult = element.map(...).filterChildren(...)...first();
```

**Comment by surli** [comment]
Could you elaborate more on the semantic of your proposed feature: 
  * is it supposed to stop each step whenever one element is found satisfying the step query?
  * or is it supposed to stop only intermediate steps whenever one element is found and execute entirely the final step?

The signature you propose:
> What about T CtQuery#first() and code like
> ```CtElement firstResult = element.map(...).filterChildren(...)...first();```

seems to only operate to the second semantic.

> (optionaly) support for recursive mapping. It means for example query step N can send some values back to input of query step N-1.

I have the feeling this can be a really error prone feature which can easily create infinite loop... Do you think of many usecases for this feature?

**Comment by pvojtechovsky** [comment]
Originally it is supposed to stop evaluation of any other query step immediately after first result is produced by last query step.
The behavior of this new code
```java
CtElement firstResult = element.map(...).filterChildren(...)...first();
```
is equal to this old code
```java
List allResults = element.map(...).filterChildren(...)...list();
CtElement firstResult = allResults.isEmpty()?null:allResults.get(0);
```
but faster and shorter, because query knows that other results are not needed so it stops the evaluation and returns the first found element.
So it was my origin intention. I already found a use case for that. The refactoring validation algorithm has to report problem when there exists e.g. a conflict in the name. Such query has to search for first conflict and then can finish. In this case I even do not need any results, just to know whether query returns any element or none.


But you mentioned 
> is it supposed to stop each step whenever one element is found satisfying the step query?

It sounds interesting too, but I do not know yet what would be the use case behind.

>> support for recursive mapping
>
> this can be a really error prone feature 

I agree. I planned to use it for recursive visiting of class hierarchy, but it is safer to implement it as special query, which has recursive algorithm hidden internally. So I actually do not think that support for recursive query steps is needed.

**Comment by pvojtechovsky** [comment]
The usage of [EarlyTerminatingScanner](https://github.com/INRIA/spoon/blob/e5e98127df72cab06817547e4f084bcd7545bfc7/src/main/java/spoon/reflect/visitor/EarlyTerminatingScanner.java) mentioned by @msteinbeck in PR #1136, would be a nice part of this PR too.
