### ISSUE TITLE
Invalid menu links on spoon.gforge.inria.fr

### ISSUE THREAD

**Issue by pvojtechovsky** [INRIA/spoon#1121]
Last three menu links 
http://spoon.gforge.inria.fr/template_instantiation.html
http://spoon.gforge.inria.fr/template_can_be_templated.html
http://spoon.gforge.inria.fr/template_parameter.html

under http://spoon.gforge.inria.fr/template_definition.html are invalid.

**Comment by tdurieux** [comment]
@monperrus your link checker does not work?

**Comment by monperrus** [comment]
on md files it works, but not on yml configuration files.

--Martin

**Comment by pvojtechovsky** [comment]
Do you know that 
http://spoon.gforge.inria.fr/template_instantiation.html
http://spoon.gforge.inria.fr/template_can_be_templated.html
http://spoon.gforge.inria.fr/template_parameter.html
 still does not work?

**Comment by surli** [comment]
The site is compiled from yml information during night, so it's ok it does not work for now :)
