### ISSUE TITLE
CtUnaryOperator extends CtStatement

### ISSUE THREAD

**Issue by saiema** [INRIA/spoon#1134]
This makes that in the following cases

`a++;` and `i = a++;`

there's no difference between both `a++` expressions, for example, in the first case deleting the `++` operator will lead to compilation failure (since in this case `a++` is a Statement) but doing the same on the second case will lead to no compilation error since in this case `a++` is not a Statement.

Maybe `CtStatement` is not always meant to be an actual java Statement? But this leads to confusion.

An unary expression (that is, an expression that contains an unary operator applied to another expression) should be an expression, a ExpressionStatement class could be used for cases like `a++;`

**Comment by monperrus** [comment]
Hi Simon,

CtUnaryOperator is both an expression and a statement (interface CtUnaryOperator<T> extends
CtExpression<T>, CtStatement)

This happens a lot in Java, eg for method calls (CtInvocation).

--Martin

**Comment by saiema** [comment]
Hi Martin,

I knew that, and that was my issue about. The statement i = a++; according
to spoon types is a statement that has a statement as right hand side. I
can work with this, but having the type CtStatement representing both
statements and expressions diverts from what one would expect. Specifically
I can't ask whether an ast node (CtElement) represents a java statement by
the expression (elem instanceof CtStatement).

Regards.

**Comment by monperrus** [comment]
I understand. But a unary expression is indeed both. It only takes the role of a statement of an expression.

One solution would be to add a method `boolean hasStatementRole()` in CtStatement, which would encapsulates the logic of analyzing the parent.

WDYT?

**Comment by tdurieux** [comment]
We have a filter (https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/reflect/visitor/filter/LineFilter.java) that you can use to check if a statement is a line of code.

**Comment by monperrus** [comment]
Cool!

element.hasStatementRole() = new LineFilter().matches(element)

**Comment by saiema** [comment]
I can work with a workaround. But this type of things should be resolved using only the elements type.

Using a filter seems like too much for such a simple check. I'll try `e.getParent() instanceof <StatementList> || e.getParent().instanceof <Block>` to check if a `CtStatement` is indeed a java Statement. This solution should work (at least when inside a method).

If I have class Tree that inherits class Graph (a tree is a graph) I would use `g instanceof Tree` to check if a Graph is a Tree. Having `g.isTree()` or another class to do that check seems overly complicated and prone to bugs.

**Comment by monperrus** [comment]
If you have multiple orthogonal roles in a domain, you cannot encode everything in a single type (because of the combinatorial explosion). This is the case in Spoon, and we use a pretty-standard interface-based modeling of roles.

**Comment by monperrus** [comment]
> a++ > 0 should match as a code line but it's not a statement

LineFilter is badly name, it's indeed a statement filter.
