### ISSUE TITLE
Performance statistics

### ISSUE THREAD

**Issue by msteinbeck** [INRIA/spoon#1139]
I did some performance statistics and here is what I found:

- In total, building the Spoon model took ~34 seconds
- JDTBasedSpoonCompiler#buildSources took ~17 seconds
- JDTBasedSpoonCompiler#buildUnits took ~15 Seconds

That means compiling the source and building the model is about 50/50. I don't thing we can decrease the time JDT requires to compile the source code because it already uses all available cpu cores.

Here are some timings for JDTBasedSpoonCompiler#buildUnits:

- ContextBuilder#enter took ~4,8 seconds
- VirtualFolder.getAllFiles took ~2 seconds
- AstParentConsistencyChecker#scan took ~2 seconds
- CtReferenceImpl#setSimpleName took ~1 seconds
- ReferenceBuilder#getTypeReference ~2,2 seconds

Furthermore:

- CtInheritanceScanner#scan is used very often by ContextBuilder#exit, ~2,8 seconds

Input:
- Elasticsearch Core without tests
- 2827 Java files
-  sloccount: 279837 loc.

**Comment by msteinbeck** [comment]
I should note that I'm building the model in noClasspath mode

**Comment by msteinbeck** [comment]
One reason for `CtReferenceImple#setSimpleName`'s running time might be the instanceof: https://github.com/INRIA/spoon/blob/e5e98127df72cab06817547e4f084bcd7545bfc7/src/main/java/spoon/support/reflect/reference/CtReferenceImpl.java#L49

**Comment by msteinbeck** [comment]
Maybe we can get rid of the try-catch block: https://github.com/INRIA/spoon/blob/e5e98127df72cab06817547e4f084bcd7545bfc7/src/main/java/spoon/support/compiler/jdt/ContextBuilder.java#L107. It used for each element in the AST!

**Comment by msteinbeck** [comment]
By commenting out the following code:

```java
void exit(ASTNode node) {
	ASTPair pair = stack.pop();
	if (pair.node != node) {
		throw new RuntimeException("Inconsistent Stack " + node + "\n" + pair.node);
	}
	CtElement current = pair.element;
	if (!stack.isEmpty()) {
		this.jdtTreeBuilder.getExiter().setChild(current);
		this.jdtTreeBuilder.getExiter().setChild(pair.node);
                // takes very long...
		//this.jdtTreeBuilder.getExiter().scan(stack.peek().element);
	}
}
```java

I decreasing the time to build the model to 22 seconds! I know that I can't just drop this line, but maybe we can enhance the ParentExiter?

**Comment by msteinbeck** [comment]
Hint: By using a ramdisk, you can decrease the requires time to compile the sources code. In my case I reduced the time from ~17 to ~7 seconds.

**Comment by surli** [comment]
It could be great to keep those information somewhere: did you have the size of the model corresponding to the time of your first comment? Maybe you can write a performance page in Spoon doc with those numbers, and proposition to improve them?

**Comment by monperrus** [comment]
I'd propose a lightweight solution: this issue stores this information.

**Comment by msteinbeck** [comment]
> did you have the size of the model corresponding to the time of your first comment?

I added the input size above.

**Comment by surli** [comment]
Thanks, I close it now. Don't hesitate to reopen if new things come.
