### ISSUE TITLE
How could I disable static imports in the v55 output?

### ISSUE THREAD

**Issue by yanOnGithub** [INRIA/spoon#1152]
I found v53+ are producing static imports.

```
# input/Constants.java
package com.company.framework;
public class Constants {
	public static int READY = 0x1;
	public static int RUNNING = 0x2;
}

# input/Main.java
package com.company;
import com.company.framework.Constants;
public class Main {
	public static void main(String[] args) throws Exception {
		System.out.println(Constants.READY);
	}
}

# output/v52/Main.java
package com.company;
import com.company.framework.Constants;
public class Main {
	public static void main(String[] args) throws Exception {
		System.out.println(Constants.READY);
	}
}

# output/v52/Constants.java
package com.company;
public class Constants {
	public static int READY = 1;
	public static int RUNNING = 2;
}

# output/v55/Main.java
package com.company;
import com.company.framework.Constants;
import static com.company.framework.Constants.READY;
import static java.lang.System.out;
public class Main {
	public static void main(String[] args) throws Exception {
		out.println(READY);
	}
}

```

**Comment by surli** [comment]
We introduced static imports in Spoon 5.5 when you use the `--with-imports` argument. You can disable all imports if you don't pass the argument. 
The choice to add static imports has been made to fix some bugs related with name conflicts when dealing with imports.

**Comment by yanOnGithub** [comment]
Can I have this behavior?

```
// import doesnt work. should be fully-qualified in the code
import java.util.Date
import java.sql.Date
import com.company.framework1.Constants
import com.company.framework2.Constants

// ok, no fully-qualified class names
import java.util.ArrayList;

```

**Comment by surli** [comment]
Not sure to understand. Without auto-import, Spoon will use fully-qualified name and use imports only if there is name conflict between package names and variables name, i.e: 

```
import spoon.Launcher;

public class Toto {
   int spoon;
   Launcher launcher; // using spoon.Launcher here is wrong
}
```

On the contrary, in auto-import mode, Spoon try to import types and static types if there is no name conflicts:

```
import java.util.Date;

public class Toto {
  Date date1;
  java.sql.Date date2; // can't be imported
}
```

Do you spot an incorrect behaviour here? Could you create a unit test showing it?

**Comment by yanOnGithub** [comment]
Thx for the explanation. I think you mean 

> "Then you can't disable only static imports"

 while enabling auto imports.

What I want is auto imports w/o static import w/ fully qualified class names on conflict. Here is a related discussion on stackoverflow:

http://stackoverflow.com/a/2644534

One way is to produce all the fully qualified class names and press ctrl+shift+M to produce all the non-static imports, but it is kind of inefficient. Maybe I should stick with v52 --with-import at the moment.

**Comment by surli** [comment]
Reading again the produced output: 
```java
package com.company;
import com.company.framework.Constants;
import static com.company.framework.Constants.READY;
import static java.lang.System.out;
public class Main {
	public static void main(String[] args) throws Exception {
		out.println(READY);
	}
}
```
shows that we need indeed improve the pretty print of Spoon with static imports. The constant `READY` should not have been imported especially since Constants is already imported. I will have a look on that. I keep the issue open. 

> What I want is auto imports w/o static import w/ fully qualified class names on conflict.

Is it for readability reason or is there another reason behind?

**Comment by yanOnGithub** [comment]
Yes, it is for readability reason. The code base here was developed during the jdk1.4-1.6 era w/o static imports. There are a lot of constants like the following. 

```java
com.company.framework.Module1Constants.READY = 0x1; // need fqcn
com.company.framework.Module1Constants.RUNNING = 0x2; // need fqcn
com.company.framework.Module2Constants.READY = 0x3; // short name ok
com.company.framework.Module2Constants.RUNNING = 0x4; // short name ok
com.company.framework.dept3.Module1Constants.READY = 0x5; // need fqcn
com.company.framework.dept3.Module1Constants.RUNNING = 0x6; // need fqcn

```

I normally pick a handful of java files, put them in a temp directory, and run Spoon with jdk1.8 on the java files. I turn on "-x|--noclasspath" since Spoon cannot see the full code base. It would be great if Spoon could keep the original imports.

But #774 mentioned that

> spoon computes the imports instead of using the import written by the developer.

**Comment by yanOnGithub** [comment]
Meanwhile, eclipse Ctrl+shift+M requires a human to pick from a list of candidates. I came to Spoon for automation.
