### ISSUE TITLE
bug: FileNotFoundException while saving the results

### ISSUE THREAD

**Issue by scipio3000** [INRIA/spoon#1166]
Hey,

I'm currently having issues while saving the spoon results.
Here's the maven log :
```
[INFO] Reactor Summary:
[INFO]
[INFO] devops-lab1 ........................................ SUCCESS [  0.873 s]
[INFO] devops-spoon ....................................... SUCCESS [  3.372 s]
[INFO] ISLDB :: Equipe DB ................................. FAILURE [ 22.286 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 26.893 s
[INFO] Finished at: 2017-02-03T16:35:08+01:00
[INFO] Final Memory: 22M/343M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal fr.inria.gforge.spoon:spoon-maven-plugin:2.2:generate (default) on project qdb: Error to save result of the plugin: java.io.FileNotFoundException: file:\D:\Users\Gunther\devops-lab1\qdb\target\spoon-maven-plugin\result-spoon-1486136103651.xml (The filename, directory name, or volume label syntax is incorrect) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :qdb
```

I currently have 1 parent module (devops-lab1)  containing 2 sub modules :
- spoon
- qdb

Thanks.

**Comment by AdrianPal** [comment]
Same problem (same architecture) on a Mac...

**Comment by danialaswad** [comment]
Same problem (same architecture) but on linux

**Comment by surli** [comment]
I may have spotted the bug, can you tell me what maven goal you launch and give me the pom.xml section which shows the spoon-plugin configuration?
Moreover did you try to do `mvn clean` and call Spoon on one of your submodule?

**Comment by pvojtechovsky** [comment]
>  file:\D:\Users\Gunther\devops-lab1\qdb\target\spoon-maven-plugin\...

may be replace the "\" by "/", because backslashes are not valid file URL.

**Comment by scipio3000** [comment]
@surli I tried : 
```
mvn clean package
mvn clean compile
```
on the parent module and on the child module (the one containing the spoon configuration)
Here's the pom of the spoon-plugin configuration :
```
<plugins>
    ...
    <plugin>
        <groupId>fr.inria.gforge.spoon</groupId>
        <artifactId>spoon-maven-plugin</artifactId>
        <version>2.2</version>
        <executions>
          <execution>
            <phase>generate-sources</phase>
            <goals>
              <goal>generate</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <processors>
            <processor>group.tars.devops.TestProcessor</processor>
          </processors>
        </configuration>
    </plugin>
</plugins>
```

@pvojtechovsky I don't have access to this +' \\'  are valid on Windows

**Comment by pvojtechovsky** [comment]
> ' \' are valid on Windows

They are valid in a path in form `D:\Users\Gunther...`, but they are not valid in file URL. The valid file URL for Windows looks like this: `file:/D:/Users/Gunther...' or this will work too`file:///D:/Users/Gunther...'

**Comment by scipio3000** [comment]
@pvojtechovsky Right. But I don't have access to this part of the configuration

**Comment by pvojtechovsky** [comment]
ok, so then somebody from core spoon team ( @surli ?) might help you. I do not know that code too. I just know that how valid file URL should look like.

**Comment by surli** [comment]
@scipio3000 first thing: is there a reason why you don't use last version of spoon-maven-plugin? Version 2.4 is the last version (have a look on: https://mvnrepository.com/artifact/fr.inria.gforge.spoon/spoon-maven-plugin). Second thing: the project you currently working on, is it available on github? It could help for debugging. 

@pvojtechovsky right I take this one :)

**Comment by scipio3000** [comment]
@surli I upgraded to 2.4 and it did not change anything. I invited you to our project : https://github.com/scipio3000/devops-lab1

**Comment by surli** [comment]
I just release a patched version of spoon-maven-plugin to fix this bug. So use now version 2.4.1.
