### ISSUE TITLE
refactor: remove FieldScopeFunction

### ISSUE THREAD

**Issue by pvojtechovsky** [INRIA/spoon#1167]
I came to opinion, that comparing to LocalVariable/CatchVariable/Parameter-ScopeFunction, are needed to found references to these variables or detect conflicts during refactorings, the `FieldScopeFunction` makes no sense.

Why?
The `CtFieldReference` knows the declaring type and field name, what is unique identification of the referred field, so no scope function is needed to found `CtFieldReferences`. The only little purpose of field scope function might be to optimize performance and to search for such field references only in part of model. 
But this optimization:
* makes sense only for private and package protected fields, because it is clear where their references can be found.
* makes no sense for protected fields, because much more expensive scanning for child classes is needed to detect correct scope
* makes no sense for public fields, because they can be referred from whole model.

So I suggest to 
1) implement FieldScopeFunction in simpler and faster way, which focuses only for performance and does not try to search ONLY in places where field may occur.
2) to add comment to FieldScopeFunction and VariableScopeFunction, that Field scope is NOT correct for protected fields, because it searches in whole model.

Because current implementation of precise FieldScopeFunction is buggy and correct implementation is quite difficult and hard to test.

Your opinion please?

**Comment by monperrus** [comment]
> the FieldScopeFunction makes no sense.

What about simply removing FieldScopeFunction then?

**Comment by pvojtechovsky** [comment]
OK, I will try to remove it or at least make it private. But I will wait for merge of PR #1154, because there will be some conflicts.

**Comment by monperrus** [comment]
>  I will wait for merge of PR #1154 

done

> I will try to remove it or at least make it private

excellent, thanks
