### ISSUE TITLE
chore: revapi mechanism does not show only PR changes

### ISSUE THREAD

**Issue by surli** [INRIA/spoon#1171]
The purpose of the Revapi mechanism setup for PR is to compute only API changes introduced by the current PR.
However Revapi compares changes with the last snapshot deployed during night. Then if a PR has been merged during the morning and a new PR is proposed or a commit is done, compute changes concerned not only the current PR but also the newly merged PR... 
See: https://github.com/INRIA/spoon/pull/1164#issuecomment-277519127 the first change does not concerns this PR, but concerns PR #1165.

**Comment by surli** [comment]
Jenkins snapshot deployer job configuration has been changed to trigger deployment when a push is done on master. It should do the trick.

**Comment by surli** [comment]
Obviously this issue is not closed, see https://github.com/INRIA/spoon/pull/1154#issuecomment-278098555

**Comment by monperrus** [comment]
added "-U" in hook script to force snapshot update. it's maybe a solution.

**Comment by surli** [comment]
Apparently it works.

**Comment by tdurieux** [comment]
Currently Revapi shows nothing...

**Comment by surli** [comment]
> Currently Revapi shows nothing...

Yes, working on it: I just proposed a fix as a gakoci PR.
