### ISSUE TITLE
Harnessing JDT's incremental compiler to recompile only outdated files

### ISSUE THREAD

**Issue by msteinbeck** [INRIA/spoon#1175]
Is it possible to configure Spoon in a way that JDT recompiles only outdated files? I'm examining a git repository and would like to enhance my incremental model update by avoiding a complete recompilation of all source files when switching from one revision to another. I'm using [CompilationUnitFilters](https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/support/compiler/jdt/CompilationUnitFilter.java) to recreate only outdated AST nodes but, still, compilation may take quite some time in case of large size software systems.

**Comment by monperrus** [comment]
We have an untested and unmaintained command-line option `buildOnlyOutdatedFiles` for this (and all the related methods). Note: it may be broken :-)

**Comment by msteinbeck** [comment]
If I'm right, this option is used for pretty printed Java files only, not for JDT's compiler suite.

**Comment by monperrus** [comment]
No, it's also about building the model, see https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/support/compiler/jdt/JDTBasedSpoonCompiler.java#L381

**Comment by msteinbeck** [comment]
> No, it's also about building the model

Yes, but it doesn't affect JDT's compiler or do I miss something?

**Comment by msteinbeck** [comment]
After some research I found that ecj provides two different "kinds" of compiler suits, the batch compiler used by Spoon and an incremental Java compiler (https://www.ibm.com/support/knowledgecenter/SS4JCV_7.5.5/org.eclipse.jdt.doc.isv/guide/jdt_api_compile.htm). As far as I can see, the incremental compiler requires some sort of Java project (IProject) to compile files incrementally. The batch compiler, on the other hand, does not seem to provide this feature (at least I can't find any switch to enable incremental compilation for the batch compiler). So, I guess I have to extract the updated files by my own and compile them using a classpath containing all unchanged files --- performing some sort of incremental compilation by my own. Ultimately, I'll close this issue because changing from ecj's batch compiler to its incremental compiler doesn't look like a viable option to me as, from my point of view, this makes things very complicated.

**Comment by monperrus** [comment]
> I'll close this issue because changing from ecj's batch compiler to its incremental compiler
> doesn't look like a viable option to me
I agree. Thanks for the inquiry.
