### ISSUE TITLE
FieldAccess Template Example is not substituting all values

### ISSUE THREAD

**Issue by pamela-nelson** [INRIA/spoon#1181]
Hello,

I've been trying to use the field access template example but not all values are being substituted. 
I've specifically being trying to template the getters with problems. Some variables do not substitute for some reason but the rest of the values do. Would you know what is wrong?

The following values don't substitute:
` _field_` in the getter
`.get_Field_()` in getterInvocation

```java
@Getter
public _FieldType_ get_Field_() {
	return _field_;
}

void getterInvocation() {
	_target_.S().get_Field_();
}
```

**Comment by surli** [comment]
Hi Pamela, welcome there! :)
Could you give me more information about the template and the project/code on which you're trying to apply the template?

**Comment by pamela-nelson** [comment]
Yes, no problem. The template class is below:
```
public class GetterInvocationTemplate<_FieldType_> extends AbstractTemplate {

		@Parameter
		CtTypeReference<?> _FieldType_;

		@Parameter("_field_")
		String __field_;

		@Parameter
		String _Field_;

		@Parameter
		CtExpression<GetterInvocationTemplate> _target_;
		
		@Parameter
		CtFieldAccess fieldReference;

		@SuppressWarnings("unchecked")
		@Local
		public GetterInvocationTemplate(CtTypeReference<?> type, String field,
				CtFieldAccess fieldReference) {
			_FieldType_ = type;
			__field_ = field;
			_Field_ = field.substring(0,1).toUpperCase() + field.substring(1);
			_target_ = (CtExpression) fieldReference.getTarget();
			this.fieldReference = fieldReference;
		}

		@Local
		_FieldType_ _field_;
		
		@Getter
		public _FieldType_ get_Field_() {
			return _field_;
		}

		void getterInvocation() {
			_target_.S().get_Field_();
		}

		@Override
		public CtElement apply(CtType arg0) {
			// TODO Auto-generated method stub
			return null;
		}
	}
```

I'm trying to apply it to the following class to test the template works:
```
public class EncapsulateFieldOriginal_Test1 {
    public String name = "EncapsulateField";
    public final String password = "secrets";

    public void changeName(String newName) {
        newName += "Refactoring";
        name = newName;
    }

    public void changeOriginalName(String newName) {
        String temp = name;
        name = temp + "refactoring";
    }
}
```
I use the following calls to use the template:
```
Template<?> getterTemplate = new GetterInvocationTemplate(field.getType(), field.getSimpleName(), 
					fieldReference);
			
CtBlock<?> getter = Substitution.substituteMethodBody(fieldReference.getParent(CtClass.class), getterTemplate, "getterInvocation");
```
then I replace the statement using the substituted block.

This results in the following being generated.

```
 public void changeOriginalName(java.lang.String newName) {
        java.lang.String temp = get_Field_();
        name = temp + "refactoring";
    }
```

**Comment by surli** [comment]
Ok, in fact there's no bug there: the method `substituteMethodBody` litterally get the method body you call (here it's `getterInvocation`) and replace the statement with it, substituing `_target_.S()` before it. So the `_get_Field` method is never call, and even so it's not enough to get the proper getter. 

The example you try to reuse is an old one (3 years old actually) and has several more classes like different processors dedicated to find the getters. I'll open an issue to update our examples, which are clearly out of date. 

There are several to achieve what you want to do here (i.e. replacing field access to method call) like using template matcher, or just querying getters and replace manually field access. 
We can discuss the different solutions but first what's your final goal here? Was it only to redo the example or do you have another purpose in using Spoon?

**Comment by pamela-nelson** [comment]
I am doing a refactoring project for university which applies various refactorings to code.
The first one I wanted to try was making public variables private and creating getters and setters for them.
I have completed all of it apart from updating the field references to methods.

What different solutions can I try and which do you think is best?

**Comment by surli** [comment]
> What different solutions can I try and which do you think is best?

I think the easiest way is to create a custom processor for CtFieldAccess. In that processor you create a map for getters using a specific query with name pattern and maybe code content pattern to be sure. Then you have to verify in `isToBeProcessed` if the fieldAccess is contained in the getter or not. And in `process` you replace the FieldAccess by an invocation to the proper getter.

Don't hesitate to ask if you're stuck at a step.

**Comment by pamela-nelson** [comment]
Thanks for the help. I'm not quite sure how to do the query. Could you give me an example? 

The class i'm testing to try it with is this class:
```
public class EncapsulateFieldOriginal_Test1 {
    public String name = "EncapsulateField";
    public final String password = "secrets";

    public void changeName(String newName) {
        newName += "Refactoring";
        name = newName;
    }

    public void changeOriginalName(String newName) {
        String temp = name;
        name = temp + "refactoring";
    }
}

        public String getName() {
              return name;
      }
}
```

**Comment by surli** [comment]
you can write something like that:

```java
List<CtMethod> getters = yourClass.filterChildren((CtMethod method) -> method.getSimpleName().contains("get") && method.hasModifier(ModifierKind.PUBLIC) && !method.getType().equals(new TypeFactory().VOID))
				.list();
```

There's more information about queries there: http://spoon.gforge.inria.fr/filter.html

**Comment by pamela-nelson** [comment]
Ok I see, thank you. That's very useful to know. Finally how do I create a statement that calls to the Ctmethod that I can use to replace the field access?

**Comment by surli** [comment]
You should be able to do something like this: 

```java
CtInvocation invocation = getFactory().createInvocation();
invocation.setExecutable(myGetter.getReference());

fieldReference.replace(invocation);
```

**Comment by surli** [comment]
Then did you manage to create the Processsor?
If so would you agree to share it as a spoon-example? It can help other people like you in the future :)

**Comment by surli** [comment]
I close for now, if you have any other question don't hesitate to reopen.

**Comment by pamela-nelson** [comment]
Hi, Sorry for taking so long to write back. I have put off my project for a while so only getting back into it now. I have successfully got it working for getters but not for setters. I was wondering if I could get some help with that. I think my understanding of how to use the CtInvocations is wrong. When I call to setterInvocation.setExecutable(setter.get(0).getReference()); it throws a null pointer error. setter.get(0) is there but calling getReference on returns null.

My processor is below:

`	public void process(final CtFieldAccess<?> fieldReference) {
		
		CtFieldReference<?> field = fieldReference.getVariable();
		CtClass<?> enclosingClass = field.getParent(CtClass.class);
		String fieldName = field.getSimpleName().toUpperCase().substring(0, 1) + field.getSimpleName().substring(1);
		
		//requires Getter
		if (fieldReference instanceof CtFieldRead) {
			
			//retrieve getter
			List<CtMethod> getter = enclosingClass.filterChildren((CtMethod method) -> method.getSimpleName().equals("get" + fieldName) 
																	&& method.hasModifier(ModifierKind.PUBLIC) 
																	&& !method.getType().equals(new TypeFactory().VOID))
																	.list();
			
			CtInvocation<?> getterInvocation = getFactory().createInvocation();
			getterInvocation.setExecutable(getter.get(0).getReference());

			fieldReference.replace(getterInvocation);
			
		} else if (fieldReference instanceof CtFieldWrite) {
                       //Requires setter
			CtAssignment<?, ?> assignment = (CtAssignment<?, ?>) fieldReference.getParent();
			
			List<CtMethod> setter = enclosingClass.filterChildren((CtMethod method) -> method.getSimpleName().equals("set" + fieldName) 
					&& method.hasModifier(ModifierKind.PUBLIC) 
					&& !method.getType().equals(new TypeFactory().VOID))
					.list();
			
			CtInvocation<?> setterInvocation = getFactory().createInvocation();
			
			setterInvocation.addArgument(assignment.getAssignment());

			setterInvocation.setExecutable(setter.get(0).getReference());

			fieldReference.getParent().replace(setterInvocation);
		}
	}
}`

**Comment by pamela-nelson** [comment]
My main question is how to use and set Invocations for methods which require parameters. My attempt is above in the last 4 lines but I seem to be something wrong.

On another unrelated question, I was wondering how I could use filters to get all of a certain CtType from the input project rather than all within an element.

**Comment by monperrus** [comment]
> setter.get(0) is there but calling getReference on returns null.

this seems a bug, getReference should never return null

**Comment by pamela-nelson** [comment]
I have just realised I may be setting the void type of the setter method wrong which might be causing the reference problem.

Here is the code I use to create the method. How do I correctly set the type of the method to void?

` if (!field.hasModifier(ModifierKind.FINAL)) {
        	CtMethod setter = getFactory().Core().createMethod();
    		setter.setSimpleName("set" + field.getSimpleName().substring(0, 1).toUpperCase()
    				+ field.getSimpleName().substring(1));
    		setter.addModifier(ModifierKind.PUBLIC);
    		CtTypeReferenceImpl<?> voidReturnType = new CtTypeReferenceImpl<>();
    		voidReturnType.setSimpleName("void");
    		setter.setType(voidReturnType);`

**Comment by surli** [comment]
Hi @pamela-nelson 

instead of using
```
CtTypeReferenceImpl<?> voidReturnType = new CtTypeReferenceImpl<>();
    		voidReturnType.setSimpleName("void");
    		setter.setType(voidReturnType);
```

you could directly use a constant for the type void:
```
setter.setType(TypeFactory.VOID_PRIMITIVE);
```

**Comment by monperrus** [comment]
Don't hesitate to reopen :-)

**Comment by vidyat11** [comment]
Hi  

 public static void main(String[] args) {
        // set the policy file as the system securuty policy
        System.setProperty("java.security.policy", "file:/C:/java.policy");
        // create a security manager
        SecurityManagerDemo sm = new SecurityManagerDemo();
        // set the system security manager
        System.setSecurityManager(sm);
        // perform the check
        **sm.checkSystemClipboardAccess();**
        // perform the check
        sm.checkAwtEventQueueAccess();
        // check the top level window
        boolean checked = sm.checkTopLevelWindow("Window");
        System.out.println("" + checked);
        // print a message if we passed the check
        System.out.println("Allowed!");
    }

i want to change   sm.checkSystemClipboardAccess(); into sm.checkPermission(arg);..Am new to this parser.Could you give me some more information about CtInvocation..
