### ISSUE TITLE
Is there a way to create new .java files with Spoon?

### ISSUE THREAD

**Issue by dotSp0T** [INRIA/spoon#1199]
I've recently stumbled upon Spoon and successfully (after some long nights..) managed to use it in a project to modify existing source files by adding pass-through methods to them.

I now have a project where I need to create a single .java file containing a number of pass-through methods again. I could probably create an empty file and then modify that with Spoon, but I was really wondering if I could not create the whole thing with Spoon and then print that class/java-file to the Output directory..?

**Comment by tdurieux** [comment]
You can create a new class  and print it using this code snipet :

```java
final Launcher launcher = new Launcher();
launcher.addInputResource("./src/test/resources/noclasspath/draw2d");
launcher.setSourceOutputDirectory("output/folder");
launcher.buildModel();

CtClass<?> ctClass = launcher.getFactory().Class().create("my.package.Class");
// ctClass has been created in output folder
launcher.prettyprint();
```

**Comment by surli** [comment]
I assume @tdurieux answer your question, so I close this one, don't hesitate to reopen it!

**Comment by monperrus** [comment]
> I've recently stumbled upon Spoon and successfully (after some long nights..)

@dotSp0T what was the missing piece of information to getting started faster?
