### ISSUE TITLE
[generic type] JDT-related bug concerning type inference with generics and wildcard

### ISSUE THREAD

**Issue by surli** [INRIA/spoon#1202]
See PR: #1200

**Comment by monperrus** [comment]
Three solutions:

- report the bug to JDT and wait for a fix
- report the bug to JDT and fix it ourselves
- deactivate some generics checks from Spoon with special configuration of JDT's `Compiler`.

**Comment by msteinbeck** [comment]
@surli Did you already reported the bug to JDT developers?

**Comment by surli** [comment]
@msteinbeck not yet. I'll do it next week probably.

**Comment by monperrus** [comment]
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=469404

**Comment by surli** [comment]
Apparently a new release of JDT is available: https://mvnrepository.com/artifact/org.eclipse.jdt/org.eclipse.jdt.core we should see if it can help solving this one.

**Comment by monperrus** [comment]
If no action can be taken, I propose to close this one in order to keep our bug dashboard clean.

**Comment by surli** [comment]
> I propose to close this one in order to keep our bug dashboard clean

OK to me, I just put the label to be able to find it back easily.
