### ISSUE TITLE
Is there a way to make analyse and don't create spooned file in project dir?

### ISSUE THREAD

**Issue by ondrej-111** [INRIA/spoon#1203]
Hi guys.

I want to ask you one question. I am new with Spoon and I try make some analyse but after analyse spooned file in project directory is created but I don't need it... so Is there a way to use Spoon without creating spooned file?

My code now looks like:

```java
try {
            Launcher spoon = new Launcher();
            spoon.addInputResource(projectStructure.getProjectDir().getPath());
            spoon.run();
            Factory factory = spoon.getFactory();
            ....
       } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                File sponned = new File(projectStructure.getProjectDir().getPath() + "/spooned");
                if (sponned != null) {
                    FileUtils.deleteDirectory(sponned); // I delete spooned file programmatically after analyse
                }
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
```

**Comment by monperrus** [comment]
Hi,

There are two solutions. First, to tell Spoon not to write anything: 
```
Launcher spoon = new Launcher();
spoon.addInputResource(projectStructure.getProjectDir().getPath());
spoon.setArgs(new String[] {"--output-type", "nooutput" });
spoon.run();
```
or to only build the model and not call the whole `run` pipeline
```
Launcher spoon = new Launcher();
spoon.addInputResource(projectStructure.getProjectDir().getPath());
spoon.buildModel(); 
```

**Comment by dotSp0T** [comment]
I hope you don't mind me hijacking this question. But is there a way to only create create certain files while not creating others? E.g. in a use-case where one condenses the contents of _n_ classes into one class?

**Comment by monperrus** [comment]
> But is there a way to only create create certain files while not creating others?

Yes, you can set a filter on the pretty-printed classes, see command line argument `-f|--generate-files` and API method `SpoonModelBuild#generateProcessedSourceFiles(OutputType, Filter)`
