### ISSUE TITLE
How to keep original source-formatting?

### ISSUE THREAD

**Issue by dotSp0T** [INRIA/spoon#1204]
Spoon seems to have a thing for reformatting code that it shouldn't even have to touch. Is there a way to keep my formatting for things such as a list of static integers (that is a list, not a List as in the java interface. Just a plain list of static ints..) into a hell of spaced-out oneliners?

e.g. prevent spoon from making this:
```
public static int SOMETHING   = 1,
                  ELSETHING   = 2,
                  NOTHERTHING = 3;
```

into this:
```
public static int SOMETHING = 1;

public static int ELSETHING = 2;

public static int NOTHERTHING = 3;
```

**Comment by tdurieux** [comment]
Unfortunately it is not yet possible.
Spoon generates the source code with its own formatting

**Comment by dotSp0T** [comment]
@tdurieux wouldn't it technically be possible to check if an element is _valid_ when creating the model and then just attaching the original form of that element to the element so the eventual renderer can pick it up again when (pretty)printing?

Naturally the example I've chosen is one of the more extreme, but it could probably be solved by introducing a new type of field that can hold a list of name value pairs?

**Comment by monperrus** [comment]
> by introducing a new type of field that can hold a list of name value pairs?

One core design principle of the Spoon metamodel is to be close to the semantics not to the syntax.
To that extent, having a new type of field would not make sense.

However, what would be possible is to store this information in the source position or as element
metadata, and that the pretty printer takes care of it.

Pull request welcome :-)
