### ISSUE TITLE
What is the intended way to compare Type References?

### ISSUE THREAD

**Issue by dotSp0T** [INRIA/spoon#1205]
When trying to compare return types of a method to decide if I should do further modifications, I hit a stumbling block. It is not easily possible (or at least I have not yet found out how to do it) to compare return types in a natural way.

E.g. when I want to check if a method's returntype is `void` I would naturally want to write one of the following:
```
getFactory().Type().VOID == myMethod.getType()
getFactory().Type().VOID.equals(myMethod.getType())
```
Neither of both ways will return true, even if the method returns true. The issue seems to be that Spoon seems to create a new reference objects for types in its TypeFactory (and likely in other places?):
```
62: public final CtTypeReference<Void> VOID = createReference(Void.class);

96: public CtTypeReference<Void> voidType() {
97:     return VOID.clone();
98: }
```

This is not bad in itself, it would allow to modify a type reference without modifying every other type reference by accident. The issue here is though, that (although that is an assumption of me) we would want type references to point to the same thing.

With that: **Is there another, _intended_ way to compare Types or in that matter anything in Spoon?**

**Comment by monperrus** [comment]
What about `getFactory().Type().VOID_PRIMITIVE.equals(myMethod.getType())`?

**Comment by surli** [comment]
Don't hesitate to reopen.
