### ISSUE TITLE
Call graph with only invocations within project

### ISSUE THREAD

**Issue by ondrej-111** [INRIA/spoon#1209]
Hello guys. I have a program which write all invocations of some chosen project dir. But if I want to this invocations I need all project's dependencies. But in my case I need only invocations within project dir so I tried to use this flag: 
`
spoon.setArgs(new String[] { "--noclasspath" });
`
and run spoon like:

```
Launcher spoon = new Launcher();
        spoon.addInputResource("/Users/ondrejzoricak/Documents/intelliJprojects/ComprehensionTool");
        spoon.setArgs(new String[] { "--noclasspath" });
        spoon.buildModel();
```

and then get factory and write all invocations:

```
Factory factory = spoon.getFactory();
        for (CtType<?> type :
                factory.Class().getAll()) {
            if (type.isInterface() || type.isAnnotationType()) continue;
            CtClass clazz = (CtClass) type;
            Set<CtMethod> methodSet = clazz.getAllMethods();
            for (CtMethod method :
                    methodSet) {
                final List<CtInvocation<?>> elements = method.getElements(new AbstractFilter<CtInvocation<?>>() {
                    @Override
                    public boolean matches(CtInvocation<?> element) {
                        return super.matches(element);
                    }
                });
                for (Iterator<CtInvocation<?>> it = elements.iterator(); it.hasNext(); ) {
                    CtInvocation element = it.next();
                    System.out.println(i + ". " + clazz.getSimpleName() +
                            " - " + method.getSimpleName() + " = " + element.getExecutable().toString());
                    i++;
                }
            }
        }
```

but problem is that if I used --noclasspath arg then program end with empty output.

Thanks for all suggestions.

**Comment by surli** [comment]
Actually that's normal: 
```java
spoon.setArgs(new String[] { "--noclasspath" });
``` 
will reset the Spoon environment, creating an empty array for the input resources. Then you have two possible way to solve your problem, either you use the set args before:

```java
spoon.setArgs(new String[] { "--noclasspath" });
spoon.addInputResource("/Users/ondrejzoricak/Documents/intelliJprojects/ComprehensionTool");
```

or you use the programmatic way to set the environment:
```java
spoon.addInputResource("/Users/ondrejzoricak/Documents/intelliJprojects/ComprehensionTool");
spoon.getEnvironment().setNoClasspath(true);
```

**Comment by ondrej-111** [comment]
Yeah You are right it is working find now but If I instead clazz.getSimpleName() want to call clazz.getActualClass() error occur:

Exception in thread "main" spoon.support.SpoonClassNotFoundException: cannot load class: main.resources.ConsoleUI

**Comment by surli** [comment]
`getActualClass()` will load your class, then it needs the complete classpath to work and it should not be used in mode no-classpath.

**Comment by surli** [comment]
I assume it's ok now, don't hesitate to reopen the issue if you have any other question.
