### ISSUE TITLE
chore: verify that all lines changed in a PR are covered by at least one test

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#1212]
Idea: integrate https://github.com/Bachmann1234/diff-cover in CI, as we've done with revapi

**Comment by tdurieux** [comment]
Can be easy done by using the coverage API and github API

**Comment by monperrus** [comment]
@tdurieux do you mean the coveralls API?

**Comment by tdurieux** [comment]
Yes

**Comment by monperrus** [comment]
The coveralls page already gives you this information:

Eg: https://coveralls.io/builds/15689894

     59 of 65 new or added lines in 3 files covered. (90.77%) 

(only for the builds on PR, not on master builds)

Closing this one.

**Comment by tdurieux** [comment]
The useful information would be to know which added lines are not covered b

**Comment by monperrus** [comment]
coveralls give you that information if you click on the file.

See
https://coveralls.io/builds/15689894/source?filename=src%2Fmain%2Fjava%2Fspoon%2Frefactoring%2FRefactoring.java#L100

**Comment by tdurieux** [comment]
That is new, it was not there the last time I checked.
It would be nice if GitHub allows third party to integrate this type of information in the diff

**Comment by monperrus** [comment]
That may be hard to get this done by Github. Another option is to add this in
https://github.com/sindresorhus/refined-github/
