### ISSUE TITLE
CtFieldReference.getDefaultExpression() returns initializer from a field of another class

### ISSUE THREAD

**Issue by bastik** [INRIA/spoon#1213]
Hi, I'm trying to collect and evaluate certain strings in the source repository.

I tried VisitorPartialEvaluator, but it runs into an infinite loop. The reason of this is that fields get mixed up. The code setup is like this:

```java
class BaseClass {
    public final static String PREFIX = "BasePrefix";
}

class ClassB {
    public final static String PREFIX = BaseClass.PREFIX + ".b";
    public String getKey() {
        return BaseClass.PREFIX + ".x";
    }
}
```

Now if you try to read the return value of the `getKey()` method, the CtFieldReference object will return the default value of `ClassB.PREFIX`, not `BaseClass.PREFIX`.

**Comment by tdurieux** [comment]
this bug is related to #756
