### ISSUE TITLE
chore: revapi comments do not comply with minSeverity=BREAKING 

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#1229]
See for instance https://github.com/INRIA/spoon/pull/1193#issuecomment-286841295 which contains a lot of changes that are only non_breaking or potentially_breaking

**Comment by surli** [comment]
Ignore nowImplementsInterface changes, see: http://revapi.org/modules/revapi-basic-features/extensions/ignore.html

**Comment by monperrus** [comment]
See https://github.com/revapi/revapi/issues/78
