### ISSUE TITLE
CompilationUnit: Get path of .class file from CompilationUnit

### ISSUE THREAD

**Issue by msteinbeck** [INRIA/spoon#1230]
Is it possible to get the file path of the class file of a compilation unit? If not, would you mind if I would add such a feature?

**Comment by monperrus** [comment]
Sounds interesting. What method do you propose?

**Comment by msteinbeck** [comment]
I'm looking for a method like this:

```java
...
public List<File> getBinaryFiles() {
    // for each type declaration return .class file
}
...
```

This allows me to delete outdated .class files with ease. I need this for my incremental compilation approach where I'm extracting outdated files and compile them by adding the unchanged .class files to the classpath. Since a single .java file might be compiled to several .class files, `getBinaryFiles` should return a list of files.
