### ISSUE TITLE
Static variable declared in an interface won't be correctly imported

### ISSUE THREAD

**Issue by orichalque** [INRIA/spoon#1236]
Hello, 
I'm instrumenting the source code of JUnit4 using Spoon, and I noticed an issue.

I have this method before running Spoon :

```
    public synchronized void addFailure(final Test test, final AssertionFailedError e) {
        testFailed(TestRunListener.STATUS_FAILURE, test, e);
    }
```
This interface: 

```
public interface TestRunListener {
    /* test status constants*/
    int STATUS_ERROR = 1;
    int STATUS_FAILURE = 2;
    ...
}
```

And after running Spoon on my code, my method becomes: 
```
    public synchronized void addFailure(final Test test, final AssertionFailedError e) {
        // new statement added here.
        testFailed(STATUS_FAILURE, test, e);
    }
```

And the import is wrong : `import TestRunListener.STATUS_FAILURE;` instead of  `import junit.runner.TestRunListener;`

I'm currently using spoon-core-5.6.0-20170312.234509-77.jar
Is there a command-line option to add ? For now I'm using :
`launcher.setArgs(new String[]{"--output-type", "nooutput", "--with-imports", "-x"});`

And I still have an error without the "--with-import". 

Best Regards,

T.

**Comment by orichalque** [comment]
Hey,

I just tried with the last release of Spoon and I had the same problem :s

The method I'm instrumenting is in a class called [BaseTestRunner](https://github.com/junit-team/junit4/blob/master/src/main/java/junit/runner/BaseTestRunner.java) located in the same package as the interface [TestRunListener ](https://github.com/junit-team/junit4/blob/master/src/main/java/junit/runner/TestRunListener.java)

**Comment by surli** [comment]
Thanks for the information, we'll see what happened there.

**Comment by tdurieux** [comment]
I did not succeed to reproduce your bug, I try with two different spoon versions on the last junit release.

Spoon produces compilable code:

```java
public synchronized void addFailure(final Test test, final AssertionFailedError e) {
        testFailed(TestRunListener.STATUS_FAILURE, test, e);
    }
```

**Comment by orichalque** [comment]
Hello,

I managed to reproduce it with a simple case: 

```
package Model;
public interface MyInterface {
	public int VALUE = 5;
}
```

```
package Model;
public class MyClass {
    public static void main(String[] args) {
        System.out.println(MyInterface.VALUE);
    }
}

```

After instrumenting with Spoon (using the option --with-import, only), 

```
package Model;

import static MyInterface.VALUE; //Won't compile

public class MyClass {
    public static void main(String[] args) {
        System.out.println(MyInterface.VALUE);
    }
}

```

**Comment by tdurieux** [comment]
With the last spoon version I do not have the:
`import static MyInterface.VALUE; `

```java
@Test
public void test() throws Exception {
	Launcher spoon = new Launcher();
	spoon.getEnvironment().setShouldCompile(true);
	spoon.getEnvironment().setAutoImports(true);
	spoon.addInputResource("./src/test/java/spoon/test/imports/testclasses/MyInterface.java");
	spoon.addInputResource("./src/test/java/spoon/test/imports/testclasses/MyClass.java");
	spoon.setBinaryOutputDirectory("./target/spoon/static_imports/bin");
	spoon.setSourceOutputDirectory("./target/spoon/static_imports/src");
	spoon.run();
}
```

**Comment by surli** [comment]
@orichalque I just commited the unit test of @tdurieux using exactly the same package name you used in your own example and everything's runny smoothly here. 
Feel free to improve my unit test to show the bug. 

Just to be sure, can you try using Spoon 5.7.0-SNAPSHOT? 
And what JDK version are you using?

**Comment by orichalque** [comment]
Hello, 

I tried using the same configuration you used, and the problem I had disappeared. 

I was creating a new Launcher() for each class I was instrumenting, now I added the whole src folder to instrument all the classes, and the import can be resolved. 

Though I have an other import problem remaining, still with the JUnit4 source code:

I have this class: [StackTracePrintingMatcher](https://github.com/junit-team/junit4/blob/master/src/main/java/org/junit/internal/matchers/StacktracePrintingMatcher.java)
With the attribute : `private final Matcher<T> throwableMatcher;` Matcher<T> being imported by `import org.hamcrest.Matcher;`

After the instrumentation, the StackTracePrintingMatcher generated will have instead the attribute: 
`private final org.junit.internal.matchers.Matcher<T> throwableMatcher;`

And it won't compile because the class Matcher doesn't even exist in the package `org.junit.internal.matchers`.

Here's my Spoon configuration: 
```

		launcher = new Launcher();
		String sourceFiles = project.getLocation().toString() + "/src/";
		launcher.getEnvironment().setShouldCompile(true);
		launcher.getEnvironment().setAutoImports(false);
		launcher.getEnvironment().setNoClasspath(true);
		launcher.addInputResource(sourceFiles);
		launcher.setBinaryOutputDirectory(projectCopied.getLocation().toString() + "/out/");
		launcher.setSourceOutputDirectory(projectCopied.getLocation().toString() + "/outSrc/");
                // ... 
                launcher.run();
```

Do you know where this may come from ? Is this because of `launcher.getEnvironment().setNoClasspath(true);`

Thank you

Thibault

**Comment by surli** [comment]
> It was indeed a source classpath problem

Yes, in no-classpath mode, Spoon will try to find the class in the current files and if it does not manage to do it, it considers it is in the current package. 

So I consider this one is solved. Don't hesitate to reopen it if you have further questions.
