### ISSUE TITLE
Avoid rewrite of untouched classes

### ISSUE THREAD

**Issue by diorcety** [INRIA/spoon#124]
If a class is processed but not modified, for example only analyzed for creating a new class, this class is anyway generated.
Provide a way to specify the classes to generate(or the classes to don't generate) could be a good improvement

**Comment by GerardPaligot** [comment]
Hi @diorcety, do you have test the solution proposed by @monperrus? If yes, can we have your feedback about that?

Thanks in advance.

**Comment by diorcety** [comment]
No sorry. i did a workarorund
