### ISSUE TITLE
Maven plugin version 5.6.0 support

### ISSUE THREAD

**Issue by v-rtodorov** [INRIA/spoon#1250]
Hello,

There is a lot of new stuff in version 5.6.0 but the sppon-maven project uses 5.4.0 which is older. We have tried locally to increase the version in plugin pom.xml to 5.6.0 and the Processors with newer stuff like CtLiteral worked perfectly. 

Can we have spoon version upgrade for the snapshot version of the maven plugin ? It works anyway with it ?

Changed in plugin pom.xml from 5.4.0 to <spoon.version>5.6.0</spoon.version> and it works.

**Comment by surli** [comment]
> Changed in plugin pom.xml from 5.4.0 to <spoon.version>5.6.0</spoon.version> and it works.

Create a pull request on https://github.com/SpoonLabs/spoon-maven-plugin with that change and I'll merge it ;)

**Comment by v-rtodorov** [comment]
With great pleasure but I do not have rights. Please find the pom.xml attached.
[pom.xml.zip](https://github.com/INRIA/spoon/files/890748/pom.xml.zip)
<img width="848" alt="screen shot 2017-04-03 at 9 36 26 am" src="https://cloud.githubusercontent.com/assets/26829039/24620327/14b2dbbe-1852-11e7-9426-660d0e7e82f6.png">

**Comment by surli** [comment]
Actually I was talking about forking the project and creating a Github pull request, not pushing directly ;) 

But it's ok I did the changes and I just released a new version of spoon-maven-plugin.

**Comment by v-rtodorov** [comment]
Thank you very much ☺
