### ISSUE TITLE
Is a CtModel serializable?

### ISSUE THREAD

**Issue by msteinbeck** [INRIA/spoon#1252]
I would like to serialize an entire CtModel. Is this, by default, possible?

**Comment by tdurieux** [comment]
Sorry I made a mistake on my mobile

**Comment by pvojtechovsky** [comment]
I never used that feature, but there is `SerializationModelStreamer` which should do what you need. It is tested here `SerializableTest#testSerializationModelStreamer'.
So it looks like it should be possible to serialize the spoon model

**Comment by surli** [comment]
@msteinbeck did you try the solution proposed by @pvojtechovsky ?

**Comment by msteinbeck** [comment]
Not yet but I'll close this issue for now. At least it looks like the infrastructure to serialize an entire model is available. If I encounter problems I'll create another issue addressing the concrete problem. Thank you so far.

**Comment by monperrus** [comment]
```java
Factory factory = launcher.getFactory();

ByteArrayOutputStream outstr = new ByteArrayOutputStream();

new SerializationModelStreamer().save(factory, outstr);

Factory loadedFactory = new SerializationModelStreamer().load(new ByteArrayInputStream(outstr.toByteArray()));
```
