### ISSUE TITLE
[generic type] Incorrect CtExecutableReference signature from CtInvocation when one of the arguments uses generic type

### ISSUE THREAD

**Issue by mrubato** [INRIA/spoon#1258]
The signature obtained the following way:

```
CtInvocation invocation = getInvocationFromModel();
String signature = invocation.getExecutable().getSignature();

```
is incorrect when one of the method arguments is a templated type AND is also a type not present in the known source paths (e.g., a type from some imported library).

For example, if we have the following method:

`void someMethod(SomeType<String> arg) {..}`

where SomeType is:

```
package externallib.types;

public interface SomeType<T> {
}

```
The resulting signature does not correctly indicate the fully-scoped (externallib.types.SomeType) name of SomeType. This appears to happen only when going through the CtInvocation, not when scanning for the CtMethod and then calling getSignature.

Note: In my configuration, setNoClasspath has been set to true. This occurs with 5.6.0.

**Comment by surli** [comment]
Hi @mrubato thanks for reporting!
Can you give some supplementary information: 

> The resulting signature does not correctly indicate the fully-scoped (externallib.types.SomeType) name of SomeType.

So what does it return then?

**Comment by mrubato** [comment]
@surli So if we have the following:

```
package com.myproject;

import externallib.SomeType;

public class MyClass {
    public void doSomething(SomeType<String> someType) {
    ....
    }
}

```
`invocation.getExecutable().getSIgnature() `

will return:

`com.myproject.MyClass#doSomething(com.myproject.SomeType)`

In other words, it appears to think SomeType is part of the same package as the method using it.

**Comment by monperrus** [comment]
thanks for the bug report!

**Comment by surli** [comment]
@mrubato you can now use spoon-core 5.7.0-SNAPSHOT, the fix will be included in the next release.

**Comment by mrubato** [comment]
@surli @monperrus Thanks guys! Nice turnaround!
