### ISSUE TITLE
IndexOutOfBoundsException when adding empty array in annotation value

### ISSUE THREAD

**Issue by marciodel** [INRIA/spoon#1264]
I'm trying to add an empty array to a annotation value. But a IndexOutOfBoundsException is thrown reporting invalid 0 index.

**Comment by surli** [comment]
Hi @marciodel thanks for reporting, could you give me the minimal snippet of code which throw the exception, and some information about the arguments you're using?

**Comment by marciodel** [comment]
I'm trying to use CtAnnotation.addValue like this: 

final CtAnnotation<JSBody> anno = this.getFactory().Annotation().annotate(element, JSBody.class).addValue("params", new String[0]);

When I use the statement below it works:

final CtAnnotation<JSBody> anno = this.getFactory().Annotation().annotate(element, JSBody.class).addValue("params", new String[]{"p1"});

I will try to add an CtExpression instead. Wich one should I use? CtNewArray, CtLiteral or CtCodeSnippetExpression? 

Thanks
