### ISSUE TITLE
[generic type] Regression in being able to spoon Guava

### ISSUE THREAD

**Issue by surli** [INRIA/spoon#1271]
It seems that #1218 introduced a regression on Guava project which is used by our CI to check the behaviour of Spoon, see the trace : 
<details>

> Cloning the remote Git repository
> Cloning repository https://github.com/spoon-bot/guava.git
> git init /builds/workspace/Guava # timeout=10
> Fetching upstream changes from https://github.com/spoon-bot/guava.git
> git --version # timeout=10
> git fetch --tags --progress https://github.com/spoon-bot/guava.git +refs/heads/*:refs/remotes/origin/*
> git config remote.origin.url https://github.com/spoon-bot/guava.git # timeout=10
> git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
> git config remote.origin.url https://github.com/spoon-bot/guava.git # timeout=10
> Fetching upstream changes from https://github.com/spoon-bot/guava.git
> git fetch --tags --progress https://github.com/spoon-bot/guava.git +refs/heads/*:refs/remotes/origin/*
> git rev-parse refs/remotes/origin/master^{commit} # timeout=10
> git rev-parse refs/remotes/origin/origin/master^{commit} # timeout=10
> Checking out Revision cc335985ccd19c6dd13087ca3c13c92e7793c36b (refs/remotes/origin/master)
> git config core.sparsecheckout # timeout=10
> git checkout -f cc335985ccd19c6dd13087ca3c13c92e7793c36b
> git rev-list cc335985ccd19c6dd13087ca3c13c92e7793c36b # timeout=10
> [Guava] $ /bin/sh -xe /tmp/hudson8643585831120465795.sh
> rm -rf /builds/.m2/repository/fr/inria/gforge/spoon
> [Guava] $ /bin/sh -xe /tmp/hudson1465629534996861412.sh
> [...]
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 1:21.906s
> [INFO] Finished at: Tue Apr 25 01:32:31 CEST 2017
> [INFO] Final Memory: 22M/644M
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal fr.inria.gforge.spoon:spoon-maven-plugin:2.4:generate (default) on project guava: Exception during the spoonify of the target project. spoon.SpoonException: Cannot resolve 1) type parameter <K>  of declarer @com.google.common.annotations.GwtIncompatible
> [ERROR] public abstract class ForwardingNavigableMap<K, V> extends com.google.common.collect.ForwardingSortedMap<K, V> implements java.util.NavigableMap<K, V> {
> [ERROR] protected ForwardingNavigableMap() {
> [ERROR] }
> [ERROR] 
> [ERROR] @java.lang.Override
> [ERROR] protected abstract java.util.NavigableMap<K, V> delegate();
> [ERROR] 
> [ERROR] @java.lang.Override
> [ERROR] public java.util.Map.Entry<K, V> lowerEntry(K key) {
> [ERROR] return delegate().lowerEntry(key);
> [ERROR] }
> [ERROR] 
> [ERROR] protected java.util.Map.Entry<K, V> standardLowerEntry(K key) {
> [ERROR] return headMap(key, false).lastEntry();
> [ERROR] }
> [ERROR] 
> [ERROR] @java.lang.Override
> [ERROR] public K lowerKey(K key) {
> [ERROR] return delegate().lowerKey(key);
> [ERROR] }
> [...]

</details>

See full stack trace:
https://ci.inria.fr/sos/job/Guava/262/console

**Comment by surli** [comment]
Hi @pvojtechovsky we think this might be linked to your PR #1218 could you have a look on it?

**Comment by pvojtechovsky** [comment]
I will check it.

**Comment by pvojtechovsky** [comment]
@monperrus  I can reproduce it in Spoon 7.1 only. It is not reproducible on master. I suggest to close this issue again.
