### ISSUE TITLE
*Factory.create() should be added to Factory.create$1

### ISSUE THREAD

**Issue by surli** [INRIA/spoon#1272]
We should put all create() method of different factories to Factory with a name like `createMethod` if `create` comes from MethodFactory. 

The SpoonArchitectureEnforcerRule test should be updated (see line 78).

**Comment by surli** [comment]
I think it's now done in `SpoonArchitectureEnforcerTest`. I close it.

**Comment by monperrus** [comment]
I don't think those missing factory methods have been added.

To which PR / commits do you refer to?

**Comment by surli** [comment]
I refer to this contract:
https://github.com/INRIA/spoon/blob/67269b1c9d5cf66f6e7edaba3c170f56d160b5bc/src/test/java/spoon/test/architecture/SpoonArchitectureEnforcerTest.java#L57

**Comment by monperrus** [comment]
Indeed. This issue is about removing `if (m.getSimpleName().equals("create")) continue;`
