### ISSUE TITLE
Add support for receiverParameter

### ISSUE THREAD

**Issue by surli** [INRIA/spoon#1283]
This kind of code is not properly managed by Spoon:

```java
public class TestSpoon {

    public void toto(@NonNull TestSpoon this) {
        System.out.println("AHAHAHAHAHAHA");
    }

    public static void main(String[] args) {
        TestSpoon spoon = new TestSpoon();
        spoon.toto();
    }
}
```

The method `toto` appeared in the model without any parameter. We should be able to find it inside the model as a standard parameter, specifically to manage annotations. 

bug found by @zhongxingyu

**Comment by monperrus** [comment]
From the JLS, "Method declaration", page 229-230

> The receiver parameter is an optional syntactic device for an instance method or an
> inner class's constructor. For an instance method, the receiver parameter represents
> the object for which the method is invoked. For an inner class's constructor, the
> receiver parameter represents the immediately enclosing instance of the newly
> constructed object. Either way, the receiver parameter exists solely to allow the
> type of the represented object to be denoted in source code, so that the type may
> be annotated. The receiver parameter is not a formal parameter; more precisely,
> it is not a declaration of any kind of variable (§4.12.3), it is never bound to any
> value passed as an argument in a method invocation expression or qualified class
> instance creation expression, and it has no effect whatsoever at run time.

**Comment by zhongxingyu** [comment]
It has no effect at run time, but an annotation processor may use the type annotation on receiver parameter to do some things such as type checking at compile time. 
Type Annotations Specification (JSR 308) has a more clear explanation on this.
