### ISSUE TITLE
feature: add support for sniper mode (only rewrites the changed nodes)

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#1284]
see ROADMAP

**Comment by monperrus** [comment]
depends on #1168

**Comment by monperrus** [comment]
useful for repairnator and co

**Comment by tdurieux** [comment]
see #1358

**Comment by monperrus** [comment]
closed per #1927

**Comment by monperrus** [comment]
FYI:
An Algorithm for Layout Preservation in Refactoring Transformations
https://link.springer.com/chapter/10.1007/978-3-642-28830-2_3

**Comment by monperrus** [comment]
More papers on high-fidelity / layout preserving code transformation:

High-fidelity C/C++ code transformation (2017)
https://www.sciencedirect.com/science/article/pii/S0167642307000718/pdf

Detaching and reconstructing the documentary structure of source code (2010)
https://www.researchgate.net/profile/Gabor_Kusper/publication/284888833_ICAI2010-volume2/links/5659ad0408aeafc2aac4c23a/ICAI2010-volume2.pdf#page=401

Layout preserving parser for refactoring in Erlang (2009)
https://pdfs.semanticscholar.org/8487/eeda4c867e8f7cd13d83391488b2abec4a39.pdf

revcpp: A reversible c++ preprocessor (2015)
https://www.lrde.epita.fr/~sigoure/revcpp.pdf

Scrap you reprinter (2017)
https://www.cs.kent.ac.uk/people/staff/dao7/publ/reprinter2017.pdf

**Comment by monperrus** [comment]
Transformation tools with high-fidelity / layout preserving features:

* [ASF+SDF](http://www.meta-environment.org/), superseeded by [Rascal (generic)](https://github.com/usethesource/rascal)
* [StrategoXT (generic)](https://github.com/metaborg/strategoxt)
* [Cscout (for C)](https://github.com/dspinellis/cscout)
* [HaRe (for Haskell)](https://github.com/alanz/HaRe)
* Clair for C++

**Comment by jurgenvinju** [comment]
* [Clair](https://github.com/cwi-swat/clair) is based on Rascal, provides concrete syntax matching for an external C++ parser
* Clair-related paper: concrete syntax with black box parsers: https://homepages.cwi.nl/~jurgenv/papers/Programming-2019.pdf

Relevant papers:
* Term Rewriting with Layout: https://homepages.cwi.nl/~jurgenv/papers/RULE-2000.pdf
* "First Class Layout" chapter in https://homepages.cwi.nl/~jurgenv/papers/thesis-2005.pdf

**Comment by jurgenvinju** [comment]
the paper which coined the term "hifi" transformation for "no loss of layout and source code comments":

"High Fidelity C/C++ Code Transformation" by Daniel Waddington and Bin Yao https://www.researchgate.net/publication/222998573_High-Fidelity_CC_Code_Transformation

**Comment by monperrus** [comment]
FYI, JavaParser calls this feature "lexical preservation", see @ftomassetti's post
https://tomassetti.me/lexical-preservation-javaparser/

**Comment by jlundhol** [comment]
This paper by Rodin T. A. Aarssen and Tijs van der Storm suggesting "Separator Syntax Trees" might be of interest:

High-fidelity metaprogramming with separator syntax trees (2020)
https://dl.acm.org/doi/abs/10.1145/3372884.3373162
