### ISSUE TITLE
getQualifiedName returns simple name when analysing a single file (sometimes)

### ISSUE THREAD

**Issue by mduruisseau** [INRIA/spoon#1293]
Hello, 

I have two classes "TransporteurFragment" and "CompletableFragment". Both of them are in the same package.
TransporteurFragment extends CompletableFragment, and CompletableFragment is an abstract class extending Fragment (from Android) and containing one abstract method.

If I scan the entire project folder, and do element.getSuperclass().getQualifiedName(), where element is the CtClass corresponding to TransporteurFragment, it returns the correct QualifiedName (x.y.z.CompletableFragment). 
However, if I scan only the TransporteurFragment file, it returns "CompletableFragment". 

At first I though it was not a bug and only a consequence of scanning a single file, but then I though about the imports that indicates where the used classes are from, and the fact that it works for other files ...

I tried to reproduce this, with basic Java files but I don't know why, it works ... 
I have however detected that if CompletableFragment is in a different package than TransporteurFragment, even when scanning only TransporteurFragment.java, it returns the correct QualifiedName, which let me think that maybe there is a real issue ;)

I hope I was clear enough, if not, I can share you the files that cause me problems !

(I use v5.6.0 of Spoon, from Maven)

**Comment by surli** [comment]
Hi @mduruisseau 

>I hope I was clear enough, if not, I can share you the files that cause me problems !

you're clear but if you can share the file to reproduce the bugs it would be extremely helpful to help you on this one :)

And just in case could you try with 5.7.0-SNAPSHOT?

**Comment by mduruisseau** [comment]
Hi !

I have tested with 5.7.0-SNAPSHOT but I got the same result. With a lot of `11:19:54.402 spoon.Launcher - java.lang.ClassCastException` in the logs, but the analysis still works.

I attach the two files that are concerned by my issue as a zip (GitHub doesn't like Java files)

[issue_1293_files.zip](https://github.com/INRIA/spoon/files/992492/issue_1293_files.zip)

**Comment by surli** [comment]
Hi @mduruisseau thanks for the files. Do you use Spoon in `noClassPath` mode?

**Comment by mduruisseau** [comment]
Hi @surli 

Yes, I use Spoon in `noClassPath` mode.
I tried without this option:
`Exception in thread "Thread-60" spoon.compiler.ModelBuildingException: CompletableFragment cannot be resolved to a type at [...]\TransporteurFragment.java:18
`

**Comment by surli** [comment]
> Yes, I use Spoon in noClassPath mode.

Ok so the bug makes sense: as you only specify the class `TransporteurFragment` as input resource, Spoon does not know the other class `CompletableFragments` and as it has no import information, it considers this type has no package, where it should consider it's in the same package as the current class. 
I will fix that soon.
