### ISSUE TITLE
Two links swapped in documentation page for homepage

### ISSUE THREAD

**Issue by efung** [INRIA/spoon#1294]
On this page, `doc/doc_homepage.md`

The two links for analyze and transform are swapped:

``` enables you to transform (see [example](/first_analysis_processor.html)) and analyze Java source code (see [example](/first_transformation.html))```

should be

``` enables you to transform (see [example](/first_transformation.html)) and analyze Java source code (see [example](/first_analysis_processor.html))```

**Comment by monperrus** [comment]
thanks! would you create a pull request (https://github.com/INRIA/spoon/edit/master/doc/doc_homepage.md)?
