### ISSUE TITLE
Exception at compilation due to a constructor with private visibility

### ISSUE THREAD

**Issue by orichalque** [INRIA/spoon#1306]
Hello,

I'm having an issue while instrumenting the source code of [AssertJ](https://github.com/joel-costigliola/assertj-core) with Spoon. 
The instrumentation part will work, but the compilation part will fail due to the following error:
```
spoon.compiler.ModelBuildingException: The constructor BooleanArrays() is not visible at C:\Users\...\eclipse\BooleanArraysBaseTest.java:44
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.report(JDTBasedSpoonCompiler.java:578)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.reportProblems(JDTBasedSpoonCompiler.java:559)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.compile(JDTBasedSpoonCompiler.java:158)
	at spoon.Launcher.run(Launcher.java:658)
```

I created a small Maven project with the part of the AssertJ source code that I cannot instrument/compile with Spoon. 

The project architecture is the following: 

```
TheProject
|
|
|__ pom.xml
|
|
\__ src
        |
        |
        \__ main
        :       |
        :       |
        :       \__ java
        :               |
        :               |
        :               \__ internal
        :                       |
        :                       |
        :                       |__ BooleanArrays.java
        :                       |
        :                       |
        :                       |__ Failures.java
        |
        |
        \__ test
                |
                |
                \__ java
                        |
                        |
                        \__ internal
                        :       |
                        :       |
                        :       |__ BooleanArraysBaseTest.java
                        |
                        |
                        \__ test
                                |
                                |
                                |__ BooleanArrays.java
```

According to the Exception message, the problems comes from the class `BooleanArraysBaseTest`, which contains the following code: 

```
public class BooleanArraysBaseTest {

  protected boolean[] actual;
  protected Failures failures;
  protected BooleanArrays arrays;

  @Before
  public void setUp() {
    actual = test.BooleanArrays.arrayOf(true, false);
    failures = spy(new Failures());
    arrays = new BooleanArrays();
    arrays.failures = failures;
  }
}
```

The statement `arrays = new BooleanArrays();` refers to the BooleanArrays class contained in the same package ('internal'), which is a Singleton, having a constructor with the package visibility: 

```
  @VisibleForTesting
  BooleanArrays() {
  }
```

The other class also called `BooleanArrays`, but contained in the other package ('test') has a private constructor. 
 
My Launcher configuration is the following:
```
launcher.getEnvironment().setShouldCompile(true);
launcher.getEnvironment().setAutoImports(true);
launcher.getEnvironment().setNoClasspath(false);		

launcher.getEnvironment().setSourceClasspath(/* an array with jars */);		

launcher.addInputResource(/* src/main/java folder*/);
launcher.addInputResource(/* src/test/java folder */);

launcher.setBinaryOutputDirectory(/* a folder in the project spooned*/); 
launcher.setSourceOutputDirectory(/* an other folder in the project spooned*/);

launcher.addProcessor(/* a processor */);
launcher.run()

```

Is there something wrong with my configuration ? I managed to instrument several other projects, but not this one.
Tell me if you need any other information.

An archive containing this project is available [here](http://ovh.to/tq4oPt9).

Thank you,

Thibault

**Comment by surli** [comment]
Hi @orichalque I'm trying to reproduce your bugs, which version of Spoon did you try?

**Comment by orichalque** [comment]
Hi, I'm using the 5.6.0

**Comment by surli** [comment]
Ok, I don't manage to reproduce your bug in a simple test case right now. Could you try with version 5.7.0 and also try to remove the annotation on the constructor of `BooleanArrays`, just to check if it's related or not.

**Comment by surli** [comment]
I just saw that your error message show a weird path: 
>The constructor BooleanArrays() is not visible at **C:\Users\...\eclipse\BooleanArraysBaseTest.java**

It should be in **internal** directory at least, no?

**Comment by orichalque** [comment]
I'm going to try using Spoon 5.7.0.
And the path is weird indeed, since it is the root folder of my eclipse.

I'm launching the spoon instrumentation from an Eclipse Plugin, it this is of any help.

**Comment by surli** [comment]
> I'm launching the spoon instrumentation from an Eclipse Plugin, it this is of any help.

Do you know if the eclipse plugin you're using move the files before launching Spoon? Because it looks like the hierarchy of your Java file is wrong, leading to the error.

**Comment by orichalque** [comment]
I'm doing multiple operations before instrumenting the source code, including reverse-engineering, with the MoDisco framework, and Model Transformations. But, as far as I know, I'm not moving any files or folder. 

Nonetheless I managed to instrument several other projects with Spoon, using the same configuration.
I'll try to reproduce the error using only Spoon on the project I shared in my first message.

**Comment by orichalque** [comment]
I wrote a quick Eclipse plugin launching a Spoon instrumentation available [here ](https://github.com/orichalque/SpoonPlugin/blob/master/src/spooneclipseplugin/instrumenter/SpoonInstrumenter.java)

When running it on the project sample I presented earlier, I have the exact same error, still with the following exception: 
```
Caused by: spoon.compiler.ModelBuildingException: The constructor BooleanArrays() is not visible at C:\Users\user\eclipse\modeling-neon\eclipse\BooleanArraysBaseTest.java:23
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.report(JDTBasedSpoonCompiler.java:580)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.reportProblems(JDTBasedSpoonCompiler.java:561)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.compile(JDTBasedSpoonCompiler.java:158)
	at spoon.Launcher.run(Launcher.java:658)
	at spooneclipseplugin.instrumenter.SpoonInstrumenter.instrument(Unknown Source)
```
The same error happens when removing the  `@VisibleForTesting` annotation.

**Comment by orichalque** [comment]
However I noticed than when changing the visibility of the `test.BooleanArrays` constructor to public, the exception doesn't happen anymore. Which is strange, because only the `internal.BooleanArrays` constructor is called.

**Comment by surli** [comment]
> I wrote a quick Eclipse plugin launching a Spoon instrumentation available here

I don't manage to run the plugin, apparently it requires that a "lib" directory to be present in the sample project? 

> However I noticed than when changing the visibility of the test.BooleanArrays constructor to public, the exception doesn't happen anymore. Which is strange, because only the internal.BooleanArrays constructor is called.

It really looks like your plugin somehow messed up the project between `test.BooleanArrays` and `internal.BooleanArrays`. Did you try to reproduce the error in command line?

**Comment by surli** [comment]
So, I finally managed to run your plugin in debug, and indeed the problem is not located in `internal.BooleanArrays` but in `test.BooleanArrays` I'm not sure yet, where the problem comes from, but it may be related to the use of JDT. 
At least I can reproduce it, so I will investigate.

**Comment by orichalque** [comment]
> I don't manage to run the plugin, apparently it requires that a "lib" directory to be present in the sample project?

Indeed, I put all the jar in a single /lib/ folder, for the `setSourceClasspath(/* an array with jars */);`, since I have no quick way to get all the jar from Maven. 
I forgot to give you the [link ](http://ovh.to/npHYwdK)of the project with the lib folder.

I'll try to run the plugin using command line as soon as possible. Since now I only ran Spoon programmatically.

Thank you for your help
