### ISSUE TITLE
spoon 1.5 disappeared from Maven central

### ISSUE THREAD

**Issue by ocean7** [INRIA/spoon#133]
Once upon a time spoon 1.5 was in maven central and all was well. At some point, Spoon 1.5 simply vanished. And

```
<dependency>
	<groupId>fr.inria.gforge.spoon</groupId>
	<artifactId>spoon-core</artifactId>
	<version>1.5</version>
</dependency>
```

No longer worked and all builds broke. Why did this happen? Is Maven Central running out of space? Why ever delete artifacts that have been exposed to the public?

This is especially problematic since later versions of spoon (2.4, 3.0) contain some significant issues around annotation processing (see https://github.com/INRIA/spoon/issues/132, https://github.com/INRIA/spoon/issues/60). Spoon 1.5 did not have these issues I think because, well, all our stuff used to work and now it doesn't.

I wonder if it might be possible to redeploy spoon 1.5 to maven central? It'd be much appreciated.

(Spoon is amazing btw. Please don't take this issue as a complaint, we'd like to upgrade at some point but not until the annotation issues have been resolved.)

**Comment by monperrus** [comment]
Hi,

Spoon lives in a multiverse. Between 1.4 and 2.31, Spoon was not put in Maven Central, but on a specific server (see below). 

So, it seems you lived in the parallel universe for some time. You can still jump in:

```
    <dependencies>
		<dependency>
			<groupId>fr.inria.gforge.spoon</groupId>
			<artifactId>spoon-core</artifactId>
			<version>1.5</version>
		</dependency>
	</dependencies>
	<repositories>
		<repository>
			<id>gforge.inria.fr-release</id>
			<name>Maven Repository for Spoon</name>
			<url>http://spoon.gforge.inria.fr/repositories/releases/</url>
			<releases />
		</repository>
	</repositories>
```
(but repositories/releases/ disappeared for some weeks, we made a mistake on spoon.gforge.inria.fr, sorry for this)
