### ISSUE TITLE
feature: CtPackageReference should have a getQualifiedName in addition to getSimpleName

### ISSUE THREAD

**Issue by surli** [INRIA/spoon#1330]

**Comment by surli** [comment]
Looking on this feature request: shouldn't we put `getQualifiedName` directly in `CtReference` ?

**Comment by surli** [comment]
I answer myself: it's a bad idea. We got a lot of different references for which it makes no sense to have a FQN.

**Comment by monperrus** [comment]
I agree with you, it's a bad idea :-)

**Comment by surli** [comment]
In fact CtPackageReference already reference the FQN of package in its simpleName, see:
https://github.com/INRIA/spoon/blob/bf1233aa362c1d23030c0d491e8de15eacf12276/src/main/java/spoon/reflect/factory/PackageFactory.java#L52

So, should we align its behaviour on the class behaviour: simpleName with only the last package simple name, and a FQN computed from it. 
Or it does not make any sense to use simpleName in CtPackageReference, and we should only document the fact the FQN is always returned and close this issue?

**Comment by monperrus** [comment]
If this line is always used and we are sure that simple name is always the fully qualified name,
then 1) we document 2) we still add the new method for improving the API, that would simply delegate
to getSimpleName

**Comment by surli** [comment]
> If this line is always used

Yes, a PackageReference is always created using a FQN name, either from the CtPackage FQN or from a reflect Package FQN. 

> 1) we document 2) we still add the new method for improving the API, that would simply delegate to getSimpleName

I'll change the PR and test in that way then.
