### ISSUE TITLE
Bug in annotation value access

### ISSUE THREAD

**Issue by petitpre** [INRIA/spoon#137]
There are 2 ways to annotate an element with an array parameter:
	@AnnotArray({ RuntimeException.class })
	public void testValueWithArray() ;
	@AnnotArray(RuntimeException.class)
	public void testValueWithoutArray() ;

When I try to access to the annotation parameter with spoon with something like:
myCtMethod.getAnnotation(AnnotArray.class).value()

It work only with the first method example. The second fail with exception:
java.lang.ClassCastException: java.lang.Class cannot be cast to [Ljava.lang.Class;
	at com.sun.proxy.$Proxy3.value(Unknown Source)

I've write a test that surround this bug:
https://github.com/petitpre/spoon/blob/bugValues/src/test/java/spoon/test/annotation/AnnotationTest.java#L345

**Comment by boeserwolf91** [comment]
Seems to be a duplication of #132
