### ISSUE TITLE
handling non-java resources 

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#138]
as the default Java compiler does, I propose that Spoon copies all non-Java files that are in the source folder to the output folder.

doing so, one can safely compile the output folder.

**Comment by seintur** [comment]
+1

**Comment by boeserwolf91** [comment]
+1 I guess that makes sense.

**Comment by GerardPaligot** [comment]
Recently, I thought about this issue and my conclusion is that this shouldn't be integrate in Spoon because Spoon doesn't compile source code generated but we can integrate this feature in plugins which launches spoon.

What do you think about this?

**Comment by pschichtel** [comment]
this is a little late, but I wouldn't do this. I agress with @GerardPaligot 
Spoon doesn't compile. Compilation-related projects should add this in if necessary.
