### ISSUE TITLE
refactor: Xxx#replace(...) are too numerous

### ISSUE THREAD

**Issue by pvojtechovsky** [INRIA/spoon#1385]
For example there is 
`CtBlock#replace(CtBlock block)`
but the correct is 
`<S extends CtStatement> CtStatement#replace(S statement)`, because each block (or any statement) can be replaced by any CtStatement or instance of subclass of CtStatement.

But for example CtInvocation can be replaced by CtStatement or CtExpression depending on the context where this invocation is used ...

WDYT? Are the Xxx#replace(...) methods defined correctly?
It is not actually a problem for me. I just spotted it, while thinking about refactoring of SubstitutionVisitor

**Comment by tdurieux** [comment]
Your are right.
It is strange because I never had issue when I used this method

**Comment by surli** [comment]
Actually in CtBlock you inherit from the method `CtStatement#replace(CtStatement element)` so it should be ok, no?

**Comment by pvojtechovsky** [comment]
![image](https://user-images.githubusercontent.com/23107345/31949074-b82867ce-b8d8-11e7-932e-835759c66963.png)

The method replace is implemented more times. With different signatures. This issue is only a question whether it makes sense or we can simply delete all of them and keep only CtElement#replace(CtElement) - to have it KISS

**Comment by surli** [comment]
Indeed. I'll propose a PR in that way.

**Comment by pvojtechovsky** [comment]
May be the idea was to restrict correct replacements. For example CtBlock can be replaced by any Statmenet, but should not be replaced by Expression. But I guess it is hard to express all these rules into API of spoon model. So i vote for remove of all clones of `replace` too.

**Comment by surli** [comment]
> For example CtBlock can be replaced by any Statmenet, but should not be replaced by Expression.

Yes, I was thinking about that. Do you know what's the current behaviour when you try to replace a CtBlock with a CtExpression? Spoon throws an exception?

**Comment by pvojtechovsky** [comment]
I do not know. I did not tried that.
