### ISSUE TITLE
Using Maven pom.xml to build model

### ISSUE THREAD

**Issue by msteinbeck** [INRIA/spoon#1396]
Is it possible to create a Spoon model from a single pom.xml? Since the pom contains all dependencies, it should be possible to create a model without noclasspath mode. This feature is not limited to Maven, but could also be added for Ant, Gradle, and even Eclipse project files.

**Comment by surli** [comment]
Just to clarify: you mean to be able to launch Spoon in specifying only a targeted pom.xml and to let Spoon analyze the file and create the model from sources, using the proper dependencies? 

I like the idea, but I'm not sure if it should be integrated to spoon-core, or if it should be another project which can analyze the pom.xml and then call Spoon with the proper arguments...

**Comment by msteinbeck** [comment]
> Just to clarify: you mean to be able to launch Spoon in specifying only a targeted pom.xml and to let Spoon analyze the file and create the model from sources, using the proper dependencies?

Let me put it in other words: Java

```java
Launcher launcher = new Launcher();
launcher.addInputResource("./pom.xml");
launcher.buildModel();
CtModel completeModel = launcher.getModel();
```

So yes, I would like to add only a pom.xml and create a complete model out of it.

> I like the idea, but I'm not sure if it should be integrated to spoon-core, or if it should be another project which can analyze the pom.xml and then call Spoon with the proper arguments...

Why would you like to put this feature into another project? Spoon is all about creating models from Java source code, isn't it :). With a little bit of luck, there already is a Maven parser.

**Comment by surli** [comment]
> Why would you like to put this feature into another project? Spoon is all about creating models from Java source code, isn't it :). 

Actually I was thinking about spoon-maven-plugin which is another project, so do we want to include this feature inside spoon-core, or not. Yes, we could do as you propose but maybe it would be better to explicit the fact the pom.xml input resource will impact the classpath and so one. 

So maybe something like this would be better, WDYT?

```
Launcher launcher = new Launcher();
launcher.setPomProject("./pom.xml");
launcher.buildModel();
CtModel completeModel = launcher.getModel();
```

> With a little bit of luck, there already is a Maven parser.

See: http://maven.apache.org/components/ref/3.2.5/maven-model/

**Comment by pvojtechovsky** [comment]
I vote to put it into another project too. Otherwise the spoon core needs a dependency to
* maven project parser
* to libraries which can download dependencies from maven repository ...

**Comment by surli** [comment]
> Otherwise the spoon core needs a dependency to
> - maven project parser
> - to libraries which can download dependencies from maven repository ...

I assume you don't want those dependencies because of the size of the libraries to add. So as a check I tested to package spoon with and without the new dependency for Maven model resolver, here are the results:

```
Kwak-Spirals:spoon urli$ du -k target/spoon-core-5.8.0-SNAPSHOT-jar-with-dependencies.jar 
7264	target/spoon-core-5.8.0-SNAPSHOT-jar-with-dependencies.jar
Kwak-Spirals:spoon urli$ du -k target/spoon-core-5.8.0-SNAPSHOT-jar-with-dependencies.jar 
10112	target/spoon-core-5.8.0-SNAPSHOT-jar-with-dependencies.jar
```

So around 3 Mb more with the new dependency.

**Comment by msteinbeck** [comment]
> So around 3 Mb more with the new dependency.

To be honest, that's nothing much compared to JDT (5.6M). Furthermore, the libraries used to download dependencies from Maven repositories can be reused for a potential Gradle parser.

**Comment by surli** [comment]
> To be honest, that's nothing much compared to JDT (5.6M).

I tend to agree: i'm not sure it's a real issue to add 3 Mb to the full jar. WDYT @pvojtechovsky @monperrus ?

**Comment by monperrus** [comment]
I'm in favor of this proposal because: 

1. the main goal of Spoon is to create models of Java source code
2. it is fully backward compatible
3. the memory overhead is acceptable

**Comment by pvojtechovsky** [comment]
I personally do not need this feature and if you want it in spoon core, then I really have no problem with that ;-)
