### ISSUE TITLE
February release

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#141]
Hi all,

The February release (v3.1, bug fix) is planned for February 9.

--Martin

**Comment by GerardPaligot** [comment]
Hi,

Spoon v 3.1 has been released!

Changelog:

- [documentation] Adds a note about the management of old issues and PRs.
- [feature] Copies all resources files from source to destination folder.
- [feature] Gives a numeric name at a anonymous class.
- [bug fix] Fixes annotations when there contains arrays.
- [bug fix] Fixes the method getActualMethod in CtExecutableReferenceImpl .
- [bug fix] Fixes a wrong classpath which was added to the argument.

[Maven Central](http://search.maven.org/#artifactdetails%7Cfr.inria.gforge.spoon%7Cspoon-core%7C3.1%7Cjar):

```xml
<dependency>
    <groupId>fr.inria.gforge.spoon</groupId>
    <artifactId>spoon-core</artifactId>
    <version>3.1</version>
</dependency>
```

So, we can close this issue!

**Comment by tdurieux** [comment]
Hi,

Why this version is not available in the Github releases page: https://github.com/INRIA/spoon/releases ?

[feature] Copies all resources files from source to destination folder. => Thanks

**Comment by monperrus** [comment]
added in the in the Github releases page
