### ISSUE TITLE
chore: spoon-bot should  delete old Revapi reports

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#1426]
spoon-bot should post a Revapi comment only if the computed API change are different from the last post.

Possible implementation, in `revapy.py`, use the Github API to go over the list of comments to the PR and compare them against the newly computed one.

**Comment by monperrus** [comment]
@surli would you have a look at this one?

**Comment by pvojtechovsky** [comment]
How it should behave when 
1st commit has a revapi changes
2nd later commit fixes compatibility problems and there is NO revapi change

In such case there will stay old confusing revapi report.

Idea: 
1) each CI run should always delete old revapi changes 
2) and generate new one if ther is a revapi change - same like now - or add nothing if there is no change.

**Comment by surli** [comment]
The solution proposed in #1683 is not working
