### ISSUE TITLE
bug: CtBodyHolder, CTRHSReceiver and CtShadowable are not CtInheritanceScan-ABLE

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#1430]
See pb with CtBodyHolder, CTRHSReceiver and CtShadowable

one can check this contract in a new architectural test

**Comment by monperrus** [comment]
>  That every CtElement should be CtInheritanceScan-ABLE?

Yes, every abstract non-leaf CtElement should be CtInheritanceScan-ABLE

**Comment by surli** [comment]
>  every abstract non-leaf CtElement should be CtInheritanceScan-ABLE

Ok for CtBodyHolder but CtRHSReceiver and CtShadowable do not inherit from CtElement right now.

**Comment by pvojtechovsky** [comment]
In case of CtBodyHolder it is not intentional. So I am ok with adding inheritance from CtElement.
And for others probably too.
