### ISSUE TITLE
Find Unused codes or DeadCodes using Spoon Metamodel

### ISSUE THREAD

**Issue by sourabhsparkala** [INRIA/spoon#1431]
Find unnecessary (dead) public java code. For example public classes, methods or fields which have no references. 

I want to know if it is possible to use Spoon static analysis to find these dead codes in the source code. Could I get a starting point or an example snippet to understand, how to accomplish this?

Regards

**Comment by surli** [comment]
Hi @sourabhsparkala !

Yes it's completely feasible with Spoon and even not so difficult :) 
Here's an example of what you can do using Spoon API:

```java
// first, we create the AST model of your source code with Spoon
Launcher launcher = new Launcher(); 
launcher.addInputResources(...); // here you specify the source code you want to analyze
launcher.getEnvironment().setSourceClasspath(...); // specify the classpath of your source code
launcher.buildModel();
CtModel model = launcher.getModel();

// then we analyze dead methods
List<CtMethod> methods = model.getElements(new TypeFilter<>(CtMethod.class)); // get all methods
List<CtExecutableReference> executableReferences = model.getElements(new TypeFilter<>(CtExecutableReference.class)); // get all references for executables

for (CtExecutableReference execReference : executableReferences) {
	CtExecutable declaration = execReference.getExecutableDeclaration(); // we look for the declaration of the reference
	if (declaration != null && declaration instanceof CtMethod) { // if it's a method
		CtMethod methodOfExec = (CtMethod)declaration;
		for (CtMethod method : new ArrayList<>(methods)) { // we look for it in the list of methods (we copy it to be able to remove from the original list)
			if (method.equals(methodOfExec)) {
				methods.remove(method); // and we can remove it
				break;
			}
		}
	}
}

if (methods.isEmpty()) {
	System.out.printf("There is no dead code from methods!");
} else {
	for (CtMethod method : methods) {
		System.out.printf("The following method seems unused: "+method.getSimpleName());
	}
}
```

The code for dead fields should be almost identical, except you should use `CtField` and `CtFieldReference` instead of `CtMethod` and `CtExecutableReference`.

**Comment by msteinbeck** [comment]
We implemented this using Spoon and it works fine. You need to consider some special cases, though. For instance, classes implementing an interface may not be used directly, but may be used through dynamic dispatching. For example:

```
A a = new B();
a.doSomething();
```

If `B` is overriding `doSomething()`, it is not referenced directly, but wouldn't be considered unused, right?

**Comment by sourabhsparkala** [comment]
Thank you so much. This really helped a lot....

Regards
Sourabh

**Comment by pavanspoon** [comment]
Hi Surli,

How can we get the method references using spoon api. Can you help on this .

**Comment by pavanspoon** [comment]
What I mean from which class the method is invoking .
