### ISSUE TITLE
question: what's the semantic difference between ClassTypingContext#isSubSignature and ClassTypingContext#isOverriding?

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#1438]
@pvojtechovsky ?

**Comment by pvojtechovsky** [comment]
See [http://docs.oracle.com/javase/specs/jls/se7/html/jls-8.html#jls-8.4.2](http://docs.oracle.com/javase/specs/jls/se7/html/jls-8.html#jls-8.4.2) I took these terms from that specification and implemented it like that.

**Comment by monperrus** [comment]
Thanks for the pointer.

"Two method signatures m1 and m2 are override-equivalent iff either m1 is a subsignature of m2 or m2 is a subsignature of m1. "

We have to improve the javadoc accordingly.

**Comment by surli** [comment]
So, wrt this pointer `isOverriding` should check `isSubsignature` with argument in order m1, m2 and in order m2, m1. Right?

**Comment by pvojtechovsky** [comment]
I think check in one direction is OK, because in out case we know which method comes from superClass and which subClass

**Comment by surli** [comment]
Ok, in fact the overriding definition is in http://docs.oracle.com/javase/specs/jls/se7/html/jls-8.html#jls-8.4.8.1. I'll change my PR.
