### ISSUE TITLE
Spoon receives the 2017 OW2 Community Award 

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#1456]
We're pleased to announce that Spoon has received the 2017 OW2 Community Award.

**Kudos to our awesome community!**  :beers: :beers: :sparkles:.

OW2 is one of the leading European open-source organizations (à la Apache).

More information at https://www.ow2con.org/bin/view/2017/Awards_Results?year=2017&event=OW2con17

Benjamin Danglot (@danglotb) was there to receive the award, from OW2 CEO Cédric Thomas ([@cedricth](https://twitter.com/cedricth)).
<img src="https://www.ow2con.org/bin/download/2017/Awards_Results/OW2con17-winners-Awards-Spoon">

**Comment by surli** [comment]
The presentation of Spoon @ OW2Conf'17 is available on YouTube: 
https://youtu.be/JcCIbjnkfD4

Thanks @danglotb for the talk 👍
