### ISSUE TITLE
[Question] spoon.SpoonException: The template xxx is not part of model. Add template sources to spoon template path.

### ISSUE THREAD

**Issue by tokazio** [INRIA/spoon#1459]
How to add template sources to spoon template path for my maven project please ?

**Comment by surli** [comment]
Hi @tokazio 

> How to add template sources to spoon template path for my maven project please ?

I'm not sure to fully understand your question. You can use template through Spoon API like this:

```java

Launcher spoon = new Launcher();
launcher.addInputResource("/path/to/sources");
launcher.addTemplateResource(new FileSystemFile("/path/to/MonTpl.java"));
launcher.buildModel();
MonTpl monTemplate = new MonTpl();

// get element from launcher.getModel()
monTemplate.apply(....) // apply template to an element
```

Does it answer your question?

**Comment by tdurieux** [comment]
I think it is related to the maven plugin

**Comment by surli** [comment]
Ping @tokazio ?

**Comment by surli** [comment]
I close this ticket for now, don't hesitate to reopen it if needed
