### ISSUE TITLE
bug: Comments are probably not parsed well on Mac

### ISSUE THREAD

**Issue by pvojtechovsky** [INRIA/spoon#1460]
`JDTCommentBuilder#cleanComment` method splits lines by Linux `\n`
```java
String[] lines = comment.split("\n");
```
and then cleans up remaining MS Windows `\r`. I guess that this algorithm will not work on Mac, which uses `\r` as EOL.

The handling of EOL in spoon seems to be not consistent. May be the best would be to 
1) preprocess all parsed java source file and to normalize EOL from `\r\n` and `\r` to Linux `\n`
2) then all internal algorithms in spoon can be easier and may expect that EOL is always `\n`
3) to configure what EOL is used when pretty printing

WDYT?

I am not not going to develop anything here. I just noted that it should be handled somehow during #1455, which is hard for me to test, because I am not able to say what behavior is correct concerning EOL... and Spoon. 

Are there already some rules how EOLs should be handled by Spoon?

**Comment by pvojtechovsky** [comment]
I have checked current implementation and `CtComment#getContent()` [already separates lines by constant](https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/support/compiler/jdt/JDTCommentBuilder.java#L552) "\n" - independent on OS.

So the remaining problem is to fix [bug](https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/support/compiler/jdt/JDTCommentBuilder.java#L536) in comments handling on Mac OS, which are using "\r"

**Comment by surli** [comment]
> So the remaining problem is to fix bug in comments handling on Mac OS, which are using "\r"

Actually "\r" was used on older version of MacOS (9 and below): I'm using Mac and `System.getProperty("line.separator")` returns "\n".

I tried to create a new test in #1679 and it seems to return the documentation correctly.
