### ISSUE TITLE
CtScanner: visit  method for the top element of scanned (Sub)-AST

### ISSUE THREAD

**Issue by msteinbeck** [INRIA/spoon#1466]
I would like to have a visit method in CtScanner that allows me to visit the top element of the scanned (sub)-ast. That is, If I scan the root package of my AST, the method gets called once for this package. If, on the other hand, I scan a sub node, this method gets called once for this element.

**Comment by surli** [comment]
I'm not sure to fully understand what you want here: you want to be able to visit ONLY the top element of an AST, so let say your AST is constituted bye a package, with a class inside it will only visit the package? 

Or do you want to visit each node of an AST, which is already the behavior of CtScanner... I'm missing something here, could you provide an example?

**Comment by surli** [comment]
ping @msteinbeck any more information on this issue?

**Comment by monperrus** [comment]
[Issue Cleaning Marathon] No more activity here, closing the issue, and of course we can continue the discussion when something new happens.
