### ISSUE TITLE
bug: FilterTest#testClassCastExceptionOnForEach seems to fail on CI

### ISSUE THREAD

**Issue by surli** [INRIA/spoon#1467]
See: https://ci.inria.fr/sos/job/Spoon%20Install%20Commit%20Hook/224/console

> Tests run: 40, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 4.194 sec <<< FAILURE! - in spoon.test.filters.FilterTest
testClassCastExceptionOnForEach(spoon.test.filters.FilterTest)  Time elapsed: 0.109 sec  <<< ERROR!
spoon.SpoonException: Execution of query callback failed
	at spoon.test.filters.FilterTest.testClassCastExceptionOnForEach(FilterTest.java:884)
Caused by: java.lang.ClassCastException: spoon.reflect.CtModelImpl$CtRootPackage cannot be cast to spoon.reflect.declaration.CtType
	at spoon.test.filters.FilterTest.testClassCastExceptionOnForEach(FilterTest.java:884)

**Comment by surli** [comment]
This bug seems to occur with a specific version of JDK, I manage to reproduce it with Oracle JDK 8.0.40: https://ci.inria.fr/sos/job/Spoon%20Install%20Commit%20Hook/229/consoleFull

The last version of JDK 8 seems to fix the bug, which is why we did not see the bug with Travis: https://ci.inria.fr/sos/job/Spoon%20Install%20Commit%20Hook/226/consoleFull

**Comment by nharrand** [comment]
On travis it occurs with both openjdk11 and oracle jdk11.
See https://travis-ci.org/INRIA/spoon/jobs/459858096
It might be worth reopening this issue.
