### ISSUE TITLE
branches: why is there a stable branch?

### ISSUE THREAD

**Issue by surli** [INRIA/spoon#1473]
As the master branch is always stable, especially because we are always using PR, why is there still a branch called "stable"?

**Comment by monperrus** [comment]
for historical reasons. I'm OK to remove it.

**Comment by surli** [comment]
> I'm OK to remove it.

Let's do that then.

**Comment by surli** [comment]
Except it's currently protected so I can't do it :-)

**Comment by monperrus** [comment]
not protected anymore :-)
