### ISSUE TITLE
ctClass#getSuperclass returns the current class

### ISSUE THREAD

**Issue by aveuiller** [INRIA/spoon#1475]
The class [it.feio.android.omninotes.models.Attachement](https://github.com/federicoiosue/Omni-Notes/blob/9ebbc0151950f8f9ec69326a9f4decc3db290f4d/omniNotes/src/main/java/it/feio/android/omninotes/models/Attachment.java) will return itself when `getSuperclass()` is called.

This happens in noclasspath mode

**Comment by surli** [comment]
In noclasspath, if Spoon cannot find the superclass it should return null, so there's certainly a bug here. 
But, first things first: do you know why there's a strange typo in your class definition: 
```java
public class Attachment extends it.feio.android.omninotes .commons.models.Attachment
```

The space between package name and `omninotes` and `.commons` seems really strange to me: does this code compile?

**Comment by tdurieux** [comment]
> if Spoon cannot find the superclass it should return null

I don't agree, the class extends something spoon has to return something

**Comment by tdurieux** [comment]
> The class it.feio.android.omninotes.models.Attachement will return itself when getSuperclass() is called.

It is not possible, getSuperclass returns a reference and you call it on a ctclass, it cannot be itself. The getdeclaration on the reference is probably wrong but we do what we can in noclasspath

**Comment by aveuiller** [comment]
@tdurieux Yes, by _itself_ I mean that it returns the same class definition. If you prefer `ctClass.getSuperclass().getSuperclass()` will return the same instance as `ctClass.getSuperclass()` (as you can see on the screenshot)

@surli As far as I can see the tabulation on the package, even if weird, does not change anything on the compilation and the behavior of spoon. I tried to remove it and got the same behavior.

![bug-omni](https://user-images.githubusercontent.com/4600261/28213259-9a72bf82-68a5-11e7-9947-0751e883e095.png)
