### ISSUE TITLE
String Array Annotations are not being correctly parsed

### ISSUE THREAD

**Issue by ocean7** [INRIA/spoon#148]
There's an annotation:

```
@Retention(RetentionPolicy.RUNTIME)
public @interface Tags {

	public String[] value();
}
```

In several cases this annotation is used without actually defining an array. For example:

```
@Tags("Boom")
public void testMethod() {

}
```

Or sometimes it's used by referring to a single static constant:

```
@Tags(Tags.Boom)
public void testMethod() {
}
```

Attempts to retrieve this array later, when the annotation is declared using a single element result in a class cast exception:

```
2015-02-04 18:40:55,773 ERROR spoon.Launcher - java.lang.String cannot be cast to [Ljava.lang.String;
java.lang.ClassCastException: java.lang.String cannot be cast to [Ljava.lang.String;
```

**Comment by GerardPaligot** [comment]
This issue should have been resolved with the PR https://github.com/INRIA/spoon/pull/142. Which version of spoon do you use?

**Comment by ocean7** [comment]
4.0-SNAPSHOT. Was that fixed merged and deployed to the SNAPSHOT?

**Comment by GerardPaligot** [comment]
Mh maybe not. @monperrus, did you deploy a snapshot version after our spoon session last monday?

**Comment by ocean7** [comment]
The actual jar being used is:

spoon-core-4.0-20150122.143025-2.

It looks like the JAR comes Jan 22 which is before last Monday. But this is the latest SNAPSHOT version that's deployed in the repo. 

Take a look at the contents of:

http://spoon.gforge.inria.fr/repositories/snapshots/fr/inria/gforge/spoon/spoon-core/4.0-SNAPSHOT/

The jars in that are all from Jan 22 or Jan 12.

Can we re-run the build and deploy the latest snapshot?

**Comment by monperrus** [comment]
re-deployed
--Martin

**Comment by GerardPaligot** [comment]
@ocean7 Can you test the new snapshot version and confirm that it works (or not)?

**Comment by ocean7** [comment]
Do believe this has been fixed now. Thanks!
