### ISSUE TITLE
Stackoverflow problem at spoon.support.compiler.jdt.ReferenceBuilder.getTypeReference

### ISSUE THREAD

**Issue by justinwm** [INRIA/spoon#1482]
Dear All

I am using the version of 5.7, and I have encountered a stackoverflow problem when processing a Java file using spoon.

My code is very simple, just as follows:
`
Launcher spoon = new Launcher();`
`spoon.addInputResource("./targets/KMeansPlusPlusClusterer.java");`
`spoon.getEnvironment().setNoClasspath(true);`
`ClassDeclarationProcessor processor = new ClassDeclarationProcessor();`
`spoon.addProcessor(processor);`
`spoon.run();`

Class `ClassDeclrationProcessor` simply overwrites the `process()` method and dose nothing right now.
For the other Java files, it's OK, but there is an stackoverflow problem when the input source files is `KMeansPlusPlusClusterer.java`.

![image](https://user-images.githubusercontent.com/2504533/28401908-8e8f4e5c-6d4f-11e7-9db2-8ff34d62f861.png)

I suppose it might relates to the input file.

Is there any who knows how to resolve this issue and process the source file correctly?

You can find the `KMeansPlusPlusClusterer.java` in the following link.

[https://github.com/justinwm/Lexer/blob/master/code/src/KMeansPlusPlusClusterer.java](https://github.com/justinwm/Lexer/blob/master/code/src/KMeansPlusPlusClusterer.java)

Thanks very much!!

**Comment by surli** [comment]
Hi @justinwm,

thanks for the report, actually this bug has already been fixed. Try to use the last release of Spoon, which is version 5.8.0. Tell me if it fix your bug then I'll close the ticket.

**Comment by justinwm** [comment]
Hi @surli 

Thanks! It works on version 5.8.0.

Thanks!
