### ISSUE TITLE
feature request: SingleMemberAnnotation support

### ISSUE THREAD

**Issue by Wreulicke** [INRIA/spoon#1484]
In pretty print mode with spoon, 
annotation having only "value" member converts normal annotation.

JDT Core has 3 tree model related to annotation.

* MarkerAnnotation like ( @ RequestMapping)
* SingleMemberAnnotation ( @ RequestMapping("path"))
* NormalAnnotation (@ RequestMapping(value="path"))

May I obtain code used single member annotation ?

I presents before/actual/expected.

* before (spoon process)
```java
class Controller{
    @RequestMapping("get")
    public String get() {
        return "get";
    }
}
```

* after
```java
class Controller{
    @RequestMapping(value = "get")
    public String get() {
        return "get";
    }
}
```

* expected
```java
class Controller{
    @RequestMapping("get")
    public String get() {
        return "get";
    }
}
```

# 

I used below code.
If there is my mistake, could you show me.

```java
public class ProcessorTest {
	@Test
	public void test() {
		SpoonAPI api = new Launcher();
		api.getEnvironment().setAutoImports(true);
		api.getEnvironment().setNoClasspath(true);
		api.getEnvironment().setComplianceLevel(8);
		api.addInputResource("src/test/resources/Controller.java");
		api.setSourceOutputDirectory("spooned");
		api.run();
	}
}
```

**Comment by monperrus** [comment]
closed per #1485
