### ISSUE TITLE
Preorder Traversal of an AST using Spoon

### ISSUE THREAD

**Issue by sourabhsparkala** [INRIA/spoon#1496]
Hello I wonder if there is a way to traverse through AST from .java file and with preoder or inorder technique?

Also, if that is true, id it possible to modify the AST with new nodes before and after?

Is there any small example snippet, or could you please help me in understanding if this is possible with spoon?

Regards
Sourabh

**Comment by pvojtechovsky** [comment]
Welcome! Spoon is using preorder traversing of AST tree. See mainly spoon.reflect.visitor.CtScanner.

Have a look at [Spoon documentation](http://spoon.gforge.inria.fr/index.html) for explanation of basic concepts and examples. Note that all [spoon filters](http://spoon.gforge.inria.fr/filter.html) are based on preorder traversing.

**Comment by sourabhsparkala** [comment]
Hello @pvojtechovsky 

Thank you for the reply,

I am running a preorder tree traversal, and I am visiting each node. Say, I reach a respective node, I want to insert new nodes 'Before' and 'After' the respective node. Sometimes, the inserting node may be a 'Statement' or a 'Comment'. Is there a way to to do that? or is there some other awesome class already implemented for doing simple mutations to AST like insert new node, delete node, replace node? Any example snippet on how to achieve this or a starting point would help me a lot and it would be very much appreciated. I am new to java, hence I am not sure how this works.

To parse through a Java file

I find a statement
int i =0;

This can be a CtLocalVariable enclosed in a method or CtLiteral enclosed in a class but ultimately considered as a node in AST.

I want to update the Tree by adding the new statement as a node before and after the respective node in AST

Like given below:

int j = 10;
int i = 0;
int k = 20;

insertBefore() and insertAfter() seems to be applicable only for CtStatement not for CtElement or CtCodeElement

Could you please give me a hint on how to achieve this when I am traversing through the AST?


for(CtCodeElement element: (List<CtCodeElement>)model.getElements(new TypeFilter(CtCodeElement.class))){
				System.out.println(""+ ++count +"-------"+ element.getShortRepresentation()+"-------"+ element.toString() +"----------");
				CtComment comment = element.getFactory().Code().createComment( ++count + "[" , CtComment.CommentType.BLOCK);
			    comment.insertBefore(element.    /*  This is where I am finding issue in inserting a node element  */);
				element.addComment(comment);
		}
Regards
Sourabh

**Comment by surli** [comment]
Hi @sourabhsparkala and welcome here :)

So to sum up what I understood, you want to insert nodes (CtElement) before and after a statement or a comment, right? 
Spoon only provides an API `insertBefore` and `insertAfter` for CtStatement: a lot of code elements inherits from CtStatement but not all of them, see http://spoon.gforge.inria.fr/code_elements.html

What nodes are you targeting exactly? In your example, why don't you filter on CtStatement instead of CtCodeElement?

**Comment by tdurieux** [comment]
`insertBefore()` and `insertAfter()` is only compatible with statement.

If you want to add a comment, it is better to use `addComment(CtComment)` method on the element.

If you want to add a Statement before any element in your source code, you can do something like this.

```java
for(CtCodeElement element: (List<CtCodeElement>)model.getElements(new TypeFilter(CtCodeElement.class))){
    CtStatement statement;
    if (element instanceof CtStatement) {
        statement = (CtStatement) element;
        if (new LineFilter().match(statement) == false) {
             statement = element.getParent(new LineFilter());
        }
    } else {
        statement = element.getParent(new LineFilter());
    }
    if (statement != null) {
        statement.insertBefore(<new_statement>);
    }
}
```

**Comment by sourabhsparkala** [comment]
Hello @tdurieux . @surli 

Thank you for this insight.This helps.

I will miss out on many other instances present in the code element;

Please consider the Test Class below
public class App2 
{
	int a,b=0;
	public int main()
	{
		int i,b =0;
		System.out.println("Hello world");
		if(b<2){
			System.out.println("in if loop");
			b++;
		}
		return 0;
	}
}

If I do CtCodElement parsing on the same

for(CtCodeElement statement: (List<CtCodeElement>)model.getElements(new TypeFilter(CtCodeElement.class))){
			    	System.out.println(statement.toString() + "------------" + statement.getShortRepresentation());
			}

I get output:

public class App2 {
    int a;

    int b = 0;

    public int main() {
        int i;
        int b = 0;
        java.lang.System.out.println("Hello world");
        if (b < 2) {
            java.lang.System.out.println("in if loop");
            b++;
        }
        return 0;
    }
}------------spoon.support.reflect.declaration.CtClassImpl@1f3e52
{
}------------spoon.support.reflect.code.CtBlockImpl@1
super()------------spoon.support.reflect.code.CtInvocationImpl@1
0------------spoon.support.reflect.code.CtLiteralImpl@1
{
    int i;
    int b = 0;
    java.lang.System.out.println("Hello world");
    if (b < 2) {
        java.lang.System.out.println("in if loop");
        b++;
    }
    return 0;
}------------spoon.support.reflect.code.CtBlockImpl@1
int i------------spoon.support.reflect.code.CtLocalVariableImpl@6a
int b = 0------------spoon.support.reflect.code.CtLocalVariableImpl@63
0------------spoon.support.reflect.code.CtLiteralImpl@1
java.lang.System.out.println("Hello world")------------spoon.support.reflect.code.CtInvocationImpl@1
java.lang.System.out------------spoon.support.reflect.code.CtFieldReadImpl@1
java.lang.System------------spoon.support.reflect.code.CtTypeAccessImpl@1
"Hello world"------------spoon.support.reflect.code.CtLiteralImpl@1
if (b < 2) {
    java.lang.System.out.println("in if loop");
    b++;
}------------spoon.support.reflect.code.CtIfImpl@1
b < 2------------spoon.support.reflect.code.CtBinaryOperatorImpl@1
b------------spoon.support.reflect.code.CtVariableReadImpl@1
2------------spoon.support.reflect.code.CtLiteralImpl@1
{
    java.lang.System.out.println("in if loop");
    b++;
}------------spoon.support.reflect.code.CtBlockImpl@1
java.lang.System.out.println("in if loop")------------spoon.support.reflect.code.CtInvocationImpl@1
java.lang.System.out------------spoon.support.reflect.code.CtFieldReadImpl@1
java.lang.System------------spoon.support.reflect.code.CtTypeAccessImpl@1
"in if loop"------------spoon.support.reflect.code.CtLiteralImpl@1
b++------------spoon.support.reflect.code.CtUnaryOperatorImpl@1
b------------spoon.support.reflect.code.CtVariableWriteImpl@1
return 0------------spoon.support.reflect.code.CtReturnImpl@1
0------------spoon.support.reflect.code.CtLiteralImpl@1

As you can see, I will not be able to get Instances of CtField, CtTypeAccess, CtLiteral with CtStatement.

1. What I need is a way to insert valid statements like Comments can be added anywhere in the code before and after these CodeElements.
2. I need way to get all the Instance Class, not the Impl class name, the actual ElementType class like CtLiteral. How can I know what type of ElementType classes are recognized in the list<CtCodeElement>

Your help would be greatly appreciated.

Regards
Sourabh

**Comment by sourabhsparkala** [comment]
Hello,

For the input file:
public class App2 
{
	int a,temp=0;
	public int main()
	{
		int i,b =0;
		System.out.println("Hello world");
		if(b<2){
			System.out.println("in if loop");
			b++;
		}
		return 0;
	}
}


I am trying something like this now:

public class CodeElementProcessor extends AbstractProcessor<CtElement>{

	int count = 0;
	public void process(CtElement element) {
		if (element instanceof CtCodeElement){
			if(!element.toString().contains("super")){
				System.out.println("CodeElement-----------"+ element.toString() + "------------" + element.getShortRepresentation());
				if(element instanceof CtExpression){
					CtStatement statement = null;
					((CtExpression)element).addComment(getFactory().Core().createComment().setContent("/*testing*/"));
				} else {
					((CtStatement)element).addComment(getFactory().Core().createComment().setContent("/*testing*/"));
				}
			}
		} else 
			if (element instanceof CtTypedElement) {
			System.out.println("TypedElement-----------"+ element.toString() + "------------" + element.getShortRepresentation());
			//getFactory().Code().createCodeSnippetStatement("testing");
		} 

	}
}

But the comments are not getting inserted to the output file? Is there a way to debug this, to check if the element is getting added with comments?

**Comment by tdurieux** [comment]
You have to enable the comment in the environment.

De : sourabhsparkala<mailto:notifications@github.com>
Envoyé le :mardi 8 août 2017 19:09
À : INRIA/spoon<mailto:spoon@noreply.github.com>
Cc : Thomas Durieux<mailto:durieuxthomas@hotmail.com>; Mention<mailto:mention@noreply.github.com>
Objet :Re: [INRIA/spoon] Preorder Traversal of an AST using Spoon (#1496)


Hello,

For the input file:
public class App2
{
int a,temp=0;
public int main()
{
int i,b =0;
System.out.println("Hello world");
if(b<2){
System.out.println("in if loop");
b++;
}
return 0;
}
}

I am trying something like this now:

public class CodeElementProcessor extends AbstractProcessor{

int count = 0;

public void process(CtElement element) {

        if (element instanceof CtCodeElement){

                if(!element.toString().contains("super")){

                       System.out.println("CodeElement-----------"+ element.toString() + "------------" + element.getShortRepresentation());

                       if(element instanceof CtExpression){

                               CtStatement statement = null;

                               ((CtExpression)element).addComment(getFactory().Core().createComment().setContent("/*testing*/"));

                       } else {

                               ((CtStatement)element).addComment(getFactory().Core().createComment().setContent("/*testing*/"));

                       }

               }

        } else

               if (element instanceof CtTypedElement) {

                System.out.println("TypedElement-----------"+ element.toString() + "------------" + element.getShortRepresentation());

                //getFactory().Code().createCodeSnippetStatement("testing");

        }



}

}

But the comments are not getting inserted to the output file? Is there a way to debug this, to check if the element is getting added with comments?

**Comment by surli** [comment]
> What I need is a way to insert valid statements like Comments can be added anywhere in the code before and after these CodeElements.

If what you need to insert is *only* comment, you can add them on every `CtElement` through the `addComment` method.

>    I need way to get all the Instance Class, not the Impl class name, the actual ElementType class like CtLiteral. How can I know what type of ElementType classes are recognized in the list

In fact it's up to you to decide what you want to filter. When using `model.getElements(new TypeFilter(CtCodeElement.class))` you decide to filter all CodeElements of the class so you only get those.
If you want to get all fields you can directly filter by `CtField` and so one. If you want absolutely all the statements of the class, the better way IMHO is to filter by CtElement, but be careful because some elements you will get are not pretty printed (e.g. `super()------------spoon.support.reflect.code.CtInvocationImpl@1` in your example, which is retrieved but not printed at the end). 

You can see the metamodel of Spoon on those pages to help you: http://spoon.gforge.inria.fr/structural_elements.html and http://spoon.gforge.inria.fr/code_elements.html

**Comment by surli** [comment]
I close this ticket, don't hesitate to reopen it if you have any other question.
