### ISSUE TITLE
How to get CtClass from CtMethod using spoon

### ISSUE THREAD

**Issue by pavanspoon** [INRIA/spoon#1509]
I want to get the class name of the method using spoon.

**Comment by surli** [comment]
Hi @pavanspoon,

let's say you got a `CtMethod` named `method` you can use the method `getParent(...)` to get access to any element of a type which is a parent of this method.

Then you can write something like: 

```java
CtMethod method = spoon.getFactory().getModel().getElements(new TypeFilter<CtMethod>(CtMethod.class)).get(0); // just one way to get a method

CtClass zeclass = method.getParent(CtClass.class); // you will get here the first CtClass parent of this method
```

**Comment by pavanspoon** [comment]
Hi @surli 

Thank you for this insight.This helps.
Can you help me to get the method references.

public class A{
  priivate B b;

add(){
  b.display();
}

}

public class B{

public void display(){
 //
}

}

Here want to get the displayMethod references using spoon.

**Comment by surli** [comment]
Ok first of all, `b.display();` in class A represents a `CtInvocation` in Spoon metamodel, and `display()` method declaration in class B is a `CtMethod`. 

Let's say you want to get them both, and that your source code is contained in a folder `src`. 

First you have to build your Spoon model: 

```java
Launcher spoon = new Launcher();
spoon.addInputResource("./src/");
spoon.buildModel();
Factory factory = spoon.getFactory();
```

Then, let's get the `CtMethod` in class B, if I assume that you know exactly the name of your method, the easiest way to do it is that one: 

```java
CtClass<?> classB = factory.Class().get("your.package.B"); // here I assume that your.package.B is the fully qualified name
CtMethod<?> displayMethod = (CtMethod<?>)classB.filterChildren(new TypeFilter<CtMethod>(CtMethod.class)).filterChildren(new NameFilter<CtMethod>("display")).list().get(0);
```

Here I'm using two different filter: the first one to get only the methods of the class, the second one to get only the one named "display". As you can see you can easily chain the filters. 

So, to get the invocation from A, it's exactly the same kind of code but for a `CtInvocation`:

```java
CtClass<?> classA = factory.Class().get("your.package.A");
CtInvocation displayInvocation = (CtInvocation)classA.filterChildren(new TypeFilter<CtInvocation>(CtInvocation.class)).filterChildren(new NameFilter<CtInvocation>("display")).list().get(0);
```

**Comment by pavanspoon** [comment]
Hi @surli 

Thanks for this help. Can we able to get hold of all references of method and can we able to get the import statement using spoon api.

public class A{
  priivate B b;

add(){
  b.display();
}

}

public class B{

public void display(){
 //
}

}

public class C{
  b.display()
}

public class D {
  b.display()
}

when we traverse the B class in spoon model , we will get all the the methods ,we want to hold the references of CtMethod method(not only display) from which classes they are invoking.

**Comment by surli** [comment]
> Can we able to get hold of all references of method and can we able to get the import statement using spoon api.

It could help here if you explain what you're trying to do exactly. 

I gave you one way to get the different `CtInvocation` of a method: you can get all the methods of a given class (B for example) using a `TypeFilter` of `CtMethod` and in storing them in a list, and then you can use a `TypeFilter` of `CtInvocation` to get all references of those methods in different classes. It's one way to do it.

**Comment by pavanspoon** [comment]
Hi @surli 

Here We have package like src/main/java/com/basic, In this package , we have sub packages like service ,serviceImpl,Dao and DaoImpl each package will have classes . we want to build a spoon model. In Dao package we have CustomerDaoImpl class is there, In that we have updateCustomerDetails(Customer c) method is defined but this method is called from some other classes like CustomerService and AccountService  and etc.... When we traverse the CustomerDaoImpl class and updateCustomerDetails method Now we cant to get the all the references using Spoon.

	final Launcher launcher = new Launcher();
		launcher.getEnvironment().setNoClasspath(true);
		launcher.addInputResource("./src/main/java/com/basic");
		launcher.getModelBuilder().setBinaryOutputDirectory(new File("./src/main/java/com/basic/dao/"));
		launcher.buildModel();
		
		final CtModelImpl model = (CtModelImpl) launcher.getModel(); 
		List<CtType<?>> classesList = launcher.getFactory().Class().getAll();
		   for (CtType<?> type : classesList) {
			   if(type instanceof CtClass<?>){
				    CtClass<?> clas = (CtClass<?>)type;
					CtMethod<?> methodList = (CtMethod<?>)clas.filterChildren(new TypeFilter<CtMethod>(CtMethod.class)).list();
					CtInvocation<?> displayInvocation = (CtInvocation)clas.filterChildren(new TypeFilter<CtInvocation>(CtInvocation.class)).list();


			   }
		   }


here we are getting invocations of that class not method references,

CtInvocation displayInvocation = (CtInvocation)classA.filterChildren(new TypeFilter<CtInvocation>(CtInvocation.class)).filterChildren(new NameFilter<CtInvocation>("display")).list().get(0);

Could you please help on this . How can we write generic code for handling all CtClass methods.

**Comment by surli** [comment]
> here we are getting invocations of that class not method references,

You can easily get the method references with `getExecutable()` method of `CtInvocation`, it will return a `CtExecutableReference` to the method called.

**Comment by pavanspoon** [comment]
Hi @surli 

we are not able to get references of method using CtExecutableReference.

![image](https://user-images.githubusercontent.com/31468819/29880881-9862d736-8dc6-11e7-87ae-ea5c491e75ed.png)

**Comment by surli** [comment]
Your error occured line 62: you try to get access to the element 0 of the list of CtMethod, but your list is certainly empty. You have to check its size.

**Comment by pavanspoon** [comment]
Hi @surli 

Thanks for response. Even we are not getting method references list is notempty. It is returning object not method references. Is this code correct .Could you check .
 CtClass<?> classA = launcher.getFactory().Class().get("com.basic.dao.MyDaoImpl");
				    CtMethod<?> displayMethod = (CtMethod<?>)classA.filterChildren(new TypeFilter<CtMethod>(CtMethod.class)).filterChildren(new NameFilter<CtMethod>("updateDetail")).list().get(0);
					CtInvocation<?> displayInvocation = (CtInvocation)classA.filterChildren(new TypeFilter<CtInvocation>(CtInvocation.class)).list().get(0);
					CtExecutableReference<?> ctExecutableReference  =  displayInvocation.getExecutable();
					System.out.println(ctExecutableReference.getExecutableDeclaration());

![image](https://user-images.githubusercontent.com/31468819/29883153-f632dad6-8dcc-11e7-9f14-bc3ddd6002c4.png)

**Comment by surli** [comment]
In fact it's returning method reference for Object constructor. 
It's because when you call this line:
```java
CtInvocation<?> displayInvocation = (CtInvocation)classA.filterChildren(new TypeFilter<CtInvocation>(CtInvocation.class)).list().get(0);
```

It gets all method (and constructor) invocations from classA, and then returns the first one. And it's always the implicit call to Object constructor. 
You have to notice that your two calls for the CtMethod and the CtInvocation are completely separated: you're not getting the invocation related to the CtMethod. 
So if you only want the invocation of "updateDetail" method, just add a new NameFilter when getting the CtInvocation, exactly like you did for CtMethod.

**Comment by pavanspoon** [comment]
Hi @surli 

Thanks for this help.

Can we able to get the import statements in CtClass (import javax.xml.bind.JAXBContext) using spoon api.

**Comment by surli** [comment]
> Can we able to get the import statements in CtClass (import javax.xml.bind.JAXBContext) using spoon api.

Yes it's possible but it's a new feature so it's not release yet, you have to use the last snapshot of spoon: 
```
<dependencies>
	<dependency>
		<groupId>fr.inria.gforge.spoon</groupId>
		<artifactId>spoon-core</artifactId>
		<version>5.9.0-SNAPSHOT</version>
	</dependency>
</dependencies>
<repositories>
	<repository>
		<id>gforge.inria.fr-snapshot</id>
		<name>Maven Repository for Spoon Snapshot</name>
		<url>http://spoon.gforge.inria.fr/repositories/snapshots/</url>
		<snapshots />
	</repository>
</repositories>
```

Imports information are available from the compilation unit in Spoon for now: 
```java
Launcher spoon = new Launcher();
... // everything usual to build spoon model
String classFQN = "my.class.with.imports.Classname";
CompilationUnit cu = spoon.getFactory().CompilationUnit.create(classFQN);
Collection<CtReference> imports = cu.getImports();
```

Please note that you'll get indeffirently static imports and type imports. You can discriminate them by their type: if it's a CtTypeReference it's a normal import, if it's a CtExecutableReference or a CtFieldReference it's a static import.

**Comment by pavanspoon** [comment]
Hi @surli 

Thanks for quick response. We tried this approach but there is no create method in CompilationUnit it seems even we are using latest spoon version. could you me help on this.

![image](https://user-images.githubusercontent.com/31468819/29917070-61a3384c-8e5e-11e7-97c0-4307f3c93075.png)

**Comment by pavanspoon** [comment]
Hi @surli 

we are not able to get the imports using below code . can you help on this.

for (CtClass<?> ctClass : classes) {
			CompilationUnit cu =  launcher.getFactory().CompilationUnit().create(ctClass.getQualifiedName());
			Collection<CtReference> imports = cu.getImports();
			System.out.println("imports:::::::::"+imports.size());
			for (CtReference ctReference : imports) {
				System.out.println("ctReference:::::::::"+ctReference);
			}
		}

![image](https://user-images.githubusercontent.com/31468819/29918198-3b37a8b0-8e62-11e7-8b9c-8c8ff11bddd6.png)

**Comment by surli** [comment]
> we are not able to get the imports using below code

My bad, you have to use the autoImports mode in Spoon for that feature: 

```java
spoon.getEnvironment().setAutoImports(true);
// building model and other stuff
```

**Comment by pavanspoon** [comment]
Hi @surli 

Thanks for responding, eventhough we are not getting import statement.

final Launcher launcher = new Launcher();
		launcher.getEnvironment().setNoClasspath(true);
		launcher.getEnvironment().setAutoImports(true);
		launcher.addInputResource("./src/main/java/com/basic");
		launcher.getModelBuilder().setBinaryOutputDirectory(new File("./src/main/java/com/basic/dao/"));
		launcher.buildModel();
		
		final CtModelImpl model = (CtModelImpl) launcher.getModel(); 	
		List<CtClass<?>> classes = model.getElements(new TypeFilter<>(CtClass.class)); // get all classes
			for (CtClass<?> ctClass : classes) {
			CompilationUnit cu =  launcher.getFactory().CompilationUnit().create(ctClass.getQualifiedName());
			Collection<CtReference> imports = cu.getImports();
			System.out.println("imports:::::::::"+imports.size());
			for (CtReference ctReference : imports) {
			}
		}
![image](https://user-images.githubusercontent.com/31468819/29920147-c6c880be-8e69-11e7-98b4-4ba0de42f323.png)

**Comment by surli** [comment]
Yes actually I made a mistake: CompilationUnitFactory#create does not take the fully qualified name of the class, but its file path. 

So instead:
```java
CompilationUnit cu =  launcher.getFactory().CompilationUnit().create(ctClass.getQualifiedName());
```

You can try this code : 
```java
String classPosition = ctClass.getPosition().getFile().getAbsolutePath();
CompilationUnit cu = launcher.getFactory().CompilationUnit().create(classPosition);
```

**Comment by pavanspoon** [comment]
Hi @surli 

Thank you for this insight.This helps.
