### ISSUE TITLE
Is there any way convert spoon model to xml or xmi using spoon api

### ISSUE THREAD

**Issue by pavanspoon** [INRIA/spoon#1511]
Hi @surli 

Is there any way convert spoon model to xml or xmi using spoon api.

**Comment by surli** [comment]
Spoon API does not provide an out of the box way to convert a Spoon model in XML or XMI. However there is mechanisms to serialize a Spoon model in files and to be able to load the file. Maybe it's a starting point in writing the converter you need. Have a look on `ModelStreamer` and `SerializationModelStreamer` in Spoon, and if you decide to implement this feature don't hesitate to open a pull request and to propose it :)

**Comment by pavanspoon** [comment]
Hi @surli 

Thanks for Suggestion. Definitely we can try it out.  Can we able to see the  complete spoon model tree.

**Comment by surli** [comment]
> Can we able to see the complete spoon model tree.

From CtModel you can access the complete tree.

**Comment by monperrus** [comment]
To get started with the metamodel, you can browse the model (ie the Spoon AST) of a java file (say
|MyClass.java|) as follows:

|$ java -cp spoon-core-5.8.0-jar-with-dependencies.jar spoon.Launcher -i MyClass.java --gui
--noclasspath |

**Comment by pavanspoon** [comment]
Hi @surli @monperrus 

We are not able to see the complete tree using CtModel and even using this command also we are not able to see the complete tree ,  **java -cp C:\Users\ab69284\Desktop\spoon\spoon-core-5.9.0-SNAPSHOT-jar-with-dependencies.jar spoon.Launcher -i C:\Users\ab69284\Desktop\spoon-master\src\main\java\com\basic\dao\FPLauncherTest.java --gui**

FPLauncherTest : 

 Launcher launcher = new Launcher();
		launcher.getEnvironment().setNoClasspath(true);
		launcher.getEnvironment().setAutoImports(true);
		launcher.addInputResource("./src/main/java/com/basic");
		launcher.getModelBuilder().setBinaryOutputDirectory(new File("./src/main/java/com/basic/dao/"));
		launcher.buildModel();
		final CtModelImpl model = (CtModelImpl) launcher.getModel(); 

Could you help on this.

![image](https://user-images.githubusercontent.com/31468819/29965055-c69e2164-8f29-11e7-8be3-c573862929c0.png)

![image](https://user-images.githubusercontent.com/31468819/29965095-e54505d8-8f29-11e7-864b-39a623b757ae.png)

**Comment by surli** [comment]
I'm not sure about the GUI interface of Spoon, but concerning the results you have with eclipse debugger it seems ok to me: from RootPackage, you have to open the packs (all packages), follow the tree of packages, then you'll be able to access types and only there you'll have access to the class and its inner components.

**Comment by pavanspoon** [comment]
Hi @surli 

Thanks for help, it's work for us. Can you help me to get the caller information, let take small below example when we traverse the DaoImpl CtClass and  CtMethod(updateDetailByParams()) , we want to get the caller information like from where(ServiceImpl ) it was called and again from where (ControlImpl )  serviceImpl was called .

We want to get this information in heirarchy. Could you help on this.

public class DaoImpl {
	public void updateDetailByParams(Integer age, String firstName,	String lastName, String gender, Long Salary) {
		System.out.println("updated by param successfully");
	    // Some Database Operation
	}
}

public class ServiceImpl {
	public void updateDetailByParams(Integer age, String firstName,	String lastName, String gender, Long Salary) {
		DaoImpl d = new DaoImpl();
		d.updateDetailByParams(age, firstName, lastName, gender, Salary);
	}
}

public class ControllerImpl {
	public void updateDetailByParams(Integer age, String firstName,	String lastName, String gender, Long Salary) {
		ServiceImpl s = new ServiceImpl();
		s.updateDetailByParams(age, firstName, lastName, gender, Salary);
	}
}

**Comment by surli** [comment]
Ok basically you want to create the call-graph of a method using Spoon. I don't think there is an utility for that in Spoon but I may be wrong ( @monperrus @tdurieux @pvojtechovsky ?)

From my point of view, the easiest way to code it is to create a recursive function: you list all CtInvocation from the different classes that interests you, then you code a function that takes in parameter a targeted CtMethod you want to trace back and you check against all CtInvocation that this CtMethod is called. When you find the CtInvocation which call your method, you get their parents CtMethod and you call back your function on them. You push your CtMethod results in an appropriate data structure and there it is you have your algorithm.

**Comment by monperrus** [comment]
We have one call graph builder in another project, see
https://github.com/v-m/PropagationAnalysis/blob/master/softminer/src/main/java/com/vmusco/softminer/sourceanalyzer/graphbuilding/GraphBuilder.java

**Comment by pavanspoon** [comment]
Hi @monperrus 

Thank you for your response. We want to hold the information like below using spoon api.

DaoImpl .updateDetailByParams()< --ServiceImpl .updateDetailByParams() <--ControllerImpl .updateDetailByParams()

Is there anyway to get this information , when we traverse DaoImpl .updateDetailByParams() need to get immediate caller information like ServiceImpl .updateDetailByParams() from there ControllerImpl .updateDetailByParams().

**Comment by surli** [comment]
> Is there anyway to get this information 

There's actually many ways, but none to be used immediately: you have to code it according to your needs. Then you have two pointers for that: my approach of a naïve algorithm to build a call graph, or a version already implemented in another project that you'll have to adapt.
