### ISSUE TITLE
Announcement: Spoon 5.9.0 released !!! :beer: (and towards Spoon 6.0.0...)

### ISSUE THREAD

**Issue by surli** [INRIA/spoon#1514]
The last minor release of Spoon 5.x.x will be published next week and we are now starting a new cycle we Spoon 6.0.0. The version 5 of Spoon is now more than 1 year old, a lot of new features have been added and we are starting to break some things like in working on template (see #1476).

So the first release of Spoon 6 will at least contain changes on the way template parameters are used and NameFilter will be removed in favor of NamedElementFilter. But we'll discuss about that for this release :)

For the 5.9.0 release, you can mainly expect more bug fixes and a few new features, I'll add the changelog soon.

**Comment by surli** [comment]
# New features

* Introduce NamedElementFilter (because NameFilter is ill-designed). (PR: #1500)
* In auto-import mode, imports from original source code are reused. (PR: #1499)
* Add automatically generated comments in template-produced code. (PR: #1465)
* Add support for short pretty-printing of annotation value when appropriate. (PR: #1485)
* **prettyprinter**: DefaultJavaPrettyPrinter#setLineSeparator(String). (PR: #1490)


# Bug Fixes

* **setInputClassloader**: Bug when using a URLClassLoader with standard URLs. (PR: #1507)
* Fix issue related to processing generic types. (PR: #1504)
* Fix NPE in noclasspath mode. (PR: #1502)
* Compute positions of elements. (PR: #1493)
* Support substitution of references to target type in inner type. (PR: #1477)
* **comment**: Splitting of comment by EOL. (PR: #1455)
* **template**: Object is not an template parameter implicitly. (PR: #1461)
* **reference**: Fix getReference of an unknown class that has the same name as an existing class. (PR: #1480)


# Documentation

* Update usage of maven plugin to latest version 2.5. (PR: #1508)
* Remove information about deleted stable branch. (PR: #1474)
* **release**: Update release information in documentation. (PR: #1471)


# Refactoring

* Encoding is correctly handled in Environment. (PR: #1498)
* Deprecate PrettyPrinter#getPackageDeclaration. (PR: #1489)
* **printer**: Remove deprecated method from PrinterHelper. (PR: #1472)


# Performance

* Compile comments only if needed. (PR: #1487)
* Collect list of source files only once. (PR: #1486)
* No call to expensive toString in DoNotFurtherTemplateThisElement. (PR: #1478)


# Tests

* Fix CtRenameLocalVariableRefactoringTest#testRenameAllLocalVariablesOfRenameTestSubject. (PR: #1491)


# Other

* Fix pom.xml to allow deploying snapshots. (PR: #1495)


# Community

* @pvojtechovsky gets merge honor and responsibility. (PR: #1468)

# Authors
| Name    | Nb Commit |
|---------|-----------|
| Pavel Vojtechovsky | 11 |
| Simon Urli | 10 |
| Wreulicke | 1 |
| Lionel Seinturier | 1 |
| Thomas Durieux | 1 |
| Jan Galinski | 1 |
| Martin Monperrus | 1 |

**Comment by surli** [comment]
So Spoon 5.9.0 is officially released today!

Thanks all our contributors @pvojtechovsky @Wreulicke @msteinbeck @seintur @tdurieux @jangalinski for their work on this version, let's continue like this for the new Spoon 6 :)

**Comment by pvojtechovsky** [comment]
Thank You Simon for that maintenance work!

**Comment by jangalinski** [comment]
Too kind of you ... I just fixed a version in the README ... anyway: thanks!

**Comment by monperrus** [comment]
Thanks Simon, thanks @pvojtechovsky <https://github.com/pvojtechovsky> @Wreulicke
<https://github.com/wreulicke> @msteinbeck <https://github.com/msteinbeck> @seintur
<https://github.com/seintur> @tdurieux <https://github.com/tdurieux> @jangalinski
<https://github.com/jangalinski>! --Martin
