### ISSUE TITLE
Spoon: towards compilation using JDK 8?

### ISSUE THREAD

**Issue by surli** [INRIA/spoon#1519]
Until now Spoon was compiled using JDK7 even if the tests in Spoon should use JDK8 for compilation / execution. 
I don't really see the point in changing over a compilation in JDK8 for Spoon except that, as @pvojtechovsky noticed, new versions of eclipse JDT are released (3.13.0 or 3.12.3 depending if looking on tycho or not) which are compiled using JDK8. 

As Spoon is based on JDT usage, it should be great to be able to use the last version of the library, and some statistics tends to show that as of now JDK 8 is mainly used everywhere: https://plumbr.eu/blog/java/java-version-and-vendor-data-analyzed-2017-edition

Moreover, I think it's good to ask the question now as the next release will be a major one, so if we want to change now seems a good moment. 
So what do you think about changing Spoon compilation in favor of JDK8 to be able to support new version of JDT?

**Comment by monperrus** [comment]
Indeed, we have to be able to use recent builds of JDT, also to soon support Java 9.

So I'm OK to switch the source and API compatibility level to Java 8.
