### ISSUE TITLE
How get the fields list using spoon

### ISSUE THREAD

**Issue by pavanspoon** [INRIA/spoon#1520]
Hi @surli 

We want to get the all fields count from class using spoon. Let's take small example.

public class Customer {

private String name;
private int age;
private int id;
private Address address;

}

public class Address{
private String city;
private String state;
private String country;
private Contact contact;

}

public class Contact{
  private String email;
private int mobileNum;

}

Here we try to get all the fields list size from Customer . We need to get count as 8. Could you please help on this.

**Comment by surli** [comment]
You can use a `TypeFilter` to get all elements that interests your from the model: 

```
model.getElements(new TypeFilter<CtField>(CtField.class)).size()
```

**Comment by surli** [comment]
I close this one for now. Don't hesitate to reopen if needed.
