### ISSUE TITLE
Launcher cann't able to find the source code in web application

### ISSUE THREAD

**Issue by pavanspoon** [INRIA/spoon#1524]
Hi @surli 

We are not able to prepare the CtModel in webapplication but in standalone it is able to build the CtModel
could you help on this.

public void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
			      response.setContentType("text/html");
			  	Launcher launcher = new Launcher();
				launcher.getEnvironment().setNoClasspath(true);
				launcher.getEnvironment().setAutoImports(true);
				launcher.addInputResource("./src/main/java/com/ctl/");
				launcher.getModelBuilder().setBinaryOutputDirectory(new File("./src/main/java/com/basic/dao/"));
				launcher.buildModel();
				final CtModelImpl model = (CtModelImpl) launcher.getModel()

}

**Comment by tdurieux** [comment]
It is probably due to this line
launcher.addInputResource("./src/main/java/com/ctl/");
Your working directory is probably not correct

**Comment by surli** [comment]
@pavanspoon is your problem solved here? if so can you close the issue?
