### ISSUE TITLE
add support for JSON generator of the AST

### ISSUE THREAD

**Issue by sourabhsparkala** [INRIA/spoon#1526]
Hello All,

I have .java file. I use spoon to parse it. Can the contents be serialized using spoon to JSON output?

Is there any special class or method to generate a JSON object or file?

Your help would be appreciated.

Regards
Sourabh

**Comment by surli** [comment]
> Can the contents be serialized using spoon to JSON output?

Spoon do not provide an API for creating a JSON output from a model. However, you can code it yourself, as a CtModel is serializable. Don't hesitate to propose a PR if you need this feature.

**Comment by msteinbeck** [comment]
I suggest to use [jackson](https://github.com/FasterXML/jackson) for Java to JSON serialization.

**Comment by mehdi-kaytoue** [comment]
Dear all, 
I am also very interested in that feature. Basically, I build a CtModel, a very big one. Creation lengths 55 minutes and things work great. However, I wonder if performing a serialization of my CtModel once and for all, and just reading the serialization would not be much faster. Is it worth in your opinion? 
Any advances? I'd be happy to help.
Cheers,
Mehdi

**Comment by monperrus** [comment]
> However, I wonder if performing a serialization of my CtModel once and for all, and just reading the serialization would not be much faster

Yes. There is already support for serialization, see #1252 (but not in JSON)

**Comment by mehdi-kaytoue** [comment]
Saw #1252 just a moment after, sorry. It works nicely after some test on "small" models (50 Mb source code) both serializing and deserializing. Great!

However, deserialization its twice longer that reading the model from the sources.
Looking at SerializationModelStreamer.load(), I wonder if we can have something more efficient?
Not sure to fully understand, but we need to assign the factory to each CtElement of the model?

**Comment by tdurieux** [comment]
Maybe you can try this: https://github.com/RuedigerMoeller/fast-serialization

**Comment by monperrus** [comment]
> Looking at SerializationModelStreamer.load(), I wonder if we can have something more efficient?
Maybe there is a performance bug there. Could you open an issue dedicated to this problem?

(we're not discussing JSON export anymore)

**Comment by monperrus** [comment]
This has been made in https://github.com/SpoonLabs/gumtree-spoon-ast-diff/.

See class `Json4SpoonGenerator`:  https://github.com/SpoonLabs/gumtree-spoon-ast-diff/blob/master/src/main/java/gumtree/spoon/builder/Json4SpoonGenerator.java

Kudos to @martinezmatias!
