### ISSUE TITLE
Spoon dependencies from repo.maven.apache.org. Use proxy repository?

### ISSUE THREAD

**Issue by pvojtechovsky** [INRIA/spoon#1531]
last days it often happens that downloading of dependencies needs long time or it fails like this:

`[ERROR] Failed to execute goal on project spoon-core: Could not resolve dependencies for project fr.inria.gforge.spoon:spoon-core:jar:6.0.0-SNAPSHOT: Could not transfer artifact ant:ant:jar:1.6.5 from/to central (http://repo.maven.apache.org/maven2): GET request of: ant/ant/1.6.5/ant-1.6.5.jar from central failed: Connection reset`

Would not it be solution to cache all these dependencies using some sonetype nexus **proxy repository**? Or is it already configured like this but nexus proxy has some problems?

I really do not understand architecture of spoon CI build process (and I do not want to understand it). I just know that "proxy repository" might be a solution if CI architecture allows it :-)

**Comment by surli** [comment]
> Or is it already configured like this but nexus proxy has some problems?

I think it's the case but our server (spoon.gforge.inria.fr) seems sometimes unreachable. One solution might be to deploy snapshot over sonatype directly instead of deploying them on our own repo as it seems not really stable. WDYT @monperrus ?

**Comment by monperrus** [comment]
It seems there are different problems:

P1) the INRIA CI environment sometimes has no network access, and cannot access 
repo.maven.apache.org (issue title).

P2) the INRIA CI snapshot deployment job sometimes fails for different reasons (incl P1)

P3) spoon.gforge.inria.fr is sometimes unavailable and the snapshots are not available

Deploying the snapshots on Sonatype is only a partial solution, it would only fix P3.

**Comment by tdurieux** [comment]
Apparently, the solution is to stop to use INRIA servers that are not production ready.

**Comment by surli** [comment]
The first solution for this is #1557 
I close this one.
