### ISSUE TITLE
Spoon on the "awesome-static-analysis" tools list

### ISSUE THREAD

**Issue by pvojtechovsky** [INRIA/spoon#1532]
We are not listed there [https://github.com/mre/awesome-static-analysis](https://github.com/mre/awesome-static-analysis)

and here https://en.m.wikipedia.org/wiki/List_of_tools_for_static_code_analysis ?
WDYT?

**Comment by monperrus** [comment]
PR done: https://github.com/mre/awesome-static-analysis/pull/111

**Comment by monperrus** [comment]
PR merged, Spoon is in awesome-static-analysis

**Comment by pvojtechovsky** [comment]
I have added the line into Java section of [https://en.m.wikipedia.org/wiki/List_of_tools_for_static_code_analysis], but there is missing a Spoon article for that - and I am not allowed to make one. So may be it was bad idea...
