### ISSUE TITLE
Maven plugin should fail when getEnv().report(Level.error, msg) is called

### ISSUE THREAD

**Issue by tmortagne** [INRIA/spoon#1534]
At XWiki we plan to use Spoon Maven plugin to fail the build when some module use a forbidden method. I wrote a custom Processor (which was super easy, good job :)) but I can't find any way to tell the plugin to fail the build when there is errors in the report.

**Comment by tdurieux** [comment]
Hi,

The easiest way to stop the build is to throw a runtime exception.

**Comment by tmortagne** [comment]
Sure but it would be nicer to see all the errors of the report instead of crashing the execution. Just need a switch to fail or not the build when there is errors in the report.

**Comment by tmortagne** [comment]
> I'm pretty sure that the only way to change the build status of maven is to throw an exception.

Yes but that exception should be through by the plugin itself when finding errors in the report IMO. It allows seeing all errors and not just the first one and it also allows enable/disable failing the build for the same processor depending on the need. There is several processor provided by Spoon and which don't trough any exception right now for example.

**Comment by vmassol** [comment]
Spoon advocates itself as a tool to enforce architecture rules. As such it should provide a "check" goal that would run the processors and have options to fail the build if a processor reports an ERROR. That seems a very basic need for such a tool. All Maven plugins I know that do checks provide this ability.

@tdurieux Hi. For the context, I met Martin at a STAMP meeting and he advocated the use of Spoon for the XWiki project. I said I'd look into it and Thomas worked on trying it out for XWiki. It's working quite well except on this point. I think it would benefit the tool nicely if you guys could add this feature. Thanks!

**Comment by tdurieux** [comment]
> @tdurieux Hi. For the context, I met Martin at a STAMP meeting and he advocated the use of Spoon for the XWiki project. I said I'd look into it and Thomas worked on trying it out for XWiki. It's working quite well except on this point. I think it would benefit the tool nicely if you guys could add this feature. Thanks!

I agree, I just gave a workaround since we don't have this feature (yet).

@tmortagne Do you use `getEnvironment().report(...)`?

**Comment by monperrus** [comment]
Interesting! That would be indeed a useful feature. 

What would be a good API to your opinion?

    Something.failBuild() // to be called in the processor
    Something.failBuild(String msg)

**Comment by tdurieux** [comment]
> Something.failBuild() // to be called in the processor
Something.failBuild(String msg)

I'm not a big fan because the processors are not only designed for the Maven Plugin. 
And these API outside the maven plugin are hard to understand.

**Comment by tmortagne** [comment]
> @tmortagne Do you use getEnvironment().report(...)?

Yes.

**Comment by monperrus** [comment]
That's why the "Something" would probably be a class from the Maven plugin, not from spoon-core.

**Comment by tmortagne** [comment]
> Something.failBuild() // to be called in the processor
> Something.failBuild(String msg)

The existing API is fine and processors don't need to do more that listing error/warnings (by the way it looks like FATAL log level is simply ignored, I don't need it but noticed it when doing experiments).

What is missing is properties exposed in the Mojo so that you can tell it to fail or not the build.

**Comment by monperrus** [comment]
> processors don't need to do more that listing error/warnings (by the way it looks like FATAL log level is simply ignored

how would like to signal that the build should fail?

**Comment by tdurieux** [comment]
When can add a listener on our logger like this

```java
LOGGER.addAppender(new Appender() {
});
```
And when it detects an error when can fail the process.

**Comment by tmortagne** [comment]
> how would like to signal that the build should fail?

It's usually a property in the plugin configuration parameter so a field in https://github.com/SpoonLabs/spoon-maven-plugin/blob/master/src/main/java/fr/inria/gforge/spoon/Spoon.java (or a different mojo if you want to introduce a dedicated "check" Mojo which fail the build by default which would probably make more sense).

> When can add a listener on our logger

Actually I was imagining the plugin looking at the full module report and failing the build if the report contains any ERROR (its nicer to see all the error of the module to fix all of them). From what I understand when looking at plugin sources you already have something catching the error but it's just storing an XML file right now it seems. But sure as long as there is a way to fail the build I'm happy :)

**Comment by monperrus** [comment]
> It's usually a property in the plugin configuration parameter
I mean, even if there is this option, what would write in the code to tell that it has failed? you
would throw an exception as @tdurieux suggests?

**Comment by tmortagne** [comment]
Yes the plugin should through a MojoFailureException AFAIK.

**Comment by monperrus** [comment]
OK that's clear. With the current version of the plugin, what happens when you throw a MojoFailureException?

**Comment by vmassol** [comment]
> Yes the plugin should through a MojoFailureException AFAIK.

Why not simply report a ERROR level using `getEnvironment().report(...)` and then it's a Maven plugin-level config to tell the plugin to fail when there are errors or not?

**Comment by monperrus** [comment]
That's also an option. It would require the plugin to somehow listen / observe to the environment
object.

**Comment by tmortagne** [comment]
> Why not simply report a ERROR level using getEnvironment().report(...) and then it's a Maven plugin-level config to tell the plugin to fail when there are errors or not?

Yes this is what I'm saying, the PLUGIN should throw en Exception, not the processor.

**Comment by tdurieux** [comment]
Yes, like the listener i gave

**Comment by monperrus** [comment]
OK. It seems we agree on the basic design.

Currently, does it work if one directly throws a MojoFailureException from the processor code?

**Comment by tmortagne** [comment]
Processor#process is not allowed to throw any exception but a RuntimeException should crash the plugin which will make Maven stop the build yes as suggested by @tdurieux.

**Comment by monperrus** [comment]
I understand, [MojoFailureException](https://maven.apache.org/ref/3.2.3/maven-plugin-api/apidocs/org/apache/maven/plugin/MojoFailureException.html) is not a runtime exception so it cannot be thrown.

Could you try and confirm that throwing a runtime exception is a valid workaround?

**Comment by tmortagne** [comment]
Depends how to define "valid" but throwing a RuntimeException do stop the build :)
