### ISSUE TITLE
Allow passing properties to a Processor trough Maven plugin

### ISSUE THREAD

**Issue by tmortagne** [INRIA/spoon#1537]
Maybe I missing something but I can't find any way to pass properties to a Processor when using the Maven plugin.

**Comment by tmortagne** [comment]
Hmm actually if I understand well SpoonConfigurationFactory I'm support to provide a spoon.xml file at the root of my module resources. Probably just missing some example/documentation, sorry for the noise.

**Comment by monperrus** [comment]
> Probably just missing some example/documentation, sorry for the noise. 
Sorry for the missing documentation :-) We also love documentation PRs :-D

**Comment by tmortagne** [comment]
> We also love documentation PRs :-D

Any pointer on how to find out what is the format in that file and where it's supposed to be located ?

**Comment by surli** [comment]
> Any pointer on how to find out what is the format in that file and where it's supposed to be located ?

Actually reading to the test of spoon-maven-plugin, the `spoon.xml` file is only used to pass the template and processor's names configuration, look at this spoon.xml example:

```xml
<spoonModel>
    <processors>
        <processor>com.dooapp.processor.wrapper.GenerateMissingWrapperClassProcessor</processor>
    </processors>
    <templates>
        <template>com.dooapp.template.WrapperConstructorTemplate</template>
    </templates>
</spoonModel>
```

So given the name of the issue I don't think it's what you want to do, right? 
Could you give more details then on the kind of properties you would like to give to the processor?

**Comment by tmortagne** [comment]
> So given the name of the issue I don't think it's what you want to do, right?

Yep.

>  Could you give more details then on the kind of properties you would like to give to the processor?

I'm writing a processor that takes a list of forbidden invocations so I need to pass at least classes and method names (and probably parameters to be fully clean even if I don't have the need right now). Should maybe put that is a pull request on Spoon side when I'm happy with it as it's probably generic enough.

**Comment by surli** [comment]
> I'm writing a processor that takes a list of forbidden invocations so I need to pass at least classes and method names

Ok that's something which is not supported yet throught the maven plugin.
So, first: an easy workaround is to create a Maven module based on spoon-core, which will use your processor and to create a command line launcher to specify your parameters. 

Second: what you really want (in the future) is to be able to specify name of the Spoon Model (classes, methods, ...) and to use them inside the Processor to match some elements, right?

Something like:

```xml
<spoonModel>
  <processors>
     <processor>
        <name>my.package.CustomProcessor</name>
        <configuration>
          <include>
                <class>my.spooned.app.MyClass</class>
                <method>myMethodA</method>
         </include>
        </configuration>
       </processor>
</spoonModel>
```

**Comment by tmortagne** [comment]
I would have preferred to configure all that in the pom but sure something like that :)

**Comment by tmortagne** [comment]
Just a detail: I would also add a "reason" associated to the forbidden method or maybe even better a way to specify one or several spoon.processing.ProblemFixer to directly pass them to the report.

**Comment by surli** [comment]
>  I would also add a "reason" associated to the forbidden method or maybe even better a way to specify one or several spoon.processing.ProblemFixer to directly pass them to the report

Hm, I think I see your point, but IMHO it would make the configuration of spoon-maven-plugin customized for your own Processor and not generic at all... which is something we don't want :)

Nevertheless it could really help if you could provide more insight on your own processor: is it available somewhere?

**Comment by tmortagne** [comment]
Waiting for XWiki 9.8RC1 release and I commit it (if I commit anything on master now @gdelhumeau might want to kill me).

But it's really basic, it's just extending AbstractProcessor<CtInvocation<?>> and check if the invocation is forbidden. My current use case is forbidding the use of File#deleteOnExit.

**Comment by tmortagne** [comment]
Here is is https://github.com/xwiki/xwiki-commons/blob/master/xwiki-commons-tools/xwiki-commons-tool-spoon/src/main/java/org/xwiki/tool/spoon/ForbiddenInvocationProcessor.java

**Comment by monperrus** [comment]
Closed per https://github.com/SpoonLabs/spoon-maven-plugin/pull/44
