### ISSUE TITLE
Processor for a specific type is invoked for wrong types

### ISSUE THREAD

**Issue by ocean7** [INRIA/spoon#154]
I've got an interface Animal and I'd like to write a processor for any class that implements the Animal interface. Thought I could get this done with:

```
public class AnimalTypeProcessor extends AbstractProcessor<CtType<Animal>> { 

 public void process(CtType<Animal> animalType) { ...}
}
```

This processor is being invoked for plenty of classes... none of them are the classes I'm interested in.

**Comment by GerardPaligot** [comment]
Hi @ocean7,

Processors don't use generic type of elements specified in the processor. To do that, you need to override the method `isToBeProcessed` and filter appropriate classes.

PS: Sorry for the delay of my response.
