### ISSUE TITLE
The spoon output file after modification has some unfiltered classpath declarations.

### ISSUE THREAD

**Issue by sourabhsparkala** [INRIA/spoon#1550]
Hello I observed something while using spoon parser and modifier.

Please find the input code below:

```java
public class App {
    public static void main(String[] args) {
            System.out.println("Hello world ");
            System.out.println("Second print statement");
        }
}

/*Say I delete the the second print statement System.out.println("Second print statement");
The resulting out is shown below
*/

public class App {
    public static void main(String[] args) {
            java.lang.System.out.println("Hello world ");
        }
}
```

Why is the classpath of System.out.println i.e "java.lang" added as part of the final output, is there a prettyprint flag, which needs to be considered to create an exact output as similar to the original input?

Regards
Sourabh

**Comment by surli** [comment]
Hi @sourabhsparkala 

> Why is the classpath of System.out.println i.e "java.lang" added as part of the final output, is there a prettyprint flag, which needs to be considered to create an exact output as similar to the original input?

You may have found a bug :)

Could you provide more information: what happens if you don't delete the statement but just output the code? And do you use auto-imports mode to Spoon the code?

**Comment by sourabhsparkala** [comment]
@surli 

Hello,
It doesn't have to be cut, I think if we alter the original code  in any way, The Non-primitive data types like String, System.out.println all gets auto-imports.

I am not sure how to check for auto-imports, if you can guide me. I can confirm on that.

Regards
Sourabh

**Comment by surli** [comment]
> It doesn't have to be cut, I think if we alter the original code in any way

But did you try to *not* altering the code, only building the model and printing, and then to look the output?

> I am not sure how to check for auto-imports, if you can guide me. I can confirm on that.

What arguments are you using with the Launcher for building Spoon model?

**Comment by monperrus** [comment]
Enable autoimport to get rid of qualified / package names.

```
[--with-imports]
        Enable imports in generated files.
```

**Comment by surli** [comment]
> Enable autoimport to get rid of qualified / package names.

Even in autoimport `java.lang` should not be printed.

**Comment by sourabhsparkala** [comment]
Hello @surli  @monperrus 

Apologies for the late reply.

I ran the basic example today, without any modifications

`package com.sample.spoon;

public class App 
{
	public static float test2=0;
	public static App a=null;
    public void print()
    {
    	int test=20;
    	
    	String abc="";
    	if(test>20) {
    		System.out.println( "Testing int" + test);
    	} else {
    		System.out.println( "Testing else" + test);
    	}
    	
    	if(test<20) {
    		System.out.println( "Testing int second if" + test);
    	}    	
    }
    
    private void print2()
    {
    	int test=20;
    	if(test>20) {
    		System.out.println( "Testing int" + test);
    	} else {
    		System.out.println( "Testing else" + test);
    	}
    	
    	if(test<20) {
    		System.out.println( "Testing int second if" + test);
    	}    	
    }
}`

The Processor I defined is

`public class StatementProcessor extends AbstractProcessor<CtStatement>{
	@Override
	public void process(CtStatement statement) {
		System.out.println(statement.toString());
	}
}`

The way of calling the processor is main method
`public class AppTest {
	public static void main(String[] args) { 
		try {
			SpoonModel spooner = new SpoonModel().addSource(new File("src/main/java/com/sample/spoon/App.java"));
			spooner.process(StatementProcessor.class);
			spooner.print(new File("output/spoonedInstrument"));
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
}`

The output I get is given below:

`package com.sample.spoon;


public class App {
    public static float test2 = 0;

    public static com.sample.spoon.App a = null;

    public void print() {
        int test = 20;
        java.lang.String abc = "";
        if (test > 20) {
            java.lang.System.out.println(("Testing int" + test));
        }else {
            java.lang.System.out.println(("Testing else" + test));
        }
        if (test < 20) {
            java.lang.System.out.println(("Testing int second if" + test));
        }
    }

    private void print2() {
        int test = 20;
        if (test > 20) {
            java.lang.System.out.println(("Testing int" + test));
        }else {
            java.lang.System.out.println(("Testing else" + test));
        }
        if (test < 20) {
            java.lang.System.out.println(("Testing int second if" + test));
        }
    }
}`

I guess without any changes/modifications the classpath import is still prefixed to System.out.println

I have observed an other issue with this.

The new out put file if you observe closely, The System.out.println(("There are two enclosing ()")) , instead of System.out.println("The proper syntax")

**Comment by surli** [comment]
Hi @sourabhsparkala 

```java
SpoonModel spooner = new SpoonModel().addSource(new File("src/main/java/com/sample/spoon/App.java"));
```

If I'm right this `SpoonModel` class is not a Spoon class but your own implementation, right? Could you give me the source of this class? Or else you could tell where it comes from?

**Comment by sourabhsparkala** [comment]
Hello @surli 

Please find the the attached the customized model class and compiler class

SpoonModel.java

`package com.sample.spoon;

import org.eclipse.jdt.internal.compiler.batch.Main;
import spoon.OutputType;
import spoon.SpoonModelBuilder;
import spoon.processing.ProcessingManager;
import spoon.processing.Processor;
import spoon.reflect.declaration.CtElement;
import spoon.reflect.factory.FactoryImpl;
import spoon.support.DefaultCoreFactory;
import spoon.support.QueueProcessingManager;
import spoon.support.StandardEnvironment;

import java.io.File;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.List;

public class SpoonModel {
	
	 	final SpoonModelBuilder compiler;

	 	public SpoonModel() throws Exception {
	 		compiler = new SpoonModelCompiler(
	 				new FactoryImpl(new DefaultCoreFactory(), new StandardEnvironment()));
	 	}

	 	public SpoonModel addSource(File... files) throws Exception {
	 		for (File file : files) {
	 			compiler.addInputSource(file);
	 		}
	 		return this;
	 	}

	 	public SpoonModel addTemplate(File... files) throws Exception {
	 		for (File file : files) {
	 			compiler.addTemplateSource(file);
	 		}
	 		return this;
	 	}

	 	spoon.reflect.factory.Factory getFactory() {
	 		return compiler.getFactory();
	 	}

	 	public SpoonModel process(CtElement element, Class<? extends Processor>... processors) throws Exception {
	 		// Build spoon model
	 		compiler.build();

	 		ProcessingManager processing = new QueueProcessingManager(compiler.getFactory());

	 		for (Class<? extends Processor> processorClz : processors) {
	 			processing.addProcessor(processorClz.getName());
	 		}
	 		processing.process(element);

	 		return this;
	 	}

	 	public SpoonModel process(Class<? extends Processor>... processors) throws Exception {
	 		// Build spoon model
	 		compiler.build();
	 		
	 		List<Processor<?>> processorsNames = new ArrayList<Processor<?>>();
	 		for (Class<? extends Processor> processor : processors) {
	 			processorsNames.add(processor.newInstance());
	 		}
	 		compiler.process(processorsNames);

	 		return this;
	 	}

	 	public SpoonModel print(File dest) throws Exception {
	 		dest.mkdirs();
	 		for (File file : dest.listFiles()) {
	 			file.delete();
	 		}

	 		//   compiler.getFactory().getEnvironment().setPreserveLineNumbers(true);
	 		compiler.setSourceOutputDirectory(dest);

	 		compiler.generateProcessedSourceFiles(OutputType.COMPILATION_UNITS);
	 		return this;
	 	}

	 	public boolean compile() {
	 		File target = compiler.getSourceOutputDirectory();
	 		final boolean compile = Main.compile(new String[]{"-1.7 " , "-proc:none", target.toString()}, new PrintWriter(System.out), new PrintWriter(System.out),null);
	 		return compile;
	 	}

	 	public Class getSpoonedClass(String classname) throws ClassNotFoundException {
	 		File target = compiler.getSourceOutputDirectory();

	 		ClassLoader classLoader = new SpoonClassLoader(getClass().getClassLoader(), target);
	 		return classLoader.loadClass(classname);
	 	}
}
`
SpoonModelCompiler.java

`package com.sample.spoon;

import spoon.reflect.declaration.CtPackage;
import spoon.reflect.declaration.CtType;
import spoon.reflect.factory.Factory;
import spoon.reflect.visitor.DefaultJavaPrettyPrinter;
import spoon.support.compiler.jdt.JDTBasedSpoonCompiler;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.List;

import org.apache.commons.io.IOUtils;

public class SpoonModelCompiler extends JDTBasedSpoonCompiler {
	
	public SpoonModelCompiler(Factory factory) {
		super(factory);
	}

	protected void generateProcessedSourceFilesUsingCUs() {

		try {
			getFactory().getEnvironment().debugMessage(
					"Generating source using compilation units...");
			// Check output directory
			if (getSourceOutputDirectory() == null) {
				throw new RuntimeException(
						"You should set output directory before generating source files");
			}
			// Create spooned dir
			if (getSourceOutputDirectory().isFile()) {
				throw new RuntimeException("Output must be a directory");
			}
			if (!getSourceOutputDirectory().exists()) {
				if (!getSourceOutputDirectory().mkdirs()) {
					throw new RuntimeException("Error creating output directory");
				}
			}
			setSourceOutputDirectory(getSourceOutputDirectory().getCanonicalFile());
			getFactory().getEnvironment().debugMessage(
					"Generating source files to: " + getSourceOutputDirectory());

			List<File> printedFiles = new ArrayList<File>();
			printing:
			for (spoon.reflect.cu.CompilationUnit cu : getFactory().CompilationUnit()
					.getMap().values()) {

				getFactory().getEnvironment().debugMessage(
						"Generating source for compilation unit: " + cu.getFile());

				CtType<?> element = cu.getMainType();

				CtPackage pack = element.getPackage();

				// create package directory
				File packageDir;
				if (pack.getQualifiedName()
						.equals(CtPackage.TOP_LEVEL_PACKAGE_NAME)) {
					packageDir = new File(getSourceOutputDirectory().getAbsolutePath());
				} else {
					char dot = '.';
					// Create current package dir
					packageDir = new File(getSourceOutputDirectory().getAbsolutePath()
							+ File.separatorChar
							+ pack.getQualifiedName().replace(dot, File.separatorChar));
				}
				if (!packageDir.exists()) {
					if (!packageDir.mkdirs()) {
						throw new RuntimeException(
								"Error creating output directory");
					}
				}

				File file = new File(packageDir.getAbsolutePath()
						+ File.separatorChar + element.getSimpleName()
						+ DefaultJavaPrettyPrinter.JAVA_FILE_EXTENSION);
				file.createNewFile();

				// the path must be given relatively to to the working directory
				InputStream is = getCompilationUnitInputStream(cu.getFile()
						.getPath());

				IOUtils.copy(is, new FileOutputStream(file));

				if (!printedFiles.contains(file)) {
					printedFiles.add(file);
				}
			} // end for
		} catch (IOException e) {
			throw new RuntimeException(e);
		}
	}
}
`
SpoonClassLoader.java

`package com.sample.spoon;

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.net.MalformedURLException;

public class SpoonClassLoader extends ClassLoader {
	private final File directory;

	public SpoonClassLoader(ClassLoader classLoader, File directory) {
		super(classLoader);
		this.directory = directory;
	}

	public SpoonClassLoader(File directory) {
		this.directory = directory;
	}

	public Class loadClass(String name) throws ClassNotFoundException {
		try {
			File file = new File(directory, name.replaceAll("\\.", "/") + ".class");

			if (!file.exists()) {
				return super.loadClass(name);
			}

			InputStream input = new FileInputStream(file);
			ByteArrayOutputStream buffer = new ByteArrayOutputStream();
			int data = input.read();
			while (data != -1) {
				buffer.write(data);
				data = input.read();
			}
			input.close();
			byte[] classData = buffer.toByteArray();

			return defineClass(name, classData, 0, classData.length);
		} catch (MalformedURLException e) {
			e.printStackTrace();
		} catch (IOException e) {
			e.printStackTrace();
		}

		return null;
	}
}
`
Please let me know if you need more information.

Regards
Sourabh

**Comment by tchangalov** [comment]
@surli, @monperrus Hello, I am picking up this issue for Sourabh. I was able to enable/disable the auto-import feature. I think our issue now is that if our input file contains something like:

```Java

java.lang.System.out.println("Hello world2");

System.out.println("Hello world ");

```

(where package files may or may not be prepended) How do we ensure that the output file is identical? I believe that using the auto-import feature will change one of the above two statements, regardless of what it was set to? Is there a workaround that? I appreciate your help!

**Comment by pvojtechovsky** [comment]
> How do we ensure that the output file is identical?

That's tricky task. There is #1358, which wants to achieve that output is same like input. But it needs some time. Till then you have to accept that spoon output will have different formatting and sometime different qualified names.

**Comment by monperrus** [comment]
Spoon pretty-prints the code with some configuration (eg auto-import).

However, once the configuration is done, it pretty-prints uniformly.

This means it is impossible to have both

java.lang.System.out.println("Hello world2");
System.out.println("Hello world ");

in the pretty-printed code.

**Comment by surli** [comment]
I close this one as it seems @monperrus answered your questions. Don't hesitate to comment if you have any other issue related.
