### ISSUE TITLE
computing the list of directly tested public API classes

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#1555]
I want to compute the API of Spoon, ie the list of classes that are 1) public and 2) directly tested.
By directly tested, I mean directly used in test code, and not only indirectly executed.

Here is a piece of Spoon code to do so:

```java
		Launcher spoon = new Launcher();
		spoon.addInputResource("src/main/java");
		spoon.addInputResource("src/test/java");
		CtModel m = spoon.buildModel();

		List<CtType> testClasses = new ArrayList<>();
		List<CtType> publicAppClasses = new ArrayList<>();
		for (CtType t : m.getAllTypes()) {
			if (t.getQualifiedName().matches("(?i:.*test.*)")) {
				testClasses.add(t);
			} else if (
					t instanceof CtClass
					&& t.getModifiers().contains(ModifierKind.PUBLIC)
					&& !t.getModifiers().contains(ModifierKind.ABSTRACT)
					&& !t.getPackage().getQualifiedName().contains("internal")
					&& !t.getSimpleName().endsWith("Impl")
					&& !isHelperClassWithOnlyStaticMethods(t)
			) {
				publicAppClasses.add(t);
			}
		}

		List<String> publicAppClassesTested = new ArrayList<>();
		List<String> publicAppClassesNotDirectlyTested = new ArrayList<>();
		// now checking if all public app classes are used in a test
		publicAppClasses.parallelStream().forEach(t -> {
				boolean isTested = testClasses.parallelStream().anyMatch(x ->
						x.getElements((CtExpression v) -> v.getType() != null && v.getType().equals(t.getReference())).size()>0
						|| x.getElements((CtVariable v) -> v.getType() != null && v.getType().equals(t.getReference())).size()>0

						// if used in instanceof
						|| x.getElements((CtTypeAccess v) -> v.getAccessedType() != null && v.getAccessedType().equals(t.getReference())).size()>0
				);
				if (!isTested) {
					publicAppClassesNotDirectlyTested.add(t.getQualifiedName());
				} else {
					publicAppClassesTested.add(t.getQualifiedName());
				}
		});

		System.out.println("Public classes tested ("+publicAppClassesTested.size()+"):");
		System.out.println();
		for (String t: publicAppClassesTested) {
			System.out.println("* "+t);
		}

		System.out.println();
		System.out.println();

		System.out.println("Public classes NOT directly tested ("+publicAppClassesNotDirectlyTested.size()+"):");
		System.out.println();
		for (String t: publicAppClassesNotDirectlyTested) {
			System.out.println("* "+t);
		}

```

**Comment by monperrus** [comment]
I'm quite surprised by the results for Spoon itself, with a high number of not directly tested public classes.

WDYT?

Public classes tested (101 classes): ....

Public classes NOT directly tested (80 classes):

* spoon.reflect.visitor.filter.AllTypeMembersFunction
* spoon.reflect.visitor.printer.CommentOffset
* spoon.reflect.path.CtPathException
* spoon.generating.clone.GetterTemplateMatcher
* spoon.reflect.visitor.filter.AnnotationFilter
* spoon.reflect.path.impl.CtNamedPathElement
* spoon.generating.clone.SetterTemplateMatcher
* spoon.support.RuntimeProcessingManager
* spoon.reflect.path.impl.CtRolePathElement
* spoon.generating.replace.ReplaceScanner
* spoon.reflect.visitor.filter.DirectReferenceFilter
* spoon.legacy.NameFilter
* spoon.reflect.path.impl.CtTypedNameElement
* spoon.support.comparator.QualifiedNameComparator
* spoon.reflect.visitor.AccessibleVariablesFinder
* spoon.reflect.visitor.filter.FieldReferenceFunction
* spoon.processing.SpoonTagger
* spoon.support.comparator.SignatureComparator
* spoon.reflect.visitor.AstParentConsistencyChecker
* spoon.reflect.visitor.filter.FieldScopeFunction
* spoon.processing.TraversalStrategy
* spoon.reflect.visitor.CtDequeScanner
* spoon.refactoring.Refactoring
* spoon.support.compiler.SnippetCompilationError
* spoon.reflect.visitor.EarlyTerminatingScanner
* spoon.reflect.Changes
* spoon.reflect.factory.EvalFactory
* spoon.reflect.visitor.JavaIdentifiers
* spoon.reflect.ModelElementContainerDefaultCapacities
* spoon.support.compiler.ZipFile
* spoon.support.compiler.ZipFolder
* spoon.experimental.modelobs.EmptyModelChangeListener
* spoon.reflect.cu.position.NoSourcePosition
* spoon.reflect.visitor.PrinterHelper
* spoon.support.compiler.jdt.ASTPair
* spoon.experimental.modelobs.action.AddAction
* spoon.reflect.visitor.PrintingContext
* spoon.experimental.modelobs.action.DeleteAction
* spoon.reflect.visitor.TypeContext
* spoon.reflect.visitor.filter.PotentialVariableDeclarationFunction
* spoon.experimental.modelobs.action.DeleteAllAction
* spoon.reflect.visitor.filter.RegexFilter
* spoon.experimental.modelobs.action.UpdateAction
* spoon.support.util.QualifiedNameBasedSortedSet
* spoon.experimental.modelobs.context.ListContext
* spoon.reflect.visitor.filter.SiblingsFunction
* spoon.support.util.SignatureBasedSortedSet
* spoon.experimental.modelobs.context.MapContext
* spoon.reflect.visitor.filter.SubtypeFilter
* spoon.experimental.modelobs.context.ObjectContext
* spoon.support.util.Timer
* spoon.reflect.visitor.filter.VariableAccessFilter
* spoon.experimental.modelobs.context.SetContext
* spoon.support.visitor.HashcodeVisitor
* spoon.support.visitor.ProcessingVisitor
* spoon.support.gui.SpoonModelTree
* spoon.support.visitor.clone.CloneBuilder
* spoon.support.gui.SpoonObjectFieldsTable
* spoon.support.visitor.clone.CloneVisitor
* spoon.support.gui.SpoonTreeBuilder
* spoon.support.visitor.TypeReferenceScanner
* spoon.support.visitor.equals.EqualsChecker
* spoon.support.compiler.jdt.ContextBuilder
* spoon.support.visitor.equals.EqualsVisitor
* spoon.support.compiler.jdt.FactoryCompilerConfig
* spoon.support.template.DefaultParameterMatcher
* spoon.support.compiler.jdt.FileCompilerConfig
* spoon.support.visitor.java.reflect.RtMethod
* spoon.support.template.UndefinedParameterException
* spoon.support.util.EmptyClearableList
* spoon.support.visitor.java.reflect.RtParameter
* spoon.support.compiler.jdt.JDTTreeBuilder
* spoon.support.visitor.replace.ReplacementVisitor
* spoon.support.util.EmptyClearableSet
* spoon.support.compiler.jdt.JDTTreeBuilderHelper
* spoon.template.TemplateException
* spoon.support.util.EmptyIterator
* spoon.support.compiler.jdt.ParentExiter
* spoon.support.compiler.jdt.PositionBuilder
* spoon.support.compiler.jdt.ReferenceBuilder

**Comment by tdurieux** [comment]
I think there are some false positive. For example I am pretty sure I used nosouceposition in a test, and i think I saw EarlyTerminatingScanner in a test

**Comment by monperrus** [comment]
update the code to handle instanceof (the only usage of NoSourcePosition).

In my IDE I don't see a test usage of EarlyTerminatingScanner.

**Comment by surli** [comment]
Maybe push it as a new test (like #1365 for imports) and we can improve tests piece by piece
