### ISSUE TITLE
deploy snapshot to http://maven.inria.fr/ instead of gforge

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#1557]

**Comment by surli** [comment]
We finally got the credentials to deploy on maven.inria.fr but I don't see how to easily deploy both on gforge AND maven.inria.fr. 

So if we change to deploy on maven.inria.fr there might be a service interruption for users using Snapshot release. However it might be a good time to do the change as we just release a version of Spoon. WDYT?

**Comment by monperrus** [comment]
I'm OK to deploy Snapshots on maven.inria.fr only, even with a small interruption.

**Comment by monperrus** [comment]
closed per #1900
