### ISSUE TITLE
feat: add method CtTypeInformation#isParametrized()

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#1565]
cool idea of @pvojtechovsky 

What about adding another method `CtTypeInformation#isParametrized()`, with this contract

Type | isParametrized() | isGenerics() 
------|-------------------|----
Integer | false | false
List\<Integer\> | true | false
List\<T\> | true | true

**Comment by Egor18** [comment]
It seems like `type.isParameterized()` would be just an alias for `!type.getActualTypeArguments().isEmpty()`.
Do we actually need that?

**Comment by monperrus** [comment]
The value of a method is not measured by its complexity, but by how it helps users.

If this new method helps newcomers to write their analysis or transformation, that's good IMHO.
