### ISSUE TITLE
Why CtReference and children are not annotated with @PropertyGetter and @PropertySetter ?

### ISSUE THREAD

**Issue by pvojtechovsky** [INRIA/spoon#1569]
@tdurieux  Why CtReference and children are not annotated with @PropertyGetter and @PropertySetter ?

I though that references of Spoon model are part of model same like elements, I recognized just now that @PropertyGetter and @PropertySetter annotations are missing on whole class hierarchy of CtReference.

Is it intentional? Is it planned to add these annotations there too?

**Comment by monperrus** [comment]
Good question.

Conceptually, a reference is only a string with no property. In theory it should be doable to
correctly pretty-print the whole model only using the simpleName of  references.

That's the reason: the pretty-printable model itself ends at the boundary of references. Beyond,
it's low-level information for resolving them (ie for getDeclaration).

This is open to discussion if there is a need to @PropertyGetter <https://github.com/propertygetter>
and @propertysetter there.

**Comment by pvojtechovsky** [comment]
I do not have clear opinion about result of this discussion, so just some notes:
Sometime more then simpleName is needed. For example:
* CtExecutableReference has 
  * List<CtTypeReference<?>> actualTypeArguments - which are not only the copy of something else in model, but brings new information in it.
  * List<CtTypeReference<?>> parameters - which are needed to found correct method declaration
* CtTypeReference has
  * CtPackageReference pack - which builds complex qualified reference

etc.

And even if only CtReference#simpleName would be needed, I expected before that it should be annotated too. I did not understood why references are somehow considered to be not part of the spoon model.

So I actually vote for adding of these annotations to references too.

**Comment by monperrus** [comment]
> I did not understood why references are somehow considered to be not part of the spoon model.
You now, we had two separate class hierarchies for more than 10 years: elements and references :-).
We unified them 2 years ago.

> So I actually vote for adding of these annotations to references too.
>
I'm fine with that too.

**Comment by pvojtechovsky** [comment]
@tdurieux I will need these CtRoles on CtReference children to implement #1582 do you have some algorithm which might bring these roles into Spoon reference API automatically? Or should I do it manually?

**Comment by tdurieux** [comment]
I generated the roles (maybe some are missing) for the references in this branch: https://github.com/tdurieux/spoon/tree/role_reference

**Comment by pvojtechovsky** [comment]
Super! Thanks! I will use it

**Comment by pvojtechovsky** [comment]
@tdurieux  Are you going to make a PR from this branch, or should I takeover the changes make own PR?
I will base my new code on your branch, so later we will need Your changes merged too.

**Comment by tdurieux** [comment]
I will do a PR, Martin likes baby pr :)

**Comment by pvojtechovsky** [comment]
> I will do a PR,

Super! So I can focus on generators and detection of problems ;-) 

There are some problems in new roles of CtReferences:
All getters have role CtRole.TYPE:
* CtTypeReference#getTypeDeclaration()
* CtTypeReference#getDeclaringType()
* CtExecutableReference#getDeclaringType()
* CtExecutableReference#getType() - CtRole.TYPE is correct here
* CtFieldReference#getDeclaringType()
* CtFieldReference#getType() - CtRole.TYPE is correct here

I suggest to have new role CtRole.DECLARING_TYPE and it would be applied to
* CtTypeReference#getDeclaringType()
* CtExecutableReference#getDeclaringType()
* CtFieldReference#getDeclaringType()

And there remains 
* CtTypeReference#getTypeDeclaration()
* CtExecutableReference#getExecutableDeclaration()
* CtField#getFieldDeclaration()
* ... ?
What about new CtRole.DEREFERENCE ?

WDYT?

**Comment by tdurieux** [comment]
> All getters have role CtRole.TYPE:

I already fixed this.

> CtTypeReference#getTypeDeclaration()
CtExecutableReference#getExecutableDeclaration()
CtField#getFieldDeclaration()
... ?
What about new CtRole.DEREFERENCE ?

most of them are DerivedProperty, no?

**Comment by pvojtechovsky** [comment]
Fixed by #1586
