### ISSUE TITLE
Unexpected behaviour when processing

### ISSUE THREAD

**Issue by DaveJarvis** [INRIA/spoon#1573]
Consider the following `main` program:

``` .java
public static void main(String args[]) {
    final List<String> processors = getProcessorClassNames();
    final Launcher launcher = new Launcher();

    // Drop in the processors by name.
    for (final String processor : processors) {
        launcher.addProcessor(processor);
    }

    launcher.getEnvironment().setNoClasspath(true);

    launcher.addInputResource("Project/src");
    launcher.setSourceOutputDirectory("Project/spoon");
    launcher.buildModel();
    launcher.process();
}
```

And:

``` .java
public class EmptyCatchProcessor extends AbstractProcessor<CtCatch> {

    private static final String CLASSNAME = EmptyCatchProcessor.class.getName();
    private static final Logger LOG = Logger.getLogger(CLASSNAME);

    @Override
    public void process(final CtCatch element) {
        final CtBlock<?> body = element.getBody();
        final List<CtStatement> statements = body.getStatements();

        if (statements.isEmpty()) {
            LOG.log(Level.WARNING, "Empty catch clause", element);
        } else {
            LOG.log(Level.INFO, "No empty catch clause found");
        }
    }
}
```

The `process( final CtCatch element )` method is never called even though an EmptyCatchProcessor is instantiated. It seems strange that `AbstractProcessor` has a `final` process method:

``` .java
	/**
	 * The manual meta-model processing cannot be overridden (use
	 * {@link AbstractManualProcessor}) to do so.
	 */
	public final void process() {
	}
```

`ProcessingVisitor::canBeProcessed` calls `processor.getProcessedElementTypes()` twice, which violates DRY. Defining additional methods results in:

``` .java
private boolean canBeProcessed(final CtElement e) {
    // getProcessedElementTypes() returns a set, even if empty, never null.
    final Set<Class<? extends CtElement>> elementTypes = getProcessedElementTypes();
    boolean result = false;

    // null check eliminated, and thank you Tony Hoare /s.
    // https://www.lucidchart.com/techblog/2015/08/31/the-worst-mistake-of-computer-science/
    if (isProcessing()) {
        result = true;

        for (Object o : elementTypes) {
            if (!((Class<?>) o).isAssignableFrom(e.getClass())) {
                result = false;
                break;
            }
        }
    }

    return result;
}
```

This approach hides some implementation details that the `canBeProcesssed` method needn't be concerned about, leading to code that's easier to maintain. That is, making the factory/processor instance variables private and pulling them up into a common superclass (or other such refactoring) will not affect `canBeProcessed`.

With that out of the way, where can I find an example of processing from within an application (e.g., the "main" above) that can leverage the `AbstractProcessor<E>` infrastructure? Having a difference between running Spoon from the command line and leveraging the API from within a Java program seems to violate the [principle of least astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment).

The suggested alternative (`AbstractManualProcessor`) requires much more effort. The following code, for example, won't compile because the `CtCatch` element is not readily available:

``` .java
public class EmptyCatchProcessor extends AbstractManualProcessor {

    private static final String CLASSNAME = EmptyCatchProcessor.class.getName();
    private static final Logger LOG = Logger.getLogger(CLASSNAME);

    @Override
    public void process() {
        final CtBlock<?> body = element.getBody();
        final List<CtStatement> statements = body.getStatements();

        if (statements.isEmpty()) {
            LOG.log(Level.WARNING, "Empty catch clause", element);
        } else {
            LOG.log(Level.INFO, "No empty catch clause found");
        }
    }
}
```

Getting a handle on the `CtCatch` statement is trivial by extending `AbstractProcessor<CtCatch>`.

**Comment by monperrus** [comment]
Thanks for the bug report. Would you have a failing test case that we can look at?

**Comment by DaveJarvis** [comment]
There is no failing test case, sorry. The `main()` program as written with the methods defined in a [separate discussion thread](https://github.com/INRIA/spoon/issues/1563#issuecomment-334524485) (to get `getProcessorClassNames()` using the [Reflections](https://github.com/ronmamo/reflections) library) shows that the `process( CtCatch )` method is never called.

**Comment by monperrus** [comment]
This is basic usage that is heavily used in many projects and should work.

One possibility is that |getProcessorClassNames()| returns an empty list.

**Comment by DaveJarvis** [comment]
`getProcessorClassNames()` returns a list of one item.

**Comment by DaveJarvis** [comment]
Works as expected.
