### ISSUE TITLE
Null pointer exception in CtModel

### ISSUE THREAD

**Issue by krlu** [INRIA/spoon#1575]
I am using the Spoon API in scala and I simply want to add some new methods to a class (without knowing anything about the class of course) and I keep getting a null pointer exception. Code shown below:  
```
  def main(args: Array[String]): Unit = {
    val launcher = new Launcher
    launcher.addInputResource("...some source code.....")
    launcher.getEnvironment.setAutoImports(true)
    launcher.getEnvironment.setNoClasspath(true) // optional
    launcher.buildModel()
    val model: CtModel = launcher.getModel
    val fullModel = model.getAllTypes.head
    val constants = findConstants(model)
    val returnType = new CtTypeReferenceImpl[Int]()
    returnType.setSimpleName("void")
    constants.foreach(const => {
      val varType: CtTypeReference[Int] = const.getType
      val varName = const.getAssigned
      val paramType = new CtParameterImpl[Int]
      paramType.setType(varType)
      paramType.setSimpleName("newValue")
      val method: CtMethod[Int] = createMethod(returnType, paramType, varName)
      println(method)
    })
    println(fullModel)
  }

  private def createMethod(returnType: CtTypeReference[Int], paramType: CtParameter[Int], assignmentVar: CtExpression[Int]): CtMethod[Int] = {
    val method = new CtMethodImpl[Int]
    method.setType(returnType)
    method.setModifiers(Set(ModifierKind.STATIC, ModifierKind.PUBLIC))
    method.setSimpleName(s"update${assignmentVar.toString.replace("this.", "").capitalize}")
    method.addParameter(paramType)
    val expression = new CtVariableReadImpl[Int]
    val localVar = new CtLocalVariableReferenceImpl[Int]
    localVar.setSimpleName(paramType.getSimpleName)
    expression.setVariable(localVar)
    val statement = new CtAssignmentImpl[Int, Int]()
    statement.setAssignment(expression)
    statement.setAssigned(assignmentVar)
    method.setBody(statement)
    method
  }

  private def findConstants(model: CtModel): Seq[AssignmentType] = {
    // find constants
    val methodFilter = new TypeFilter[MethodType](classOf[MethodType])
    val assignmentFilter = new TypeFilter[AssignmentType](classOf[AssignmentType])
    val assignedVariables = model.getElements(assignmentFilter).toList
    val methodElements: Seq[PathPlannerAnalysis.MethodType] = model.getElements(methodFilter).toList
    val nonConstantElements = methodElements.flatMap(e => e.getElements(assignmentFilter).toList)
    assignedVariables.filter(!nonConstantElements.contains(_))
  }
```

However, if in the main method I move `println(fullModel)` to the line above the `foreach` statement, it no longer crashes. 
Is it possible that when performing transformations, I am mutating the original model?

As an aside, if there are any sources on how to use Spoon in a Scala environment, that would be greatly appreciated!

**Comment by tdurieux** [comment]
Your bug is on the line new CtMethodImpl. You have to use the factory to create the CtXXX the factory is accessible on every CtElement with the method getFactory

**Comment by krlu** [comment]
To make sure I understand. In the for each loop above, am I supposed to take the CtElement `const` and do 
'const.getFactory()' and then use that factory to generate all the required components I need? And I should I always be using the factory to generate things instead of creating a `new` instance manually?

**Comment by pvojtechovsky** [comment]
yes, you should always use factory to create new elements. Optionally you can clone existing elements.

But it is a lot of work to generate new AST model elements by individual node creations. Have a look at Spoon [templates](http://spoon.gforge.inria.fr/template_definition.html), which are elegant tool for such code generation tasks.

**Comment by krlu** [comment]
Ok thanks!
