### ISSUE TITLE
spoon.compiler.ModelBuildingException: The type java.lang.Object cannot be resolved.

### ISSUE THREAD

**Issue by orichalque** [INRIA/spoon#1583]
Hi, I've been using Spoon within an Eclipse plugin, and it was running quite fluently. Nonetheless I'm trying to use it now inside a standalone Maven project. 
I need to rewrite the source code of an application with several other LOC in it, and compile it afterwards.
I re-used the Spoon Launcher configuration I had before, but now it won't work and I have the following message:

```
spoon.compiler.ModelBuildingException: The type java.lang.Object cannot be resolved. It is indirectly referenced from required .class files at /.../MyClass.java:1
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.report(JDTBasedSpoonCompiler.java:597)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.reportProblems(JDTBasedSpoonCompiler.java:578)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:126)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:107)
	at spoon.Launcher.buildModel(Launcher.java:705)
	at spoon.Launcher.run(Launcher.java:656)
```
My configuration is the following:

```
        Launcher spoonLauncher = new Launcher();

        spoonLauncher.getEnvironment().setShouldCompile(true);
        spoonLauncher.getEnvironment().setAutoImports(true);
        spoonLauncher.getEnvironment().setNoClasspath(false);

        spoonLauncher.addInputResource(directory.toString());

        spoonLauncher.setBinaryOutputDirectory(binDirectory);
        spoonLauncher.setSourceOutputDirectory(srcDirectory);

        spoonLauncher.run();
```

And finally the java file I'm rewriting is a standard "HelloWorld" classfile.
When I set "NoClasspath" to true, the file will be written, but not compiled, with a similar error:

```
2017-10-09 10:40:43,359 WARN spoon.Launcher - warning: The type java.lang.Object cannot be resolved. It is indirectly referenced from required .class files at /.../MyClass.java:1
2017-10-09 10:40:43,360 WARN spoon.Launcher - warning: The type java.lang.String cannot be resolved. It is indirectly referenced from required .class files at /.../MyClass.java:1
```

Am I supposed to add the JRE to the classpath ? How ? 
Thank you.

**Comment by surli** [comment]
I just tried with a small maven project and it works for me. 
How do you launch exactly your project? Through your IDE? or directly through a java -jar after a mvn package? 
Do you use a specific maven configuration for packaging? 
It's clearly a classpath issue, but here I don't think it's directly related to Spoon.

**Comment by orichalque** [comment]
Right now this is launched through the IDE, by running JUnit test cases. 
I'll try running it in a different environment. If it's not Spoon related then I'll  have to look somewhere else then ;-)

**Comment by surli** [comment]
> Right now this is launched through the IDE, by running JUnit test cases.

I just test to put my test in a Junit test, it works both running with a `mvn test` and inside IntelliJ IDEA.

**Comment by monperrus** [comment]
I would say that this is due to setShouldCompile(true).

What happens if you set it to false?

**Comment by orichalque** [comment]
I made a new mvn project from scratch, and I'm still having the same error. Both when running with JUnit and Mvn. I made an archive with the sources: 

[mvn project](https://github.com/INRIA/spoon/files/1368365/SpoonTest.zip)

Could you tell me if there's something wrong with the code I'm using ?

**Comment by orichalque** [comment]
@monperrus 
Hi, I'm having the same error with `setShouldCompile(false)`

**Comment by surli** [comment]
@orichalque Ok I don't have Java 9 on my machine, so I just change the target release on your pom.xml and it works fine for me: 

```
<maven.compiler.source>1.8</maven.compiler.source>
<maven.compiler.target>1.8</maven.compiler.target>
```

**Comment by orichalque** [comment]
I changed the Java version on my machine and my IDE (IntelliJ) to the jdk1.8.0_131  and now it's working.

Thank you for your help :-)

**Comment by surli** [comment]
Good.
