### ISSUE TITLE
Trying to get all assignments in a method

### ISSUE THREAD

**Issue by krlu** [INRIA/spoon#1594]
I am using the Spoon API in a scala program. 

I have some method type `val someFunction: MethodType` and I want to extract all variable assignments by doing this: 

```
type AssignmentType = CtAssignment[Any, Any]
val assignmentFilter = new TypeFilter[AssignmentType](classOf[AssignmentType])
val assignments: List[AssignmentType] = someFunction.getBody.getElements(assignmentFilter).toList
```

However, I notice that the `assignment` list is missing initialization statements such as : 

`double variable = 1.0` 

And instead only include instances where those variables are re-assigned. 
I'm trying to find some "CtInitialize" type but I can't find it. I presume there's some pattern for this, but I'm not looking in the right place.

Any help is appreciated.

**Comment by monperrus** [comment]
"double variable = 1.0" is a variable definition (CtField or 
CtLocalVariable)

What you look for are instances of CtRHSReceiver

val assignmentFilter = new TypeFilter[CtRHSReceiver](classOf[CtRHSReceiver])

--Martin
