### ISSUE TITLE
perf: it seems that recent commits changed the perf of Spoon

### ISSUE THREAD

**Issue by surli** [INRIA/spoon#1595]
We got some `OutOfMemoryException` when executing MainTest on the CI, that we never had before. 

See: https://ci.inria.fr/sos/job/Spoon%20Install%20Commit%20Hook/301/console

**Comment by monperrus** [comment]
I'd say it's not the perf of Spoon but the memory footprint of MainTest.

maybe because of the millions of execption objects created

**Comment by pvojtechovsky** [comment]
Yes, it can be!

**Comment by pvojtechovsky** [comment]
The Exceptions are needed just for debugging in case of problem. So we can change the test so it only reports: "There is problem" without details... then it needs less memory

**Comment by monperrus** [comment]
closed per #1596
