### ISSUE TITLE
Trying to construct mathematical expressions

### ISSUE THREAD

**Issue by krlu** [INRIA/spoon#1597]
I want to create the following expression as a CtExpression: 
```
val x = a + b
```
where a and b are some `Double` values. 

I see that there is a `CtUnaryOperator` type, but it's not clear to me how to use it. 
Any help appreciated.

**Comment by pvojtechovsky** [comment]
Hi! 

If you need to generate any code, then have a look at templates. It is the fastest way to generate simple or complex code [Transformation with Templates](http://spoon.gforge.inria.fr/template_definition.html)

Good luck! ;-)
