### ISSUE TITLE
feat: add method to run compilation checkings on a transformed model 

### ISSUE THREAD

**Issue by surli** [INRIA/spoon#1598]
If `shouldCompile` is set in Environment, it currently means that when running `run()` on Launcher, we will check that a code can be compiled.
However, if we get a model, transform it, and want to check if it still can be compiled it's a little bit of work. 
I would be great to add a new method to check that easily.

**Comment by monperrus** [comment]
Closing this old issue now that we have [`ModelConsistencyChecker`](https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/reflect/visitor/ModelConsistencyChecker.java).

Improvements to `ModelConsistencyChecker` welcome in pull-requests!
