### ISSUE TITLE
Uncorrect parsing of field with generic type fully quallified name

### ISSUE THREAD

**Issue by nharrand** [INRIA/spoon#1607]
When trying to parse the class below, the field
```java
class Test {
   path.to.pack.Target<Object, Object> field;
}
```
is parsed as
```java 
import path.to.pack.Target<Object, Object>;
class Test {
   Target<Object, Object><Object, Object> field;
}
```

Spoon was called as :
```java
Launcher launcher = new Launcher();
launcher.addInputResource(srcDir.getPath());
launcher.getEnvironment().setAutoImports(true);
launcher.getEnvironment().setNoClasspath(true);
launcher.getEnvironment().setComplianceLevel(8);
launcher.buildModel();

CtModel model = launcher.getModel();
```

**Comment by surli** [comment]
Hi @nharrand 

If you use the argument `launcher.getEnvironment().setAutoImports(true);` it means that Spoon will try to import every types which is not in the current package.

**Comment by surli** [comment]
Thanks for reporting this one @nharrand. Working on it!

**Comment by surli** [comment]
@nharrand The fix has been merged: you can use last SNAPSHOT of Spoon before we release the fix.

**Comment by nharrand** [comment]
Thanks!
