### ISSUE TITLE
bug: auto-imports for package-info.java files is not supported

### ISSUE THREAD

**Issue by szaluk** [INRIA/spoon#1608]
Is it possible to programmatically create package-info.java files using Spoon?  I have the code working where it iterates over the packages, checks to see if a certain condition is met in the classes and now what I need to do is to create a package-info.java file with an annotation set.  I created the processor to do the rest but I don't see a way to create the package-info.java file.  I can do it with the I/O classes in Java but wanted to see if there was a better way using Spoon.

Thanks,
Steve

**Comment by monperrus** [comment]
Interesting usage.

If you add an annotation to a CtPackage object, it should work.

**Comment by szaluk** [comment]
That worked!

This is what it generated:

```
@com.company.annotations.TestData(createdBy = "name", priority = com.company.enums.priority.Priority.HIGH, tags = { "tag1" , "tag2" }, team = com.company.enums.team.Team.NONE, testSubType = com.company.enums.testtype.TestSubType.XLT, testType = com.company.enums.testtype.TestType.UNIT)
package test.server.com.company;

```
Is there anyway to get it to generate like this instead without the fully qualified packages:

```
@TestData(team = Team.NONE, priority = Priority.HIGH, tags = { "tag1", "tag2" }, createdBy = "name", testType = TestType.UNIT, testSubType = TestSubType.XLT)
package test.server.com.company;

import com.company.annotations.TestMetaData;
import com.company.enums.priority.Priority;
import com.company.enums.team.Team;
import com.company.enums.testtype.TestSubType;
import com.company.enums.testtype.TestType;
```

**Comment by monperrus** [comment]
Maybe :-)

Have you tried setting autoimport to true?

**Comment by szaluk** [comment]
Yes, I do have that set.

**Comment by szaluk** [comment]
Auto import works great for the other processors I have implemented for my classes and methods.

**Comment by monperrus** [comment]
@surli ? how to plug ImportScanner on package-info creation?

**Comment by surli** [comment]
@szaluk I just fixed your issue concerning using imports in package-info files. Not released yet, but you should be able to use it with the SNAPSHOT version of Spoon.

**Comment by szaluk** [comment]
@surli @monperrus Thanks for all the help and the quick turnaround!
