### ISSUE TITLE
addModifier documentation out of sync

### ISSUE THREAD

**Issue by DaveJarvis** [INRIA/spoon#1616]
http://spoon.gforge.inria.fr/mvnsites/spoon-core/apidocs/spoon/reflect/declaration/CtModifiable.html

> <T extends CtModifiable> T addModifier(ModifierKind modifier)
> Returns: true if this element changed as a result of the call

However, the code does not return a Boolean:

``` .java
	@Override
	public <C extends CtModifiable> C addModifier(ModifierKind modifier) {
		if (modifiers == CtElementImpl.<ModifierKind>emptySet()) {
			this.modifiers = EnumSet.noneOf(ModifierKind.class);
		}
		getFactory().getEnvironment().getModelChangeListener().onSetAdd(this, MODIFIER, this.modifiers, modifier);
		modifiers.add(modifier);
		return (C) this;
	}
```

This documentation issue is applicable to all implementations of `addModifier`.

Recommend the Javadocs be updated to indicate whether there's a way to determine that a modifier was added versus already existed.

**Comment by monperrus** [comment]
Thanks for the report. Would you a do a pull request to fix the documentation?
