### ISSUE TITLE
CtType#getAllMethods contract seems not respected

### ISSUE THREAD

**Issue by surli** [INRIA/spoon#1618]
Looking on `CtType#getAllMethods` we have the following comment (see: https://github.com/INRIA/spoon/blob/40e15b299ac462fb2facddb777ab5bb3cae65458/src/main/java/spoon/reflect/declaration/CtType.java#L211)

> Up to 5.2: The recursion stops when the super-type/super-interface is not in the model,
	 which means that no method of library super-classes, or of Object are present.

However when looking on the test `CtTypeInformationTest#testGetSuperclass` we explicitely try to obtain methods from Object 
See: https://github.com/INRIA/spoon/blob/40e15b299ac462fb2facddb777ab5bb3cae65458/src/test/java/spoon/reflect/declaration/CtTypeInformationTest.java#L139

So either the contract is wrongly defined, or the implementation is wrong.

**Comment by monperrus** [comment]
The documentation is wrong.

(the behavior has been changed with the introduction of shadow classes some time ago)

**Comment by surli** [comment]
Ok, and do we agree that for a given class and its associated CtClass we should have the following contract: 

MyClass.class.getMethods().length == MyCtClass.getAllMethods().size() ?

**Comment by monperrus** [comment]
No, because we have the methods of objects

MyCtClass.getAllMethods().size()  == MyClass.class.getMethods().length + Object.methods.size

**Comment by surli** [comment]
> No, because we have the methods of objects

Actually getMethods() also return Object method. The main difference is `getMethods()` of Java only return public methods, and do not duplicate overriden method even when they don't have exactly the same signature (like with generics)

**Comment by surli** [comment]
Fixed in #1644
