### ISSUE TITLE
Test Code isn't human readable because enums and static values are fully qualified

### ISSUE THREAD

**Issue by ocean7** [INRIA/spoon#162]
We're using spoon to generate some documentation. As part of this effort we're actually including some of the Java code in a generated website. We use CtMethod.getBody().toString() to get the code associated with a special annotated method. The string returned from this method has enums and other static variables fully qualified. Can this be disabled? The actual code itself (that's parsed by spoon) doesn't use fully qualified names to refer to enums (it relies on Java import mechanism). Could spoon by default return a faithful copy of the actual code?

**Comment by GerardPaligot** [comment]
You can generate your source code with the option `--with-imports` from the launcher. This should centralize all imports in the header of your classes and no more use fully qualified names in your source code. But this option is a little bit experimental.

**Comment by ocean7** [comment]
This doesn't seem to work. Tried passing this option to the Launcher ctor:

```
    private static SpoonCompiler createSpoonCompiler(final Factory factory) {
        Launcher launcher = new Launcher() {
            @Override
            public Factory createFactory() {
                return factory;
            }
        };
        launcher.setArgs(new String[] { "--with-imports" });
        return launcher.createCompiler();
    }
```

**Comment by GerardPaligot** [comment]
You seems to use directly a compiler and not the launcher. Test something like this:

```java
private static SpoonCompiler createSpoonCompiler(final Factory factory) {
    Launcher launcher = new Launcher() {
        @Override
        public Factory createFactory() {
            return factory;
        }
    };
    factory.getEnvironment().setAutoImports(true);
    return launcher.createCompiler();
}
```

**Comment by ocean7** [comment]
Yes, this doesn't work either.

Actually creating the factory and the launcher like:

```
StandardEnvironment spoonEnvironment = new StandardEnvironment();
		spoonEnvironment.setComplianceLevel(8);
		spoonEnvironment.setVerbose(true);
		spoonEnvironment.setAutoImports(true);
		 
		Factory factory = new FactoryImpl(new DefaultCoreFactory(), spoonEnvironment);
```

**Comment by GerardPaligot** [comment]
@ocean7 In the next snapshot (or release), you can print any elements with imports.
