### ISSUE TITLE
bug: import of interface class in JDTImportBuilder

### ISSUE THREAD

**Issue by tdurieux** [INRIA/spoon#1628]
I don't understand the `klass.isInterface()` in this line:

https://github.com/INRIA/spoon/blob/4ed07f7395ad0b46a0ec360388fe5a0be6f98ac0/src/main/java/spoon/support/compiler/jdt/JDTImportBuilder.java#L115

For me we should never import method from interfaces, it means nothing.
Do I miss something?

**Comment by surli** [comment]
> For me we should never import method from interfaces, it means nothing.

I think you're right that there's a problem: we should not import all methods from interfaces, but they can also contain static methods or fields, and we should import them as for standard classes. 
So the condition should be changed.
