### ISSUE TITLE
Trying to find the imports of a class model

### ISSUE THREAD

**Issue by krlu** [INRIA/spoon#1629]
I have the following scala code: 

```
    val launcher = new Launcher
    launcher.addInputResource("SomeClass.java")
    launcher.getEnvironment.setAutoImports(true)
    launcher.getEnvironment.setNoClasspath(true)
    launcher.buildModel()
    val model: CtModel = launcher.getModel
    println(model.getAllTypes)
```
However, when I print `model.getAllTypes` I don't see the import statements at the top being printed. Is there a way for me to get them? I noticed there is an `ImportScanner` object, but it looks like I'd have to go into each element to find the relevant imports.

**Comment by surli** [comment]
Hi @krlu 

For now the import are not directly part of Spoon model, so cannot get computed imports unless you use yourself the ImportScanner.
However, if you only want to retrieve the original imports, you can get them through CompilationUnit:

```java
String path = "path/of/compilationUnit.java";
CompilationUnit cu = launcher.getFactory().CompilationUnit().create(path);
cu.getImports(); // return a set of CtReference
```

You can retrieve your interesting path from a CtType by using `getPosition().getFile()`.

**Comment by krlu** [comment]
Thanks so much!

**Comment by kenail2002** [comment]
> Hi @krlu
> 
> For now the import are not directly part of Spoon model, so cannot get computed imports unless you use yourself the ImportScanner. However, if you only want to retrieve the original imports, you can get them through CompilationUnit:
> 
> ```java
> String path = "path/of/compilationUnit.java";
> CompilationUnit cu = launcher.getFactory().CompilationUnit().create(path);
> cu.getImports(); // return a set of CtReference
> ```
> 
> You can retrieve your interesting path from a CtType by using `getPosition().getFile()`.

perfect
