### ISSUE TITLE
Define order of scanning of fields in Spoon model

### ISSUE THREAD

**Issue by pvojtechovsky** [INRIA/spoon#1634]
It would be helpful to generate CtScanner automatically from the information stored in interfaces of spoon.reflect.... packages.

How to define that order? Each leaf interface of spoon model would contain class level annotation with ordered list of CtRoles.
```java
@ScanningOrder({
  ANNOTATION,
  TYPE_MEMBER,
  COMMENT
})
interface CtAnnotationType {...}
```

Any other alternative idea?

**Comment by monperrus** [comment]
> How to define that order? 
We can take the order of methods in the interface itself.

**Comment by pvojtechovsky** [comment]
The leaf

**Comment by surli** [comment]
> The explicit well visible definition of order might be helpful.

I agree, it's easier to read it, and I think it's "dangerous" to relate on the order of the methods in the interfaces: on the long term, it seems particulary tedious to check for each contribution that the order of introduced methods are ok.

**Comment by monperrus** [comment]
should we close this issue?

**Comment by pvojtechovsky** [comment]
The topic is still relevant from my point of view, but I have no time to do anything in this area now. So if nobody else is interested too, then close it.

**Comment by monperrus** [comment]
we can reopen it becomes active again
