### ISSUE TITLE
question: Access to original low-level AST?

### ISSUE THREAD

**Issue by Egor18** [INRIA/spoon#1635]
Hello. I was playing around with spoon to perform some simple analysis.
And my question is: Is it possible to get the original low-level AST, which exists before AST simplification?

Let me explain it with a simple example. Here is the original code:
```
if (cond)
  return ((((10))));
else return 20;
```

And here is the same code after AST simplification:
```
if (cond)
{
  return 10;
}
else
{ 
  return 20;
}
```

So in spoon we are working only with the simplified code. But can I somehow lookup for the original AST?
Can I find these unnecessary parentheses in the AST?

[rest of the issue in #1636]

**Comment by monperrus** [comment]
In Spoon, what you call the low-level AST is the JDT AST.

It's not possible to get the JDT AST from a Spoon AST node.

(and I'm not sure that even the JDT AST would give you information about the additional parentheses)

**Comment by Egor18** [comment]
Ok. Thank you.
