### ISSUE TITLE
bug in setPosition

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#1636]
from @Egor18

Also I probably have found some issue with `getPosition()` method.
Consider the following code:
```
if (cond) return 10;
else return 20;
```

When I'm trying to get positions this way:
```
@Override
public void visitCtIf(CtIf ifElement)
{
  super.visitCtIf(ifElement);
  
  CtStatement thenStatement = ifElement.getThenStatement();
  CtStatement elseStatement = ifElement.getElseStatement();
 
  System.out.println(thenStatement.getPosition());
  System.out.println(elseStatement.getPosition());

  ...
}
```

It outputs:
```
(unknown file)
(unknown file)
```

But if I change source code to this:
```
if (cond)
{
  return 10;
}
else
{
  return 20;
}
```

It works fine:
```
(/Users/Egor/eclipse-workspace/Test/src/Test.java:10)
(/Users/Egor/eclipse-workspace/Test/src/Test.java:14)
```

To bypass this issue I have to use this trick:
```
SourcePosition thenPos = thenBody.getStatement(0).getPosition();
SourcePosition elsePos = elseBody.getStatement(0).getPosition();
```

It would be great to have it fixed :)
Thank you.

**Comment by tdurieux** [comment]
it is normal because ` CtStatement thenStatement = ifElement.getThenStatement();` and  `CtStatement elseStatement = ifElement.getElseStatement();` return implicit block, implicit element does not have position

**Comment by Egor18** [comment]
So, Is it possible to get first non-implicit element, to get it's position?

**Comment by monperrus** [comment]
> implicit element does not have position

This may be the bug. The implicit blocks should have the position of their contained statement.

**Comment by monperrus** [comment]
> So, Is it possible to get first non-implicit element, to get it's position?

Here is a workaround:
```
CtElement parentWithPosition = element.getParent(new Filter<CtElement>() {
	@Override
	public boolean matches(CtElement element) {
		return element.getPosition().getFile()!=null
}
})
```

**Comment by pvojtechovsky** [comment]
I would say that the implicit element does not have position of parent, but position of all children?

**Comment by monperrus** [comment]
> I would say that the implicit element does not have position of parent, but position of all children?
>
I agree, this should be  the contract.

**Comment by monperrus** [comment]
good questions!

I'd say we don't have to support the position of all implicit elements but at least those for which
we have a good answer, such as implicit blocks.
