### ISSUE TITLE
About imports in Spoon

### ISSUE THREAD

**Issue by surli** [INRIA/spoon#1650]
We currently use two different mechanisms in Spoon to manage imports: 
   - We try to get back original imports (in JDTImportBuilder), except for `*` imports, which are exploded
   - We compute from the model the imports needed and solve conflicts (in ImportScanner)

Then there is at least 3 remaining problems with our approach:
   1. We do not manage properly `*` imports (i.e. we never write a `*` import, even if it was in the original code)
   2. We try to solve conflict only after all transformation, which can be error prone IMHO
   3. We cannot get easily the list of imports from the model (see #1629)

I suggest to push back imports in the Spoon model (according to @monperrus it was previously in it). Then we should be able to have the concepts of package import and static type import (respectively `import foo.*` and `import static foo.Type.*`). Then I propose in a long term view to compute import using the sniper observer model, at each operation in the model: it would allow to know if an operation introduce a conflict in import and to solve it directly or to throw an exception if we cannot solve it. 

WDYT?

**Comment by monperrus** [comment]
> according to @monperrus <https://github.com/monperrus> it was previously in it
Not really. We only add a way to add manual imports.

> I suggest to push back imports in the Spoon model 
That's possible. One question is whether we attach imports to types or whether we add CtCompilationUnit.

**Comment by surli** [comment]
> One question is whether we attach imports to types or whether we add CtCompilationUnit.

IMHO they should be attached to types: then we can pretty print using the original compilationunit by taking the union of imports of all types.

**Comment by monperrus** [comment]
I agree.

I thing the notion of compilation unit is too low level for being part of the Spoon model, which is
meant to be a nice abstraction.

**Comment by pvojtechovsky** [comment]
I agree, but we should design it by way it is friendly to refactorings. Something like "suggested imports". The DJPP would then use data in suggested import in case when there are more ways how to print import ... 
But how it should look like?

**Comment by surli** [comment]
> The DJPP would then use data in suggested import in case when there are more ways how to print import ...

You mean, for example, importing a type instead of statically importing its methods/fields? 
Or importing a package instead of importing a lot of classes? 

For me, the answer is to always stick to the old behaviour, and when there's a decision to take, stick to the current rule: always do a type import in favor of any other import.

**Comment by pvojtechovsky** [comment]
> You mean, for example, importing a type instead of statically importing its methods/fields?
> Or importing a package instead of importing a lot of classes?

yes

> For me, the answer is to always stick to the old behaviour

I do not understand context of this sentence or this PR...
I guess we want 
* to keep imports same like they were in original file
* to let client influence imports used during printing
* ...

**Comment by surli** [comment]
Yes, sorry the meaning of my sentence was: to keep imports same like they were in original file

**Comment by monperrus** [comment]
@surli close this one?

**Comment by surli** [comment]
Closed by #1707
