### ISSUE TITLE
chore: improve Travis building time

### ISSUE THREAD

**Issue by surli** [INRIA/spoon#1653]
We currently run  3 different jobs on Travis, always replicating some step like checkstyle: I propose to only do checkstyle, verify, etc once, and to only call mvn test on the 3 different configurations, to speed-up the CI.

WDYT?

**Comment by tdurieux** [comment]
Good idea,

What I would like to have is: 
* one travis build for checkstyle, and license
* other travis builds for the tests

That way even if the checkstyle fails we can have a feedback for the tests.

**Comment by surli** [comment]
So for now, I propose the following solution:
  - first stage: 3 runs in parallel, with different configuration of JDK and java compliance, which only run mvn test
  - second stage: 2 runs in parallel: 1 for checkstyle, site etc; the other one for coverage (never fails)

If the first stage fails, the second is never executed. WDYT?

**Comment by tdurieux** [comment]
It is a good idea to do the second stage in parallel of the first stage.
There is no point to wait to run it.

**Comment by surli** [comment]
> It is a good idea to do the second stage in parallel of the first stage.

Done.

**Comment by pvojtechovsky** [comment]
Looking forward how fast it will be now ;-)

**Comment by surli** [comment]
> Looking forward how fast it will be now ;-)

In fact, we got almost the same build time than before (~ 9 minutes) in last try (see: https://travis-ci.org/INRIA/spoon/builds/293121327)

I think we can expect a minimum time of ~6 minutes (max time of each job) and a maximum time of ~20 minutes (if jobs are all launched sequentially). 
I don't think the way jobs are launched is predictable: they are more or less parallel, but it depends on Travis resources I think.

**Comment by pvojtechovsky** [comment]
Does it have to download all resources all the time? Would not a cache which is updated once a day would be enough?

**Comment by surli** [comment]
> Would not a cache which is updated once a day would be enough?

I tried to add .m2 in cache, with a mechanism to delete all from .m2/fr/inria to be sure we don't keep a version of Spoon in cache by mistake.
I also try to fork the execution of tests to improve performance, we'll see if it's better :)
