### ISSUE TITLE
chore: get coverage for PR

### ISSUE THREAD

**Issue by surli** [INRIA/spoon#1654]
Apparently we dont' get coveralls results anymore for one or 2 weeks.

**Comment by monperrus** [comment]
I've simply disabled the status update.

The results are still pushed to the coverall website, and the badge is updated.

**Comment by surli** [comment]
> I've simply disabled the status update.

There's a reason behind it? 
I found it usefull in PRs

**Comment by monperrus** [comment]
> There's a reason behind it?

Not waiting for coveralls, which is sometimes super slow for putting a green status.

**Comment by surli** [comment]
> Not waiting for coveralls, which is sometimes super slow for putting a green status.

Ok then. On the long term view, maybe we can do something like with revapi but for code coverage on PR. WDYT?

**Comment by monperrus** [comment]
In the long term, beyond a coverage number, I would love to have:

- coverage checking on diff (#1212)
- mutation testing on diff (https://github.com/STAMP-project/pitest-descartes/issues/24 @oscarlvp
@bbaudry)

--Martin

**Comment by monperrus** [comment]
re-enabled the coveralls commit status

closing
