### ISSUE TITLE
achievement: 400 stars!

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#1695]
We've just got our 400th star on Github!

Let's continue to work on the dissemination side (good documentation, links, blog posts, papers, talks) so that many more people get enlightened by the Spoon light!

And kudos to our awesome community!

**Comment by pvojtechovsky** [comment]
Here is history of Spoon project stars:
http://www.timqian.com/star-history/#inria/spoon

**Comment by monperrus** [comment]
super cool!

**Comment by monperrus** [comment]
admire the perfect "777" stars of today :electron:

**Comment by monperrus** [comment]
Hi all,

FYI, we've just passed the 1000th star milestone on Github!!!

**Comment by monperrus** [comment]
Today, we celebrate the 100th Github contributor!

![Screenshot from 2021-10-19 10-53-23](https://user-images.githubusercontent.com/803666/137877004-bae22df8-d38b-47aa-bccd-f70eaf9c7ab7.png)

Spoon is a great collective achievement!
