### ISSUE TITLE
Unwanted factorized annotation values

### ISSUE THREAD

**Issue by lodart** [INRIA/spoon#1722]
I am currently writing a program aiming at refactoring tests from junit 4 to 5.
To do so, I want to change Categories to Tags.

Here is the junit4 version:
`@Category({SlowTests.class, FastTests.class})`

Here is the expected result in junit 5 wanted to be produced (one tag per category):
```
@Tag("SlowTests")
@Tag("FastTests")
```

Here is my code, a for-loop on a list:
```
for (String tag : tagList) {
            method.getFactory().Annotation().annotate(method, Tag.class,"value",tag);
        }
```

Here is the result:
`@Tag({ "TestAnnotation.SlowTests" , "TestAnnotation.FastTests" })`

Any idea why the tags are "factorized"?
Thanks !

**Comment by pvojtechovsky** [comment]
There is bug in 
```
AnnotationFactory#annotate(CtElement element, CtTypeReference<A> annotationType, String annotationElementName, Object value)
```

**Comment by surli** [comment]
Hi @lodart thanks for reporting the issue!
I proposed a PR in #1724 to solve it which may change the behaviour of Spoon regarding annotate method: you're invited to give your opinion if you like.
