### ISSUE TITLE
How to replace an element with another?

### ISSUE THREAD

**Issue by justinwm** [INRIA/spoon#1729]
Referring to the CtElements Doc as follows:

`void replace(CtElement element)`

`Replaces this element by another one.`

Does this API means to replace the current element with the parameter `element`?

I have tried this but it fails to replace the current element with the target one :-(

Referring to the tutorials, I write my code as follows:

        @Override
	    public void process(CtElement candidate) {
		if (!(candidate instanceof CtExpressionImpl)) {
			return;
		}
		
		CtExpressionImpl<?> expr = (CtExpressionImpl<?>) candidate;
		CtExpressionImpl<?> texpr = getCandidateRandomly();
		expr.replace(texpr);
       }

The `expr` hasn't been replaced with `texpr` after this.
Is there anything wrong with this? or how can I use `replace()` function properly?

**Comment by monperrus** [comment]
Hi Justin,

Your usage is correct.

Are you sure that texpr is indeed different from expr?

What's the AST type of expr and texpr?

Are you able to reproduce the bug in a failing test case?

**Comment by justinwm** [comment]
Hi

I have figured that out :-)  
This function works normally. Thanks very much for your reply :-)
I thought the content of `expr` and `texpr` will be replaced after calling this :-(

Thanks again! You can close this. @monperrus
