### ISSUE TITLE
bug: ElementPrinterHelper#createListPrinter "startPrefixSpace" is not supported

### ISSUE THREAD

**Issue by surli** [INRIA/spoon#1735]
When building a list printer with boolean startPrefixSpace to true, it does not print a space before the start token.

**Comment by pvojtechovsky** [comment]
You are right, there is a mistake. 

There is no `createListPrinter(true, ...)`, all the calls are `createListPrinter(false, ...)`, so the best solution is probably to remove that `startPrefixSpace` parameter from the method - because it is unused.

WDYT?

**Comment by surli** [comment]
> because it is unused.

I don't agree, unless it's too complicated to fix: I discover this bug because I wanted to use it for #1730

**Comment by pvojtechovsky** [comment]
OK. It is easy to fix it. I can do it tomorrow evening.
