### ISSUE TITLE
Bug in getReferencedTypes

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#174]
it seems that AudioFormat.Encoding dependency is not detected by getReferencedTypes

```
import javax.sound.sampled.AudioFormat;
import javax.sound.sampled.AudioFormat.Encoding;
import java.util.HashMap;

public class Bar {
    public AudioFormat doSomething() {
        return new AudioFormat(Encoding.ALAW, (float)1.0, 8, 2, 1, (float)1.0, true, new HashMap<String, Object>());
    }
}
```

**Comment by GerardPaligot** [comment]
I have looked into this and it seems that when we already import the declaring class of the reference (here `AudioFormat` for `Encoding` class), it isn't necessary to add the reference. I'm ok with this so, for me, there isn't really a bug.
