### ISSUE TITLE
chore: add Nopol in Jenkins CI

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#1743]

**Comment by tdurieux** [comment]
astor is also broken since 6.0.0.
Because 
DefaultJavaPrettyPrinter.reset() is now private
and
CtStatement.replace(...) does not exist anymore, astor has to be recompiled.

**Comment by surli** [comment]
Nopol added and working. 
Astor added but apparently I have some issues with it. I close this one, I'll open another one in Astor's project.
