### ISSUE TITLE
About memory performance in Spoon 6.0.0

### ISSUE THREAD

**Issue by surli** [INRIA/spoon#1744]
@tdurieux brings to my attention that apparently Spoon 6.0.0 is much more slower than previous releases, so I tried to analyze the memory usage between Spoon 5.9.0 and Spoon 6.0.0 when calling Launcher#run on a project (namely Google Guava). 

The result is shown here: 
![spoon-bench-result](https://user-images.githubusercontent.com/1478232/33169260-424e5fda-d044-11e7-9725-c72e1ec7b5ba.png)

Apparently Spoon 6.0.0 uses around 200 Mb supplementary on my machine. Does anyone know out to properly compute a bench and to find where we may have a performance issue?

**Comment by surli** [comment]
Some more insight: I compared the time to run MainTest between release 5.9.0 and 6.0.0 on some commits (to get an average).

In Spoon 5.9.0 the average is 43 seconds, and it goes to 62 seconds in Spoon 6.0.0.
I will try to see if the difference came when introducing the new JDT dependency.

**Comment by surli** [comment]
So indeed between 67269b1c9d5cf66f6e7edaba3c170f56d160b5bc and 75f18837a6314a76bbad23c4773dd6259268d3c8 (introducing of support of JDK9, including new JDT), we go from 40 seconds to 58 seconds. 

I don't know if it's only related to the usage of a new version of JDT.

**Comment by monperrus** [comment]
About memory issue:

* https://github.com/INRIA/spoon/pull/1592 may be an explanation
* check that cloning code use dedup

**Comment by tdurieux** [comment]
In java 8 there is a string dedup but it is not enabled by default:
-XX:+UseG1GC -XX:+UseStringDeduplication

**Comment by monperrus** [comment]
I meant Spoon's dedup.

**Comment by tdurieux** [comment]
it is used...

**Comment by surli** [comment]
I just had a look on the performance trendings from the CI on the last 40 builds for MainTest and GenerationTest and we can observe a slow but real rise of time spent for both tests classes.

MainTest:
![MainTest](https://ci.inria.fr/sos/job/Spoon%20Install%20Commit%20Hook/performance/respondingTimeGraphPerTestCaseMode?width=900&height=550&performanceReportPosition=TEST-spoon.test.main.MainTest.xml)

GenerationTest:
![GenerationTest](https://ci.inria.fr/sos/job/Spoon%20Install%20Commit%20Hook/performance/respondingTimeGraphPerTestCaseMode?width=900&height=550&performanceReportPosition=TEST-spoon.processing.CtGenerationTest.xml)

For information build 387 is from november and 425 was yesterday.

**Comment by monperrus** [comment]
closing this one since there is no concrete action to take. we can reopen when somebody starts working on it.
