### ISSUE TITLE
isSubtypeOf is not working with class hierarchies

### ISSUE THREAD

**Issue by mohammadnaseri** [INRIA/spoon#1757]
Hi, 
I am using spoon to analyze an Android project. I am creating the launcher like the following:
```
Launcher launcher = new Launcher();
launcher.addInputResource("path to my Android project");
launcher.getEnvironment().setSourceClasspath(new String[]{"path to Android jar file");
launcher.getEnvironment().setNoClasspath(true);
CtModel model = launcher.buildModel();
```
In my Android project, I have a class like following:
```
public class MyEditText extends AppCompatEditText {
}
```
```AppCompandEditText``` is an Android class which extends ```EditText```
Now, I want to check if ```MyEditText``` is a subType of ```EditText```. 
I am doing like following:
```
CtTypeReference androidEditRef = launcher.getFactory().Type().createReference("android.widget.EditText");

CtTypeReference nodeRef = App.launcher.getFactory().Type().createReference("MyEditTextPackagePath");

nodeRef.isSubtypeOf(androidEditRef)
```
Now this one returns false, I feel like ```isSubType``` is not checking the class hierarchy. 
Please let me know if I am doing something wrong here.

**Comment by pvojtechovsky** [comment]
Hi,

I guess that `android.widget.EditText` is not on spoon class path. 
Try `androidEditRef.getTypeDeclaration()`, what it returns? Null or an exception or instance of CtType?
Try `nodeRef.getTypeDeclaration()`, what it returns? Null or an exception or instance of CtType?
Try `nodeRef.getTypeDeclaration().getSuperclass()' and then `nodeRef.getTypeDeclaration().getSuperclass().getSuperclass()' ...

**Comment by mohammadnaseri** [comment]
```android.widget.EditText``` is in android class path. and I added the jar path of android to the launcher class path. 
```androidEditRef.getTypeDeclaration()``` returns instance of CtType.
```nodeRef.getTypeDeclaration()``` returns instance of CtType too.
```nodeRef.getTypeDeclaration().getSuperclass()``` returns ```AppCompatEditText```
But 
```nodeRef.getTypeDeclaration().getSuperclass().getSuperclass()``` returns null.

**Comment by surli** [comment]
Hi @mohammadnaseri 

please have a look on my first step in the proposed PR #1760 : I tried to reproduce your bug, however in my unit test it seems to pass without problem. Maybe I forget something compared to your own conditions ?
 Try maybe to use Spoon 6.1.0-SNAPSHOT to check if it fixes the bug or not.

**Comment by surli** [comment]
ping @mohammadnaseri : is this issue fixed?

**Comment by mohammadnaseri** [comment]
Yes. Sorry I forgot to close the issue.
