### ISSUE TITLE
MavenLauncher adding non existing imports in the spooned java class

### ISSUE THREAD

**Issue by orichalque** [INRIA/spoon#1758]
Hi,

I encountered an issue with Spoon, when I was adding some java statements in a test case of an old revision of the source code of Log4j.

This Log4j revision is under maven, with a dependency to the version 4.7 of JUnit. I am using Spoon in a project using the version 4.12 of JUnit.

I'm using the version 6.0.0 of Spoon, with the Maven Launcher and the following configuration:
```
launcher.getEnvironment().setShouldCompile(true);
launcher.getEnvironment().setAutoImports(true);
```

This test case I'm spooning has the following import:
`import static org.junit.Assert.*;`

And in the Spooned version, the imports become the followings:

```
import static org.junit.Assert.assertArrayEquals;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNotSame;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertSame;
import static org.junit.Assert.assertThat;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;
```

Which leads to my issue during the compilation:
`The import org.junit.Assert.assertNotEquals cannot be resolved`

So, I took a look at the 4.7 version of JUnit, and it seems that this specific method does not exist, but exists in the 4.12 version. 
 
I reproduced this issue in a small project that I'm joining here. The architecture is the following;
```
.
├── pom.xml
└── src
    └── main
        ├── java
        │   └── fr
        │       └── atlanmod
        │           └── App.java
        └── resources
            └── Myproject
                ├── pom.xml
                └── src
                    ├── main
                    │   └── java
                    │       └── fr
                    │           └── atlanmod
                    │               └── MyApp.java
                    └── test
                        └── java
                            └── fr
                                └── atlanmod
                                    └── TestApp.java
```
The project Myproject inside the src/main/resources directory has a dependency to JUnit 4.7, and the main project has a dependency to the 4.12 one.

To reproduce it, first run a `mvn package` in the internal mvn project to install the dependencies, then ` mvn package exec:java -Dexec.mainClass=fr.atlanmod.App` at the root to run the main App that will spoon this internal project, using a simple processor.

Setting auto-imports to false wont produce it.

[project.zip](https://github.com/INRIA/spoon/files/1514509/project.zip)

Best Regards,

Thibault

**Comment by surli** [comment]
Hi @orichalque, 

we merge few weeks ago a new implementation of imports in Spoon which should fix your problem.
Do you mind trying your code with Spoon 6.1.0-SNAPSHOT?

**Comment by orichalque** [comment]
Hi @surli,

I changed to Spoon 6.1.0-SNAPSHOT and it seems that it's working fluently with this version.
Thanks for your help !

**Comment by surli** [comment]
Great! I close the issue but don't hesitate to open another one if you have other problems with imports: there will be other changes related to import mechanism in Spoon 6.1.0.
