### ISSUE TITLE
April release with java 8!

### ISSUE THREAD

**Issue by GerardPaligot** [INRIA/spoon#176]
Hi all,

The next release of Spoon **4** with Java **8** is planned for **4**/**8**.

**Comment by monperrus** [comment]
Release done, see http://lists.gforge.inria.fr/pipermail/spoon-discuss/2015-April/001769.html

Will close the issue after the release beer :-)

**Comment by monperrus** [comment]
Release beer done with a home-brewed from @petitpre :-) 

The pure Spoon swag!
