### ISSUE TITLE
Rules about printing in fully qualified name mode

### ISSUE THREAD

**Issue by surli** [INRIA/spoon#1775]
I'm currently working on a big refactoring on imports mechanism in #1772 and here again I have questions about printing types in fully qualified name mode. 

Just as a reminder, the fully qualified name mode is the default mode in Spoon and consists in using Spoon without imports, and printing the package names when using types.

However I have currently two questions:
 - should we print `java.lang.` packages, e.g. `java.lang.String myString`
 - in the same package should we print the package of external classes: 

```
package my.package;

public class A {}

package my.package;

public class B extends my.package.A {}
```

Apparently for the second question, the actual behaviour of Spoon is to keep the package names (see: https://github.com/INRIA/spoon/blob/b26167e4ad2ece972523cdf832e3603b92a399a1/src/test/java/spoon/test/imports/ImportTest.java#L184) 

Personnaly I am in favor of removing as much as possible the package names: it seems really artificial to print the package names in those cases, and it's easier to maintain this way.

**Comment by pvojtechovsky** [comment]
If you speak about autoimport mode, then 
* I agree that package names shouldn't be used when it is possible. The package names are needed only in case of name conflicts.
* java.lang is by default imported by java, so such package shouldn't be printed in autoimport mode too.

**Comment by surli** [comment]
> If you speak about autoimport mode, then

No in fact here my question was about when autoimport is false. Should we fully qualified absolutely everything or not? Knowing that in case of name collision we can not fully qualified everything.

**Comment by monperrus** [comment]
> Should we fully qualified absolutely everything or not?
yes, this is the design principle so far.
> Knowing that in case of name collision we can not fully qualified everything.
I'm not sure of this, because a fully qualified name is meant to be unique.

**Comment by surli** [comment]
> I'm not sure of this, because a fully qualified name is meant to be unique.

Yeah but we already know a code like that:

```java
import java.io.File;

public class MyClass {
public String java = new File("/tmp").toString(); 
}
```

which compiles, is transformed in FQN to:

```java
public class MyClass {
  public java.lang.String java = new java.io.File("/tmp").toString();
}
```

which does not compile.

>  Should we fully qualified absolutely everything or not?

At least ok for `java.lang` but I really don't see the point in fully qualifiying the name of inner classes ?...
