### ISSUE TITLE
feature: Add Progress Listener for Model Building

### ISSUE THREAD

**Issue by msteinbeck** [INRIA/spoon#1778]
Using Spoon to create a model for large size projects takes quite some time. Thus, I would like to attach some sort of progress listener to the `Launcher` class allowing me to track the current progress while creating a model. The progress listener should be able to distinguish between source compilation (JDT) and model creation (Spoon). I did some research and found that the JDT compiler allows to attach a [CompilationProgress](https://help.eclipse.org/mars/index.jsp?topic=%2Forg.eclipse.jdt.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fjdt%2Fcore%2Fcompiler%2FCompilationProgress.html). For the model creation, I would suggest to fire a progress event for each compilation unit.

Wrapping JDT's `CompilationProgress` class with a custom progress listener should be straightforward.

What do you think?

**Comment by monperrus** [comment]
It makes sense.
