### ISSUE TITLE
About CompilationUnits in Spoon

### ISSUE THREAD

**Issue by surli** [INRIA/spoon#1785]
We started to discuss with @tdurieux about the concept of CompilationUnit and its usage in Spoon. 
We both agree on the fact that the compilation units are currently badly used in Spoon: currently, only the source compilation units are managed. So you can never query the output compilation units, and you might even get a wrong compilation unit, for example if you query the CU of a type generated by a template. 

In order to fix the issue @tdurieux proposes a radical solution which is to put the compilation units directly in the Spoon model: we should be able to do `CtType.getParent(CompilationUnit.class)` and get something. 

I'm personnally mixed in the sense that it would mean that for the same code, we could have two different models, depending if we use the outputType `CompilationUnit` or `classes`. But, on the other hand, it's already the case: we may have two different models depending if we use `autoimport` or not. 

So WDYT about that proposal?

**Comment by pvojtechovsky** [comment]
The idea of CtType.getParent(CompilationUnit.class) is in conflict with CtType.getParent() which actually returns CtPackager - which is expected and wanted behavior.

**Comment by surli** [comment]
> CtType.getParent(CompilationUnit.class) is in conflict with CtType.getParent() which actually returns CtPackager

As I imagine it, the `CompilationUnit.getParent()` would then return a CtPackage. But I agree it's a major breaking of existing behaviour.

**Comment by pvojtechovsky** [comment]
May be the `CompilationUnit` doesn't blongs into main model. The Main model represents "logical java model", The CompilationUnits and imports belongs to another model "representation of logical model in file system" -> "printing model". Note that CompilationUnits or imports has no influence to behavior of such java code. It has only influence to the way how this code is mapped to files.
We can think about other related models too:
* data flow diagram
* code flow diagram
* ...
All such models are somehow linked to "Main model", but they can be understood as another independent models.

So may be the CompilationUnits etc. should not be part of main spoon model AST - cannot be navigated by parent-child relationship. But client can navigate to this "side model" using appropriate method.

It might be something like:
A) CtType.getPrintableType(), which returns PType. PType would be an element of AST of PrintModel.
B) CtElement.adaptTo(Class), which returns the representation of this element in supported "side model" which is linked to current element.
C) or KISS like CtType.getCompilationUnit()
D) ...

**Comment by monperrus** [comment]
Thanks for bringing this question on the table.

> May be the |CompilationUnit| doesn't blongs into main model.
I'm quite along this line.

> So may be the CompilationUnits etc. cannot be navigated by parent-child relationship
I agree here.

**Comment by tdurieux** [comment]
I like the idea of the side model but it is a lot of work for few use cases. 
Not sure if it is realistic to do it.

**Comment by surli** [comment]
So let's keep it as it is for now. Don't hesitate to reopen the discussion for further comments.
