### ISSUE TITLE
chore: Revapi is triggered on comments and shouldn't be

### ISSUE THREAD

**Issue by tdurieux** [INRIA/spoon#1788]
Revapi comments my PR but there is no code change, it is a lot of noise for noting.

**Comment by surli** [comment]
We already have #1426 for this.

**Comment by tdurieux** [comment]
It is not the same, apparently, Revapi submits a report for each new comment on the PR

**Comment by surli** [comment]
Oh. My bad. The trigger is somehow broken then.

**Comment by tdurieux** [comment]
I'm not sure if it is on comment, but something strange is happening

**Comment by surli** [comment]
I have the feeling that we don't have this issue anymore, am I right?

**Comment by tdurieux** [comment]
yes
