### ISSUE TITLE
How to mark Template statements?

### ISSUE THREAD

**Issue by pvojtechovsky** [INRIA/spoon#1809]
There is already possible in Spoon templates to use **template statements**.

For example this template
```java
for(Object x : $iterable$) {
	System.out.println(x);
}
```
will be substituted depending on value of `$iterable$`
A) `$iterable$ = factory.createFieldReference("field1").getReference()`
```java
for(Object x : field1) {
	System.out.println(x);
}
```
B) `$iterable$ = new String[]{"A", "B", "C"}`
```java
System.out.println("A");
System.out.println("B");
System.out.println("C");
```

In case B), the `for` statement is a **template statement**. In #1686 I already implemented TemplateMatcher, which can use `for` **template statement** for matching too. It means code like
```java
System.out.println("X");
System.out.println("Y");
```
is matched using template
```java
for(Object x : $iterable$) {
	System.out.println(x);
}
```
and produces parameter-value:
`$iterable$ = new String[]{"X", "Y"}`

The conceptual problem I actually have is how to tell template engine that this `for` is a **template statement** and not a normal statement.
Note: In case of substitution there was possible to decide it by parameter value, but it is not possible during template matching process. Here I need somehow explicitly declare it.

Idea:
> I1) to mark it using a comment

```java
/*TMPL*/
for(Object x : $iterable$) {
	System.out.println(x);
}
```

WDYT? Would it be usable?

Note: I imagine we might have more template statements.
`if` **template statement**, which optionally generates content of `if` body.
```java
/*TMPL*/
if($useLoging$) {
LOG.debug("Command _X_ started")
}
_X_.S();
/*TMPL*/
if($useLoging$) {
LOG.debug("Command _X_ finished")
}
```

`switch` **template statement**, which chooses one or more possible template variants.
`invocation` **template statement**, which includes another template
...

**Comment by surli** [comment]
If I understand you well, a **template statement** is a snippet of code which would be executed and the output written in the destination instead of just replacing the templated variables in the destination, right?

It looks like scripting capabilities inside the template mechanism of Spoon. I find it's really interesting but indeed we must scope it to make it easily usable. 
I'm ok using comments to declare it, but I would be more verbose: 
1. We should identify the begin and end of the template statement,
2. We should identify immediately that it's something for Spoon template processor

So maybe something like that: 
```java
/*Begin:SpoonScriptTpl*/
for(Object x : $iterable$) {
	System.out.println(x);
}
/*End:SpoonScriptTpl*/
```

WDYT?

**Comment by monperrus** [comment]
> the for statement is a template statement. In #1686 I already implemented TemplateMatcher, which can use for template statement for matching too. It means code like

neat!

**Comment by monperrus** [comment]
> > I actually have is how to tell template engine that this for is a template statement and not a normal statement.

so far the design principle is that a template is the whole body of a special method -- eg `statement` (and the template parameters are usually fields). Can this principle be used for this case as well?

**Comment by pvojtechovsky** [comment]
> by comments

may be we can implement that later. Actually I decided to handle marking of template statements using expression variable reference. It looks like this on low level now:
```java
for(Object x : $iterable$) {
	System.out.println(x);
}
...
patternBuilder.configureLiveStatements(statementMarker -> {
  statementMarker.byVariableName("$iterable$");
})
```
So I can continue to finish template matching process. We will discuss the details of configuration API later.

Thanks for Your feadback!
