### ISSUE TITLE
Is it possible to parse a .jar using spoon? 

### ISSUE THREAD

**Issue by JackLehman** [INRIA/spoon#1823]
Is it possible to parse a .jar using spoon? or from a maven dependency?
For example, a luncher that takes as input the jar file or maven dependency to parse the code.

**Comment by surli** [comment]
Spoon is dedicated to parse source code, not binaries. If you have a jar file that contains source code - which seems unusual - you can always unzip it and launch Spoon over it.

**Comment by surli** [comment]
@JackLehman I'm closing the issue don't hesitate to comment it or to open a new one if you have further question.
