### ISSUE TITLE
Good first bug: Fix parsing of Javadoc comments

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#1825]
Good first bug to welcome new contributors

Javadoc tags (eg `@see`) are not well parsed, they are printed with the "* " before the content and the spaces before the "*" are not consistently handled.

An assertion is available in `JavaDocTest#testJavaDocReprint()`

**Comment by manic-coder** [comment]
Hey, I'm starting out on open source and I want to make this my first solved bug :) 

I've imported your project in IntelliJ Idea. I'm having some issues:
1. No maven project found
2. Encoding issues (Java illegal characters found)

Can you help me resolve them please?

**Comment by surli** [comment]
Hi @manic-coder 

The easiest way to import the project in IntelliJ is, after you git clone the project, to just open it in intellij "File -> Open" and then choose "reimport all maven project" see:
![image](https://i.stack.imgur.com/AYTOh.png)

**Comment by monperrus** [comment]
See
https://www.packtpub.com/mapt/book/application_development/9781785286124/2/ch02lvl1sec25/importing-an-existing-maven-project-in-intellij-idea

**Comment by manic-coder** [comment]
Hi @monperrus , thank you I have built the project.

In JavaDocTest file, assertion at line 48 reads
`assertEquals("Creates an annotation type." + System.lineSeparator()
				+ "* @param owner" + System.lineSeparator()
				+ " * \t\tthe package of the annotation type" + System.lineSeparator()
				+ "* @param simpleName" + System.lineSeparator()
				+ " * \t\tthe name of annotation" + System.lineSeparator()
				, aClass.getMethodsByName("create").get(0).getDocComment());`

However, the assertion that has to be corrected has the same actual value (second parameter) but a different expected value (first parameter)
`assertEquals("Creates an annotation type." + System.lineSeparator()
						+ "@param owner" + System.lineSeparator()
						+ " \t\tthe package of the annotation type" + System.lineSeparator()
						+ " @param simpleName" + System.lineSeparator()
						+ " \t\tthe name of annotation" + System.lineSeparator()
				, aClass.getMethodsByName("create").get(0).getDocComment());
	}`

How can both assertions be true?

**Comment by surli** [comment]
> How can both assertions be true?

They cannot. The first assertion should be replaced by the second one.

**Comment by manic-coder** [comment]
In the correct assertion,

does there have to a space before "\t\t" and before "@param simpleName"?
There is no space before the first tag (@param owner). A consistent implementation would perhaps be when there is no space at the beginning of any of these strings.

In any case, I have rectified the issue and when this is cleared up, I'm ready to submit a PR :)

**Comment by monperrus** [comment]
> A consistent implementation would perhaps be when there is no space at the beginning of any of
> these strings.
I agree. Consistency is important.

**Comment by manic-coder** [comment]
Hi, I have submitted a PR (#1841) :)

**Comment by monperrus** [comment]
Thanks a lot, the Travis continuous integration fails, can you have a look at the cause of the failure?

**Comment by monperrus** [comment]
Closed per #1841
