### ISSUE TITLE
Spoon-maven-plugin prevents from compiling projects

### ISSUE THREAD

**Issue by surli** [INRIA/spoon#1830]
Some projects got the error:

>[INFO] --- maven-compiler-plugin:3.7.0:compile (default-compile) @ xwiki-commons-blame-api ---
[INFO] Nothing to compile - all classes are up to date

See for example the discussion here: https://github.com/SpoonLabs/spoon-maven-plugin/pull/51#issuecomment-355977076

**Comment by surli** [comment]
@tmortagne now it should work with xwiki (on my machine it works at least). However be careful: you currently do not specify explicitely which goal to use with spoon-maven-plugin. So before 2.7.0 it was working with the goal  "generate", and now it works with the goal "check". On the future it might be another goal.

**Comment by tmortagne** [comment]
> However be careful: you currently do not specify explicitely which goal to use with spoon-maven-plugin

You are not looking at the right pom I think. See https://github.com/xwiki/xwiki-commons/blob/feature-updatespoon/xwiki-commons-pom/pom.xml#L162. The root pom only define the version to use.

**Comment by surli** [comment]
Oh ok, my bad :)

**Comment by surli** [comment]
@tmortagne for information I wait until you tell me it's ok for you with those last changes before releasing spoon-maven-plugin.

**Comment by tmortagne** [comment]
Right, sorry about that. Will test it today.

**Comment by tmortagne** [comment]
I confirm it works fine for me. Thanks !

**Comment by surli** [comment]
It's released: you can now use spoon-maven-plugin 2.8

**Comment by tmortagne** [comment]
Great news !

**Comment by tmortagne** [comment]
Hmm just a last details: I can't build with spoon 6.1.0 because of the Maven 3.5 dependency coming from it.

**Comment by surli** [comment]
Hmmm. Right I forgot this one. You might put a dependency to either Spoon 6.2.0-SNAPSHOT (I removed the breaking dependency from it few PRs ago)  or an older one then?

**Comment by tmortagne** [comment]
> You might put a dependency to either Spoon 6.2.0-SNAPSHOT

It's not critical enough to use a SNAPSHOT on master, I can wait :)

> or an older one then?

Older one won't contains the work on processor's parameters you did, right ? Won't the 2.8 version of the plugin have issue with older version also ?

**Comment by surli** [comment]
> Older one won't contains the work on processor's parameters you did, right ? 

Indeed. 

> Won't the 2.8 version of the plugin have issue with older version also ?

It should not: the API of Spoon remains stable.

**Comment by tmortagne** [comment]
> It should not: the API of Spoon remains stable.

OK I tough maybe processor's parameter stuff might have required some new API or something.
