### ISSUE TITLE
[Question] Force spoon to not change the source when parsing

### ISSUE THREAD

**Issue by Sigurthorb** [INRIA/spoon#1831]
Hello

I am currently using spoon to parse individual files in a project.
When spoon parses the code it automatically changes/adds/removes imports and code within the java file.

My current environment is

```
StandardEnvironment standardEnvironment = new StandardEnvironment();
standardEnvironment.setLevel(String.valueOf(Level.OFF));
standardEnvironment.setNoClasspath(true);
standardEnvironment.setAutoImports(true);
standardEnvironment.setCommentEnabled(true);
compiler = new SpoonModelCompiler(new FactoryImpl(new DefaultCoreFactory(), standardEnvironment));
```

Am I missing something from the documentation that I can use to force spoon not to change the source or is that not possible with spoon?

**Comment by monperrus** [comment]
Yes, when spoon **pretty-prints** the code, it automatically changes/adds/removes imports even in autoimport mode. But the code is strictly semantically equivalent.

Do you do analysis or transformation of Java source code?

**Comment by monperrus** [comment]
Closing this one, don't hesitate to reopen.
