### ISSUE TITLE
In noclasspath mode, all calls to `CtTypeReference#getActualClass` should catch SpoonClassNotFoundException

### ISSUE THREAD

**Issue by surli** [INRIA/spoon#1833]
The current behaviour in Spoon is that if `getActualClass` is called a `SpoonClassNotFoundException` is thrown if the class cannot be found. It is still true in noclasspath mode, and it makes sense when a client calls the method directly. 

However IMHO it does not make sense in the internal API of Spoon: in noclasspath mode, we should never propagate a SpoonClassNotFoundException in the internal API. I suggest that we change the API to manage those as standard exception and no more RuntimeException. The benefit will be that we know exactly where we need to catch those or to propagate them. WDYT?

**Comment by monperrus** [comment]
In general, client code should never call getActualClass() because it breaks Spoon's encapsulation
(source code model or shadow class).

This is even more true in noclasspath, in noclasspath there is absolutely no reason to call
getActualClass.

So I would say it's better to throw this exception, to violently warn clients that they are doing
something really dangerous.

**Comment by tdurieux** [comment]
The problem is that our API uses getActualClass in noclasspath

**Comment by msteinbeck** [comment]
> The problem is that our API uses getActualClass in noclasspath

I observed several errors resulting from this fact. noclasspath mode and getActualClass should be strictly isolated to make Spoon more fail-safe.

**Comment by surli** [comment]
> The problem is that our API uses getActualClass in noclasspath

I don't agree it's a problem: you can use the noclasspath mode with a classpath, so you can use getActualClass. The problem is that we do not throw the exception, so in other methods we cannot rely on different behaviour when we are in noclasspath.

**Comment by monperrus** [comment]
We can continue the discussion with a PR, and see the impact on tests.

**Comment by monperrus** [comment]
this is done at the client method level, in particular getTypeDeclaration, see #2028
