### ISSUE TITLE
License questions about CeCILL-C

### ISSUE THREAD

**Issue by leventov** [INRIA/spoon#1861]
- Under what license is Spoon released: CeCILL-C 1, 2, or 2.1?
 - With what licenses is it compatible?
   - Under what license some source code that is modification of or amendment to Spoon source code should be released?
   - Under what license some source code that uses Spoon as a Java library should be released?

**Comment by monperrus** [comment]
> Under what license is Spoon released: CeCILL-C 1, 2, or 2.1?

According to License.txt this is CeCILL-C 1, see https://github.com/INRIA/spoon/blob/master/LICENSE.txt#L516 

> With what licenses is it compatible?

Good question, let us ask to Inria law people.

**Comment by leventov** [comment]
This page: https://www.gnu.org/licenses/license-list.en.html says that CeCILL-C 1 is incompatible with GNU licenses.

Please consider relicensing under CeCILL-C 2.1 (at least; more commonly used and more permissive licenses are better) that should be compatible with LGPL.

**Comment by leventov** [comment]
It seems that currently, probably all software that depends on Spoon should be CeCILL-C 1-licensed, that's hard to believe in.

**Comment by monperrus** [comment]
CeCILL-C is similar to LGPL, it means that:

> Under what license some source code that is modification of or amendment to Spoon source code should be released?

The same license, CeCiLL-C

> Under what license some source code that uses Spoon as a Java library should be released?

Basically anything, incl. proprietary licenses.

**Comment by leventov** [comment]
It's not, however, how LGPL works, unless you provide the library only in runtime and don't bundle it into any kind of uberjar.

**Comment by surli** [comment]
> It's not, however, how LGPL works, unless you provide the library only in runtime and don't bundle it into any kind of uberjar.

That not what I understand when reading CeCILL-C FAQ: 

> If you distribute a program that is a modification of a program under one of the licenses in the CeCILL family, or that incorporates such a program,totally or partially, that is where the differences are. [...] If the program is under CeCILL-C, you can also distribute your program under any license but you have to distribute under CeCILL the possible modifications you did to the original source code (and mention the use you made of the initial program).

**Comment by monperrus** [comment]
> Please consider relicensing under CeCILL-C 2.1

Note that "CeCILL-C 2.1" does not exist. There is only "CeCILL 2.1" (no "C" version).

Relicensing under CeCILL 2.1 would be much less permissive for users.

**Comment by leventov** [comment]
Ok, to wrap up this question: do I understand it right that CeCILL-C 1 is more permissive than LGPL but less permissive than Apache, MIT, BSD licenses?

**Comment by surli** [comment]
> do I understand it right that CeCILL-C 1 is more permissive than LGPL but less permissive than Apache, MIT, BSD licenses?

It's surely less permissive than Apache, MIT and BSD licenses, as it should be released using the same license if changes has been done inside the library. Still I cannot say it's more permissive than LGPL as I always considered it as a "LGPL for french law", but I'm not a lawyer :)

**Comment by surli** [comment]
@leventov I close this one. Don't hesitate to comment back if you have further question.

**Comment by monperrus** [comment]
FYI Spoon is now dual-licensed MIT & Cecill-C, see #2950

**Comment by climbfuji** [comment]
Apologies for using this thread for a related question, does anyone know whether the Cecill-C licenses are compatible with Apache 2, which versions of Cecill-C (if applicable), and whether this is one-way or both-ways (e.g. Apache 2 can be embedded in GPL3, but not the other way round). Thanks!
