### ISSUE TITLE
Return public DefaultJavaPrettyPrinter.writeHeader() method

### ISSUE THREAD

**Issue by leventov** [INRIA/spoon#1865]
As a side effect of #784 (https://github.com/INRIA/spoon/pull/784/files#diff-5f33bf5d1f38230de815e4c60a67a215L2328), `DefaultJavaPrettyPrinter` doesn't have public `writeHeader()` method anymore. It makes public `computeImports()` and `scan()` much less useful, because you cannot print header (imports) anyway (`calculate()` does all those things together). However the ability to compute imports and write them (via `writeHeader()`) is useful for reorganizing or changing the imports list.

**Comment by monperrus** [comment]
closed per  #1866
