### ISSUE TITLE
Retrieve the children of a given class

### ISSUE THREAD

**Issue by TcQPAD** [INRIA/spoon#1879]
Hello, I have some code to mutate, and I'd like to realize OOP mutations.
For example, let's say I have 3 classes such as : 

`class A { ... }`

`class B extends A { ... }`
`class C extends A { ... }`

And in the code I want to mutate I have : 

`A a = new B();`

I'd like to mutate it by replacing the call to the constructor of `B` with a call to the constructor of `C`.

 I found out how to check if a given class is a subclass of another class, but I couldn't find if it's possible to retrieve all the classes extending a given class. Here is what I got so far : 

```
@Override
    public boolean isToBeProcessed(CtConstructorCall element) {
        return element.getType().getSuperclass() != null;
    }
```

Is it possible, after getting the super class using `getSuperClass()` to access all the children of the retrieved super class?

**Comment by pvojtechovsky** [comment]
Hello, have a look at `SubInheritanceHierarchyFunction`. 
Here are an examples how to use it
/spoon-core/src/test/java/spoon/test/refactoring/MethodsRefactoringTest.java

**Comment by TcQPAD** [comment]
Hello, thank you for your answer. 
If I get it, the principle is to explore the method hierarchy of a given class constructor?

**Comment by pvojtechovsky** [comment]
> to access all the children of the retrieved super class?

I understood you wrong. The `SubInheritanceHierarchyFunction` returns children sub classes. But you probably speak about type members. Try 
`type.getSuperclass().getTypeDeclaration().getTypeMembers()`
or 
getConstructors
`((CtClass)type.getSuperclass().getTypeDeclaration()).getConstructors()`

**Comment by TcQPAD** [comment]
No, actually you got me right (I think).
What I'd like to retrieve are all the classes that extend a given parent. I think your code, if I understood it, is what I need for my mutant.
