### ISSUE TITLE
Drop fragment fonctionality

### ISSUE THREAD

**Issue by GerardPaligot** [INRIA/spoon#188]
Fragment mode hasn't been maintained by spoon developers. So, we have decided that the fragment functionality will be dropped in a next release.

But a new feature will replace fragment, the snipper mode. This new feature will be in an another PR.

**Comment by styurin** [comment]
Fragments are still mentioned here: http://spoon.gforge.inria.fr/Doc/FAQ/ under section "How to preserve the transformed source code formatting and one-line comments?".
