### ISSUE TITLE
`spooned` directory should not be created using NO_OUTPUT with spoon 6.1.0

### ISSUE THREAD

**Issue by aveuiller** [INRIA/spoon#1896]
The launcher configuration is as follow:

        Launcher launcher = new Launcher();
        for (String stingClass : classesToAnalyze) {
            launcher.addInputResource(stingClass);
        }
        launcher.addProcessor(generateOutputProcessor());
        launcher.getEnvironment().setNoClasspath(true);
        launcher.getEnvironment().setCommentEnabled(true);
        launcher.getEnvironment().setOutputType(OutputType.NO_OUTPUT);
        return launcher;

**Comment by surli** [comment]
I just tried to reproduce your bug in https://github.com/surli/spoon/commit/4c6d3d9916b3d9a3f4ec76fcc6744d4b7b545e6f and using Spoon 6.1.0 but I don't get any failure. Maybe the problem comes from your processor?..

**Comment by monperrus** [comment]
closed per #1915
