### ISSUE TITLE
Support Java 10 in Spoon

### ISSUE THREAD

**Issue by surli** [INRIA/spoon#1897]
Java 10 brings new features like the support of type inference in local variable with the keyword `var`. This should be added in Spoon AST when the JDT will be ready for Java 10. 

More information: http://openjdk.java.net/projects/jdk/10/

**Comment by surli** [comment]
Am I missing something for this one, or is the only change to bring in Spoon here is really the support for local variable inference with `var` keyword?

**Comment by monperrus** [comment]
What the official URL to the Changelog of Java 10?

**Comment by surli** [comment]
The more complete page is: http://openjdk.java.net/projects/jdk/10/
You also have release notes from Oracle but with fewer information IMHO: http://www.oracle.com/technetwork/java/javase/10-relnote-issues-4108729.html

**Comment by surli** [comment]
It's now supported with #2054
