### ISSUE TITLE
community: Towards a calendar-based release process

### ISSUE THREAD

**Issue by surli** [INRIA/spoon#1898]
I propose to change the current process of releasing (which is now "release when you want") to a more systematical process, like releasing each 3 monthes. 

Why releasing on a predefined calendar?

1. It would help the community as the user will now exactly when a new release should be available
2. JDT and now Java are both using a release process of 6 monthes, we would be synchronized with them with a release each 3 monthes

WDYT?

**Comment by monperrus** [comment]
My two cents is that 1) too much rules and processes can be bad 2) no user has ever complained that
we release too slowly or too fast.

So the Goldilocks principle <https://en.wikipedia.org/wiki/Goldilocks_principle> would say: don't
release too often or too late, do it just when it's ready.

This is what we do, we follow the Goldilocks release process.

**Comment by monperrus** [comment]
[Issue Cleaning Marathon] No more activity here, closing the issue, don't hesitate to re-open.
