### ISSUE TITLE
Maven plugin have a hard time dealing with generated sources

### ISSUE THREAD

**Issue by tmortagne** [INRIA/spoon#1902]
I changed the phase from the default "validation" to "process-sources" so that the spoon is executed after "generate-sources". Might worth thinking about it as a default maybe but it's not really my main issue :)

It looks like the plugin does not "see" generated source folders and complain about unknown packages when checking a non generated source file importing a generated class.

To reproduce:

* clone https://github.com/xwiki/xwiki-rendering.git
* `cd xwiki-rendering-wikimodel`
* remove the `<xwiki.spoon.skip>true</xwiki.spoon.skip>`
* `mvn clean install -e`

**Comment by surli** [comment]
I just checked and this one is a bit tricky: apparently Maven API does not provide a generic way to get access to the generated sources directory. Or at least I did not find it yet.

I could add a check to "/target/generated-sources" but it's not generic at all and not always expected. 

However there is already some ways to do what you want:
  1. Add a specific configuration for this project in specifying the generated source folder: 

```xml
<build>
    <plugins>
      <plugin>
        <groupId>fr.inria.gforge.spoon</groupId>
        <artifactId>spoon-maven-plugin</artifactId>
        <configuration>
          <srcFolders>
            <srcFolder>src/main/java</srcFolder>
            <srcFolder>target/generated-sources/</srcFolder>
          </srcFolders>
        </configuration>
      </plugin>
    </plugins>
</build>
```

  2. Use the "noclasspath" parameter to not take into account the generated code: 

```xml
<configuration>
<noclasspath>true</noclasspath>
</configuration>
```

You can even add the specific configuration in `resources/spoon.xml` in your project.

**Comment by tmortagne** [comment]
> apparently Maven API does not provide a generic way to get access to the generated sources directory. 

Actually from what I understand all sources (generated or not) are listed in MavenProject#getCompileSourceRoots(). At least that's where you will find javacc plugin sources since that's what it's using to register them.
