### ISSUE TITLE
BuildModelException because of an "ambiguous method" with full classpath

### ISSUE THREAD

**Issue by surli** [INRIA/spoon#1911]
I got recently the following error:

> spoon.compiler.ModelBuildingException: The method info(String, Object) is ambiguous for the type Logger at /private/tmp/twill/twill-yarn/src/main/java/org/apache/twill/internal/appmaster/ApplicationMasterService.java:750

when calling Spoon on the project: https://github.com/apache/twill/tree/master/twill-yarn with a full classpath obtained with `mvn dependency:build-classpath`

Reproduction steps:
Fetch the following commit: https://github.com/apache/twill/commit/7f494d13da45e6f9a27dfe1b4bde9d521d306c20

```java
String path = "/tmp/twill/twill-yarn/src/main/java";
        String classPath = ""; // full classpath obtained with mvn dependency:build-classpath

        Launcher launcher = new Launcher();
        launcher.addInputResource(path);
        launcher.getEnvironment().setSourceClasspath(classPath.split(":"));
        //launcher.getEnvironment().setNoClasspath(true);

        CtModel model = launcher.buildModel();
```

**Comment by monperrus** [comment]
I've already seen that a long time ago.

Does JavaC give the same error?

**Comment by surli** [comment]
So, after investigation: I replicate the error when using last snapshot of Spoon.
However, I have no problem to compile the project, using javac or even ecj in IntelliJ.
On the other hand, the developers seemed aware about this kind of error because there is the following comment, just above the incriminated line:

> // Casting is needed in Java 8, otherwise it complains about ambiguous method over the info(String, Throwable)

I tried to replicate the bug in a unit test in Spoon but without success: it needs to use a specific classpath I think. 

My conclusion is that it's again a problem on JDT side, so we cannot fix it properly on our side. I propose that we mark it as a wontfix.

**Comment by monperrus** [comment]
Do we have an open JDT issue about this problem?

**Comment by surli** [comment]
No, it would need to replicate the bug in isolation from Spoon.
