### ISSUE TITLE
feature: collection-based property on steroids

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#1916]
In Spoon, collection-based properties (ie getters than return set or list of ctelements) are mutable.

This poses two problems:

* the parent is not set
* the change events are not sent

By using specific implementations of lists, we could get this fixed while remaining backward compatible.

@pvojtechovsky has already done in the heavy-lifting in the role-related classes.

**Comment by pvojtechovsky** [comment]
This is  somehow duplicate to #1633. Both issues has same solution - to use dynamic lists and sets

**Comment by monperrus** [comment]
duplicate of #1633
