### ISSUE TITLE
How can I get single line of the statement one by one?

### ISSUE THREAD

**Issue by jxzyz** [INRIA/spoon#1921]
Dear All, I'm a freshman dealing with Spoon. Now I need to parse the source to find the length of each line. However I can't find each single line of the code. For example
`int c = 0;
c = 1;
System.out.print(c);`
I want to find the statement one by one, and get it length. At first I tried to use CtStatement, but I failed. Because I found that it's said that CtStatement could also be a block! I'm confused. It means that if there is a block in my code, I will only get the block, and I can't see what was in the block. So if I want to get the statement One by one ,what should I do? 
Thank u all

**Comment by monperrus** [comment]
If you have a `CtBlock` object, you can iterate through the statements with `getStatements()`

    for(CtStatement s: method.getBody().getStatements()) {
       // do something
    }

**Comment by jxzyz** [comment]
@monperrus Thank u. But I still hava a question.
s's type is CtStatement, But it can still be a block. How can I avoid this situation. And, if where is a nested block, what should I do?

**Comment by pvojtechovsky** [comment]
Any statement can be a block. This idea comes from Java language specification. You cannot avoid it if you are using java. But you can easily iterate over all non block statements by a recursive function like
```java
void forEachNonBlockStatement(CtStatement stmt, Consumer<CtStatement> consumer) {
  if (stmt instanceof CtBlock) {
    ((CtBlock) stmt).getStatements().forEach(s->forEachStatement(s, consumer));
  } else {
    consumer.accept(stmt);
  }
}
```
