### ISSUE TITLE
Use noClasspath by default in Spoon

### ISSUE THREAD

**Issue by surli** [INRIA/spoon#1934]
Most bugs we are getting there can be simply resolved by using a `setNoClasspath(true)` in the environment: why not setting this by default? 

1. It would ease the adoption of Spoon
2. For old clients we can trigger a warning to set the default value has changed
3. For old clients, as they should normally already set the classpath it should not be a problem: the classpath is still used 
4. We can always change that and release it as a major release

WDYT?

**Comment by pvojtechovsky** [comment]
I am OK with that idea.

Optionally we might force clients to set the noClassPath mode to true/false. By default it might be `null` and Spoon Launcher would fail when it would be `null` with a nice exception ... something like: "Please decide the Spoon compilation mode ... with a link to Spoon documentation..." ... that would guide clients and would force them to understand that concept...

Or more user friendly we can write a warning into log when noClassPath is null and to use by default true (as you suggest).

**Comment by monperrus** [comment]
I find this a very good idea! esp wrt to ease of adoption.

(This would not break any existing code, so I wouldn't go for a major release for this.)
