### ISSUE TITLE
Question about how to create a field access

### ISSUE THREAD

**Issue by Eric-W0** [INRIA/spoon#1965]
Hi,

Having a hold on an instance of `CtField`, I would like to create the Ct equivalent of this statement:

`return this.x;`

I started using `CtFieldRead`, but then I'm not sure how I get a `CtVariableReference` from my `CtField` instance when I call `CtFieldRead#setVariable`.

Any advice?

Thank you.

**Comment by pvojtechovsky** [comment]
Hi,

Use CtField#getReference() to get `CtFieldReference`, which can be used as `CtVariableReference`, because of `CtFieldReference extends CtVariableReference`

**Comment by monperrus** [comment]
would be addressed by #1967
