### ISSUE TITLE
CtCatchVariable does not include source position of modifiers

### ISSUE THREAD

**Issue by W3D3** [INRIA/spoon#1968]
`CtCatchVariable` implements the `CtModifiable` interface and therefore can include modifiers.
For all other classes that implement `CtModifiable` I found that their SourcePosition is of type `DeclarationSourcePosition` containing the getters `getModifierSourceStart()` and `getModifierSourceEnd()`.
This is not the case for the CtCatchVariable.

**Comment by monperrus** [comment]
Thanks for the bug report. What would be the fix to your opinion?

**Comment by W3D3** [comment]
I would like the CtCatchVariable to also have a `DeclarationSourcePosition` that can give me the position of its modifiers.
