### ISSUE TITLE
regression: Spoon-based projects broken because of positions

### ISSUE THREAD

**Issue by surli** [INRIA/spoon#1970]
I just put a label "breaking_pr" on #1964 because it seems some projects based on Spoon has been broken due to this PR. I'm not sure that this PR intended to have a breaking behaviour for clients, but it's obviously the case. I open the issue here because the 4 concerned projects are tested in the Spoon CI to ensure that the snapshots are not breaking things. 

The concerned projects are the following:

* [x] https://github.com/SpoonLabs/gumtree-spoon-ast-diff FIXED
* [x] https://github.com/SpoonLabs/nopol FIXED
* [x] <s>https://github.com/SpoonLabs/spooet</s> UNRELATED
* [x] https://github.com/Spirals-Team/npefix FIXED

Nopol and gumtree are both broken using last snapshot of Spoon returning `java.lang.UnsupportedOperationException: PartialSourcePosition only contains a CompilationUnit`.
Complete Jenkins logs for Nopol: https://ci.inria.fr/sos/job/nopol/88/console
For gumtree: https://ci.inria.fr/sos/job/gumtree-spoon-ast-diff/506/console

Then we have Spooet which seems broken because of changes on the visibility of `reset` method on `DefaultJavaPrettyPrinter`: I'm not quite sure if it's coming from #1964 or not. Complete Jenkins log: https://ci.inria.fr/sos/job/spooet/494/console

Finally NPEFix seems to compute diff differently since last commits. Here again the log: https://ci.inria.fr/sos/job/npefix/460/console

WDYT @monperrus @tdurieux @pvojtechovsky are those bugs or is it a normal regression due to a major change?

**Comment by monperrus** [comment]
To me, this is a regression. We aim at maximum backward compatibility in Spoon.

PS: the regression on Spooet is much older. We detect it now because the CI setup was spooet was not
correct ((we never teste against the latest Spoon).

**Comment by monperrus** [comment]
gumtree-spoon fixed

The reason was that Jenkins did not take the latest snaptshot. Add `mvn -U dependency:resolve` in the job.

**Comment by monperrus** [comment]
npefix also fixed, see https://ci.inria.fr/sos/job/npefix/

Thanks @tdurieux

**Comment by monperrus** [comment]
nopol fixed, see https://ci.inria.fr/sos/job/nopol/

thanks @tdurieux

**Comment by zqudm** [comment]
When i use spoon-core-6.0.0-jar-with-dependencies.jar,  my program works well. However, when i use spoon-core-9.2.0-beta-8-jar-with-dependencies.jar,  a failure occurred,  that is, 

 _Exception in thread "main" java.lang.UnsupportedOperationException: PartialSourcePosition only contains a CompilationUnit_

How to fix this error?  Thanks !

**Comment by zqudm** [comment]
@tdurieux  Ok.
