### ISSUE TITLE
feature: CtScanner-based DFS Iterator for a CtElement

### ISSUE THREAD

**Issue by msramalho** [INRIA/spoon#1979]
I am working with Spoon for a project and needed an iterator that would go over a **CtElement's** descendants in a depth-first search manner, since **CtScanner** does not do this one element at a time, but rather at once (using `enter()` and `exit()`) it was not fitted for my designs. So I created a **CtIterator**.

If you can't see why this would be needed instead of an extended CtScanner consider you have two elements and need to go through both their trees but only advance on one, when a condition is met on the other and vice-versa. 

### Example behaviour

```java
CtIterator iterator = new CtIterator(/** some CtElement*/); 
while (iterator.hasNext()) { 
    CtElement next = (CtElement) iterator.next(); 
    System.out.println(next.toString()); 
}
```

If you would like me to create a PR to spoon with my implementation of CtIterator, please say so. Otherwise just close this issue.

😃

**Comment by monperrus** [comment]
Welcome to Spoon Miguel! This sounds really interesting. We'd be happy to review and merge your PR :-)
