### ISSUE TITLE
question: how to set up Intellij so that it reformats the code according to the checkstyle rules? 

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#1981]
follow-up on #1980 

How to set up Intellij so that it reformats the code according to the checkstyle rules?
AFAIK, we don't have a documented procedure for this.

**Comment by msramalho** [comment]
A detailed description of how to do this can be found [here](https://stackoverflow.com/questions/26955766/intellij-idea-checkstyle)(StackOverflow) and is continued [here](https://youtrack.jetbrains.com/issue/IDEA-61520#comment=27-1292600)(jetbrains).

**Comment by monperrus** [comment]
Thanks a lot Miguel!
