### ISSUE TITLE
How to find a method's parent(its package and all classes it belongs to)which is used by another method

### ISSUE THREAD

**Issue by jxzyz** [INRIA/spoon#1985]
Excuse me sir, nowadays there are another problems troubling me a lot.
It's obvious that we can calling other method in one method. How can I find the called method's parents?
For example, if there is a class is defined as "com.sun.javadoc.Doclet",and it has a mehthod called "start()" and "go_on()". "start()" calls "go_on()". We can use CtInvocation to find "go_on()". However I don't know how to find "com.sun.javadoc.Doclet" through "go_on()" which is produced by CtInvocation.
The code I write is as follows:

> 
> 		List<CtInvocation> methodnum = method.getElements(new TypeFilter(CtInvocation.class));
> 		List<String> umethod = new ArrayList();
> 		for(int i=0;i<methodnum.size();i++)
> 		{
> 			if(umethod.size()==0)
> 				umethod.add(methodnum.get(i).getExecutable().getParent().toString());
> 			
> 			else{
> 				int j=0;
> 				for(;j<umethod.size();j++)
> 				{
> 					if(umethod.get(j).equals(methodnum.get(i).getExecutable().getSignature()))
> 						break;
> 				}
> 				if(j==umethod.size()&&!umethod.get(j-1).equals(methodnum.get(i).getExecutable().getParent()))
> 					umethod.add(methodnum.get(i).getExecutable().getParent().getShortRepresentation());
> 			}
> 		}
> 

here I tried many different ways but I failed.
Hope sirs can help me out!

**Comment by monperrus** [comment]
The solution might be 

    anInvocation.getExecutable().getDeclaringType().getTypeDeclaration()
    // or
    anInvocation.getExecutable().getExecutableDeclaration().getParent()

**Comment by jxzyz** [comment]
Thank u sir, but I'm sorry to tell that it doesn't work.
In the first situation

> anInvocation.getExecutable().getDeclaringType().getTypeDeclaration().getPackage().getSimpleName()
I can find some packages, however it will show a SpoonClassNotFoundException sometimes.
In the second situation

>anInvocation.getExecutable().getExecutableDeclaration().getParent().toString()
I can only get the  the declaration of a class. The type of getParent() is CtElement. I can't get its name or its package.
So, is there any other solutions can help me?

**Comment by jxzyz** [comment]
Thank u sir, but I'm sorry to tell that it doesn't work.
In the first situation

> anInvocation.getExecutable().getDeclaringType().getTypeDeclaration().getPackage().getSimpleName()


I can find some packages, however it will show a SpoonClassNotFoundException sometimes.
In the second situation

> anInvocation.getExecutable().getExecutableDeclaration().getParent().toString()


I can only get the the declaration of a class. The type of getParent() is CtElement. I can't get its name or its package.
So, is there any other solutions can help me?

**Comment by monperrus** [comment]
> I can find some packages, however it will show a SpoonClassNotFoundException sometimes.

Are you in noclasspath mode?

> I can only get the the declaration of a class. The type of getParent() is CtElement. I can't get its name or its package.

You have to cast it as `CtType` or `CtClass`

**Comment by monperrus** [comment]
Closing, don't hesitate to reopen if necessary.
