### ISSUE TITLE
How to accelerate the speed of analysis?

### ISSUE THREAD

**Issue by jxzyz** [INRIA/spoon#1990]
Dear Sirs,
I have some problem again.
In my program, I want to analysis some code, and I have millions of files to be analyzed.
Now I can only analyze a thousand files per minute.
So is there any API in spoon that can help me accelerate the speed of analysis?
Thank u all!

**Comment by msteinbeck** [comment]
What exactly is the time consuming part? The generation of the model, or the analysis itself?

**Comment by jxzyz** [comment]
I guess it may be the analysis. Because sometimes I'm making a project model and finding its classes' feature it will take a few seconds to show the result for each class.

**Comment by monperrus** [comment]
There is no secret option to speedup building the model.

If you're doing some analysis, some methods are known to be slow because they use reflection (getAllMethods, getTypeDeclaration, etc)

**Comment by msteinbeck** [comment]
I strongly suggest to cache resolved references. You may also speedup your analysis by comparing qualified names instead of resolving references and comparing AST nodes.

**Comment by tdurieux** [comment]
Avoid to traverse multiple times the ast.

Use EarlyTerminatingScanner when you want to find only one element.
Don't use too much the toString()

**Comment by monperrus** [comment]
See also #1111

**Comment by jxzyz** [comment]
I got it! Thank u all!
