### ISSUE TITLE
Behavior of CtPackage#addType

### ISSUE THREAD

**Issue by pvojtechovsky** [INRIA/spoon#2000]
It is continuation of discussion in #1917. 

In short:
There is question what is the intended behavior of CtPackage#addType
A) it should move type from it's current package to new package (to change qualified name)
B) it should add the type into package where it actually is

Current behavior is (B) ... and is checked by test CtPackageAssertTest#testEqualityBetweenTwoCtPackage`. It means when type belongs to no package (has no parent), then it is added into package. When type belongs to any package, then it is kept there, but the type is assigned to new package too - the spoon model is no more tree ... it is broken.

> Martin wrote:
> I would go for A) it should move type from it's current package to new package (to change qualified name)

But 
* that is not backward compatible 
* such move sounds more like refactoring and if we want to do it correctly, then we should move also all the references to moved type, etc. 
* one of the nice features of PR  #1917 is the optional sanity check, which avoids adding of one CtElement to two places. It assures that spoon model is the tree. So calling of `CtPackage#addType` with type which already belongs to some other package is unsafe/wrong from that point of view.

I suggest this implementation:
* When type belongs to no package (has no parent), then it is added into package. (same like current implementation)
* When the type already belongs to this package, then this call does nothing.
* When type belongs to another package, then this call throws exception

WDYT?

**Comment by monperrus** [comment]
OK for me. I don't expect many tests to fail with that change, but we'll see.
