### ISSUE TITLE
add method `CtStatement#comment()`

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#2013]
to comment code in the pretty-printed code, this is a traceable version of (`#delete`)

**Comment by tdurieux** [comment]
Honestly, I'm against this. it had API footprint to spoon (that is already huge) and it can be done by the client side in one or two lines.
I think we should really pay attention the API footprint.

We can maybe create an utility class that contains "useful" method like this.

**Comment by LakshyAAAgrawal** [comment]
Hey, Will this feature be added? If yes, can I work on this?

**Comment by monperrus** [comment]
Welcome to Spoon. Yes, feel free to make a pull-request, that's a good exercise :-)

**Comment by LakshyAAAgrawal** [comment]
Sir, I tried reading about the problem and also looked into the similar thread about adding [blank lines](https://github.com/INRIA/spoon/issues/1268) and about [delete](https://github.com/INRIA/spoon/issues/403). I see that CtStatement extends CtElement interface, which already has the addComment method along with others related to comments.

Could you please clarify if what we want from CtStatement#comment() is 
1. to comment the current statement in the actual model of the code - like:
```
int i = 10;
```
becomes
```
// int i = 10;
```
 2. Or is it to add a comment for the statement.
```
int i = 10;
```
becomes
```
int i = 10; // Hi, I am a comment
```

I understand that 2 is already implemented. Is it something else we are trying to add?

**Comment by monperrus** [comment]
yes, the intention is the first semantics you describe.

**Comment by LakshyAAAgrawal** [comment]
Idea: Should there be a way to and is there a usecase for "uncomment" of a legal/valid statement which has been commented by using CtStatement#comment?

**Comment by monperrus** [comment]
> is there a usecase for "uncomment"

thanks for the proposal, that's not required for now IMHO.
