### ISSUE TITLE
Using visitor to visit only certain types of elements

### ISSUE THREAD

**Issue by peey** [INRIA/spoon#2018]
I'm using spoon from Java. Let's say I have 

    CtClass l = Launcher.parseClass("class A { void m() { /*some code here*/} }");

Now I'd like to visit all switch elements in the AST.

I was expecting to do this by using

```
class MyVisitor implements CtVisitor {
  @Override
  public <S> void visitCtSwitch(CtSwitch<S> ctSwitch) {
  // my code here
  }
}

l.accept(new MyVisitor());
```

But the problem here is that MyVisitor must implement all methods in `CtVisitor`. So I'll need to add empty method definitions for _every other method in CtVisitor_ in order to acomplish this.

Is there a better way to do this?

**Comment by pvojtechovsky** [comment]
try something like
```java
CtClass clazz = ...
clazz.filterChildren(new TypeFilter(CtSwitch.class))
```
