### ISSUE TITLE
Add CtAssignment as resource in Try-with-resource 

### ISSUE THREAD

**Issue by ashutosh1598** [INRIA/spoon#2019]
I want to create a try-with-resource like `try( input = new FileInputStream("file.txt"))`, but the addResource function only accepts CtLocalVariable as argument, which means I am forced to create it like `try( FileInputStream input = new FileInputStream("file.txt"))` . But I want `input` to be declared previously. How can I do this?

**Comment by pvojtechovsky** [comment]
I do not know, but I would try 
1) to write a source code you want to generate in some testing class and method
2) analyze that source code by Spoon and have a look how spoon AST looks for that.

Then 
A) create same AST using Factory methods
B) generate the same AST using [Template](http://spoon.gforge.inria.fr/template_definition.html) or Pattern (#1686)

**Comment by ashutosh1598** [comment]
Oh good idea. Thanks

**Comment by ashutosh1598** [comment]
It's not valid java syntax to declare variable beforehand in try-with-resource.
