### ISSUE TITLE
getTypeDeclaration should not crash in noclasspath due to SpoonClassNotFoundException

### ISSUE THREAD

**Issue by tdurieux** [INRIA/spoon#2022]
Hi all,

What is the best practice to handle getActualClass when the class is not in the classpath?

For example, 

https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/support/reflect/reference/CtTypeReferenceImpl.java#L188

would we add a try catch and return null or the exception is the best way to go?

**Comment by pvojtechovsky** [comment]
I never needed noclasspath mode till now. So it is hard for me to imagine real use cases... What would client's expect in this case? 
In which use case the null is good ?
In which use case exception is good ? Checked or Unchecked ;-) ?

**Comment by tdurieux** [comment]
It is to handle this type of error: https://github.com/INRIA/spoon/issues/2014#issuecomment-393950423
basically we do not handle the error in spoon :/

**Comment by pvojtechovsky** [comment]
What is concept/definition of "no classpath mode"?: "If class is missing then silently ignore that and continue with next analyze step". If that is the definition then 

> would we add a try catch and return null or the exception is the best way to go?

to return null

I checked ~50% of callers of getActualClass in spoon code and most of them doesn't handle exception and will probably fail in noclasspath mode. It seems to me like it is wrong.

May be we should extend contract of getActualClass  method. Actually the description is this:
```java
	/**
	 * Gets the Java runtime class of the referenced type.
	 *
	 * This is a low-level feature, it should never been used.
	 * Use {@link #getTypeDeclaration()} instead,
	 * in order to only stay in the Spoon world and manipulate CtType instead of java.lang.Class
	 *
	 * @return the Java class or throws a {@link SpoonClassNotFoundException} if the class is not found.
	 *  In case of a {@link CtTypeParameterReference} or a {@link CtArrayTypeReference} this method can return null value.
	 * @throws SpoonClassNotFoundException
	 * 		if the class is not in the classpath
	 */
	Class<T> getActualClass();
```
there should be: 
>  @return the Java class or 
A) in normal mode throws a {@link SpoonClassNotFoundException} if the class is not found. 
B) in noclasspath mode returns null

and all the callers of this method should check null and somehow continue ...

WDYT?

**Comment by tdurieux** [comment]
I think we already discussed this. 
And Martin was against it but I don't remember why

**Comment by monperrus** [comment]
AFAIU, the only case where getActualClass can return null is in  CtTypeParameterReferenceImpl and
CtArrayTypeReferenceImpl.

Let's see what happens if they never return null: https://github.com/INRIA/spoon/pull/2027

**Comment by monperrus** [comment]
We have two issues:

* a consistent contract for getActualClass, this is #2027
* removing calls to getActualClass in Spoon code

It seems we have to rename the issue to avoid confusion.
