### ISSUE TITLE
discussion(software engineering): test-driven code-review

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#2026]
Hi all,

In our Spoon community, all pull-requests are code-reviewed. Over time, some of us have started to always review the tests first.

I discover that we're not the only one:

* [Test Driven Code Review  (Google)](https://testing.googleblog.com/2010/08/test-driven-code-review.html)
* [Test-Driven Code Review (The code gang)](https://hackernoon.com/test-driven-code-review-3f05f6cee400)

**Comment by surli** [comment]
Closing for now, don't hesitate to reopen or comment to continue the discussion.

**Comment by monperrus** [comment]
Also interesting: "Anatomy of a perfect pull request"
https://opensource.com/article/18/6/anatomy-perfect-pull-request

**Comment by monperrus** [comment]
Dear all,

Very good reading: 
[Good Code Reviews, Better Code Reviews - Some Best Practices](https://blog.pragmaticengineer.com/good-code-reviews-better-code-reviews/)

Selected Quotes:

> Better code reviews are also empathetic. They know that the person writing the code spent a lot of time and effort on this change. These code reviews are kind and unassuming. They applaud nice solutions and are all-round positive.

> Better code reviews pay additional attention to making the first few reviews for new joiners a great experience. Reviewers are empathetic that the recent joiner might not be aware of all the coding guidelines and might be unfamiliar with parts of the code. These reviews put additional effort into explaining alternative approaches, pointing to guides. They are also very positive in tone, celebrating the first few changes to the codebase that the author is suggesting.
