### ISSUE TITLE
Spoon 7.0.0 is released!

### ISSUE THREAD

**Issue by surli** [INRIA/spoon#2041]
Hi everyone,

it has been a while since the last release of Spoon, so I'll try to do a new one before the end of the month.
My goal before the release would be that all PR with fixes are merged and validated (through Jenkins CI).

Apparently the remaining PR fixing a bug are the following:
 - ~~#1945~~ 
 - ~~#2040~~ 
 - ~~#2024~~ 
 - ~~#1771~~ 
 - ~~#2015~~ 

I don't think that #1771 will be fixed so soon, so I propose to keep that one for a future release. Do you think the other one are ok to be included in the next release? Do I miss something?

Concerning the release number, there is breaking PRs, like #2009 and we changed an important behaviour by making Spoon using by default the `noclasspath` mode, so **I'm favorable with doing a major release**.

So I propose to the next release to be Spoon 7.0.0. WDYT?

**Comment by tdurieux** [comment]
Should we update jdt at the same time? There is a new release available in maven central

**Comment by surli** [comment]
> Should we update jdt at the same time? There is a new release available in maven central

Yes if you want.

**Comment by monperrus** [comment]
This morning was a merge festival! Let's see if CI remains green after all those PRs together!

Next step before the 7.0.0, merging the Pattern feature.

**Comment by surli** [comment]
So finally all bug listed in my first comment had been fixed and pattern feature has been merged.

The remaining things to do are: 
  - #2074 (noclasspath)
  - #2054 (Java 10 var)
  - #2083 (imports after processing)

#2074 and #2054 should be merged soon. 
However #2083 remains difficult: I don't see any other clean way to fix it than refactoring the imports to attach them to types instead of compilation unit (purpose of #2085). 

This PR will again be a breaking one. But this task might take a while to be done. 

So for me we have three strategies here:
 1. We wait #2885 is completely done and fixes #2883 before releasing
 2. We keep the bug shown in #2883 open, maybe we deprecate some API I'm currently breaking in #2885 and we release
 3. We find another quick and dirty way to fix #2883 for this release, and we finish #2885 for the next one

I'm now in favor of 2. WDYT?

**Comment by surli** [comment]
Hi everyone,

so there is no more open bugs and I'm waiting for the two last PR to be merged (#2074 and #2083). Which mean, I should be able to release in the next few days.

## What to do about #1852 ?
My last question is about #1852 and the related issue #1846: the proposed solution is breaking a lot of API, so maybe it's more interesting to integrate it in Spoon 7, but I'm not yet sure how much work is it to finish it. Don't hesitate to participate to the conversation there.

Finally here's a first draft of the changelog for Spoon 7.0.0!

## Changelog

# Breaking changes

* Comments are now enabled by default in Spoon (PR: #2065)
* The mode "noclasspath" is now the default mode (PR: #1934 #2074)
* When an element is added twice to two different parents, an exception is now thrown (PR: #2009)
* The template API has been broken in favor of the new Pattern mechanism

# Major features

* The concept of Pattern has been introduced after the longest PR-ever in Spoon. This will improve a lot the job of using template for matching and generating code. Kudos to @pvojtechovsky for this amazing job! (PR: #1686)
* An incremental build launcher has been added to improve performance when building several times big models. Thanks @Egor18 ! (PR: #1905)
* Java 9 modules can now be built in full-classpath mode
* Java 10 is now fully supported in Spoon (PR: #2054)

# New features

* Handles range version in MavenLauncher. (PR: #2057)
* Add CtAnnotation#getAllValues to reason about all annotation values. (PR: #2042)
* One can get annotation values directly. (PR: #2036)
* EqualsVisitor can report which attribute is not equal. (PR: #1998)
* Add CtElement#descendantIterator and CtElement#asIterable. (PR: #1986)
* Add CtIterator for dfs-based iteration of CtElement's descendants. (PR: #1980)
* Add SourcePosition#isValidPosition(), to detect invalid position without null or -1 checks. (PR: #1964)
* Add #getSourceDetails to debug source code positions. (PR: #1950)
* Add the ability to follow the progress of the creation of the Spoon model. (PR: #2043)
* Add CtAnnotation#getWrappedValue to provide a regular interface for annotation values. (PR: #1935)
* experimental: Add ChangeCollector to listen on changes and remembers them. (PR: #1941)
* position: Add the position of the modifier in the ast. (PR: #1959)


# Bug Fixes

* Fix visibility of enum values. (PR: #1999)
* Proper support for "Object[]::new" constructs. (PR: #1945)
* Enum#valueOf is now well shadowed. (PR: #2096)
* Fix position of (String arg[]). (PR: #2015)
* Support creation of partial shadow classes. (PR: #2040)
* Init RoleHandler lazily to pass when RoleHandler is generated. (PR: #2068)
* Prevent NPE due to getDeclaringType. (PR: #2039)
* Fix regression due to #2009. (PR: #2035)
* CtAnnotation#getValue returns the default value if one exists. (PR: #2034)
* Detection of lambda expression method. (PR: #2023)
* Comment /*/ parsing in JDTCommentBuilder. (PR: #2032)
* Fix low-level JDT error due to some annotations (in particular @Nullable). (PR: #1975)
* Npe in getEnclosingType when getTypeDeclaration is null. (PR: #2033)
* Fix when interface method overrides object method. (PR: #2025)
* Fix CtTypeParameter creation in shadow mode. (PR: #2031)
* Consistent contract for getActualClass: never returns null. (PR: #2027)
* Fix missing license header. (PR: #2075)
* Fix regression in Template. (PR: #2069)
* Clarify Environment#checksAreSkipped and associated setters. (PR: #2011)
* Set parent of auto-created CtExecutableReference. (PR: #2007)
* Manage generics from interfaces in shadow mode. (PR: #1914)
* Bug when getting CU from a parsed snippet. (PR: #2086)
* Fix actualTypeArguments of array type reference. (PR: #1997)
* SetModifiers(Collections.emptySet()) resets modifiers now. (PR: #1992)
* Don't fail on ClassNotFoundException in CtQueryImpl. (PR: #1996)
* NPE when CtQueryImpl#detectTargetClassFromCCE return null. (PR: #1995)
* Handle comments at the bottom of a file. (PR: #1976)
* Catch NoClassDefFoundError when we try to import a class absent from the classpath. (PR: #1974)
* Fix LineFilter for loops with no body. (PR: #1973)
* Fix the position of catch variables. (PR: #1969)
* Set the constructor implicitness directly in JDTTreeBuilder. (PR: #1958)
* Fix the source start and source end of package. (PR: #1957)
* Fix failing build because of the usage of random in CompilationUnit comparison. (PR: #1954)
* Provide default sorting of compilation units. (PR: #1938)
* Remove useless CtPackageImpl#getPosition. (PR: #1952)
* Fix position of new `new SomeInterface() {...}`. (PR: #1949)
* Fix positions of TypeParameter, annonymous classes, and methods without modifiers. (PR: #1948)
* Add a log warning in verifySourceClasspath. (PR: #1937)
* Set noclasspath to true as default. (PR: #1936)
* Fix class class-level comments' position. (PR: #1931)
* Always create new type reference for primitive type. (PR: #1940)
* Comments after class name and before type members are associated to correct node. (PR: #1939)
* Typo in javadoc of CtModel. (PR: #1942)
* CtCatchVariable#getType() in noclasspath mode may return null. (PR: #1932)
* Fix bugs and resource leaks found with error-prone. (PR: #1924)
* Derived properties return unmodifiable collections. (PR: #1923)
* CompilationTest#testFilterResourcesDir file separators on Windows. (PR: #1925)
* All unsettable properties in the metamodel are derived too. (PR: #1904)
* DJPP is more tolerant to inconsistent model. (PR: #1903)
* comment: Creating an inline comment with newline separators throws an exception. (PR: #2080)
* executable: Fix npe in getExecutableDeclaration when declaring type is null. (PR: #2021)
* mavenlauncher: Add support for Maven dependency management. (PR: #2024)
* metamodel: Mark unsettable setters of name, modifier and label. (PR: #2048)
* module: Spoon is able to build Java 9 code with modules in full classpath. (PR: #2070)
* pattern: Improve handling of CtTypeReference Pattern parameters. (PR: #2078)
* reference: Fix npe in getTypeReference when the reference is null. (PR: #2020)
* EnumValues constructor call should be marked as implicit. (PR: #2090)


# Refactoring

* Introduce ModelList and ModelSet, collections specific to Spoon that handle parents and change events. (PR: #1917)
* Remove unused imports from tests. (PR: #2104)
* Report missing parameter value in exception. (PR: #2079)
* Fix bad resource usage with try-with-resources. (PR: #2045)
* Move metamodel from src/test to src/main. (PR: #2016)
* Remove usage of getActualClass() from CtTypeReferenceImpl. (PR: #2037)
* GetTypeDeclaration cannot crash in noclasspath mode. (PR: #2028)
* Remove deprecated elements from last release of Spoon. (PR: #2098)
* Get*Field now use shadow types. (PR: #2008)
* EqualsChecker#setNotEqual can be used to debug non-equality. (PR: #1993)
* PartialSourcePosition only supports getCompilationUnit for fail-fast behavior. (PR: #1963)
* Encapsulate try-with-resources for printing lists in DefaultJavaPrettyPrinter. (PR: #1956)
* Never return null from CtElement#getPosition() but NoSourcePosition. (PR: #1951)
* Remove old broken untested mechanism "buildOnlyOutdatedFiles". (PR: #1913)
* Remove old, unused, untested class Timer. (PR: #2017)


# Documentation

* Give our definition of public API. (PR: #2092)
* Add Youtube Links of Spoon presentations on Readme. (PR: #2082)
* Move package.html to package-info.java. (PR: #2005)
* Add link to Google Scholar. (PR: #1987)
* Update documentation after release 6.2. (PR: #1899)
* Update README.md to state Java 10 support. (PR: #2091)


# Tests

* Ignore OS specific EOL. (PR: #2006)
* Fix CtGenerationTest#testGenerateRoleHandler egg/chicken problem. (PR: #2087)
* Fix MavenLauncherTest. (PR: #2049)
* Compare the computed imports against human imports. (PR: #1365)
* Add test to check that all setters trigger a change event. (PR: #2010)
* Unify MetamodelTest and MetaModelTest. (PR: #2012)
* Better tests for derived and unsettable properties. (PR: #2050)
* SpoonMetaModel can be built without spoon sources, only using shadow classes. (PR: #1907)
* Remove testIncrementalModel. (PR: #2004)
* Add test for ExpressionTemplate. (PR: #2002)
* Add new test for shadow enums. (PR: #1926)
* Add a test to check that in NO_OUTPUT mode, nothing is created. (PR: #1915)


# Other

* Remove bold emphasis of component in changelog. (PR: #2046)
* Allow to use @Experimental on a single method. (PR: #2099)
* Run Spoon tests also on JDK10. (PR: #2053)
* Coverage computation now uses JDK9. (PR: #2071)
* Upgrade JDT version to 3.13.102. (PR: #2052)
* Upgrade copyright to 2018. (PR: #2058)
* Check license header presence in CI. (PR: #2066)
* Add SonarQube dashboard link. (PR: #2044)
* Change README to encourage usage/contribution. (PR: #2030)
* Fix SCM info in pom.xml. (PR: #1966)
* Fix revapi comparison against Snapshot. (PR: #1920)
* Fix typo in snapshot repository URL. (PR: #1910)
* Deploy snapshots on maven.inria.fr instead of gforge.inria.fr for better availability. (PR: #1900)
* Prepare for next development iteration.

# Authors
| Name    | Nb Commit |
|---------|-----------|
| Pavel Vojtechovsky | 36 |
| Simon Urli | 33 |
| Martin Monperrus | 20 |
| Thomas Durieux | 20 |
| Egor18 | 4 |
| Miguel Sozinho Ramalho | 2 |
| Lionel Seinturier | 2 |
| Filip Krakowski | 1 |
| Tomasz Zielinski | 1 |
| Roman Leventov | 1 |
| André Cruz | 1 |

**Comment by monperrus** [comment]
Awesome changelog!!!!!

Just made small changes. (in particular, note that the famous Pattern PR is meant to be almost fully-backward compatible with Template).

**Comment by surli** [comment]
I will do the release tomorrow. @monperrus @tdurieux @pvojtechovsky I propose that we won't merge anything until the release is done: then if everything's ok on the CI tomorrow morning I release.

**Comment by tdurieux** [comment]
I think we should fix the test for windows before

**Comment by surli** [comment]
> I think we should fix the test for windows before

I was hesitating to propose that, but I'm ok to postpone until those tests are working too. 

#2111 is a first fix towards this direction

**Comment by surli** [comment]
Finally all tests are now passing on Windows with the last merged PRs! \o/
The release will finally happen next week, because we never release a friday and we need all jobs to be passing this night.

**Comment by surli** [comment]
I just updated the changelog, this is the final one, I will release right now :tada:

**Comment by surli** [comment]
So, it is officially released today! Thanks to all the contributors for their job :)

**Comment by monperrus** [comment]
Thanks a lot Simon for leading the release effort!

**Comment by monperrus** [comment]
And BIG kudos to all contributors!
