### ISSUE TITLE
Can I export my project after refactoring using spoon ?

### ISSUE THREAD

**Issue by MAJHOOOOOL** [INRIA/spoon#2064]
Hello 

I want to refactor some code element in my project 

my code to refactor 

`launcher.addInputResource("src");
        launcher.buildModel();

.
.
.
.

System.out.println(cm.getSimpleName());
        Refactoring.changeMethodName(cm, "after");
        System.out.println(cm.getSimpleName());
`

the output 

> before
after

now I want to export my project after modification
can I  ?

**Comment by surli** [comment]
Hi @MAJHOOOOOL 

> now I want to export my project after modification

If by "export" you mean to get the source code of your project transformed, yes it's pretty easy actually.
You have first to specify in which directory to output the files, and then to call the prettyprint method:

```java
launcher.getEnvironment().setSourceOutputDirectory(new File("/path/to/my/dir"));
launcher.prettyprint();
```

**Comment by MAJHOOOOOL** [comment]
Thank you so much 

but why it is past full path after refactoring "in method call only"

for example 

my method name is 
before()

and after refactoring 
PackName.className.after()

**Comment by surli** [comment]
By default, Spoon works with full qualified names: it won't manage type imports.
To use it with imports and more natural types, you need to specify it:

```
launcher.getEnvironment().setAutoImports(true);
```

**Comment by MAJHOOOOOL** [comment]
Thank you so much
