### ISSUE TITLE
is there any way to refactor Package name 

### ISSUE THREAD

**Issue by MAJHOOOOOL** [INRIA/spoon#2067]
Hello 

http://spoon.gforge.inria.fr/mvnsites/spoon-core/apidocs/

I checked the javadoc for Class Refactoring

and I did not find anything about Package name refactoring  

is there any way to do this?

**Comment by pvojtechovsky** [comment]
Hello,

I am not aware of any package name refactoring method in spoon. But we gladly merge your PR if you implement one ;-)

This algorithm will be similar to `Refactoring#changeTypeName`. You just have to run it for each type in the package and then change the package name too.

**Comment by MAJHOOOOOL** [comment]
ummm I know it is easy and I will do it for my software but I do not think I will do it here because I do not want to do something not clean like the entire library

**Comment by MAJHOOOOOL** [comment]
Oh easy but not that much 

also, there is something should be solved 
`launcher.getEnvironment().setSourceOutputDirectory(new File("/path/to/my/dir"));
launcher.prettyprint();
`
when you use this code the package also will be not refactored after export

**Comment by pvojtechovsky** [comment]
Move your refactoring method from your class to Spoon class `Refactoring`. Give it some nice name and make a Pull request (PR) for that. Later we have to add some jUnit test too - it will be part of the same PR. We of course need only the part of the code which is relevant for all Spoon client's.
