### ISSUE TITLE
It is impossible to disable the no classpath with the command line

### ISSUE THREAD

**Issue by tdurieux** [INRIA/spoon#2073]

**Comment by surli** [comment]
Are you sure about that? 

We process the argument in that way in the launcher: 

```
environment.setNoClasspath(jsapActualArgs.getBoolean("noclasspath"));
```

So we always set the value based on the flag, which is false by default. Then even if when using the API Spoon is using noclasspath, when using the CLI, it should keep the old behaviour.

**Comment by tdurieux** [comment]
In fact the default value of noclasspath is still false because the default constructor of Launcher runs processArguments() which set the noclasspath to false.
