### ISSUE TITLE
Pattern and CtTypeReference

### ISSUE THREAD

**Issue by pvojtechovsky** [INRIA/spoon#2077]
I need some concept how to create pattern with CtTypeReferences and how to match and generate with them. The problem is with actual type arguments and with fact that client of Pattern should be able to define how should be the actual type arguments handled.

Example E1
```java
class Example1 {
   List<String> field1;
   Set<Double> field2;
   BiConsumer<Integer, Number> field3;
   Double field4;
   Set field5;
}
```
Now imagine that client wants to match fields of class Example1. There are possible these different matching requests
MA) match any field. E.g. using matcher like: `FieldType fieldName`, where `FieldType` and `fieldName` are parameters. Note: all fields 1-5 should match. And first match will be param `FieldType`==`List<String>` and `fieldName`==`field1`
MB) match any Set field. E.g. using matcher like: `Set fieldName`, where `fieldName` is parameter. Only fields 2 and 5 should match. 

Note: the solution should fit to both use cases of Pattern: 1) to matching 2) to generating

Generating example E2:
```java
class SomeType extends SuperType<SuperTypeParam> {}
```
(this example comes from `CtGenerationTest#testGenerateRoleHandler` and is related to issue #2076)
Here client might have these different requests:
GA) Substitute `SuperType<SuperTypeParam>` by any other type with any other parameters. E.g. `extends BiConsumer<A,B>` or `extends Double` or ...
GB) Substitute **qualified name** (not only simple name which causes issue #2076) of `SuperType`, and individually substitute actual type arguments. E.g. 
 `SuperType` -> `List` and `SuperTypeParam` -> `Double` will generate `extends List<Double>`

Should we support all these cases? WDYT?

**Comment by pvojtechovsky** [comment]
I actually tend to this approach:
* if parameter value type of Pattern parameter, which represents type reference is `String`, then we match/generate only qualified name. The actual type arguments stay unchanged.
Pattern:
```java
import somePackage.SomeType;
...
void method() {
  SomeType<Double> var1;
  if (var1 instanceof SomeType) {
    SomeType<?> value = (SomeType) var1;
  }
}
```
`pattern...parameter("type").byType(SomeType.class);`

it will generate following code with pattern parameter "type"<="java.lang.List":
```java
import java.lang.List;
...
void method() {
  List<Double> var1;
  if (var1 instanceof List) {
    List<?> value = (List) var1;
  }
}
```
note: different actual type arguments used on different instances of CtTypeReference to List.

* if parameter value type of Pattern parameter, which represents type reference is `CtTypeReference`, then we match/generate type reference including actual type arguments. 
This case is not usable in previous example, because client would need to handle each variant of type reference (`SomeType<Double>`, `SomeType`, `SomeType<?>`) individually. 
This case is usable in example like this Pattern:
```java
class B extends A {}
```
`pattern...parameter("superType").byType(A.class);`
it will generate following code with pattern parameter "superType"<="java.lang.List<String>":
```java
class B extends List<String> {}
```

I think that we should somehow support both approaches ... I just do not know how to define it in usable/understandable and implementable way...
WDYT?

**Comment by pvojtechovsky** [comment]
Here is more abstract description of the same problem.
Current Pattern concept expects that pattern parameter value can be mapped
A) to one attribute (CtRole) of a AST node. E.g. to simpleName
B) to zero, one or more AST nodes. E.g. to replace CtStatement(s) with another CtStatement(s)

But in case of CtTypeReference we need to map pattern parameter value of type CtTypeReference to muliple attributes of the AST node. It must be always mapped to simpleName, packageReference and to declaringType. And **sometime** we have to map also actualAypAarguments and **sometime** we have to ignore them (or somehow aggregate them?)

**Comment by surli** [comment]
Hi @pvojtechovsky 

concerning your first comment, I think it would be great to support MA and MB: there might be plenty of usecases here.
Concerning GA and GB, I've the feeling that it's not really a problem of usecase but a problem of implementation: GA seems more difficult to implement (and maybe to use?) than GB. Or am I wrong?

When you say: 
> This case is not usable in previous example, because client would need to handle each variant of type reference (SomeType<Double>, SomeType, SomeType<?>) individually.

I'm not sure to agree: maybe it's possible to treat differently generic types? Like using the type erasure for the matching and not the exact type. 

> I think that we should somehow support both approaches ... I just do not know how to define it in usable/understandable and implementable way...

If the problem is to define the API for end-user, I'd say that we need two different `parameter()` method for the patterns, after reading your examples.

Now I currently have no idea how to implement the changes :-/

**Comment by monperrus** [comment]
> I just do not know how to define it in usable/understandable and implementable way...
WDYT?

Do you mean with the fluent API? what's your current proposal?

**Comment by pvojtechovsky** [comment]
Thank you for your feedbacks. I see two contradictory ways how to work with `CtTypeReference`s in Pattern:
1) To take `CtTypeReference` as one node (pattern parameter value) with simpleName, packageRef, declaringType and actualTypeArguments. This approach is needed in (MA - example E1)

  The value of such pattern parameter would be always CtTypeReference, because Class or String cannot express all necessary information needed for matching on generating.

  For example: `OuterClass<TA, TB>.InnerClass<Something<A,B>>` would need exactly 1 pattern parameter of type `CtTypeReference`.

2) To understand `CtTypeReference` as combination of 3 independent nodes: 1) simpleName + packageRef; 2) actualTypeArguments; 3) declaringType. This approach would be very useful and understandable too in cases like example E3 (see above)

  The type reference would be in this case represented by more the one pattern parameter. First pattern parameter would represent the type (as pattern parameter String (qualified name) or Class), then there would be one pattern parameter for each actual type argument and optionally there would be pattern parameters which represents declaringType.

  For example: `OuterClass<TA, TB>.InnerClass<Something<A,B>>` would need about 7 pattern parameters

**Comment by pvojtechovsky** [comment]
So first question is: Do we want to support both ways W1 and W2. 

And if yes, then there is question how should the related Pattern API look like.

API for W1
1) definition of Pattern parameter: we have to select, which `CtTypeReference` nodes of source model have to become pattern parameters of type "full type reference". In example E1 we can simply say that type of CtField is pattern parameter. It doesn't matter in what way we select `CtTypeReference` nodes. But after they are selected they have to be handled as "full type reference"
2) the pattern matching and generating will both use parameter value of type CtTypeReference, where declaringType and all actualTypeArguments are fully initialized.

Note: with this approach the type references like: `List` and `List<?>` and `List<Double>` and `List<Set<String>>` are completely different nodes, which will fit to different patter variables.

API for W2
1) definition of Pattern parameter: we have to select all `CtTypeReference` nodes whose qualified name equals to required qualified name (String) or Class. But all selected nodes are not marked as parameters, instead only their attributes (simple name and package reference) are mapped to pattern parameter.
2) the pattern matching and generating will both use parameter value of type String, Class or CtTypeReference. But in case of CtTypeReference (if we will support that approach at all), the declaringType and all actualTypeArguments are null/empty.

Note: with this approach the type references like: `List` and `List<?>` and `List<Double>` and `List<Set<String>>` will share pattern parameter based on `java.util.List`

**Comment by surli** [comment]
I might be wrong but I have the feeling that W2 is not what I would want when playing with Patterns. It seems to me more like "playing with String", than really using strong types, which is one strength of Spoon. 

But I'm not yet a Pattern user ;)

**Comment by pvojtechovsky** [comment]
I already used Templates/Patterns to generate code. I like this approach a lot because it is easy to maintain.
End the code in example E3 above is exactly the situation, which happens when generating code. You need to replace references to generic template type X by real type Y and the actual type arguments has to be replaced individually (or sometime kept as they are). 

> "playing with String"

I understand what you mean. But here is not just string it is usage of whole `Generic type` ... with variable type parameters - which may be independent ... depending on use case. So it fits with Spoon thinking too from my point of view

**Comment by monperrus** [comment]
Close for cleaning?
