### ISSUE TITLE
tests fail with windows

### ISSUE THREAD

**Issue by boeserwolf91** [INRIA/spoon#208]
Unfortunately the project can't be build with windows anymore. I get 18 test failures. 

[Here is the console output under windows](https://gist.github.com/boeserwolf91/7a8299c8b6c555e56c29)

**Comment by GerardPaligot** [comment]
Thanks for your report. We don't develop on Windows so we didn't notice this bug. We will try to got a windows instance to fix these errors (or PR is welcome of course!).
