### ISSUE TITLE
BUG: ModelBuildingException: Cannot infer type arguments

### ISSUE THREAD

**Issue by justinwm** [INRIA/spoon#2081]
Hi! 

I am using the Spoon of version 6.2.0 to analyze java source files, and encountered the following error:
<img width="1787" alt="image" src="https://user-images.githubusercontent.com/2504533/41573708-9328555e-73b0-11e8-843f-3ee755eeb482.png">

The line 229 of the target source file is:

`        disruptor = new Disruptor<>(factory, ringBufferSize, threadFactory, ProducerType.MULTI, waitStrategy);`

It seems that Spoon cannot infer the argument type of Disruptor<>.

Actually, I am analyzing the Apache Logging project https://github.com/apache/logging-log4j2, and the  target source file is `logging-log4j2/log4j-core/src/main/java/org/apache/logging/log4j/core/async/AsyncLoggerConfigDisruptor.java`.

I have added all the required classpathes simply using the following code:

<img width="659" alt="image" src="https://user-images.githubusercontent.com/2504533/41573838-44598938-73b1-11e8-8a82-d489145cd955.png">

Here, the filename is the target source file.

Have anyone encountered similar errors? Hope you can help me resolve this issue. Thanks very much!!

**Comment by tdurieux** [comment]
Can you provide the classpath that you use?

**Comment by justinwm** [comment]
@tdurieux 

I have added the library, which provides the the class `com.lmax.disruptor.dsl.Disrupter` to the classpath. 

Actually, I have resolved this issue by providing the source code of library `com.lmax.disruptor.dsl.Disrupter` instead of the jar file.

Although I do not know what's the differences, it resolves this issue for now :-)

Thanks very much!

**Comment by surli** [comment]
So apparently it's fixed. I close this one for now.
