### ISSUE TITLE
How to transform CtType object to CtClass?

### ISSUE THREAD

**Issue by Gu-Youngfeng** [INRIA/spoon#2084]
Hi, all! I meet problem in getting supper class of its child class, like the following code,

    CtClass spcls = (CtClass) cls.getSuperclass().getTypeDeclaration(); // get **cls's** supper class spcls

This code can run without exception, but I know the `getTypeDeclaration()`'s return type is `CtType`, and I am curious about how to transform `CtType` to `CtClass` in a meaningful way.

**Comment by monperrus** [comment]
Your cast operator is correct!  I don't know another way. One could possibly add a convenience method asCtClass in CtType.

**Comment by Gu-Youngfeng** [comment]
Dear Dr. Martin Monperrus, thanks for your kindly help, but why method `getDeclaration()` returns a null object?

    CtClass spcls = (CtClass) cls.getSuperclass().getDeclaration();
    System.out.println (spcls == null); // true

The apidco of `getSupperclass()` says that `getDeclaration()` and `getTypeDeclaration()` can both return the CtType object. Here is the doc of `getSupperclass()`,

> **CtTypeReference<?> getSuperclass()**
> Returns the class type directly extended by this class.getSuperClass().getDeclaration()/ getTypeDeclaration() returns the corresponding CtType (if in the source folder of Spoon). 
> **Returns:**
> the class type directly extended by this class, or null if there is none or if the super class is not in the classpath (in noclasspath mode)

**Comment by surli** [comment]
To be short: 
`getDeclaration()` will only look in your sources to get the proper type: if the type you're looking for is not in the source you provided, it returns null.

`getTypeDeclaration()` will look in your sources but also in your classpath: if the type you're looking is neither in the sources or in the classpath, it returns null. 

Hope this helps.

**Comment by Gu-Youngfeng** [comment]
Hi, @surli. But if I add option of launcher,

    launcher.getEnvironment().setNoClasspath(true);

`getDeclaration()` still return null value.

**Comment by surli** [comment]
Here the option won't change the return value: it just avoids to get an error when you parse your source code.

Let's say that you got a class: 

`public class A extends B {}`

 in your source and B is only available in an external Jar that you don't put in the classpath for Spoon.
In noclasspath, you will be able to parse this code, in noclasspath mode. 

Still the `getDeclaration()` of the superclass of `A` will return null, because B is unavailable from your sourcecode.
