### ISSUE TITLE
Metadata in node

### ISSUE THREAD

**Issue by danglotb** [INRIA/spoon#2089]
Hello all,

It would be great to have metadata inside the nodes of the Spoon model, something that is not in the java code but rather for spoon usage.

These data could be used for several things such as sorting elements, colors of the nodes etc...

Imagine a process in several iterations. At each iteration, each node has a new color, according to an arbitrary criterion. In the second iteration, the process is different according to the colors of the node.

WDYT?

Cheers.

**Comment by tdurieux** [comment]
What is the difference with the current CtElement.putMetadata(...)?

**Comment by danglotb** [comment]
None, I didn't know this feature. Sorry & Thank you!
