### ISSUE TITLE
refactor: fix all IDEA code inspection warnings

### ISSUE THREAD

**Issue by zielint0** [INRIA/spoon#2105]
**Please do not close this issue before 2019-01-01**

Proposition of IntelliJ IDEA Code Inspection. I will create a ruleset from this task.

Class structure
- Utility class is not 'final'
   - #2355 (8 warnings) 2018-08-09

Code style issues
- 'expression.equals("literal")' rather than '"literal".equals(expression)' :+1: 
   - ~~#2365 (24 warnings) 2018-08-10~~
- C-style array declaration :+1: 
   - ~~#2229 (3 warnings) 2018-07-16~~
- 'size() == 0' replaceable with 'isEmpty()' :+1: 
   - ~~#2232 (68 warnings) 2018-07-16~~
- Multiple variables in one declaration :+1: 
   - ~~#2346 (4 warnings) 2018-08-04~~
- Redundant 'new' expression in constant array creation :+1: 
   - ~~#2344 (3 warnings) 2018-08-03~~
- Unnecessary call to 'super()' :+1: 
   - ~~#2274 (76 warnings) 2018-07-24~~

- Java language level migration aids
   - Java 5
      - 'StringBuffer' may be 'StringBuilder' :+1: 
         - ~~#2230 (1 warning) 2018-07-16~~
      - 'while' loop replaceable with 'foreach' :+1: 
         - ~~#2231 (2 warnings) 2018-07-16~~
   - Java 7
      - Explicit type can be replaced with <> :+1: 
         - ~~#2227 (11 warnings) 2018-07-16~~
- Unnecessary semicolon :+1: 
  - ~~#2226 (25 warnings) 2018-07-15~~

Control flow issues
- Pointless boolean
   - #2242 (102 warnings) 2018-07-18
- Unnecessary 'null' check before 'instanceof' expression or call :+1: 
   - ~~#2267 (3 warnings) 2018-07-23~~

Data flow
 - Redundant local variable
   - ~~#2275 (10 warnings) 2018-07-24~~

Declaration redundancy
- Redundant throws clause :+1:
  - ~~#2221 (6 warnings) 2018-07-15~~ 

Imports
- Unused import :+1:
  - ~~#2104 (105 warnings) 2018-06-24~~ 

JUnit
- Misordered 'assertEquals()' arguments
   - ~~#2314 (14 warnings) 2018-07-31~~

Performance
- 'Collection.toArray()' call style
   - ~~#2343 (11 warnings) 2018-08-02~~
- Manual array to collection copy :+1: 
  - ~~#2224 (4 warnings) 2018-07-15~~
- Redundant 'Collection.addAll()' call :+1: 
  -  ~~#2225 (1 warning) 2018-07-15~~
- String concatenation in loop :+1: 
  - ~~#2234 (3 warnings) 2018-07-15~~

Probable bugs
- Unused assignment
   - ~~#2263 (18 warnings) 2018-07-22~~

Verbose or redundant code constructs
- Redundant 'isInstance' or 'cast call :+1: 
   - ~~#2433 (3 warnings) 2018-09-01~~
- Redundant Collection operation :+1: 
   - ~~#2281 (1 warning) 2018-07-26~~
- Unnecessary return statement :+1: 
   - ~~#2233 (4 warnings) 2018-07-16~~

**Comment by surli** [comment]
I'm not sure about the purpose of this issue. In general we try to create one issue by subject on Spoon: here it looks like you're trying to list all the changes you're doing to improve technical debt. Am I right?

Why not just creating the PR instead?
And finally why do you need to leave this issue open until 2019?

**Comment by zielint0** [comment]
Hello Simon
> Am I right?

Yes. The purpose of this issue is to gather all pull requests with fixes decreasing technical debt. It helps tracking progress and shows what was done (i.e. inspections) and when.

> Why not just creating the PR instead?

I create PRs and link them here.

> And finally why do you need to leave this issue open until 2019?

I plan to fix everything before 2019 and add new features after.

**Comment by zielint0** [comment]
Could somebody allow me to:
 - create labels
 - use labels on issues and PRs
?

I would like to mark all activities using proper label for clarity.

Thank you very much in advance.

**Comment by surli** [comment]
Hi @zielint0 

in order to create/use labels on Github you need write access on the repository.
However as stated in our [contributing guidelines](https://github.com/INRIA/spoon/blob/master/CONTRIBUTING.md) the community grant write access after a significant amount of work on the repository. You just arrive here some days earlier so it's a bit early to give you this grant :) 

But let express what kind of new label you'd want and I'll apply them on your issues.

**Comment by zielint0** [comment]
@surli 

Please create a YELLOW label 'code inspection'.
Please mark my all past (created) ISSUES and PRs as 'code inspection'.
Please mark all future ISSUES and PRs as 'code inspection' (we are talking about ones with fixes from Code Inspection).

Thank you!

**Comment by surli** [comment]
Sorry but after second thought I don't really see the point there: if it's about marking only your PR/issues, you can already use the Github filters to access them quickly, so why creating a new specific label then? 

At least I would have agree on a label called "Refactoring" maybe, which would have been useful for other people. Here it seems you want to mark only your PRs, I'm not sure to understand the way you work.

**Comment by zielint0** [comment]
Of course I will open also other issues and PRs, not only 'code inspection' ones :-)
So there will be not mapping: my prs <=> code inspection.

**Comment by monperrus** [comment]
a good issue is a one for which the closing criterion is super clear, renamed this one to "fix all IDEA code inspection warnings"

**Comment by zielint0** [comment]
@monperrus 
That's right! :)

**Comment by monperrus** [comment]
is it possible to embed IDEA inspection warnings in Travis CI directly? or in SonarQube?

**Comment by zielint0** [comment]
@monperrus 
> is it possible to embed IDEA inspection warnings in Travis CI directly? or in SonarQube?

After some digging I found that perhaps Travis can live with Coverity
https://web.archive.org/web/20160112183828/https://scan.coverity.com/travis_ci
