### ISSUE TITLE
Support Java 11 in Spoon

### ISSUE THREAD

**Issue by surli** [INRIA/spoon#2106]
Java 11 will be released in September. The complete changelog is available there: http://openjdk.java.net/projects/jdk/11/

So far I see the following change that might impact Spoon:
  - introduce `nest` access-control context (http://openjdk.java.net/jeps/181)
  - `var` keyword is authorized in lambda variable declaration (http://openjdk.java.net/jeps/323)
  - deprecated (since Java 9) Java API are removed from standard API (http://openjdk.java.net/jeps/320)

**Comment by monperrus** [comment]
Closed per #3029, thanks to @Egor18
