### ISSUE TITLE
chore(ci): build Spoon on a windows slave

### ISSUE THREAD

**Issue by surli** [INRIA/spoon#2109]
We currently do not have a windows slave on the CI to check that all tests are passing on Windows too. See #2108

**Comment by tdurieux** [comment]
We never succeed to have something stable on Windows

**Comment by surli** [comment]
Could you elaborate?

**Comment by tdurieux** [comment]
We had appveyor configured but it was not stable, it maybe changed

INRIA jenkins  did not support windows properly, @GerardPaligot never succeed to configure the slave (even with the help of the IT...)

**Comment by surli** [comment]
Done: we now have Jenkins running `mvn install` on a Windows slave at each commit on master: https://ci.inria.fr/sos/job/spoon-windows

**Comment by tdurieux** [comment]
and we have Failures: 37 :/
