### ISSUE TITLE
Release 4.1: May 5, 2015

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#216]
Hi all,

The next release 4.1 is planned for Tuesday 5th May. It will contain the recent bug fixes done since 4.0.0.

--Martin

**Comment by GerardPaligot** [comment]
Hi all,

We are happy to announce that Spoon 4.1.0 is released. This version brings fixes from Spoon 4.0.0.

You can retrieve the changelog here:

- Sets the parent of a field to its declaring type.
- ClassCastException for CtAnnotationType#getAllMethods()
- Throws an exception when we try to insert statement before super invocation.
- Prints type annotations on fully qualified name.
- NullPointerException thrown in CtTypeImpl#getUsedTypes when inner types are used.
- ClassCastExection for CtTypeInformation#getSuperclass.
- Adds a default expression for fields typed by an annotation.
- Generates site with Java 8.

Thanks for all contributors!
 
To download it:

Jar: https://gforge.inria.fr/frs/?group_id=73

Maven: http://search.maven.org/#artifactdetails%7Cfr.inria.gforge.spoon%7Cspoon-core%7C4.1.0%7Cjar

This issue can be closed.

**Comment by petitpre** [comment]
done
