### ISSUE TITLE
doc: push examples from ow2 and INRIA spirals-team seminar to spoon-examples

### ISSUE THREAD

**Issue by surli** [INRIA/spoon#2174]
Some examples have been used to present Spoon in different seminars: they should be published on spoon-examples repository.

**Comment by monperrus** [comment]
do you still have the sources?

**Comment by surli** [comment]
> do you still have the sources?

I guess everything's there: https://github.com/surli/ow2con sorry for the poor doc in it.

**Comment by monperrus** [comment]
closed by https://github.com/SpoonLabs/spoon-examples/pull/18
