### ISSUE TITLE
setParent() not set consistently in many cases

### ISSUE THREAD

**Issue by leventov** [INRIA/spoon#220]
In AST node linking methods, almost never `node.setParent(this)` is called, that is inconvenient most of the time. Especially strange, that after some `XxxFactory.createYyy()` calls I should also type `y.setParent()`. For example, after `MethodFactory.create()`.

However, *sometimes* it is set, search for `setParent(this)` in this repo on Github.

**Comment by monperrus** [comment]
long-standing known problem, #224 takes care of this, for most of the cases.
