### ISSUE TITLE
Should CtScanner visit CtExtendedModifier?

### ISSUE THREAD

**Issue by pvojtechovsky** [INRIA/spoon#2218]
There is new "element" in model `CtExtendedModifier`. May be it should be visited by CtScanner too?

What do you think?

Note: when sniper mode visits Spoon AST and builds tree of source fragments, it needs to visit `CtExtendedModifier`s too. 

WDYT?

But may be `CtExtendedModifier` is not real AST node element and it is correct as it is now. Sniper mode can live with that ;-)

**Comment by pvojtechovsky** [comment]
Note that CtComment is not source element same like `CtExtendedModifier` ... and we are scanning it

**Comment by monperrus** [comment]
close?

**Comment by pvojtechovsky** [comment]
sniper mode is handling CtExtendedModifier individually. The code would be easier if CtScanner would visit CtExtendedModifier too. So I need your opinion here. Is CtExtendedModifier kind of element which should be visited by CtScanner or not?

**Comment by monperrus** [comment]
I have no opinion. If the change is backward compatible, that's perfectly fine to scan CtExtendedModifier.

**Comment by pvojtechovsky** [comment]
CtExtendedModifier would have to implement CtElement and then we can scan it
