### ISSUE TITLE
bug: should reject invalid names according to the Java specification

### ISSUE THREAD

**Issue by danglotb** [INRIA/spoon#2237]
Hi all.

I am opening this thread to discuss the possibility of checking the name against the specification names.

Currently in Spoon, I can do the following:

```java
CtVariableReference reference = factory.createLocalVariableReference().setSimpleName("tacos.EatIt()")
factory.createVariableRead(reference, false);
```

This can lead to an inconsistency of the spoon model because the invocation is represented by a local variable.

What can be done, is a check on the provided name, using a regex.

WDYT?

EDIT: I fixed the snippet since it was incorrect. However, the discussion remains the same and open.

**Comment by pvojtechovsky** [comment]
Do you mean that Spoon should allow only reference and element names, which can be `java identifier`?
I like this idea. 👍

**Comment by surli** [comment]
I think we can easily enforce the usage of identifier as defined in the JLS through regexp in our different factories. I can take this one.
