### ISSUE TITLE
Android not supported below  Android N

### ISSUE THREAD

**Issue by manishjaswal** [INRIA/spoon#2243]
I am not able to integrate Spoon in project where I have to support Android API level 19

I am getting message : 

Default interface methods are only supported starting with Android N (--min-api 24): boolean spoon.pattern.internal.node.RepeatableMatcher.isMandatory(spoon.support.util.ImmutableMap) |  
-- | --

Sample code repository is : https://github.com/manishjaswal/AndroidSpoon

**Comment by surli** [comment]
I just checked your project and here it's become tricky: Spoon uses Java 8 features such as `default` methods in interfaces. And here the error messages says that Java 8 is not supported below Android N.

I'm not really familiar with Android and the gradle process, so maybe you can hack it a bit to avoid the check of Spoon classes.
Else the easiest way I see here is to use Spoon outside the Gradle plugin process: so to create a Java Maven project using Spoon and to call Spoon on the sources using the Java API.

Sorry not being more helpful here.
