### ISSUE TITLE
Model is not coherent around CtTargetedAccess, CtSuperAccess, CtThisAccess, CtTypeAccess

### ISSUE THREAD

**Issue by leventov** [INRIA/spoon#225]
- `CtSuperAccess<T>` extends `CtTargetedExpression<T, E>` with `E` as `CtExpression<?>`, however, `E` should be maybe `CtTypeAccess<T>`.

- `CtThisAccess` is *not* a subinterface of `CtTargetedAccess`, despite it is mentioned in `CtTargetedAccess` doc comment.

- I doubt `CtTargetedAccess` is ever a useful abstraction, because `this` and `super` are not proper variables.

**Comment by monperrus** [comment]
Could you create three different issues to discuss them separately?
