### ISSUE TITLE
CtSuperAccess<T> extends CtTargetedExpression<T, E> with E as CtExpression<?>, however, E should be maybe CtTypeAccess<T>.

### ISSUE THREAD

**Issue by leventov** [INRIA/spoon#226]
- `CtSuperAccess<T>` extends `CtTargetedExpression<T, E>` with `E` as `CtExpression<?>`, however, `E` should be maybe `CtTypeAccess<T>`.

**Comment by GerardPaligot** [comment]
`CtTargetedExpression` is extended by `CtSuperAccess` and `CtFieldAccess`. For `CtSuperClass`, `CtTypeAccess` could be the target expression (expression who uses the type specified in `E`). But it isn't always a type for `CtFieldAccess` so we cannot specify `CtThisAccess` in the interface of `CtTargetedExpression`.

But with my last [PR](https://github.com/INRIA/spoon/pull/230), we return a instance of `CtTypeAccess` for the target of a `CtSuperAccess` when there is an explicit type before the `super`.

**Comment by monperrus** [comment]
done my #230
