### ISSUE TITLE
Is there a way to detect all dependence's in a block of code

### ISSUE THREAD

**Issue by MAJHOOOOOL** [INRIA/spoon#2260]
Hi 

I want to detect all dependence's in a block of code

for example 

```
class a {
static int i 
static void Hello(){
////////
}
}

class b{

void test(){
a.hello()

print a.i + 5
}
}

```

So I want to detect all dependence's in class b that depend on any other component in my project

thank you

**Comment by pvojtechovsky** [comment]
I do not know special utility for that purpose, but I would use code like this:
```java
CtClass clazzB = ...;
new CtScanner() {
   public <T> void visitCtTypeReference(final CtTypeReference<T> reference) {
      //this is called whenever anything in code references another type
      super.visitCtTypeReference(reference);
   }.scan(clazzB);
}
```

**Comment by surli** [comment]
I'm closing this one as it got an answer. Don't hesitate to reopen it if needed.

**Comment by MAJHOOOOOL** [comment]
Sorry I have some difficulties to use CtScanner

let us assume w have a method called getAge()
And I want to scan if method buddy contain any dependence's on other class, methods or fields 
What is the code should I use

**Comment by surli** [comment]
@pvojtechovsky give you exactly a snippet of code that you could use for that. The you can then add a check on `reference.getSimpleName().equals("getAge")` for example.

**Comment by MAJHOOOOOL** [comment]
Sorry for this 

But I am really confused 

can you please give me a full example of how to use it
Sorry for that

**Comment by monperrus** [comment]
Closing, don't hesitate to reopen.
