### ISSUE TITLE
How to get error reports from the JDT compiler?

### ISSUE THREAD

**Issue by Vetii** [INRIA/spoon#2271]
I am trying to run a Processor using the Launcher. I saw there was a way to run a standalone compiler, but since I also wanted to generate source files, I went for the launcher, since it was fairly easy to use.

I would like the compiler to compile the generated source code, so that I get to see if there are errors. However, when the compilation works, I get class files, but if I try to make the compiler fail (by generating invalid code), it seems to fail silently, the only change is that no classes are generated.

Here is my code (I am using Kotlin, instead of Java):
```
    fun run(filePath : String, outputDirectoryPath : String): Boolean {
        try {
            var launcher = Launcher()
            launcher.addInputResource(filePath)
            launcher.environment.isAutoImports = true
            launcher.setSourceOutputDirectory(outputDirectoryPath)
            launcher.environment.outputType = OutputType.CLASSES
            launcher.environment.setShouldCompile(true)
            launcher.addProcessor(CoCoProcessor()) // My Processor
            launcher.run()
            println(launcher.environment.errorCount) // Prints 0
            return true
        } catch (e : FileNotFoundException) {
            val workingDir = System.getProperty("user.dir")
            println("File not found, working directory: '$workingDir'")
        }
        return false
    }
```

Is there any way to get an exception, some logging, or some sort of data about whether or not compilation succeeded, and why?

**Comment by tdurieux** [comment]
You can get them like this: `((JDTBasedSpoonCompiler) launcher.getModelBuilder()).getProblems();`

**Comment by Vetii** [comment]
Works, thanks!

Is there something about this in the doc? If I want to add it to the doc, what is the right place?

**Comment by Vetii** [comment]
Will try to find a way, found my answer, closing.
