### ISSUE TITLE
Deprecate CtTargetedAccess?

### ISSUE THREAD

**Issue by leventov** [INRIA/spoon#228]
- I doubt CtTargetedAccess is ever a useful abstraction, because `this` and `super` are not proper variables.

**Comment by GerardPaligot** [comment]
Well, it is difficult to define what is `this` and `super`. Yes, they aren't really variables but what are they?

**Comment by leventov** [comment]
The fact that `super` and field accesses are not things of any common kind, more specific than "Java AST token", makes CtTargetedAccess useless abstraction, the only thing you can do with it is begin instanceof checking..

so in order to reduce noise and confusion with CtTargetedExpression (the actually useful abstraction), IMO it's worth to deprecate it and/or exclude from Javadoc generation.

Even if you agree with me, of cause it's not neccessary, because it's not a bug or problem.
