### ISSUE TITLE
compile error by passing this as a parameter

### ISSUE THREAD

**Issue by tiran1984** [INRIA/spoon#229]
when i try to compile a class with this code 
...
   public boolean addToItems(ICItemDO target) {
        target.setAnswer(this);
        return this.displayItems.add(target);
    }
...
the compiler cant unterstand the line 
  target.setAnswer(this); 
when i set null or a new object it will compile

**Comment by GerardPaligot** [comment]
I can't reproduce your bug. I wrote a test case with the sample:

```java
public class Sample {
	private List<ICItemDO> displayItems = new ArrayList<ICItemDO>();

	public boolean addToItems(ICItemDO target) {
		target.setAnswer(this);
		return this.displayItems.add(target);
	}

	class ICItemDO {
		void setAnswer(Sample sample) {
		}
	}
}
```

And I compile it with spoon but all works fine.

Which version of spoon did you use? And how did you use it?

**Comment by tiran1984** [comment]
i use the current version 4.1

**Comment by GerardPaligot** [comment]
That is ok. Can you give us more context of your bug? And can you give us a stacktrace?

**Comment by tiran1984** [comment]
in a simple example it works.

**Comment by GerardPaligot** [comment]
Unfortunately, if you don't give more information, I can't help you.
