### ISSUE TITLE
feature: improve logging to be able to suppress certain messages

### ISSUE THREAD

**Issue by Tallic** [INRIA/spoon#2290]
The new logging features are nice, however, i am not able to adjust spoons logging behavior which is especially inhibiting given the leveling of some messages.

```
20:17:09.948 [DEBUG] [spoon.Launcher] Some annotations might be unreachable from the shadow element: spoon.support.reflect.declaration.CtMethodImpl@7f2c2e78
```
This message should definitely be on trace level, it is mostly uninformative and spams the output during development (DEBUG) up to the point where the IDE runs out of memory. Not to speak from the extra time it takes to print the same line over and over again.
Attempts to mute the spoon logger failed (which would be sad as all the good intentions go to waste).
Another indication that this needs a fix is given in your own code in the `Metamodel` class:

```java
public static Set<CtType<?>> getAllMetamodelInterfaces() {
		Set<CtType<?>> result = new HashSet<>();
		Factory factory = new FactoryImpl(new DefaultCoreFactory(), new StandardEnvironment());
		//avoid debug messages: Some annotations might be unreachable from the shadow element:
		//which causes bad meta model creation performance
		factory.getEnvironment().setLevel("INFO");
		result.add(factory.Type().get(spoon.reflect.code.BinaryOperatorKind.class));
		result.add(factory.Type().get(spoon.reflect.code.CtAbstractInvocation.class));
....
```
However, setting the global logging level is *not* the proper solution as this is not always possible.

**Versions**
Spoon: 7.0.0

**Comment by Tallic** [comment]
Ok thanks. 
Consider replacing the log message with a proper java doc string as it describes parts of the contract and not an event happening in the runtime (uncesserary straining resources).

> However not sure to understand the problem with muting the logger? 

Changing the log level on your logger has no influence. 

> You would want that we use several different loggers inside Spoon to be able to custom the level for the different procedures?

The `Launcher.LOGGER` is a global variable (bad) and a logging antipattern ([Logging Best Practices](https://wiki.opendaylight.org/view/BestPractices/Logging_Best_Practices#Logger_instances)) as the messages cannot be attributed to the emitting code in the log.

Generally:
> Each class containing calls to the logging subsystem MUST have its own logger, which is not shared with any other class. The variable holding reference to this logger MUST me named 'LOG'. The easiest way to ensure you have the proper logger declaration is to use the following pattern:

**Comment by surli** [comment]
OK we are on the same page on the refactoring needed for the logger then :)
