### ISSUE TITLE
bug? About the usage of CtCodeSnippetStatement

### ISSUE THREAD

**Issue by surli** [INRIA/spoon#2318]
I just found in https://github.com/SpoonLabs/astor/pull/112 that @martinezmatias was using `CtCodeSnippetStatement` in given more that one statement at a time, and it was working in 6.2.0 but apparently no more in 7.0.0. 

Here's an example of the test and its behaviour in Spoon 7.0.0:

```java
String snippet = "int n=0; n += 2";
Factory factory = new FactoryImpl(new DefaultCoreFactory(), new StandardEnvironment());
CtStatement st = factory.Code().createCodeSnippetStatement(snippet).compile();

System.out.println(st.toString()); // n += 2;
CtElement fix = ((CtBlock) st.getParent()).getStatement(1); // indexOutOfBoundsException : there's only one statement
```

So apparently there's a bug here because the second statement indeed have the block as parent, but is not included as a statement of the block. 

Now the question is: should a `CtCodeSnippetStatement` accept to get more that one statement? Shouldn't we create a new element `CtCodeSnippetBlock` to those cases? 

I'm really not a user of those features in Spoon so I need your vision on this one.

**Comment by surli** [comment]
OK in fact my "bug" was coming because of this line: https://github.com/INRIA/spoon/blob/59ea00ebbc064205c2fc05caa438e437527cc402/src/main/java/spoon/support/compiler/SnippetCompilationHelper.java#L96

This was added by @pvojtechovsky to detach the statement from the snippet to allow its usage elsewhere. However the parent of element is still set to the snippet which might cause the kind of error I got. Then shouldn't we also remove the parent from the detached parent? WDYT?

**Comment by pvojtechovsky** [comment]
> Then shouldn't we also remove the parent from the detached parent?

@surli, I do not understand what exactly do you suggest. Could you please write the suggested java code, so it is more clear?

**Comment by surli** [comment]
```java
String snippet = "int n=0; n += 2";
Factory factory = new FactoryImpl(new DefaultCoreFactory(), new StandardEnvironment());
CtStatement st = factory.Code().createCodeSnippetStatement(snippet).compile();

// I propose that change:
assertNull(st.getParent());
```

**Comment by pvojtechovsky** [comment]
I agree to detach parent too, so the code will be something like 
```java
ret.delete();
ret.setParent(null);
```

**Comment by surli** [comment]
Indeed. OK I'll make a PR in that way.

**Comment by monperrus** [comment]
@surli do you have an ongoing WIP PR on this?

**Comment by surli** [comment]
Not yet.
