### ISSUE TITLE
is there some support for method parameters renaming? 

### ISSUE THREAD

**Issue by MAJHOOOOOL** [INRIA/spoon#2347]
Hi 

Is there any method in a spoon to refactor the parameters of a method?

Thank you

**Comment by surli** [comment]
What do you mean by refactoring? Renaming?

**Comment by MAJHOOOOOL** [comment]
Sorry about this 

Yes 
Renaming

**Comment by surli** [comment]
As far as I know there is no off-the-shelf tool in Spoon for parameter refactoring. However we do have something for local variable refactoring, so maybe it could be adapted for parameters.

**Comment by monperrus** [comment]
what about `CtRenameRefactoring`?

**Comment by pvojtechovsky** [comment]
There is parameter name refactoring.
There is `CtRenameLocalVariableRefactoring`, which can rename local variable. The renaming of method parameter is probably simpler then `CtRenameLocalVariableRefactoring`, so you can try to copy `CtRenameLocalVariableRefactoring` and keep there the code which checks parameter name conflicts only. If you made something like that we gladly have a look at your PR ;-)
