### ISSUE TITLE
CtElementImpl.EMPTY_LIST

### ISSUE THREAD

**Issue by leventov** [INRIA/spoon#236]
Is there special reason for defining own EMPTY_LIST and EMPTY_SET, instead of using standard like `java.util.Collections.emptyList()`? Research showed this was added in this commit: 804ec47132d1b27d7356012aa7f9310649d69992 by Renaud Pawlak.

I found this, because there are constructs like `if (foos == EMPTY_LIST()) foos = new ArrayList<>(); foos.add(foo)` in plenty of `addFoo()` methods.

When I create a method like `createMethod(emptyList(), emptySet(), emptyList(), emptySet())` (these empties stands for modifiers, parameters, formal type parameters, exceptions, etc.), and use static methods from `Collections` class, then when I try to add parameter or exceptions, Spoon doesn't replace unmodifiable empty collections with new modifiable before adding, and throws `UnsupportedOperationException`, because it compares against Spoon's `EMPTY_LIST()`.

So, the question is -- is that incompatibility with `Collections.emptyList[Set]` is intentional. If not, it's better to remove these customs for usecases like I explained in the previous paragraph.

**Comment by leventov** [comment]
I see now -- this explained in a very recent commit, with changes regarding this -- 18a05bade6c39123b0e712203ae39c86553e675a

I don't understand why `clear()` is deadly required, you can add a wrapping method like.
```
static void clear(List<?> l) {
  if (l == emptyList()) return;
  l.clear();
}
```

**Comment by leventov** [comment]
If performance and memory consumption that matters, `emptyCollection -> new ArrayList()` is also far from optimal.

First of all, `new ArrayList<>()` allocates an array of 10 elements, that is too much parameters, formal type parameters, constructors, anonymous executables, fields.

`TreeSet` used as a default container for AST tokens kept in `Set`s is also very inefficient, if you doesn't need sorted semantics -- it's entry Object has 5 reference fields and 1 boolean, i. e. takes about 64 bytes on 64-bit JVM without CompressedOops.

I suggest to consider [SmallCollection pattern](http://stackoverflow.com/a/26252014/648955) (example for Map, but applies to Set and List as well). I expect using this pattern will lead to more GC, if AST is updated actively, but much lesser memory consumption, that any usage of Collections from `java.util`

**Comment by monperrus** [comment]
On performance, remember that there is only on instance shared between all  AST nodes.

**Comment by monperrus** [comment]
> you can add a wrapping method like.
> static void clear(List<?> l) {
>  if (l == emptyList()) return;
>  l.clear();
>}

Good idea. Pull request welcome.

**Comment by leventov** [comment]
@monperrus 

> On performance, remember that there is only on instance shared between all AST nodes.

I understand, I mean after inserting *first* member/param/field/etc, currently too much memory is allocated.

> Pull request welcome.

Ok, I will probably PR something in some time.

**Comment by leventov** [comment]
See #244

**Comment by GerardPaligot** [comment]
This PR should be closed. ping @monperrus
