### ISSUE TITLE
Is A2.java file valid?

### ISSUE THREAD

**Issue by zielint0** [INRIA/spoon#2363]
@surli 
Is it intended to have an extra (not paired) brace (curly bracket) in last line in file A2.java?
spoon\src\test\resources\noclasspath\A2.java

Checkstyle spits exception on it because it is invalid syntax.
https://github.com/checkstyle/checkstyle/issues/6065

```
public class A2 {

	int field;

	public void b(int param) {
		IntUnaryOperator f1 = x -> x;
		IntBinaryOperator f2 = (a, b) -> a + b;
		try {
			System.out.println(f1.applyAsInt(f2.applyAsInt(field, param)));
		} catch (RuntimeException e) {
			throw e;
		}
	}

	public void c(int param) {
		c(param);
	}
}
} // THIS IS REDUNDANT (extra brace)
```

The comment `// THIS IS REDUNDANT (extra brace)` is added by me.

**Comment by zielint0** [comment]
I also reported 2 Spoon files that crash Checkstyle:
- https://github.com/checkstyle/checkstyle/issues/6066
- https://github.com/checkstyle/checkstyle/issues/6064

**Comment by surli** [comment]
Have you found where this file is used in the tests?

**Comment by zielint0** [comment]
spoon\src\test\java\spoon\reflect\ast\CloneTest.java
->testCopyMethod()
`l.addInputResource("./src/test/resources/noclasspath/A2.java");`

**Comment by zielint0** [comment]
@monperrus 
Yes, next day or two.

**Comment by zielint0** [comment]
@monperrus 
@surli 
I removed it here: refactor: remove redundant '}' from resource file A2.java #2412 
Is A2.java resource needed?
