### ISSUE TITLE
Auto-imports of java.lang classes fail to use qualified names if class of same name is defined in file.

### ISSUE THREAD

**Issue by Vetii** [INRIA/spoon#2369]
Hello,

If I try to run an Launcher (with auto imports) on the following java code:

~~~
package TestJava;

public class JavaLongUse {

    public class Long {

    }

    public static long method() {
        return java.lang.Long.parseLong("10000");
    }

    public static void main(String[] args) {
        System.out.println(method());
    }
}
~~~

I get the following output:

~~~
package TestJava;


public class JavaLongUse {
    public static class Long {}

    public static long method() {
        return Long.parseLong("10000");
    }

    public static void main(String[] args) {
        System.out.println(JavaLongUse.method());
    }
}
~~~

Which leads to the compilation error "The method parseLong(String) is undefined for the type JavaLongUse.Long", because "java.lang.Long" disappears in the output file, and "Long" now refers to the JavaLongUse.Long class.

Is there a way to force qualified names in specific places?

**Comment by surli** [comment]
Thanks for reporting this bug! I'll investigate on it.

> Is there a way to force qualified names in specific places?

No Spoon only supports auto-imports mode for the whole model. So you can only switch it off globally.
