### ISSUE TITLE
How to: access annotations declared on an annotation?

### ISSUE THREAD

**Issue by dsyer** [INRIA/spoon#2370]
I can access annotations on a type in a `AbstractProcessor<CtClass<?>>` using `element.getAnnotations()`. Each of those is a `CtAnnotation<?>` which has an `annotationType` property. Neither the `CtAnnotation<?>` nor the `annotationType` seems to ever have any annotations itself, despite the underlying annotation having them (and being retained at runtime). I can see them with the normal `java.lang.reflect` methods `getDeclaredAnnotations()`, but nothing in the Spoon model seems to have that data.

**Comment by surli** [comment]
Hi @dsyer 

do you mean getting the annotations in the declaration of the annotation currently used, such as: 

```java
@Retention(value = RetentionPolicy.RUNTIME)
public @interface Foo {
}

@Foo // once you get this annotation you also want to get it's @Retention annotation
public class MyClass {}
```

If you want to access this kind of information, you need to retrieve the declaration of the annotation and its own annotation.
If I misunderstood could you provide an example illustrating what you want to do? Thanks.

**Comment by dsyer** [comment]
It's more likely to be

```java
@Bar
@Retention(value = RetentionPolicy.RUNTIME)
public @interface Foo {
}
```

and I want to find the `@Bar`. I can do it with `ctAnnotation.getAnnotationType().getActualClass().getDeclaredAnnotations()` but that `getActualClass()` method is deprecated, and I don't see another way to get that data.

**Comment by surli** [comment]
OK but we're clear that in that case `@Bar` is attached to the annotation class `Foo` right?

So if you get `Foo` because it's used in a case like: 
```java
@Foo
public class Baz {}
```

and you got access to `Baz` with your processor.
Let's say you've got a `CtClass classBaz` which points to it.
Then you should be able to do something like that:

```java
CtAnnotation fooAnnotation = classBaz.getAnnotations().get(0); 
CtType fooDeclaration = fooAnnotation.getAnnotationType().getDeclaration();
CtAnnotation barAnnotation = fooDeclaration.getAnnotations().get(0);
```

I did not test, but I think it should work. Let me know.
