### ISSUE TITLE
automated snapshot deployment for the master branch

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#238]
when a PR is accepted in master, a snapshot should automatically be deployed

**Comment by GerardPaligot** [comment]
Our snapshot server accepts only authentication with ssk keys. So, before this issue, we must push a ssh key valid with our snapshot server to this project GitHub according to this [article in the Travis documentation](http://docs.travis-ci.com/user/private-dependencies/).

**Comment by GerardPaligot** [comment]
We installed a Jenkins which deploys a snapshot version for the master branch every night. This issue can be closed.

**Comment by monperrus** [comment]
Coo! Thanks.
