### ISSUE TITLE
[BUG]: "this" becomes "super" after Spoon analysis

### ISSUE THREAD

**Issue by justinwm** [INRIA/spoon#2381]
I have encountered an strange bug when using Spoon, either with version 6.2 or 7.0

The source code I am analyzing is https://github.com/apache/commons-math/blob/master/src/main/java/org/apache/commons/math4/linear/ArrayRealVector.java

After building the model using the following code on the above source file:

`Launcher launcher = new Launcher();`
`launcher.addInputResource(targetClassLocation);`
`launcher.setSourceOutputDirectory(location + File.separator + "spoon");`
`launcher.getEnvironment().setSourceClasspath(classPath.split("::"));`
`launcher.buildModel();`
`List<CtElement> originalClasses = launcher.getFactory().Package().getRootPackage()
							.getElements(new TypeFilter(CtClass.class));`
`WriteLinesToFile.writeToFiles(originalClasses.get(0).toString(), "ArrayRealVector.java");`

The output file "ArrayRealVector.java" is different with the original source file "ArrayRealVector.java".
The key work `this` becomes `super`.

Original:
<img width="676" alt="image" src="https://user-images.githubusercontent.com/2504533/44250265-4121ef00-a226-11e8-9d35-df1a65324868.png">

Analyzed:

<img width="741" alt="image" src="https://user-images.githubusercontent.com/2504533/44250287-526afb80-a226-11e8-9498-4b33e67bc36d.png">

I do not know how this would happen, which seems to be a serious bug.

**Comment by pvojtechovsky** [comment]
Hi @justinwm I tried to reproduced this problem in #2680, but it works well for me. I cannot reproduce it. Is it still reproducible? Could you make a PR with failing test case?
