### ISSUE TITLE
What's the state of Spoon's incremental build?

### ISSUE THREAD

**Issue by msteinbeck** [INRIA/spoon#2382]
Our research group recently published the Java library [LibVCS4j](https://github.com/uni-bremen-agst/libvcs4j). The library is supposed to analyze the evolution of software systems by examining their version control systems. I would like to bridge LibVCS4j and Spoon's incremental build launcher in order to provider another library that allows static analysis tools to process a spoon model for each revision of, for instance, a Git repository. Thus, I would like to know if the incremental launcher is ready for productive use or if some changes/bug fixes are necessary.

**Comment by mehdi-kaytoue** [comment]
I do have the same need : I'd like to build the model from a given git commit.
Then, after pulling some changes from git, e.g. 2 modified java files, 3 added and 2 removed, I would like to adapt my ct_model quickly without rebuilding it from scratch. 
From what I understood, it's the same @msteinbeck ?
What I understood at the time of #1905, is that it could consider only new files.
Happy to dig it again!

**Comment by monperrus** [comment]
I wanted to add LibVCS4j to https://en.wikipedia.org/wiki/Mining_software_repositories but it's already there :-)

**Comment by msteinbeck** [comment]
Yes I added LibVCS4j some time ago :). Our incremental model updater is almost finished. We adapted your tests from [IncrementalLauncherTest](https://github.com/INRIA/spoon/blob/master/src/test/java/spoon/test/model/IncrementalLauncherTest.java). Even though they are not too extensive, yet they are very helpful to have some ground truth data. We will try to add more extensive tests in the future.

The incremental model updater will be provided as a separate Maven module. That is, it depends only on LibVCS4j's API and Spoon. The module will not only contain an incremental model updater, but also provide basic infrastructure for gathering different metrics and detecting Code Smells. However, due to Spoon's awesomeness, it is not limited to metrics and Code Smells :P.  Once it is published, you may add it to your lists of tools using Spoon.
