### ISSUE TITLE
Provide full control for spoon-gradle-plugin

### ISSUE THREAD

**Issue by treenwang** [INRIA/spoon#2388]
We are using spoon-gradle-plugin to generate java source code recently. 
We want to control the output by setting the parameters like "--with-imports", "--encoding", etc, which described in http://spoon.gforge.inria.fr/command_line.html.
But spoon-gradle-plugin doesn't provide a way to make this happen. Could you please add this feature?  I think it just need to add String[] to the plugin as an extra parameter besides current project parameters in https://github.com/SpoonLabs/spoon-gradle-plugin/blob/master/src/main/groovy/fr/inria/gforge/spoon/SpoonPlugin.groovy

**Comment by surli** [comment]
Hi @treenwang 

we'll look on adding this feature.
In the meantime, FYI this feature is already supported in the spoon-maven-plugin if you can use it instead the spoon-gradle-plugin.

**Comment by treenwang** [comment]
Thanks! My project use gradle. It looks hard to use maven plugin. I tried another way which initialize Launcher directly for now. I can wait for a new release.

**Comment by treenwang** [comment]
Closed this ticket since we can use other ways.
