### ISSUE TITLE
Is there are any settings to retain import statements?

### ISSUE THREAD

**Issue by tempuser1909** [INRIA/spoon#2397]
Hi,

Can I ask how do I add import statement?

Or how do I ensure that the original import statements remain intact?

I only know about setAutoImports() but it does not seem help in my use case.

Thank you.

**Comment by surli** [comment]
Hi @tempuser1909 

> Can I ask how do I add import statement?

There is no easy API to do that for now: I'm working on the whole import mechanism for Spoon but it's still a work in progress. In the meantime I provided in this message some insight to add an import statement manually: https://github.com/INRIA/spoon/issues/1267#issuecomment-347125893

> Or how do I ensure that the original import statements remain intact?

The original import statements *should* remain intact: in fact, they might change depending on the transformation you make in your code (e.g. if you add a new field with an external type for example). 
Besides that, our strategy is to keep the original imports.

> I only know about setAutoImports() but it does not seem help in my use case.

Could you elaborate more about your usecase then?

**Comment by tempuser1909** [comment]
Hi @surli,

An example of my use case is

Original source
``
public class A{
}
``

Then it is supposed to insert Object/Class References which will require new import statement.
``
public class A{
    Scanner scan = new Scanner();
}
``


Only another note, I noticed that for me when i do prettyprint() with setAutoImports(false), it does not generate any import statements.

And when I do prettyprint() with setAutoImports(true), it does generate some import statements but it is not the original import statements. Because I am testing on an example Java file, I was thinking if unused imports will be deleted. Can I ask if that is true?

Thank you.

**Comment by tempuser1909** [comment]
Not sure if it will help anyone but I will put the class I wrote that inserts import statements easier.

[ImportWriter.java](https://gist.github.com/tempuser1909/0ffa6d86fb6791216700f9ebb1363e1f)

**Comment by monperrus** [comment]
Thanks @tempuser1909 how do you use this code together with Spoon?

**Comment by tempuser1909** [comment]
Hi @monperrus, I have added Main.java in the gist to show an example of how I used it with Spoon.

The idea is to get the files you want from Spoon's CtModel and add the defined import statements.

However, there could be some improvements done on it.

**Comment by monperrus** [comment]
Interesting, thanks. Why do you need to rewrite the imports since the code is written in fully-qualified mode (`setAutoImports(false)`)?

**Comment by tempuser1909** [comment]
It is because I do not want to disturb the existing code as much as possible. I only wanted to have access to all the elements via an API and modify what I need to modify. The code that I working with has been written to be as readable as possible. So with fully-qualified identifiers, I think it will make the code less readable.

Also, I have to add that I wrote that class during my phase of seeing what Spoon can do, so I only used `setAutoImports(false)`. And only recently when I have been testing with complete code that I have used `setAutoImports(true)` which works fine (but I still wanted to retain the imports from the original source, it is just part of my criteria).

**Comment by monperrus** [comment]
> I still wanted to retain the imports from the original source

Why?

**Comment by pvojtechovsky** [comment]
Spoon actually doesn't support forcing of printing of import if the import is not used.

Workaround: Add javadoc which contains links to all by default imported types. That forces spoon to keep the import there even if it is not used in java code.

Real solution would need a change in ImportScannerImpl#usedImport Map values has to be set to TRUE.

I have found no way how to do it without changing Spoon code, because all fields are private.
