### ISSUE TITLE
add CtReference.getParent() and replace()

### ISSUE THREAD

**Issue by leventov** [INRIA/spoon#240]
Why there are no methods like `CtReference. getParent()` and `replace()`. I can change all reference's fields, during scanning, but cannot change the reference class.

I stuck with implementing "generic specialization" properly, where I need to replace all CtTypeParameterReferences with CtTypeReferences.

**Comment by monperrus** [comment]
renamed issue as "add CtReference.getParent() and CtReference.replace()"

I like the idea.

**Comment by GerardPaligot** [comment]
What is expected when we call `getParent()` on a `CtReference`?

**Comment by leventov** [comment]
@GerardPaligot the same when we call `getParent()` on `CtElement` -- parental AST element that holds this reference

**Comment by GerardPaligot** [comment]
If our reference is an element in our source directory, we can get its parent thanks to `ref.getDeclaration().getParent()` but when the reference come from a dependency, we don't have any information to know what is its parent.

**Comment by leventov** [comment]
@GerardPaligot right, currently we cannot, so need to add `parent` field to `CtReferenceImpl` (just like in `CtElementImpl`) and update it properly.

**Comment by leventov** [comment]
I don't need this now (I have written workarounds once and they work), but it doesn't seem coherent to be able to manipulate with CtElement as AST element, but not Reference. The difference is that CtReference could only be a leaf, but `getParent()` and `replace()` make perfect sense for leafs

**Comment by JakeWharton** [comment]
I'm looking for something like this now as well. Basically an easy way to automate remapping of references to one class with another.
