### ISSUE TITLE
Discussion: Meaning of CtTypeParameterReference#upper and #bounds

### ISSUE THREAD

**Issue by pvojtechovsky** [INRIA/spoon#2401]
I am thinking about solution of #2161 and it looks like Spoon model is not fitting to java specification concerning some attributes of CtTypeParameterReference.

There are these problems
> P1 `CtTypeParameterReference#upper` makes sense only for `CtWildcardReferenceImpl`. 

The attribute `upper` of pure `CtTypeParameterReference` makes no sense or it should be unsettable and should always return true.

> P2 `CtTypeParameterReference#superType` should be settable only for `CtWildcardReferenceImpl`.

The attribute `superType` should be derived for `CtTypeParameterReferenceImpl`, because it can be always computed from `CtTypeParameter#superClass`.
The attribute `superType` should be settable (not derived) for `CtWildcardReferenceImpl` only.

WDYT?

**Comment by pvojtechovsky** [comment]
It seems to me that the most clean solution would be 
1) to replace
`CtWildcardReference extends CtTypeParameterReference`
by
`CtWildcardReference extends CtTypeReference`

2) to remove CtTypeParameterReference methods `isUpper`, 'setUpper`, `setBounds`, `addBound`, `removeBound`, 'setBoundingType', because they are completely useless - they mirrors no java language feature, because type parameter reference has no bounds and no upper.

3) may be we can keep `CtTypeParameterReference#getBoundingType`, but it should be derived with implementation `getDeclaration().getSuperclass()` ... it would be also more clear if `CtTypeParameterReference#getSuperclass()` would return `getDeclaration().getSuperclass()` too

4) to add CtWildcardReference methods: `isUpper`, 'setUpper`, `getBoundingType`, `setBoundingType`. Note: `add/removeBound` or `setBounds` makes no sense here too, because wildcard reference doesn't support multiple bounds.

WDYT? 
Will you accept such deep changes in Spoon model? ... I guess they are needed, because otherwise the API is confusing with useless methods, whose calling has no influence to printed java source or causes not compilable sources.

I am still searching for a reason which explains why that "confusing" design is needed ... do you have any idea?

**Comment by monperrus** [comment]
> I am still searching for a reason which explains why that "confusing" design is needed ... do you have any idea?

AFAIK, because CtTypeParameter has been in and out over time.

> Will you accept such deep changes in Spoon model?

In principle yes, unless we realize during the refactoring that we're confused once more :-)

**Comment by pvojtechovsky** [comment]
> I am still searching for a reason which explains why that "confusing" design is needed ... 

The reason is visible in failing tests of #2406. E.g. on the test sources like
```java
public class Cloud<T extends String> {

	<U extends InputStream> void method(T param, U param2) {}
	<U extends Reader> void method(T param, U param2) {}
	<U extends List<? extends InputStream>> void method(T param,  U param2) {}
}
```
where `CtMethod m` which points to `<U extends Reader> void method(T param, U param2) {}` has problem to create correct reference using `m.getReference()`. Such method reference has no information about bounds of origin method parameter types.

So it looks like the only reason why CtTypeParameterReference needs bounds is algorithm of `CtTypeImpl#getMethod(String name, CtTypeReference<?>... parameterTypes)`
... and may be similar algorithms...

**Comment by pvojtechovsky** [comment]
The results of this discussion were used in #2406. So I am closing this issue.
