### ISSUE TITLE
get inherited classes

### ISSUE THREAD

**Issue by JackLehman** [INRIA/spoon#2407]
Is it possible to get all sub classes from one specific Java class or an interface? There is the getsuperclass method in the spoon api but I was wondering if there's a method to identify all subclasses. 
Thanks

**Comment by pvojtechovsky** [comment]
Yes, have a look at SubInheritanceHierarchyFunction and the test MethodsRefactoringTest#testSubInheritanceHierarchyFunction, which shows how to use it.

Do you have an idea where to put such functions to allow new clients like you to found them? Where did you searched?

**Comment by JackLehman** [comment]
Thanks it works. I want to evaluate the quality of subclasses. So first I need to extract them and then evaluate some metrics related to software quality like how are sub methods are implemented and so on.

Btw, I have another question, if I want to analyze several projects I will have a factory per maven project. like `Factory factory = launcher1.getFactory();`

How is it possible to have one single factory object that contains all CtClasses of all projects?
I was looking for something like this `factory.add(launcher2.getFactory())`
