### ISSUE TITLE
bug: serious warning in EnumFactory ("Inconvertible types")

### ISSUE THREAD

**Issue by zielint0** [INRIA/spoon#2408]
Line `return (CtEnum<?>) super.get(qualifiedName);` gaves warning: *Inconvertible types; cannot cast 'spoon.reflect.declaration.CtType<java.lang.Object>' to 'spoon.reflect.declaration.CtEnum<?>'*

Is it something to analyze and fix?

spoon/reflect/factory/EnumFactory.java
```
	@Override
	@SuppressWarnings("unchecked")
	public CtEnum<?> get(String qualifiedName) {
		try {
			return (CtEnum<?>) super.get(qualifiedName);
		} catch (Exception e) {
			return null;
		}
	}
```

**Comment by monperrus** [comment]
What about `return (CtEnum) super.get(qualifiedName);`?

**Comment by monperrus** [comment]
@zielint0 do you plan to create the corresponding PR?

**Comment by zielint0** [comment]
@monperrus 
I plan to investigate it this week. Then PR or close.

**Comment by monperrus** [comment]
ping?

**Comment by zielint0** [comment]
Packet lifetime exceeded.
