### ISSUE TITLE
how to add developers with no Inria affiliation as administrator of Spoon's Jenkins CI  ?

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#2418]
It seems that https://ci.inria.fr/ accepts external contributors.

@pvojtechovsky could you try to create an account there?

**Comment by pvojtechovsky** [comment]
I was able to create account and login there. I was able to join the projects
* Spoon Open Source project
* Pull Request Tester Spoon

But I have no idea how to access any details of these projects.

... I also have to learn French ... but that will need some time :-)))

**Comment by surli** [comment]
I just granted you access and give you admin rights to the Spoon Open Source Project. So now you should be able to administrate our Jenkins jobs if needed :-)
You should be able to log in there: https://ci.inria.fr/sos/

**Comment by pvojtechovsky** [comment]
ok, I can login to Jenkins. I have seen that tool already, but only as a client who starts a job. I am not trained in that area... but may be it will be helpful in future. I do not know yet... Anyway thanks for confidence ;-)

**Comment by monperrus** [comment]
Excellent news. Closing the issue for now.
