### ISSUE TITLE
How can we get all the constructors of any class or package (not default constructor)?

### ISSUE THREAD

**Issue by mashalahmad** [INRIA/spoon#2440]
How can we get all the constructors of any class or package (not default constructor)?

thanks

**Comment by pvojtechovsky** [comment]
See `CtClass#getConstructors()`
or you can use something like `package.filterChildren(new TypeFilter(CtConstructor.class))`

**Comment by pvojtechovsky** [comment]
`constructor.isImplicit()==false`

**Comment by mashalahmad** [comment]
is there any way to search the AST in  depth-first order??

**Comment by monperrus** [comment]
method CtElement#getChildren and #iterator traverse the AST in depth-first order.

**Comment by mashalahmad** [comment]
is there any way to configure the service of spoon?

**Comment by monperrus** [comment]
What do you want to configure exactly?

**Comment by mashalahmad** [comment]
actually im working on a project where another parser(recorder http://recoder.sourceforge.net/doc/api/index.html?recoder/java/declaration/package-summary.html) service is configured like this


import recoder.service.CrossReferenceSourceInfo;
import recoder.ServiceConfiguration;

  protected ServiceConfiguration xconfig;
    protected CrossReferenceSourceInfo si;
    
    /**
     * @param serviceConfiguration configuration
     * @param si source info
     * 
     */
    public MetricsUtility(ServiceConfiguration serviceConfiguration, CrossReferenceSourceInfo si) {
        super();
        this.si = si;
        this.xconfig = serviceConfiguration;
    }

can something like this be done with spoon?

**Comment by monperrus** [comment]
The concept of "Service" is specific to Recoder.

In Spoon, most of the configuration is done in the `Environment` class.

**Comment by mashalahmad** [comment]
hi could you please tell me how could I do the same with spoon?

 protected CrossReferenceSourceInfo si;

protected List<Field> getAllFields(ClassDeclaration cd) {
    
        List<Field> FieldList = new ArrayList<Field>();
        for (Field field : si.getAllFields(cd)) 
            if (field.getContainingClassType() instanceof ClassDeclaration)
                FieldList.add(field);
        
        return FieldList;
    }

protected Set<Field> getAttributeReferences(Method method){
        
            Set<Field> attributeReferencelist = new HashSet<Field>();
            
            List<Field> allFields = getAllFields((ClassDeclaration)si.getContainingClassType(method));
            
            TreeWalker walker = new TreeWalker(((MethodDeclaration)method).getBody());
            while (walker.next()){
                ProgramElement pe = walker.getProgramElement();
                if (pe instanceof FieldReference){
                    Field field = si.getField((FieldReference)pe);
                    ClassType ct = si.getContainingClassType(field);
                    if (((ct instanceof ClassDeclaration)||(ct instanceof InterfaceDeclaration))
                        &&(allFields.contains(field)))/**field is known in class*/
                            attributeReferencelist.add(field);/**Add field to FieldSet*/
                }
            }
            
            return attributeReferencelist;
        }

**Comment by pvojtechovsky** [comment]
Hi, This method should do the same like your `getAttributeReferences`
```java
List<CtFieldReference<?>> getAttributeReferences(CtMethod method){
	//get the type which declares method
	CtType declaringType = method.getDeclaringType();
	return method
		//visit AST of the method and pass all the nodes of type CtFieldReference to the next query step
		.filterChildren(new TypeFilter<>(CtFieldReference.class))
		//select all the field references whose field belongs to the declaringType
		.select((CtFieldReference fieldRef)->fieldRef.getDeclaration().getDeclaringType() == declaringType)
		//collect all results into List
		.list();
}
```

**Comment by mashalahmad** [comment]
and could you please tell me about this one too as its  getting the field after some service configuration.
specially this si.getAllFields(cd)
 CrossReferenceSourceInfo  is actually serivce setup of coder [http://recoder.sourceforge.net/doc/api/index.html?recoder/java/declaration/package-summary.html](Link (recorder.service))

really appreciate your help :)
protected CrossReferenceSourceInfo si;

protected List getAllFields(ClassDeclaration cd) {

    List<Field> FieldList = new ArrayList<Field>();
    for (Field field : si.getAllFields(cd)) 
        if (field.getContainingClassType() instanceof ClassDeclaration)
            FieldList.add(field);
    
    return FieldList;
}

**Comment by pvojtechovsky** [comment]
See existing spoon model methods
* CtClass#getFields()
* CtClass#getAllFields()

You can get overview about Spoon model here http://spoon.gforge.inria.fr/structural_elements.html 
And then have a look at javadoc of Spoon model interfaces. Each method has good documentation.

Your questions are welcome here, but looking at javadoc might give you answers faster ;-)

We try to make Spoon model intuitive and well documented.

**Comment by mashalahmad** [comment]
Thanks alot @pvojtechovsky  I am reading the javadoc too and even reading you papers too but sometime its so difficult to understand something.
 could you please tell how I can check the consistency and admissibility of a construct, e.g. cardinality of participants like Model element of recorder? :)

**Comment by pvojtechovsky** [comment]
> how I can check the consistency and admissibility of a construct, e.g. cardinality of participants like Model element of recorder?

I do not understand your question. I do not know the concepts of recorder. So try to ask e.g. by describing your needs, instead referencing to how record is doing that ;-)

**Comment by pvojtechovsky** [comment]
> e.g. cardinality of participants

Spoon model has List or Set on places where multiple values are allowed. And single value property when one value is expected.

> how I can check the consistency and admissibility of a construct

You can print modified or generated AST into java sources and compile them. If compiler has no problem then origin spoon model is consistent ;-)

**Comment by mashalahmad** [comment]
Hi

Im trying to get the constructor on a declaring type like this

private CtType<?> astNode = null;
for (CtConstructor<?> constructor : astNode.getClass().getConstructors()) {
            if (!(constructor.isImplicit()))
       addChild(new ConstructorMetrics(this.specifiedMetrics, this,constructor)
}
but im getting error on astNode.getClass().getConstructors()) it first ask to change the constructor to java.lang.reflect.Constructor<?> but I need to check whether its implicit or not. How can I do this?

**Comment by pvojtechovsky** [comment]
private CtType astNode = ...; 
if (!(astNode.isImplicit()))
In Spoon you never need to access Java runtime class like Class, Method, Field. Everything is available in Spoon mirror classes like CtClass, CtMethod, CtField, ...

**Comment by mashalahmad** [comment]
but description of CtClass #getconstructors() says 

Set<CtConstructor<T>> getConstructors()
Returns the constructors of this class. This includes the default constructor if this class has no constructors explicitly declared. Derived from CtType.getTypeMembers()
so even the ctype is not implicit (if (!(astNode.isImplicit()))) it still return the default constructor . 

plus how to change the return type of astNode.getClass().getConstructors() to CtConstructor not Constrcutor<?>

**Comment by mashalahmad** [comment]
Thanks alot you are really greatt!!!@pvojtechovsky  can you tell how can I traverse depth first search wise like this forest walker?

protected void initializeChildren() {
        classesPerLayer = new HashMap<String, List<CtClass<?>>>();
        classes = new ArrayList<CtClass<?>>();      
        AbstractTreeWalker tw = new ForestWalker(astNodes);
        while (tw.next()) {
            ProgramElement pe = tw.getProgramElement();
            if (pe instanceof CtClass<?>) {
            	CtClass<?> cd = (CtClass<?>) pe;
                /** Don't count anonymous class */
                if (!cd.isAnonymous()) {
                    addChild(new TypeMetrics(this.specifiedMetrics, this, cd));
                    classes.add(cd);
                }
            }
        }
        Iterator<String> keys = classesPerLayer.keySet().iterator();
        while (keys.hasNext()) {
            String key = keys.next();
            Layer layer = new Layer(this.specifiedMetrics, this,classesPerLayer.get(key));
            layer.setName(key);
            addChild(layer);
            totalNumberOfClassesInLayers += classesPerLayer.get(key).size();
        }
    }

**Comment by pvojtechovsky** [comment]
I do not know if it is "depth first", but in spoon we are using `filterChildren`
http://spoon.gforge.inria.fr/filter.html

**Comment by mashalahmad** [comment]
Hi

I tried to get list of classes that are not Anonymous I implement it like this but im getting error on filterchildern

 classes = new ArrayList<CtClass<?>>();  
        CtType<?> declaringType = ((CtTypeMember) classes).getDeclaringType();
    	return classes
    		
    		.filterChildren(new TypeFilter<>(CtAssignment.class))
    		.select((CtClass<?> cd)->cd.isAnonymous==false&& cd instanceof declaringType )
    		.list();

**Comment by pvojtechovsky** [comment]
This might work
`.filterChildren((CtClass<?> cd)->cd.isAnonymous==false && cd instanceof declaringType).list();`

What do you expect here?
```
classes = new ArrayList<CtClass>();
//List of CtClass cannot be type cast to CtTypeMember. No magic allows that
CtType declaringType = ((CtTypeMember) classes).getDeclaringType();
```
I do not understand

**Comment by mashalahmad** [comment]
I want to traverse each compilation unit (in dfs fashion) of AST and check if node is class and is not anonymous 
private List<CompilationUnit> units;
        classes = new ArrayList<CtClass<?>>();  
    	 classes =	.filterChildren((CtClass<?> cd)->cd.isAnonymous==false && cd instanceof declaringType).list();

still getting error on .filterchildern

**Comment by pvojtechovsky** [comment]
> still getting error on .filterchildern

... because java compiler doesn't understand that. `filterChildren` is a method of a AST node element. This is a way how to filter all AST nodes of spoon model (all loaded compilation units and types)

```java
Factory factory = ...
List<CtClass> nonAnonymousClasses = factory.getModel()
   .filterChildren((CtClass cd)->!cd.isAnonymous())
   .list();
```

**Comment by mashalahmad** [comment]
Im trying to do a similar implementation to this function

  protected void initializeChildren() {
        
        classes = new ArrayList<ClassDeclaration>();
		transient private List<CompilationUnit> astNodes = null;
		
        AbstractTreeWalker tw = new ForestWalker(astNodes);
        while (tw.next()) {
            ProgramElement pe = tw.getProgramElement();
            if (pe instanceof ClassDeclaration) {
                ClassDeclaration cd = (ClassDeclaration) pe;
                /** Don't count anonymous class */
                if (!Utility.isAnonymous(cd)) {
                    addChild(new TypeMetrics(this.specifiedMetrics, this, cd));
                    classes.add(cd);
                }
            }
        }
    }

where compilation unit are traversed dfs with Abstract Tree walker and if node is a class and not anonymous then list of classes is acquired and each class id passed to a function addcChild.
according to spoon I did it like this but im getting error on cd now. how we can call a function while fitering out the nodes as classes?

protected void initializeChildren() {
					
					classes = new ArrayList<ClassDeclaration>();
					transient private List<CompilationUnit> astNodes = null;
        			Factory factory = (Factory) astNodes;
        	        classes = factory.getModel()
        		   .filterChildren((CtClass<?> cd)->!cd.isAnonymous())       		   
        		   .list();
        	        addChild(new TypeMetrics(this.specifiedMetrics, this, cd));
        	        	
       
    }

**Comment by monperrus** [comment]
> how we can call a function while fitering out the nodes as classes?

There is a method forEach after a call to filter.

    aMethod.filterChildren(new TypeFilter<>(CtLocalVariable.class)).forEach( ... )

**Comment by mashalahmad** [comment]
hey thanks

why im getting null values here

List<CtFieldReference<?>> getAttributeReferences(CtMethod method){
	//get the type which declares method
	CtType declaringType = method.getDeclaringType();
	return method
		//visit AST of the method and pass all the nodes of type CtFieldReference to the next query step
		.filterChildren(new TypeFilter<>(CtFieldReference.class))
		//select all the field references whose field belongs to the declaringType
		.select((CtFieldReference fieldRef)->fieldRef.getDeclaration().getDeclaringType() == declaringType)
		//collect all results into List
		.list();
}

specially here fieldRef.getDeclaration().getDeclaringType(). I just want to see the type of referncefied is same as that of method.

**Comment by pvojtechovsky** [comment]
Check the meaning of
* getDeclaringType
* getTypeDeclaration

and then use getTypeDeclaration instead of getTypeDeclaration

**Comment by mashalahmad** [comment]
Well I checked it with simple getTypeDeclaration too but its the same :( null all the time.

**Comment by pvojtechovsky** [comment]
CtTypeReferenceImpl#getTypeDeclaration returns null only if you spoon is in no-class path mode and the sources of the target class are not available in spoon model. So check how do you launch the spoon

**Comment by mashalahmad** [comment]
hey thanks alot will check this one 👍
