### ISSUE TITLE
Building AST for guava (JDT issue) -> action: try with latest version

### ISSUE THREAD

**Issue by leventov** [INRIA/spoon#245]
JDT guys say this is not their bug, maybe you think this this is yours? :)

https://bugs.eclipse.org/bugs/show_bug.cgi?id=468119

**Comment by monperrus** [comment]
Can you write a test case reproducing the bug?

Thanks, --Martin

**Comment by leventov** [comment]
It requires to check in the whole guava source into spoon project.
Try to do the following:
`git clone git@github.com:google/guava.git`

Then run
```
public class GuavaTest {
    
    @Test
    public void buildGuavaAst() {
        Launcher spoon = new Launcher();
        SpoonCompiler comp = spoon.createCompiler();
        try {
            comp.addInputSources(SpoonResourceHelper.resources(
                    "/path/to/guava/guava/src/"));
            spoon.getEnvironment().setNoClasspath(true);
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }
        comp.build();
    }
}
```

**Comment by GerardPaligot** [comment]
Well, yes. There is a problem from Spoon because we don't handle `CaptureBinding18` ("18" seriously?) in `getTypeReference` but when we handle it, JDT throws errors.

With this sample:

```java
private static <K> ATacos<K> make(Map<K, ?> map) {
	return makeIt((EnumMap) map);
}

private static <K extends Enum<K>> ATacos<K> makeIt(EnumMap<K, ?> original) {
	return null;
}
```

(This code is the same than the code in Guava)

When you try to just compile it with JDT, you got 1 error and 1 warning:

```console
----------
1. ERROR in /Users/gerard/Documents/workspace/spoon/src/test/java/spoon/test/visibility/testclasses/Tacos.java (at line 22)
	return copyOfEnumMap((EnumMap) map);
	       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Type mismatch: cannot convert from Tacos.ATacos<Enum<Enum<K>>> to Tacos.ATacos<K>
----------
2. WARNING in /Users/gerard/Documents/workspace/spoon/src/test/java/spoon/test/visibility/testclasses/Tacos.java (at line 22)
	return copyOfEnumMap((EnumMap) map);
	                      ^^^^^^^
EnumMap is a raw type. References to generic type EnumMap<K,V> should be parameterized
----------
2 problems (1 error, 1 warning)
```

So we cannot compile the original source code before the building of the AST.

My test case is:

```java
@Test
public void testCompileCaptureBinding18() throws Exception {
	final StandardEnvironment environment = new StandardEnvironment();
	environment.setComplianceLevel(8);
	Factory factory = new FactoryImpl(new DefaultCoreFactory(), environment);
	JDTBasedSpoonCompiler compiler = new JDTBasedSpoonCompiler(factory);
	compiler.addInputSource(new File("./src/test/java/spoon/test/visibility/testclasses/Tacos.java"));
	compiler.compile();
}
```

**Comment by leventov** [comment]
As I written in JDT issue, I've also tried to build a small reproducable example, exactly copying the source from Guava, but it behaves differently.

**Comment by GerardPaligot** [comment]
There are two bugs. The first one is the infinite loop that you exposed in your JDT issue and was a bug from Spoon. And a second one with compilation errors from JDT like I exposed in my previous post. This last error isn't from Spoon but well in JDT.

**Comment by GerardPaligot** [comment]
New issue created on JDT: https://bugs.eclipse.org/bugs/show_bug.cgi?id=469404

**Comment by GerardPaligot** [comment]
Guava have fixed the bug I have reported on their bugtracker (https://github.com/google/guava/issues/2082) which concerns this issue.

Unfortunately, I found a new bug from JDT. I created a new issue here: https://bugs.eclipse.org/bugs/show_bug.cgi?id=470817

**Comment by GerardPaligot** [comment]
yay! \o/
