### ISSUE TITLE
FieldRefernce type matching with type of class

### ISSUE THREAD

**Issue by mashalahmad** [INRIA/spoon#2464]
Hi
Im matching the type of referncefields to type of class but why im getting null when i want to get the type of class why is that?

List<CtFieldReference<?>> fieldrefs = getAttributeReferences(method);
    		for (CtFieldReference<?> field : fieldrefs) {
    			if (field.getDeclaringType()==cd.getDeclaringType()) {
    				ImplementAttributeReferences.add((CtField<?>) field);}
    			     else {System.out.println("notfound");
                          }

**Comment by mashalahmad** [comment]
Hey 

So whats the way to do the matching like this??? I want to see the type of reference field is same as class and not any default (e.g. system )class

**Comment by mashalahmad** [comment]
okay I solved the previous issue. could you please tell how can I solve the typecaste(cannot cast from Typereference to field declaration)  error at line 5. I want to get a set of CtField type.


1     Set<CtField<?>> ImplementAttributeReferences = new HashSet<CtField<?>>();
2   		List<CtFieldReference<?>> fieldrefs = getAttributeReferences(method);
3  		  for (CtFieldReference<?> field : fieldrefs) 
4    			if (field.getDeclaringType().toString().equals(cd.getQualifiedName())) 
5    				ImplementAttributeReferences.add((CtField<?>) field);
 6   			     // else System.out.println("notfound");
 7   		System.out.println(ImplementAttributeReferences);
 8   		return ImplementAttributeReferences;

**Comment by pvojtechovsky** [comment]
> cannot cast from Typereference to field declaration

in Java language are such operations not possible. In Spoon most model types (e.g. CtClass, CtField, CtMethod, ...) has two represtantions: 1) the entity itself and 2) the reference to the entity.
For example
* CtClass - CtTypeReference
* CtMethod - CtExecutableReference
* CtField - CtFieldReference
* ...

Each interface of Entity has a method, which creates a new instance of entity reference
Each interface of Entity reference has a method, which searches for an existing instance of entity.

For example: 
* `CtField#getReference()`, `CtFieldReference#getFieldDeclaration()`.
* `CtClass#getReference()`, `CtTypeReference#getTypeDeclaration()`

Is it more understandable now? ;-)

**Comment by mashalahmad** [comment]
thanks so much @pvojtechovsky  now this make sense but then how to get  values of those fields for whom I get the References?

**Comment by pvojtechovsky** [comment]
```java
CtFieldReference<?> fieldRef = ...
CtField<?> field = fieldRef.getFieldDeclaration();
```

**Comment by mashalahmad** [comment]
thanks alot :) U rock!!!!
