### ISSUE TITLE
spoon-maven-plugin: <enableComments>false</enableComments>

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#2465]
Now that comments are enabled by default now, it seems that 

    <enableComments>false</enableComments>

does not work anymore in spoon-maven-plugin

@surli WDYT?

**Comment by surli** [comment]
Once https://github.com/SpoonLabs/spoon-maven-plugin/pull/62 is merged and Spoon 7.1.0 is released, don't forget to bump Spoon version in spoon-maven-plugin and to also release it.
