### ISSUE TITLE
Review process improvement - delay PR closing before review is done

### ISSUE THREAD

**Issue by zielint0** [INRIA/spoon#2475]
@monperrus 
@pvojtechovsky 
@surli

Could we leave PR open for some time (3-4 days?), so the author has chance and time to explain any doubts and provide explanation?

For example, I did not reply before closing
- https://github.com/INRIA/spoon/pull/2472
- https://github.com/INRIA/spoon/pull/2468

Could you reopen them for review and consider merging? :-)
I provided detailed explanations.

**Comment by monperrus** [comment]
Dear Tomasz,

We agree, it is important that everybody has the time to see the PR and comment on it. That's a documented guideline in https://github.com/INRIA/spoon/blob/master/CONTRIBUTING.md:

    Spoon integrators leave pull requests opened at least 1 day before merging, so that the community is aware and can comment on them

3-4 days may be too long, esp when there are other pending pull-requests

**Comment by zielint0** [comment]
Mercii Martin! :-)

> 3-4 days may be too long, esp when there are other pending pull-requests

How about 1-2 days for my PRs? ;-)

If there are merge conflicts in my PRs, I can solve them or reintroduce fixes as new PR (sometimes it is faster and less laborious).

**Comment by monperrus** [comment]
> How about 1-2 days for my PRs? ;-)

We may consider a special temporary exception for you Tomasz :-)

**Comment by zielint0** [comment]
@monperrus 
Mercii!
