### ISSUE TITLE
bugs: bugs found with static analyzer PVS-Studio Java

### ISSUE THREAD

**Issue by Egor18** [INRIA/spoon#2483]
Hello!
I found several bugs in Spoon with our PVS-Studio Java static analyzer prototype.

1.
https://github.com/INRIA/spoon/blob/6b07da89021260f2222212ec1cd523ae9f4ec72f/src/main/java/spoon/support/visitor/ClassTypingContext.java#L218-L227 **Warning:** V6008 Null dereference of 'type'. ClassTypingContext.java:225

2.
https://github.com/INRIA/spoon/blob/97f6af6a14ba948050f087e205cc43d9b1516460/src/main/java/spoon/support/compiler/jdt/PositionBuilder.java#L691-L696 **Warning:** V6007 Expression 'content[off] == '\n'' is always false. PositionBuilder.java:694

Probably forgot to increment `off` here.

3.
https://github.com/INRIA/spoon/blob/8f14f3d0af5a21eef32a061224abbc786e7d3484/src/test/java/spoon/support/visitor/java/JavaReflectionTreeBuilderTest.java#L244-L245 **Warning:** V6009 Function 'equals' receives an odd argument. An object 'removeModifiers(elementModifiers, ModifierKind.PUBLIC, ModifierKind.ABSTRACT)' is used as an argument to its own method. JavaReflectionTreeBuilderTest.java:244

https://github.com/INRIA/spoon/blob/8f14f3d0af5a21eef32a061224abbc786e7d3484/src/test/java/spoon/support/visitor/java/JavaReflectionTreeBuilderTest.java#L253-L254 **Warning:** V6009 Function 'equals' receives an odd argument. An object 'removeModifiers(elementModifiers, ModifierKind.PUBLIC)' is used as an argument to its own method. JavaReflectionTreeBuilderTest.java:253

I'm pretty sure that `otherModifiers` (which is unused now) should be used here.

4.
https://github.com/INRIA/spoon/blob/88fe9031bca9d7c9cbb2103cb9e66ab5936760a9/src/main/java/spoon/metamodel/MMMethodKind.java#L114-L117 **Warning:** V6007 Expression 'result.level == k.level' is always false. MMMethodKind.java:115

We've already checked that `result.level < k.level`, how could it be `result.level == k.level`?

5.
https://github.com/INRIA/spoon/blob/267199348663afc9d94b8896ef9be714350a3d3a/src/main/java/spoon/support/reflect/declaration/CtEnumImpl.java#L115-L117 **Warning:** V6060 The 'enumValues' reference was utilized before it was verified against null. CtEnumImpl.java:117, CtEnumImpl.java:116

https://github.com/INRIA/spoon/blob/79980e9ee7785f406115d7a07d44f20d8274add1/src/main/java/spoon/pattern/PatternBuilder.java#L116-L117 **Warning:** V6060 The 'template' reference was utilized before it was verified against null. PatternBuilder.java:117, PatternBuilder.java:116

https://github.com/INRIA/spoon/blob/c020be3c28e95e1803abf79a63c8d9b1f649f203/src/main/java/spoon/support/compiler/jdt/ReferenceBuilder.java#L310-L312 **Warning:** V6060 The 'cuDeclaration' reference was utilized before it was verified against null. ReferenceBuilder.java:312, ReferenceBuilder.java:310

These checks for null make no sense, because we would get NRE earlier anyway.

6.
There are lots of suspicious unused variables as well. Here is the list:
**Warning:** V6021 Variable 'tpr' is not used. RoleHandlersGenerator.java:147
**Warning:** V6021 Variable 'caseStmt' is not used. PositionBuilder.java:390
**Warning:** V6021 Variable 'mapEntryNode' is not used. PatternParameterConfigurator.java:601
**Warning:** V6021 Variable 'mmMethod' is not used. MetamodelProperty.java:112
**Warning:** V6021 Variable 'executableTypeReference' is not used. JDTTreeBuilderHelper.java:240
**Warning:** V6021 Variable 'executableFactory' is not used. JDTTreeBuilderHelper.java:190
**Warning:** V6021 Variable 'typeFactory' is not used. JDTTreeBuilderHelper.java:188
**Warning:** V6021 Variable 'innerClass' is not used. ImportScannerImpl.java:697
**Warning:** V6021 Variable 'childSPI' is not used. ElementSourceFragment.java:184
**Warning:** V6021 Variable 'sp' is not used. ElementSourceFragment.java:142

**Comment by Egor18** [comment]
And one more:
https://github.com/INRIA/spoon/blob/c020be3c28e95e1803abf79a63c8d9b1f649f203/src/main/java/spoon/reflect/factory/ExecutableFactory.java#L129-L135 **Warning:** V6026 This value is already assigned to the 'paramType' variable. ExecutableFactory.java:135

`atr` is assigned to `paramType`, `erased` is assigned to `atr` and `paramType` is assigned to `erased` again.

**Comment by monperrus** [comment]
Thanks a lot @Egor18

Do you plan to contribute to Spoon with pull-requests fixing those important warnings?

**Comment by Egor18** [comment]
Yes, I can fix some of them.

**Comment by Egor18** [comment]
What should we do about №4? Simply remove unreachable code with exception?

**Comment by pvojtechovsky** [comment]
> What should we do about №4? 

Please replace 
```java
if (k.detector.test(method) && result.level < k.level) {
```
by
```java
if (k.detector.test(method) && result.level <= k.level) {
```

**Comment by monperrus** [comment]
Thanks a lot for your PRs!

**Comment by Egor18** [comment]
> > What should we do about №4?
> 
> Please replace
> 
> ```java
> if (k.detector.test(method) && result.level < k.level) {
> ```
> 
> by
> 
> ```java
> if (k.detector.test(method) && result.level <= k.level) {
> ```

I tried to do that change, but unfortunately 80 tests fail with that exception:
`spoon.SpoonException: Ambiguous method kinds OTHER X OTHER for method getAnnotation(java.lang.Class)`

**Comment by pvojtechovsky** [comment]
> What should we do about №4?

@Egor18 this should work
```java
			if (k.detector.test(method) && result.level <= k.level) {
				if (result.level == k.level && k != OTHER) {
					throw new SpoonException("Ambiguous method kinds " + result.name() + " X " + k.name() + " for method " + method.getSignature());
				}
				result = k;
			}
```

**Comment by Egor18** [comment]
All warnings were fixed except for the last one (V6026).
@pvojtechovsky, It looks like it's your code, could you please check it out? Is there some error, or it's just a redundant code?

**Comment by pvojtechovsky** [comment]
@Egor18 
please try this code as solution
```java
	private CtTypeReference<?> getMethodParameterType(CtTypeReference<?> paramType) {
		if (paramType instanceof CtTypeParameterReference) {
			paramType = ((CtTypeParameterReference) paramType).getBoundingType();
		}
		if (paramType instanceof CtArrayTypeReference) {
			CtArrayTypeReference atr = (CtArrayTypeReference) paramType;
			CtTypeReference<?> originCT = atr.getComponentType();
			CtTypeReference<?> erasedCT = getMethodParameterType(originCT);
			if (originCT != erasedCT) {
				CtArrayTypeReference<?> erased = atr.clone();
				erased.setComponentType(erasedCT);
				return erased;
			}
		}
		if (paramType == null) {
			paramType = factory.Type().OBJECT;
		}
		return paramType.clone();
	}
```

**Comment by Egor18** [comment]
All warnings were fixed. Thanks for help. I'm closing the issue.
