### ISSUE TITLE
bug: imports added to generated sources are never used

### ISSUE THREAD

**Issue by pvojtechovsky** [INRIA/spoon#2485]
Test case:
* The Spoon pattern is based on java source which imports template class like e.g. `com.somepackage.Request`
* The Spoon pattern replaces this template class by another class, so the `com.somepackage.Request` isn't used in generated code.

bug: printed sources contains import of `com.somepackage.Request` if any javadoc contains substring "Request".
I my case the javadoc was, which caused that is: `Generated by com.somepackage_generator.templates.soap.RequestBuilderTemplate#serviceWrapper(RequestBuilderTemplate.java:25)`

The problem is in /spoon-core/src/main/java/spoon/reflect/visitor/ImportScannerImpl.java method visitCtJavaDoc
in code
`javadoc.contains(ctImport.getReference().getSimpleName())`

Spoon should understand javadoc better before it marks import as used.

**Comment by monperrus** [comment]
closed per #2486
