### ISSUE TITLE
Problems with setTarget() assigning

### ISSUE THREAD

**Issue by leventov** [INRIA/spoon#249]
Now source calls `setParent(this)` in setter methods more consistently, but it leads to NullPointerExceptions in some cases.

E. g. `ctTargetedAccess.setTarget(null)` -- seems to be a valid way to construct AST sometimes? Or I should always know on which `this` (it might be not very simple, if there are nested inner classes) I call each expression and set `this` implicit?

Otherwise source of many setters should look more like
```
setTarget(E target) {
    if (target != null) // this condition is absent currently
        target.setParent(this);
    this.target = target;
}
```

**Comment by monperrus** [comment]
Can you write a failing test case?

**Comment by leventov** [comment]
Ok, see the pull request. The test case might look artificial, but I do actually need this. Imagine I want to replace delegation:

```
class Foo {
  Bar bar;
  void foo() {
    bar.bar();
  }
}
```

with inheritance/merged classes. In this case I have some code like
```
fooAst.filter(CtTargetedAccess.class).forEach(access -> {
  if (access.getTarget().getReference().getClass() == Bar.class) {
    access.setTarget(null);
  }
})
```

to remove `bar.` parts.

As I said, replacing `bar.` with `this.` (might be implicit) is possible, but not convenient, in case of nested classes etc., and also less efficient (why create `CtThisAccess` instances for each occurance, if it might be just `null`).
