### ISSUE TITLE
How can I get the list of all the methods called by the current method?

### ISSUE THREAD

**Issue by prasannjeet** [INRIA/spoon#2534]
Hello,
Say I have a `CtMethod m`, and this method calls various other methods (maybe from various packages) in it's body.

How can I get a list of all these methods?

**Comment by pvojtechovsky** [comment]
Hello,
```java
m.filterChildren(new TypeFilter(CtInvocation.class)).map((CtInvocation inv) -> inv.getExecutable()).list()
```

**Comment by prasannjeet** [comment]
Thank you! 👍

**Comment by prasannjeet** [comment]
The above returns me list objects of type CtExecutableReferenceImpl.
Is it possible to get the list of objects of type CtMethod?
(Or is it possible to convert CtExecutableReferenceImpl to CtMethod?)
thanks!

**Comment by pvojtechovsky** [comment]
use `(CtMethod) methodRef.getExecutableDeclaration()`
you are welcome ;-)
