### ISSUE TITLE
Why are not shadow classes accessible from Factory?

### ISSUE THREAD

**Issue by pvojtechovsky** [INRIA/spoon#2546]
I have found that shadow Types have assigned same Factory like normal classes, but they are not accessible from that Factory, because `TypeFactory#get(Class)` creates shadow types first using different/temporary Factory and later it assigns them normal Factory.

@monperrus What is the reason for that? Would not it be more consistent to have shadow classes accessible after they are loaded once?

**Comment by monperrus** [comment]
closed per #2536
