### ISSUE TITLE
refactor: restore older assertions (isEmpty -> size > 0) in some places

### ISSUE THREAD

**Issue by zielint0** [INRIA/spoon#2553]
@pvojtechovsky 
Thanks to Pavel's feedback I will restore older assertions. They are a bit better.
Thank you Pavel again!

https://github.com/INRIA/spoon/pull/2468

I will close this issue when it's done. Just don't want to miss this one.

**Comment by monperrus** [comment]
Cleaning session: since #2468 is closed, we can now close this one.

**Comment by monperrus** [comment]
cleaning pass, don't hesitate to comment or reopen.
