### ISSUE TITLE
CtCatchVariable/CtParameter.setDefaultExpression() should throw UnsupportedOperationException

### ISSUE THREAD

**Issue by leventov** [INRIA/spoon#260]
Currently both CtCatchVariableImpl and CtParameterImpl define `defaultExpression` field and allow to work with it normally via `getDefaultExpression()` and `setDefaultExpression()`. However this should be never done, and clearly identifies a bug in spoon library user's code.

**Comment by GerardPaligot** [comment]
For now, `setDefaultExpression()` throws an `UnsupportedOperationException` and `getDefaultExpression()` returns `null`. That seems good too.

**Comment by monperrus** [comment]
for both CtCatchVariable and CtParameter? could you add a test case?

**Comment by GerardPaligot** [comment]
@monperrus Yep, here: https://github.com/INRIA/spoon/pull/361
