### ISSUE TITLE
NullPointerException/StackOverflow error while compiling new Foo class version from #259

### ISSUE THREAD

**Issue by leventov** [INRIA/spoon#264]
See #259

**Comment by GerardPaligot** [comment]
Do you manage to reproduce the error locally?

**Comment by GerardPaligot** [comment]
I found some new information about this issue:

1. It isn't the `Foo` class the problem but the executable reference expression in this line `return (T) nullParent.getBody().getElements(elemType::isInstance).get(0);` in `NullParentTest` class.
2. I can't reproduce the bug when I execute test cases in my IDE. The bug appears only when I use maven in command line. That sucks, impossible to launch a test case in debug mode.

**Comment by leventov** [comment]
@GerardPaligot I suggest a plan:
1) I split #259 commit in two parts - one just adds if (!= null) checks, another -- adds NullParentTest for it.
2) You merge first part
3) second is pending in pull requests due to a bug

Because I really need if (!= null) checks in my project; And now all process is stuck because nice-to-have tests for it (for reducing techincal debdt and ease future developement; addition itself is trivial and obviously don't have bugs) are failing because of another bug.

**Comment by GerardPaligot** [comment]
Sounds like a good idea. This bug doesn't concern #249.

**Comment by leventov** [comment]
@GerardPaligot thank you. I've updated #259; when you merge it I'll PR NullParentTest which is failing.

**Comment by monperrus** [comment]
OK, we merge #259 and you create a new PR with the tests only.

**Comment by leventov** [comment]
#267

**Comment by boeserwolf91** [comment]
@GerardPaligot maybe the bug is related to the bug which will be fixes with #311 
Maybe a new ecj versions helps at this point too. Did you try it?

**Comment by GerardPaligot** [comment]
@boeserwolf91 mh, maybe. I'll check that today.

**Comment by GerardPaligot** [comment]
Unfortunately, #311 doesn't correct #267.
