### ISSUE TITLE
IncrementalLauncher reactivness

### ISSUE THREAD

**Issue by nharrand** [INRIA/spoon#2646]
I am unsure if I am using it wrong or if this is by design, but I feel like `IncrementalLauncher` is not instantaneous (duh). Would it make sense, (and would it be possible) to add a method to wait for a new `CtType` to be added to the model?

WDYT?

**Comment by Egor18** [comment]
Incremental launcher actually detects when a source file was added (or modified), and then rebuilds correspondig type and its dependant types. Unmodified types are loaded as classpath entries.
Here is the basics of the incremental launcher algorithm: https://github.com/INRIA/spoon/pull/1688#issuecomment-342425370
You can get the information about new types here (`mAddedSources`):
https://github.com/INRIA/spoon/blob/0baea22886471256e305e66e8a4cdcd8146795a9/src/main/java/spoon/IncrementalLauncher.java#L240

**Comment by nharrand** [comment]
Thanks for your answer.
My confusion came from the fact that `mChangesPresent` is final. Do I have to recreate an instance of IncrementalLauncher, every time I want it updated?

**Comment by Egor18** [comment]
Well, it was designed for the most usual use-case:
1) Load model from cache (and rebuild changed types)
2) Save new cache info
3) Do your transformations
4) Exit application

**Comment by nharrand** [comment]
> Well, it was designed for the most usual use-case:

It wasn't a criticism at all! I still think it suits my needs. I just misunderstood what it did.
