### ISSUE TITLE
feat: Allow to configure the path where to put the log files

### ISSUE THREAD

**Issue by surli** [INRIA/spoon#2672]
Currently the path of Spoon log files is hard-coded to be put in `/tmp/spoon-log.log` (see: https://github.com/INRIA/spoon/blob/f8a96bdb648f598ce86dbf3bc5d4cd287f59531a/src/main/resources/log4j.properties#L10). 

We should allow user to configure that path.

**Comment by Egor18** [comment]
Unlike `setLevel` there is no easy way to configure (or override) output path in runtime.
I think there are actually 2 options:

1) We can replace path with system property:
`log4j.appender.R.File=${spoon.log.path}`
And then user will have to add `-Dspoon.log.path=...` or to call `System.setProperty(...)` prior to running spoon.
This is a bit inconvenient.

2) We can configure the whole logger from code and not from log4j.properties. 
Or at least we can remove appender from there and add it from code using `logger.addAppender(...)`.

WDYT?

**Comment by monperrus** [comment]
I guess we can already do solution 1? (if yes, it means that the feature is already there, we have to document it and we can close the issue).

**Comment by Egor18** [comment]
> I guess we can already do solution 1?

Not exactly. We'll have to replace
`log4j.appender.R.File=${java.io.tmpdir}/spoon-log.log`
with
`log4j.appender.R.File=${spoon.log.path}`
and initialize `spoon.log.path` environment variable with default value somewhere if it was not defined by user.

**Comment by monperrus** [comment]
This solution LGTM.
