### ISSUE TITLE
feat: add support to navigate from sibling to sibling within Spoon's model tree

### ISSUE THREAD

**Issue by tempuser1909** [INRIA/spoon#2699]
Hi,

I am wondering if spoon has any API provided that allows me to navigate between siblings?

Currently, I only know of these 3 methods that allows me to obtain the elements I want
- element.getElement() is to get anything from itself, its children and subchildren
- element.filterChildren() is to get all children and subchildren
- element.getParent() is to get parent or keep going up the tree until Class type is matched

However, I would like to get the element's sibling after I did the query to obtain this element.
(and I can go upwards a execution flow starting from the element I got from the query)

Is it possible to do that?

Thank you.

**Comment by pvojtechovsky** [comment]
Hi,

no it is not possible. But there is CtScanner which visits all nodes of AST. May be it is helpful in your case.

**Comment by surli** [comment]
In your case you might also use the XPath-like API we provide: once you get an element you have its path, so you might use it to build the sibling path. See: http://spoon.gforge.inria.fr/path.html

**Comment by nharrand** [comment]
I think #2906 implements this to some extent. 
It adds `CtElement#getDirectChildren()`, so one would just need to do `ctElement.getParent().getDirectChildren();` to navigate through siblings. (Some filtering is still required to get only elements of a certain role).

**Comment by nharrand** [comment]
I think we can close this. Don't hesitate to re open if you feel like it deserve something more.
