### ISSUE TITLE
feat: add principled support for models validators

### ISSUE THREAD

**Issue by surli** [INRIA/spoon#2701]
I start this issue as a general topic to discuss the concept of model *validators*. We proposed this concept while discussing with @pvojtechovsky in #2624 about moving imports, but I already had something like that in mind when proposing #1598 a while ago.

The general idea is to allow the execution on validations on a Spoon model. Those validations can be executed only to report some information, but also to change the model in order to fix it.
Right now, the first idea of such validator would be to properly manage the imports in a model.

Still several questions have to be clarified from my point of view:
  1. What's the difference between a "validator" and a "processor"? At first I'd say the difference is only on the step when a validator is executed but I'm not so sure anymore, see why in 2.
  2. When the validators needs to be triggered? At first, we only discussed about executing the validator before pretty-printing, but maybe it needs to also be executed before executing the processors, after executing the processors, before pretty-printing...? 
  3. If a validator aims at fixing a model, then it can transform it, so how do we check the validations of our validators? :) 

So, here it is, just few questions to start the discussion.

**Comment by pvojtechovsky** [comment]
> 1. What's the difference between a "validator" and a "processor"?

It would be probably easier if we would merge these terms and to have only processor.
Problems:
* After CompilationUnit is CtElement (will be soon), then Processor might be called on CtCompilationUnit
* The CtCompilationUnit is actually not accessible from `factory.Package().getRootPackage()`, so compilation unit processor have to be called different - or compilation units must be somehow accessible from the root package
* The processor is always called on all nodes of model, while pretty printer validator needs to be called on to be printed compilation unit(s) and all it's types

> 2. When the validators needs to be triggered?

printer is actually processor too (well ... depending on Launcher configuratiom :-( ...), but it's processor queue is created individually in `JDTBasedSpoonCompiler#generateProcessedSourceFilesUsingTypes`.

May be we should have processors for everything and client will simply define list of processors, which has to be executed.... e.g. ["buildModel", "modifyModel", "validateModel", "printModel", "compileModel"]
And we should also support more flexible alternative solution where client can call processors one by one ... as his/her algorithm needs.... but that needs more coding on client's side.

> 3. If a validator aims at fixing a model, then it can transform it, so how do we check the validations of our validators?

I do not understand this question.

**Comment by monperrus** [comment]
closed per #2683
