### ISSUE TITLE
Github is down

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#2709]
"We continue to monitor restores which are taking longer than anticipated. We estimate they will be caught up in an hour and a half." https://status.github.com/messages

I have problems to merge and comment :disappointed:

**Comment by nharrand** [comment]
https://blog.github.com/2018-10-21-october21-incident-report/

**Comment by pvojtechovsky** [comment]
Github seems to be in good condition now. Anyway they are still working on some fixes...

**Comment by pvojtechovsky** [comment]
Looks like github doesn't run CI yet.

**Comment by pvojtechovsky** [comment]
Github status is green. Spoon CI processes were processed. Closing this issue
