### ISSUE TITLE
How to get head of a nested if that is in a if-elseif-else statement?

### ISSUE THREAD

**Issue by tempuser1909** [INRIA/spoon#2712]
Hi,

I am currently having issues with getting back the base If statement.

Example
```
if(...) {
...
} else if (...) {
    if(...) {
    } else if(...) {
    } else if(...) {
    } else {
        <this block>
    }
} else {
...
}
```

So I managed to get \<this block\> but if I use `block.getParent(CtIf.class)`, I am only able to get the CtIf of the 2nd else-if block which is not the element I wanted. And if I keep it in a while loop with a condition like `while(block.getParent(CtIf.class) != null){ block = block.getParent(CtIf.class); }` I will only get the very first CtIf. My goal is to obtain first CtIf element that holds if-elseif-elseif-else block.

Because the tree for this whole CtIf is
```
CtIf statement
-> then
-> else
    -> CtIf statement
        -> then
            -> CtIf statement
                -> then
                -> else
                    -> CtIf statement
                        -> then
                        -> else
                            -> CtIf statement
                                -> then
                                -> else
        -> else
```
rather than something like this (just an example)
```
CtIf statement
-> then
-> CtElseIf statement
    -> then
        -> CtIf statement
            -> then
            -> CtElseIf statement
                -> then
            -> CtElseIf statement
                -> then
            -> else
-> else
```
I find it hard to identify if a CtIf is a else-if or the original if statement.

I wonder if it is possible to find the original if statement with the current API?

Thank you.

**Comment by surli** [comment]
> I wonder if it is possible to find the original if statement with the current API?

The quick answer is no AFAIK. As you mentionned the model does not have the concept of "Else if" so it's not easy currently to know if you are in a big "if / else if / else" or in several "if / else / if / else". 

I think the idea of no having the concept of "else if" was to allow users to use only one concept to catch all ifs "CtIf", and not having to manage the case of "else if". I wonder if we could add in the model a CtElseIf which directly inherits from CtIf. WDYT @monperrus @pvojtechovsky ?

**Comment by msteinbeck** [comment]
> I wonder if we could add in the model a CtElseIf which directly inherits from CtIf.

IMHO, it might not be a good idea to inherit directly from a `CtIf`. According to the `Liskov substitution principle` a `CtElseIf` must fulfill all conditions of a `CtIf`. Although they have a lot in common, a `CtIf`, for example, may stand alone, wheres a `CtElseIf` requires either a `CtElseIf` or a `CtIf` predecessor.

**Comment by monperrus** [comment]
You want something like this (not tested, may need some adaptation): 

```
// return the first "else if" in the parents
someNode.getParent(new Filter<CtIf>() {
			@Override
			public boolean matches(CtIf element) {
				return element.getRoleInParent().equals(CtRole.THEN);
			}
		})
```

**Comment by tempuser1909** [comment]
@monperrus, I do not think that this example could work because the nested IF can be in the else block too. And if the nested IF is in the else block, the tree will look too similar to if-elseif-elseif-elseif-elseif-else rather than if-elseif-else-if-elseif-elseif-else. (still quoting my code example above) making it hard to identify the nested IF's first CtIf statement.

**Comment by pvojtechovsky** [comment]
What about that loop?
```java
while (block.getParent() instanceof CtIf) block = block.getParent();
```

**Comment by tempuser1909** [comment]
@pvojtechovsky, 

```while (block.getParent() instanceof CtIf) block = block.getParent();``` 

The problem with this, I believe, is that it does not stop at the nested IF if condition because there is no difference between if and elseif.

```
if(...) {
...
} else if (...) {
    if(...) {      <-- this is what I want to get
    } else if(...) {
    } else if(...) {
    } else {
        <this block>
    }
} else {
...
}
```

**Comment by pvojtechovsky** [comment]
it will stop there because the parent of that CtIf is CtBlock and not another CtIf. Try it

**Comment by tempuser1909** [comment]
@pvojtechovsky, ohhhh! I see. I will try that. Thanks!

**Comment by surli** [comment]
> it will stop there because the parent of that CtIf is CtBlock and not another CtIf.

What if you have:
```
if(...) {
...
} else if (...) {
    if(...) {      <-- this is what I want to get
    } else if(...) {
      statement1
      statement2
    } else if(...) {
    } else {
        <this block>
    }
} else {
...
}
```

the else-if containing 2 statement will also be considered as a block, won't it?
