### ISSUE TITLE
Is Spoon's license compatible with MIT

### ISSUE THREAD

**Issue by msteinbeck** [INRIA/spoon#2713]
May I publish a Java library under MIT license if it is using Spoon? I tried to figure out whether the CeCILL license is compatible with MIT, but had no luck so far.

**Comment by surli** [comment]
Spoon is not compatible with MIT. The CeCILL license it used is basically a LGPL.

**Comment by msteinbeck** [comment]
So may I license my library under the terms of the LGPL or do I have to go with the CeCILL license?

**Comment by surli** [comment]
Actually, if your library is only using Spoon as an external library (i.e. you make a reference of Spoon, but you're not changing anything inside Spoon) I think you can put whatever license you want on your own code. See: https://softwareengineering.stackexchange.com/questions/141847/how-does-using-a-lgpl-gem-affect-my-mit-licensed-application

**Comment by surli** [comment]
If on the contrary you're changing/modifying a part of Spoon, then you have to use the same license.

**Comment by msteinbeck** [comment]
That sounds great. We use Spoon from Maven Central, so licensing shouldn't be a problem. Thank you for your link.

**Comment by monperrus** [comment]
FYI Spoon is now dual-licensed MIT & Cecill-C, see #2950
