### ISSUE TITLE
get file location from ctclass

### ISSUE THREAD

**Issue by JackLehman** [INRIA/spoon#2718]
I would like to find a way to get the location or absolute path of my ctclass element. getPath() does not help as it doesn't show the class location in my hard drive. e.g., I would to run something like this myctclass.getLocation() and it should return /users/myspace/.../example.java 

Is there any option to get this working?

Thank you in advance

**Comment by pvojtechovsky** [comment]
```java
CtClass clazz ´...
File file = clazz.getPosition().getFile();
file.getAbsolutePath()
```
You are welcome

**Comment by JackLehman** [comment]
Perfect. Thanks.
