### ISSUE TITLE
feat: Support Java 11 new features

### ISSUE THREAD

**Issue by surli** [INRIA/spoon#2728]
Here's the list of new features in Java 11: https://openjdk.java.net/projects/jdk/11/

At first sight, I think we need to implement:
  * https://openjdk.java.net/jeps/323

**Comment by nharrand** [comment]
And now [java 12](https://jdk.java.net/12/) even if it is probably less urgent (as it is not LTS).
At firs glance, I see only this that could cause a problem:
 * [Switch Expressions](https://openjdk.java.net/jeps/325)
