### ISSUE TITLE
feature: add support for execution/control flow analysis

### ISSUE THREAD

**Issue by tempuser1909** [INRIA/spoon#2734]
Hi,

I would like to ask if it has been proposed to have execution/control flow analysis?

For example, instead having just one CtModel when you call launcher#buildModel(), Spoon can have another model (maybe something like CtExecutionModel/CtExecutionGraph) that is still tied to CtModel but allows user to analyze the parsed code in a different way.

Or maybe Spoon is just meant to be purely for AST analysis?

Thank you.

**Comment by pvojtechovsky** [comment]
There is an experimental project on github which contains such spoon extension for control flow analysis. But it is actually not up to date with latest Spoon and it is not finished. But I am sure it would be good starting point. I agree that it would be nice to have it as part of Spoon core too.
@monperrus what is the link to that project?

**Comment by monperrus** [comment]
See also: 
https://github.com/DIVERSIFY-project/syringe.
(would be great to port both https://github.com/marcelinorc/spooncontrolflow and https://github.com/DIVERSIFY-project/syringe here)

**Comment by monperrus** [comment]
@tempuser1909 such a feature would be welcome, do you plan to contribute with a pull-request?

**Comment by tempuser1909** [comment]
@monperrus, I can try and see if I can implement such a big feature.

I will first try implementing one of the issues I have raised a couple months (#2396).

And once I am comfortable with developing/compiling Spoon and with Spoon internals, I will try my hand at implementing this.

**Comment by pvojtechovsky** [comment]
> I can try and see if I can implement such a big feature.
> And once I am comfortable with developing/compiling Spoon and with Spoon internals, I will try my hand at implementing this.

It sounds really great! You have our support! 👍 

> I will first try implementing one of the issues I have raised a couple months (#2396).

It would be nice to have it too, but may be with sniper printing mode this feature is not so urgent for you?

**Comment by tempuser1909** [comment]
Yes, it is not as urgent with Sniper mode. However, I thought that it would be easier to implement and at the same time get to know Spoon's internals better with that issue first.

**Comment by nharrand** [comment]
I guess #2827 implements this feature request. So, I am closing this. Don't hesitate to reopen if it's missing something.

**Comment by monperrus** [comment]
FYI:
TinyPDG https://github.com/YoshikiHigo/TinyPDG is a library for building control flow graphs (CFGs) and program dependency graphs (PDGs) from Java source code. It also includes functionality to detect code clones by using the built PDGs. By @YoshikiHigo

**Comment by lsafina** [comment]
Hello! It is probably too late for this post, but I was looking for java to CFG library, and unfortunately haven't found this thread at the beginning (\*feeling super dumb*). So I wrote my converter, completely based on Spoon model. I leave the link here, maybe someone will be interested https://gitlab.inria.fr/lsafina/java-cfg-builder

P.S: After finding this thread I wanted to check on `control-flow` library, but wasn't able to resolve the dependency and to find it at https://mvnrepository.com/artifact/fr.inria.gforge.spoon. Is it alright?

**Comment by monperrus** [comment]
thanks for the pointer.

yes, spoon-control-flow is not deployed on Maven Central, you can build and install from source.

**Comment by monperrus** [comment]
yes, PRs to improve documentation are much welcome!
