### ISSUE TITLE
Missing documentation page (diagrams.html)

### ISSUE THREAD

**Issue by hansjorg** [INRIA/spoon#2738]
On the introduction page for analysis processors, this paragraph is referring to a non-existent page:

```You can view the complete meta model of Spoon at this page. It is a simple way to know what you can inspect with processors.``` 

Page with link:

http://spoon.gforge.inria.fr/first_analysis_processor.html

Missing page:

http://spoon.gforge.inria.fr/diagrams.html

**Comment by monperrus** [comment]
Thanks a lot for the bug report! Fixed in #2743
