### ISSUE TITLE
add support for override analysis

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#274]
We have a transformation that requires a method that gives the overridden method.

```
CtMethod {
  // returns the overridden method, null if none 
  CtMethod getOverridenMethod()

}
```

**Comment by monperrus** [comment]
to get the first declaration of the method it would be something like:

````
m = meth.getOverridenMethod();
while (m!=null)  {
  m = m.getOverridenMethod();
}
```

**Comment by monperrus** [comment]
should it be `CtExecutableReferene getOverridenMethod()`?

**Comment by monperrus** [comment]
the implementation may reuse CtExecutableReference.isOverriding()

**Comment by GerardPaligot** [comment]
We should talk where we put this method. I don't think we should put it in the AST but in a query space where we can put utility methods like this one.

**Comment by GerardPaligot** [comment]
2 filters for this issue:

- OverridenMethodFilter where 0 is the top overriden method.
- OverridingMethodFilter to get all method below the current method overriden or declared excluding itself.
