### ISSUE TITLE
preparation of a post with @ftomassetti

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#2742]
@ftomassetti, we'd be happy to answer here to your questions and debate about source code analysis and transformation :trumpet:

**Comment by ftomassetti** [comment]
Hi, I would instead have the questions and debate on a google doc for two reasons:
1) Comments and discussions are easier in my view
2) SEO Reasons: if here we write the same content I will copy in the post this could look as a copy of an existing page, which could be bad

So I would work on a list of questions and put them in a google doc that I would share here and which could be accessible to any member of your team

**Comment by ftomassetti** [comment]
I started planning a general structure of the post [here](https://docs.google.com/document/d/1caeKxxp7XRtjR34Tg39RMjm5zy5MUJnNjYihrXyyBPQ/edit?usp=sharing). What do you think?

**Comment by monperrus** [comment]
Hi Federico, I've just added some content in the Gdoc. WDYT?

**Comment by monperrus** [comment]
Those two goals are quite different, but both or them are interesting.

Hence, I would propose to do two different posts:
* When and why using source code transformation? Joint post by the JavaParser and the Spoon teams.
* A short introduction to spoon (where we would not repeat again all possible usages as we do
currently, we could replace this by a highlight on the key features)

**Comment by pvojtechovsky** [comment]
@ftomassetti Here is an example of bulk refactoring.

Most of the changes of DefaultJavaPrettyPrinter.java in this PR #1956 were done automatically by Spoon by these steps:
1) search for all occurrences of [OldPattern](https://github.com/INRIA/spoon/tree/master/src/test/java/spoon/test/template/testclasses/replace/OldPattern.java)
2) for each match of OldPattern remember matched elements and matching parameters
3) generate new elements by [NewPattern](https://github.com/INRIA/spoon/tree/master/src/test/java/spoon/test/template/testclasses/replace/NewPattern.java) and matching parameters
4) replace matched elements by newly generated elements

Here is the code which does matching and replacing
```java
//create spoon model, which contains to be refactored code, OldPattern and NewPattern. 		
Factory factory = null;
//old code pattern
Pattern oldPattern = OldPattern.createPatternFromMethodPatternModel(factory);
//new code pattern
Pattern newPattern = NewPattern.createPatternFromNewPattern(factory);
//search AST of root package (contains types, their members, statements, ...) for oldPattern
oldPattern.forEachMatch(factory.getModel().getRootPackage(), (Match match) -> {
	//this is called for each match of the oldPattern
	//list of matching elements. This code matches old code pattern
	List<CtElement> oldCode = match.getMatchingElements();
	//generate elements of new code, which should be used instead of oldCode
	List<CtStatement> newCode = newPattern.generator().generate(CtStatement.class, match.getParameters());
	for (int i = 0; i < oldCode.size(); i++) {
		if (i == 0) {
			//replace first element of old code by generated code
			oldCode.get(i).replace(newCode);
		} else {
			//delete all other elements of old code
			oldCode.get(i).delete();
		}
	}
});
```

Note: at the time of #1956, I had to adjust formatting manually after automatic replace. But now we have sniper printer, which keeps source of untouched AST fragments same as original, so it is even less work to do such refactoring on real projects.

**Comment by pvojtechovsky** [comment]
>  where the pattern is described?

`OldPattern#patternModel` and `NewPattern#NewPattern` are the patterns

**Comment by monperrus** [comment]
OK for keeping one post.

Note that properly covering one single use case would take at least 2-3 paragraphs and 1-2 listings.
 
Since we have already listed 11 usages, this is a lot of work and content!

**Comment by monperrus** [comment]
The post is online see https://tomassetti.me/analyze-generate-and-transform-java-code/

See also discussion in #2744
