### ISSUE TITLE
Detecting bean elements with spoon, using patterns or matchers?

### ISSUE THREAD

**Issue by mehdi-kaytoue** [INRIA/spoon#2762]
I have several bean classes as follow:

![image](https://user-images.githubusercontent.com/6720471/48313868-52c72880-e5c2-11e8-97db-00e1eac6fe24.png)

My goal it to get, bean by bean, a reference to the CtMethod of get/set and reference to CtField PROP_xxx and propxxx.

For the moment, I did something a bit "artisanal", that is, searching for CtClass which have some CtField whose simple name starts with PROP_. Then, for each match, filter elements of this CtClass by type/name to match with the getter setter and property value assignation. 

I use these references to track in all the code where are the usage of each bean through their setter/getter or PROP_ usage, hence my need of identifying the CtMethod/CtField object in particular.

After looking at the matchers and more especially patterns, I feel that I could do something much nicer, such as specifying the template of a bean, and looking for all it's occurrences. Did someone ever encountered this need (which could imagine quite common)?

Thanks for any advices,
cheers,
Mehdi

EDIT: after reading (a bit) discussion about javaParser, I found out that they have this project of bean identification too, see slide 21 of @ftomassetti at https://www.slideshare.net/FTomassetti/javaparser-a-tool-to-generate-analyze-and-refactor-java-code?ref=http://javaparser.org/presentations/

**Comment by pvojtechovsky** [comment]
I am glad you are interested in patterns. Yes it is possible to use them here.
I did not tried to match patterns on the SET of field members. I mean one field, one setter and one getter, which are located on arbitrary place and order of CtType or some of them even inherited from super type.
I believe it is possible, but you are first who tries it this way, so it will need some experimenting... without documentation.... and may be bug fixing ... anyway I agree it would be nicest and shortest approach.
I will gladly support you with that, but that will need some time ;-)

The easier, but less nice is to use 3 patterns. One for field, second for getter and third for setter. That is tested and should be easy. This way you can detect all fields, getters and setters, and to get their pattern parameters like: property name and property type. You just have to somehow combine fields, getters and setters together e.g. by the same property name.

But may be the patterns are too heavy hammer for that simple task, which can be done, as you described, by few queries. The patterns becomes to be really useful when you need to match more complicated code. See my comment [here](https://github.com/INRIA/spoon/issues/2742#issuecomment-437458623), which shows matching quite complicated structure, which would be nearly impossible to match and maintain using queries.

**Comment by Evestar7** [comment]
I'm ready when you are. What's next on the agenda for the meeting?

**Comment by mehdi-kaytoue** [comment]
Thanks for your answer @pvojtechovsky. I understand very well what you mean. 

Do you thing that introducing CtBean as a feature which would be detected at model construction / post proc (the sooner the more efficient), and then being able to query TypeFilter<CtBean>?

**Comment by pvojtechovsky** [comment]
I am sure it doesn't belong to primary Spoon AST model. But it would be an interesting extension which might be implement somewhere outside the Spoon AST as secondary model.
I can imaging more such secondary models, which would be linked to primary model.
* Data flow model
* Control flow model
* Bean properties model
* ...

But actually Spoon doesn't offer an API how to define and maintain such secondary models. I am sure we need something like that. 

WDYT?

**Comment by mehdi-kaytoue** [comment]
100% agree. 

All the operations I am doing before running my algorithms on the model requires some additional knowledge on the model, and namely, I call a method "augmentModel()" where things such as beans are identified. 

This notion of "augmented model" built upon a ctmodel would be awesome.
For beans, it would mean that CtBeanModel would give access to them after some build()  on this augmented model. 

I don't know the architecture of spoon enough to give a proposition right now, but I'd love to participate in that feature!

**Comment by mehdi-kaytoue** [comment]
One may probably wish to combine augmented models, that is, working with beans in control flow model, ...

**Comment by pvojtechovsky** [comment]
The support of model augmenting would be interesting for me too, but I am busy with other topics these days ... so I can think about that later ... anyway suggestions and ideas are welcome ... as usually ;-)

**Comment by pvojtechovsky** [comment]
>  I'd love to participate in that feature!

@mehdi-kaytoue you are welcome to implement #2774 ;-) Or do you expect some different concept? Please give us feedback to #2774 if it would be fitting to your needs. It would be good to have your opinion before I start to implement it. May be I will found time for that in next months ... if you do not do it sooner ;-)

**Comment by pvojtechovsky** [comment]
>  method call graph 

many clients needs that. I am sure I will need it too... it would be nice to have it somehow as part of Spoon, so we do not have to implement it again and again ...

> I would have never know where to start

I will gladly discuss concepts with you. It is much faster to write a concept for the feature then to implement a feature. ... and I fight with not enough time too.
