### ISSUE TITLE
Multi-modules projects and spoon

### ISSUE THREAD

**Issue by tdurieux** [INRIA/spoon#2770]
Hi everyone,

I'm currently trying the spoon multi-modules project with spoon but some of those projects define several times the same class.
Currently, spoon rejects to create such models.

How would you handle this case?

**Comment by nharrand** [comment]
I don't know the solution, but I am interested having it.

**Comment by pvojtechovsky** [comment]
It looks like an incompatibility of current Spoon model with Java modules concept.
It needs some change in Spoon concepts ...

**Comment by surli** [comment]
> spoon multi-modules project with spoon 

which can of multi-modules? Maven multi-modules? Java multi-modules?
