### ISSUE TITLE
Exception while building  Model

### ISSUE THREAD

**Issue by mashalahmad** [INRIA/spoon#2778]
Im getting this error at the build Model. 
Exception in thread "main" spoon.SpoonException: SourcePosition values must be ascending or equal
could you please throw light on it?

**Comment by pvojtechovsky** [comment]
It means you have some kind of source code which is not well handled by Compiler/Spoon and the provided source position is invalid.

It would be very helpful if you could provide the failing test case - code fragment which causes that error.

**Comment by pvojtechovsky** [comment]
@mashalahmad without more detailed error description we cannot fix it. So please try to give us more details or close this issue. Thank You ;-)
