### ISSUE TITLE
Set encoding per file

### ISSUE THREAD

**Issue by Egor18** [INRIA/spoon#2781]
Hi!
There are some big legacy projects, which have mixed encodings like UTF-8 and Cp1251 for source files.
I know that we can set encoding in spoon with `launcher.getEnvironment().setEncoding(...)` for the whole project, however it seems like it's impossible to specify encoding for a specific file.
It cases some trouble. For example if we parse Cp1251 file as UTF-8:
In Cp1251:
```
String s1 = "Привет";
String s2 = "АБВГДЕ";
```

In UTF-8:
```
String s1 = "??????";
String s2 = "??????";

```
These two strings considered equal in AST, because of the encoding.

So what can I do here? I'd like to have some encoding auto detection (outside of spoon), but I'm not sure if it possible to specify encoding for each file separately in spoon.

**Comment by pvojtechovsky** [comment]
It is not yet possible, but I guess there should be possible to make PR which allows to register some callback, which will be called to detect encoding of each file individually.
If I remember well it is Spoon code who reads bytes from file and converts them to characters, so Spoon can influence used encoding too.

**Comment by surli** [comment]
I think an issue might be when using JDT directly: see https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/support/compiler/jdt/JDTBasedSpoonCompiler.java#L158. Currently we only give one encoding for the whole project to be parsed by JDT. I'm not sure we can give it multiple encodings.

**Comment by pvojtechovsky** [comment]
I checked the code yesterday and it is doable. Yes, we give one encoding to JDK compiler, but internally JDK compiler calls Spoon back and spoon delivers `char[]`. So Spoon can read each file using different encoding.

**Comment by Egor18** [comment]
Thanks, I've just managed to add a specific callback to the `Environment` for that purpose.    
So I can invoke it for each file in `initializeCompiler` method from `FileCompilerConfig`:
```
if (jdtCompiler.getEnvironment().getEncodingCallback() == null) {
    char[] content = IOUtils.toCharArray(inputStream, jdtCompiler.getEnvironment().getEncoding());
    cuList.add(new CompilationUnit(content, fName, jdtCompiler.getEnvironment().getEncoding().displayName()));
}
else {
    String enc = jdtCompiler.getEnvironment().getEncodingCallback().apply(new File(fName));
    char[] content = IOUtils.toCharArray(inputStream, enc);
    cuList.add(new CompilationUnit(content, fName, enc));
}
```


The api looks like this:

```
final Launcher launcher = new Launcher();
launcher.addInputResource("./src/test/resources/encodings/Cp1251.java");
launcher.addInputResource("./src/test/resources/encodings/Utf8.java");
launcher.getEnvironment().setEncodingCallback(file -> detectEncoding(file));
CtModel model = launcher.buildModel();
```
`detectEncoding` - user provided function, used to detect an encoding of each file. (I used juniversalchardet inside).

It works ok now (it can handle both Cp1251 and Utf8).
I will polish it a bit and provide PR.

P.S. Not quite sure about the api - reopening a file to detect an encoding could be quite slow. But using `inputStream` here is not good as well (we need to somehow read it twice). Probably it's better to read `inputStream` into a byte array and then use it for encoding detection and then convert it to the `content` using that encoding.

**Comment by pvojtechovsky** [comment]
> Not quite sure about the api

... that is exactly the reason why I did not wrote anything yesterday ... because nice solution would need deeper changes in related Spoon code, which is already buggy concerning encoding handling ...

**Comment by Egor18** [comment]
Thanks!

**Comment by Evestar7** [comment]
Stick a fork in ME, I am done.
