### ISSUE TITLE
Javadoc missing from the website

### ISSUE THREAD

**Issue by daeglee** [INRIA/spoon#2790]
spoon document website needs to be updated

javadoc line is not founded (404 Error)

For example,

Factory [(javadoc](http://spoon.gforge.inria.fr/mvnsites/spoon-core/apidocs/spoon/reflect/factory/Factory.html))

**Comment by surli** [comment]
Thanks for reporting this we indeed had an issue when deploying the javadoc.

**Comment by UpdateYourDocumentation** [comment]
Hiya, 

Do you have any idea when the JavaDocs will be back up on the website? Alternatively have you just got a dropbox (or etc) link for them?

Thanks

**Comment by nharrand** [comment]
For current SNAPSHOT version, this seems to work:
http://spoon.gforge.inria.fr/mvnsites/spoon-core/spoon-core/apidocs/index.html

**Comment by monperrus** [comment]
redeployed, pb fixed http://spoon.gforge.inria.fr/mvnsites/spoon-core/apidocs/spoon/reflect/factory/Factory.html

**Comment by monperrus** [comment]
Thanks for the bug report

**Comment by nharrand** [comment]
Javadoc is missing again.

**Comment by monperrus** [comment]
Fixed see http://spoon.gforge.inria.fr/mvnsites/spoon-core/apidocs/index.html

Thanks for the report
