### ISSUE TITLE
Scanning of Comments on CompilationUnit?

### ISSUE THREAD

**Issue by pvojtechovsky** [INRIA/spoon#2798]
If we move comment at the beginning of the file to compilation unit (like In #2683), then such comment is not visited when scanning from rootPackage, because compilation unit is part of secondary model (mapping of classes to files) and is not part of primary model (semantic java).

Is it OK?

Note: it breaks some tests like `CtScannerTest#testScan` with contract: `all AST nodes are visited through method "scan" `

WDYT?

**Comment by stefanleh** [comment]
> 
> 
> It seems OK to me. Conceptually, comments are not first-class AST nodes (they have nothing to do with the program behavior).

That might be true, but nobody likes the comments moved around when modifying the code via processors. In my current project the comments were used for defining extension points in the code, which is for sure not what they are for, but it worked for them many years pretty well. Now i cant change the code via processors but need to use the processors for finding the parts i need to change then by regex. So i would love spoon handling comments as first class citizens.

**Comment by pvojtechovsky** [comment]
Thank you to your feedback. 
@stefanleh do you have an concept how the comments can become first class citizens in Spoon model? Please make a new issue with that concept.

**Comment by surli** [comment]
Not sure why the issue has been closed (might be a mistake) so I reopen it.

**Comment by pvojtechovsky** [comment]
I closed this issue intentionally. My origin question was answered. So it can be closed.
And "comments as first class citizens" belong to different issue - if anybody wants to discuss it.

**Comment by surli** [comment]
Sorry I read it before finishing my coffee this morning, I missed the last sentence of your answer. :sleepy: Closing it again.
