### ISSUE TITLE
Jenkins: create a job to check Spoon with another seed

### ISSUE THREAD

**Issue by surli** [INRIA/spoon#2835]
We use to have a Travis job with the following execution:

```
SPOON_SEED_CU_COMPARATOR=1 mvn -Djava.src.version=1.8
```
in order to check the behavior. See: https://github.com/INRIA/spoon/pull/1954 for more information.

We should keep this test in a jenkins job.

**Comment by monperrus** [comment]
Staled, closing. Feel free to reopen if appropriate.
