### ISSUE TITLE
Is spoon-control-flow module ready for use?

### ISSUE THREAD

**Issue by kanghj** [INRIA/spoon#2849]
Hello,

I noticed https://github.com/INRIA/spoon/commit/8a8ef93b347312720d7d021d81dad1b44a9e4754 adding a new module for control flow analysis. This seems like an exciting feature. Is this module ready for use? I've tried adding 

```
<dependency>
         <groupId>fr.inria.gforge.spoon</groupId>
         <artifactId>control-flow</artifactId>
         <version>0.0.1</version>
     </dependency>
```
to my pom.xml but it didn't succeed in finding it.

**Comment by monperrus** [comment]
closing?

**Comment by kanghj** [comment]
Yes, I'll close it. mvn install works as expected. I've been trying it out, and I will make another issue if I have more questions about this.
