### ISSUE TITLE
StackOverflowError in CtAnnotation#getValueOfObject

### ISSUE THREAD

**Issue by seintur** [INRIA/spoon#2858]
CtAnnotation#getValueOfObject fails with a StackOverflowError when the value of the annotation parameter is an operation that references a constant that is not in the model built by Spoon.

The sample project https://github.com/seintur/spoon-annotation-getValueAsObject reproduces the bug.

**Comment by monperrus** [comment]
Hi Lionel,
Could you create a pull-request with a failing test case?
This would be super useful for fast fixing :-)
Thanks.

**Comment by monperrus** [comment]
closed by #2866
