### ISSUE TITLE
CtElement equality bug or feature

### ISSUE THREAD

**Issue by seintur** [INRIA/spoon#2859]
I'm getting confused on how to test the equality of two CtElement instances with Spoon.

The following project illustrates the issue:

https://github.com/seintur/spoon-ctelement-equality/tree/master

This project defines a method processor that processes the following method:

```java
public class C {
    int r;
    void m() {
      r = 1;
      r = 2;
    }
  }
```

The code of the processor follows:

```java
      public void process(CtMethod<?> element) {
		CtBlock<?> block = element.getBody();
		List<CtStatement> l = block.getStatements();
		CtFieldAccess<?> fa0 = (CtFieldAccess<?>) ((CtAssignment)l.get(0)).getAssigned();
		CtFieldAccess<?> fa1 = (CtFieldAccess<?>) ((CtAssignment)l.get(1)).getAssigned();
		List<CtElement> lfas = new ArrayList<>();
		lfas.add(fa0);
		lfas.add(fa1);
		System.out.println("Original");
		System.out.println(lfas.get(0).getParent());
		System.out.println(lfas.get(1).getParent());
		lfas.remove(fa1);
		System.out.println();
		System.out.println("After removal");
		System.out.println(lfas.get(0).getParent());
	}
```

As can be read, the processor retrieves the two statements r=1 and r=2, add them in list lfas, removes the second element, and displays the list. The output follows:

	Before removal
	r = 1
	r = 2
	
	After removal of the second element
	r = 2

After the removal, the list contains the second element that should have been removed. In my understanding, this means that List#remove tested the equality of the first element of the list (r=1) with the parameter (r=2), returned true, and removed the first element instead of the second one.

My question follows: is it a bug or a feature? If a feature, how one should test the equality of two CtElement instances?

**Comment by surli** [comment]
Hi @seintur !

here you're checking the equality of a `CtFieldAccess`, and I'd say they're both the same for `r = 1;` and `r = 2;` since here we only care about the access to `r`. It's exactly the same kind of access.
So I think here both elements of your list are equals: it should be easy to check by using a set. 

IMO it's then a feature.

**Comment by seintur** [comment]
Hi @surli 

ok, got it, it makes sense.

Lionel.
