### ISSUE TITLE
bug: If CtPath contains "#subPackage[...]", then evaluateOn() would be invalid

### ISSUE THREAD

**Issue by ycaxgjd** [INRIA/spoon#2870]
if one code file has one line of package info like `package spoon;` then for example, `element.getPath().evaluateOn(root)` would not find any elements, even `element` itself because of the occurrence of corresponding `#subPackage[...]`

we have to reprocess `element.getPath()` and here is one example :
```
CtPath path = ancestor.getPath();
String str = ancestorPath.toString();
str = str.substring(str.indexOf("#containedType"));
path = new CtPathStringBuilder().fromString(str);
List<CtElement> list = path.evaluateOn(root);
```

**Comment by monperrus** [comment]
Thanks a lot for the bug report. Could you make a pull-request with a failing test case? Thanks!

**Comment by ycaxgjd** [comment]
I tried on my test case and found it working with no problem, following similar test cases in _spoon/src/test/java/spoon/test/path/PathTest.java_

now i guess this issue might come from minor differences between spoon and gumtree-spoon-ast-diff
