### ISSUE TITLE
Visitor not working as expected

### ISSUE THREAD

**Issue by ftomassetti** [INRIA/spoon#2875]
Hi, I am trying this Kotlin code:

```
    val originalCode = """class MyClass {

            MyClass() {
            }

            void foo(MyParam param, String otherParam) {
                param.doSomething();
            }

            int bar(MyParam param) {
                return param.count();
            }

        }"""
    val parsedClass = Launcher.parseClass(originalCode)
    parsedClass.accept(object : CtAbstractVisitor() {

        override fun <T : Any?> visitCtMethod(m: CtMethod<T>) {
            // This is never invoked
            println(m.simpleName)
        }
    })
```

I am surprised that the visitCtMethod does not seem to be invoked. Am I doing something wrong? How can I find all method declarations in a tree?

**Comment by monperrus** [comment]
CtAbstractVisitor is not recursive. To filter through children recursively you probably want to use
a scanner:
||
||

| val parsedClass = Launcher.parseClass(originalCode) parsedClass.accept(object : *CtScanner*() {
override fun <T : Any?> visitCtMethod(m: CtMethod<T>) { // This is never invoked
println(m.simpleName) *super.*||*|visitCtMethod(m|**)*  } |
