### ISSUE TITLE
Visualization: hierarchical edge bundling of imports

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#2878]
![screenshot_2019-02-12_17-13-42](https://user-images.githubusercontent.com/803666/52650021-b6c2fb00-2ee9-11e9-9390-b3986c22beaa.png)

From @msteinbeck, spin-off of https://github.com/INRIA/spoon/issues/2877#issuecomment-462712528

Live version at http://spoon.gforge.inria.fr/visu/spoon.html

> This visualization technique is called hierarchical edge bundling. It has been developed to enhance the visualization of graphs with lots of edges. In this example, all java files of Spoon are arranged on a circle. Whenever there is a dependency between two files `a` and `b`, an edge is drawn from `a` to `b`. All edges follow the hierarchy of the system, that is, the package hierarchy.

**Comment by monperrus** [comment]
@msteinbeck it would be great to have it only for the interfaces in spoon.reflect. could you make a try?

**Comment by tdurieux** [comment]
It can be the logo of spoon, and the logo evolves for each release :)

**Comment by monperrus** [comment]
CD could do it: continuous delivery of logos :-)

**Comment by tdurieux** [comment]
It has probably never been done :)

**Comment by msteinbeck** [comment]
@monperrus Should only files located in `spoon.reflect` be placed on the circle, or should only dependencies from and to `spoon.reflect` depicted by an edge?

**Comment by monperrus** [comment]
I mean the first "only files located in spoon.reflect be placed on the circle,"

**Comment by msteinbeck** [comment]
@monperrus I sent you an email.
