### ISSUE TITLE
Obtaining CtType from fully qualified name

### ISSUE THREAD

**Issue by pratikfegade** [INRIA/spoon#2880]
Hi, how should one go about obtaining a reference to a CtType object from a fully qualified java name? Also, is there a way to check if a CtType is an array type?

**Comment by monperrus** [comment]
> how should one go about obtaining a reference to a CtType object from a fully qualified java name?
factory.Type().get(fullyQualifiedName)

> Also, is there a way to check if a CtType is an array type?
This is a hard one, see answer at https://github.com/INRIA/spoon/pull/2882

**Comment by pratikfegade** [comment]
Okay thanks a lot! I actually have another question. I want to replace field accesses in a given source with function calls. So for example, `int hash = a.b.c.hashCode()` should be replaced by something like `int hash = getFieldC(getFieldB(a)).hashCode()`. I have been subclassing CtScanner and replacing field reads there but that does not replace all the field reads in an expression like the above. I found the ReplacementVisitor, but couldn't figure out how to use it from the documentation. Could you give an example, if ReplacementVisitor is actually what I think it is? If not, what would let me achieve this?

**Comment by monperrus** [comment]
Happy to help. For a new question, please create a new issue. If this one is answered, please close. Thanks.
