### ISSUE TITLE
replace field accesses in a given source with function calls

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#2884]
from https://github.com/INRIA/spoon/issues/2880#issuecomment-464808350

> I want to replace field accesses in a given source with function calls. So for example, `int hash = a.b.c.hashCode()` should be replaced by something like `int hash = getFieldC(getFieldB(a)).hashCode()`.

**Comment by monperrus** [comment]
Here is a solution: #2885

**Comment by pratikfegade** [comment]
Thanks! You may close this issue now. I believe non-collaborators cannot close issues.

**Comment by monperrus** [comment]
Thanks!
