### ISSUE TITLE
counting constructorcalls of subtypes

### ISSUE THREAD

**Issue by blackfoxoh** [INRIA/spoon#2886]
Hi,
I'm trying to use the analyse-component of spoon to gather some insights on our code. I tried a lot the last days but now I need a little help how to achieve what I want, please:
I want to analyze a project with a swing-client. There are lot's of classes I can find by name ("Detailbereich*") or better by filtering for subclasses of a common superclass. Each of theese classes I want to scan for constructorcalls of classes which are subclasses of javax.swing.JComponent and just want to count these constructorcalls per subtype. In the end a textual output is enough for the first step and writing the output is not the problem - just to show more clearly what my goal is:

> DetailbereichXXX: JTextField=6; JLabel=8; MyOwnSwingComp=2

 

I started with a java-class like the following:
```
      Launcher launcher = new Launcher();
      launcher.addInputResource("path/to/source");
      launcher.buildModel();
```

I then tried things like writing processors, added an instance to the launcher and called `launcher.process()` or tryed `CtModel model = launcher.getModel();` further but for now I'm stuck how to find all the subclass-stuff (MyOwnSwingComp from example above could be a subclass of JTextField for example). 
I know it is a bit complex question and I'm not expecting a final solution but maybe someone can point me in the right directions
- how to start best? Using Processors? Iterating/Filtering the model?
- how to filter for constructorcalls of subclasses of JComponent (a JDK-class, not contained in the analysed source)?

Thanks for reading and trying to help

**Comment by monperrus** [comment]
A processor is a good option.

Method `isSubtypeOf` is what you want. Example:

```java
        Launcher l = ....;
		l.addProcessor(new AbstractProcessor<CtConstructorCall>() {
			@Override
			public void process(CtConstructorCall element) {
				if (element.getType().getTypeDeclaration().isSubtypeOf(getFactory().createReference("javax.swing.JComponent"))) {
					// do domething
				}
			}
		});
```

**Comment by blackfoxoh** [comment]
Thank you very much :-)
The subtype-checking and especially `getFactory().createReference("javax.swing.JComponent")` was what I missed when trying on my own...
