### ISSUE TITLE
SpoonException when setting the content of a comment that begins with //

### ISSUE THREAD

**Issue by rolve** [INRIA/spoon#2887]
I am using Spoon to anonymize Java files, so I am removing instances of names inside comments. I get the content of the comment using `CtComment.getContent()`, replace some stuff, and put the new string back using `setContent()`.

However, if the original content of a multi-line comment starts with `//`, then the code in `JDTCommentBuilder.cleanComment()` throws an exception, because it thinks this is a single-line comment (but it is the *content* of a multi-line comment that happens to *look like* a single-line comment).

The original comment looks for example like this:

    /*
    // foo
    bar
    */

Why is `cleanComment()` even used? Isn't `setContent()` supposed to modify only the *content* of the comment, without dealing with comment markers?

**Comment by monperrus** [comment]
> Why is |cleanComment()| even used?
for historical reasons.

does the exception happen when building the model or when calling setContent?

could you write a failing test case in a pull request?

Thanks!

**Comment by rolve** [comment]
> does the exception happen when building the model or when calling setContent?

When calling `setContent()` with something that starts with `//`.

I don't think I'll find the time to create a complete test case though...

**Comment by monperrus** [comment]
I cannot reproduce the exception, see #2887.

Which version do you use?

**Comment by rolve** [comment]
I'm sorry, I wasn't precise enough. The problem seems to occur only if the `//` is on a new line.

This crashes for me, I am using Spoon 7.3.0:

    import spoon.Launcher;
    import spoon.reflect.code.CtComment;
    import spoon.reflect.visitor.CtScanner;
    
    public class Crash {
        public static void main(String[] args) {
            Launcher.parseClass("class A { /* Hey */ }").accept(new CtScanner() {
                public void visitCtComment(CtComment comment) {
                    comment.setContent("//\nHo");
                }
            });
        }
    }
