### ISSUE TITLE
EvalHelper#getCorrespondingRuntimeObject doesn't handle valid field references

### ISSUE THREAD

**Issue by Aaron1011** [INRIA/spoon#2891]
Currently, [EvalHelper#getCorrespondingRuntimeObject ](https://github.com/INRIA/spoon/blob/ee7b9d962eb3b56d048302fedf5fdc7f76db7e55/src/main/java/spoon/support/reflect/eval/EvalHelper.java#L70) only supports references to enum fields. However, Java annotations can also reference static fields of other classes (e.g. `Integer.MAX_VALUE`).

To make methods such as `CtAnnotation#getValueAsObject` more useful, `EvalHelper#getCorrespondingRuntimeObject` should be extended to support all valid annotaiton field reads.

**Comment by monperrus** [comment]
Thanks for the report. Fix in #2899.
