### ISSUE TITLE
Question about getting all typeVariables 

### ISSUE THREAD

**Issue by NerwenElensar** [INRIA/spoon#2895]
I am stuck on a problem how to find all type variables in e.g. a class. I found a method called "getActualTypeArguments" in the CtActualTypeContainer, which seems to do exactly what I want.

So as you see in the code screenshot I am trying to filter all CtActualTypeContainers into a list so I can use it to get all the typeArguments. As I am not really great with Generics I don't understand the failure. As I have a List but eclipse tells me to convert it to List. When I change it to List it says to change it to List Please tell me what is wrong in there, or if there's an easier way to get all type Arguments using the spoon Framework. 

![image](https://user-images.githubusercontent.com/11652712/53517681-81b0ce00-3acf-11e9-9a99-d351e25f219e.png)

**Comment by tdurieux** [comment]
If you are replacing TypeFilter<> by TypeFilter<CtActualTypeContainers>, it should work.

**Comment by NerwenElensar** [comment]
Thanks a lot! I was so confused and stuck on it. ^_^
