### ISSUE TITLE
Navigate CtElement in a clone tree

### ISSUE THREAD

**Issue by 11510746** [INRIA/spoon#2896]
## Description
1. **Clone** the original AST for modification
2. Having the reference to a node in the original AST, **WANT** to get the reference of the **corresponding node** in the clone AST

## Implement 1
Traverse the clone AST and use `.equals(CtElement)` to find the corresponding node. But it is a little bit slow.

## Implement 2
`CtElement.class` also offers a method `getElements(filter)`, but **how to custom a filter** that fulfills my need? Will it be faster than Impletement 1?

**Comment by monperrus** [comment]
Using [paths](http://spoon.gforge.inria.fr/path.html)
Something like:

```
CtPath path = elem.getPath();
CtPath subPath = absPath.relativePath(rootElem);
CtElement elemInClone = subPath.evaluateOn(clone).get(0)
```
