### ISSUE TITLE
License: change license to double-license Cecill-C/MIT

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#2898]
It's been years that we're aware that the Cecill-C license hinders the development of Spoon (see #321, #1861, #1930, #2713).

And finally, @ftomassetti hits again in [his great post](https://tomassetti.me/analyze-generate-and-transform-java-code/) (and he's right to do so, thanks for it :-).

I've consulted Inria, and it seems we have a solution, which is acceptable and backward compatible: double-licensing.

__We would change the license from Cecill-C to a dual-license Cecill-C/MIT__ 

We're commenting on this issue before the end of this month in order to reach a consensus.

**Comment by nharrand** [comment]
It seems like a good solution to me.
