### ISSUE TITLE
question: Insert a CtElement node to a CtElement parent

### ISSUE THREAD

**Issue by 11510746** [INRIA/spoon#2901]
I am trying to apply operate spoon AST node of the left tree according to `Diff.getRootOperations()`.

I got the parent to insert with the help of `MappingStore`, but I do not find any useful method in `CtElement.class` that help me insert a child node at any place.

```java
/* left - left tree
** right - right tree
*/
CtType clone = left.clone();
for(Operation op : rootOperations){
    if (op instanceof InsertOperation){
                // the insert node is from the right tree
                ITree rightTreeNode  = op.getAction().getNode();
                CtElement spoonObj = (CtElement) rightTreeNode.getMetadata(SpoonGumTreeBuilder.SPOON_OBJECT);
                CtElement toInsert = spoonObj.clone();
                // get the corresponding parent node in the left tree
                ITree leftTreeParent = ms.getSrc(rightTreeNode.getParent());
                CtElement spoonParent = (CtElement) leftTreeParent.getMetadata(SpoonGumTreeBuilder.SPOON_OBJECT);


                //But how to set a child in the parent
                // Want something like: spoonParent.setChild(index, spoonParent)
                toInsert.setParent(spoonParent);
            }
}
```

I also wonder the whether the SourcePosition of each node in the clone tree will get invalid after insertion?

**Comment by monperrus** [comment]
> I do not find any useful method in |CtElement.class| that help me insert a child node at any place.
Spoon is semantic you have to use a semantic setter: parent.addStatement, parent.addTypeMember, etc.

**Comment by monperrus** [comment]
> I also wonder the whether the SourcePosition of each node in the clone tree will get invalid after insertion?

Please create one issue per question if they are different.

**Comment by 11510746** [comment]
> Spoon is semantic you have to use a semantic setter: parent.addStatement, parent.addTypeMember, etc.

As you say, I find `insertAfter` and `insertBefore` methods in `CtStatement`.  And it seems all possible kinds of nodes to insert are subtypes of `CtStatement` (what is the type if i want to insert `import` statements). 

<img width="481" alt="2019-03-07 9 36 37" src="https://user-images.githubusercontent.com/23020574/53963103-8e64a000-4127-11e9-95b3-a3ce22a3b324.png">


But **what I can held is a parent node**, not the statement it should be inserted before or after. I want to get the children list of the parent.

I also find `CtStatementList#addStatement(int index, CtStatement statement)`.  But how can I get the children list (something like `CtStatementList`)?

**Comment by monperrus** [comment]
> I also find CtStatementList#addStatement(int index, CtStatement statement). But how can I get the children list (something like CtStatementList)?

CtBody#getStatements()

**Comment by 11510746** [comment]
> CtBody#getStatements()

So the parent should be a subtype of `CtBodyHolder` bc it has `CtStatement getBody()` method.

But `CtClass` is not a subtype of it. If the parent happens to be a `CtClass`, then I cannot get its body.

<img width="503" alt="2019-03-07 10 38 56" src="https://user-images.githubusercontent.com/23020574/53964198-cff64a80-4129-11e9-99e1-03c09e248e5a.png">

**Comment by monperrus** [comment]
To understand the Spoon metamodel, please see
http://spoon.gforge.inria.fr/structural_elements.html
http://spoon.gforge.inria.fr/code_elements.html
