### ISSUE TITLE
Cannot get imports of a file

### ISSUE THREAD

**Issue by lucacampanellaadn** [INRIA/spoon#2913]
Hi,
I'm trying to get the imports from a source file, but the implementation seems to be buggy.
Here's my code:
`        CompilationUnit cu = launcher.getFactory().CompilationUnit().getOrCreate(srcTojavaFile);
        ModelList<CtImport> imports = cu.getImports(); `

No matter what I put in the file, `cu.getImports()` always returns empty. Using the debugger, seems in the CompilationUnit object imports are always empty.

Thanks!
Luca

**Comment by nharrand** [comment]
Have you try to use 
```java
launcher.getEnvironment().setAutoImports(true);
```
before parsing a class?

**Comment by lucacampanellaadn** [comment]
It still doesn't work, also calling .toString on the Compilation unit (cu) object yields this exception: 
`Exception in thread "main" java.util.NoSuchElementException
	at java.util.ArrayDeque.removeFirst(ArrayDeque.java:285)
	at java.util.ArrayDeque.pop(ArrayDeque.java:522)
	at spoon.reflect.visitor.DefaultJavaPrettyPrinter.scan(DefaultJavaPrettyPrinter.java:374)
	at spoon.support.reflect.declaration.CtElementImpl.toString(CtElementImpl.java:296)`

**Comment by surli** [comment]
@lucacampanellaadn how do you use it? Did you build the model before calling: 
```
CompilationUnit cu = launcher.getFactory().CompilationUnit().getOrCreate(srcTojavaFile); 
```
? The list of imports is only built when running `launcher.buildModel();`

**Comment by lucacampanellaadn** [comment]
Yes I do, right now my complete code is:
`       Launcher launcher = new Launcher();
        launcher.addInputResource(pathToJar);
        launcher.buildModel();
        CtModel model = launcher.getModel();
        List<CtClass> classes = model.getElements(new TypeFilter<>(CtClass.class));
        classes.forEach(ctClass -> System.out.println(ctClass));`

**Comment by lucacampanellaadn** [comment]
Right, I wasn't doing that. So currently my updated code is:
```
        Launcher launcher = new Launcher();
        launcher.getEnvironment().setAutoImports(true);
        launcher.buildModel();

        CompilationUnit cu = launcher.getFactory().CompilationUnit().getOrCreate(src);
        ModelList<CtImport> imports = cu.getImports(); // return a set of CtReference

        cu.toString();
```
And still no imports are found, plus cu.toString() still gives same exception.
Thanks!

**Comment by nharrand** [comment]
Yes but here you use `addInputResource` on a Jar, aren't you? If so, you need to either decompile it, or use the JarLauncher.

```
JarLauncher launcher = JarLauncher("<path_to_jar>", "<path_to_output_src_dir>", "<path_to_pom>");
```

**Comment by surli** [comment]
You first need to specify the resources to use for building the model, read the doc there: http://spoon.gforge.inria.fr/launcher.html

**Comment by lucacampanellaadn** [comment]
I tried that, with code:
```
Launcher launcher = new Launcher();
launcher.getEnvironment().setAutoImports(true);
CompilationUnit cu = launcher.getFactory().CompilationUnit().getOrCreate(src);
launcher.buildModel();
ModelList<CtImport> imports = cu.getImports(); // return a set of CtReference
cu.toString();
```
And still no input and the exception

**Comment by lucacampanellaadn** [comment]
Any update? :)

**Comment by nharrand** [comment]
Try this:

```java
		Launcher launcher = new Launcher();
		launcher.addInputResource("path/to/UseJson.java");
		launcher.getEnvironment().setAutoImports(true);
		launcher.buildModel();

		CompilationUnit cu = launcher.getFactory().CompilationUnit().getOrCreate("path/to/UseJson.java");
		ModelList<CtImport> imports = cu.getImports(); // return a set of CtReference
		cu.toString();
```

**Comment by lucacampanellaadn** [comment]
Thanks for the answer!
Still not working and still exception :(

**Comment by nharrand** [comment]
Can you send me the stack trace? (You are using version 7.3.0 ?)

**Comment by lucacampanellaadn** [comment]
Yes, this is the stack trace of the `.toString()`:
```

**Comment by nharrand** [comment]
Can you also post the source of the file you are analyzing?

**Comment by lucacampanellaadn** [comment]
Yes,
```
package matchers;

import java.io.InputStreamReader;

public class TestClass {
    public TestClass() {
        InputStreamReader isr;
    }
}
```


I also made sure the file is actually there doing:
```
        File test = new File("./analyzer/src/main/java/matchers/TestClass.java");
        System.out.println(test.exists());
```

**Comment by nharrand** [comment]
It is weird that you get an exception with the PrettyPrinter.
Do you call `launcher.prettyprint();` somewhere?

I am having trouble reproducing this error. With spoon-core 7.3.0

With `TestSpoon.java`
```java
public class TestSpoon {
	public static void main(String[] args) {
		Launcher launcher = new Launcher();
		launcher.addInputResource("path/to/TestClass.java");
		launcher.getEnvironment().setAutoImports(true);
		launcher.buildModel();

		CompilationUnit cu = launcher.getFactory().CompilationUnit().getOrCreate("path/to/TestClass.java);
		List<CtImport> imports = cu.getImports(); // return a set of CtReference
		for (CtImport i: imports) System.out.println(i.toString());
	}
}
```
and `TestClass.java`
```java
package matchers;

import java.io.InputStreamReader;

public class TestClass {
	public TestClass() {
		InputStreamReader isr;
	}
}
```

I get 
```
import java.io.InputStreamReader;
```

**Comment by nharrand** [comment]
Could you print your model with:
```java
		Launcher launcher = new Launcher();
		launcher.addInputResource("path/to/TestClass.java");
		launcher.getEnvironment().setAutoImports(true);
		launcher.buildModel();
		launcher.setSourceOutputDirectory("output");
		launcher.prettyprint();
```

**Comment by lucacampanellaadn** [comment]
Yes I can, exactly the class gets printed in the file, very strange.

**Comment by nharrand** [comment]
Ok, to narrow the problem down:

If you try this way:
```java
Launcher launcher = new Launcher();
launcher.addInputResource("path/to/TestClass.java");
launcher.getEnvironment().setAutoImports(true);
launcher.buildModel();

CtType t = launcher.getModel().getRootPackage().getPackage("matchers").getType("TestClass");

CompilationUnit cu = launcher.getFactory().CompilationUnit().getOrCreate(t);
List<CtImport> imports = cu.getImports();
System.out.println("Print size of imports: " + imports.size());
for (CtImport i: imports) System.out.println(i.toString());
```
t should not be null, as you can print it.
Do you get an empty import list?
Or does it contains a CtImport that you can not print?

**Comment by lucacampanellaadn** [comment]
Ok nice, like this it works and prints the imports. Only problem is (not a big problem for me, but maybe you want to fix it), if I call `cu.toString()` right after the cu declaration it still throws this exception:
```
Exception in thread "main" java.lang.NullPointerException
	at spoon.reflect.visitor.ImportScannerImpl.isTypeInCollision(ImportScannerImpl.java:890)
	at spoon.reflect.visitor.ImportScannerImpl.visitCtTypeReference(ImportScannerImpl.java:137)
	at spoon.support.reflect.reference.CtTypeReferenceImpl.accept(CtTypeReferenceImpl.java:82)
	at spoon.reflect.visitor.ImportScannerImpl.scan(ImportScannerImpl.java:148)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:176)
	at spoon.reflect.visitor.CtScanner.visitCtImport(CtScanner.java:914)
	at spoon.support.reflect.declaration.CtImportImpl.accept(CtImportImpl.java:79)
	at spoon.reflect.visitor.ImportScannerImpl.scan(ImportScannerImpl.java:148)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:176)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:150)
	at spoon.reflect.visitor.CtScanner.visitCtCompilationUnit(CtScanner.java:981)
	at spoon.support.reflect.declaration.CtCompilationUnitImpl.accept(CtCompilationUnitImpl.java:417)
	at spoon.reflect.visitor.ImportScannerImpl.scan(ImportScannerImpl.java:148)
	at spoon.reflect.visitor.ImportScannerImpl.computeImports(ImportScannerImpl.java:315)
	at spoon.support.reflect.declaration.CtElementImpl.toString(CtElementImpl.java:294)
	at AnalyzerMain.analyzeImports(AnalyzerMain.java:86)
```
