### ISSUE TITLE
Cannot analyze Jar

### ISSUE THREAD

**Issue by lucacampanellaadn** [INRIA/spoon#2914]
Hi,
I'm trying to analyze a class inside a jar. I created a jar with just one class inside, just to make it as simple as possible. Nontheless seems I can't analyze the class. Here's my code:
`Launcher launcher = new Launcher();
launcher.addInputResource(pathToJar);
launcher.buildModel();
CtModel model = launcher.getModel();
List<CtClass> classes = model.getElements(new TypeFilter<>(CtClass.class));
classes.forEach(ctClass -> System.out.println(ctClass));`

The list of classes is always empty and using the debugger seems the model is not well formed.
Thanks

**Comment by surli** [comment]
Hi @lucacampanellaadn the standard launcher of spoon is meant to only analyze source code, so you need to feed it with standard .java source code files.
Now @nharrand implemented a JarLauncher that is aimed at analyzing binary files. You might find more information about it here: https://github.com/INRIA/spoon/tree/master/spoon-decompiler

**Comment by lucacampanellaadn** [comment]
Hi, thanks, I'll try it out.
I think the readme for the repo is wrong, I can't find the "spoon-decompiler" artifactId under "fr.inria.gforge.spoon", am I right?
Thanks

**Comment by surli** [comment]
I guess it has never been released on central. Right @nharrand?
Still you should be able to use the snapshot version.

**Comment by lucacampanellaadn** [comment]
Where can I find it?

**Comment by surli** [comment]
The instructions are also in https://github.com/INRIA/spoon/tree/master/spoon-decompiler on "snapshot release"

**Comment by lucacampanellaadn** [comment]
There seems to be no such file as described by the readme here: [http://maven.inria.fr/artifactory/spoon-public-snapshot](http://maven.inria.fr/artifactory/spoon-public-snapshot)

**Comment by nharrand** [comment]
> I guess it has never been released on central. Right @nharrand?

I am on it. 

Meanwhile you can just download the sources and run mvn install it.

**Comment by lucacampanellaadn** [comment]
Did it with mvn install and it works, still having it as a remote dependency would be nice. Thanks again!

**Comment by luca-campanella** [comment]
Hi guys!
I think it's still unpublished, right?

**Comment by luca-campanella** [comment]
Is something preventing you from publishing it? :)

**Comment by nharrand** [comment]
Only lazyness! But it is on my todolist!

**Comment by luca-campanella** [comment]
I know the feeling ;)

**Comment by nharrand** [comment]
Done
