### ISSUE TITLE
question: why `CtLoop#getBody()` returns `CtStatement` but `CtBlock`

### ISSUE THREAD

**Issue by 11510746** [INRIA/spoon#2921]
Other interfaces which implement `CtBodyHolder` override `CtStatement getBody()` as `CtBlock getBody()`. 

I wonder under what situation, a loop's body is not an instance of  `CtBlock`?

**Comment by tdurieux** [comment]
for example:
```java
while(true) receiver = null;
```
or
```java
while(true);
```

It is to stay retro compatible when we did not have implicit CtBlock in spoon. @monperrus do we want to keep this behavior?

**Comment by nharrand** [comment]
@tdurieux 
Actually, (may be it depends on your java settings), but both of your examples have a loop that contains a CtBlockImpl as body.

**Comment by tdurieux** [comment]
Yes now, but it was not the case before. Like I said it was to stay retro-compatible with previous spoon api

**Comment by nharrand** [comment]
Ok.

**Comment by monperrus** [comment]
Yes, now in Spoon, you always have a block on analyzed code, this greatly facilitates automated large scale transformations with insertBefore/insertAfter/etc.
