### ISSUE TITLE
bug: `try-catch` missing when `catch` body without `{ }`

### ISSUE THREAD

**Issue by 11510746** [INRIA/spoon#2922]
## Spoon version
7.3.0

## left code
```java
try (FileReader fr = new FileReader(path);
             BufferedReader br = new BufferedReader(fr)) {
     	    br.readLine();
        }catch (Exception e) 
            e.printStackTrace();
```

<img width="760" alt="1" src="https://user-images.githubusercontent.com/23020574/54682993-74758500-4b4b-11e9-9cff-794382796adb.png">

## right code
```java
try (FileReader fr = new FileReader(path);
             BufferedReader br = new BufferedReader(fr)) {
     	    br.readLine();
        }catch (Exception e) {
            e.printStackTrace();
        }
```
<img width="710" alt="2" src="https://user-images.githubusercontent.com/23020574/54683027-8d7e3600-4b4b-11e9-88d2-b26bc47d136f.png">

**Comment by tdurieux** [comment]
In which Java version, is it a valid syntax?

**Comment by 11510746** [comment]
> In which Java version, is it a valid syntax?

java 1.8

it is not a valid syntax
