### ISSUE TITLE
Find a field value runtime

### ISSUE THREAD

**Issue by NerwenElensar** [INRIA/spoon#2923]
Hey there!
I am using spoon framework to write an api to do code analysis(my bachelors thesis). I want to write a method to return a field value. While I know I can get the assignment of a declared field, it is only static. I was wondering if I can get the value in runtime? Or am I limited to static code analysis? 
I found the section about spoon as a better runtime reflection but I can't make it work and think I might have misunderstood something there. 

Thanks in advance.

**Comment by monperrus** [comment]
> While I know I can get the assignment of a declared field, it is only static

Yes, Spoon supports runtime introspection of classes, not of objects. For this, have a look at https://github.com/ronmamo/reflections https://github.com/jOOQ/jOOR
