### ISSUE TITLE
feat: CtImportKind.Unresolved

### ISSUE THREAD

**Issue by nharrand** [INRIA/spoon#2933]
I feel like this sort of problem have been raised before, so pardon me if this is just silly.

Currently when in noClassPath mode and with AutoImport, we remove all imports that we cannot resolved (`JDTImportBuilder#build()`) . Would it be possible to just create Unresolved imports (containing the original string) that could be printed later?

I know that either setting a classpath, or not using autoimport or using the SniperPrettyPrinter more or less solves this kind of issue, but I feel it still could be useful.

But maybe it creates more problem down the line, that I do not see right now.

A simpler option could be at least to log the fact that some import are simply ignored, to inform the user of other solutions.

WDYT?

**Comment by monperrus** [comment]
> Would it be possible to just create Unresolved imports (containing the original string) that could
> be printed later?
In noClassPatch, that's an excellent idea.

**Comment by monperrus** [comment]
done in #2936
