### ISSUE TITLE
package statements are missing

### ISSUE THREAD

**Issue by lzfgnu** [INRIA/spoon#2944]
I'm writing a program to format java code(variable renaming，function renaming，class renaming). the second screenshot is the input code to format, while the first screen is the output. you can see that the input contains package import statement. I want to remain those statement in the output code. Because I am just doing renaming. How can I remain those package statements ?

![Screenshot from 2019-04-12 16-26-00](https://user-images.githubusercontent.com/25069103/56023380-4a754400-5d40-11e9-8b0e-6b155858e7b5.png)
![Screenshot from 2019-04-12 16-26-36](https://user-images.githubusercontent.com/25069103/56023384-4d703480-5d40-11e9-82a0-4cd31ebc76d9.png)

` 
        Launcher launcher = new Launcher();
        launcher.addInputResource(projectPath);
        launcher.getEnvironment().setAutoImports(true);
        CtModel model = launcher.buildModel();
        model.processWith(new FieldProcessor());
        model.processWith(new FieldAccessProcessor(table));
        model.processWith(new VariableProcessor());
        model.processWith(new ParamProcessor());
        Collection<CtType<?>> types = model.getAllTypes();

        List<CtType<?>> typeList = new ArrayList<>();
        for (CtType<?> type : types) {

            String newClassName = NameTransform.transform(Type.CLASS, type.getSimpleName());
            if (!type.getSimpleName().equals(newClassName)) {
                Refactoring.changeTypeName(type, newClassName);
            }

            Set<CtMethod<?>> methods = type.getMethods();
            if (methods != null) {
                for (CtMethod<?> method : methods) {
                    String newName =
                            NameTransform.transform(Type.METHOD, method.getSimpleName());
                    if (!method.getSimpleName().equals(newName)) {
                        Refactoring.changeMethodName(method, newName);
                    }
                }
            }

            Set<CtType<?>> nestTypes = type.getNestedTypes();
            Queue<CtType<?>> nestTypesQ = new ArrayDeque<>();
            if (!nestTypes.isEmpty()) {
                nestTypesQ.addAll(nestTypes);
            }
            while (!nestTypesQ.isEmpty()) {
                CtType<?> nestType = nestTypesQ.poll();
                String newName = NameTransform.transform(Type.CLASS, nestType.getSimpleName());
                if (!nestType.getSimpleName().equals(newName)) {
                    Refactoring.changeTypeName(nestType, newName);
                }
                nestTypes = nestType.getNestedTypes();
                if (nestTypes != null) {
                    nestTypesQ.addAll(nestTypes);
                }
            }
            typeList.add(type);

        }
        for (CtType<?> type : typeList) {
            System.out.println(type);
        }
    }`

The same problem in other issue
![Screenshot from 2019-04-12 22-38-07](https://user-images.githubusercontent.com/25069103/56045451-dc4a7480-5d73-11e9-92dc-8fa89d1ccb2f.png)

**Comment by surli** [comment]
Not sure to understand the issue here. 
According to your screenshot you're talking about an "unused import statement", which means that one of the import is not used in your class. 
Basically in your example `TEST2.testT4` is not used anymore so IntelliJ informs you that this imports is useless. I guess it's related to the transformation you performed. 

So in a nutshell there's nothing wrong here.

**Comment by lzfgnu** [comment]
> Not sure to understand the issue here.
> According to your screenshot you're talking about an "unused import statement", which means that one of the import is not used in your class.
> Basically in your example `TEST2.testT4` is not used anymore so IntelliJ informs you that this imports is useless. I guess it's related to the transformation you performed.
> 
> So in a nutshell there's nothing wrong here.

I'm writing a program to format java code(variable renaming，function renaming，class renaming). the second screenshot is the input code to format, while the first screen is the output. you can see that the input contains package import statement. I want to remain those statement in the output code. Because I am just doing renaming. How can I remain those package statements ?

**Comment by surli** [comment]
The problem is that your original input contains several classes: by default, Spoon process the file to display only one class by compilation unit. 
You can change this behaviour by setting it in the environment:
```
launcher.getEnvironment().setOutputType(OutputType.COMPILATION_UNITS);
```

**Comment by lzfgnu** [comment]
> The problem is that your original input contains several classes: by default, Spoon process the file to display only one class by compilation unit.
> You can change this behaviour by setting it in the environment:
> 
> ```
> launcher.getEnvironment().setOutputType(OutputType.COMPILATION_UNITS);
> ```

Thanks for replying! I tried your method just now. but how can I get the output codes. 
`        
for (CtType<?> type : typeList) {
            System.out.println(type);
}`
the code above doesn't work.

**Comment by lzfgnu** [comment]
I saw the same problem in other issue
![Screenshot from 2019-04-12 22-38-07](https://user-images.githubusercontent.com/25069103/56045402-c50b8700-5d73-11e9-8375-0037eacdbcfe.png)

**Comment by monperrus** [comment]
See  #2945
