### ISSUE TITLE
Weird behaviour in BlueJ IDE

### ISSUE THREAD

**Issue by NerwenElensar** [INRIA/spoon#2954]
Hey there! 
I wrote my own API with the spoon framework to run some code analysis. I've written for example a method to see if a field uses the desired type which looks like that:
https://pastebin.com/ZXrKM77q

When I use this method in Eclipse IDE in my tests it works totally fine. I do something like that:
classOnwhichItshouldbetesteed.hasFieldWithType("java.util.Map");

However when I do this in the BlueJ IDE it fails. and only works if I don't use the qualified name e.g.: hasFieldWithType("Map") but I use the same implementation. The only difference I see so far is that in Eclipse named packages where in blueJ it is in unnamed packages. Is there any known issues about it?

**Comment by monperrus** [comment]
What do you mean by `it does not work`? Compilation or execution?
