### ISSUE TITLE
Matcher problem

### ISSUE THREAD

**Issue by lucacampanellaadn** [INRIA/spoon#2956]
Hi, 
I'm using Matchers to find particular expressions in my code, but one matcher is behaving strangely. This is probably my fault when writing the matcher, but I don't know where I'm doing it wrong.

I have a template matcher built from the line `subFlow(_subFlow_.S());` where `_subFlow_.S()` is declared as `TemplateParameter<FlowLogic<SignedTransaction>> _subFlow_;`

This should match the following expression:
`signedTx = ((net.corda.core.transactions.SignedTransaction) (this.subFlow(new net.cardossier.core.flow.car.CreateVinMappingFlow.CreateVinMappingInitiator(new net.cardossier.core.flow.car.CreateVinMappingFlow.CreateVinMappingInput(vin)))))`
But it doesn't.
On the other side it (rightfully) matches for example the following expression:
`net.corda.core.transactions.SignedTransaction signedTx = this.subFlow(new net.corda.core.flows.ReceiveFinalityFlow(this.otherPartySession, txId))`

What am I doing wrong? Is there a better way to write the matcher?
Thanks!
Cheers,
Luca

**Comment by monperrus** [comment]
Thanks for your bug report. Could you push a failing test case in a pull-request?

**Comment by lucacampanellaadn** [comment]
Hi!
Thanks for the answer. Digging more into the problem I realized the classes `CreateVinMappingInput` and `CreateVinMappingInitiator` were not in the spoon model. Once you put them, everything works. 
This is fine. Now the question is: is there a way to match every method `subFlow` not depending on having the argument class in the classpath or not?
Thanks again,
Cheers
Luca

**Comment by monperrus** [comment]
great!

easy analyses don't require the full classpath, more advanced ones do, by construction.

**Comment by lucacampanellaadn** [comment]
Ok, so there is no way of matching that method not having the classes in the classpath right?
