### ISSUE TITLE
question: How to print CtType with package info

### ISSUE THREAD

**Issue by 11510746** [INRIA/spoon#2958]
# Description
I modified the spoon AST ndoes and want to get the string content.

I tried `CtElementImpl#toString()` which is implemented with `DefaultJavaPrettyPrinter`. However, the package information is missing although it is stored in the spoon tree.

Is there any existing method that could print a class with its package info?

**Comment by monperrus** [comment]
Yes `toStringWithImports(), see https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/reflect/declaration/CtType.java#L111
`

**Comment by monperrus** [comment]
Could you please avoid `# Description` in your issues? Thanks!
