### ISSUE TITLE
how to avoid fully-qualifed types in pretty-printed code?

### ISSUE THREAD

**Issue by nanaker** [INRIA/spoon#2959]
Hello i'm using spoon processor to do some refactoring to my source code 
for example : add a modifier to a method 
but when i charge the class at the first time it change all the Types 
for example : String became java.lang.String 
            and SQLiteDatabase became android.database.sqlite.SQLiteDatabase
So the code is completely changed 
is there any solution to avoid this changes or to change juste what i want to change and how to save it in the file ?

**Comment by nanaker** [comment]
Also when i use 
run.getEnvironment().setAutoImports(true);

i get this error when i save the file class 
spoon.SpoonException: spoon.SpoonException: Cannot create MethodTypingContext for method declared in different ClassTypingContext

**Comment by monperrus** [comment]
thanks for your bug report. could you create a pull request with a failing test case?
