### ISSUE TITLE
Does Spoon supports bytecode analysis?

### ISSUE THREAD

**Issue by SeanCoek** [INRIA/spoon#2960]
[http://spoon.gforge.inria.fr/first_analysis_processor.html](http://spoon.gforge.inria.fr/first_analysis_processor.html)
I check out this web page and it says Spoon supports bytecode analysis at the end, but that reference link returns 404 page. So I am wondering it's possible to use Spoon to analyze bytecode files? How?

**Comment by nharrand** [comment]
Hello @SeanCoek ,
You can perform byte code analysis through decompilation. See the documentation of the [JarLauncher](http://spoon.gforge.inria.fr/launcher.html) and the module `spoon-decompiler`. The module is still quite new, so don't hesite to ask further questions if the documentation is not helpful enough. (And don't hesitate to report bug!)

**Comment by monperrus** [comment]
I'd recommend to subscribe to #675
