### ISSUE TITLE
How to modify a java file?

### ISSUE THREAD

**Issue by chenchongyu** [INRIA/spoon#2962]
I want to modify a exist Java Class.
It's like this:
`public class UserModel {
    public String userName;
}
`
And I want to add 

> @nullable

on userName.
This is my code. 
`
public class SpoonTest {

    public static void main(String[] args) {
        final SpoonAPI spoon = new Launcher();
        spoon.addInputResource("src/com/company/spoon/UserModel.java");
        spoon.run();

        Factory factory = spoon.getFactory();

        CtType<UserModel> objectCtType = factory.Type().get(UserModel.class);
        List<CtField<?>> fields = objectCtType.getFields();
        System.out.println(fields.size());

        for (CtField field : fields) {
            if (!field.hasAnnotation(Nullable.class)) {
                System.out.println(field.getSimpleName() + " does not has annotation.");
                field.addAnnotation(new CtAnnotationImpl<Nullable>());
            }

        }
    }
}

`

But It doesn't work.
I don't how to modify the java file. Please correct my mistake.

**Comment by chenchongyu** [comment]
It create a new file which has the same name and content with origin file.
I want to modify the origin file.

**Comment by monperrus** [comment]
>  I want to modify the origin file.

You can use the same argument for input and output directory.

**Comment by chenchongyu** [comment]
Thanks for reply.
I add this:

> spoon.setSourceOutputDirectory("");

But it doesn't add Nullable annotation to the UserModel.java

**Comment by chenchongyu** [comment]
> > I want to modify the origin file.
> 
> You can use the same argument for input and output directory.

Thanks for reply.
I add this:

`spoon.setSourceOutputDirectory("");`

But it doesn't add Nullable annotation to the UserModel.java

**Comment by nharrand** [comment]
Hello @chenchongyu ,
In general, when you want to create an element in spoon, you should use the factories.
If you call the method `run` and do modifiactions after, they will not be printed. (But You can write your transformations in Processor and add them to your luncher and then call `run`).

Here is your exemple with these modifications:

```java
public class AddNullable {
	public static void main(String[] args) {
		Launcher spoon = new Launcher();
		spoon.addInputResource("field/HasField.java");
		spoon.getEnvironment().setAutoImports(true);
		spoon.setSourceOutputDirectory(new File("output"));
		CtModel model = spoon.buildModel();

		Factory factory = spoon.getFactory();


		CtAnnotationType nullableAnnotation = (CtAnnotationType) factory.Type().get(Nullable.class);

		CtType hasField = model.getRootPackage().getType("HasField");
		List<CtField> fields = hasField.getFields();
		System.out.println(fields.size());

		for (CtField field : fields) {
			if (!field.hasAnnotation(Nullable.class) && !field.getType().isPrimitive()) {
				System.out.println(field.getSimpleName() + " does not has annotation.");
				CtAnnotation an = factory.createAnnotation(nullableAnnotation.getReference());
				field.addAnnotation(an);
			}
		}
		spoon.prettyprint();
	}
}
```

**Comment by chenchongyu** [comment]
> Hello @chenchongyu ,
> In general, when you want to create an element in spoon, you should use the factories. (Never call the constructor of a class `CtSomethingImpl`, but rather call `factory.createSomething(...)`)
> If you call the method `run` and do modifiactions after, they will not be printed. (But You can write your transformations in Processor and add them to your luncher and then call `run`).
> 
> Here is your exemple with these modifications:
> 
> ```java
> public class AddNullable {
> 	public static void main(String[] args) {
> 		Launcher spoon = new Launcher();
> 		spoon.addInputResource("field/HasField.java");
> 		spoon.getEnvironment().setAutoImports(true);
> 		spoon.setSourceOutputDirectory(new File("output"));
> 		CtModel model = spoon.buildModel();
> 
> 		Factory factory = spoon.getFactory();
> 
> 
> 		CtAnnotationType nullableAnnotation = (CtAnnotationType) factory.Type().get(Nullable.class);
> 
> 		CtType hasField = model.getRootPackage().getType("HasField");
> 		List<CtField> fields = hasField.getFields();
> 		System.out.println(fields.size());
> 
> 		for (CtField field : fields) {
> 			if (!field.hasAnnotation(Nullable.class) && !field.getType().isPrimitive()) {
> 				System.out.println(field.getSimpleName() + " does not has annotation.");
> 				CtAnnotation an = factory.createAnnotation(nullableAnnotation.getReference());
> 				field.addAnnotation(an);
> 			}
> 		}
> 		spoon.prettyprint();
> 	}
> }
> ```

Thanks So Much! It works for me.

**Comment by nharrand** [comment]
> Thanks So Much! It works for me.

Happy to hear it. I close the issue, don't hesitate to open new ones if you have other questions.

**Comment by monperrus** [comment]
You can also watch this repo to help other Spoon users in the future, thanks!

**Comment by chenchongyu** [comment]
> You can also watch this repo to help other Spoon users in the future, thanks!

It's  my pleasure.
