### ISSUE TITLE
How to get the type of return statement of a method?

### ISSUE THREAD

**Issue by mashalahmad** [INRIA/spoon#2964]
Hello 

Im plementing a metric where I want to get the type of "input parameters" of a method as well as the type of "return statement".

` 1	private static Set<CtType<?>> getMethodTypeSet(CtMethod<?> method){
	                    2				
	                    3		Set<CtType<?>> MethodTypeSet = new HashSet<CtType<?>>();
	                    4		List<CtParameter<?>> parameters=method.getParameters();
	                    5		for (CtParameter<?> parameter : parameters){
	                    6			CtType<?> type = (CtType<?>) parameter.getReferencedTypes();
	                    7			MethodTypeSet.add(type);
	                    8		}
	                    9		MethodTypeSet.addAll(method.getReturnType());
	                    10	
	                    11	     return MethodTypeSet;
	                    12	}  `
At the line 9 method.getReturnType() is there any way in spoon to get this?
thanks

**Comment by nharrand** [comment]
Hello @mashalahmad,

I think you are looking for `method.getType()`.

**Comment by mashalahmad** [comment]
hi thanks why spoon doc is not working?
