### ISSUE TITLE
RFC: Presentation of Spoon, based on an example

### ISSUE THREAD

**Issue by alshopov** [INRIA/spoon#2973]
Hi all,
I am Alexander Shopov. 
I have created a presentation on Spoon and will present it in [Utrecht at TEQnation 2019](https://teqnation.nl/sessions/700-tons-of-code-later-when-your-ide-will-not-cut-it-you-need-a-spoon/)
The example code is in my [Spoonerism example repo](https://github.com/alshopov/spoonerism) hosted at GitHub.
The slides to the presentation are also available as [700TonsOfCodeLater.odp](https://github.com/alshopov/spoonerism/blob/master/doc/700TonsOfCodeLater.odp) in the repos itself.
I'll be honored if I receive some feedback.

**Comment by monperrus** [comment]
Hi Alexander,

That's great. Will look at the slides.
In the meantime, what about moving spoonerism to the spoon-examples repo for maximizing sharing and
visibility?

--Martin

**Comment by alshopov** [comment]
Hi Martin,
It will be an privilege moving the examples and/or the slides to the spoon-examples - this naturally depends on Spoon's maintainers' view whether the quality of my material if good enough. From my side - code is licensed MIT, the presentation is [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/) to enable wider possible reuse. If you like the code - I will refactor it to match cass and package names in the spoon-examples repo

**Comment by monperrus** [comment]
You presentation is great!

Here are my comments https://github.com/alshopov/spoonerism/pull/1

**Comment by monperrus** [comment]
> If you like the code - I will refactor it to match cass and package names in the spoon-examples repo
Please do so!

**Comment by monperrus** [comment]
looking forward to your pull-request on spoon-examples!

**Comment by alshopov** [comment]
I have not forgotten (-:
Just too many tasks currently. But it is coming...

**Comment by monperrus** [comment]
Thanks @alshopov  for the pull-request: https://github.com/SpoonLabs/spoon-examples/pull/19
