### ISSUE TITLE
bug?: anonymous class inside a method 

### ISSUE THREAD

**Issue by nanaker** [INRIA/spoon#2974]
hello i'm trying to find the emplacement of a inner class to do some modification ( the anonymous class ) but when i'm printing the getQualifiedName of the Ctclass i'm getting this : 
net.ktnx.mobileledger.ui.profiles.ProfileDetailFragment$<unknown>

which cause a lot of bugs , and I can not locate it in the file .

Could you help me please.

here is the method :

![image](https://user-images.githubusercontent.com/21294779/57606930-e07bd480-7561-11e9-9bc2-c69a0d0bab84.png)

**Comment by nharrand** [comment]
Hello @nanaker ,
Thanks for reporting this bug. Could you post the code (both the code read by spoon, and the spoon code) to help us reproduce it? Or even better would you make a pull request with a failing test?

**Comment by nanaker** [comment]
Here is the code 
i have 2 Similar classes 

in the first i have 
.........setPositiveButton(R.string.Remove, new DialogInterface.OnClickListener() {
                @Override
                public void onClick(DialogInterface dialog, int which) {........................
in the second 
 ..................setPositiveButton(R.string.btn_send_crash_report,
                        new DialogInterface.OnClickListener() { ...........................

[code.zip](https://github.com/INRIA/spoon/files/3172424/code.zip)

![image](https://user-images.githubusercontent.com/21294779/57615387-753afe00-7573-11e9-9630-fc3c4560726d.png)

**Comment by nharrand** [comment]
If I understand this correctly, this seems to be a problem in jdt core which does not resolve Anonymous classes in lambda expression in no classpath mode. I'll investigate further, but you might be able to avoid the problem by setting up the classpath.
