### ISSUE TITLE
how to remove comments?

### ISSUE THREAD

**Issue by mounaBoudjelida** [INRIA/spoon#2976]
Hello,
I'm trying to remove a comment from a ctMethod, but it not works for me.
Here is my code, please check it.
![image](https://user-images.githubusercontent.com/20458402/57776416-5aa18a00-7717-11e9-9756-f7ddf9f45391.png)

And here is the output of the code:

comments list
[/* comment 1 test */, // Comment 2, /**
* * comment 3 *
*/, /* comment 4 */]
element before removing
 public void test_comment() {
   /* comment 1 test */
   a = (b) + (c);
   // Comment 2
   /**
    * * comment 3 *
    */
   /* comment 4 */
}
remove comment from body
 public void test_comment() {
   /* comment 1 test */
   a = (b) + (c);
   // Comment 2
   /**
    * * comment 3 *
    */
   /* comment 4 */
}
remove comment from element
 public void test_comment() {
   /* comment 1 test */
   a = (b) + (c);
   // Comment 2
   /**
    * * comment 3 *
    */
   /* comment 4 */
}
remove comment by using remove statment when there is a statement after the comment
  public void test_comment() {
   /* comment 1 test */
   a = (b) + (c);
   // Comment 2
   /**
    * * comment 3 *
    */
   /* comment 4 */
}
remove comment by using remove statment when there is no statement after the comment
 public void test_comment() {
   /* comment 1 test */
   a = (b) + (c);
   /**
    * * comment 3 *
    */
   /* comment 4 */
}
element after removing
 public void test_comment() {
   /* comment 1 test */
   a = (b) + (c);
   /**
    * * comment 3 *
    */
   /* comment 4 */
}

**Comment by monperrus** [comment]
Thanks for the bug report. What's the comment that stays while it should be gone?

**Comment by shamiul94** [comment]
Could you solve this problem? It would be helpful if you could share the solution with us.

**Comment by shamiul94** [comment]
Could you solve this problem? Share it please.

**Comment by shamiul94** [comment]
Just use this line - 
```
        launcher.getEnvironment().setCommentEnabled(false);
```
This line will ignore comments totally and you don't need to bother about them anymore.
