### ISSUE TITLE
fix #2899 does not work for shadowed String constants

### ISSUE THREAD

**Issue by mictaege** [INRIA/spoon#2977]
Upgrading from spoon 7.0.0 to 7.4.0. I faced problems that has been caused by the behavior described in the issues:

- #2891 EvalHelper#getCorrespondingRuntimeObject doesn't handle valid field references
- #2698 bug: Default expression of field of shadow type is not initialized

Both issues has been fixed with

- #2899 fix: improve getCorrespondingRuntimeObject/convertElementToRuntimeObject to handle shadow fields

but the fix does not work for String constants and I still get `"not possible to transform to expression ..."` errors.

Debugging the application I could see the following behavior:

With #2899 `EvalHelper#getCorrespondingRuntimeObject` has been extendend with this additional condition

```
if (field.getDefaultExpression() instanceof CtLiteral) {
  return ((CtLiteral) field.getDefaultExpression()).getValue();
}
```

But if the shadowed field is a String constant `getDefaultExpression()` returns `null` and therefore the `Exception` below will still be raised.

This is because the default expression has never been set in `JavaReflectionTreeBuilder#visitField(Field)`:

```
if (modifiers.contains(ModifierKind.STATIC)
    && modifiers.contains(ModifierKind.PUBLIC)
    && field.getType().isPrimitive()
    ) {
      CtLiteral<Object> defaultExpression = factory.createLiteral(field.get(null));
      ctField.setDefaultExpression(defaultExpression);
}
```

For String constants `field.getType().isPrimitive()` is not `true` and so the whole _if-condition_ turns to `false` and the _default expression_ will not be set into the `CtField`.

Changing the _if-condition_ to something like that
```
if (modifiers.contains(ModifierKind.STATIC)
    && modifiers.contains(ModifierKind.PUBLIC)
   && (field.getType().isPrimitive() || field.getType().getName().equals("java.lang.String"))
    ) {
      CtLiteral<Object> defaultExpression = factory.createLiteral(field.get(null));
      ctField.setDefaultExpression(defaultExpression);
}
```
in the debugger would make the whole condition `true` and then the default expression will be set correctly.

**Comment by monperrus** [comment]
Thanks a lot for the super detailed bug report.

It seems that the test case and the patch is super easy to write based on your extensive analysis. Would you give it a try in a pull-request? That would be awesome.

**Comment by mictaege** [comment]
Thanks a lot for for your prompt reply!

As you suggested I tried to make a pull-request to fix this issue.
