### ISSUE TITLE
Exception while running Spoon

### ISSUE THREAD

**Issue by MakroCZ** [INRIA/spoon#2979]
Hello,
I'm making small GUI controller spoon analyzer to school.
When I run Spoon (Launcher.run()) I get
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: spoon.reflect.declaration.CtCompilationUnit.getImports()Ljava/util/List;
first one from Swing Worker where I run Spoon
and
Caused by: java.lang.NoSuchMethodError: spoon.reflect.declaration.CtCompilationUnit.getImports()Ljava/util/List;
which contains Spoon DefaultJavaPrettyPrinter.calculate() at stack trace.

I have no idea why these errors are appearing so any idea will help.
If you need any source codes I will post them.

Thanks for help.

**Comment by nharrand** [comment]
Hello @MakroCZ , 
Thanks for the bug report. 
Can you upload both the sources that cause the problem when beeing analyzed and the sources required to reproduce the crash.
Or even better, you can make a pull request with a failing test case.

**Comment by MakroCZ** [comment]
I'am not able to make pull request right now, because I have my sources in private school repo and I don't want to spend much time playing with repos (deadlines) :)
But I'm uploading sources and my test files. One another processor is currently WIP, so you probably want to remove not finished code.
Just load both files and in optimalization category choose Empty catch and Not used parameter.

[Spoonalyzer.zip](https://github.com/INRIA/spoon/files/3203466/Spoonalyzer.zip)
[TestFiles.zip](https://github.com/INRIA/spoon/files/3203467/TestFiles.zip)

**Comment by nharrand** [comment]
I am sensitive to your time constraints, but it would be helpful if you could at least give two snippets like this:

```java
public class ClassBeingAnalyzed {
  public void someMethod() {}
}
```
and

```java
Launcher launcher = new Launcher();
//The options that used (in particular classPath vs NoClasspath, autoImport, etc
Launcher.run();
```

**Comment by MakroCZ** [comment]
Code calling Spoon analyze:
`
Launcher l = new Launcher();
l.addInputResource(files.get(i).getPath());
for (MyAbstractProcessor t : tests) {
     l.addProcessor(t);
}
publish(i+1);
l.run();`

and tested class:
`
public class Test {
    public Test(String test) {}

    public void error(String test2, int notUsed) {} 

}`
Tested only autoImport setting, true and false both cause error.

**Comment by nharrand** [comment]
I cannot reproduce your error as is. I assume that the error occurs when you print something modified by one of your processor. (Which definitly does not mean, that it is not a bug in Spoon) I noticed that you are using `spoon-core:7.2.0`. You might want to try with a newer version, some bugs concerning imports have been fixed since. If you can isolate the processor causing the issue, that might be helpful as well.

**Comment by MakroCZ** [comment]
It looks that problem was fixed in newer version of Spoon.
Can't reproduce with Spoon 7.5.0-beta-21.
