### ISSUE TITLE
add support for java 8 annotation element types

### ISSUE THREAD

**Issue by boeserwolf91** [INRIA/spoon#298]
A few month ago I introduced a class named [CtAnnotatedElementType](https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/reflect/declaration/CtAnnotatedElementType.java). As I implemented it Java 8 wasn't supported by spoon. Now it is supported but it seems like the [CtAnnotation#getAnnotatedElementType](https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/support/reflect/declaration/CtAnnotationImpl.java#L347-L390) method doesn't handle the two new types ```TYPE_PARAMETER``` and ```TYPE_USE```.

[Here is a link explaining these new types](https://dzone.com/articles/java-8-type-annotations)

**Comment by GerardPaligot** [comment]
Java 8 annotations are supported but not in these classes. In Java 8, you can annotated all references of a type.

So, you can find this new interface [CtTypeAnnotableReference](https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/reflect/reference/CtTypeAnnotableReference.java) which is implemented by `CtTypeReference`, `CtTypeParameterReference` and `CtArrayTypeReference`.

**Comment by boeserwolf91** [comment]
Thanks for your fast answer. I found another "bug" (at least I think it's a bug; I'll continue my investigation tomorrow). Is it possible the the new annotation types aren't processed with a processor? 

So if I create a class ```public class AnnotationProcessor extends AbstractProcessor<CtAnnotation<?>>```?

How can I observe the new annotations?

**Comment by GerardPaligot** [comment]
Unfortunately, for now, there is no simple way to do that because we can't process references.

For me, the best way would be write a new abstract processor for typed annotation (I'm working yet on a proto).
