### ISSUE TITLE
Feature: java 9/10 support for spoon-maven-plugin

### ISSUE THREAD

**Issue by djuelg** [INRIA/spoon#2983]
I made a PR to support this here:
https://github.com/SpoonLabs/spoon-maven-plugin/pull/63

While spoon is compatible to java 9 and 10 the spoon-maven-plugin is not. I made the least changes possible to make the project running again.

The plugin was building and running with java 9/10 after the changes to pom.xml and SpoonMojoGenerate.java. But testing with a real project showed that there was another issue regarding a not found directory, thus I had to make the change in AbstractSpoonConfigurationBuilder.java. That change made the build process pass and spoon did a proper job 👍

EDIT: I'm on vacation until 2019-06-21, until then I will not be able to answer.

**Comment by monperrus** [comment]
Really cool, thank you very much. Merged it.

The next step is to release on Maven Central.

**Comment by djuelg** [comment]
Hi, thanks for the quick merge!

How do i create a release on Maven Central? To prepare and perform a release build a GPG passphrase is needed. I think only maintainers can do that.

**Comment by monperrus** [comment]
You need an OSS account/token valid for the groupId, and a GPG.

You would generate your own GPG keypair and I would give you an access token through an encrypted
channel.

What do you think?

**Comment by djuelg** [comment]
Yeah, that sounds great :)

>  I would give you an access token through an encrypted channel.

In case you have telegram: My username is djuelg

**Comment by monperrus** [comment]
Just sent you a test message on Telegram. Ack?

**Comment by monperrus** [comment]
Actually, it's a better practice to register you officially.

What's your OSS Sonatype username?

**Comment by djuelg** [comment]
I don't have one. Where do I get it?

**Comment by monperrus** [comment]
I'd say https://issues.sonatype.org/secure/Signup!default.jspa

What's your login?

**Comment by djuelg** [comment]
Thank's! It's djuelg again.

**Comment by monperrus** [comment]
Sonatype does not support fine-grain release rights for artifactId, but only for groupId, see <https://issues.sonatype.org/browse/OSSRH-40889?page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel&focusedCommentId=732033#comment-732033>, so let's collect the community feedback, see #3038

**Comment by djuelg** [comment]
Thanks for the release!
