### ISSUE TITLE
Template class gets added to the import as well as its source code gets added to the output source folder

### ISSUE THREAD

**Issue by yaadyaad** [INRIA/spoon#2987]
Dear All,

I have two projects and therefore two source code folders
* gen - where the spoon-related code resides
* myapp - where the sources of a main application lives and where the generated code is being added

When generating a new class with some class template that extends ExtensionTemplate, lets say BaseLogicTemplate, an UNUSED import statement `import spoon.template.ExtensionTemplate;` gets added to the generated class.

I have another template, CustomLogicTemplate that extends BaseLogicTemplate, and when generating a class with this CustomLogicTemplate, another an UNUSED import statement `import spoon.template.BaseLogicTemplate;` gets added to the generated class. 

In addition, source code of both templates `BaseLogicTemplate` and `CustomLogicTemplate` are copied from `gen` project source code to `myapp` source code.

Here is how a Launcher gets created:

        Launcher launcher = new Launcher();
        launcher.addInputResource(mainProjectFolder + "/src/main/java");
        launcher.addTemplateResource(new FileSystemFolder("./src/main/java/gen/core/templates"));
        launcher.setSourceOutputDirectory(mainProjectFolder + "/src/main/java");
        launcher.getEnvironment().setAutoImports(true);
        launcher.getEnvironment().setCommentEnabled(true);

The code is generated with `launcher.prettyprint()` method.

Expected behaviour:
* No UNUSED import statement gets added to the generated class.
* Source code of templates should not be copied to the sourceOutputDirectory.

Can you please point me out where and how I can fix it?

I use the following version of Spoon in my gradle build file:
    compile 'fr.inria.gforge.spoon:spoon-core:7.4.0'

Thank you,
Dmitry

**Comment by monperrus** [comment]
Thanks for your report/ Imports have been reworked. Bug still present in 8.1.0?

**Comment by xsebek** [comment]
I think this is still an issue in 8.2.0<sup>[1](#rel)</sup>, but perhaps I am just using it wrong, @monperrus ?

To reproduce a small example could look like this:
```
src/main
├── java
│   └── example
│       ├── Launch.java
│       ├── StProcessor.java
│       └── StTemplate.java
└── resources
    └── Example.java
```

<details>
  <summary><code>Launch.java</code></summary>
 
```java
package example;

import spoon.*;
import spoon.support.compiler.FileSystemFile;
import spoon.support.sniper.SniperJavaPrettyPrinter;

public class Launch {
    public static void main(String[] args) {
        Launcher launcher = new Launcher();
        launcher.getEnvironment().setPrettyPrinterCreator(() ->
                new SniperJavaPrettyPrinter(launcher.getEnvironment())
        );

        launcher.addInputResource("./resources/Example.java");
        launcher.addProcessor(new StProcessor());
        launcher.addTemplateResource(new FileSystemFile("./java/example/StTemplate.java"));
        launcher.run();
    }
}
```

</details>


<details>
  <summary><code>StProcessor.java</code></summary>
 
```java
package example;

import spoon.processing.AbstractProcessor;
import spoon.reflect.code.CtAssert;

public class StProcessor extends AbstractProcessor<CtAssert> {
    public void process(CtAssert element) {
        var t = new StTemplate();
        t._asserted_ = element.getAssertExpression();
        var ifAssert = t.apply(null);
        element.replace(ifAssert);
    }
}
```

</details>

<details>
  <summary><code>StTemplate.java</code></summary>
 
```java
package example;

import spoon.reflect.code.CtExpression;
import spoon.template.Parameter;
import spoon.template.StatementTemplate;


public class StTemplate extends StatementTemplate {
    @Parameter
    public CtExpression<Boolean> _asserted_;

    public void statement() throws Throwable {
        if (_asserted_.S()) {
            assert true;
        } else {
            assert false;
        }
    }
}
```

</details>

<details>
  <summary><code>Example.java</code></summary>
 
```java
class Example {
    public void main() {
        assert 6 * 7 == 42;
    }
}
```

</details>

The quite unexpected result is this:

```
src/main/spooned
├── Example.java
└── example
    └── StTemplate.java
```

<details>
  <summary><code>Example.java</code></summary>
 
```java
class Example {
    public void main() {
		{
			{
				assert true;
			}
		}
    }
}
```

</details>

<details>
  <summary><code>StTemplate.java</code></summary>
 
```java
package example;

import spoon.reflect.code.CtExpression;
import spoon.template.Parameter;
import spoon.template.StatementTemplate;


public class StTemplate extends StatementTemplate {
    @Parameter
    public CtExpression<Boolean> _asserted_;

    public void statement() throws Throwable {
        if (_asserted_.S()) {
			{
				assert true;
			}
        } else {
			{
				assert false;
			}
        }
    }
}
```

</details>

The result I expected/hoped for is single spooned directory `example` with file `Example.java` like this:

```java
class Example {
    public void main() {
        if (6 * 7 == 42;) {
            assert true;
        } else {
            assert false;
        }
    }
}
```

Thanks a lot for your work on 🥄  and I would be very grateful if you could help me understand the usage here 🙂 
<sub>(Or is it a bug? 🐛 )</sub>

----

<a name="rel">1</a>: 8.2.0 (#3501) does not mention templates, unlike 8.1.0 (#3310)

**Comment by monperrus** [comment]
Hello! It seems you put the full directory as input resource. What happens if you put only Example.java?

**Comment by xsebek** [comment]
I think I did, with `addInputResource("./resources/Example.java");`. The result is the same with only `"./resources"` though.
If you meant the template, then that is already `FileSystemFile("./java/example/StTemplate.java")`.

**Comment by monperrus** [comment]
If you only have `addInputResource("./resources/Example.java")`, with no other call in `addInputResource`, the template code is written to the output?

If yes, that's clearly a bug.

**Comment by xsebek** [comment]
Yes, as in the example `Launch.java` above, adding InputResource, Processor and TemplateResource and then `run()` modifies the template before using it as well as adding it to the output.

Is there any way I could help with this, @monperrus ?

**Comment by monperrus** [comment]
Yes! Would you be able to create a PR with a failing test case? That 
would be super useful.
