### ISSUE TITLE
isGenerics always returns false for CtType

### ISSUE THREAD

**Issue by Egor18** [INRIA/spoon#2989]
`isGenerics()` method always returns false when called on a top-level type (even if it has generic parameters):
https://github.com/INRIA/spoon/blob/151176f4fae4d472c5bad16fc07c384ec85ca207/src/main/java/spoon/support/reflect/declaration/CtTypeImpl.java#L536-L539
I think it should be something like this instead:
```
@Override
public boolean isGenerics() {
    for (CtTypeParameter ref : formalCtTypeParameters) {
        if (ref.isGenerics()) {
            return true;
        }
    }
    return false;
}

```
Here is an example:
`class A <T> { /* ... */ }`
```
CtType<?> a = model.getAllTypes().stream().filter(t -> t.getSimpleName().equals("A")).findFirst().get();
a.isGenerics() // => false (I think it should be true)
```

WDYT?

**Comment by monperrus** [comment]
Reading again the specification of the method in the Javadoc (improved in #2990):

> isGenerics(): Returns true if it refers to a type parameter (ie not a concrete class, eg "T foo"). It can refer to it directly (eg T), or indirectly (eg List&lt;T&gt;, or Set&lt;List&lt;T&gt;&gt;).

It's pretty clear that you found a bug.

**Comment by Egor18** [comment]
Ok, I'll fix that.
