### ISSUE TITLE
auto import

### ISSUE THREAD

**Issue by mislalee** [INRIA/spoon#2996]
Hello 
i'm using auto import in my configuration to save the result of my transformation in a file  
but when it come to this instruction 
View minusButton = child.findViewById(R.id.contact_remove);

it is printed like this 
View minusButton = child.findViewById(contact_remove);
and i have an error : cannot find symbol variable contact_remove

how can i solve this ? 
with setAutoImport(true)

**Comment by nharrand** [comment]
Hello @mislalee ,
Thanks for the bug report. Can you provide a little bit more context? (Do you use NoClassPath mode or not? Can you give the full snippet that configure your Launcher (if you use a Launcher)).
Can you give the complete class processed?

**Comment by mislalee** [comment]
Hello ,
Sorry for the late reply 
here is my configuration 
![image](https://user-images.githubusercontent.com/37048417/59031259-0e9bbe00-885b-11e9-9350-5ac0d44e845c.png)

**Comment by nharrand** [comment]
And that class being analyzed? (The whole class makes it easier to reproduce the bug.)

**Comment by mislalee** [comment]
Here is an example of a file that contain 
mPreviousIcon = (ImageView) findViewById(R.id.page_button_previous_icon);

Could you please show me an example of code of how to save this file after a modification without changing the contenant of the file just the portion of code that i changed. please i really need it for my project .  

[example.txt](https://github.com/INRIA/spoon/files/3271217/example.txt)
