### ISSUE TITLE
add addProcessor(Processor) in SpoonAPI

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#300]
see http://lists.gforge.inria.fr/pipermail/spoon-discuss/2015-August/001794.html

**Comment by boeserwolf91** [comment]
I added the Processors totally different and I didn't see it as a hack (?)
See [this link](https://github.com/CubeEngine/Pericopist/blob/a8ca283b078de41cc78283d7c00a1aa7307b0444/core/src/main/java/org/cubeengine/pericopist/extractor/java/JavaMessageExtractor.java#L75-L100)
