### ISSUE TITLE
Removing Processor

### ISSUE THREAD

**Issue by Elothis** [INRIA/spoon#3004]
Hey,

I really like the visitor pattern of processors, which is why I want to use these instead of manually building the CtModel everytime and working directly with the Launcher to print the results.

But is there a way to remove a processor once it is added? I want to do certain things only once and do not want a certain processor to do its actions everytime again when `run()` is being called again later on the same launcher the Processor is already attached to. But I cannot seem to find a `removeProcessor` method of any sort.

Is there a way to make a processor only run its actions once, without executing them everytime `run` gets called on the respective Launcher?

Thanks!

**Comment by nharrand** [comment]
Hello @Elothis ,

I think the simpliest approach in your case is not to call `run()` and to run your processor separately and prettyprint (or not) once you have run everything and as many time you wanted.

```java
//Create your launcher
Launcher launcher = ...
CtModel model = launcher.getModel();

//Run the first batch of processor
model.getRootPackage().accept(myProcessor1);
model.getRootPackage().accept(myProcessor2);

//Re run the processor you want to
model.getRootPackage().accept(myProcessor1);

//Once you are done, prettyprint
launcher.prettyprint();
```

**Comment by Elothis** [comment]
Hello @nharrand ,

thanks for the reply, this sound like exactly I want to be doing!
One further question though: You wrote to call `launcher.getModel()` and not `launcher.buildModel()`. Where exactly is the difference between these 2 calls?
I think I remember getting a SpoonException of some sort with the message "Model already built" once or twice after having called `launcher.buildModel()`. Does this have something to do with it?

**Comment by Elothis** [comment]
Your comment brought me to another idea though: to look if you can simply call a processor once instead of adding it to the launcher. And it seems like there is such a solution with `model.processWith(myProcessor)`.

I will have to experiment a bit further with this, but I think this will do the exact thing you talked about via the `model.accept(Visitor v)` call I didnt seem to get to make work.

**Comment by nharrand** [comment]
You are right: to use Processors, you should use `CtModel#processWith()`. (My previous answer was unhelpful.)
And yes you should call `launcher.buildModel()` only once and then you can access the model by calling `getModel()` as many time as you want.
I am not sure why your attempts to use CtVisitor were unfruitful, but if you end have trouble with it, don't hesitate to post your code.
