### ISSUE TITLE
feat: add support for java 12

### ISSUE THREAD

**Issue by Charmik** [INRIA/spoon#3011]
Hello! I was wondering, what's current situation about java 11 (12?) ? I looked at roadmap, but it's still open. And you write only about java 10 on the main page.
I tried to parse file compiled by java 11 with var and it was okay for me.

I only need to parse source and get fields for all classes, does everything work right now for java 11? or is it still in progress? I think I am interested only about jep-323, as I understand it's not supported right now, what's the plan about it? Thanks!

**Comment by monperrus** [comment]
Hello

* for Java 11, please ask on #2106 to see if somebody makes progress.
* Renamed this issue for Java 12
* could you please discuss one single topic per issue? thanks!

**Comment by monperrus** [comment]
would you be interested in working on this yourself?

**Comment by Charmik** [comment]
I can try to look on it, but it depends on the amount of work.

**Comment by monperrus** [comment]
excellent! looking forward to it!

**Comment by Egor18** [comment]
I've just created PR to support local variable syntax for lambda parameters (jep-323) from Java 11 (#3029).

**Comment by Egor18** [comment]
Regarding Java 12, it introduced a new syntax for switch expressions (https://openjdk.java.net/jeps/325).
However, this is only a preview feature i.e. it is only available with `--enable-preview` flag and is not enabled by default.
