### ISSUE TITLE
bug(DefaultPrettyPrinter): brocken indentation for else if statments

### ISSUE THREAD

**Issue by lzfgnu** [INRIA/spoon#3012]
![1](https://user-images.githubusercontent.com/25069103/59107644-adafdb00-896b-11e9-8337-f454f5b5cfbb.png)
![2](https://user-images.githubusercontent.com/25069103/59107648-b2748f00-896b-11e9-9ef2-75556623848d.png)
![3](https://user-images.githubusercontent.com/25069103/59107787-f5366700-896b-11e9-8c0c-badc08e8aaf1.png)

**Comment by nharrand** [comment]
Hi @lzfgnu ,
Thanks for the bug report. Can you use code snippet instead of images, it makes reproduction so much easier. (Using 3 back quotes. )
```java
class T {}
```

**Comment by lzfgnu** [comment]
> Hi @lzfgnu ,
> Thanks for the bug report. Can you use code snippet instead of images, it makes reproduction so much easier. (Using 3 back quotes. )
> 
> Example:
> 
> ```java
> class T {}
> ```

Thanks for your reply. Here are my codes.

Input
```java
class T{
  public String s;
}
public class Test {
  public static void main(String[] args) {
    int a = 1;
    if (a == 1) {

    }   
    else if (a == 2) {

    }   
    else if (a == 3) {

    }   
  }
}

```

Output
```java
class T {
    public String s;
}
public class Test {
    public static void main(String[] args) {
        int a = 1;
        if (a == 1) {
        } else
            if (a == 2) {
            } else
                if (a == 3) {
                }


    }
}
```

```java
public class Test {
    public static void main(String[] args) throws Exception{
        Launcher launcher = new Launcher();
        launcher.addInputResource("/home/skymelody/Test.java");
        launcher.getEnvironment().setAutoImports(true);
        CtModel model = launcher.buildModel();
        Collection<CtType<?>> types = model.getAllTypes();
        System.out.println("--------------------------------------");
        for (CtType<?> type : types) {
            System.out.println(type);
        }
    }
}
```

**Comment by nharrand** [comment]
Thanks!
