### ISSUE TITLE
feat(BytecodeLauncher): Update JarLauncher to make it work with other bytecode packaging

### ISSUE THREAD

**Issue by nharrand** [INRIA/spoon#3015]
As reported [here](https://github.com/INRIA/spoon/issues/675#issuecomment-492213104) currently the JarLauncher may not handle anything other than jar.
This is probably for no better reason than accidental one.

**Comment by monperrus** [comment]
+1

**Comment by nharrand** [comment]
Since #3124  `DecompiledResource` can be used to handle any file the decompiler accept.
