### ISSUE TITLE
Papers about language-agnostic code agnostic and transformation

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#3016]
There is some interesting work in the area of language-agnostic code analysis and transformation. We can share pointers here, so that people who subscribe to the issue get notified.

**Comment by monperrus** [comment]
One tool, many languages: language-parametric transformation with incremental parametric syntax.
https://arxiv.org/pdf/1707.04600

**Comment by monperrus** [comment]
FYI: Lightweight Multi-Language Syntax Transformation with Parser Parser Combinators
https://www.cs.cmu.edu/~rvantond/pdfs/ppc-pldi-2019.pdf

by @rvantonder

**Comment by monperrus** [comment]
Static Code Analysis of Multilanguage Software Systems.
https://arxiv.org/abs/1906.00815

**Comment by jkoppel** [comment]
FYI, I object to the term "language agnostic." sed is language-agnostic; Cubix is language-parametric.

**Comment by monperrus** [comment]
Thanks Jim for the clarification, renamed the issue.

**Comment by monperrus** [comment]
Semantic, parsing, analyzing, and comparing source code across many languages (by @github)
https://github.com/github/semantic

**Comment by monperrus** [comment]
fAST: flattening abstract syntax trees for efficiency
https://dl.acm.org/citation.cfm?id=3339783

**Comment by monperrus** [comment]
Comby〔 Rewrite Code 〕- A tool for changing code across many languages.
https://comby.dev/
