### ISSUE TITLE
Matcher not working in case of cast

### ISSUE THREAD

**Issue by lucacampanella** [INRIA/spoon#3026]
Hi!
I have a matcher that should match all the method invocations of type `this.subFlow(...)`. In the construction of the code I have this:
```
public class MatcherContainer extends FlowLogic {

    public TemplateParameter<FlowLogic<?>> _subFlow_;

    private void subFlowMatcher() throws FlowException {
        subFlow(_subFlow_.S());
    }

    @Override
    public Object call() throws FlowException {
        return null;
    }
}
```

And from having this file in a model I compute:
```
CtMethod<?> method = (CtMethod<?>) model.getElements(
                    new NamedElementFilter(CtMethod.class, "subFlowMatcher")).get(0);
CtElement templateRoot = method.getBody().getStatement(0);
TemplateMatcher myMacther = new TemplateMatcher(templateRoot);
```

Now, if inside `CtStatement statement` I have this line:
`            SignedTransaction fullyStx = (SignedTransaction) this.subFlow(new CollectSignaturesFlow(partStx, Collections.singleton(counterpartySession)));`
Than doing
`statement.getElements(myMatcher);` 
gives an empty result.
While having the same line *without a cast* 
`SignedTransaction fullyStx = this.subFlow(new CollectSignaturesFlow(partStx, Collections.singleton(counterpartySession)));`
Correctly matches the method invocation.

Is this a bug or am I doing something wrong in the matcher?
If necessary I can create a repository to reproduce the issue.
Let me know
Thanks 
Luca

**Comment by monperrus** [comment]
Thanks for the bug report. Bug reproduced in #3028.

Would you try to debug it and propose a patch?
