### ISSUE TITLE
bug: Filtering does not recurse in anonymous classes

### ISSUE THREAD

**Issue by seintur** [INRIA/spoon#3031]
See PR https://github.com/INRIA/spoon/pull/3030 that contains a failing test case that illustrates the issue.

**Comment by Egor18** [comment]
It looks like there is a missing semicolon (so it's invalid java syntax):
`CtClass<?> c = Launcher.parseClass("class C { Object r = new Runnable() { public void run() {} }}");`
it should be:
`CtClass<?> c = Launcher.parseClass("class C { Object r = new Runnable() { public void run() {} };}");`

And the assert works fine in that case.

**Comment by seintur** [comment]
ok my mistake, sorry about that. Thanks.
