### ISSUE TITLE
Javadoc Tags @serialField and @serialData

### ISSUE THREAD

**Issue by Cyclone1337** [INRIA/spoon#3033]
I found following problem: The real javadoc tag is @serialField and @serialData, but spoon expected @serial_Field and @serial_Data. 

You can read it here:
https://docs.oracle.com/javase/7/docs/technotes/tools/windows/javadoc.html#serialField
https://docs.oracle.com/javase/7/docs/technotes/tools/windows/javadoc.html#serialData

**Comment by monperrus** [comment]
Thanks a lot for the bug report! Would you be able to submit a PR with a failing test case? That
would be super useful :-)

**Comment by Egor18** [comment]
It looks like there is a problem with `fromName` method:
```
static Type fromName(String tagName) {
	for (Type t : Type.values()) {
		if (t.keyword.toUpperCase().equals(tagName.toUpperCase())) {
			return t;
		}
	}
	return UNKNOWN;
}
```
So it makes SERIALFIELD out of @serialField and not  SERIAL_FIELD from the enum. I'll take a look.
