### ISSUE TITLE
javadoc tag exception

### ISSUE THREAD

**Issue by Cyclone1337** [INRIA/spoon#3034]
I found the following problem. If I have this two lines in my javadoc:

`@throws IllegalArgumentException if ....`
`@exception FileNotFoundException if ....`

If I call the getParam() method from the @throws tag, I get "IllegalArgumentException". That is good, but if I call the getParam() method from the @exception tag, I get null.

The getContent() from @throws is "if ...." and from @exception "FileNotFoundException if ...." 
it looks like the parameter would not be separated properly from the content

**Comment by monperrus** [comment]
Thanks for the precise bug report!

The fix is likely super easy, would you go for your first PR :-)?
