### ISSUE TITLE
Release of spoon-maven-plugin

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#3038]
(follow-up of https://github.com/INRIA/spoon/issues/2983#issuecomment-504401839)

We need to release a new version of [spoon-maven-plugin](https://github.com/SpoonLabs/spoon-maven-plugin/).

@djuelg, who has recently [contributed](https://github.com/SpoonLabs/spoon-maven-plugin/commits?author=djuelg) to spoon-maven-plugin, volunteers to make the release on Maven Central (thanks!).

Sonatype does not support fine-grain release rights for artifactId, but only for groupId, see <https://issues.sonatype.org/browse/OSSRH-40889?page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel&focusedCommentId=732033#comment-732033>

I propose to give @djuelg the right to release on `fr.inria.gforge.spoon` under the gentleman agreement that he only releases artifact `spoon-maven-plugin` and the principle ["With great power comes great responsibility"](https://en.wikipedia.org/wiki/With_great_power_comes_great_responsibility)

**Comment by surli** [comment]
Thanks @djuelg for your contribution! 
I don't want to be harsh but IMO releaser of spoon artifacts should be Spoon integrators as defined in https://github.com/INRIA/spoon/blob/master/CONTRIBUTING.md#the-integrator-code-of-conduct. 

So I'm personally not in favor of giving release rights outside this scope.

**Comment by djuelg** [comment]
Hi @surli I can understand your concerns. Even though I would have been honoured to create the release myself, it is more important for me that the release is published in the near future. 

If not me, could someone else do it instead? :)

**Comment by surli** [comment]
> If not me, could someone else do it instead? :)

I can take it, I'll try to do that in the coming days.

**Comment by monperrus** [comment]
Thanks a lot @surli

**Comment by surli** [comment]
So spoon-maven-plugin 3.2 has just been released.

**Comment by monperrus** [comment]
Thanks Simon.
