### ISSUE TITLE
createCodeSnippetExpression/Statement can only be used once.

### ISSUE THREAD

**Issue by alcides** [INRIA/spoon#304]
```factory.Code().createCodeSnippetExpression(...).compile()``` and its Statement counterpart can only be used once, even in different Processors.

I want to be able to generate two or more snippets in order to build a new AST to modify the original program. These are small things that are not enough to justify a template, but take 10-20 lines to create manually.

**Comment by GerardPaligot** [comment]
Can you give us an example or a test failed, because when I wrote this test:

```java
@Test
public void testCompileSnippetSeveralTimes() throws Exception {
	final Factory factory = TestUtils.createFactory();
	final CtCodeSnippetExpression<Object> snippet = factory.Code().createCodeSnippetExpression(
			"1 > 2");
	final CtExpression<Object> compile = snippet.compile();
	final CtCodeSnippetExpression<Object> snippet2 = factory.Code().createCodeSnippetExpression(
			"2 < 1");
	final CtExpression<Object> compile1 = snippet2.compile();
	assertTrue(compile instanceof CtBinaryOperator);
	assertTrue(compile1 instanceof CtBinaryOperator);
}
```

Everything works or I don't understand your issue.

**Comment by GerardPaligot** [comment]
It seems that their is no problem. See https://github.com/INRIA/spoon/pull/362

**Comment by alcides** [comment]
This is still an issue with 4.3 and 4.4-SNAPSHOT of today.

I am using this code:
```java
CtConditional conditional = (CtConditional) factory
.Code()
.createCodeSnippetExpression("( null == null) ? null : null").compile();
```

I added this expression to the code: It worked.

I copied and pasted it before: It stopped working. Gives:

```
java.lang.ClassCastException: spoon.support.reflect.code.CtCodeSnippetExpressionImpl cannot be cast to spoon.reflect.code.CtConditional
	at aeminium.jparcompiler.processing.TaskCreationProcessor.futurifyInvocation(TaskCreationProcessor.java:623)
```

I remove the duplicated instruction and now it does not compile and gives this error. The exact same code as before. This issue has happened to me before, with SnippetExpression and Statements.

I would guess this is some caching being done during the Snippet compilation, but I am not sure how this works exactly.

This is happening in this codebase: https://github.com/alcides/JParCompiler/commit/3561adfb2e521d5849027873c3ebe16d178a03c2, ant run would initiate the process if AeminiumRuntime and AeminiumFutures (both under http://github.com/Aeminium/) are available next to the JParCompiler project.

**Comment by GerardPaligot** [comment]
Do you have a test case which fails? I can't reproduce it.

**Comment by alcides** [comment]
https://dl.dropboxusercontent.com/u/193832/tmp/JParCompiler.zip

Sorry for being such a large project, but "ant compile" on the command line should spill the error.
(That line of code has worked before introducing other CodeSnippets).

This has happened before with other snippets in the project.

**Comment by tdurieux** [comment]
I was able to reproduce and fix the bug (see https://github.com/tdurieux/spoon/tree/fix-snippet).

The bugs were:
1. when spoon create a snippet it wraps the snippet into a wrapper class, this class was not correctly removed
2. the signature of a class is the rootPackage was not correctly performed (the signature was "class .Wrapper)

With this two bugs and depending on the state of spoon, spoon returned a snippet not compiled.

**Comment by alcides** [comment]
Thank you very much! I was so in need of this fix for years now!
