### ISSUE TITLE
Question: get the Imports

### ISSUE THREAD

**Issue by Cyclone1337** [INRIA/spoon#3044]
Hey, I have a problem with get my imports.
My testfile has the following imports:

> import java.awt.geom.IllegalPathStateException;
> import java.io.FileNotFoundException;
> import java.io.FileReader;
> import java.io.IOException;
> import java.text.ParseException;
> import java.util.IllegalFormatException;

i thought i could do this via the method "visitCtImport(CtImport ctImport)", but i don't get any import.
So i checked the CtImport documentation and found this:
> This element represents an import declaration. The given reference should be of type CtTypeReference, CtPackageReference, CtExecutableReference, CtFieldReference or CtTypeMemberWildcardImportReferenceImpl
>      import static import static org.junit.Assert.*;
>  It will be ignored in all other cases. Example:
>      import java.io.File;

So my question is now: how can i get the non-static imports?

**Comment by surli** [comment]
Hi @Cyclone1337 apparently I wrote this doc but it's clearly bad documentation :) 
CtImport concerns all imports static or not. It contains the kind of import and you can see in the [CtImportKind](https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/reflect/declaration/CtImportKind.java) that it can be static fields as well as standard type import. 

Now for the import to be computed you need to specify that you want them to be parsed: `launcher.getEnvironment().setAutoImports(true);`.

**Comment by Cyclone1337** [comment]
I use the following code:
```
Launcher launcher = new Launcher();
launcher.getEnvironment().setAutoImports(true);
launcher.addInputResource(folder.getRoot().getAbsolutePath());
CtModel model = launcher.buildModel();
```
But somehow the imports are still not found.

**Comment by surli** [comment]
> i thought i could do this via the method "visitCtImport(CtImport ctImport)",

How exactly do you call this visitor? The CtImports are attached to a CompilationUnit element in Spoon, not to a CtType, so you have to be careful to call the visitor from the appropriate elements.
You could check by calling it directly from the CtModel and check if you have any import.

**Comment by Cyclone1337** [comment]
It will be called by:
```
Launcher launcher = new Launcher();
launcher.getEnvironment().setAutoImports(true);        launcher.addInputResource(folder.getRoot().getAbsolutePath()); 
CtModel model = launcher.buildModel();

JavadocDetector javadocDetector = new JavadocDetector(revision);
//To some parameter configuration of javadocDetector
javadocDetector.scan(model);
```
My JavadocDetector is a subclass of Scanner.
And the detector contains the visit method:
```
    @Override
    public void visitCtImport(CtImport ctImport) {
        System.out.println(ctImport.getImportKind());
        System.out.println(ctImport.getReference().getDeclaration());
        System.out.println(ctImport.getReference().getSimpleName());
        super.visitCtImport(ctImport);
    }
```
The code inside is only for testing.

**Comment by msteinbeck** [comment]
Did you make sure that `folder.getRoot().getAbsolutePath()` contains the expected files?

**Comment by Cyclone1337** [comment]
`folder.getRoot().getAbsolutePath()` must contains the expected files, because the rest of my detector works. Only the imports were not found.

**Comment by Cyclone1337** [comment]
i found a solution, thanks @surli

**Comment by surli** [comment]
> i found a solution

could you explain what was the problem? Just in case someone else got the same issue in the future? Thanks.

**Comment by Cyclone1337** [comment]
My problem was, that i tried to get the imports without using the CompilationUnit.
In my solution i get the factory of the checked cttype and get the CompilationUnit from this factory.

`CompilationUnit cu = type.getFactory().CompilationUnit().getOrCreate(type);`
