### ISSUE TITLE
Create new method

### ISSUE THREAD

**Issue by Elothis** [INRIA/spoon#3051]
Hey,
I want to create a new method in an existing class with spoon. I have tried and played around with the method- and core-factory, but cannot seem to get it to work and I cannot find any example code to help me out a bit.

So how would I go about creating an empty method `public void myMethod() {}` in an existing class "TestClass"?

Any help to give me a kick start on how to go about doing this would be greatly appreciated!

Thanks a lot :)

**Comment by monperrus** [comment]
Thanks for your question.

See https://github.com/INRIA/spoon/blob/master/src/test/java/spoon/test/api/APITest.java#L303
