### ISSUE TITLE
Given a code snippet, check whether another code snippet  contains it or not? 

### ISSUE THREAD

**Issue by zqudm** [INRIA/spoon#3058]
In other words, how to check  a code snippet is  another code snippet's  descendant ? Thanks

**Comment by monperrus** [comment]
do you mean a string snippet or an AST snippet?

**Comment by zqudm** [comment]
Specifically, given a CtElement C1 and a CtElement C2,  how to whether C1 is the descendant of C2 or not.
For example,  the following code is CtTry  in  which it contains two CtIf . Just the opposite， given the second CtIf, how to check whether CtTry has the descendant that are equal to CtIf or not.
    try {
         } catch (IllegalFieldValueException ex) {
             if (monthOfYear != 2 || dayOfMonth != 29) {
                 throw ex;
             }
             instant = iGregorianChronology.getDateTimeMillis
                 (year, monthOfYear, 28,
                  hourOfDay, minuteOfHour, secondOfMinute, millisOfSecond);
             if (instant >= iCutoverMillis) {
                 throw ex;
             }
         }

**Comment by monperrus** [comment]
see #3062
