### ISSUE TITLE
New Spoon AST visualisation tool

### ISSUE THREAD

**Issue by arnobl** [INRIA/spoon#3071]
I just coded for interns of our group and students a JavaFX app for visualising the Spoon tree of Java code.
Everything is here:
https://github.com/inspectorguidget/showMeYourSpoon

Maybe this may replace the Swing app called by the `--gui` option.
Suggestions and co are welcome.

**Comment by monperrus** [comment]
Really cool! We would be happy to welcome it in the main repo! WDYT?

**Comment by arnobl** [comment]
Sure. Great honours ;)
What should I do?
- Change the licence to the Spoon's ones?
- PR to code in a new root folder `spoon-visualisation`?

It requires jdk11 however.

**Comment by monperrus** [comment]
Great! Yes, that's the perfect workflow.

**Comment by arnobl** [comment]
PR merged
