### ISSUE TITLE
question: multiple instances of Spoon using the same spoon-log file

### ISSUE THREAD

**Issue by jose** [INRIA/spoon#3073]
Hi,

The static constructor of the Launcher class [sets](https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/Launcher.java#L135) the `spoon.log.path` property to `"${java.io.tmpdir}/spoon-log.log"`.

- What's that log file for?
- Multiple instances of Spoon running on the same machine use the same log file. Would that be a problem?

--
Best,
Jose

**Comment by monperrus** [comment]
>   * What's that log file for?
>
Storing log lines of the execution.
>
>   * Multiple instances of Spoon running on the same machine use the same log file. Would that be a
>     problem?
>
I don't know. It depends on whether the Log4J class is clever enough to merge/lock log lines.
