### ISSUE TITLE
CI timeout in MavenLauncherTest

### ISSUE THREAD

**Issue by Egor18** [INRIA/spoon#3076]
Sometimes Travis CI build terminates because of the timeout in MavenLauncherTest:
```
...
[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.452 s - in spoon.test.exceptions.ExceptionTest
[INFO] Running spoon.MavenLauncherTest
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
The build has been terminated
```
I encountered this issue several times in the past (had to trigger Travis CI build several times).

Right now 2 PRs are stuck because of that:
https://github.com/INRIA/spoon/pull/3072
https://github.com/INRIA/spoon/pull/3075

Can we add `travis_wait` or disable this test for CI or do something else about it?

**Comment by monperrus** [comment]
Seems that Travis CI has fixed their problem. Do we close this one?

**Comment by Egor18** [comment]
OK
