### ISSUE TITLE
spoon-decompiler is not available in a maven repo

### ISSUE THREAD

**Issue by ElRichu** [INRIA/spoon#3078]
Hello,
I want to use SpoonClassFileTransformer in a maven project. However i can't add the spoon-decompiler dependency as explained here : 
https://github.com/INRIA/spoon/tree/master/spoon-decompiler
because spoon-decompiler does not exist on the repository : 
http://maven.inria.fr/artifactory/spoon-public-snapshot/fr/inria/gforge/spoon/

best,
Ludo, intern in diverse team.

**Comment by nharrand** [comment]
Yes, I really need to deploy it on maven central. Sorry about that.

Meanwhile you can just run `mvn install` in the spoon-decompiler directory to install it locally.

**Comment by nharrand** [comment]
Duplicate of #2914 
Related to https://issues.sonatype.org/browse/OSSRH-51861

**Comment by nharrand** [comment]
[FInally done!](https://repo1.maven.org/maven2/fr/inria/gforge/spoon/spoon-decompiler/)

**Comment by monperrus** [comment]
Thanks!
