### ISSUE TITLE
Bug: javax.transaction.Transactional annotation parameters cannot be handled correctly

### ISSUE THREAD

**Issue by Elothis** [INRIA/spoon#3079]
Hey,
I have come across a problem with the javax.transaction.Transactional - Annotation Type:
When having code like this 
```
import javax.transaction.Transactional;

@Transactional(value = Transactional.TxType.REQUIRED)
public class CourseBusiness extends AbstractBusiness {
```
and simply generating the spoon model from it and prettyprinting it back to the disk without any modifications the original code gets incorrectly changed to this
```
import Transactional.TxType;
import javax.transaction.Transactional;

@Transactional(TxType.REQUIRED)
public class CourseBusiness extends AbstractBusiness {
```
So the annotation parameter seems to get messes up and an unresolvable additional import gets added as well.

Cheers!

**Comment by Elothis** [comment]
The issue seems to be gone now for me, although I dont know why and I did not change anything related to it (I think :D). But I guess I will close this one since I cannot reproduce it anymore.

**Comment by nharrand** [comment]
Well, I was working on it, I can reproduce it. :-) I think it is mostly due to the fact that the enum type might not be properly resolved. Not sure though. I am still investigating.

**Comment by nharrand** [comment]
Ok my bad. It turns out that when the key of an annotation parameter is "value" and that is the only parameter, our default pretty printer simplies it.

**Comment by nharrand** [comment]
So this should not be a problem. (The simplification seems to be legit.)

The new import is only there because `javax.transaction.Transactional` was probably not in the classpath, so Transactional.TxType probably badly resolved.
