### ISSUE TITLE
FileNotFoundException due to additional '.' in path when saving

### ISSUE THREAD

**Issue by Elothis** [INRIA/spoon#3080]
Hello,

I have set the source output directory of my launcher to be the project path itself to use spoon as some kind of refactoring tool. So I have set it like this:
```
Environment env = launcher.getEnvironment();
env.setSourceoutputDirectory("C:/Workspace/TargetProject/src/main/java");
```

When I now generate the spoon model for the TargetProject and simply prettyprint it back without modifications, I get following errors flying for pretty much every .java-file:
`java.io.FileNotFoundException: C:\Workspace\TargetProject\src\main\java\.\com\my\package\structure\services\UserService.java (Access denied)`
And - of course - the file cannot be found because it does not exist due to the extra dot ('.') suddenly being there after the source output directory i specified (after the "\src\main\java"-part).

I have no idea how and why this dot got there. It also does not occur when I do the same with a much more simple project without the maven-like structure of having /src/main/java as the output source directory but just /src. Then no dot appears and the exceptions do not get thrown.

Does anyone have an idea why this occurs? 

Thanks alot :)

**Comment by Elothis** [comment]
The issue is gone now after coding some more on my project. Looks like it was something not related to spoon itself, so I will close this one :)

**Comment by monperrus** [comment]
Try to add a final slash after `java`:

    env.setSourceoutputDirectory("C:/Workspace/TargetProject/src/main/java/");
