### ISSUE TITLE
[doc] Last stable version 

### ISSUE THREAD

**Issue by tdurieux** [INRIA/spoon#3120]
On the website, the Maven Stable version points to the beta which does not sound really stable :)

```
<dependency>
    <groupId>fr.inria.gforge.spoon</groupId>
    <artifactId>spoon-core</artifactId>
    <version>7.6.0-beta-4</version>
</dependency>
```

**Comment by monperrus** [comment]
do you mean the badge?

**Comment by monperrus** [comment]
Fixed per https://github.com/SpoonLabs/spoon-ci-config/commit/39876a20af631938ade0dda8d9ce5b1633b27c05

**Comment by monperrus** [comment]
thanks for the bug report.
