### ISSUE TITLE
regressions after big import revamp

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#3121]
Those regressions have to be fixed:

* [x] AssertFixer
* [x] NpeFix
* [x] Casper
* [x] Nopol
* [x] gumtree-spoon-ast-diff
* [x] AssertJ regression see https://ci.inria.fr/sos/job/AssertJ/
* [x] Julia

**Comment by monperrus** [comment]
Regression in AssertFixer fixed see https://github.com/STAMP-project/AssertFixer/pull/43/files

**Comment by monperrus** [comment]
Regression in NpeFix fixed see https://ci.inria.fr/sos/job/npefix/971/

**Comment by monperrus** [comment]
Regression in Casper fixed, see https://ci.inria.fr/sos/job/casper/1035/

**Comment by monperrus** [comment]
regression in gumtree-spoon fixed see https://github.com/SpoonLabs/gumtree-spoon-ast-diff/pull/113/files

**Comment by monperrus** [comment]
regression in Nopol fixed, see https://ci.inria.fr/sos/job/nopol/618/

**Comment by nharrand** [comment]
regression in many build are now fixed thanks to #3139 
https://ci.inria.fr/sos/job/Moshi/1112/
https://ci.inria.fr/sos/job/Commons-codec/
https://ci.inria.fr/sos/job/Google%20Guice/
https://ci.inria.fr/sos/job/Guava/
https://ci.inria.fr/sos/job/Jsoup/
https://ci.inria.fr/sos/job/Jsoup/
https://ci.inria.fr/sos/job/Commons-lang/
https://ci.inria.fr/sos/job/Bukkit/
https://ci.inria.fr/sos/job/Joda%20Time/
https://ci.inria.fr/sos/job/RxJava/

**Comment by monperrus** [comment]
AssertJ regression fixed, see https://ci.inria.fr/sos/job/AssertJ/1118/

**Comment by monperrus** [comment]
next on the list is @seintur's juliac

**Comment by seintur** [comment]
Boys, you definitively made some progress! Congrats!

One more (last?) NPE to fix in juliac. Visit https://ci.inria.fr/sos/job/juliac/1095/consoleText search for the 2nd occurrence of "Tinfi Example HelloWorld Ultra-Merge" and you will see a stack trace with a NPE at spoon.support.compiler.jdt.ParentExiter.visitCtBlock(ParentExiter.java:442)

If this does not speak, I'll try to circumvent the bug to a smaller, more intelligible, case.

Tx.

**Comment by seintur** [comment]
Juliac is now back to stable https://ci.inria.fr/sos/job/juliac/changes (I have commited the needed changes to take into account the revamp).

**Comment by monperrus** [comment]
Cool, thanks Lionel!

Could you give a link to the commit? I'd like to see the diff and understand the
backward-incompatible change.

**Comment by seintur** [comment]
Hi @monperrus 

https://gitlab.ow2.org/fractal/juliac/commit/b667b280017a439e75dad164781057ea27d77f84

AFAIK a change in the contract of CTExecutable.toString().
