### ISSUE TITLE
Is automated release still working?

### ISSUE THREAD

**Issue by nharrand** [INRIA/spoon#3142]
From https://repo1.maven.org/maven2/fr/inria/gforge/spoon/spoon-core/ as far as I can tell a beta used to be release every week, but the last one is from 2019-08-17 08:43. Is there something wrong with the automated release process? 
@monperrus ?

**Comment by monperrus** [comment]
Indeed, something is broken in the deploy script: https://travis-ci.org/SpoonLabs/spoon-deploy/branches

**Comment by nharrand** [comment]
Thanks for the pointer. See https://github.com/SpoonLabs/spoon-deploy/pull/1 for a proposed fix.

**Comment by monperrus** [comment]
Fixed: https://travis-ci.org/SpoonLabs/spoon-deploy/builds/603153319
