### ISSUE TITLE
Usage of createVariableRead instead of createVariableWrite

### ISSUE THREAD

**Issue by maakbay** [INRIA/spoon#3155]
in spoon/reflect/factory/CodeFactory.java:

`public <A, T extends A> CtAssignment<A, T> createVariableAssignment(CtVariableReference<A> variable, boolean isStatic, CtExpression<T> expression)`

This method uses `createVariableRead(variable, isStatic)` instead of `createVariableWrite(variable, isStatic)`. It produces bugs on code analysis and manipulations. 

Please fix it.

**Comment by monperrus** [comment]
Thanks for the report. Would you make a pull request? That would be great!

**Comment by maakbay** [comment]
Okay, i will try to implement my solution into Factory. Is it right way to do?

**Comment by monperrus** [comment]
closed per #3157

**Comment by monperrus** [comment]
Thanks a lot for the bug report and the fix!
