### ISSUE TITLE
governance: add spdx data in license header

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#3158]
For automatic license identification, it is a best practice to have a machine processable field `spdx-license-identifier` in source files

https://github.com/search?l=Java&q=spdx-license-identifier&type=Code

* We can add this in our source files.
* We can add a check in CI that it is indeed there with an acceptable value.

**Comment by surli** [comment]
> We can add a check in CI that it is indeed there with an acceptable value.

Not sure it's needed: we already have a license check in our mvn build, cf: https://github.com/INRIA/spoon/blob/master/spoon-pom/pom.xml#L272

>  it is a best practice to have a machine processable field spdx-license-identifier in source files

first time I heard about that, sounds interesting do you have some pointers?

**Comment by monperrus** [comment]
https://spdx.org/

People who are careful with intellectual property (foundations such Eclipse, companies using open-source) love that, it makes their analyses easier and their results more reliable.

**Comment by monperrus** [comment]
@MartinWitt 

Reference from https://wiki.spdx.org/view/SPDX_FAQ:

> How does one represent a file or package that is dual licensed (i.e., a license choice)?
>    SPDX license information can be represented using conjunctive or disjunctive regular expressions. For example, a file that is dual licensed under either the GPL-2.0 or MIT would be represented using the following disjunctive expression: (GPL-2.0 or MIT).


* I assume "or" should be lower-case
* Are the parentheses mandatory?

**Comment by MartinWitt** [comment]
looking at [spdx-spec](https://spdx.org/sites/cpstandard/files/pages/files/spdxversion2.1.pdf). Appendix V: Using SPDX short identifiers in Source Files and Appendix IV:  SPDX License Expressions
, I would say parentheses are kinda mandatory and the `or` must be upper case. I would add parentheses even if the are not mandatory

> For the Tag:value format, any license expression that consists of more than one license identifier and/or LicenseRef, should be encapsulated by parentheses: "( )".

> If presented with a choice between two or more licenses, use the disjunctive binary "OR" operator to
> construct a new lincense expression, where both the left and right operands are valid license expression
> values.
> For example, when given a choice between the LGPL­2.1 or MIT licenses, a valid expression would be:
> (LGPL­2.1 OR MIT)

**Comment by stone-wall** [comment]
Martin is right OR should be uppercase. I don't think that parentheses are mandatory as they are not used in the examples from https://spdx.org/ids :

> // SPDX-License-Identifier: MIT
> /* SPDX-License-Identifier: MIT OR Apache-2.0 */
> # SPDX-License-Identifier: GPL-2.0-or-later

**Comment by stone-wall** [comment]
From looking at the examples of real usages page on SPDX, it looks like it is added as the very first line to every file. see https://spdx.org/ids-where
Also, at the bottom of that page they suggest to contact them if you use SPDX to be added to the list ;) 
Maybe could even make a spoon processor that adds SPDX info to other Java programs that want to start using SPDX

**Comment by MartinWitt** [comment]
after reading [linux kernel](https://lwn.net/Articles/739183/), i read some interesting point. Somebody with knowledge about licenses want to comment about the idea removing the hugh text and replace it with SPDX only?

> An additional goal is to eventually get rid of the other license texts; the consensus seems to be that the SPDX identifier is a sufficient declaration of the license on its own.

**Comment by monperrus** [comment]
> comment about the idea removing the hugh text and replace it with SPDX only?

Unless we find an authoritative reference advocating to do so, I prefer to keep text + SPDX, it's more explicit.

**Comment by MartinWitt** [comment]
Somebody wants to do this?
> Also, at the bottom of that page they suggest to contact them if you use SPDX to be added to the list ;)
