### ISSUE TITLE
bug: fully-qualified names in sniper mode

### ISSUE THREAD

**Issue by moraispgsi** [INRIA/spoon#3176]
I am trying to refactor a small project, all I do is add recycle calls to leaking resources. This particular source file after refactoring caught my attention because it displays a number of problems. Here is the diff: https://www.diffchecker.com/3yqrjgzY

We can see the inline packages that it unnecessarily adds, also in the exceptions catch clauses the variable name 'e' is suffixed with the exception class name ```java.io.FileNotFoundExceptione```. Also around line 600, notice how many parentheses were added to the argument.

Environment:
- With classpath android jars provided.
- SniperJavaPrettyPrinter
- setAutoImports gives the same result whether it is set to true or false
- It happens on files that did not suffer any mutation as well so the refactoring applied is not the cause.

**Comment by moraispgsi** [comment]
https://www.diffchecker.com/3yqrjgzY

**Comment by moraispgsi** [comment]
I need to get this fixed somehow, anyone available to help me out?

**Comment by monperrus** [comment]
Hi Ricardo, we'd be happy to look at this, could you create a pull request with a failing test case? Thanks!
