### ISSUE TITLE
Support definitions across modules

### ISSUE THREAD

**Issue by chrismwendt** [INRIA/spoon#3178]
Does Spoon support `.getDeclaration()` across modules within the same project?

It seems like it doesn't. See the motivating issue comment https://github.com/sourcegraph/lsif-java/issues/6#issuecomment-557749671

(related issue https://github.com/INRIA/spoon/issues/2770 describes a different problem with multiple module projects: duplicate classes in different modules cause errors)

**Comment by monperrus** [comment]
Hi Chris,

> Does Spoon support `.getDeclaration()` across modules within the same project?

Do you mean Maven modules?

In theory this is supported. Can you isolate a failing test case?

**Comment by chrismwendt** [comment]
> Do you mean Maven modules?

Yes.

> In theory this is supported.

Good to know, thanks!

> Can you isolate a failing test case?

I'll close this until I have a minimal repro. I suspect that Maven modules are breaking `.getDeclaration()` in a project, but I could be mistaken. There could be something else preventing it from working.

**Comment by monperrus** [comment]
OK, thanks
