### ISSUE TITLE
Is it possible to get the source content of a symbol's definition?

### ISSUE THREAD

**Issue by jdneo** [INRIA/spoon#3190]
Sorry I'm recently play with Spoon so I'm not quite sure if this is possible or not.

What I want to achieve is, for example:

``` java
String test = "test"
```

Is it possible to get the source of the class `String` and also point out the position of the definition of `String` in that source?

Thanks.

**Comment by monperrus** [comment]
Hi Sheng.

Yes it is possible to get the source, if the source is in the source classpath (say mypack.Foo). If
the class definition is only binary (such as for `java.lang.String`), you can get an approximation
of the source with decompilation of the binary class (see module spoon-decompiler).

**Comment by jdneo** [comment]
Thank you @monperrus
