### ISSUE TITLE
Is there a possibility to move to CeCILL-B License

### ISSUE THREAD

**Issue by sirinath** [INRIA/spoon#321]

**Comment by boeserwolf91** [comment]
What is the big difference? Why do you need the change of the license? This information could help the decision and make it easier to grant/decline the request.

**Comment by sirinath** [comment]
This will enable to modify and use in libraries under other license. Current license will only allow it to be used as a library.

**Comment by seintur** [comment]
Can you give some concrete examples of projects where you want to use Spoon with a different license?

**Comment by sirinath** [comment]
Source is not relased but will be hosted here: https://github.com/orgs/JvmTrader/. We might not need whole of Spoon so want to explore what parts we can borrow. We are exploring only packages which will allow the flexibility to change the license.

**Comment by boeserwolf91** [comment]
So if I got it in a right way, you don't want to use the whole Spoon project as a dependency, but you want to use some classes of Spoon directly by copying (and maybe modfiying) them into your project. I see. 
okay I'm out and can't help. The Inria people have to decide it.

**Comment by sirinath** [comment]
Yes.

**Comment by pschichtel** [comment]
To me that sounds more like not the license is the problem, but the fact that the single monolithic jar of spoon contains more than you need.
The better solution for that would be to split out certain parts as optional modules.

**Comment by monperrus** [comment]
This is an interesting question. @sirinath you confirm that your use case is to use the source code of some classes of Spoon by copying (and maybe modfiying) them into your project?

**Comment by sirinath** [comment]
I want to learn from the source and if needed copy or reuse fragments or snippets of code.

**Comment by monperrus** [comment]
Cecill-C enables you:

- to learn from the source
- to reuse fragments as long as those fragments and the modifications on them remain under Cecill-C

A dual license with Cecill-B is not an option for a number of reasons.

Best regards,

--Martin

**Comment by monperrus** [comment]
FYI Spoon is now dual-licensed MIT & Cecill-C, see #2950
