### ISSUE TITLE
Spoon documentation

### ISSUE THREAD

**Issue by GerardPaligot** [INRIA/spoon#322]
After a survey at the community, a lot of contributors/users asked a real documentation of the usage of Spoon. The goal of this issue is to talk about this documentation. What do you want in it? What seem important for you? Which structure do you want? etc.

For a first version, we think to aggregate this [scientific paper of Spoon](https://hal.inria.fr/hal-01078532), the [FAQ](http://spoon.gforge.inria.fr/Doc/FAQ/) and some information that we can find in `package.html` files in the project.

What do you think about that?

**Comment by monperrus** [comment]
we can add a section about the new path API

**Comment by pschichtel** [comment]
Maybe take a few example use cases and provide a "walk through"

**Comment by alcides** [comment]
I would like an explanation of the factory classes (Core, Code, etc..). It was hard to understand how to manually create an AST.

And I believe examples of how to modify an AST with new nodes is important, because not everything can be done using the Substitutions API.

**Comment by GerardPaligot** [comment]
Hi everyone,

Yesterday, we have updated the [website of Spoon](http://spoon.gforge.inria.fr/) to include the documentation in a near future!

we also thought about a plan for this documentation:

1. Getting Started

  1.1. Introduction
  1.2. First Processor
  1.3. First transformation
2. Usage

  2.1. Command Line
  2.2. Maven
  2.3. Gradle
3. Spoon Meta Model

  3.1. Elements
  3.2. Code elements
  3.3. References
  3.4. How to create an AST?
  3.5. How to modify an AST?
4. Quering source code elements

  4.1. Filter
  4.2. Path
5. Processing source code elements

  5.1. Processor for elements
  5.2. Processor for annotations
6. Templating source code

  6.1. Template definition
  6.2. Template instantiation
  6.3. Template substitution
  6.4. Literal template parameters

I think we have all ideas of the community in this plan but if you have new idea to integrate at this plan, we are always open to integrate them!

**Comment by pschichtel** [comment]
maybe reference some open source projects using spoon? I personally like to learn about libraries through existing projects.

**Comment by GerardPaligot** [comment]
@pschichtel For that, we have [this page](http://spoon.gforge.inria.fr/ecosystem.html).

**Comment by pschichtel** [comment]
Oh missed that one, fine then

**Comment by GerardPaligot** [comment]
yay! Documentation is already available on the [spoon website](http://spoon.gforge.inria.fr/)!
