### ISSUE TITLE
perfomance/API question

### ISSUE THREAD

**Issue by Charmik** [INRIA/spoon#3226]
Hello! I want to parse many files from my disk (.java) and get AST of these classes. 
My current code is simple:
```
Path source = ...;
final Launcher launcher = new Launcher();
launcher.addInputResource(source.toAbsolutePath().toString());
launcher.buildModel();
```
and I do it for many files (hundreds or thousands). It works pretty slow, because JDT does something strange. It parses file of course, but it iterates over classPath and tries to do something with jars (I suppose it parses default class-path with JDK classes or something like this). And It does it for every file, it's pretty slow. I tried to do:
```
final Environment env = launcher.getEnvironment();
env.setSourceClasspath(new String[0]);
env.setNoClasspath(true);
env.checksAreSkipped();
```
but it doesn't help in any way. 
Flamegraph: (github doesn't support .svg, so I attached picture of svg).

<img width="1205" alt="Screenshot 2020-02-03 at 4 32 22 PM" src="https://user-images.githubusercontent.com/4145681/73657194-d2975200-46a2-11ea-874f-5f214afb903c.png">

I tried another approach: take all files and then parse them all together:
```
for (final Path source : sources) {
            launcher.addInputResource(source.toAbsolutePath().toString());
}
launcher.buildModel();
```

It works much better, because it iterates over class-path only once. But I have a problem: I can't guarantee that .java files are valid. There are can be files from decompiler which spoon can't parse. So my question here is: if I parse all files together, how can I repeat my API from first example? That I get Path to the file and I need one thing: get AST of this file, or get an exception if spoon can't parse it. 
I except something like this: 
```
Model model = buildModel(from all files); 
model.getResult(Path path); // AST or exception for specific file.
```

but as I understand if 1 file from 100 is not parsed then I will get exception in `buildModel` method. 

```
model.filterChildren(f -> f.getPath().equals(path))
```
is it the right way?
Thank you!

**Comment by tdurieux** [comment]
Not sure to completely understand the question but if you are in noclasspath mode you can get the compilation problems from the JDTBasedSpoonCompiler class: https://github.com/INRIA/spoon/blob/99775fcf4e51ef73c80e2ef04edd6131615885e2/src/main/java/spoon/support/compiler/jdt/JDTBasedSpoonCompiler.java#L639

it should be something like this
```java
((JDTBasedSpoonCompiler) getModelBuilder()).getProblems()
```
