### ISSUE TITLE
Windows builder in our Jenkins

### ISSUE THREAD

**Issue by GerardPaligot** [INRIA/spoon#324]
To avoid this kind of [PR](https://github.com/INRIA/spoon/pull/310), we should have a windows builder in our Jenkins. This builder will compile the latest version of Spoon and report us any problems on Windows systems.

**Comment by boeserwolf91** [comment]
:+1: I would like to have this. (rather I would like that you have this :smile:)

**Comment by pschichtel** [comment]
I thought about adding a windows slave to my Jenkins instance and building Spoon on there

**Comment by boeserwolf91** [comment]
@pschichtel yes, please. The current merge request #394 shows that this is needed. The jenkins should create an issue directly :+1:

**Comment by GerardPaligot** [comment]
@boeserwolf91 @pschichtel Happy to announce that now, Spoon uses [AppVeyor](http://www.appveyor.com/)! :)

**Comment by boeserwolf91** [comment]
This is a good news. Thank you.
