### ISSUE TITLE
Cannot access child module POM information from SpoonPom

### ISSUE THREAD

**Issue by scootafew** [INRIA/spoon#3262]
I've been using the `MavenLauncher` class to analyse multi (maven) module projects, but only the top level `SpoonPom` is exposed. The field `modules` on `SpoonPom` is package-private and I would like to suggest adding a getter to allow retrieval of child module POM information (artifactId, version etc.).

Is there any reason why this would be undesirable?

**Comment by nharrand** [comment]
> Is there any reason why this would be undesirable?
No, it is welcome.
Although, we still don't support multi module. In a perfect world, we would support accessing the sources from all modules.
