### ISSUE TITLE
Duplicate imports

### ISSUE THREAD

**Issue by moraispgsi** [INRIA/spoon#3267]
When running a test that previously passed with the latest commits on master I get duplicate imports. 
![image](https://user-images.githubusercontent.com/12514975/75094840-b3476280-5586-11ea-8e2d-dc1e5f274207.png)

**Comment by monperrus** [comment]
do you have a failing test case?

**Comment by moraispgsi** [comment]
Sorry Martin, lately I haven't had the time to create it. I can assure you this is a problem worth looking at. It happens after a refactoring rule is applied, to it involves some kind of modification.
