### ISSUE TITLE
Fully qualified names problem in Sniper pretty printer

### ISSUE THREAD

**Issue by moraispgsi** [INRIA/spoon#3268]
After the latest changes to master it is adding fully qualified names when originally there weren't.
![image](https://user-images.githubusercontent.com/12514975/75094953-ba22a500-5587-11ea-8591-6c1a2b6f260c.png)

**Comment by monperrus** [comment]
Thanks for the bug report, a failing test case would help very much :-)

**Comment by monperrus** [comment]
Probably fixed in master

**Comment by monperrus** [comment]
Re-opening, this bug is still there, it has happened with Sorald on https://github.com/AddstarMC/Prism-Bukkit/pull/248/files

**Comment by monperrus** [comment]
@slarse 's #3372 was related to this

**Comment by monperrus** [comment]
@slarse thinks that this happens mostly in noclasspath mode, if you hit this problem, try the full classpath mode, incl. the Maven mode.

**Comment by slarse** [comment]
I'm putting this on my TODO list.

> https://github.com/AddstarMC/Prism-Bukkit/pull/248/files

I think this is specifically related to it being in a catch clause, as was the case with #3372.

**Comment by slarse** [comment]
I've opened a new issue for this (#3799), it seems like an isolated issue for catch clauses in that the package for the exception type isn't marked implicit.

@monperrus you can close this issue again.

**Comment by monperrus** [comment]
Superseded by #3799
