### ISSUE TITLE
CtConstructor equals comparison fails

### ISSUE THREAD

**Issue by shoeoffhead** [INRIA/spoon#3273]
Hi,

I just tracked down a nasty bug, where I compare CtExecutable instances with each other. The two different constructors listed below will compares as equal:

execTypeMember.equals(constructor) -> uses CtElementImpl.equal under the hood and returns true. It uses boolean ret = EqualsVisitor.equals(this, (CtElement) o) to do the equality check. Is it supposed to return true? The two constructors have the same argument list. However this are two different constructors from two different classes!

`protected LinkMapIterator(final org.apache.commons.collections4.map.AbstractLinkedMap<K, V> parent) {
    super(parent);
}`

`protected EntrySetIterator(final org.apache.commons.collections4.map.AbstractLinkedMap<K, V> parent) {
    super(parent);
}`

**Comment by shoeoffhead** [comment]
Should I just do an identity check to get true equality?

execTypeMember == constructor instead of execTypeMember.equals(constructor) ?

If there can only be one instance of the constructor in the Model an identity check could work. If there could however be more then one instance of the same CtExecutable an identity check could result in a similar nasty bug in my code later on or even go unnoticed.

**Comment by monperrus** [comment]
Thanks for the report, it's maybe a bug,

Could you propose a pull-request with a failing test case showing the bug?

Thanks!

**Comment by shoeoffhead** [comment]
Sorry...I am not into the whole Git or Github thing or testing.

**Comment by monperrus** [comment]
great opportunity to learn :-)

**Comment by shoeoffhead** [comment]
Maybe for the next bug ;)

**Comment by monperrus** [comment]
This would be a breaking behavioral change, see #3313

> However this are two different constructors from two different classes!

This is questionable. The code of the constructor, incl. body modifiers and arguments is strictly the same. To some extent, it's the same constructor.

Could you tell more about your use case?

**Comment by monperrus** [comment]
Per #3313 this is a WONTFIX. Thanks for the report!
