### ISSUE TITLE
Is it possible to create CtElements on the fly?

### ISSUE THREAD

**Issue by lsafina** [INRIA/spoon#3274]
Hello,
Could you please tell me, Is it possible to create CtElements on the fly? For example, I want to create and alternate different CtUnaryOperator and CtBinaryOperator. 
I tried to do it by using the DefaultCoreFactory class:

`val unaryOperator = DefaultCoreFactory().createUnaryOperator<Boolean>()
   unaryOperator.setKind<CtUnaryOperator<*>>(UnaryOperatorKind.NOT)
   unaryOperator.setOperand<CtUnaryOperator<*>>(guard)` 

(which does not work for me, since I can not provide a not-nullable factory)
and directly:

`val guard = CtBinaryOperatorImpl<Boolean>()
  guard.setKind<CtBinaryOperator<Boolean>>(BinaryOperatorKind.EQ)`

which was even worse.
Is there a good way to do it?

**Comment by MartinWitt** [comment]
Maybe some code helps more a bit more then writing a lot of  text. You can get a Factory from the launcher calling simply launcher.getFactory(). In the example below, the programm swaps all CtBinarayOperators. ( Sry for the "inline" style, it can be solved much cleaner using visitor)

```java 
import spoon.support.compiler.VirtualFile;


public class Foo {

	private static final String dummyClass = "public class Bar{ public void foo(){int x = 3 + 4;}}";

	public static void main(String[] args) {
		// create a simple Launcher
		Launcher launcher = new Launcher();
		// create a virtual File because testing example
		SpoonResource file = new VirtualFile(dummyClass);
		// add it like a normal source
		launcher.addInputResource(file);
		// generate model
		CtModel model = launcher.buildModel();
		// get all binaray expressions expressions
		// TypeFilter is useable for all CtElements see doc for more info.
		Collection<CtBinaryOperator<?>> col = model
				.getElements(new TypeFilter<CtBinaryOperator<?>>(CtBinaryOperator.class));
		// print all binaray operators before swap here only : 3 +4
		col.forEach(System.out::println);
		// now swap all
		col.forEach(v -> swapOperants(v, launcher.getFactory()));
		// proof that model is changed: prints 4+3
		model.getElements(new TypeFilter<CtBinaryOperator<?>>(CtBinaryOperator.class)).forEach(System.out::println);

	}

	/**
	 * the factory allows creation CtElements. You can get one from the launcher
	 * with launcher.getFactory()
	 */
	private static void swapOperants(CtBinaryOperator<?> input, Factory factory) {
		// swap left and right, but keep kind of operator
		CtBinaryOperator<?> swapped = factory.createBinaryOperator(input.getRightHandOperand(),
				input.getLeftHandOperand(), input.getKind());
		// replace in code with new one
		input.replace(swapped);
	}
}
```

**Comment by lsafina** [comment]
Thank you very much for explanation! I didn't get from the beginning that already created factory can be used.
