### ISSUE TITLE
The behavior of CI has changed (MavenLauncherTest  is broken)

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#3289]
The behavior of MavenLauncherTest has changed on Travis CI.

See all failures on ongoing PRs.

```
[ERROR]   MavenLauncherTest.mavenLauncherTestMultiModulesAndVariables:204 Content of classpath: 

[ERROR]   MavenLauncherTest.multiModulesProjectTest:126 expected:<166> but was:<17>
```

Why? How to fix that?

**Comment by MartinWitt** [comment]
With the configuration below i cant reproduce the bug. Could be a unix problem?

Maven home: C:\Program Files\apache-maven-3.6.1\bin\..
Java version: 11.0.2, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk-11.0.1
Default locale: de_DE, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
openjdk 11.0.2 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)

**Comment by monperrus** [comment]
Something has changed on the Travis side.

**Comment by monperrus** [comment]
I checked the Travis configuration difference when this problem first happened (difference between 363 and 363 at https://travis-ci.org/SpoonLabs/spoon-ci-external/builds)

The Travis configuration is the same.

**Comment by monperrus** [comment]
Since We have no idea on what the cause of this is, and how to fix it properly, we'll change the expected values so that we can proceed with merging the pending PRs.

**Comment by monperrus** [comment]
Interesting: `mavenLauncherTestMultiModulesAndVariables` says "we cannot guarantee that the dependency is present in .m2 cache and the test might fail". The reason may be the Travis CI cache (lost? corrupted?). I'm investigating this.

**Comment by monperrus** [comment]
This indeed was the reason. #3298 is a fix.
