### ISSUE TITLE
spoon-maven-plugin: how to access the target ClassLoader?

### ISSUE THREAD

**Issue by vmassol** [INRIA/spoon#3291]
Hi, I have written a custom Spoon Processor in which I need to access the maven ClassLoader for the module being built. 

I do this:

```
Enumeration<URL> urls = Thread.currentThread().getContextClassLoader().getResources(COMPONENTS_TXT_LOCATION);
```

And I can see that the CL is not the correct one. There isn't all the dependencies from project into which the spoon maven plugin is executing.

I've also tried:

```
Enumeration<URL> urls = environment.getInputClassLoader().getResources(COMPONENTS_TXT_LOCATION);
```

But same result.

Would you know how I can access that CL?

Thanks a lot

**Comment by monperrus** [comment]
In spoon-maven-plugin, there is some hairy code to get the classloader info.

* https://github.com/SpoonLabs/spoon-maven-plugin/blob/7d75eb3/src/main/java/fr/inria/gforge/spoon/SpoonMojoGenerate.java#L267
* https://github.com/SpoonLabs/spoon-maven-plugin/blob/master/src/main/java/fr/inria/gforge/spoon/util/ClasspathHacker.java

What about using `ClassLoader.getSystemClassLoader()`?

**Comment by vmassol** [comment]
> What about using ClassLoader.getSystemClassLoader()?

Doesn't work; It returns the plexus classworld CL which doesn't contain the project's dependencies.

**Comment by vmassol** [comment]
Also note that when I try `ctClass.getActualClass()` I get an exception `Method threw 'spoon.support.SpoonClassNotFoundException' exception.`. I was hoping to get the Class and then get its classloader....

**Comment by vmassol** [comment]
Actually, I think I'm wrong :) I think it's working fine. Doing more tests and I'll close this issue. Thanks and sorry for the false alarm.

**Comment by vmassol** [comment]
Actually I was wrong. I do have the module dependency JARs in the context CL. It's just missing one URL/path, which is the one for the current module, i.e. the URL to the target/classes directory.

**Comment by vmassol** [comment]
I've found a way of implementing my code without the need for the CL. I still don't know the answer but I don't need it FTM ;) Thanks!

**Comment by monperrus** [comment]
Cool! Dealing with ClassLoader is always a nightmare.
