### ISSUE TITLE
Unexpected behavior when doing ctInvocation.getArguments().indexOf(object).

### ISSUE THREAD

**Issue by fermadeiral** [INRIA/spoon#3299]
Hi,

I'm writing this issue just because I believe I have found a bug (I already have a workaround for my specific project, thus I don't need further support or clarification, this is just a bug report issue).

I have the following method call: `longMethod(1 + 2, 1 + 2);`. Note that both arguments are binary operators, and both are also the same expression. I have an object, of the type `CtBinaryOperator`, which holds the object of the second method call argument, named `ctBinaryOperatorArg2`. I want to find its index in the method call, thus I do `int indexArg2InInvocation = ctInvocation.getArguments().indexOf(ctBinaryOperatorArg2);`. While I expected this would return "1", this returns "0". If my method call does not contain the same expression in both arguments, let's say `longMethod(1 + 2, 3 + 4);`, everything works fine, thus I believe that the issue with the original method call is due to the fact that both argument objects have the same `.toString()` output or something like this.

Cheers,
Fernanda

**Comment by monperrus** [comment]
This is normal.

The reason is that List.indexOf in Java is based on `.equals()` equality, not on object sameness.

**Comment by fermadeiral** [comment]
> This is normal.

Oh, ok. In that case, issue closed.
