### ISSUE TITLE
finergit export of spoon

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#3309]
Hi all,

I've created a fine-grained export of spoon using @YoshikiHigo's  [Finergit](https://github.com/kusumotolab/FinerGit).

Finergit enables us to have the history of a single method, for example:

* [History of Launche#JSAP_defineArgs()](https://github.com/monperrus/spoon-finergit/commits/master/src/main/java/spoon/Launcher%23protected_JSAP_defineArgs().mjava)
* [History of testTest()](https://github.com/monperrus/spoon-finergit/commits/master/src/test/java/spoon/test/main/MainTest%23public_void_testTest().mjava)

The full export is at https://github.com/monperrus/spoon-finergit

WDYT?

**Comment by MartinWitt** [comment]
After having a first look, i cant see the target audience for this.
For a developer it's something your IDE provides you (hopefully), for a user you have no(?) reasons to look into it. 
Are there some benefits for maintaining it, even if it could get automated?

**Comment by monperrus** [comment]
> For a developer it's something your IDE provides you (hopefully),

Which IDEs do that? Thanks!

**Comment by MartinWitt** [comment]
I' using vscode with [gitlens](https://github.com/eamodio/vscode-gitlens). Provides history for line, selection, file etc. The intellij plugin should be [git toolbox](https://plugins.jetbrains.com/plugin/7499-gittoolbox), the eclipse plugin [egit](https://www.eclipse.org/egit/).
But like I said, having it wont hurt if someone wants to use it.

**Comment by monperrus** [comment]
> I' using vscode with gitlens. Provides history for line, selection, file etc.

Thanks for the tip. That's syntactic, not semantic at the method level, as FinerGit. But I guess
it's straightforward to select the body of the method.
