### ISSUE TITLE
How to get the line no post update of the AST

### ISSUE THREAD

**Issue by Rahamathulla** [INRIA/spoon#3316]
hi,

I have a spoon parser class which updates few statements in a class. The line
assignment.getPosition().getLine()--> returns the line no of the source code in original form. say in our case 5

I am updating the AST by replacing the statement.

assignment.replace(statement1);

again i am calling 
assignment.getPosition().getLine()

it still returns 5 , which is the original line no. but the line nos are changed in the output file generated.

please let me know how to get the line no post update the AST on the fly.

**Comment by nharrand** [comment]
Hi @Rahamathulla ,

This is not possible to the best of my knowledge. 
The position is computed by jdt from the original sources. 
When you modify the AST, there is no longer a link between between modify AST nodes and original sources. How the rest of the AST would link to source position will depend on what pretty printer you use to print it.

Depending one what you want to do, and how often you want to do it, you can print your modifications and reparse them. 
If you you can tell how many lines your new fragments take (assuming they come from other sources), you could try to predict how following line numbers will be affected. But I guess this will be error prone.
