### ISSUE TITLE
Wrong javax import statement causing compilation error

### ISSUE THREAD

**Issue by gibahjoe** [INRIA/spoon#3320]
Hello,

thank you for this great tool.

The generated code for a class that declares a javax validation annotation on its parameter has wrong import statement which causes compile time errors. This only seems to be an issue with javax annotations such as @Valid and @NotNull

for a declaration of 
```java
public void testThatValidAnnotationImportsAreCreated(@Valid @NotNull RandomDto randomDto) 
{
        
throw new IllegalArgumentException("An Error has occurred");

 }
```

The import generated is

```java
import com.example.processor.src.other.@javax.validation.Valid

@javax.validation.constraints.NotNull

RandomDto;
```

instead of 

```java
import com.example.processor.src.other.RandomDto;

import javax.validation.Valid;

import javax.validation.constraints.NotNull;
```

this is related to issue #1773 and #1774

Tested on Spoon 8.1.0 and 8.2.0-beta2 running java 8 

My launcher config is

``` java
  SpoonAPI launcher = new Launcher();

  Environment environment = launcher.getEnvironment();

  environment.setNoClasspath(true);

  environment.setAutoImports(true);

  launcher.addInputResource(s);

  launcher.setSourceOutputDirectory(sourceOutputDirectory);

  ClassProcessor processor = new ClassProcessor();

  launcher.addProcessor(processor);

  launcher.process();

  launcher.prettyprint();
  ```

**Comment by monperrus** [comment]
Would you have a failing test case that reproduces the bug? Thanks!

**Comment by gibahjoe** [comment]
check #3323

Its not a failing testcase, just take a look at the generated source file

**Comment by gibahjoe** [comment]
any update?

**Comment by monperrus** [comment]
not yet: no message on Github = no update for sake of time constraints, sorry.

What about giving it a try and laucnhing a debugger on your own?

**Comment by gibahjoe** [comment]
I am happy to try. If you could point me to where the imports are being generated. or anything related
