### ISSUE TITLE
wrong prettyprint of javax annotation in sniper

### ISSUE THREAD

**Issue by gibahjoe** [INRIA/spoon#3321]
When using the SniperJavaPrettyPrinter, It throws the error below when processing javax annotations

`
otherFragment ((/path/to/file/Class.java:21)) OTHER_IS_BEFORE of (/path/to/file/Class.java:21)
spoon.SpoonException: otherFragment ((/path/to/file/Class.java:21)) OTHER_IS_BEFORE of (/path/to/file/Class.java:21)
`

The specific line it complains about has this code
```java
public TestSource(@NotBlank String firstName, String lastName) {
        this.firstName = firstName;
        this.lastName = lastName;
    }
```
I am guessing its the javax annotation thats causing it. So its probably related to #3320 

This same code works fine using the DefaultJavaPrettyPrinter class

**Comment by monperrus** [comment]
Thanks for the bug report. Would you propose a failing test case in a pull-request? That would be
super useful for fixing.

**Comment by gibahjoe** [comment]
Hello, any update on this issue?
