### ISSUE TITLE
feat(spoon-maven-plugin): offer ability to use compile test source roots

### ISSUE THREAD

**Issue by vmassol** [INRIA/spoon#3327]
It would be nice to offer a flag to include test sources for processing and that would use maven's http://maven.apache.org/ref/3.2.3/apidocs/org/apache/maven/project/MavenProject.html#getTestCompileSourceRoots()

Similar to https://github.com/SpoonLabs/spoon-maven-plugin/blob/7d75eb310668cc0c622483d2b2436f9ebee35935/src/main/java/fr/inria/gforge/spoon/configuration/AbstractSpoonConfigurationBuilder.java#L46

**Comment by monperrus** [comment]
FTR, https://github.com/SpoonLabs/spoon-maven-plugin/pull/68 makes progress on this point.
