### ISSUE TITLE
Spoon-Maven-Plugin: Processor Dependency

### ISSUE THREAD

**Issue by MartinWitt** [INRIA/spoon#3332]
During a pr for thee spoon-maven-plugin i discovered a problem.
The declared dependency from ` http://spoon.gforge.inria.fr/repositories/snapshots/fr/inria/gforge/spoon/spoon-processors/`  is an empty jar. And the "real" jar seems a subproject in /test/projects/processors. Is this strange configuration intended?

**Comment by monperrus** [comment]
This is normal, `processors` is not meant to be deployed on spoon.gforge.inria.fr and anywhere else. It is deployed locally in CI on or the developer machine, see https://github.com/SpoonLabs/spoon-maven-plugin/blob/master/.travis.yml#L19
