### ISSUE TITLE
Question: how to manually add import ? 

### ISSUE THREAD

**Issue by henry-lp** [INRIA/spoon#3333]
Hi ,
Below here is a transformed code using spoon processor. I transformed some lines to `Thread.currentThread().getContextClassLoader()` using my processor but no imports was done to import `java.lang.Thread`. I tried to use fully qualified expression snippet instead of `CtTypeAccess` and hoped for spoon auto imports to handle it but still not working. 

Question: Is there a way to add the import `java.lang.Thread` ?

For more details, please clone https://github.com/henry-lp/travisplay , checkout branch `spoon-issues` , run script.sh and then check output folder `spooned`.

```
package apps;
import javax.ejb.embeddable.EJBContainer;
import javax.ejb.embeddable.EJBContainer;
public class JEEGetClassLoader {
    ClassLoader d = Thread.currentThread().getContextClassLoader();

    public void case1() {
        ClassLoader c = Thread.currentThread().getContextClassLoader();
    }

    public void case2() throws ClassNotFoundException {
        Thread.currentThread().getContextClassLoader().loadClass("anotherclass");
    }

    /* case 3 - anonymous class */
    Person t = new Person() {
        public void eat() {
            ClassLoader e = Thread.currentThread().getContextClassLoader();
        }
    };

    /* case 4 - inner class */
    abstract class InnerClass {
        ClassLoader f = Thread.currentThread().getContextClassLoader();

        public void hello() {
            Thread.currentThread().getContextClassLoader();
        }
    }

    public void usingEJB() {
        EJBContainer container = new EJBContainer();
    }
}
```

**Comment by MartinWitt** [comment]
i dont understand why you want a import to java.lang.Thread. The import is not needed.
Could you explain why you want java.lang imports?

**Comment by henry-lp** [comment]
I see, That's true this import is indeed not needed :) . I got somehow confused by another bug. Thanks a lot for clearing it up for me. This issue can be closed.
