### ISSUE TITLE
Type access to class not on classpath causes Spoon to assume it belongs to compilation unit's package (noclasspath)

### ISSUE THREAD

**Issue by slarse** [INRIA/spoon#3337]
Hello!

Another hour, another bug. I've begun to understand enough of how Spoon works to debug these things now :)

The problem I have is that if I have a type access to a type that's not on the classpath (e.g. to access static variable or method), then Spoon does two things wrong:

1. It assumes that the type belongs to the compilation unit's package. This assumption is invalid if there is any `*` import from a package that's not on the classpath. It was introduced to fix #1293.
2. It makes the reference explicit, causing it to show in pretty-printing.

In conjunction, 1 and 2 can cause compile errors as a class that was imported with a `*` import may suddenly be qualified with the wrong package. The place where it all happens is here:

https://github.com/INRIA/spoon/blob/e7d42138db21a59beff566af22d72aca4141ddbc/src/main/java/spoon/support/compiler/jdt/ReferenceBuilder.java#L1053-L1064

The second point also affects all cases where the JDT does not provide info about something belonging to `java.lang` (see #1307), i.e. that the `java.lang` package statement suddenly becomes explicit. This alone isn't very serious as the code still compiles fine, it's just a bit annoying.

Here's a simple example of where there are issues:

```java
package bug;

import some.pkg.*;
import some.other.pkg.*;

public class StaticMemberAccess {
    int someValue = SomeClass.generateValue();
}
```

Spoon will attach an explicit package reference to `bug` to `SomeClass`, but it could be in any of `bug`, `some.pkg` or `some.other.pkg`, there is no way to tell. So, one needs to check if there is any `*` import from a package that's not resolved before assuming that the compilation unit's package should be used, and I also think that the package should be marked implicit both in the case of the missing `java.lang` thing, and when the package is guessed.

I'm not sure what to do when the package cannot be determined however, is it allowed to set the package as `null`?

I'm working on a PR for this.

**Comment by monperrus** [comment]
> I've begun to understand enough of how Spoon works to debug these things now :)

Great! Your direct bug fixes are super valuable.

> It assumes that the type belongs to the compilation unit's package. 
> It makes the reference explicit, causing it to show in pretty-printing.

That makes two bugs to fix :-)

> is it allowed to set the package as null?

Yes. However, I would prefer to use the null design pattern here if this does not break too many tests (note that we use this pattern for source positions with NoSourcPosition)
