### ISSUE TITLE
Don't display warning when some processor properties are optional

### ISSUE THREAD

**Issue by vmassol** [INRIA/spoon#3339]
Right now, I get:

```
warning: No value found for property 'componentsTxtPath' in processor ...  
```

And my processor has:

```
    @Property
    private String componentsTxtPath;
...
    private Path getComponentsTxtPath(SourcePosition position)
    {
        String path = this.componentsTxtPath;
        if (path == null) {
            path = "target/classes/META-INF/components.txt";
        }
        return Paths.get(computeMavenModulePath(position), path);
    }
```

As you can see I handle the case when it's null in the processor and thus I'd like this property to be optional and not have the warning displayed.

Thanks!

**Comment by monperrus** [comment]
Thanks for the bug report! I fully agree with you, that's not a useful warning.

It seems to be an easy PR to fix that, would you give it a try?

Thanks!

**Comment by MartinWitt** [comment]
looks fixed and can be closed?

**Comment by monperrus** [comment]
Thanks @MartinWitt
