### ISSUE TITLE
bug: parentheses around casts change bytecode and crash JDK8

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#3353]
Very subtle problem found by @slarse 

> Every time a cast is made in the code, the Java compiler inserts a CHECKCAST instruction to make sure that the cast was actually safe. If the CHECKCAST is not present after a type conversion, the JVM will not even run the code. When the cast is OK, the CHECKCAST is essentially a nop, it does nothing. If it fails, the JVM crashes. The problem I encountered was that with JDK8, any cast where there's one or more redundant parentheses around the expression causes two identical CHECKCAST instructions to be generated. Since a CHECKCAST either crashes the JVM or does nothing, having two in a row makes no sense. So, for e.g. `(Integer) obj;` there's just one CHECKCAST, but for `(Integer) (obj);` there are two. As Spoon's pretty printer always inserts redundant parentheses, this causes enormous diffs for large files, and any file containing a cast will cause a diff unless the author actually placed a redundant parenthesis around the expression. The problem is gone in JDK9.

Since it's solved in JDK9+, this issue is more for documentation purpose than for fixing.

**Comment by slarse** [comment]
For context, I found this when comparing the bytecode generated from compiling a reference source file to the bytecode generated from compiling the same source file as pretty-printed by Spoon's default printer. The diffs mentioned are the bytecode diffs as produced by [SootDiff](https://github.com/secure-software-engineering/sootdiff).

Consistently reproducible with `OpenJDK 1.8.0_242` and `OpenJDK 1.8.0_120`, but I could not reproduce it with any of the versions of JDK9, JDK10, JDK11 and JDK13 that I had at hand.

**Comment by monperrus** [comment]
we all agree that it's cool but it's WONTFIX
