### ISSUE TITLE
Which versions of Java are supported?

### ISSUE THREAD

**Issue by MysterAitch** [INRIA/spoon#3374]
I noticed that the description of this project refers to supporting Java 9, 10, 11, 12, 14 (missing 13?), while the readme and the main webpage both state "It fully supports modern Java versions up to Java 11."

Which is correct? Is this just a case of the documentation needing updating?

**Comment by MartinWitt** [comment]
Looking here [https://openjdk.java.net/projects/jdk/13/](https://openjdk.java.net/projects/jdk/13/) java 13 has no "new" feature, that spoon needs to implement. Java 14 is fully supported, expect preview feature records( textblocks needed no change in spoon). 

14: see #3314
13: no features
12: see #3011
11: see #2106 

So spoon supports up to java 14.
The documentation is outdated sometimes and could be fixed.

**Comment by monperrus** [comment]
Thanks for noticing the glitch, see #3375
