### ISSUE TITLE
Wrong version and JavaDoc in README

### ISSUE THREAD

**Issue by teras** [INRIA/spoon#3377]
Hello I just discovered spoon and I'm excited that there's always honest competition!

I tried to use it though, following the README file but found some glitches.

First of all for maven dependencies I saw this:

```xml
<dependency>
    <groupId>fr.inria.gforge.spoon</groupId>
    <artifactId>spoon-core</artifactId>
    <version>{{site.spoon_release}}</version>
</dependency>
```

Which is the correct version? Probably this is a parsing error.

By clicking on the maven artifact, I can assume that (as of today) it's `8.2.0-beta-8` but I believe this information should be more obvious.

Also the link to JavaDoc is broken?

Thank you for your effort !

**Comment by monperrus** [comment]
`{{site.spoon_release}}` is rendered in http://spoon.gforge.inria.fr/

Thanks for the broken link, fixed in https://github.com/INRIA/spoon/pull/3378

**Comment by teras** [comment]
Oh OK, it's still frustrating for "new users" like me :)
