### ISSUE TITLE
Sorting Class members with spoon?

### ISSUE THREAD

**Issue by coderesting** [INRIA/spoon#3380]
Hi,

I'm pretty new to Java/ Spoon.
My goal is to reorder the members of all classes in a Java-Project in a way, that the class has the following structure.

1. static variables (public, protected, private)
2. instance variables (public, protected, private)
3. Constructors
4. methods

Eclipse has this functionality but I haven't found it anywhere else. 
Any ideas on how to accomplish that task with Spoon would be appreciated.

Thanks.

**Comment by monperrus** [comment]
Spoon is the perfect tool for this use case.

The methods you need are in `CtType`, in particular `addTypeMemberAt`.

**Comment by coderesting** [comment]
Thanks for the answer, but now I'm having another problem.
A variable of a class is removed with `removeField(field)`. Then I add it back in with `addFieldAtTop(field)` and it appears under the existing methods of the Class. How can that happen?

**Comment by MartinWitt** [comment]
Could you provide a code example showcasing this behavior? 
Would help me looking into it.

**Comment by coderesting** [comment]
Here you go:
```
Launcher launcher = new Launcher();
launcher.addInputResource( "./assets/JavaCode.java" );
launcher.buildModel();
CtModel model = launcher.getModel();

for(CtType<?> c : model.getAllTypes()) {
	List<CtField<?>> fields = c.getFields();	
	for(CtField<?> field : fields) {
		c.removeField(field);
		c.addFieldAtTop(field);
	}		
	System.out.println(c.toString());`
}
```

The content of JavaCode.java is:
```
public class HelloWorld {
	void testMethod() {}
	private int testVariable;
}
```

**Comment by MartinWitt** [comment]
I looked into and found the issue. Your code is working, but [here](https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java#L258) the clone changes the order of the typemembers. Now I'm looking into the clone method and hope i can fix it for you.
This changes the issue from a question to a bug.

**Comment by MartinWitt** [comment]
I sadly have to do some university stuff. I hope I find time for this issue next weekend. If you or somelse wants to fix it feel free. It looks like the list is cloned without keeping the order.

**Comment by coderesting** [comment]
Do you know if there is a workaround for the issue?

**Comment by monperrus** [comment]
What if you use the other methods `add*` of CtType instead of `addFieldAtTop`?

**Comment by MartinWitt** [comment]
The bug is in the PrettyPrinter not in the position changing methods, like `addFieldAtTop` .
Before printing spoon clones a CtElement. And the clone method changes the order of the  `List<typeMembers>`.

**Comment by coderesting** [comment]
Does this bug affect all pretty printing modes?

**Comment by monperrus** [comment]
@MartinWitt thanks, the bug is not in the pretty-printing code but in the cloning code, created #3389

@coderesting good news there is a workaround, use `toStringWithImports()` or `toStringDebug()`

Closing it, #3389 is the one to be fixed.

**Comment by coderesting** [comment]
Ok, that worked for me.
Thanks for your help @monperrus and @MartinWitt

**Comment by monperrus** [comment]
Note that if you pretty-print the transformed code to disk, you would not be impacted by this bug).
