### ISSUE TITLE
[question]what is the meaning of sourceEnd and sourceStart in interface SourcePosition

### ISSUE THREAD

**Issue by 645709712** [INRIA/spoon#3383]
hi,I have already read the doc of interface SourcePosition.it explains the method 'getSourceStart()' as:Gets the index at which the position starts in the source file.

So I want to know what's the meaning of 'index'...

Thank you very much

**Comment by MartinWitt** [comment]
the index is the character number in the file. 
Showcasing this at an example:
```java
String a = 3;
int b = 4;
```
The first line has 13 chars. SourceIndex start for `int` would be 14 and end 16.

**Comment by 645709712** [comment]
> the index is the character number in the file.
> Showcasing this at an example:
> 
> ```java
> String a = 3;
> int b = 4;
> ```
> 
> The first line has 13 chars. SourceIndex start for `int` would be 14 and end 16.

I see.Thank you very much

**Comment by monperrus** [comment]
Feel free to make a documentation pull-request to improve the Javaodc. Thanks!
