### ISSUE TITLE
Is there any method to find runtime exceptions an compile time exception in a java file using spoon library?

### ISSUE THREAD

**Issue by sohanmadhana** [INRIA/spoon#3384]

**Comment by MartinWitt** [comment]
Hi,
do you mean thrown Exception, caught exception or declared exception?
See:
### thrown Exception
`Files.newByteChannel(...)`
### caught exception
```java
     try {
        System.out.println("foo");
     } catch (Exception ignore) {}
```
### declared Exception
`public class Foo extends Exception`

depending on the context, i could answer your question. 

btw: i thought long about answering your question, because it looks really low effort.

**Comment by sohanmadhana** [comment]
Thank you for the answer. Can we find runtime exceptions, like arrayindexoutofbound, throw stack trace.

**Comment by santos-samuel** [comment]
> Thank you for the answer. Can we find runtime exceptions, like arrayindexoutofbound, through stack trace.

I didn't quite understand what you meant with "through stack trace" but i'll give it a shot.

Feel free to correct me if im wrong.

Runtime behaviour and static analysis/transformation don't go along well.
Using spoon, you could easily find which exceptions could be thrown, and in which lines, and also which from those are being caugh in your code.
Knowing with certainty if in a specific line an exception will be thrown can be feasible in some cases and unfeasible in others.
For example: If you have a list and an indexed for loop iterating that list, knowing if the loop would throw the index out of bound exception would depend on whether you know the size of the list and the number of iterations beforehand or not. 
If the intialization of the list being iterated was based on the parse of a file given as input by the user, it would be impossible to infer that information. However, if you could track from the point where the list was initialized and do sort of a dataflow analysis assessing each code branch where the list could be modified and deducing the maximum size the list could possibly have, you're halfway there. The other half is doing the same for the breaking condition of the loop. Things get even more "annoying" if the variable being iterated and used to access the list is changed inside the for loop

> btw: i thought long about answering your question, because it looks really low effort from you.
> You could describe more and not only write a title.
^ this
