### ISSUE TITLE
Release 4.3.0: September 22, 2015

### ISSUE THREAD

**Issue by GerardPaligot** [INRIA/spoon#340]
Hi all,

The next release 4.3.0 is planned for Tuesday 22th September. This release is a big one, the last release was in June!

I post the changelog soon!

**Comment by monperrus** [comment]
FYI: everything on track for tomorrow's release!

**Comment by GerardPaligot** [comment]
The version 4.3.0 is released. Thanks to all contributors! You can find the changelog below:

New features

- Adds the possibility to set level for all loggers of Spoon.
- Introduces a new API for reasoning about the path between elements in a model
- Support zip/jar as input file
- Introduces CtRHSReceiver to factorize all assignment-like elements.

Minor API changes:

- Adds setOutputSourceDirectory and setOutputBinaryDirectory methods in SpoonAPI
- Adds addProcessor(Processor) method in SpoonAPI.
- Converts all setters in the AST for a fluent API.

Bug Fixes

- Fixes array[index] on RHS is now considered ArrayRead (https://github.com/INRIA/spoon/pull/341)
- Improves noclasspath mode. (https://github.com/INRIA/spoon/pull/338, https://github.com/INRIA/spoon/pull/339)
- Fixes the auto-import of CtInvocations (https://github.com/INRIA/spoon/pull/335)
- Makes AbstractAnnotationProcessor compatible with type annotations. (https://github.com/INRIA/spoon/pull/320)
- Prints only imports used in classes in with-imports mode. (https://github.com/INRIA/spoon/pull/315)
- Enables annotations on fields of enum. (https://github.com/INRIA/spoon/pull/295)
- Fixes import of an inner class in a class package. (https://github.com/INRIA/spoon/pull/293)
- Added correct handling for enum's listed in an enum definition (CtEnum) (https://github.com/INRIA/spoon/pull/289)
- Fixes NPE with properties directory is non existing (https://github.com/INRIA/spoon/pull/287)
- Generates right types for parameters in a lambda. (https://github.com/INRIA/spoon/pull/285)
- Uses diamond syntax for type of some elements. (https://github.com/INRIA/spoon/pull/284)
- Scanning of constructors in Enums added to CtScanner (https://github.com/INRIA/spoon/pull/281)
- Fixes Type package with incomplete sources. (https://github.com/INRIA/spoon/pull/278)
- Field access in sub classes in noclasspath mode. (https://github.com/INRIA/spoon/pull/266)
- Bug fix for nested annotation types. (https://github.com/INRIA/spoon/pull/265)
- Bug fix when adding an annotation. (https://github.com/INRIA/spoon/pull/263)
- Allows to assign null AST childs after non-null (https://github.com/INRIA/spoon/pull/259)
