### ISSUE TITLE
IncrementalLauncher invoke saveCache error

### ISSUE THREAD

**Issue by liulhdarks** [INRIA/spoon#3404]
My sources code depends on tripartite libraries, but I want to use IncrementalLauncher to analysis only source code without JAR packages, it can succeed to build model, but when I execute saveCache method, it will report erros:
`spoon.support.compiler.SnippetCompilationError: The import org.apache.ibatis cannot be resolved at [C@3c137612:7
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.reportProblemsWhenCompiling(JDTBasedSpoonCompiler.java:590)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.compile(JDTBasedSpoonCompiler.java:160)
	at spoon.IncrementalLauncher.saveCache(IncrementalLauncher.java:267)`

1. why IncrementalLauncher must invoke compile method? 
`getModelBuilder().compile(SpoonModelBuilder.InputType.FILES);`

2. if I want to build incremental model, is it the only way to use IncrementalLauncher? can I add a new CtClass or update existing CtClass from single source code string to the model built by SpoonAPI launcher?

**Comment by monperrus** [comment]
Thanks for the bug report! Would you create a PR with a failing test case? It would  be super helpful to fix the bug.
