### ISSUE TITLE
Incorrect transformation with comment lines 

### ISSUE THREAD

**Issue by anderruiz** [INRIA/spoon#3424]
The following transformation is being done incorrectly

@MyAnnotation(somevalues...) // plus more...
public class MyClass {
}

Is transformed to

// plus more ... @MyAnnotation(somevalue...)
public class MyClass {
}

**Comment by monperrus** [comment]
This is normal if you use the default pretty-printing mode, see http://spoon.gforge.inria.fr/launcher.html
