### ISSUE TITLE
Can I use a spoon to automatically create sub-method?

### ISSUE THREAD

**Issue by deng1234** [INRIA/spoon#3478]
hi, dear spoon team

I want extract some statements from a method to create a new sub-method. But I have some trouble when I try to get parameters and return values. 

1. How to extract parameters from statements accurately?
2. How to deal with multiple return values?

for example:

public class test {

	void mainFunction() {
		int sum = 0;
		int count = 0;
		int i = 0;
		for(i = 0; i < 10; i++) {
			if(i % 3 == 0) {
				sum = sum + i;
				count++;
			}
		}
		System.out.println(sum);
		System.out.println(count);
	}
}

to:

public class test {
    
	private int count;
	private int sum;
	
	void subFunction(int i, int count, int sum) {
		for(i = 0; i < 10; i++) {
			if(i % 3 == 0) {
				sum = sum + i;
				count++;
			}
		}
		this.count = count;
		this.sum = sum;
	}
	
	
	void mainFunction() {
		int sum = 0;
		int count = 0;
		int i = 0;
		this.subFunction(i, count, sum);
		System.out.println(this.sum);
		System.out.println(this.count);
	}
}

The following code is that I try to extract parameters from some statements, But CtElement is inherited by many classes. Whether have other method to extract parameters except use following code?

if(newStatements.get(i) instanceof CtAssignment) {
	CtAssignment assignment = (CtAssignment) newStatements.get(i);
	CtParameter parameter = getFactory().createParameter();
	parameter.setSimpleName(assignment.getAssigned().toString());
	parameter.setType(assignment.getAssigned().getType());
	parameters.add(parameter);
}

I have no clear idea about handling multiple return values currently.

**Comment by monperrus** [comment]
> Can I use a spoon to automatically create sub-method?

yes, this refactoring a valid use case of Spoon. See class CtRefactoring.

> handling multiple return values currently.

what about returning a List or an array?

**Comment by deng1234** [comment]
Thank you for your reply.

CtRefactoring is useful for other transform, but it can't create a new method and obtain the parameters and return values ​​of the new method.

According to my understanding. If I want use spoon to create a sub-method automatically, the main problem is getting parameters and return values ​​from some statements.

Return a list is OK,  however the position where the return values is used in the main function should be changed.
eg:
`System.out.println(sum)`
change to:
`System.out.println(list.get(0))`

**Comment by MartinWitt** [comment]
From my experience a visitor applying to all elements recursive helps alot in problems of this kind.
Getting parameters needed for a subfunction looks related to [escape analysis](https://en.wikipedia.org/wiki/Escape_analysis#Example_(Java)) .
If you provide your current program, I can try to help you writting an analysis for the parameter.
