### ISSUE TITLE
Issues with DefaultJavaPrettyPrinter.visitCtTypeReferenceWithoutGenerics() method

### ISSUE THREAD

**Issue by leventov** [INRIA/spoon#348]
To be honest it is hard to me now to say *what* is wrong with this method, but it generated invalid Java code. I used this patch: https://github.com/OpenHFT/Spoon/commit/f3bd62b4de7fb6b3237c5247823e27fad19de2c0#diff-5f33bf5d1f38230de815e4c60a67a215

**Comment by GerardPaligot** [comment]
Do you have a test case or a snippet for this? The last (and only) modification of the method `visitCtTypeReferenceWithoutGenerics` goes back to 2013.

**Comment by GerardPaligot** [comment]
@leventov No news, good news?

**Comment by leventov** [comment]
@GerardPaligot no news. I just use my fork (OpenHFT/Spoon) with the patches, it works, so I don't pay time to this.

**Comment by GerardPaligot** [comment]
Sorry @leventov but if we don't have the bug, that seems hard to integrate it in Spoon. I close the issue but if you have time to localise the bug, you can re-open this issue.

**Comment by leventov** [comment]
@GerardPaligot that's OK
