### ISSUE TITLE
test suite fails at some point in CI

### ISSUE THREAD

**Issue by mhow2** [INRIA/spoon#3486]
Please see the build log at : 

https://gitlab.ow2.org/ow2/oscar/spoon/-/jobs/28973/raw

The build job is defined at:
https://gitlab.ow2.org/ow2/oscar/spoon/-/blob/master/.gitlab-ci.yml

**Comment by monperrus** [comment]
Thanks for the bug report @mhow2 

The errors are:

```
[ERROR] Failures: 
[ERROR]   TypeFactoryTest.reflectionAPI:65 expected:<3> but was:<5>
[ERROR]   TypeTest.testAllTypeMembersFunctionMode:68 expected:<17> but was:<16>
[ERROR]   TypeTest.testGetAllExecutables:53 expected:<16> but was:<15>
[ERROR]   ExecutableReferenceTest.testSpecifyGetAllExecutablesMethod:140 expected:<13> but was:<12>
```

The reason is maybe that the job uses Java version: 14.0.1.

Could you try with Java 11?

Thanks!

**Comment by mhow2** [comment]
ok, the reason is the docker image `maven:latest` switched to java 14. I tweaked it to `maven:3-jdk-11` : so simple ;) 

Thanks !

**Comment by monperrus** [comment]
perfect, thanks!
