### ISSUE TITLE
NullPointerException when creating new Package (spoon.reflect.factory.PackageFactory#create)

### ISSUE THREAD

**Issue by clemensbartz** [INRIA/spoon#3488]
Affected version: spoon-core, 8.1.0

**Set-up**
Choose any empty directory as `sourceDirectory`, set up launcher and environment like this:
```java
final Launcher launcher = new Launcher();
launcher.addInputResource(getSourceDirectory().getAbsolutePath());
launcher.setSourceOutputDirectory(getSourceDirectory().getAbsolutePath());
launcher.getEnvironment().setAutoImports(true);
launcher.buildModel();
factory = launcher.getFactory();
processor = launcher.createOutputWriter();
model = launcher.getModel();
```

**Observation**
When creating a new (root) package, the documentation for create states:
> the parent package (can be null)

```java
final CtPackage ctPackage = factory.createPackage(null, "fooBar");
````

This throws an NPE:
```java
java.lang.NullPointerException
	at spoon.reflect.factory.PackageFactory.create(PackageFactory.java:101)
	at spoon.reflect.factory.FactoryImpl.createPackage(FactoryImpl.java:1214)
	at de.redacted(redacted.java:42)
```

**Expectation**
A new root package is created.

**Comment by monperrus** [comment]
Thanks a lot for the bug report. Would you be able to make a pull-request containing a failing test case? That would be super useful.

**Comment by MartinWitt** [comment]
Looks like [github](https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/reflect/factory/PackageFactory.java#L101) the `toString()` produces the problem, because null.toString(). Trying to create a patch later today, if noone else wants to have an easy first commit.

**Comment by clemensbartz** [comment]
As requested, I have added a test case which is currently failing for this issue.

**Comment by monperrus** [comment]
Thanks.
