### ISSUE TITLE
ctVisitTypeReference() doesn't visit RHS instanceof occurrences

### ISSUE THREAD

**Issue by leventov** [INRIA/spoon#349]
The fix I came up with is
```
--- a/src/main/java/spoon/reflect/visitor/CtScanner.java
+++ b/src/main/java/spoon/reflect/visitor/CtScanner.java
@@ -466,6 +466,9 @@ public abstract class CtScanner implements CtVisitor {
                scan(literal.getAnnotations());
                scan(literal.getType());
                scanReferences(literal.getTypeCasts());
+               T value = literal.getValue();
+               if (value instanceof CtReference)
+                       scan((CtReference) value);
                exit(literal);
        }
```

But I'm not sure this is the "right" way.

**Comment by GerardPaligot** [comment]
I don't understand this issue. What is the link between `CtTypeReference`, `CtRHSReceiver` and `CtLiteral`?

**Comment by leventov** [comment]
Sorry I was not precise.

If I try to scan all references, by calling `ctElement.getElements((CtTypeReference<?> ref) -> ...)` it doesn't visit references on RHS of `isntanceof`.

I proposed a possible fix in the issue body. But since from JLS perspective there are no such term as "type literal", probably "right" solution would be create a special class of expression for `instanceof`, say `CtInstanceof`

**Comment by leventov** [comment]
See https://github.com/OpenHFT/Spoon/commit/59968c292df674b6c198c219662897a2c988da19

**Comment by GerardPaligot** [comment]
The real question here is: why the right hand operand is a `CtLiteral` and not directly a `CtTypeReference`? ...

@monperrus Any idea? That sounds good for you to change the right hand operand from `CtLiteral` to `CtTypeReference`?

**Comment by leventov** [comment]
@GerardPaligot I think because instanceof is `CtBinaryOperator`, which has two CtExpressions, the right one should represent a type, but couldn't be just `CtTypeReference` (because `CtTypeReference` is not a `CtExpression`).

JLS classify `isntanceof` as binary operation, but it special case the type on instanceof's RHS: it is not a  literal, or expression

**Comment by GerardPaligot** [comment]
> @GerardPaligot I think because instanceof is CtBinaryOperator, which has two CtExpressions, the right one should represent a type, but couldn't be just CtTypeReference (because CtTypeReference is not a CtExpression).

This is exactly what I want changed! Deprecate the right hand operand expression and create a new one.
