### ISSUE TITLE
Bug when trying to get the reference of a lambda cast with an intersection

### ISSUE THREAD

**Issue by quentinLeDilavrec** [INRIA/spoon#3520]
Hi,

There seems to be an error with a particular use of lambda expressions :
`Runnable f = (Serializable & Runnable) () -> system.out.println()`

If I try to get the reference of the lambda expression I get the Spoon exception :

>  The lambda can be based on interface, which has one method. But java.io.Serialize has no one

That is thrown in `CtLambdaImpl.getOverriddenMethod()`.

In fact, `Serialize` do not declare any method but `Runnable` does.

Thanks

**Comment by monperrus** [comment]
Thanks a lot for the bug report. Would you be able to make a pull-request with a failing test case? That would be super useful.
