### ISSUE TITLE
Can I use spoon to get all effected code by a method?

### ISSUE THREAD

**Issue by SamuelMotal** [INRIA/spoon#3522]
Hello, dear spoon team,

my goal is to get from a certain method all the code which is executed by this method like other methods in the same class or methods in other classes. Right now I am doing this recursively by walking through all the code that this method calls. 
The code looks currently like this: 
```
	private void getCodeFromExecuteablesRecursive(final Map<String,String> result, final CtElement element) {
		if(element instanceof CtExecutableReference) {
			final CtExecutableReference<?> reference = (CtExecutableReference<?>)element;
			if(reference.getDeclaration() != null && reference.getDeclaration().getBody()!=null) {
				if(!result.containsKey(getClassAndMethodSignature(reference.getPath(), reference.getSignature()))) {
					result.put(getClassAndMethodSignature(reference.getDeclaration().getPath(), reference.getSignature()), reference.getDeclaration().toString());
				}else {
					return;
				}
				getCodeRecursiveFromStatements(result,reference.getDeclaration().getBody().getStatements());
			}
		}else if(element instanceof CtBlock) {
			final CtBlock<?> block =(CtBlock<?>)element;
			getCodeRecursiveFromStatements(result, block.getStatements());
		}else if(element instanceof CtInvocation) {
			final CtInvocation<?> invocation = (CtInvocation<?>)element;
			getCodeFromExecuteablesRecursive(result,invocation.getExecutable());
		}
		
	}
	
```
Currently I have two problems:
1) I am not really satsified with my current code. I am also not sure if it covers all situations. Do you have any recommendations how to do this in a better way?
2) Let's say we come to a code snippet which calls an interface. Do you see any possibility to determine which implementation of this interface was used in this particular call? 

Thank you and best regards

**Comment by MartinWitt** [comment]
Hi,

> I am not really satsified with my current code. I am also not sure if it covers all situations. Do you have any recommendations how to do this in a better way?

if you want to get all executable calls from a method you can use `method.getElements(new TypeFilter<CtAbstractInvocation<?>>(CtAbstractInvocation.class))`. The TypeFilter finds all childs matching the filter and executable in spoon is either a CtMethod or CtConstructor

> Let's say we come to a code snippet which calls an interface. Do you see any possibility to determine which implementation of this interface was used in this particular call?

To my best knowledge there is no exact possibility for this. You can find all caller and hope you find the exact type at caller side.

**Comment by SamuelMotal** [comment]
Thanks a lot - I will change the code to use the TypeFilter.
