### ISSUE TITLE
Move CI to travis-ci.com

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#3600]
Travis CI will close travis-ci.org, we need to move to travis-ci.com

> Hi there!
> 
> As you’ll no doubt have noticed, Travis CI has, for some time, been split between travis-ci.com and travis-ci.org. This was initially planned to enable open-source and commercial/private projects to be distinctly separate, but back in May 2018, we announced that open source builders would have the opportunity to build and test their projects under travis-ci.com, meaning your public and private repositories could be managed under one domain with a consistent interface and build environment.
> 
> 
> In an effort to ensure that all of our users - whether you build open-source, public or private repositories - receive regular feature updates, security patches and UX/UI enhancements, we are announcing that travis-ci.org will be officially closed down completely on December 31st, 2020, allowing us to focus all our efforts on bringing new features and fixes to travis-ci.com and all of our awesome users like yourself on the travis-ci.com domain. 
> 
> What this means for you
> 
> The main thing to expect is that your projects will be built and tested with the same speed and robustness as you’ve come to expect from Travis CI - but also with great new features such as support for AWS Graviton2 which is only available on travis-ci.com. Open-source projects will be free as they always have, with lighting fast builds provided by partners like Packet.
> 
> 
> We encourage you to migrate your existing repositories that are currently on travis-ci.org over to travis-ci.com as soon as possible, enabling you to identify any additional changes required to your code or configuration well in advance of the December 31st deadline. We’ve documented everything you need to know in order to migrate your repositories, and of course, you can reach out on the community forum for any additional help.
> 
> 
> If you have any questions or concerns, please feel free to contact our support team who will be happy to talk through any migration queries you may have!
>  
> 
> Happy building on travis-ci.com!

**Comment by MartinWitt** [comment]
[https://docs.travis-ci.com/user/migrate/open-source-repository-migration](https://docs.travis-ci.com/user/migrate/open-source-repository-migration ) Looks like guide for moving. Someone with write permissions need to follow these steps and move the repo.

**Comment by monperrus** [comment]
We now use Travis CI.com https://travis-ci.com/INRIA/spoon/

**Comment by monperrus** [comment]
Travis CI is down, message is "Builds have been temporarily disabled for private and public repositories due to a negative credit balance. Please go to the Plan page to replenish your credit balance."

Seems like the move was useless

**Comment by monperrus** [comment]
Sent the following email to support

> Hi Travis,
> 
> We love Travis CI for our OSS project https://github.com/INRIA/spoon
> 
> Per the documentation of https://docs.travis-ci.com/user/billing-overview/#usage---credits
The OSS credits may be assigned as one time pool or renewable pool, subject to case by case assesment of Travis CI staff.
> 
> Could you please set up a renewable pool of credits for our project https://github.com/INRIA/spoon?

**Comment by monperrus** [comment]
In the meantime, we may set up a pull request builder on our Jenkins a https://ci.inria.fr/sos/. Excited?

**Comment by slarse** [comment]
@monperrus For a temporary substitute, the fastest thing would probably be to setup a GitHub Actions workflow. Want me to give it a go?

 Jenkins is awesome but it is more fiddly. We'd need to both setup the jobs, and add webhooks to integrate with GitHub.

**Comment by monperrus** [comment]
> For a temporary substitute, the fastest thing would probably be to setup a GitHub Actions workflow. Want me to give it a go?

Yes, that would be great, thanks a lot.

**Comment by slarse** [comment]
I'm on it!
