### ISSUE TITLE
PositionBuilder modifier positions bug

### ISSUE THREAD

**Issue by Strum355** [INRIA/spoon#3606]
Given a class similar to the following [1], the PosiitonBuilder fails to attach a position to class modifiers.
When it encounters `/*` in `@Consumes("*/*")`, it treats it as the start of a comment. As such, it continues treating up until the "end of last modifier" position as a comment, therefore never adding a position to it.
When it discovers it has remaining modifiers, it throws an exception, causing the entire top level declaration to have NOSOURCEPOSITION assigned to it.

[1]
```java
// imports, package decl 
@Consumes("*/*")
public class DiscoveryJerseyProvider implements EtcBlahSampleText { ... }
```

**Comment by monperrus** [comment]
Thanks for the bug report. Are you fixing it? That would be great :)

**Comment by andrewbwogi** [comment]
I can try to fix this
