### ISSUE TITLE
The SpoonifierVisitor mentionned in the documentation seems to be SpoonifyVisitor

### ISSUE THREAD

**Issue by dhmoclex** [INRIA/spoon#3615]
Hi,

The documentation talks about a SpoonifierVisitor (http://spoon.gforge.inria.fr/factories.html), but it cannot be found on the repository. Nevertheless there is a SpoonifierTest and a SpoonifyVisitor.

For consistency, which will help new user, it may be preferable to adopt either SpoonifyVisitor or SpoonifierVisitor.
Moreover the documentation should reference at least SpoonifyVisitor insted of SpoonifierVisitor which doesn't exist in Spoon.

I can address a pull request for which term you prefer if you want.

Thanks for this great tool,
Sébastien.

**Comment by nharrand** [comment]
Oops indeed that's an unfortunate inconsistency. A pull request is very much welcome for this!

**Comment by nharrand** [comment]
But in any case thanks for the report.

**Comment by dhmoclex** [comment]
Which one do you want ? SpoonifyVisitor or SpoonifierVisitor ?

**Comment by nharrand** [comment]
My personal preference would go to `SpoonifierVisitor` but any of the two would be fine I think.
