### ISSUE TITLE
Working With ByteCode as well as SourceCode

### ISSUE THREAD

**Issue by sirinath** [INRIA/spoon#3621]
Is it possible to extend the functionality to directly work with bytecode? When working with other JVM languages and 3rd party libraries one does not have access to Java source code. This would make Spoon very much more useful.

**Comment by monperrus** [comment]
Source code analysis on bytecode can be done with the spoon-decompiler 
module: https://github.com/INRIA/spoon/tree/master/spoon-decompiler

**Comment by nharrand** [comment]
So, there are two ways you can try to do it. Neither is perfect. 

First you can use the spoon-decompiler module. This allows you to decompile bytecode to Java source (in theory even if the original sources were not written in java), build an AST modify it, print it back to Java and then recompile it. (You can even do this with an agent during class loading.)

The other option is to use the experimental work of @andrewbwogi available [here](https://github.com/andrewbwogi/metameta).
I allows you to translate simple spoon transformation into ASM transformations that do work on bytecode.
