### ISSUE TITLE
Possible regression on adding values to CtAnnotation

### ISSUE THREAD

**Issue by jottler** [INRIA/spoon#3639]
I use Spoon to generate Java source files running Java 8. Using spoon-core 8.3.0-SNAPSHOT and 8.3.0-beta-10 I see a regression where adding a second value to a CtAnnotation makes the first added value not appear in the annotation in the created source.

To reproduce I have a simple annotation

    package tryspoon;

    public @interface Summary {
        String title();
        String date();
    }

and the following main class

    package tryspoon;

    import spoon.Launcher;
    import spoon.SpoonAPI;
    import spoon.reflect.declaration.CtAnnotation;
    import spoon.reflect.reference.CtTypeReference;

    public class Spooner {
        public static void main(String[] args) {
            SpoonAPI spoon = new Launcher();

            CtTypeReference<Summary> typeRef = spoon.getFactory().createCtTypeReference(Summary.class);
            CtAnnotation<Summary> annotation = spoon.getFactory().createAnnotation(typeRef);

            annotation.addValue("title", "First summary");
            annotation.addValue("date", "2020-10-05");

            // This outputs @tryspoon.Summary(date = "2020-10-05")
            System.out.println(annotation);

            // This outputs {date="2020-10-05", title=null}
           System.out.println(annotation.getAllValues());

           // This *does* output First summary
           System.out.println(annotation.getValue("title").toString());
           }
    }

The value of the first added key-value pair is seemingly being nulled when adding the second pair. In my actual code, this results in a created Java source file where the first annotation element is missing. I note that actually getting the value
works, that is `annotation.getValue("title").toString()` does return "First summary".

Originally I thought I saw the same behaviour using spoon-core 8.2.0 but I cannot reproduce with 8.2.0 now.

**Comment by nharrand** [comment]
Thanks a lot, @jottler , for the bug report, and the reproduction steps. This is indeed an issue!
