### ISSUE TITLE
Spoon snapshot repository at maven.irisa.fr unreachable

### ISSUE THREAD

**Issue by slarse** [INRIA/spoon#3648]
Hello!

Since yesterday, my builds can't reach the Spoon snapshot repository at maven.irisa.fr. This causes some builds that depend on snapshots to slow to a crawl as Maven tries to resolve dependencies from that server. For example, [sorald](https://github.com/spoonlabs/sorald) now builds in >20 minutes, as opposed to <1 minute.

Does anyone have any idea of what's going on?

**Comment by monperrus** [comment]
There is a problem at maven.irisa.fr.

It's not the first time.

If we want to move to avoid this in the future, one alternative option 
is to move the snapshots to the Nexus at https://repository.ow2.org/

If you or somebody want to make the conf, I can share the authorization 
tokens.

**Comment by slarse** [comment]
I've never configured for publishing snapshots. How are snapshots currently published? I can't find it in the CI configuration, is it manual?

How about using [GitHub Packages](https://docs.github.com/en/free-pro-team@latest/packages/using-github-packages-with-your-projects-ecosystem/configuring-apache-maven-for-use-with-github-packages) for snapshots? It seems very straightforward, and it can be configured in a GitHub Action workflow to update the snapshot on each push to master. No need to share any tokens either as the workflow has the necessary token by default. I could try that out on one of my projects first and see how it goes. Thoughts?

**Comment by monperrus** [comment]
Today, snapshots are deployed by a Jenkins job: https://ci.inria.fr/sos/job/Spoon-Snapshot-Deployer/

**Comment by monperrus** [comment]
> How about using GitHub Packages for snapshots?

I would be fine with this too.

**Comment by slarse** [comment]
> > How about using GitHub Packages for snapshots?
> 
> I would be fine with this too.

Gerat, I'll give this a shot then as it's what I'm familiar with. I'll have a go at it today as the unresponsive snapshot server is really slowing down my workflow.

**Comment by slarse** [comment]
@monperrus I've been playing around with GitHub packages for the past hour, and I think it's insufficient. The biggest hurdle is that it requires authentication [even to fetch public packages](https://github.community/t/download-from-github-package-registry-without-authentication/14407/7). I've [tried it with Spork](https://github.com/KTH/spork/packages/446156) just to verify, and it's indeed not possible to fetch the package without supplying a username and auth token.

I'm guessing we want snapshots to be publicly available, and then we should probably use the OW2 Nexus. In my mind, it should be about as simple as doing the following in `spoon-pom/pom.xml`

```diff
-        <snapshotRepository>
-            <id>maven.inria.fr-snapshot</id>
-            <name>Maven Repository for Spoon Snapshots</name>
-            <url>http://maven.inria.fr/artifactory/spoon-public-snapshot</url>
-        </snapshotRepository>
+        <snapshotRepository>
+            <!-- Not sure what the ID should be? -->
+            <id>ow2-nexus</id>
+            <name>Maven Repository for Spoon Snapshots</name>
+            <url>https://repository.ow2.org/nexus/content/repositories/snapshots/</url>
+        </snapshotRepository>
```

```diff
-        <repository>
-            <id>maven.inria.fr-snapshot</id>
-            <name>Maven Repository for Spoon Snapshots</name>
-            <url>https://maven.irisa.fr/artifactory/spoon-public-snapshot</url>
-        </repository>
+        <repository>
+            <!-- Not sure what the ID should be? -->
+            <id>ow2-nexus</id>
+            <name>Maven Repository for Spoon Snapshots</name>
+            <url>https://repository.ow2.org/nexus/content/repositories/snapshots/</url>
+        </repository>
```

And then updating the credentials in the Jenkins job. We could set it up as a GitHub Action if you configure the secrets for https://repository.ow2.org/ in the repository (see https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets), but if the Jenkins job works why change it?

**Comment by slarse** [comment]
FYI maven.irisa.fr appears to be back up again, so the matter is less pressing now. But since it's happened before we should probably still make the switch. Do you want me to create a PR with the above changes to the pom?
