### ISSUE TITLE
Feature: CtModifiable#isTransient

### ISSUE THREAD

**Issue by MartinWitt** [INRIA/spoon#3651]
Looking at CtModifiable class, there a lot of convenience method, but `isTransient` is missing? Is there any reason for it? 
A implementation could be the following. 
```java
public boolean isTransient() {
return this.hasModifier(ModifierKind.TRANSIENT);
}
```

http://spoon.gforge.inria.fr/mvnsites/spoon-core/apidocs/spoon/reflect/declaration/CtModifiable.html

Edit: I looks like some more Modifiers from `ModifierKind` are missing. Feel free to implement them also.
I created this as good first issue, because it's relative easy and no high priority change. Some1 can have an easy start with this issue.

**Comment by monperrus** [comment]
Excellent good first issue :)

**Comment by Artamm** [comment]
Hi! I'm new to an open source - can I try to do it?

**Comment by nharrand** [comment]
@Artamm Of course! That's the point of `good first issue`s!
