### ISSUE TITLE
help-wanted: how to properly add a field like `A a = new A(new B());`

### ISSUE THREAD

**Issue by gluckzhang** [INRIA/spoon#3663]
Hello! I just encountered a problem in adding fields in a class.

In order to do something like this:
```java
XStream xStream = new XStream();
```

I used the following code:
```java
CtField<?> xStreamField = factory.createCtField(
    "xStream",
    factory.createCtTypeReference(Class.forName("com.thoughtworks.xstream.XStream")),
    "new XStream()"
);
...
generatedClass.addField(xStreamField);
```

This part works well. Spoon also automatically adds the `import com.thoughtworks.xstream.XStream;` for the class.

**My question is:**

How should I do `XStream xStream = new XStream(new JettisonMappedXmlDriver());` instead? If I just change the expression string in `factory.createCtField()`, Spoon does not add the import for JettisonMappedXmlDriver automatically. Even if I use 

```java
generatedClass.getFactory().createUnresolvedImport("com.thoughtworks.xstream.io.json.JettisonMappedXmlDriver", false);
```

I still fail to add the import for class JettisonMappedXmlDriver. I am using Spoon `8.0.0` in my project. Thank you in advance!

**Comment by nharrand** [comment]
Hi @gluckzhang 

You can add your default initialization afterward like so:

```java
CtField<?> xStreamField = factory.createCtField(
	"xStream",
	factory.createCtTypeReference(Class.forName("com.thoughtworks.xstream.XStream")),
	"new XStream()"
);
xStreamField.setDefaultExpression(factory.createConstructorCall(
	factory.createCtTypeReference(Class.forName("com.thoughtworks.xstream.io.json.JettisonMappedXmlDriver"))
));
generatedClass.addField(xStreamField);
```

Instead of having your default initialization being a snippet, you'll have a real subtree with resolved reference to the type `JettisonMappedXmlDriver` that should be added to the import list.

**Comment by gluckzhang** [comment]
Hi @nharrand , thanks a lot! That's exactly what I am looking for :)
