### ISSUE TITLE
refactor: move from Log4j API to SLF4J API

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#3686]
For sake of future maintenance, we need to depend on the SLF4J API (instead of the Log4J API) 

See discussion in #3678

**Comment by MartinWitt** [comment]
As a small note: We can skip an anti corruption layer or any other abstraction and directly use sl4j. See [http://slf4j.org/faq.html#optional_dependency](http://slf4j.org/faq.html#optional_dependency) for reasoning.

**Comment by monperrus** [comment]
We could write a spoon transformation for this, to be applied on Spoon itself, and we would use the sniper mode to have a minimal diff.

**Comment by andrewbwogi** [comment]
I have a fix for this.
