### ISSUE TITLE
[Bug] Issues with CtClass::compileAndReplaceSnippets compiling method call after comment

### ISSUE THREAD

**Issue by lapplislazuli** [INRIA/spoon#3687]
Hi there,

I came accross an weird issue. 
I wanted to add an empty method to a class, as well as a simple method call in another method. 

## Expected Output 

From: 
```Java
class A {
    public int mult(int a, int b){
         return a * b;
    }
}
```
To: 

```Java
class A {
    public int mult(int a, int b){
         // New Comment
         otherMethod();
         return a * b;
    }
   
   private void otherMethod(){

   }
}
```

## Actual Output

after first compileAndReplaceSnippets:

```Java
class A {
    public int mult(int a, int b){
         // New Comment
         return a * b;
         return a * b;
    }
   
   private void otherMethod(){

   }
}
```

after second compileAndReplaceSnippets, it throws an error for unreachable code (which seems reasonable).

## Code to reproduce
```Java
    @Tag("Regression")
    @Test
    void testSnippetReplacement_ReplaceMethodCallSnippetAfterComment_shouldNotThrowError(){
        String initialClass = "package some; class A { public int mult(int a, int b){return a * b;}";

        CtClass<?> containingClass = Launcher.parseClass(initialClass);
        String methodName = "vanishingMethodCall";

        var methodToAlter= containingClass.getMethodsByName("mult").get(0);

        // Build an empty method, return void
        CtMethod emptyMethod = containingClass.getFactory().createMethod();
        emptyMethod.setSimpleName(methodName);
        emptyMethod.setParent(containingClass);
        emptyMethod.setType(emptyMethod.getFactory().Type().VOID_PRIMITIVE);
        emptyMethod.addModifier(ModifierKind.PRIVATE);
        emptyMethod.setBody(emptyMethod.getFactory().createBlock());

        containingClass.addMethod(emptyMethod);

        containingClass.compileAndReplaceSnippets();

        methodToAlter.getBody().addStatement(0,
                containingClass.getFactory().createCodeSnippetStatement(methodName+"()"));

        methodToAlter.getBody().addStatement(0,containingClass.getFactory().createInlineComment("I seem to break the test"));

        // This creates the double return
        containingClass.compileAndReplaceSnippets();
        // This fails the test, as the second return does not compile
        containingClass.compileAndReplaceSnippets();

        return;
    }
```

## Further Info / Considerations

This only occurs when there is a comment before the method. If you remove the line where the InlineComment is added, the test succeeds. 

It also duplicates longer statements, such as if-blocks. it seems to duplicate any statement after the comment.

## Other 

I am using `Spoon-Core 8.3.0`, in a maven project. Spoon is only used as a library. 

As a workaround, at the moment I'll try to not call the method with a snippet.

**Comment by Twonki** [comment]
Short addendum: 

This behaviour occurrs apparently on all comment types not only on inline comments. 

Also I'd be happy if you could give me a small pointer how to properly build the method invocation :)

**Comment by MartinWitt** [comment]
´The error is inside `SnippetCompilationHelper#compileAndReplaceSnippetsIn` `CtPath#evaluateOn` returns an empty List and we use `iterator.next();` on it [link]. Ignoring empty lists does not fix the problem.(https://github.com/INRIA/spoon/blob/1de9318fcb97fa99ba18c3fd40025163a55df89b/src/main/java/spoon/support/compiler/SnippetCompilationHelper.java#L85)
