### ISSUE TITLE
doc: write a Spoon snippet for https://stackoverflow.com/questions/10483423/java-code-transform-at-compile-time

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#3700]
The question of https://stackoverflow.com/questions/10483423/java-code-transform-at-compile-time is a perfect use case for Spoon.

The OP says "I thrive to find a simple example of java code preprocessing for [Spoon]" 

It would be great to have a Spoon snippet showing how it works.

**Comment by andrewbwogi** [comment]
I've posted an answer there.

**Comment by monperrus** [comment]
Thanks a lot @andrewbwogi
