### ISSUE TITLE
bug: Sniper printer always prints indentation for newly added elements with tabs

### ISSUE THREAD

**Issue by slarse** [INRIA/spoon#3715]
This is a big problem for [Sorald](https://github.com/spoonlabs/sorald), as we can't repair projects that don't use spaces for indentation. I've been looking through the sniper printer, and it doesn't appear as if there are any attempts in it to use anything but tabs to print indentation for new elements with the same style of indentation as there is in the source file.

What the sniper should do here is to infer the indentation style from the file. That's easy enough, just look at the indentation of any type members of the top-level type, and pick the best fit of 2/4 spaces or 1 tabs. That should be sufficient for the vast majority of projects and files.

Any input on this before I get to work on solving it? Have I missed something, perhaps?

**Comment by monperrus** [comment]
infer the indentation style from the file seems good to me.

**Comment by slarse** [comment]
Then that's the plan! I plan to get to work on it this afternoon and hope to have it done tomorrow, such that it can be merged before Saturday's beta release. It's urgently needed for my next steps in Sorald.
