### ISSUE TITLE
Question: how to add imports to classes

### ISSUE THREAD

**Issue by Twonki** [INRIA/spoon#3718]
Hi there, 

I am a bit lost adding an import. 

I (just) want to change a class 

```java
package something;

public class Example {
// ...
}
```

to 

```java
package something;

import java.utils.Arraylist;

public class Example {
// ...
}
```

There was a question similar to this #3333 but the issue was resolved without answering the import question.

**Comment by andrewbwogi** [comment]
Hi @Twonki, you can use a `CtCompilationUnit` to add imports. After creating it you add the `CtType` from your model, set the imports and print it using a `PrettyPrinter`. For instance:

```java
Factory factory = launcher.getFactory();
CtCompilationUnit unit = factory.createCompilationUnit();
unit.addDeclaredType(exampleClass);
unit.setImports(Arrays.asList(factory.createImport(factory.createReference("java.utils.Arraylist"))));
DefaultJavaPrettyPrinter defaultJavaPrettyPrinter = new DefaultJavaPrettyPrinter(factory.getEnvironment());
System.out.println(defaultJavaPrettyPrinter.printCompilationUnit(unit));
```

`CtCompilationUnit.setImports` is an experimental method however and it may be redesigned in the future.

**Comment by Twonki** [comment]
Thank you very much! 
Works like a charm.

For anyone else who might needs this, this is the code I currently use for what I needed: 

```Java

        // Add the import if it does not exist already
        var unit = containingclass.getFactory().CompilationUnit().getOrCreate(containingclass);
        var existingImports = unit.getImports();
        var reference= factory.createImport(factory.createReference("java.util.Arraylist"));
        if(!existingImports.contains(reference)){
            existingImports.add(reference);
        }
```

**Comment by sivakg2000** [comment]
@Twonki .. it's not working form me.
