### ISSUE TITLE
Get the name of the method in a CtInvocation

### ISSUE THREAD

**Issue by NunoCastanho** [INRIA/spoon#3724]
Hello.

How do I get the name of the method that's being invoked in a `CtInvocation`? I can get the type of the target and the arguments easily but I can't seem to find a way to get the name of the method. Is there even a way?

Thank you,
Nuno

**Comment by slarse** [comment]
Hi @NunoCastanho,

You need to get the executable reference.

```java
CtInvocation someInvocation = ...;
String name = someInvocation.getExecutable().getSimpleName();
```

**Comment by NunoCastanho** [comment]
Okay, thanks!

**Comment by slarse** [comment]
You're welcome :)
