### ISSUE TITLE
More accurate log about "no class path"

### ISSUE THREAD

**Issue by QifanWang** [INRIA/spoon#3728]
Hello, I'm working with Spoon 8.3.0, and I found when users create a new MavenLauncher like, 
```
MavenLauncher launcher = new MavenLauncher("<path_to_maven_project>", MavenLauncher.SOURCE_TYPE.APP_SOURCE);
```
it will log info
```
[INFO] Running in NOCLASSPATH mode (doc: http://spoon.gforge.inria.fr/launcher.html).
```
Even though MavenLauncher would automatically infer the dependencies from the pom.xml file and "buildClassPath" and "setSourceClasspath" while calling "init" method, 
https://github.com/INRIA/spoon/blob/77b8869bd99e710ea62f8944db6f077cced6da84/src/main/java/spoon/MavenLauncher.java#L193-L198
the "Running in NOCLASSPATH mode" log has been written in calling constructor of super class "Launcher".
Is this a confusing log? Could it be possible to log more accurate information about "class path mode"?

**Comment by andrewbwogi** [comment]
Hi @QifanWang, thanks for your questions! I'll take a look at this issue.
