### ISSUE TITLE
bug: CtTypeReference for a non-generic type is filled with type parameters

### ISSUE THREAD

**Issue by dya-tel** [INRIA/spoon#3733]
Calling `CtExecutable#getExecutableDeclaration()` somehow manages to add a type parameter to the `java.lang.Object` type reference in a TypeFactory. And, well, `java.lang.Object` shouldn't have any generics.

This problem could be somehow connected to [this line](https://github.com/INRIA/spoon/blob/7abce70c8b5742f5e2f1bc59151871dd1d2050c6/src/main/java/spoon/support/visitor/java/JavaReflectionTreeBuilder.java#L402) (`contexts.peek()` happens to be the said type reference), but I'm not too sure. Further investigation is a bit too much for me, sorry.

[Code to reproduce](https://github.com/INRIA/spoon/files/5710117/ObjectGenerics.zip). Just import the Gradle project and launch `Main` class. To get the stacktrace put a breakpoint on the `System.out.println("Type parameters before ...");`.
The used Spoon version is 8.4.0-beta-8, but it's reproducible _at least_ since [this commit](https://github.com/INRIA/spoon/commit/8f45c5f841b6036580904bfce6c4dabf1ee3eb40).

**Comment by andrewbwogi** [comment]
I'm taking a look at this.
