### ISSUE TITLE
Simple way of getting all types, including the types that are imported?

### ISSUE THREAD

**Issue by MaximoOliveira** [INRIA/spoon#3742]
Is there a simple way of getting the types that are imported in our program?

For example if my program only consists of class A :

```
package resources;

import java.util.HashSet;

class A{
...
}
```

When I get all the types the following way:

```
 launcher.buildModel();
 CtModel model = launcher.getModel();
 Collection<CtType<?>> allTypes= model.getAllTypes();
```

My collection has only one CtType (like it should have) which is Class A.

However I would like to get the class HashSet (as well as any other class that I import) into my Collection.

Does Spoon offer a simple way of doing this?

Thank you!

**Comment by andrewbwogi** [comment]
Hi @MaximoOliveira, you can get all types in your program by gathering type references from all typed elements:

```java
List<CtTypedElement> list = ctModel.getRootPackage().getElements(new TypeFilter<>(CtTypedElement.class));
Set<CtTypeReference> set = new HashSet<>();
for(CtTypedElement e : list){
    set.add(e.getType());
}
```

If you specifically want types that you have imported, you can use a `CtCompilationUnit`:

```java
CtType ctType = ctModel.getRootPackage().getElements(new TypeFilter<>(CtType.class)).get(0);
CtCompilationUnit unit = ctType.getFactory().CompilationUnit().getOrCreate(ctType);
ModelList<CtImport> imports = unit.getImports();
List<CtTypeReference> list = new ArrayList<>();
for(CtImport i : imports){
    list.add(factory.Type().createReference(i.getReference().getSimpleName()));
}
```

**Comment by MaximoOliveira** [comment]
Thank you @andrewbwogi, that was helpful!
