### ISSUE TITLE
Spoon Javadoc Not available

### ISSUE THREAD

**Issue by MaximoOliveira** [INRIA/spoon#3762]
When going to

 https://spoon.gforge.inria.fr/ -> Getting started -> Javadoc

The page is not found: https://spoon.gforge.inria.fr/mvnsites/spoon-core/apidocs

![image](https://user-images.githubusercontent.com/36827697/105071420-7af12280-5a7c-11eb-8105-e64aa52ac28f.png)

**Comment by monperrus** [comment]
Thanks for the report. Fixed.

This is due to the change in the doc infrastructure, see https://github.com/INRIA/spoon/issues/3759
