### ISSUE TITLE
specify and test getTarget of CtExecRefExpr

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#377]

**Comment by GerardPaligot** [comment]
See [here](https://github.com/INRIA/spoon/blob/master/src/test/java/spoon/test/methodreference/MethodReferenceTest.java#L58-L59), [here](https://github.com/INRIA/spoon/blob/master/src/test/java/spoon/test/methodreference/MethodReferenceTest.java#L71-L72), a little bit [here](https://github.com/INRIA/spoon/blob/master/src/test/java/spoon/test/methodreference/MethodReferenceTest.java#L84-L85), [here](https://github.com/INRIA/spoon/blob/master/src/test/java/spoon/test/methodreference/MethodReferenceTest.java#L97-L98) too, [here](https://github.com/INRIA/spoon/blob/master/src/test/java/spoon/test/methodreference/MethodReferenceTest.java#L110-L111), [here](https://github.com/INRIA/spoon/blob/master/src/test/java/spoon/test/methodreference/MethodReferenceTest.java#L123-L124) and finally [here](https://github.com/INRIA/spoon/blob/master/src/test/java/spoon/test/methodreference/MethodReferenceTest.java#L136-L137). :)

**Comment by monperrus** [comment]
It seems we specify a bug, it should always be `intanceof CtTypeAccess`.

And we should state the contract in getTarget() of the interface
CtExecRefExpr (so far we just reuse the generic contract of TargetExp)

**Comment by GerardPaligot** [comment]
The target of an executable reference expression isn't always a `CtTypeAccess`. You can do that `Type::method` but this too `var::method`. Checks test cases to know more.
