### ISSUE TITLE
Get type in an Array

### ISSUE THREAD

**Issue by NunoCastanho** [INRIA/spoon#3773]
Hello.

Is it possible to obtain the type that is being kept in an array? I know that given a `CtTypeReference` we can know if it's an array, but can we get the type kept in it? For example, given a CtTypeReference for `int[]` could I be able to obtain that the type is `int`?

Thank you,
Nuno Castanho

**Comment by slarse** [comment]
Hi Nuno,

If you know that a type reference is an array (for example by checking `isArray()`), then you can cast it to `CtArrayTypeReference` and get its _component type_.

```java
CtTypeReference<?> typeRef = [some type reference];
if (typeRef.isArray()) {
        CtArrayTypeReference<?> arrayTypeRef = (CtArrayTypeReference<?>) typeRef;
        CtTypeReference<?> compType = arrayTypeRef.getComponentType(); // this is what you want
}
```

**Comment by NunoCastanho** [comment]
Thanks!
