### ISSUE TITLE
Discussion : Does Spoon provides any support for these features ?

### ISSUE THREAD

**Issue by udit-dasari** [INRIA/spoon#3774]
Hi, i and my team want to know more about the various features that Spoon may support, so we came up with some requirements for our project :

- Control flow analysis
- support for binaries
- will it be maintained in future
- lexeme related data
- Data Dependancy graph
- Incremental support
- Data flow analysis
- any other features ?
- GotoDef edges
- Reference edges
- filtering nodes based on elementType

Can you please confirm the support for above features ?

**Comment by andrewbwogi** [comment]
Hi @udit-dasari, the [documentation](https://spoon.gforge.inria.fr/index.html) provides a good overview of features in Spoon. The [Navigation and Query](https://spoon.gforge.inria.fr/filter.html) section describes many ways to query ASTs, including filtering based on the element type.

For control and data flow analysis there is the [spoon-control-flow](https://github.com/INRIA/spoon/tree/master/spoon-control-flow) package. 

If by support for binaries you mean transformation of class files, there is the [spoon-decompiler](https://github.com/INRIA/spoon/tree/master/spoon-decompiler) package. 

There are several kinds of support available for your project, including this forum and [professional support](https://github.com/INRIA/spoon/issues/3251). 

The question of future maintenance I'm passing on to @monperrus.

**Comment by monperrus** [comment]
> will it be maintained in future

We all hope so. We've been able to maintain it for 16 years already.

**Comment by udit-dasari** [comment]
Hi @andrewbwogi , is there any way i can :
1. Prevent spoon from accessing the JVM classpath and provide all the jars i want through launcher.getEnvironment().setSourceClassPath() only?
2. Get the properties of an element in the form of map (key = property, value = property's value) or something similar without needing to check like say if it's a method and then looking for properties isStatic(), etc.For ex. Jdt parser provides a generic way to do that using ChildPropertyDescriptor, SimplePropertyDescriptor, etc.

**Comment by andrewbwogi** [comment]
When `launcher.getEnvironment().setNoClasspath(false)` and `setSourceClasspath` are used together, only the argument to `setSourceClasspath` should be set as the classpath. 

To get properties of an element through a single interface, you can use [getValueByRole](https://spoon.gforge.inria.fr/mvnsites/spoon-core/apidocs/spoon/reflect/declaration/CtElement.html#getValueByRole-spoon.reflect.path.CtRole-). It takes a [CtRole](https://spoon.gforge.inria.fr/mvnsites/spoon-core/apidocs/spoon/reflect/path/CtRole.html) (e.g. `CtRole.IS_STATIC`) and returns a value based on the element and the role argument.

**Comment by iamKunalGupta** [comment]
@andrewbwogi It is mentioned on the website that spoon uses either JVM or sourceClassPath to resolve, the NoClassPath mode merely prevents it from throwing exceptions in case a resolution is not found, it does not prevent spoon from using the classes currently loaded in the JVM:

> Case 2 (code available as binary in the classpath): the reference points to a code element for which the source code is NOT present, but for which the binary class is in the classpath (either the JVM classpath or the --source-classpath argument). In this case, reference.getDeclaration() returns null and reference.getTypeDeclaration returns a partial CtType built using runtime reflection. Those objects built using runtime reflection are called shadow objects; and you can identify them with method isShadow. (This also holds for getFieldDeclaration and getExecutableDeclaration)

https://spoon.gforge.inria.fr/launcher.html under `Resolution of elements and classpath`. Also it uses the `URLClassLoader` by default, so it should still load both JVM classpath as well as the classpath set in the `sourceClassPath`

**Comment by andrewbwogi** [comment]
@iamKunalGupta, it seems true that the JVM classpath is used even with `setSourceClasspath` and `setNoClasspath(false)` when the manually set classpath has a name that corresponds to a name in the JVM classpath. @udit-dasari, are you referring to this problem?

**Comment by udit-dasari** [comment]
@andrewbwogi, yes, even when i use `setSourceClasspath` and `setNoClasspath(false)` spoon is still able to access and load the JVM classpath, even if i don't pass a library in the `setSourceClasspath` the library is still being loaded if it is present in the JVM classpath

**Comment by nashid** [comment]
@monperrus  do you think in the near future Spoon would address the following gaps? 

- Control flow analysis
- Data flow analysis
- def-use analysis

There are so many tools in the JVM ecosystem and yet there is no tool that works reliably, is well-maintained, and has ok enough documentation.

Alternately, could you point me to any tool/library resource that can generate control flow and data flow effectively for JDK8+ code?

**Comment by monperrus** [comment]
Hi @nashid  See:

* https://github.com/INRIA/spoon/tree/master/spoon-control-flow
* https://github.com/INRIA/spoon/tree/master/spoon-dataflow

For def-use, nothing comes on the top of my head.

**Comment by monperrus** [comment]
Closing, thanks.
