### ISSUE TITLE
Query for depending classes

### ISSUE THREAD

**Issue by NunoCastanho** [INRIA/spoon#3777]
Hello.

Is it possible to get the classes in a model that depend on another? For example, assuming we have a `Launcher` loaded with the following classes and we built its model, I'd like to query for the classes that depend on A. As a result, I'd get the class B.

```
public class A{
    public void m(){

    }
}

public class B{
    public void m(){
        A a = new A();
        a.m();
    }
}
```

Thank you!

**Comment by andrewbwogi** [comment]
Hi, you could search for occurrences of type A in every class:
```java
if(!ctClass.filterChildren((CtTypeReference t)->t.getSimpleName().equals("A")).list().isEmpty())
    System.out.println("ctClass depends on A");
```
More generally, e.g. if the queried class depends on C that depends on A, you'd have to get the declaration of all types connected to the queried class and look for an occurrence of A in each one of them.

**Comment by slarse** [comment]
This is a pretty straightforward static analysis job, that's relatively easy to do with Spoon. Here's a general solution for finding the direct dependents of all types in the model:

```java
Launcher launcher = new Launcher();
launcher.addInputResource("project");
CtModel model = launcher.buildModel();

Set<CtType<?>> modelTypes = Collections.newSetFromMap(new IdentityHashMap<>());
modelTypes.addAll(model.getAllTypes());

Map<CtType<?>, Set<CtType<?>>> directDependents = new IdentityHashMap<>();

for (CtType<?> modelType : modelTypes) {
    List<CtTypeReference<?>> modelRefs = modelType.filterChildren(
            (CtTypeReference<?> ref) -> modelTypes.contains(ref.getTypeDeclaration())
    ).list();

    for (CtTypeReference<?> modelTypeRef : modelRefs) {
        Set<CtType<?>> dependents = directDependents.getOrDefault(
                modelType, Collections.newSetFromMap(new IdentityHashMap<>()));
        dependents.add(modelTypeRef.getTypeDeclaration());
        directDependents.putIfAbsent(modelType, dependents);
    }
}
```

The `directDependents` will contain a mapping from a type `T` in the model, to all other types `R` in the model such that `R` directly references `T`. To get the transitive dependents, you'll have to traverse the direct dependents map (taking care not to get stuck in a cyclic dependency).

**Comment by NunoCastanho** [comment]
Hello.

@slarse Thanks! I have resolved the issue in a different way given that the problem itself was slightly different. For instance, let's say:
- class A has method m()
- class B has methods m() and n()
- class B depends on A in method m() by calling A.m()
- class C has method m()
- class C depends on B in method m() by calling B.n()

My goal was to receive `B` when asking which classes depend on `A`. Class `C` does not depend on `A` because `B.n()` does not call on any method of `A`.

Nevertheless, I managed to solve the problem, thank you for your answer. Out of curiosity, how would you solve this issue?

(Also, out of the scope question but since you also use it in your code I'll ask. Is there a way to build a model ( `launcher.buildModel()`) faster? Because when I measure the time it's around 20s for that single call. The launcher itself has ~500 types, which I know might be a lot. I'm just wondering if I can reduce the time in any way)

**Comment by slarse** [comment]
@NunoCastanho Right, so the code I showed above will find compile dependence between classes, but it seems like you're after dataflow dependence. Then, you essentially need to do what I did with types above, but instead of using type declarations you need to use type member declarations, so the mapping would be something like `Map<CtTypeMember<?>, Set<CtTypeMember<?>>`.

With such a mapping, you can resolve the transitive closure of each type member, and once you have that closure, you simply get all unique type declarations from the contained type members. Starting out with just method type members (type members of type `CtExecutable`) instead of all type members is probably the easiest thing to do.

> (Also, out of the scope question but since you also use it in your code I'll ask. Is there a way to build a model ( launcher.buildModel()) faster? Because when I measure the time it's around 20s for that single call. The launcher itself has ~500 types, which I know might be a lot. I'm just wondering if I can reduce the time in any way)

Not really, but that build time does sound excessively long for just 500 types. What project are you trying to analyze, and with what hardware?

**Comment by NunoCastanho** [comment]
@slarse Okay, thanks, I'll give it a shot for that dataflow dependence.

Regarding the launcher part, I'm loading the source code of the subproject `spring-boot-autoconfigure` in `spring-boot`  of a specific commit. The hardware I'm working on is a personal computer with 8GB RAM and with an i7 processor.

**Comment by monperrus** [comment]
closing stale issue, thanks
