### ISSUE TITLE
Check if a CtClass compiles

### ISSUE THREAD

**Issue by jhonvve** [INRIA/spoon#3784]
Hello!

How can we see if a particular CtClass has any compilation error or not?

**Comment by andrewbwogi** [comment]
Hi @jhonvve, you can use [templates](https://spoon.gforge.inria.fr/template_definition.html) to transform your code. They use static type-checking to make sure that your transformed code will compile if the original code compiles.

Another option is to write the pretty-printed CtClass to a file, say `SpoonedClass.java`, and compile it with a `JavaCompiler` from the Java library:
```java
JavaCompiler compiler = ToolProvider.getSystemJavaCompiler();
int success = compiler.run(null, null, null, "/path/SpoonedClass.java");
if(success == 0)
    System.out.println("CtClass compiles");
else
    System.out.println("CtClass does not compile");
```

**Comment by jhonvve** [comment]
Thank you @andrewbwogi !

Do you know if it is possible to do this without having to write the pretty-printed CtClass to a file.

 If it possible to get a list of compilation error given a CtClass?

**Comment by andrewbwogi** [comment]
There is no ready mechanism in Spoon to determine if the CtClass will compile based on the AST alone.

**Comment by nharrand** [comment]
But you can get compilation error from JDT through the launcher.

```java
  JDTBasedSpoonCompiler compiler = (JDTBasedSpoonCompiler) launcher.getModelBuilder();
  List<CategorizedProblem> problems = compiler.getProblems()
	  .stream()
	  .collect(Collectors.toList());
```

You can add filters to check that the error's position correspond to your CtClass.

**Comment by monperrus** [comment]
If you have a default constructor and ctClass.newInstance() returns an object, it means it compiles.

**Comment by jhonvve** [comment]
Thank you!
