### ISSUE TITLE
Disconnected control-flow graph when building a CFG for a method with a switch case statement

### ISSUE THREAD

**Issue by udit-dasari** [INRIA/spoon#3787]
Hi, i'm using spoon-control-flow graph to build a cfg for a method which contains a switch case statement and the control flow graph i'm getting is disconnected (There is an edge missing).

Here is the function i'm building CFG for: 

```
public void fun()
    {
        int a = 10;
        int b=0;
        switch(a)
        {
            case 1:
            b=10;
            case 2:
            b=20;
        }
        System.out.println("Not Connected");
    }
```

Code for building the CFG: 

```
val builder = ControlFlowBuilder()
val cfg = builder.build(ctMethod) // ctMethod corresponds to the above method
cfg.simplify()
cfg.toGraphVisText()
```

The generate graph: 
![test](https://user-images.githubusercontent.com/76946379/107364604-a908d600-6b01-11eb-8452-11705f45f8f4.png)

There is an edge missing between statement: 70 and statement: 72

**Comment by andrewbwogi** [comment]
I'll see if I can reproduce this.
