### ISSUE TITLE
bug/chore: ParallelProcessor tests are flaky

### ISSUE THREAD

**Issue by slarse** [INRIA/spoon#3806]
> By merge there were problems in our CI see https://github.com/INRIA/spoon/runs/1726213633. At first glance it looks like a race condition in ParallelProcessor on windows(argh)

_Originally posted by @MartinWitt in https://github.com/INRIA/spoon/issues/3755#issuecomment-763401113_

This now just happened again, but in a different test: https://github.com/INRIA/spoon/runs/1969383888#step:5:12462

Perhaps we should disable this test on Windows until someone can dedicate some time to the Windows compatibility issues.

**Comment by slarse** [comment]
To be clear, we've had flaky failures in `compareWithSingleThreaded1` and `compareWithSingleThreaded3`. I'd suggest disabling all `compareWithSingleThreadedX` tests until someone can deal with this.

**Comment by slarse** [comment]
Actually, `compareWithSingleThreaded2` probably does not need to be disabled as it runs on a single thread.

**Comment by slarse** [comment]
Okay, now there was a failure on Ubuntu: https://github.com/INRIA/spoon/runs/1969811221?check_suite_focus=true#step:5:15517

So these tests are just flaky.

**Comment by slarse** [comment]
I'll try to have a look at what's causing the test failures tomorrow. I've no idea of what the parallel processing architecture looks like, so I may or may not be able to debug this with the little time I can spare to it.

**Comment by slarse** [comment]
Step one here is to improve the assertions in the tests to let us actually see what the "wrong" output is, the next time it happens.

**Comment by MartinWitt** [comment]
I hoped my documentation about what I was testing was enough. See https://github.com/INRIA/spoon/blob/eac3535a6ffaa30db1beb829f7363a6f49f50e79/src/test/java/spoon/test/processing/processors/ParallelProcessorTest.java#L80
More or less I test If the parallelprocessor visits the some number of elements as a normal processor.

**Comment by slarse** [comment]
@MartinWitt you misunderstand me, I didn't mean I don't understand _what's_ being tested, I meant that the assertion just says "nope". I want to see what the numbers are :)

**Comment by slarse** [comment]
I.e. this is the failure info:

```
java.lang.AssertionError
	at spoon.test.processing.processors.ParallelProcessorTest.compareWithSingleThreaded1(ParallelProcessorTest.java:87)
```

But if we use Hamcrest matchers, we'll get the actual numbers! We'll see which counter is off (probably the parallel ones, but who knows), and we'll see by how much, and in which direction.

**Comment by MartinWitt** [comment]
Oh sry, yeah that would have been way better to output numbers and not a simple correct/wrong.
Looking at my old code I believe in `processingDone` https://github.com/INRIA/spoon/blob/eac3535a6ffaa30db1beb829f7363a6f49f50e79/src/main/java/spoon/processing/AbstractParallelProcessor.java#L136 is a `awaitTermination` missing. ProcessingDone is called after the last element was supplied(otherwise the interrupt method is called correct?). https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ExecutorService.html#awaitTermination-long-java.util.concurrent.TimeUnit- The number of parallel visited nodes should be close but below the single thread visited numbers.

**Comment by slarse** [comment]
> The number of parallel visited nodes should be close but below the single thread visited numbers.

Very good info, thanks! I just added the new asserts, I intend to trigger CI a few times to see if they blow up (it happened _a lot_ yesterday).

**Comment by slarse** [comment]
Having looked over the code, I agree that the missing `awaitTermination` is very likely the cause of the problem.

> otherwise the interrupt method is called correct?

All interrupts look fine to me. I scanned it with Sonar just to be sure, and it doesn't complain about unhandled interrupts.

**Comment by slarse** [comment]
@MartinWitt Would you like to implement the `awaitTermination` fix? You spotted it so it's your contribution to make, if you want to. I'm fairly confident it will solve the issue, the only question is for how long to await termination.

**Comment by slarse** [comment]
Aha, now we have proof for the theory, the parallel processors don't have time to finish: https://github.com/INRIA/spoon/runs/2054666431#step:5:15890

**Comment by slarse** [comment]
There's a slight complication here, in that the only reliable way to actually allow all processors to run to completion within an ExecutorService is to run with `ExecutorService.invokeAll()`. Using `awaitTermination` isn't really suitable, because, for how long should we wait? Regardless of the wait time we choose, I can always break it by sleeping for a while longer in any of the processors.

With the current design, I think the best way to solve the race condition is to poll for completion (once every X.Y seconds), rather than to wait an arbitrary time for completion.
