### ISSUE TITLE
API function `replace` doesn't replace a class with a CtClass instance

### ISSUE THREAD

**Issue by algomaster99** [INRIA/spoon#3827]
I am trying to execute the following piece of code.

```java
System.out.println(originalElement);
System.out.println(uniqueParent);
((CtClass) originalElement).replace((CtClass) uniqueParent);
```

where

`originalElement` is
```java
class Already {}
```
and `uniqueParent` is
```java
class Already {
    class Klass {}
}
```

However, when I try to replace `originalElement` with `uniqueParent`, it doesn't work. I have tried the replace API with other elements such as `CtMethod` and it works there. I wanted to know if this is the intended behaviour with `CtClass` or is it supposed to be a bug?

**Comment by slarse** [comment]
Hi @algomaster99 ,

What exactly isn't working? Can you show a more complete example? In particular, how are the two classes created?

Classes are, let's say, a little bit "global" in the metamodel, so when manipulating them you have to be a careful with what you do. For one, you can't have two classes with the same qualified name in the same model (and if you find a way to make that work, it's most likely a bug!).

As an example, let's assume I'm in a state where I've got the `originalElement` version of `Already`, and then create the other one.

```java
CtClass<?> uniqueParent = originalElement.getFactory().createClass("Already");
```

Somewhat unintuitively, creating a class like this effectively replaces `originalElement` with `uniqueParent` in the model, as when you add a class to a package, any class with the same qualified name is removed. This is AFAIK an undocumented implementation detail, we'll have to see to that. Perhaps there should even be an exception here, but that'd be a breaking change so we'll probably not do that :)

Thus, if you later call `originalElement.replace(uniqueParent)`, it's more or less a no-op as `originalElement` has already been replaced. Depending on the order of operations, you may get varying degrees of strange results.

**Comment by andrewbwogi** [comment]
I think the problem here is that if you do `originalElement.replace(uniqueParent)`, `originalElement` will not hold the object referenced by `uniqueParent`. In general, this seems unavoidable because the original element could be replaced by an element of a different type. 

If you want an element where the replacement has been made, you could use `originalElement.getParent()`. In this case, it will return a `CtPackage` that has a type element referenced by `uniqueParent` instead of `originalElement`. I'm guessing that when you used `replace` on a `CtMethod`, you checked the change with an enclosing element such as a `CtClass` and not that `CtMethod` itself.

**Comment by algomaster99** [comment]
Thank you for your response, @slarse !

I have two files in my system. _Replaced `Already` with `OldKlass`_.

**prev.java**
```java
class OldKlass { }
```

**new.java**
```java
class OldKlass {
    class Klass {}
}
```

I compared them and found that there is only one [operation](https://github.com/SpoonLabs/gumtree-spoon-ast-diff/blob/master/src/main/java/gumtree/spoon/diff/operations/Operation.java#L15) between them.

```sh
Insert Class at OldKlass:2
	class Klass {}
```

I fetched the [srcNode](https://github.com/SpoonLabs/gumtree-spoon-ast-diff/blob/master/src/main/java/gumtree/spoon/diff/operations/Operation.java#L115) from the operation and tried to replace the CtElement of the **prev.java** (`originalElement`) with `uniqueParent`. I found `uniqueParent` by iterating over the CtElement of **prev.java** and checking if the element inside follows two criteria:
1.  `(uniqueParent instanceof CtClass)`
2. `((CtFormalTypeDeclarer) originalElement).getSimpleName().equals(((CtFormalTypeDeclarer) uniqueParent).getSimpleName())`

Once I found `uniqueParent`, I simply called `((CtClass) originalElement).replace((CtClass) uniqueParent);` which didn't _replace_ the class.

I know this isn't the correct method because of your explanation [here](https://docs.google.com/document/d/1G3c6gCxRJU2x4jHJgClmvyFG3yAimouw8freBh8mGAU/edit?disco=AAAALo89kxw). However, I am just confused why `replace` API doesn't work with classes when it was working in case of `CtMethod`.

> For one, you can't have two classes with the same qualified name in the same model

I don't think that is the case because I have these classes in two different files.

Thanks @andrewbwogi !
> In general, this seems unavoidable because the original element could be replaced by an element of a different type.

That's why I am checking the type first (`instance of` operator) and then replacing the class. Also, I am calling the API only when `uniqueParent` and `orginalElement` can be typecasted to `CtClass`.

**Comment by slarse** [comment]
> > For one, you can't have two classes with the same qualified name in the same model
> 
> I don't think that is the case because I have these classes in two different files.

It's a name collision, which can't be consolidated within a single model.

> I compared them and found that there is only one [operation](https://github.com/SpoonLabs/gumtree-spoon-ast-diff/blob/master/src/main/java/gumtree/spoon/diff/operations/Operation.java#L15) between them.

Ah, so you're using `AstComparator.compare(File, File)` in `gumtree-spoon`? That creates _two_ models, one for each input file. In general, combining models is pretty error prone. As different models have different factories, some things don't work correctly. Spoon isn't really designed for it. That being said, it's totally possible, I combine [three models in my merge tool Spork](https://github.com/KTH/spork).

I'm not sure what the behavior is when you try to replace a class from one model with a class from another model. As there's funky behavior within a single model, I'm guessing there may be equally funky behavior when working across models. I'll look into it.

**Comment by algomaster99** [comment]
@slarse 
> It's a name collision, which can't be consolidated within a single model.

Yeah, right. I have two different models so " you can't have two classes with the same qualified name in the same model" shouldn't be an issue.

> I'm not sure what the behavior is when you try to replace a class from one model with a class from another model.

Considering the above example, nothing happens as of now. Neither a transformation nor an error is thrown.

> As there's funky behavior within a single model

Could you please elaborate? I would like to know.

> I'm guessing there may be equally funky behavior when working across models

If I try to replace an instance of `CtMethod` instead of a `CtClass`, it is successfully performed. For example,

**prev.java**
```java
class OldKlass {
    public static void main(String args[]) {}
}
```

**new.java**
```java
class OldKlass {
    public static void main(String args[]) {
        System.out.println("I was added!");
    }
}
```

If `originalElement` is the node:
```java
public static void main(String args[]) {}
``` 
in **prev.java**

and `uniqueParent` is the node:
```java
 public static void main(String args[]) {
        System.out.println("I was added!");
    }
```  
in **new.java**

Running `((CtClass) originalElement).replace((CtClass) uniqueParent);` successfully replaces the function in `originalElement`.

**Comment by slarse** [comment]
I just tried replacing a class from one model with a class from another model, and found no problems. It works as expected.

When you say "nothing happens", _where_ are you looking? This relates back to what @andrewbwogi said, you will only see the effects of replacing a class by looking at its parent (in this case, the parent is a package, but it could be another type as well in the general case).

> I'm guessing that when you used replace on a CtMethod, you checked the change with an enclosing element such as a CtClass and not that CtMethod itself. If you want an element where the replacement has been made, you could use originalElement.getParent(). In this case, it will return a CtPackage that has a type element referenced by uniqueParent instead of originalElement.

Assuming, that `lhs` and `rhs` are types from two different models, possibly with the same qualified names, the following code snippet works as expected:

```java
CtPackage lhsPkg = lhs.getPackage();
System.out.println(lhsPkg.getTypes()); // prints lhs

lhs.replace(rhs);

System.out.println(lhsPkg.getTypes()); // prints rhs
```

So, where are you looking for changes?

**Comment by algomaster99** [comment]
> I just tried replacing a class from one model with a class from another model, and found no problems. It works as expected.

Did the body of the class got replaced? For example, if any methods or class variable declarations were added or not.

> So, where are you looking for changes?

I prettyprinted the `originalElement` and checked if it changed or not. I expected the body of the class would change but it did not when I prettyprinted it.

**Comment by slarse** [comment]
> Did the body of the class got replaced? For example, if any methods or class variable declarations were added or not.

I think you misunderstand what it means to replace a node: when running `lhs.replace(rhs)`, `lhs` is _not_ mutated. What happens is that `rhs` takes the place of `lhs` in the model, but if you inspect `lhs` in isolation, it will look the same as it did before calling `replace()`.

To illustrate, let's say I have one model `lhsModel` with a class `Klass` with a method `m()`. If we consider that the model starts from the unnamed (default) package (it doesn't, but for illustration purposes it's sufficient), it will schematically look like this:

```
// lhsModel
CtPackage: unnamed_pkg
    |
    |------ CtClass: Klass
                  |
                  |------- CtMethod: m
```

Now, let's say we rename `Klass` to `Klassy` and build another model `rhsModel` of that. It results in the following model:

```
// rhsModel
CtPackage: unnamed_pkg
    |
    |------ CtClass: Klassy
                  |
                  |------- CtMethod: m
```

If I now have that `lhs = Klass from lhsModel` and `rhs = Klassy from rhsModel` and run `lhs.replace(rhs)`, the the effect on `lhsModel` is the following:

```
// lhsModel
CtPackage: unnamed_pkg
    |
    |------ CtClass: Klassy
                  |
                  |------- CtMethod: m
```

_However_, without considering the larger picture of the model, `lhs` itself is still this:

```
// lhs
CtClass: Klassy
          |
          |------- CtMethod: m
```

Thus, you can only see the effect of `lhs.replace(rhs)` by considering the parent of `lhs`. Note however that `replace()` also does something like so: `rhs.setParent(lhs.getParent())`. So it does mutate `rhs`, but not `lhs`.

> I prettyprinted the originalElement and checked if it changed or not. I expected the body of the class would update (replaced) but it did not when I prettyprinted it.

This would be the case if you replaced the _body_ of the class, but that's not what you've done. You've replaced the entire class. The effect of replacing an element is never visible directly in the replaced element.

**Comment by algomaster99** [comment]
@slarse thank you for the elaborate explanation! It's crystal clear to me why I couldn't see any _difference_. Although if I may ask a bit about the semantics, why the effect isn't reflected in the replaced element?

**Comment by slarse** [comment]
The semantics of `original.replace(replacement)` are to _replace_ `original` with `replacement`, in the model of `original`. It's a simple substitution: take the element referenced by `replacement` and put it in the place in the model currently occupied by `original`. The way to think about it is that it is an operation on the _model_, rather than on the individual element the method is called upon.

Arguably, this is not super intuitive, and a more intuitive API would perhaps be something like `model.substitute(original, replacement)`. But `original.replace(replacement)` is less verbose and pretty convenient in practice, once you understand how it works.

**Comment by algomaster99** [comment]
Closing this issue as my question is answered :)
