### ISSUE TITLE
Remove/migrate all remaining Travis stuff

### ISSUE THREAD

**Issue by slarse** [INRIA/spoon#3836]
As we're unlikely to ever return to Travis CI, references to Travis are confusing, e.g. the directory containing the CI scripts being called `chore/travis` and the `.travis.yml` config file being present. We should remove anything that is no longer necessary, and rename everything else appropriately.

In the process of removing the Travis CI traces, we should also ensure that we've migrated all functionality that we want over to GitHub Actions.

Known other problems:

* The "external CI" scripts are not being pulled as they depend on Travis environment variables: https://github.com/INRIA/spoon/blob/4880da00459c28f920d66cb0f5630c8427fb57c3/chore/travis/ci-extra.sh#L101-L105

**Comment by KishkinJ10** [comment]
hello sir , i am a beginner and i am participating in the GSoC 2021 with Project Spoon , sir can you please brief me what are we going to do in this project ?? and how can i write timeline section in my proposal?

**Comment by slarse** [comment]
@KishkinJ10 sorry, I missed this comment. Hope you found your way to the GSoC issue #3828.

Closing this as #3834 removed the final traces of Travis.
