### ISSUE TITLE
Major Release Spoon 9.0.0

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#3845]
Release to come, what a nice changelog, thanks a lot to all contributors!

# New features

* Print minimal amount of round brackets in sniper mode. (PR: #3823)
* Make sniper printer infer indentation style of compilation unit. (PR: #3717)
* Add CtModifiable#isTransient and related methods. (PR: #3670)
* Add support for pretty-printing Java 15 text blocks. (PR: #3664)
* spoon-smpl: Initial support for the semantic patch language (Credits: Mikael Forsberg). (PR: #3282)

# Breaking changes

* Use slf4j API instead of log4j-api. (PR: #3755) / Use self-defined logging level instead of org.slf4j.event.Level. (PR: #3796)
* Consolidate a consistent behavior for CtElement#getParent. (PR: #3793)

# Bug fixes

* Fix sniper printing of comments when changing modifiers. (PR: #3701)
* Fix unqualified type reference in catch block becoming qualified. (PR: #3800)
* Prevent ImportCleaner from importing inherited static methods. (PR: #3798)
* Fix NPE due to duplicated package-info.java with setIgnoreDuplicateDeclarations(true). (PR: #3791)
* Search for packages in all available Java modules. (PR: #3771)
* Correctly sniper-print type member comments after removal of all modifiers. (PR: #3747)
* ParentNotInitializedException in AbstractTypingContext. (PR: #3741)
* Classpath mode logging in MavenLauncher. (PR: #3750)
* Fix sniper-printing of method imports. (PR: #3744)
* Custom URLClassLoaders are now actually used. (PR: #3818)
* Fix NPE in ReferenceBuilder#tryRecoverTypeArguments. (PR: #3737)
* Avoid import duplication on unresolved imports. (PR: #3730)
* Source position when there is a comment character in annotation. (PR: #3720)
* Fix pretty-printing of imports for static methods. (PR: #3716)
* Dependency rg.tukaani:xz should have a test scope. (PR: #3832)
* Fix NullPointerException when allowing duplicate classes. (PR: #3709)
* Fix incorrect parent for type reference of a CtParameter. (PR: #3696)
* Fix Sniper printer failing to put added import statement on separate line. (PR: #3702)
* Fix NullPointerException in SniperJavaPrettyPrinter.printTypes. (PR: #3676)
* More resilient wrt to errors during shadow class building. (PR: #3655)
* CtCase: Add fix for missing parents. (PR: #3695)
* pom.xml: Fix jar execution on Java 11. (PR: #3678)
* sniper: Fix rounding error in indentation detection on single type member. (PR: #3722)

# Refactoring

* Improve error message when sniper printer is set after building model. (PR: #3694)
* Throw informative exception when sniper printing cannot be done. (PR: #3764)
* Add support for malformed files through inheritance. (PR: #3668)
* Better name for spoon-control-flow. (PR: #3665)
* ArchitectureEnforcer: Replace treeSet with hashset. (PR: #3661)
* javadoc: Remove old pair class and replace it with commons-lang3 class #3660. (PR: #3660)

# Performance

* Move code outside loop in FileCompilerConfig.initializeCompiler. (PR: #3815)
* Handle some concurrency in ModelSet. (PR: #3736)

# Authors
| Name    | Nb Commit |
|---------|-----------|
| renovate[bot] | 28 |
| Simon Larsén | 27 |
| andrewbwogi | 7 |
| MartinWitt | 6 |
| Martin Monperrus | 6 |
| dya-tel | 4 |
| Artamm | 3 |
| Mikael Forsberg | 2 |
| César Soto Valero | 2 |
| Lakshya A Agrawal | 1 |
| Maxim Stefanov | 1 |
| Horia Constantin | 1 |
| Darius Sas | 1 |
| Rick Kellogg | 1 |
| Benjamin DANGLOT | 1 |

**Comment by slarse** [comment]
The following two bullet points should be under breaking changes:

* Consolidate a consistent behavior for CtElement#getParent. (PR: #3793)
    - Breaking because `CtElement#getParent(Filter)` no longer throws an exception
* Use self-defined logging level instead of org.slf4j.event.Level. (PR: #3796)
    - Breaking for all the same reasons that #3755 is breaking, but actually defines the current behavior

**Comment by monperrus** [comment]
thanks @slarse updated the changelog

**Comment by surli** [comment]
Since the change looks pretty important, does it need a new release of Spoon Maven Plugin, or is the maven plugin still works with that version?

**Comment by monperrus** [comment]
I don't expect breakage in Spoon-maven-plugin. However, a release of it would be nice after this major of spoon-core, would you take care of this @surli? Thanks!

**Comment by monperrus** [comment]
Release done.

**Comment by monperrus** [comment]
https://repo1.maven.org/maven2/fr/inria/gforge/spoon/spoon-core/9.0.0/
