### ISSUE TITLE
Snapshot deployment job is broken (DepClean bytecode version)

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#3848]
The snapshot deployment job on SOS is broken: https://ci.inria.fr/sos/job/Spoon-Snapshot-Deployer/3378/display/redirect

It seems it's due to the bytecode version of DepClean.

@cesarsotovalero WDYT?

**Comment by slarse** [comment]
We are deploying with Java 8, according to the error message the depclean plugin has been compiled with Java 11.

> se/kth/depclean/DepCleanMojo has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

**Comment by slarse** [comment]
JDK11 is a requirement of depclean: https://github.com/castor-software/depclean#installing-and-building-from-source

So we can't use it in the deployment job.

**Comment by monperrus** [comment]
What about moving the deployment job to Java 11?

**Comment by slarse** [comment]
If we deploy with Java 11, Java 8 clients can't use the generated jars (they'll get the same error we're getting here). So, deploying with Java 11 effectively means abandoning Java 8 support, at least for the snapshots.

We really only have two options: Don't run Depclean on deploying, or deploy with Java 11, thus rendering deployed artifacts unusable to <11.

**Comment by cesarsotovalero** [comment]
This issue has been fixed in DepClean recently, see https://github.com/castor-software/depclean/issues/25

[This article](https://www.baeldung.com/java-lang-unsupportedclassversion) clarifies the issue and the solution.

Abandoning the support for clients that require Java 8 is not a good idea for Spoon IMHO. I had made a minor release of DepClean, so updating the plugin to version 2.0.1 should solve the problem.

**Comment by slarse** [comment]
@cesarsotovalero Ah, so we just started using DepClean with the most unfortunate timing then :)

> I'm sorry for the issue.

No worries! I'll keep a lookout for the new release and update the dependency when it hits central. Perhaps @renovate-bot will even do it for us?

**Comment by slarse** [comment]
> Perhaps @renovate-bot will even do it for us?

It did! #3849

**Comment by cesarsotovalero** [comment]
It seems that renovate indexes new dependency versions before [Sonatype](https://search.maven.org/artifact/se.kth.castor/depclean-maven-plugin).

**Comment by monperrus** [comment]
Jenkins build is back to normal : Spoon-Snapshot-Deployer 
https://ci.inria.fr/sos/job/Spoon-Snapshot-Deployer/3379/display/redirect?page=changes

Thanks Simon & Cesar

**Comment by slarse** [comment]
> It seems that renovate indexes new dependency versions before Sonatype.

I noticed that, too. It was however possible to access the Maven page with the direct url (https://search.maven.org/artifact/se.kth.castor/depclean-maven-plugin/2.0.1/maven-plugin), and the artifacts as well.

> Jenkins build is back to normal : Spoon-Snapshot-Deployer

Then I'm closing this issue with the Triage powers invested in me!
