### ISSUE TITLE
chore/bug: Sniper printer tests with literal newlines in assertions fail on Windows

### ISSUE THREAD

**Issue by slarse** [INRIA/spoon#3857]
Not sure what's causing this, the sniper printer should respect the newline style used in the source file. See #3856 for an example.

**Comment by monperrus** [comment]
progress made with https://github.com/INRIA/spoon/pull/3881

**Comment by slarse** [comment]
Oh, not only progress, this is entirely fixed. Completely forgot that this issue existed.

For future reference, the problem was that on checkout, Git converted LF line endings to CRLF line endings (`core.autocrlf` feature). As the sniper printer is expected to honor the _actual_ line endings (which in the eyes of the tests are LF), and not the system default, this caused the tests to fail as the test source files had their line endings auto-converted, but the literals in the tests were unchanged.
