### ISSUE TITLE
Add method to insert type parameters at particular indices

### ISSUE THREAD

**Issue by algomaster99** [INRIA/spoon#3894]
As addressed in the issue [here](https://github.com/INRIA/spoon/issues/3884#issuecomment-823092037), `diffmin` requires methods for inserting `CtElement`s at particular indices in collections. One such collection, of type parameters, is derived using `CtClass.getFormalCtTypeParameters()`. This issue is a request for a method that would allow us to insert a type parameter at a particular index.

Like https://github.com/INRIA/spoon/pull/3885, the method can be called `CtFormalTypeDeclarer.addFormalCtTypeParameterAt`.

**Comment by slarse** [comment]
Thanks for the feature request. I'm just going to incorporate this into #3884 so we keep track of all of these related features.
