### ISSUE TITLE
Add method to insert parameters at particular indices

### ISSUE THREAD

**Issue by algomaster99** [INRIA/spoon#3895]
As addressed in the issue [here](https://github.com/INRIA/spoon/issues/3884#issuecomment-823092037), `diffmin` requires methods for inserting `CtElement`s at particular indices in collections. One such collection is of parameters. This issue is a request for a method that would allow us to insert a parameter at a particular index.

Like https://github.com/INRIA/spoon/pull/3885, the method can be called `CtMethod.addCtParameterAt`.

**Comment by slarse** [comment]
Again, thanks for the feature request, to keep better track of it all I'll incorporate it into #3884 :)
