### ISSUE TITLE
Feedback about Spoon's dependency management 

### ISSUE THREAD

**Issue by imjhonny** [INRIA/spoon#3899]
Hello, we built a [tool to identify bloated dependencies](https://github.com/castor-software/depclean) on Java dev trees. 

DepClean was used on Spoon's codebase and built a visual rendering of all the project's dependencies. 

We would love it if you could take 7min of your time to look at this rendering and provide feedback. 

If you are interested you can go to [this link](https://haqc929te3d.typeform.com/to/IAjqnb7o)

Thanks a lot 

DepClean team

**Comment by monperrus** [comment]
Gave feedback!
