### ISSUE TITLE
Question regarding use of type variable in class CtType

### ISSUE THREAD

**Issue by ningvin** [INRIA/spoon#3920]
I recently started playing around with Spoon and stumbled over the fact that class `CtType` is generic over the type variable `T`:
```java
public interface CtType<T> ...
```

The type variable seems to propagate to a lot of classes in the hierarchy, e.g. all classes extending `CtTypedElement`.

However I am not seeing any obvious uses of the type variable, apart from the methods `CtType.getActualClass()` (which is deprecated) and `CtClass.newInstance()`.

Instead the type variable seems to make handling typed elements a lot more awkward. The official documentation is switching between using type wildcards and simply using the raw type (which creates warnings).

Is there something I am missing here and there is more to this type variable? Or is this an artifact of past design decisions and only left for compatibility reasons?

**Comment by andrewbwogi** [comment]
Hello @ningvin, you can also use generic typing to restrict how `CtType` objects are used. You could for instance statically verify that a method is invoked with a particular parameterized `CtType` object as an argument:

```java
public void operateOnSomeType(CtType<SomeType> t) { ... }

public void someMethod() {
    CtType<SomeType> someType = getSomeType();
    CtType<OtherType> otherType = getOtherType();
    operateOnSomeType(someType);  // compiles
    operateOnSomeType(otherType); // does not compile
}
```

**Comment by ningvin** [comment]
Thanks for your answer @andrewbwogi :)

Yes, you are absolutely right: if I know the exact type at compile-time this can be very useful.

I am still a bit confused however when it comes to handling potentially unknown types at runtime, where I have to use type wildcards:

```java
Launcher launcher = new Launcher();
launcher.addInputResource(...);
launcher.run();
CtModel model = launcher.getModel();
List<CtVariable<?>> variables = model.getElements(new TypeFilter<>(CtVariable.class));
// no concrete type possible in general --> type wildcard
```

The above works fine and for a lot of things the type wildcards are not relevant.

But let's assume I want to change the type of such a variable:

```java
CtVariable<?> variable = variables.get(0);
CtTypeReference<Foo> fooTypeRef = createSomeTypeReference();
variable.setType(fooTypeRef); // ERROR: method not applicable for arguments
```

I would have to use the raw type for either the variable or the type reference to get this to compile as far as I can see.

But again, I only just started using Spoon, so maybe there is a more "spoony" way of doing this ;)

**Comment by slarse** [comment]
I think this is something of a sore spot in Spoon, but it's really hard or perhaps impossible to "fix"

First off, the type variable in `CtType` represents the concrete type being modeled. So, for example, `CtType<String>` says that you've got a model of the `String` type. This is evident for example when looking at the (though deprecated) `CtType.getActualClass()`, which returns `Class<T>`.

There are two primary problems, really. First, the meaning of the type variable is rarely documented (although we're starting to amend that, see #3923). This confused me _a lot_ when I started out, and even a more than a year later, it still does at times. Having to browse the source code to understand the meaning of a type variable is not ideal.

Second, there are tons of methods that simply return types with wildcards in the type parameters, making certain uses rather awkward. The alternative to this is however often to use a return-type-only type parameter (which many methods _also_ do, see e.g. `CtType.getNestedType()`), which is also problematic as it provides a false sense of compile-time safety (type errors can only be found at runtime as the underlying implementation relies on casting).

This summarizes to the type system often getting in your way, and working with it properly really requires quite a deep understanding of Java generics (and sometimes casting is necessary). One typical way you can work with wildcards is to _capture_ them in another type variable. For example, with a method like this:

```java
	static <T> void changeType(CtVariable<T> var) {
		CtTypeReference<T> typeRef = var.getFactory().createTypeReference();
		var.setType(typeRef);
	}
```

And then you can call it like so:

```java
CtVariable<?> variable = variables.get(0);
changeType(variable);
```

That captures the wildcard `?` into the type variable `T`, such that you can use it for _other_ wildcard-returning methods. Obviously this particular method doesn't make much sense as it sets an empty type, but the principle should be clear I hope.

Most often you can get away with a combination of wildcards and captures, but on some rare occasions casting is the only way to get what you want.

**Comment by ningvin** [comment]
Thanks a lot @slarse , this makes things a lot more clear for me.

I did not really pay attention to the fact that the return type of `Factory.createTypeReference()` is actually generic and I haven't really worked with wildcard captures before. Seems like I need to brush up on my Java Generics knowledge :)

**Comment by slarse** [comment]
> Thanks a lot @slarse , this makes things a lot more clear for me.

You're welcome! Feel free to open a new issue, or re-open this one, if you have further questions on this.

> I haven't really worked with wildcard captures before.

This probably applies to a lot of Java devs. Spoon is a somewhat rough introduction to wildcards as they're used so heavily, and they are complex to be sure. There's even a [SonarSource rule discouraging their use in return types](https://rules.sonarsource.com/java/type/Code%20Smell/RSPEC-1452?search=wildcard) as "the type inference rules are fairly complex [and] it is unlikely the user of that API will know how to use it correctly."

> Seems like I need to brush up on my Java Generics knowledge :)

I actually find the [Oracle generics tutorials to be pretty good](https://docs.oracle.com/javase/tutorial/java/generics/index.html), if you need to brush up. Here's the one on [wildcard capture](https://docs.oracle.com/javase/tutorial/java/generics/capture.html). They're terse, though, so if you're looking for something more in-depth you better look elsewhere!
