### ISSUE TITLE
Set qualified name of CtTypeReference to a string

### ISSUE THREAD

**Issue by FloweyTheFlower420** [INRIA/spoon#3925]
How would I do that?

**Comment by andrewbwogi** [comment]
To change the qualified name of a `CtTypeReference`, you set its package:
```java
Launcher launcher = new Launcher();
Factory factory = launcher.getFactory();
String pkg = "my.pkg";
ctTypeReference.setPackage(factory.Package().createReference(pkg));
```
If the simple name of `ctTypeReference` is `"MyType"`, then it will now print `"my.pkg.MyType"`. Is this what you mean?
