### ISSUE TITLE
Two ways to specify a path for an element makes it ambiguous

### ISSUE THREAD

**Issue by algomaster99** [INRIA/spoon#3977]
There are two `CtPath`s possible to identify a statement in a body which I think is confusing. In my opinion, there should be one-to-one mapping from a `CtPath` to a `CtElement`. Consider the following example:

```java
class Test {
    public void helloWorld() {
        int a = 1;
        int b = 2;
        int c = 3;
    }
}
```

Two paths are possible for `int b =2;`:
1. `#containedType[name=Test]#method[signature=helloWorld()]#body#statement[name=b]`.
2. `#containedType[name=Test]#method[signature=helloWorld()]#body#statement[index=1]`.

Note that one uses `name` and the other `index`.

I initially proposed that `getPath` API should be modified to always use `index` but @slarse said, "I'm guessing that the reason for why names are used instead of indices sometimes is to make the path more resilient to shifted statements.". So instead he proposed that another API called `getPrecisePath` could be added.

I am okay with both but it would be better if we can find a case where using `index` across models fails but `name` does not. This would completely eliminate the proposition of modifying `getPath`.

**Comment by slarse** [comment]
> I am okay with both but it would be better if we can find a case where using index across models fails but name does not

```java
class Test {
    public void helloWorld() {
        int b = 2;
        int c = 3;
    }
}
```

Path nr. 1 gives `int b =  2`, path nr. 2 gives `int c = 3`

**Comment by algomaster99** [comment]
```java
class Test {
    public void helloWorld() {
        int a = 1;
        int b = 2;
        int c = 3;
    }
}
```

I created a model of this file and deleted the `int a = 1` using:
```java
new CtPathStringBuilder().fromString("#containedType[name=Test]#method[signature=helloWorld()]#body#statement[name=a]").evaluateOn(prevPackage).get(0).delete()
```

After that `new CtPathStringBuilder().fromString("#containedType[name=Test]#method[signature=helloWorld()]#body#statement[index=0]").evaluateOn(prevPackage)` and `new CtPathStringBuilder().fromString("#containedType[name=Test]#method[signature=helloWorld()]#body#statement[index=1]").evaluateOn(prevPackage)` were returning `int b = 2` and `int c = 3`.

`index` is able to resolve the statement correctly incase of a single model. I also tried across models and it works. Could you please elaborate on your test case.

**Comment by slarse** [comment]
@algomaster99 Given your original piece of code, if the first statement is removed, the wrong element is resolved using index, but the correct element is resolved using name.

**Comment by algomaster99** [comment]
I was not able to reproduce that. During the runtime, I deleted `int a = 1` and tried to evaluate elements using `index` like I have written in my previous comment. It works well.

**Comment by slarse** [comment]
I'll try to make it more clear. This path:

```
#containedType[name=Test]#method[signature=helloWorld()]#body#statement[index=1]
```

Evaluated on the _original model_ yields `int b = 2`, but on the _modified model_ it yields `int c = 3`. Modifying the model invalidates the path.

This path:

```
#containedType[name=Test]#method[signature=helloWorld()]#body#statement[name=b]
```

Evaluated on the _original model_ yields `int b = 2`, and on the _modified model_ it _still_ yelds `int b = 2`. It is therefore more resilient to changes in the model.

**Comment by algomaster99** [comment]
> but on the modified model it yields int c = 3. Modifying the model invalidates the path.

Yeah, this is exactly what is happening which is a good thing for `diffmin`. It is considering the shift in indices but I agree this may not be favourable everywhere.

**Comment by algomaster99** [comment]
@slarse It would be fairly straightforward to implement `getPrecisePath()` because we can easily switch between `name` and `index` using the API [here](https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/reflect/path/CtElementPathBuilder.java#L193).

**Comment by slarse** [comment]
@algomaster99 Yes, it would be easy to implement. On the other hand, one can just as well use the `CtElementPathBuilder` directly, it's part of the public API as well. As it's so easy to do, it doesn't really seem worth it to add and test in Spoon core.

**Comment by algomaster99** [comment]
Although there are two ways to get the path, spoon has a functionality, in the public API, to get both of them by toggling the system property `useNamesInPath`. Thus, we don't need another API to get path by index so closing this issue.
