### ISSUE TITLE
spoon will support   cross files  dataflow？

### ISSUE THREAD

**Issue by k4n5ha0** [INRIA/spoon#3979]
hi，pls tell me，did spoon will support cross files  dataflow？i find some sec sast lib. but they don't support cross files  dataflow.

**Comment by andrewbwogi** [comment]
Hi @k4n5ha0, [spoon-dataflow](https://github.com/INRIA/spoon/tree/master/spoon-dataflow) is a prototype and does not support interprocedural analysis except for small methods like getters and setters. It is not clear from test cases if this is supported across files. I can look it up if it is sufficient functionality for your requirements.

This package has not been updated for some time, I think we must wait for someone to take it on again.

**Comment by k4n5ha0** [comment]
> Hi @k4n5ha0, [spoon-dataflow](https://github.com/INRIA/spoon/tree/master/spoon-dataflow) is a prototype and does not support interprocedural analysis except for small methods like getters and setters. It is not clear from test cases if this is supported across files. I can look it up if it is sufficient functionality for your requirements.
> 
> This package has not been updated for some time, I think we must wait for someone to take it on again.

thx!
