### ISSUE TITLE
The annotation @xxx is disallowed for this location at ...

### ISSUE THREAD

**Issue by gluckzhang** [INRIA/spoon#4002]
Hello :)

I am using Spoon to generate configuration files for [ChaosMachine](https://github.com/KTH/royal-chaos/tree/master/chaosmachine) which analyzes the resilience of try-catch blocks in Java. What I would like to annotate is catch blocks, for example:

```java
try {
    ...
} catch (@ChaosMachinePerturbationPoint(hypothesis = Hypothesis.RESILIENT) MissingPropertyException e) {
    ...
} catch (@ChaosMachinePerturbationPoint(hypothesis = {Hypothesis.DEBUG, Hypothesis.OBSERVABLE}) Exception e) {
    ...
}
```

The issue is when using the latest version of Spoon, I get the following warning message and the configuration file is not successfully generated.

```
[INFO] Running in NOCLASSPATH mode (doc: http://spoon.gforge.inria.fr/launcher.html).
[INFO] Spoon version ${project.version}
[INFO] running Spoon...
[INFO] start processing...
[WARNING] warning: The annotation @ChaosMachinePerturbationPoint is disallowed for this location at ...
[INFO] se.kth.chaos.ChaosMachineAnnotationProcessor
[INFO] spoon.support.JavaOutputProcessor
[INFO] end of processing: 
[INFO] 2 warning
[INFO] s <-- It looks like a minor issue here. Is it "2 warnings" in the same line?
```

However, when I use Spoon `7.4.0-beta-12` I can successfully generate what I want, though the same warning message still occurs.

To reproduce the same behavior here is a concrete example using a real project: https://github.com/gluckzhang/DemoSite/tree/demo-for-cap

Run command `cd site && mvn package`, you should be able to see the warning message and a file `perturbationPoints.csv` generated in folder `site`. If the version of Spoon defined in `site/pom.xml` is changed to the latest one, the warning message persists while the `.csv` file cannot be generated.

Thank you in advance!

**Comment by andrewbwogi** [comment]
Hello @gluckzhang, I get the same problem. I'll check what is going on.

**Comment by gluckzhang** [comment]
> Hello @gluckzhang, I get the same problem. I'll check what is going on.

Thanks @andrewbwogi !

**Comment by andrewbwogi** [comment]
The change that causes your problem is in f2ecd5def520d0e8fb5f7c43a8889affd1347aa2. Since then, annotations of exception types are no longer attached to `CtCatch`, but `CtCatchVariable` instead. Are you looking for these annotations in `CtCatch` objects?

**Comment by gluckzhang** [comment]
Thanks @andrewbwogi ! Exactly, I was using `CtCatch` in my [implementation](https://github.com/KTH/royal-chaos/blob/master/chaosmachine/annotation_processor/src/main/java/se/kth/chaos/ChaosMachineAnnotationProcessor.java#L23). So now I should use `CtCatchVariable` instead. Correct?

**Comment by andrewbwogi** [comment]
Yes, try using `CtCatchVariable` instead.

**Comment by gluckzhang** [comment]
Great, thanks for the help. I am closing this issue :)
