### ISSUE TITLE
`this.caseExpression` attribute in `CtCase` is no longer needed

### ISSUE THREAD

**Issue by algomaster99** [INRIA/spoon#4019]
Reference: https://github.com/INRIA/spoon/pull/4015#issuecomment-869972744

Before Java 12, only one case expression was allowed per case, so spoon maintained an attribute [`this.caseExpression`](https://github.com/INRIA/spoon/blob/3e10fd5ac22b5e7e75773bd9323870f47372f3d2/src/main/java/spoon/support/reflect/code/CtCaseImpl.java#L31) which would store the expression corresponding to the case. Java 12 introduced a feature to add multiple expressions to a single case, so [`this.caseExpressions`](https://github.com/INRIA/spoon/blob/3e10fd5ac22b5e7e75773bd9323870f47372f3d2/src/main/java/spoon/support/reflect/code/CtCaseImpl.java#L34) was introduced, which would contain a list of `CtExpression`s. The second attribute, `this.caseExpressions`, made `this.caseExpression` obsolete.

I propose that we remove the attribute and modify its getters and setters to, instead, return the list's first element and clear the list and insert a single element, respectively. This would reduce redundancy. Another benefit is that some visitors like [`CtScanner`](https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/reflect/visitor/CtScanner.java#L330-L337) do not even access `this.caseExpression`. So if someone would have set the case expression using [`this.setCaseExpression`](https://github.com/INRIA/spoon/blob/3e10fd5ac22b5e7e75773bd9323870f47372f3d2/src/main/java/spoon/support/reflect/code/CtCaseImpl.java#L58), they won't even see it in their pretty-printed string.

**Comment by slarse** [comment]
I agree, seems like a good refactoring.

**Comment by algomaster99** [comment]
I am working on it. I shall submit a PR soon.
