### ISSUE TITLE
bug: Question about equality of `CtCodeSnippetExpression`

### ISSUE THREAD

**Issue by algomaster99** [INRIA/spoon#4022]
I created two expressions as shown below.

```java
Factory factory = new Launcher().getFactory();
CtExpression<Integer> firstExpression = factory.createCodeSnippetExpression("1");
CtExpression<Integer> secondExpression = factory.createCodeSnippetExpression("2");
```
When I execute `firstExpression.equals(secondExpression);`, I get `true` in return. Clearly, the value of these expressions is different so I cannot understand why they are passing the equality test.

**Comment by slarse** [comment]
First of all, it's important to note that what you have there are not two literals, but two code snippet expressions. So this question regards equality of `CtCodeSnippetExpression` elements, and not the more general `CtExpression`. If you were to have actual `CtLiteral` elements, the equality would prove false.

```java
Factory factory = new Launcher.getFactory();
CtCodeSnippetExpression<Integer> first = factory.createCodeSnippetExpression("1");
CtCodeSnippetExpression<Integer> second = factory.createCodeSnippetExpression("2");
System.out.println(first.compile().equals(second.compile())); // false

// or similarly
CtLiteral<Integer> first = factory.createLiteral(1);
CtLiteral<Integer> second = factory.createLiteral(2);
System.out.println(first.equals(second)); // false
```

The practical reason why you get that these two are equal is that the `CtBiScannerDefault` for some reason does not visit the `SNIPPET` role. https://github.com/INRIA/spoon/blob/3e10fd5ac22b5e7e75773bd9323870f47372f3d2/src/main/java/spoon/reflect/visitor/CtBiScannerDefault.java#L824-L832

@monperrus this seems like a bug, any idea why the generated scanner does not visit the `SNIPPET` role?

**Comment by algomaster99** [comment]
> So this question regards equality of CtCodeSnippetExpression elements, and not the more general CtExpression.

Oh, right. This is more specific. Thanks for the clarification.

**Comment by monperrus** [comment]
> @monperrus this seems like a bug, any idea why the generated scanner does not visit the SNIPPET role?

I'd say because this is not "code" but only a string. If you compile the snippets first (meaning transforming into an AST) and then scan, it should work.

But it seems to me that it would not hurt or break anything to also visit the snippet by default, an exploratory PR would be welcome.

**Comment by slarse** [comment]
> I'd say because this is not "code" but only a string.

So are comments, yet their content defines them :)

I think this is a bug to be fixed, will look at it when I have some time left over.
