### ISSUE TITLE
Design suggestions for adding in pattern matching (Java 16 feature)

### ISSUE THREAD

**Issue by slarse** [INRIA/spoon#4035]
@monperrus and I had a meeting based on #4020, and we came up with a few different alternatives to consider.

Note that everywhere it says "introduce type `CtTypePattern`", we should also consider to immediately introduce `CtPattern` as a common supertype of type patterns, record patterns and array patterns (latter two are upcoming, see https://openjdk.java.net/jeps/406). As this is not relevant to comparing and contrasting these designs, we leave it in the descriptions for brevity.

This is a little bit messy, I've tried to as best I can summarize our thoughts, but there were just so many of them :). Hopefully the gist of it is understandable.

### Design A) (first draft of #4020)

Introduce `CtTypePattern<T> extends CtExpression<Void>` and the type pattern is (currently) used as the right-hand side of `CtBinaryOperator` with kind `INSTANCEOF`

Pros:
    - Quite simple
    - Backwards compatible
    - Immediately forwards compatible with upcoming JEPS to introduce patterns in cases; because patterns are just expressions
Cons:
    - TypePattern can be used anywhere an expression is allowed, making it possible to place in a lot of places it's not supposed to be (because patterns aren't actually expressions)

### Design B) (slight variation of A)

Same as A), but instead of making the `CtTypePattern` the RHS of a binary operator, it's instead the entire `a instanceof b t` instanceof expression.

Pros:
    - Quite simple
    - Independent of binary operators
Cons:
    - TypePattern can be used anywhere where an expression is allowed
    - Breaks down completely when considering that patterns will in the future appear in the abcense of `instanceof` (https://openjdk.java.net/jeps/406)
    - Unintuitive abstraction: `a instanceof b` is a binary operator, but `a instanceof b t` is something completely different?
    - TypePattern can be used anywhere an expression is allowed, making it possible to place in a lot of places it's not supposed to be (because patterns aren't actually expressions)

### Design C) (make `instanceof` a standalone model element)

Introduce `CtInstanceOf extends CtBinaryOperator<Boolean>` and `CtTypePattern extends CtElement`, which becomes a field inside of `CtInstanceOf`. For backwards compatibility, use "old" `instanceof` if compliance level <16, and use the standalone metamodel element if compliance level >=16. Hard-code `CtInstanceOf.getKind()` to return `INSTANCEOF` and `CtInstanceOf.setKind()` to be an unsettable property.

To be clear, in <16, the use of `CtInstanceOf` is prohibited (we raise an exception if one tries to instantiate its implementation). In >=16, we instead raise an exception if one tries to do `CtBinaryOperator.setKind(BinaryOperatorKind.INSTANCEOF)`. The reason for the latter is that it's not possible to "morph" a standard operator (e.g. multiplication) into a `CtInstanceOf` when a method is called. A stretch would be to do something like `replace(this, new CtInstanceofImpl())`, but throwing is probably less confusing.

As `CtInstanceOf` would extend `CtBinaryOperator`, there should be very few changes needed inside of Spoon in terms of _using_ `CtInstanceOf`. It's only when creating it and setting the kind specifically to `INSTANCEOF`

Pros:
    - Provides accurate modeling of `instanceof` and patterns.
    - Backwards compatible
    - Patterns can't be "misplaced" in the model, they are not expressions
Cons:
    - Need to maintain "two versions" of `instanceof`
    - Need to add a new metamodel element; that's always a bit of work

### Design D) (add extended `BinaryOperatorKind`)

This is similar to the solution with `CtExtendedModifier`. In effect, we add an extended version of `BinaryOperatorKind`, `CtExtendedBinaryOperatorKind`, which can hold additional information. In particular, we could have a pattern field inside of that.

Pros:
    - Backwards compatible
    - Patterns can't be "misplaced" in the model, they are not expressions
Cons:
    - The pattern becomes a little bit disconnected from the model itself. How to make methods like `filterChildren()` also include the pattern?
    - Semi-difficult to implement
    - Not very elegant or discoverable: when do I use `BinaryOperatorKind` and when do I use `CtExtendedBinaryOperatorKind`?

### Design E) (field inside `CtBinaryOperator`)

Add a field in CtBinaryOperator to store a pattern. Raise if one calls `CtBinaryOperator.get/setPattern()` and the kind is not `INSTANCEOF`, or compliance level <16.

Pros:
    - Very easy to implement
    - Backwards compatible
    - Patterns can't be "misplaced" in the model, they are not expressions
Cons:
    - A pattern only makes sense for `instanceof`, so the vast majority of binary operators in the model would now have a field which doesn't make sense to them.

### Design F) (no metamodel change, use implicit local variable)

We introduce a fake ‘implicit’ CtLocalVariable at model building time

Pros:
    - No change at all in the metamodel required
    - Backwards compatible
    - Patterns can't be "misplaced" in the model, they are not expressions
Cons:
    - Transformation is hard
    - Sniper pretty-printing is impossible

## My two cents

With the exception of design A) (the current implementation in #4020), all of these designs suffer from one major drawback: not being immediately forwards compatible with the at this point likely upcoming use of patterns in switch cases (https://openjdk.java.net/jeps/406). I say likely because the JEP is not done, so it could end up not being introduced. We could work around this by allowing `CtCase` to have _either_ one pattern, or a bunch of case expressions.

But that hits another snag: they also propose _guarded_ patterns, which look something like so: `case Triangle t && (t.calculateArea() > 100)`. Here, the pattern is the left-hand-side of a binary operator. If patterns aren't expressions, then how in the world to we model that?

Having thought this through very carefully, with the assumption that patterns for cases are implemented (and guarded patterns in particular), I think the only reasonably easy-to-implement solution is to go with design A, i.e. the one @SirYwell came up with originally for #4020. It's the most pragmatic solution, and we can add checks to `CtPattern.setParent()` that disallows patterns to become children of anything but the places we expect them to be.

**Comment by SirYwell** [comment]
Nothing to add from my side I think. Thanks for the in-depth analysis of the different designs.

For completeness and everyone coming accross this, more interesting information about pattern matching features that are in planning can be found on https://cr.openjdk.java.net/~briangoetz/amber/pattern-match.html and https://cr.openjdk.java.net/~briangoetz/amber/pattern-semantics.html

**Comment by slarse** [comment]
This is done.
