### ISSUE TITLE
CtFieldReferenceImpl.isFinal() does not appear to mirror the value returned from the associated field declaration through static block access to local non static final field referenced without `this` qualifier

### ISSUE THREAD

**Issue by raghav-deepsource** [INRIA/spoon#4040]
It is understandable that if a field reference cannot be associated with a declaration, the values of `CtFieldReferenceImpl.isStatic()` and `isFinal()` would return false as a default. however, in the case of a field reference associated with an existing field declaration, I expected these values to reflect the result of calling isFinal or isStatic on the field declaration itself.

I've written a small kotlin script to demonstrate this. It should be trivial to convert to java:
```kotlin
import spoon.reflect.code.CtFieldAccess

val classS = """class MVP  {

    final String Const = "abc";
    static String const2 = "abc";
    final static String c3 = "abc";


    static {
        Const.toString(); // CtFieldReferenceImpl.isFinal returned false here, where I expected it to return true.
        const2.toString();
        c3.toString();
    }
    
    {
        Const.toString();
        this.Const.toString();
    }
    
    public MVP() {
        this.Const.toString();
        Const.toString();
    }
}"""

val classF = spoon.Launcher.parseClass(classS)

print(classF)

print(classF.typeMembers)

classF.getElements<CtFieldAccess<String>> {
    print("$it:  ${it.variable.isStatic} ${it.variable.isFinal}")
    print("$it: ${it.variable.fieldDeclaration.isStatic} ${it.variable.fieldDeclaration.isFinal}")
    false
}
```

if this is intended, maybe it should be made clear.

this issue occurred on the latest beta version on maven, 9.1.0-beta-17
Java version is openjdk, 14
platform is linux.

**Comment by raghav-deepsource** [comment]
Would it be reasonable to delegate the implementation of the reference type's isFinal and isStatic methods to the associated field definition, if present?

**Comment by raghav-deepsource** [comment]
on further testing it seems like this mainly  happens with non static values.

**Comment by raghav-deepsource** [comment]
Well I guess this should have been expected since it isn't valid java code. This behavior may warrant documentation, imo.

**Comment by I-Al-Istannen** [comment]
I am not sure what behaviour you even want there.

What would you expect
```java
class MVP  {

    String Const = "abc";
    final String Const = "abc";

    static {
        System.out.println(Const);
    }
}
```
to return?

As far as I can see the following happens:
1. Your code does not compile. You can not just access an instance field from a static block
2. JDT detects that error and the FieldBinding it passes to spoon has no modifiers as it has no backing field.
3. Spoon reads the default modifiers from the FieldBinding and sets its static and final stuff according to that
4. When you call `getVariable` spoon will resolve that by looking for fields *with the referenced simpleName* in the declaring type. This will return any of the field declarations (the first in my testing here) and you can read its modifiers.

If your code *does* compile:
1. Spoon receives a valid FieldBinding and initializes itself accordingly
2. Everybody is happy


If you use `this` JDT generates a FieldReference instead, which just outright fails to find any match.

**Comment by slarse** [comment]
Hi @raghav-deepsource,

Thanks for reaching out. It's as @I-Al-Istannen says, whenever code doesn't compile resolving references becomes problematic, and so the solution in this case is to make the code compile first.

There is definitely room for improvement in how well reference resolution is documented in Spoon, I think [this is all we have at the moment](https://spoon.gforge.inria.fr/references.html). Perhaps we should add a Q&A somewhere as questions like this one pop up fairly often.

**Comment by raghav-deepsource** [comment]
@I-Al-Istannen I definitely agree. I hadn't realised this wasn't valid java code when I first encountered it.

Thank you for the detailed reply.

**Comment by slarse** [comment]
@raghav-deepsource

> I hadn't realised this wasn't valid java code when I first wrote it, probably because my ide didn't have anything to say about it (the code was in a resource directory)

I've had this problem in a lot of projects. My go-to mistake is to forget the type of a field.

```java
private name = "Simon";
```

I've had test cases with nonsense like that persist for long periods of time, and so nowadays I always make sure that input resources compile (when possible). For example, [here's a test that does just that](https://github.com/SpoonLabs/sorald/blob/87ce9cc379184fe141dc6dea98e344f21f461818/src/test/java/sorald/processor/ProcessorTestFilesCompileTest.java), with the [assertion helper defined here](https://github.com/SpoonLabs/sorald/blob/87ce9cc379184fe141dc6dea98e344f21f461818/src/test/java/sorald/Assertions.java). I've found it to be very much worth the effort having such a sanity check.

**Comment by raghav-deepsource** [comment]
Oh, I'm definitely using that in my tests then, thank you!

**Comment by raghav-deepsource** [comment]
Of course, I don't know how much help that would be since so many of my tests just use undefined classes left and right...

**Comment by slarse** [comment]
> Of course, I don't know how much help that would be since so many of my tests just use undefined classes left and right...

That's the tradeoff, you can't do that anymore :). I usually solve it by defining empty classes in the same file (recall that you can have however man package private classes you'd like in the same file) or nested static class, but it depends on the project and test. For some tests I define entire Maven projects, and then I can check that it compiles just by running `mvn test-compile`.
