### ISSUE TITLE
bug: Classes in overlapping modules are not resolved correctly

### ISSUE THREAD

**Issue by I-Al-Istannen** [INRIA/spoon#4051]
## Problem statement
Jigsaw projects are allowed to define modules with *overlapping packages*. A real-world example of this is `java.desktop` and `java.datatransfer`, which share the `java.awt` package.
A self-contained example is this:
<details>
<summary>Example</summary>

```
.
├── bar
│  ├── common
│  │  └── Bar.java
│  └── module-info.java
└── foo
   ├── common
   │  └── Foo.java
   └── module-info.java
```

<details>
<summary>Bar module info</summary>

```java
module bar {
  exports common;

  requires foo;
}
```
</details>

<details>
<summary>Foo module info</summary>

```java
module foo {
  exports common;
}
```
</details>

<details>
<summary>Bar</summary>

```java
package common;

/**
 * I am bar and I am a class.
 */
public class Bar {
  public static void main(String args[]) {
    Foo.main(args);
  }
}
```
</details>

<details>
<summary>Foo</summary>

```java
package common;

/**
 * I am bar and I am a class.
 */
public class Foo {
  public static void main(String args[]) {
  }
}
```
</details>

</details>

([as a zip](https://github.com/INRIA/spoon/files/6830715/Sadness.zip))
This will cause the Javadoc class lookup for at least one of the classes to fail.

## Cause
I spent a few too many hours trying to make sense of JDT, Spoon and my current conclusion is the following:

When resolving comments spoon needs to know where in the file given source code elements appear. This is all fine, but when looking up a class in an overlapping module, spoon will call `PackageFactory#get` which will in turn iterate over all modules *and choose the first package it finds!* Spoon will retrieve the package from the wrong module, can't find the class in it and create a dummy class without any positions. This causes the comment insertion to attribute *all* comments to the surrounding `CtCompilationUnit`.

## Experimental validation
I added a print to the `PackageFactory#get` method, reporting when two or more packages were found and it returned this:
```
Oh no (x times)

Javadoc for Bar is:
  [/**
   * I am bar and I am a class.
   */]

Oh no (x times)

Javadoc for Foo is:
  []
```
As you can see it swallowed one of them, as it tried to look for `Foo` in the wrong module.

## Impact
My Javadoc Indexer fails to find any Javadoc for classes in `java.awt` due to the overlap mentioned at the beginning. This is a bit unfortunate.

## Possible solutions
1. We could merge all packages into one instead of picking a random one, which would at least allow us to find them here. This might, however, create conflicting qualified names which isn't awesome.
2. We could return a List of packages from `get(QualifiedName)`
    * We could check for any `requires` clause and only return packages in our module and any required one
3. We could look up types directly without taking the `Package()` factory middle-man which would solve the problem for unambiguous qualified names and if we also know the module context (and only look in our modules + required) this should work all the time

I have no idea how we can save the `CtPackage get(QualifiedName)` method, the current code seems to query for packages first and types second, which just doesn't work anymore in a post-module world.

**Comment by I-Al-Istannen** [comment]
I am currently hacking around it using option 2, but that's not quite ideal as I only adjusted one callsite and my handling is inconsistent with the Java requirements (as it does not handle types with the same qualified name in different modules, which can probably happen if they do not require each other). So far it is enough to index OpenJDK 16 without exceptions and properly attribute Javadoc that was previously failing.


```patch
diff --git a/src/main/java/spoon/reflect/factory/TypeFactory.java b/src/main/java/spoon/reflect/factory/TypeFactory.java
index a42dbf3a..9804db96 100644
--- a/src/main/java/spoon/reflect/factory/TypeFactory.java
+++ b/src/main/java/spoon/reflect/factory/TypeFactory.java
@@ -427,15 +427,21 @@ public class TypeFactory extends SubFactory {
        @SuppressWarnings("unchecked")
        public <T> CtType<T> get(final String qualifiedName) {
                int packageIndex = qualifiedName.lastIndexOf(CtPackage.PACKAGE_SEPARATOR);
-               CtPackage pack;
+               List<CtPackage> pack;
                if (packageIndex > 0) {
-                       pack = factory.Package().get(qualifiedName.substring(0, packageIndex));
+                       pack = factory.Package().gets(qualifiedName.substring(0, packageIndex));
                } else {
-                       pack = factory.Package().getRootPackage();
+                       pack = Collections.singletonList(factory.Package().getRootPackage());
                }
 
-               if (pack != null) {
-                       CtType<T> type = pack.getType(qualifiedName.substring(packageIndex + 1));
+               if (pack != null && !pack.isEmpty()) {
+                       CtType<T> type = null;
+                       for (CtPackage ctPackage : pack) {
+                               type = ctPackage.getType(qualifiedName.substring(packageIndex + 1));
+                               if (type != null) {
+                                       break;
+                               }
+                       }
                        if (type != null) {
                                return type;
                        }
```
```patch
diff --git a/src/main/java/spoon/reflect/factory/PackageFactory.java b/src/main/java/spoon/reflect/factory/PackageFactory.java
index 9ba0ca53..4a8c62d6 100644
--- a/src/main/java/spoon/reflect/factory/PackageFactory.java
+++ b/src/main/java/spoon/reflect/factory/PackageFactory.java
@@ -13,6 +13,7 @@ import java.util.Collection;
 import java.util.List;
 import java.util.Objects;
 import java.util.StringTokenizer;
+import java.util.stream.Collectors;
 import spoon.reflect.declaration.CtModule;
 import spoon.reflect.declaration.CtPackage;
 import spoon.reflect.declaration.CtPackageDeclaration;
@@ -166,6 +167,24 @@ public class PackageFactory extends SubFactory {
                                .orElse(null);
        }
 
+       /**
+        * Gets a package.
+        *
+        * @param qualifiedName
+        *              the package to search
+        * @return a found package or null
+        */
+       public List<CtPackage> gets(String qualifiedName) {
+               if (qualifiedName.contains(CtType.INNERTTYPE_SEPARATOR)) {
+                       throw new RuntimeException("Invalid package name " + qualifiedName);
+               }
+
+               return factory.getModel().getAllModules().stream()
+                               .map(module -> getPackageFromModule(qualifiedName, module))
+                               .filter(Objects::nonNull)
+                               .collect(Collectors.toList());
+       }
+
        /**
         * @param qualifiedName Qualified name of a package.
         * @param module A module in which to search for the package.

```

**Comment by slarse** [comment]
The sample you provided does not compile for me, I get the following error:

```
$ javac --module bar --module-source-path . -d out
./bar/common/Bar.java:1: error: package exists in another module: foo
```

The point of the module system is supposed to provide strong encapsulation, which simply would not be possible if they were allowed to reach inside each others' packages. Two modules exporting the same package therefore seems impossible.

If `bar` requires `foo`, and `foo` exports a package that's present in `bar` (even if `bar` does not export it), then the compiler refuses to compile it.

However, the compiler appears to allow to have unexported packages with matching names, and in fact, even with matching types inside. That however blows up at runtime for me (note that I shuffled some stuff around here, `common` is no longer in `foo`, but both have `incommon`):

```
$ java --module-path out --module bar/common.Bar
java.lang.LayerInstantiationException: Package incommon in both module foo and module bar
```

The example you provided, `java.desktop` and `java.datatransfer` do not in fact share any packages. `java.awt` is defined only in `java.desktop`, while `java.datatransfer` contains `java.awt.datatransfer`. Note that a subpackage is an entirely different package than its parent package, there's no "package inheritance" or anything like that.

Maybe I'm missing something here, but it seems to me like the module system does not play well with spreading the same package across multiple modules. If it's exported, it's even worse.

**Comment by I-Al-Istannen** [comment]
> The sample you provided does not compile for me, I get the following error:

You are right, I screwed up my `javac` invocation...

> The example you provided, java.desktop and java.datatransfer do not in fact share any packages. java.awt is defined only in java.desktop, while java.datatransfer contains java.awt.datatransfer. Note that a subpackage is an entirely different package than its parent package, there's no "package inheritance" or anything like that.

While that is true for Java, Spoon's model makes this a bit more problematic. If I have a `java.awt.datatransfer` package, I *will* also have a `java.awt` package as a parent. This is what blows up here: The `java.desktop` module contains a proper `java.awt` package, but `java.datatransfer` contains a "synthetic" `java.awt` package as the parent for `java.awt.datatransfer`. When resolving `java.awt.Graphics2D`, Spoon is faced with ambiguity - both modules contain a `java.awt` package.

**Comment by slarse** [comment]
> While that is true for Java, Spoon's model makes this a bit more problematic. If I have a `java.awt.datatransfer` package, I _will_ also have a `java.awt` package as a parent.

Yes, this is a bit of awkwardness in Spoon's model being very much the same for packages and modules as it is for compilation units.

> This is what blows up here: The `java.desktop` module contains a proper `java.awt` package, but `java.datatransfer` contains a "synthetic" `java.awt` package as the parent for `java.awt.datatransfer`. When resolving `java.awt.Graphics2D`, Spoon is faced with ambiguity - both modules contain a `java.awt` package.

So we need to figure out how to solve this without breaking backwards compatibility (at least too badly). That obviously means that we can't remove the "synthetic" `java.awt` package, unfortunately.

> 
> EDIT:
> Based on that it might make sense to set the `implicit` value for packages? I.e. when we create a parent package in `getOrCreate` we mark it as implicit and when it is requested by qualified name we mark it as explicit. This would ensure "parent" packages are marked as implicit until something is actually in there. I am not sure whether that would work as I am not sure when exactly spoon decides to resolve a package by FQN, but something like it might be an option.

That's not a bad idea. The one thing I think it might cause trouble with is that it's pretty typical (at least I've done it on several occasions) to ignore processing children of implicit elements when... doing stuff. I.e. in a scanner, you just stop scanning when you reach an implicit element. That use case breaks down a bit.

A less intrusive solution would be to fetch all packages from all modules that match the qualified name, and sort them in descending order by the amount of contained types. That way, non-empty non-synthetic packages are found first, while still making it possible to find synthetic packages (hopefully preserving backwards compatibility). WDYT?

**Comment by I-Al-Istannen** [comment]
Sorry, I kinda forgot this issue existed but I ran into it again earlier this day.

> That's not a bad idea. The one thing I think it might cause trouble with is that it's pretty typical (at least I've done it on several occasions) to ignore processing children of implicit elements when... doing stuff. I.e. in a scanner, you just stop scanning when you reach an implicit element. That use case breaks down a bit.

Okay, yea, that does rule that one out :(

> A less intrusive solution would be to fetch all packages from all modules that match the qualified name, and sort them in descending order by the amount of contained types, and then get the first one. That way, non-empty non-synthetic packages are found first, while still making it possible to find synthetic packages (hopefully preserving backwards compatibility). WDYT?

Sounds good, increased the runtime from `3:02` to `6:24` :D 

----

I will have a look why that happens, maybe I can get it to work with an acceptable loss to performance.

**Comment by slarse** [comment]
> Sorry, I kinda forgot this issue existed but I ran into it again earlier this day.

No worries, we all do that :)

> Okay, yea, that does rule that one out :(

Maybe. I'm not sure, it might be a blocker but it also might not be.

> Sounds good, increased the runtime from 3:02 to 6:24 :D

That's... interesting. Could you put up a PR so we can look at it together?
