### ISSUE TITLE
bug: Spoon's "getShortDescription" and "getLongDescription" handling is too primitive

### ISSUE THREAD

**Issue by I-Al-Istannen** [INRIA/spoon#4059]
## Context
Spoon offers a `getShortDescription()` method in `CtJavadoc`. This method should (I guess) return the short Javadoc the standard HTML Doclet displays in the method table. The javadoc tool description (e.g. [here](https://docs.oracle.com/javase/7/docs/technotes/tools/solaris/javadoc.html)) says:
> Copies the first sentence of the overview comment to the top of the overview summary page.

## Problem statement
Sadly the current handling is a bit too simplistic (*I heard an issue is only complete once it includes images, so here goes nothing*):
![grafik](https://user-images.githubusercontent.com/20284688/126550871-7f38bab4-c82c-43ca-9b2f-81f5a94e80d5.png)
![grafik](https://user-images.githubusercontent.com/20284688/126551524-1a674aac-fa70-4387-b12a-29e9c6472a9f.png)

As you can see the javadoc is cut off after `java.`. Spoon sees the Javadoc:
```java
/**
 * An extended version of <code>java.awt.Frame</code> that adds support for
 * the JFC/Swing component architecture.
```
and the Javadoc
```java
/**
 * Accepts a function that extracts a {@link java.lang.Comparable
 * Comparable} sort key from a type {@code T}, and returns a {@code
 * Comparator<T>} that compares by that sort key.
```
and assumes the span *until the first dot* is the summary. Sadly, this doesn't work with links - which are quite common.

## Solutions
We could try a bit harder and not just scan for the first `.` but instead look for the first `.` *followed by a space or a newline*. This *should* at least improve the heuristic by quite a bit.

**Comment by andrewbwogi** [comment]
Your solution seems reasonable. I'll see if we can implement it.
