### ISSUE TITLE
bug: insertBegin method is inserting list in reverse order than it should be

### ISSUE THREAD

**Issue by Rohitesh-Kumar-Jain** [INRIA/spoon#4060]
## Context

Hi while writing test for [`CtCaseImpl.insertBegin`](https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/support/reflect/code/CtCaseImpl.java), I feel that the core logic of this method is implemented incorrectly.

JavaDoc for this method states : 

<img width="828" alt="Screenshot 2021-07-23 at 5 13 24 PM" src="https://user-images.githubusercontent.com/62026125/126777030-58ffd10d-8bc1-463d-8e73-d0219c1e09da.png">

## Problem 

`insertBegin` should add the list at the beginning of the block in the order of the elements inside the list, but it is adding in the reverse order of the elements inside the list.

What I mean is that after inserting a list consisting of statements : 

[first statement, second statement, third statement] they should be added like this : 

```
first statement 
second statement 
third statement
existing statement(s)
```

But they are being added like

```
third statement 
second statement 
first statement 
existing statement(s)
```
The existing code is working in the way as you are inserting individual statements, and not the whole list

It is based on the reasoning that the addition should be like this : 

```
list
existing statements(s)
```

And as the list is inserted in the beginning, the content of the list shouldn't be altered

## Failing test Case

 I have written this test to enforce this

```
@Test
    void testInsertBeginWithListOfStatements() {
        // contract: insertBegin add a list of statements at the beginning of a case, i.e above two already existing statements

        // arrange
        Launcher spoon = new Launcher();
        spoon.addInputResource(new FileSystemFile("./src/test/java/spoon/test/ctCase/testclasses/ClassWithSwitchExample.java"));
        spoon.buildModel();

        CtClass classWithSwitchExample = spoon.getFactory().Class().get(ClassWithSwitchExample.class);

        CtStatement firstStatementToBeInserted = classWithSwitchExample.getFactory().Code().createCodeSnippetStatement("first Statement");
        CtStatement secondStatementToBeInserted = classWithSwitchExample.getFactory().Code().createCodeSnippetStatement("second Statement");
        CtStatement thirdStatementToBeInserted = classWithSwitchExample.getFactory().Code().createCodeSnippetStatement("third Statement");
        CtCase testCase = classWithSwitchExample.getElements(new TypeFilter<>(CtCase.class)).get(0);

        CtStatementList ctStatementList =  new CtStatementListImpl<CtStatement>();

        ctStatementList.addStatement(firstStatementToBeInserted);
        ctStatementList.addStatement(secondStatementToBeInserted);
        ctStatementList.addStatement(thirdStatementToBeInserted);

        // act
        testCase.insertBegin(ctStatementList);

        // assert
        assertEquals(firstStatementToBeInserted, testCase.getStatement(0));
        assertEquals(secondStatementToBeInserted, testCase.getStatement(1));
        assertEquals(thirdStatementToBeInserted, testCase.getStatement(2));
    }
```

## Solution 

I will be happy to fix this bug, once given permission to work upon this from the community : )

I will be pushing this test along with other tests I have written for this Class.

**Comment by SirYwell** [comment]
I would consider this a bug indeed, especially as `insertEnd` behaves the way you described. A simple fix would be to either use an index or to reverse the iteration of the list.

A side note: The `insertEnd` method has a comment (https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/support/reflect/code/CtCaseImpl.java#L189) explaining behavior that differs from the `insertBegin` method too as I just saw.

**Comment by Rohitesh-Kumar-Jain** [comment]
> especially as insertEnd behaves the way you described

There is a possibility that it is supposed to work the way it is working, it's just the documentation that needs to be corrected.

As the documentation states that "inserts the given statement list at the beginning" which as we can see is not the case. It is inserting the given statement list in the reverse order of the list, which might be the required functionality.

**Comment by Rohitesh-Kumar-Jain** [comment]
> A side note: The `insertEnd` method has a comment (https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/support/reflect/code/CtCaseImpl.java#L189) explaining behavior that differs from the `insertBegin` method too as I just saw.

@SirYwell yes you are right, `insertEnd` is working the way I expect `insertBegin` to work, i.e the list being added remains in the same order

Thanks for pointing this out

**Comment by slarse** [comment]
This is clearly a bug to me, it makes no sense to reverse the provided statement list. With `insertEnd`, it works just inserting the elements in the given order as they are appended to the list. The author probably just didn't consider that prepending in the same fashion causes a reversal of the input.

If we have a look in `CtBlockImpl`, `insertBegin(CtStatementList)` does not reverse the provided statements, instead using `addAll(int, Collection<CtStatement>)`:

https://github.com/INRIA/spoon/blob/f85ebe5b2b12ea23c213200ff2d0f6b95f6d868f/src/main/java/spoon/support/reflect/code/CtBlockImpl.java#L92-L102

**Comment by Rohitesh-Kumar-Jain** [comment]
As @SirYwell pointed, reversing the iteration for this [loop](https://github.com/INRIA/spoon/blob/f85ebe5b2b12ea23c213200ff2d0f6b95f6d868f/src/main/java/spoon/support/reflect/code/CtCaseImpl.java#L169) seems a simple fix to me.

I mean something like this 

```
for (int i = statements.getStatements().size() - 1; i >= 0; i--) {
	CtStatement statement = statements.getStatement(i);
	statement.setParent(this);
	this.addStatement(0, statement);
}
```

**Comment by slarse** [comment]
I would just use `addAll(0, copy)`. See `CtBlockImpl.insertBegin(CtStatementList)` above.

**Comment by Rohitesh-Kumar-Jain** [comment]
So now should I first push the failing test case, or first fix the implementation, or we should wait for more discussion ?

**Comment by slarse** [comment]
Submit a PR with the currently failing test, and the fix for it. To make it very clear that the test fixes the problem, you can first push the failing test and let CI run (and fail). Then you push the fix, and CI passes.
