### ISSUE TITLE
Spoon integrators are on vacation

### ISSUE THREAD

**Issue by slarse** [INRIA/spoon#4062]
If you've been active in the repo during the past week, you may have noted an alarming absence of input from the Spoon integrators. That's due to circumstances of work and life, we had to go on somewhat overlapping vacations (not completely, but somewhat).

We are not ignoring your issues or pull requests, we're just taking some much needed time off. We'll start trickling back in the first half of August. Until then, feedback from integrators on PRs and issues will not be as frequent as usual.

**Comment by Rohitesh-Kumar-Jain** [comment]
Do enjoy Vacations 🎉

**Comment by slarse** [comment]
We're back!
