### ISSUE TITLE
Local classes/enums/interfaces/records

### ISSUE THREAD

**Issue by SirYwell** [INRIA/spoon#4074]
As Java 16 introduced local enums and local interfaces additionally to (local) records, I started looking into how they are handled in Spoon.

My first observation was that local interfaces are ignored but local enums are found and included in the model correctly. This seems to come from https://github.com/INRIA/spoon/blob/78d64fe348c282a190a353c17f8855684a0cb1b5/src/main/java/spoon/support/compiler/jdt/JDTTreeBuilderHelper.java#L752 this check.

Only when writing tests to cover local types I saw that local classes are actually prefixed with numbers. Looking into that, I found its cause in the check here https://github.com/INRIA/spoon/blob/78d64fe348c282a190a353c17f8855684a0cb1b5/src/main/java/spoon/support/compiler/jdt/JDTTreeBuilderHelper.java#L756 (the part after the `||`). 

In the same commit this check was introduced, this behavior was also documented in `CtType` (https://github.com/INRIA/spoon/commit/9e0de7530627784e04545fce947a461b4f7309a7#diff-493d9e2eaf0b87f5449ea2a10488544623189dcbad95afb9e68029e1d48cb753R39).
This causes several issues: 
- it differs from the output of [Class#getSimpleName()](https://docs.oracle.com/en/java/javase/16/docs/api/java.base/java/lang/Class.html#getSimpleName()) (note: "Returns the simple name of the underlying class **as given in the source code.**", highlighting added by me)
- the printer currently prints it wrong for enums (and for interfaces and records once supported)
- creating a new local class with spoon does not require this naming

My suggestion would be to just use the name which is used in the source code too, but that is clearly breaking the contract of the `getSimpleName()` method. Otherwise, the printer would need to be fixed in the appropriate places to strip numbers from interfaces and enums too.

To support local interfaces, `CtInterface` would also need to extend `CtStatement`.

**Comment by I-Al-Istannen** [comment]
Additionally, the simple name returned by `Class#getSimpleName` for anonymous classes is `""` - spoon returns the number. The name of an anonymous class isn't as relevant (it is never printed out again), but being consistent with `getSimpleName` **might** be useful.

**Comment by andrewbwogi** [comment]
The behavior that names are prefixed with numbers is inconsistent with the meaning of `getSimpleName`, which I understand is to get the element name as it is in the source code. That is why `setSimpleName` can undo it. 

> My suggestion would be to just use the name which is used in the source code too

I think this is the way to go and to consider the current contract an error.

**Comment by slarse** [comment]
> it differs from the output of Class#getSimpleName() (note: "Returns the simple name of the underlying class as given in the source code.", highlighting added by me)

That's not a problem in principle, Spoon does not claim to maintain consistency with similar standard library methods.

> the printer currently prints it wrong for enums (and for interfaces and records once supported)

This is a bug.

> creating a new local class with spoon does not require this naming

I'm uncertain if this is a problem or not. There are many conventions that a user can break if they'd like.

> My suggestion would be to just use the name which is used in the source code too, but that is clearly breaking the contract of the getSimpleName() method

Users might be relying on this behavior, so we would only break it if absolutely necessary.

**Comment by SirYwell** [comment]
> That's not a problem in principle, Spoon does not claim to maintain consistency with similar standard library methods.

As it's even documented that way, I guess that's fine. For me, it's more about what makes more sense. Looking at the commit it was introduced, it seems like it was used to determine if a type is a local type ([see here](https://github.com/INRIA/spoon/commit/9e0de7530627784e04545fce947a461b4f7309a7#diff-f8e7c95d49b9a41a115e25b7fb7dcd161d4852c5b76a9f1b58d0133198b67569R473)). This isn't required anymore and I didn't find any similar usage where it would be relevant.

> Users might be relying on this behavior, so we would only break it if absolutely necessary.

I agree, it would not make sense to just break compatibility. I'm not sure how you deal with "not-that-important-but-might-be-worth-to-change" kind of things in general, I just wanted to bring it up for discussion.

I guess it would be the best to keep it the current way for now and adapt it in my tests in #4108 and therefore also make sure that it is printed correctly?

**Comment by slarse** [comment]
> > Users might be relying on this behavior, so we would only break it if absolutely necessary.
> 
> I agree, it would not make sense to just break compatibility. I'm not sure how you deal with "not-that-important-but-might-be-worth-to-change" kind of things in general, I just wanted to bring it up for discussion.

In general, we just don't break compatibility. It has to be important for that. An example would be the typing error fixed in #4099. That fix was breaking, but was necessary as the typing was simply incorrect, and any reliance on it worked either incorrectly or just by accident.

> I guess it would be the best to keep it the current way for now and adapt it in my tests in #4108 and therefore also make sure that it is printed correctly?

I'd say so, yes.

**Comment by SirYwell** [comment]
Covered by #4108
