### ISSUE TITLE
NullPointerException in CtTypeReferenceImpl.getAllExecutables()

### ISSUE THREAD

**Issue by Andy1605** [INRIA/spoon#409]
Hi there,

The super class `sc` (`Class<?> sc = c.getSuperclass();`) in `CtTypeReferenceImpl.getAllExecutables()` could be null and should therefore be checked IMHO.
I can unfortunately not reproduce the NullPointerException, since i changed my original code several times, sorry about that. But it definitely happened.

Sincerely,
Andreas

**Comment by GerardPaligot** [comment]
The same thing for this issue, the bug is confirmed and the PR is done [here](https://github.com/INRIA/spoon/pull/411). But this PR will be merged in the next release (4.5.0).
