### ISSUE TITLE
Spoon visualisation not showing imports block

### ISSUE THREAD

**Issue by treaz** [INRIA/spoon#4102]
I have a very simple class loaded in the spoon visualisation GUI and I'm not seeing the imports section in the AST (neither or them)
```java
package com.horiaconstantin;

import org.junit.Test;
import static org.junit.Assert.assertEquals;

public class SpoonImportTest{
    @Test
    public void simpleTest(){
        assertEquals(3, 3);
    }
}
```
Am I missing something here? I didn't find any documentation about such a limitation

**Comment by monperrus** [comment]
This is normal. It's not a limitation it's a feature. Spoon provides a fully-resolved AST (you get from reference to declarations), meaning that the imports, which is syntactic sugar for not using fully-qualified names, are not part of the Spoon model by construction.

Put in another way, the imports would be part of a simple, naive parse tree, but not part of a high level AST.
