### ISSUE TITLE
The regular expression for line separators in CommentHelper is wrong

### ISSUE THREAD

**Issue by lyxell** [INRIA/spoon#4105]
While reading through some source code of Spoon I stumbled upon this regex

https://github.com/INRIA/spoon/blob/d18c944c48725eaccf6568ec22cd3a75d4496a3c/src/main/java/spoon/reflect/visitor/CommentHelper.java#L25-L28

This looks wrong to me, since neither `\\n\\r` (LF CR) nor `\\r` (CR) are valid line separators on any operating system I know of.

This should probably be replaced with:
```java
private static final Pattern LINE_SEPARATORS_RE = Pattern.compile("\\r\\n|\\n"); 
```
where `\r\n` (CR LF) is the line separator on Windows systems and `\n` (LF) is the line separator on Unix systems.

If the design of the current regex is intentional a comment should probably be added to clarify why these values are correct in this context.

Edit: Apparently a single `\r` is a valid line separator on a few old-school systems such as the C64, the ZX Spectrum and the Apple II, however, none of these systems run Java, see https://en.wikipedia.org/wiki/Newline#Representation for a complete list

**Comment by slarse** [comment]
Argh, another regex.

The quick fix here is of course just to adjust the regex to make some kind of sense. But IMO the best fix for a regex in production code is to remove it :)

> If the design of the current regex is intentional a comment should probably be added to clarify why these values are correct in this context.

I can't imagine so, this just looks like a bug that somehow has gone unnoticed.

> Apparently a single \r is a valid line separator on a few old-school systems such as the C64, the ZX Spectrum and the Apple II, however, none of these systems run Java, see https://en.wikipedia.org/wiki/Newline#Representation for a complete list

I don't think that list is complete. AFAIK, Mac OS 9 and earlier (that is to say, everything before the modern OSX/macOS) used `\r`. And that one [did have Java support](https://www.macworld.com/article/161457/mrj.html). But that's so long ago now that even knowing about it is not much more than trivia, so I don't see any reason to support anything but `LF` and `CRLF` line endings.

**Comment by I-Al-Istannen** [comment]
I guess `String#lines()` would be the nicest solution but that is Java 11+. What do you think of `\R`, i.e. `Pattern.compile("\R")`?

https://docs.oracle.com/en/java/javase/16/docs/api/java.base/java/util/regex/Pattern.html:
![image](https://user-images.githubusercontent.com/20284688/130215806-922ba48d-9549-4abe-8c61-df09b2491bb1.png)
