### ISSUE TITLE
Difference between `CtScanner` and `CtInheritanceScanner` purpose and usage

### ISSUE THREAD

**Issue by algomaster99** [INRIA/spoon#4109]
I came across them while I was working on https://github.com/SpoonLabs/gumtree-spoon-ast-diff/issues/157. I saw that the [TreeScanner](https://github.com/SpoonLabs/gumtree-spoon-ast-diff/blob/master/src/main/java/gumtree/spoon/builder/TreeScanner.java) extends from [CtScanner](https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/reflect/visitor/CtScanner.java) while [NodeCreator](https://github.com/SpoonLabs/gumtree-spoon-ast-diff/blob/master/src/main/java/gumtree/spoon/builder/NodeCreator.java) extends for the [CtInheritanceScanner](https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/reflect/visitor/CtInheritanceScanner.java), but I am not sure about the reason for such an implementation. Maybe an understanding of the difference of purpose of these two visitors will help.

**Comment by monperrus** [comment]
The contracts are different.

The core contract of `CtScanner` is, for each metamodel type, to:

1. to call enter
2. to call scan for each child element
3. to call exit

Example:

```java
	public <A extends Annotation> void visitCtAnnotation(final CtAnnotation<A> annotation) {
		enter(annotation);
		scan(CtRole.TYPE, annotation.getType());
		scan(CtRole.COMMENT, annotation.getComments());
		scan(CtRole.ANNOTATION_TYPE, annotation.getAnnotationType());
		scan(CtRole.ANNOTATION, annotation.getAnnotations());
		scan(CtRole.VALUE, annotation.getValues());
		exit(annotation);
	}
```

The core contract of `CtInheritanceScanner` is, for each metamodel type, to call scan* for all super interface. 

```java
	public <A extends Annotation> void visitCtAnnotation(CtAnnotation<A> e) {
		scanCtExpression(e);
		scanCtCodeElement(e);
		scanCtTypedElement(e);
		scanCtElement(e);
		scanCtVisitable(e);
		scanCtShadowable(e);
	}
```

**Comment by algomaster99** [comment]
Thanks, the difference is clear. I am also trying to look for what problem or shortcoming we were facing that spoon had to create a `CtInheritanceScanner`. I cannot figure out from the example of `NodeCreator` and `TreeScanner` above.

**Comment by monperrus** [comment]
For clients, the core use case of `CtInheritanceScanner` is to process all elements of a given abstract type. For example, if I want to visit all CtSadowable I would do;

```java
class MyShadowableScanner extends CtInheritanceScanner {
  @Override
  void scanCtVisitable(CtVisitable v) {
   // my code
  }
}

**Comment by algomaster99** [comment]
Thanks for your answer!
