### ISSUE TITLE
Disable sorald-buildbreaker

### ISSUE THREAD

**Issue by slarse** [INRIA/spoon#4144]
The version of SonarJava it uses is too prone to false positives, especially on dead stores. We need to upgrade the version of SonarJava in Sorald to 7+ before it can be useful.

**Comment by algomaster99** [comment]
If this was the only caveat, we can enable the build breaker job after I have upgraded the build breaker itself.

**Comment by slarse** [comment]
Well, yes the false positives was the only caveat but it's a pretty big one :)
