### ISSUE TITLE
Questions regarding getAllExecutables and typing contexts

### ISSUE THREAD

**Issue by I-Al-Istannen** [INRIA/spoon#4145]
As you can see in the profiling attached at the end, a good chunk of the runtime of JavadocApi is spent in `getAllExecutables`. Most of *that* time in turn is spent juggling around type adaptions / computing the signature.

I believe that whole Kladderadatsch was added in https://github.com/INRIA/spoon/pull/1218 (though I don't really find much justification or explanation there) to support generic subtype matches and likely to resolve things like:
```java
public class Foo<T> {
  public T foo(T t) {}
}

public class Bar extends Foo<String> {} // contains a "public String foo(String t)"
```

I am not sure why Spoon goes through all that trouble and a few hundred levels of recursion to achieve its task. Especially, when a small `rg "<[A-Z]>"` on the JDK source code only has ~12,000 matches. Does spoon perform type adaption regardless of the presence of generic types? Why is that needed?

## Disclaimer
Maybe my program is a very atypical use of the Spoon API, I don't have any other program to test against though.

## Profilings

![image](https://user-images.githubusercontent.com/20284688/131390204-c770d073-6b47-4f21-b6ff-658039006dbe.png)
![image](https://user-images.githubusercontent.com/20284688/131390296-cfc9a191-df4d-461f-96e2-653f2a872c2c.png)
![image](https://user-images.githubusercontent.com/20284688/131390358-cedbb518-b51c-4201-9a2d-349f438d7e72.png)

**Comment by I-Al-Istannen** [comment]
I am happy to report that this has gotten a lot better now with my type adaption PR merged. The method remains relatively costly though, but now spends a large chunk of time in the super hierarchy visitor instead :)

**Comment by slarse** [comment]
:champagne:
