### ISSUE TITLE
Intellij support

### ISSUE THREAD

**Issue by KhadanovichSergey** [INRIA/spoon#4159]
Hello :)

I implemented transformation processor and use spoon-maven-plugin to use it. It works well. But, intellij idea doesn't run spoon processors at compile time (build before run, for example) as it does for built-in annotation processors.

My question is: is there any intelllij support for spoon-maven-plugin. Or, may be, any plans to implement such plugin ?

**Comment by monperrus** [comment]
Hello @KhadanovichSergey, that's a duplicate of #3095, would you add your requirements there?

There is no plan to implement this, and an external contribution is very welcome.

**Comment by KhadanovichSergey** [comment]
@monperrus thanks for answer
