### ISSUE TITLE
Question regarding type parameter `T` in `CtClass`

### ISSUE THREAD

**Issue by algomaster99** [INRIA/spoon#4163]
There are some places where the presence of type parameter makes sense, for example, `CtExecutable`. The type parameter `R` of `CtExecutable<R>` represents its return type. However, this logic cannot be extrapolated for `CtClass` instances so my question is what does type parameter [`T` in `CtClass<T>`](https://spoon.gforge.inria.fr/mvnsites/spoon-core/apidocs/spoon/reflect/declaration/CtClass.html) represent?

**Comment by slarse** [comment]
The actual type. That is to say, `CtClass<String>` is Spoon's metamodel representation of `String`. It's analogous to the type parameter used in the stdlib class [`Class`](https://docs.oracle.com/javase/8/docs/api/java/lang/Class.html).

You can see some remnants of it being useful in e.g. `CtType.getActualClass`, which returns the native `Class<T>` equivalent.

It's largely not useful, to be honest. We are gravitating away from these type parameters, but it's a tricky proposition in trying to maintain backwards compatibility. New metamodel types added into Spoon are not parameterized.

**Comment by algomaster99** [comment]
> You can see some remnants of it being useful in e.g. CtType.getActualClass

Even this is no longer useful as it has been deprecated, and the reason is also clear in the [docs](https://spoon.gforge.inria.fr/mvnsites/spoon-core/apidocs/spoon/reflect/reference/CtTypeReference.html#getActualClass--.).

Thanks for the answer! On a side note, it may be useful to add the label "question" to this issue to search for it in the future. :)
