### ISSUE TITLE
fix static analysis warnings by LGTM

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#4180]
FYI, activated static analysis by LGTM, out of curiosity

https://github.com/marketplace/lgtm

Will deactivate if annoying

**Comment by monperrus** [comment]
FYI, the current LGTM report: https://lgtm.com/projects/g/INRIA/spoon?mode=tree&id=java%2Fcontradictory-type-checks%2Cjava%2Fdereferenced-value-may-be-null%2Cjava%2Finconsistent-equals-and-hashcode%2Cjava%2Findex-out-of-bounds%2Cjava%2Foutput-resource-leak%2Cjava%2Funchecked-cast-in-equals%2Cjava%2Funknown-javadoc-parameter%2Cjava%2Funused-container%2Cjava%2Fuseless-type-test%2Cjava%2Fzipslip&tag=external%2Fcwe%2Fcwe-022%2Cexternal%2Fcwe%2Fcwe-193%2Cexternal%2Fcwe%2Fcwe-404%2Cexternal%2Fcwe%2Fcwe-476%2Cexternal%2Fcwe%2Fcwe-561%2Cexternal%2Fcwe%2Fcwe-581%2Cexternal%2Fcwe%2Fcwe-772

1 alert of Arbitrary file write during archive extraction ("Zip Slip")
1 alert of Array index out of bounds in SnippetCompilationHelper.java
2 alerts of Container contents are never accessed across2 files
2 alerts of Inconsistent equals and hashCode across 2 files
17 alerts of Dereferenced variable may be null across 4 files
2 alerts of Potential output resource leak across 2 files
1 alert of Useless type test i nClassTypingContext.java

**Comment by MartinWitt** [comment]
I created PRs for the following problems:
1 alert of Arbitrary file write during archive extraction ("Zip Slip") #4199 
1 alert of Useless type test i nClassTypingContext.java #4196 
2 alerts of Potential output resource leak across 2 files #4197 
2 alerts of Container contents are never accessed across2 files #4198

PS: Could we add either add `hacktoberfest` to the topic or create a label `hacktoberfest-accepted`
> A repository/project is considered to be participating in Hacktoberfest if the 'hacktoberfest' topic is present and is accepting public contributions via pull requests. An individual pull request can also be opted-in directly by adding the 'hacktoberfest-accepted' label.

**Comment by MackieRitz** [comment]
Can i try this one?

**Comment by MartinWitt** [comment]
Sure, go ahead.

**Comment by MackieRitz** [comment]
For the zip vulnerability, we have to normalize the path starter right?
can i use  java.nio.file.Path.startsWith(--)

**Comment by monperrus** [comment]
Per https://github.com/INRIA/spoon/issues/4275#issuecomment-967286718 and https://github.com/INRIA/spoon/issues/4275#issuecomment-967437353 we are now deactivating lgtm.

**Comment by slarse** [comment]
So, feels like we should close this as we don't use LGTM anymore.
