### ISSUE TITLE
how to use Spoon to parser my code snippet into APIs?

### ISSUE THREAD

**Issue by yz-qiang** [INRIA/spoon#4182]
Hey,
I want to parser my code snippet with Spoon, but I don't know how to start it. what I first step should do and next, please help me.

**Comment by monperrus** [comment]
As discussed in the documentation at https://spoon.gforge.inria.fr/, a kick start is

```java
CtClass l = Launcher.parseClass("class A { void m() { System.out.println(\"yeah\");} }");
```

**Comment by yz-qiang** [comment]
Thanks for your reply. There has another question, can I use Spoon in Python? Because my project code is written by python.

**Comment by yz-qiang** [comment]
Thanks for your reply. Can you give me some suggestions to use Spoon in the python project, I have some trouble doing it.

**Comment by yz-qiang** [comment]
Thanks for your reply. Can you give me some suggestions to use Spoon in my python project, I have some trouble doing it.

**Comment by yz-qiang** [comment]
<img width="935" alt="Snipaste_2021-09-24_19-39-16" src="https://user-images.githubusercontent.com/72866861/134668510-56327b41-75b4-4fb3-adc6-6b905b2604f6.png">
This is a screenshot after running, it's right?

**Comment by I-Al-Istannen** [comment]
It would be helpful to know what you are trying to do, i.e. what your use case actually is. I don't really understand your title or comments. An API is an "Application Programming Interface" and I don't see how that relates to parsing code snippets.

Your code apparently runs so that's nice, you get the error because something uses SLF4J (Simple logging facade for java) for logging and you have not configured any implementations. SLF4J is just an API to log messages, the actual logger behind it can be swapped. Maybe an article such as https://www.baeldung.com/slf4j-with-log4j2-logback could help you pull in an actual logger.

I can't really comment on anything else as I have no idea what you are trying to do.

**Comment by yz-qiang** [comment]
I‘m sorry to confuse you. First, I truly need to parser code snippet into API with fully_qualified_name, for example, "List li = new List()" will be parsed into "java.util.list", and "Map.keyset().stream()" will be parsed into "Map.keySet() and Set.stream()". Spoon can do this work， right? Second, today is my first day to use Spoon,

**Comment by yz-qiang** [comment]
I‘m sorry to confuse you and thanks for your reply. 

**1.** I actually need to parser code snippet into API with fully_qualified_name, for example, "_List li = new List()_" will be parsed into "_java.util.list_", and "_Map.keyset().stream()_" will be parsed into "_Map.keySet() and Set.stream()_". Spoon can do this work, right?
**2.** Today is my first time using Spoon, I don't know how to start to use it. First, I successfully run an example in https://github.com/SpoonLabs/spoon-examples, but it generates too many files (in **target** directory), I don't know what they mean.   
**3.**  I follow https://spoon.gforge.inria.fr/first_analysis_processor.html,  execute an instruction, but it cannot work.
<img width="733" alt="1" src="https://user-images.githubusercontent.com/72866861/134687785-07d3f797-0bce-4cc6-8f14-8d43bf6f7ae3.png">

**Comment by ddy-ddy** [comment]
> I‘m sorry to confuse you and thanks for your reply.
> 
> **1.** I actually need to parser code snippet into API with fully_qualified_name, for example, "_List li = new List()_" will be parsed into "_java.util.list_", and "_Map.keyset().stream()_" will be parsed into "_Map.keySet() and Set.stream()_". Spoon can do this work, right?
> **2.** Today is my first time using Spoon, I don't know how to start to use it. First, I successfully run an example in https://github.com/SpoonLabs/spoon-examples, but it generates too many files (in **target** directory), I don't know what they mean.
> **3.** I follow https://spoon.gforge.inria.fr/first_analysis_processor.html, execute an instruction, but it cannot work.
> <img alt="1" width="733" src="https://user-images.githubusercontent.com/72866861/134687785-07d3f797-0bce-4cc6-8f14-8d43bf6f7ae3.png">

This is a supplementary document to item 2.
<img width="412" alt="截屏2021-09-24 下午10 43 02" src="https://user-images.githubusercontent.com/58058861/134694908-bdd874bc-0f01-4cf4-b7a2-d31d9d22176c.png">

**Comment by I-Al-Istannen** [comment]
> I‘m sorry to confuse you and thanks for your reply.
> 
> **1.** I actually need to parser code snippet into API with fully_qualified_name, for example, "_List li = new List()_" will be parsed into "_java.util.list_", and "_Map.keyset().stream()_" will be parsed into "_Map.keySet() and Set.stream()_". Spoon can do this work, right?
> **2.** Today is my first time using Spoon, I don't know how to start to use it. First, I successfully run an example in https://github.com/SpoonLabs/spoon-examples, but it generates too many files (in **target** directory), I don't know what they mean.
> **3.** I follow https://spoon.gforge.inria.fr/first_analysis_processor.html, execute an instruction, but it cannot work.
> <img alt="1" width="733" src="https://user-images.githubusercontent.com/72866861/134687785-07d3f797-0bce-4cc6-8f14-8d43bf6f7ae3.png">

1. Sorry, I am still not sure what you mean. You want to parse code snippets into the spoon model? Do you want to print them with fully qualified names? Do you want to modify them? Do you want to run them? Knowing your final goal would help. What you said so far are just starting steps. But it is no *plan* or *goal*, just parts of one. You might be able to use different methods to easier do what you want.
2. Files in target are only used for the build. They are not important for you and you can ignore that folder. The target folder just contains the compiled code, resources and generated code.
3. The `Test.java` file you passed as a parameter does not exist in that folder. Try passing *the full path* to the file as an argument.

**Comment by yz-qiang** [comment]
Thank you very much for answering my questions
1. Yes, I want to print them with fully qualified names. I have try different methods to do it, but failed.
2. Oh, I see. But what results do I need to focus on after I run_Mvn test_?
3. Yes, it can work. Thank you.

**Comment by I-Al-Istannen** [comment]
2. You do not need the maven test results, at least I don't know why you would. As I have no idea what you are trying to do I can't make a definite statement though.

As you still haven't answered my questions and I consequently have no idea what you are trying to do I am not sure I can really help you further. Without knowing what you are trying to achieve I can not help you. You are asking for something that could mean a *lot* of different things and can be accomplished in even more ways - it just depends on what you are *actually trying to do*. It currently feels a bit like an [XY Problem](https://xyproblem.info/).

Just printing the qualified names can be done by setting the `Environment#setPrettyPrintingMode` to `PRETTY_PRINTING_MODE.FULLYQUALIFIED`. (e.g. `launcher.getEnvironment().setPrettyPrintingMode(PRETTY_PRINTING_MODE.FULLYQUALIFIED);`)

**Comment by yz-qiang** [comment]
Thanks for your patient answer. I read your answer carefully. To tell my intent, I drew a picture.  **①** transform into **②** under **T**. As shown in the picture, _List\<String>_ (① with red color) transforms into _java.util.list<java.lang.String>_ (② with red color). Not only that, we also need to transforms _li.add('123')_ into _java.util.list.add(java.lang.string)_ (print in ②). Is there some way to achieve it? 
![image](https://user-images.githubusercontent.com/72866861/134766841-03b6254e-08d1-4b96-9422-1b226c826eb8.png)

**Comment by I-Al-Istannen** [comment]
The code `T` in your picture should work?
```java
Launcher launcher = new Launcher();
launcher.getEnvironment().setPrettyPrintingMode(PRETTY_PRINTING_MODE.FULLYQUALIFIED);
launcher.addInputResource("/tmp/test/Test.java");
launcher.setSourceOutputDirectory("/tmp/test/formatted");
launcher.run();
```
Correctly formats the files and stores them in `/tmp/test/formatted`. If you only have a single java input file you can also easily format things manually to a single String. That might be more convenient than throwing the output in a directory.
```java
Launcher launcher = new Launcher();
launcher.getEnvironment().setPrettyPrintingMode(PRETTY_PRINTING_MODE.FULLYQUALIFIED);
launcher.addInputResource("/tmp/test/Test.java");
CtModel model = launcher.buildModel();

String output = model.getAllTypes()
    .stream()
    .map(Object::toString)
    .collect(Collectors.joining("\n\n", "", "\n"));

System.out.println("\n==== OUTPUT ====\n");
System.out.println(output);
```
If you have multiple files you will need to split up types into their own files again or, if you do it all in java, you can just call `toString` on each type in the model and then do whatever you need with them.

It's also possible that there's a nicer way I am not aware of.

**Comment by slarse** [comment]
> li.add('123') into java.util.list.add(java.lang.string) (print in ②)

This is not something the pretty printer will do for you out of the box. The transform you want does not actually produce valid Java code. `li.add("123")` is a method call on a local variable, and a local variable can only be referenced by its simple name.

The only way for you to achieve this would be to extend the pretty-printer `DefaultJavaPrettyPrinter` and override the way that local variable references are printed. I.e. print the fully qualified name to the type of the variable instead of the variable's own simple name.

**Comment by yz-qiang** [comment]
> The code `T` in your picture should work?
> 
> ```java
> Launcher launcher = new Launcher();
> launcher.getEnvironment().setPrettyPrintingMode(PRETTY_PRINTING_MODE.FULLYQUALIFIED);
> launcher.addInputResource("/tmp/test/Test.java");
> launcher.setSourceOutputDirectory("/tmp/test/formatted");
> launcher.run();
> ```
> 
> Correctly formats the files and stores them in `/tmp/test/formatted`. If you only have a single java input file you can also easily format things manually to a single String. That might be more convenient than throwing the output in a directory.
> 
> ```java
> Launcher launcher = new Launcher();
> launcher.getEnvironment().setPrettyPrintingMode(PRETTY_PRINTING_MODE.FULLYQUALIFIED);
> launcher.addInputResource("/tmp/test/Test.java");
> CtModel model = launcher.buildModel();
> 
> String output = model.getAllTypes()
>     .stream()
>     .map(Object::toString)
>     .collect(Collectors.joining("\n\n", "", "\n"));
> 
> System.out.println("\n==== OUTPUT ====\n");
> System.out.println(output);
> ```
> 
> If you have multiple files you will need to split up types into their own files again or, if you do it all in java, you can just call `toString` on each type in the model and then do whatever you need with them.
> 
> It's also possible that there's a nicer way I am not aware of.

The code in T can work the same as the code you provided, but it still cannot transform li.add("123") into java.util.list.add(java.lang.object) and printed.   At this time, I noticed the generated AST, and the information in AST can print in a structural way? Please look at the picture. 
![image](https://user-images.githubusercontent.com/72866861/134789773-943df00d-bd2a-45bf-83a7-a2f71440f1cd.png)

**Comment by slarse** [comment]
@yz-qiang See my answer above

**Comment by I-Al-Istannen** [comment]
I read that but it wasn't in the picture and I assumed it was a mistake :)

If you really want that, maybe this abomination (sorry Slarse) will be a starting point then:

```java
Launcher launcher = new Launcher();
launcher.getEnvironment().setPrettyPrintingMode(PRETTY_PRINTING_MODE.FULLYQUALIFIED);
launcher.addInputResource("/tmp/test/Test.java");
CtModel model = launcher.buildModel();

String output = model.getAllTypes()
        .stream()
        .map(it -> {
            TokenWriter tokenWriter = new DefaultTokenWriter();
            DefaultJavaPrettyPrinter printer = new DefaultJavaPrettyPrinter(launcher.getEnvironment()) {

                @Override
                public <T> void visitCtInvocation(CtInvocation<T> invocation) {
                    tokenWriter.writeCodeSnippet(invocation.getExecutable().getDeclaringType().getQualifiedName());
                    tokenWriter.writeCodeSnippet(".");
                    tokenWriter.writeCodeSnippet(invocation.getExecutable().getSignature());
                }
            };
            printer.setPrinterTokenWriter(tokenWriter);

            return printer.prettyprint(it);
        })
        .collect(Collectors.joining("\n\n", "", "\n"));

System.out.println("\n==== OUTPUT ====\n");
System.out.println(output);
```

This will probably explode if the executable's declaring type is not in the classpath, but in that case you are mostly screwed anyways.

**Comment by yz-qiang** [comment]
> I read that but it wasn't in the picture and I assumed it was a mistake :)
> 
> If you really want that, maybe this abomination (sorry Slarse) will be a starting point then:
> 
> ```java
> Launcher launcher = new Launcher();
> launcher.getEnvironment().setPrettyPrintingMode(PRETTY_PRINTING_MODE.FULLYQUALIFIED);
> launcher.addInputResource("/tmp/test/Test.java");
> CtModel model = launcher.buildModel();
> 
> String output = model.getAllTypes()
>         .stream()
>         .map(it -> {
>             TokenWriter tokenWriter = new DefaultTokenWriter();
>             DefaultJavaPrettyPrinter printer = new DefaultJavaPrettyPrinter(launcher.getEnvironment()) {
> 
>                 @Override
>                 public <T> void visitCtInvocation(CtInvocation<T> invocation) {
>                     tokenWriter.writeCodeSnippet(invocation.getExecutable().getDeclaringType().getQualifiedName());
>                     tokenWriter.writeCodeSnippet(".");
>                     tokenWriter.writeCodeSnippet(invocation.getExecutable().getSignature());
>                 }
>             };
>             printer.setPrinterTokenWriter(tokenWriter);
> 
>             return printer.prettyprint(it);
>         })
>         .collect(Collectors.joining("\n\n", "", "\n"));
> 
> System.out.println("\n==== OUTPUT ====\n");
> System.out.println(output);
> ```
> 
> This will probably explode if the executable's declaring type is not in the classpath, but in that case you are mostly screwed anyways.

I'll be indebted to you for what you've done. Thank you so much, and the code is so pretty.

**Comment by yz-qiang** [comment]
> @yz-qiang See my answer above

Thank you :)

**Comment by yz-qiang** [comment]
![image](https://user-images.githubusercontent.com/72866861/135098543-ff20d006-9a38-4ceb-ab75-40bddbc8d48b.png)
Sorry to trouble you again. Is there some way to print  `map.keyset().iterator()`  as `java.util.map.keyset()` and `java.util.set.iterator()`? As shown in the picture above, and here are some code fragments below. 
![image](https://user-images.githubusercontent.com/72866861/135099819-e29479d2-ea2c-4163-83a9-bfa83e911af6.png)

**Comment by I-Al-Istannen** [comment]
Uh you can do that quite easily by recursing but it **really** sounds like you are approaching it wrong.

Are you trying to get a list of all called methods? You can do that a lot easier with spoon. What are you doing with the spoon output? I am pretty sure there is a better way to achieve your *real* goal. And not mangle the code in printing. The code in printing will not recurse into lambda arguments as arguments are ignored in your format.

----

<details>
<summary> If you *really* believe you want that that</summary>

```java
@Override
public <T> void visitCtInvocation(CtInvocation<T> invocation) {
  // This is quite specific and probably misses things (though not chains),
  // but we do not want to print the name of the variable we called the 
  // method on.
  if (invocation.getTarget() instanceof CtInvocation) {
    visitCtInvocation((CtInvocation) invocation.getTarget());
    tokenWriter.writeCodeSnippet("\n    .");
  }

  if (invocation.getExecutable().getDeclaringType() == null) {
    tokenWriter.writeCodeSnippet("<unknown>");
  } else {
    tokenWriter.writeCodeSnippet(
        invocation.getExecutable().getDeclaringType().getQualifiedName());
  }
  tokenWriter.writeCodeSnippet(".");
  tokenWriter.writeCodeSnippet(invocation.getExecutable().getSignature());
}

```
</details>

**Comment by yz-qiang** [comment]
> Uh you can do that quite easily by recursing but it **really** sounds like you are approaching it wrong.
> 
> Are you trying to get a list of all called methods? You can do that a lot easier with spoon. What are you doing with the spoon output? I am pretty sure there is a better way to achieve your _real_ goal. And not mangle the code in printing. The code in printing will not recurse into lambda arguments as arguments are ignored in your format.
> 
> If you *really* believe you want that that

Yes, I'm trying to get a list of all called methods. What's the easier way to do it with Spoon?

**Comment by I-Al-Istannen** [comment]
That was the reason I tried to get you to tell me *what you actually wanted to do* and mentioned the XY problem. 

To answer the question though, you can just take a Scanner and visit CtInvocation and stash them away:

```java
	@Test
	public void foo() {
		Launcher launcher = new Launcher();
		launcher.addInputResource("/tmp/test/Test.java");
		CtModel model = launcher.buildModel();
		List<CtInvocation<?>> invocations = new ArrayList<>();

		CtScanner scanner = new CtScanner() {
			@Override
			public <T> void visitCtInvocation(CtInvocation<T> invocation) {
				super.visitCtInvocation(invocation);
				invocations.add(invocation);
			}
		};
		model.getAllModules().stream().map(CtModule::getRootPackage).forEach(scanner::scan);

                // We now have all invocations in the list and can filter them, inspect them, print them, ...

		// We can print all invocations. Not sure what you want to use them for, but operating on
		// CtInvocation and CtExecutable is a lot nicer and richer than parsing Strings :)
		
		// If you want to get a module and varargs-aware pretty printed FQN you could look at
		// https://github.com/I-Al-Istannen/JavadocApi/blob/849c8f383291c6402148b75a4fcafb7bf19430d0/src/main/java/de/ialistannen/javadocapi/spoon/JavadocElementExtractor.java#L548-L561
                // The code in that class is garbage and works around a lot of weirdness and bugs in spoon's model, but
                // that method might nonetheless serve as some inspiration.
		System.out.println("\n==== METHOD LIST (SIGNATURES) ====\n");
		for (CtInvocation<?> invocation : invocations) {
			String methodName = "";
			if (invocation.getExecutable().getDeclaringType() != null) {
				methodName += invocation.getExecutable().getDeclaringType().getQualifiedName();
			} else {
                                // Spoon has no idea what type this belongs to. This might be because the type is not
                                // on the classpath or because spoon has a bug.
				methodName += "<unknown type>";
			}
			methodName += "#";
			methodName += invocation.getExecutable().getSignature();
			System.out.println(methodName);
		}
	}

```

**Comment by yz-qiang** [comment]
> That was the reason I tried to get you to tell me _what you actually wanted to do_ and mentioned the XY problem.
> 
> To answer the question though, you can just take a Scanner and visit CtInvocation and stash them away:
> 
> ```java
> 	@Test
> 	public void foo() {
> 		Launcher launcher = new Launcher();
> 		launcher.addInputResource("/tmp/test/Test.java");
> 		CtModel model = launcher.buildModel();
> 		List<CtInvocation<?>> invocations = new ArrayList<>();
> 
> 		CtScanner scanner = new CtScanner() {
> 			@Override
> 			public <T> void visitCtInvocation(CtInvocation<T> invocation) {
> 				super.visitCtInvocation(invocation);
> 				invocations.add(invocation);
> 			}
> 		};
> 		model.getAllModules().stream().map(CtModule::getRootPackage).forEach(scanner::scan);
> 
>                 // We now have all invocations in the list and can filter them, inspect them, print them, ...
> 
> 		// We can print all invocations. Not sure what you want to use them for, but operating on
> 		// CtInvocation and CtExecutable is a lot nicer and richer than parsing Strings :)
> 		
> 		// If you want to get a module and varargs-aware pretty printed FQN you could look at
> 		// https://github.com/I-Al-Istannen/JavadocApi/blob/849c8f383291c6402148b75a4fcafb7bf19430d0/src/main/java/de/ialistannen/javadocapi/spoon/JavadocElementExtractor.java#L548-L561
>                 // The code in that class is garbage and works around a lot of weirdness and bugs in spoon's model, but
>                 // that method might nonetheless serve as some inspiration.
> 		System.out.println("\n==== METHOD LIST (SIGNATURES) ====\n");
> 		for (CtInvocation<?> invocation : invocations) {
> 			String methodName = "";
> 			if (invocation.getExecutable().getDeclaringType() != null) {
> 				methodName += invocation.getExecutable().getDeclaringType().getQualifiedName();
> 			} else {
>                                 // Spoon has no idea what type this belongs to. This might be because the type is not
>                                 // on the classpath or because spoon has a bug.
> 				methodName += "<unknown type>";
> 			}
> 			methodName += "#";
> 			methodName += invocation.getExecutable().getSignature();
> 			System.out.println(methodName);
> 		}
> 	}
> ```

Wow, it's pretty good. Thank you so much. I can continue my downstream work. XY problem is a serious problem in our dialogue, exactly. I will pay attention to it.
