### ISSUE TITLE
Update infrastructure to Java 11 (Jenkins, etc)

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#4192]
In our CI https://ci.inria.fr/sos/, we now run spoon-maven-plugin with Java 11.

However, it crashes with

```
[ERROR] Failed to execute goal fr.inria.gforge.spoon:spoon-maven-plugin:3.1:generate (default) on project guice: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap') -> [Help 1]
```
Ref: https://ci.inria.fr/sos/job/Google%20Guice/1846/console

**Comment by monperrus** [comment]
Indeed spoon-maven-plugin's CI fails with 11: https://github.com/SpoonLabs/spoon-maven-plugin/pull/80

**Comment by monperrus** [comment]
Spoon-maven-plugin in Java 11 merged

**Comment by monperrus** [comment]
Now problem with classloader, WIP at https://github.com/SpoonLabs/spoon-maven-plugin/pull/104

**Comment by monperrus** [comment]
https://github.com/SpoonLabs/spoon-maven-plugin/pull/104 merged!

**Comment by monperrus** [comment]
Next step to fix SOS is https://github.com/INRIA/spoon/pull/4206

**Comment by monperrus** [comment]
Bukkit is green again: https://ci.inria.fr/sos/job/Bukkit/2101/

**Comment by monperrus** [comment]
Java8-workshop is green again: https://ci.inria.fr/sos/job/Java8%20Workshop/2228/

**Comment by monperrus** [comment]
The other failures are due to the projects under test not being Java 11 compatible. The changes in spoon-maven-plugin seem OK, I'll publish spoon-maven-plugin 3.5.

**Comment by monperrus** [comment]
Casper now works on Java 11: https://ci.inria.fr/sos/job/casper/1794/console

Changelog:

- bumped ASM and fix backward incompatibilities with `RemappingFieldAdapter`
- add to do some surgery to remove runtime annotation `HotSpotIntrinsicCandidate`

Reference: https://github.com/Spirals-Team/casper/commit/cb193c65297e926adbbe601fdd3ce98411f67f3b

CC @bcornu @barr @seintur

**Comment by monperrus** [comment]
Jimfs is green again https://ci.inria.fr/sos/job/Jimfs/1809/console

**Comment by monperrus** [comment]
Nopol is now green with Java 11:

* Port: https://github.com/SpoonLabs/nopol/pull/214
* https://ci.inria.fr/sos/job/nopol/1475/

**Comment by monperrus** [comment]
Dspot is green again, full Java 11: https://ci.inria.fr/sos/job/dspot/

**Comment by monperrus** [comment]
The whole CI infrastructure is now Java 11+, see Github Actions and https://ci.inria.fr/sos/.

Thus, we can close.

**Comment by slarse** [comment]
That's a big milestone. Nicely done @monperrus .
