### ISSUE TITLE
Can't Resolve Dependencies -> action: modify doc about using Spoon with Gradle

### ISSUE THREAD

**Issue by chairbender** [INRIA/spoon#420]
I tried adding spoon-core as a dependency to my gradle build script and I got this message:

    Could not find org.eclipse.jdt:org.eclipse.jdt.core:3.12.0.v20150913-1717.
    Searched in the following locations:
    https://repo1.maven.org/maven2/org/eclipse/jdt/org.eclipse.jdt.core/3.12.0.v20150913-1717/org.eclipse.jdt.core-3.12.0.v20150913-1717.pom
    https://repo1.maven.org/maven2/org/eclipse/jdt/org.eclipse.jdt.core/3.12.0.v20150913-1717/org.eclipse.jdt.core-3.12.0.v20150913-1717.jar

It appears that one of the dependencies is not available in the maven central repository, though perhaps it was at some point. Can this be fixed somehow? Is there a workaround to enable it to resolve the dependency some other way?

**Comment by chairbender** [comment]
I solved this by adding the repository https://repo.eclipse.org/content/repositories/eclipse-staging/

Can this be listed as a required repository entry in the README.md?

**Comment by GerardPaligot** [comment]
Hi @chairbender,

Which version of spoon have you used? The last released (4.4.1) or the last snapshot (4.5.1)?

**Comment by chairbender** [comment]
Latest release - 4.4.1.

**Comment by GerardPaligot** [comment]
It is weird because the repository is specified in the [pom.xml](https://repo1.maven.org/maven2/fr/inria/gforge/spoon/spoon-core/4.4.1/spoon-core-4.4.1.pom) file on maven central.

**Comment by TealOcean** [comment]
Same issue here. Had to add the repository @chairbender specified.
