### ISSUE TITLE
Feature Request: Extra Data Field

### ISSUE THREAD

**Issue by alcides** [INRIA/spoon#422]
### Use case scenario:

I am performing static analysis of the AST. I want to save information related to each node, and then I want to perform operations on the AST, while maintaining the extra information of each node. (I am doing this for automatic parallelization, cost-model analysis and so on).

### How am I doing this and what the issue is:

Right now I am using an HashMap from each ASTNode to an Object I created. However, whenever I perform modifications on the AST, the replacement methods in Spoon change the AST nodes (specially parents of the node I am replacing), leading to new nodes that I have no information of in my hashmap. This was very troublesome to fix, and I believe I still have bugs on my code because of issues like this.

## How I propose to fix this:

Adding an Object field to CtElement. A Generic type would be useful, but would add a lot of extra code to everyone else's code. Being an Object, one could easily (and unsafely) cast it to our own data type.

I know it is possible to create another factory for my own Nodes. The problem is that I don't want to create 30-something classes just for adding a field. This and they won't be compatible with all the code that uses the existing factory or factory elements.

**Comment by monperrus** [comment]
Basically a `CtElement.setMetadata(String key, Object val)`?

I like the idea.

**Comment by alcides** [comment]
Exactly.

However, is cases an element is internally replaced by another (sometimes of the same type), the metadata should be copied to the new element.

**Comment by monperrus** [comment]
do you mean with `CtElement.replace`?

**Comment by alcides** [comment]
Yes, and with SubstitutionVisitor (and similar classes/methods).

**Comment by monperrus** [comment]
Would you propose it as a pull request?
