### ISSUE TITLE
JetBrains Qodana static analyzer 

### ISSUE THREAD

**Issue by MartinWitt** [INRIA/spoon#4242]
As I read in some articles like [https://sdtimes.com/softwaredev/jetbrains-launches-code-quality-platform-qodana/](https://sdtimes.com/softwaredev/jetbrains-launches-code-quality-platform-qodana/) it seems that the basic Qodana version will be free. Qodana is JetBrains static analyzer from IntelliJ as CI/GitHub Action. Currently, IntelliJ is state of the art for static analysis and miles ahead of the other analyzers/IDEs. We could explore the integration of [https://github.com/JetBrains/qodana-action](https://github.com/JetBrains/qodana-action). 

Adding a newer static analyzer has always some risks:
- false positives
- a lot of open work to fix alerts in the current code base
- annoy new committers with stricter rules

And because I trust JetBrains to create excellent products, we would more or less kill the chance for smaller analyzers like LGTM.

Any opinions on exploring the new analyzer and if we should try to use the chance to increase the code quality?

**Comment by MartinWitt** [comment]
Closed by #4244

**Comment by MartinWitt** [comment]
In a new update, Qodana got an improvement, a printing feature of all issues, see here https://github.com/INRIA/spoon/runs/4560633813 if you are interested.

**Comment by monperrus** [comment]
Qodana adds "Unchanged files with check annotations", see https://github.com/INRIA/spoon/pull/4481/files

@MartinWitt How to deactivate this?

**Comment by MartinWitt** [comment]
This seems like a new GitHub feature, I have never seen before. Because it's marked as beta, I think we can't deactivate it.

**Comment by monperrus** [comment]
It must be because Qodana writes a special file somewhere? maybe a Sarif file 
(https://docs.oasis-open.org/sarif/sarif/v2.0/sarif-v2.0.html)?

**Comment by MartinWitt** [comment]
We never activated the upload, but it seems like in some version a flag was added for the upload with default value true. Potential fix: #4484
