### ISSUE TITLE
Problem with type intersections 

### ISSUE THREAD

**Issue by DDoS** [INRIA/spoon#425]
When migrating our project to Java 8 we came across issues with Spoon's Java 8 support. `IntersectionCastTypeBinding` and `PolyTypeBinding` were not being used by `JDTTreeBuilder` and `createExecutableReferenceExpression` was causing problems with a specific method reference (see: https://github.com/SpongePowered/SpongeAPI/commit/55abbe5f7804570e22fcf0eaf40985fa1d49849c). I hacked around the problems in a fork here: https://github.com/SpongePowered/spoon/commit/0443dbeb5eaf582dd63a80acbe65a8b91c1ccf74. You can find some more details in the comments, but I want to put the emphasis on:

> One big issue is the new TypeIntersection which is a subtype of Type. Since it represents multiple types, most CtTypeReference methods, which expect a single type, can't properly be implemented by CtTypeIntersectionReference.

We also had to fix the source code generator. It isn't related to Java 8, but you can find the commit here: https://github.com/SpongePowered/spoon/commit/ae40d42b1ef451b878282dc70c0e68fd4ab052fb

**Comment by GerardPaligot** [comment]
If I use the latest version of spoon (4.5.0-SNAPSHOT), the output seems good. For example, when I apply Spoon on:

```java
private static final Collector<Object, ImmutableList.Builder<Object>, ImmutableList<Object>> IMMUTABLE_LIST_COLLECTOR =
		Collector.of(ImmutableList::builder,
				ImmutableList.Builder::add,
				(a, b) -> a.addAll(b.build()),
				ImmutableList.Builder::build);

private static final Collector<Object, ImmutableSet.Builder<Object>, ImmutableSet<Object>> IMMUTABLE_SET_COLLECTOR =
		Collector.of(ImmutableSet::builder,
				ImmutableSet.Builder::add,
				(a, b) -> a.addAll(b.build()),
				ImmutableSet.Builder::build,
				Collector.Characteristics.UNORDERED);
```

The output is:

```java
private static final java.util.stream.Collector<java.lang.Object, com.google.common.collect.ImmutableList.Builder<java.lang.Object>, com.google.common.collect.ImmutableList<java.lang.Object>> IMMUTABLE_LIST_COLLECTOR =
        java.util.stream.Collector.of(com.google.common.collect.ImmutableList::builder,
                com.google.common.collect.ImmutableList.Builder::add,
                ( a, b) -> a.addAll(b.build()),
                com.google.common.collect.ImmutableList.Builder::build);

private static final java.util.stream.Collector<java.lang.Object, com.google.common.collect.ImmutableSet.Builder<java.lang.Object>, com.google.common.collect.ImmutableSet<java.lang.Object>> IMMUTABLE_SET_COLLECTOR =
        java.util.stream.Collector.of(com.google.common.collect.ImmutableSet::builder,
                com.google.common.collect.ImmutableSet.Builder::add,
                ( a, b) -> a.addAll(b.build()),
                com.google.common.collect.ImmutableSet.Builder::build,
                java.util.stream.Collector.Characteristics.UNORDERED);
```

Can you confirm me that there isn't any problem when you update your fork of Spoon?
