### ISSUE TITLE
Make the check mojo less verbose by default

### ISSUE THREAD

**Issue by vmassol** [INRIA/spoon#4250]
```
[INFO] --- spoon-maven-plugin:3.5:check (spoon-test) @ xwiki-commons-blame-api ---
[INFO] Running in FULLCLASSPATH mode (doc: http://spoon.gforge.inria.fr/launcher.html).
[INFO] Spoon version ${project.version}
[INFO] running Spoon...
[INFO] start processing...
[INFO] org.xwiki.tool.spoon.JUnit5JUnit4Processor
[INFO] end of processing: 
[INFO] no errors, no warnings
```

This increases a lot the XWiki build logs unnecessarily. We don't need this since the information is already contained in the spoon configuration we set (you could decide to output them when they're not specified maybe). 

I would remove:
- `Running in FULLCLASSPATH mode (doc: http://spoon.gforge.inria.fr/launcher.html).``
- ` Spoon version ${project.version}`
- ```
  start processing...
  org.xwiki.tool.spoon.JUnit5JUnit4Processor
  end of processing: 
  no errors, no warnings
  ```

I'd just keep `Running Spoon...` (uppercase `R` BTW ;)) to indicate it's executing. If there are warnings or errors, I guess they'll be displayed so no need to say there were no errors.

Also all these info should be displayed when Maven is executed in debug mode (`-X`).

WDYT?

Thanks

**Comment by monperrus** [comment]
cc/ @yogyagamage
