### ISSUE TITLE
Can I print the generate AST into json file?

### ISSUE THREAD

**Issue by zhiwenluo0802** [INRIA/spoon#4264]
Hello, 
we parse the .java file with Spoon, and generate a AST model, can we output the AST into a .json file, like:
```
[Spoon Tree Root:{
   CtRootPackage:{
      Ctclass:{
        CtMethod:{},
        CtBlock:{
         CtLocavariable:{}
         .....}}}
    }]
```
 Thank you so much :)

**Comment by monperrus** [comment]
Yes, see https://github.com/SpoonLabs/gumtree-spoon-ast-diff/blob/master/src/main/java/gumtree/spoon/builder/Json4SpoonGenerator.java

**Comment by zhiwenluo0802** [comment]
ah, sorry to disturb you again, can you show me an example how to use it. Please. :(

**Comment by slarse** [comment]
@zhiwenluo0802 Sure. For example, to print the unnamed module (default module) as JSON to standard output, you could do something like this.

```java
Launcher launcher = new Launcher();
launcher.addInputResource("path/to/your/source/files"); // add your source files here!

CtModel model = launcher.buildModel();

var jsonGenerator = new Json4SpoonGenerator();
String unnamedModuleJson = jsonGenerator.getJSONasString(model.getUnnamedModule());

System.out.println(unnamedModuleJson);
```

Check out the other methods of `Json4SpoonGenerator` for other variations of this. You can pass in any `CtElement`, and get JSON out.

Do note that `Json4SpoonGenerator` is part of the `gumtree-spoon-ast-diff` package, which doesn't ship with Spoon. See  https://github.com/SpoonLabs/gumtree-spoon-ast-diff.

**Comment by zhiwenluo0802** [comment]
> @zhiwenluo0802 Sure. For example, to print the unnamed module (default module) as JSON to standard output, you could do something like this.
> 
> ```java
> Launcher launcher = new Launcher();
> launcher.addInputResource("path/to/your/source/files"); // add your source files here!
> 
> CtModel model = launcher.buildModel();
> 
> var jsonGenerator = new Json4SpoonGenerator();
> String unnamedModuleJson = jsonGenerator.getJSONasString(model.getUnnamedModule());
> 
> System.out.println(unnamedModuleJson);
> ```
> 
> Check out the other methods of `Json4SpoonGenerator` for other variations of this. You can pass in any `CtElement`, and get JSON out.
> 
> Do note that `Json4SpoonGenerator` is part of the `gumtree-spoon-ast-diff` package, which doesn't ship with Spoon. See https://github.com/SpoonLabs/gumtree-spoon-ast-diff.

Thanks for your reply :). I ran this example, it is succeeded. I have a question about the results.
 For example. I parsed the `Stream<String> stream = map.keySet().stream();`, into `{
                          "label": "stream",
                          "type": "Invocation",
                          "children": [
                            {
                              "label": "keySet",
                              "type": "Invocation",
                              "children": [
                                {
                                  "label": "map",
                                  "type": "VariableRead",
                                  "children": []
                                }
                              ]
                            }`, I can get the `keySet()` FQN is `java.util.Map.keyset` by the _label_ in _children_. For the `stream()` I can't get it FQN. I noticed it can infer from generated AST by the _ctTypeReference_, so the output .json file can do it? The generated AST as show:
<img width="339" alt="Snipaste_2021-11-03_10-34-56" src="https://user-images.githubusercontent.com/80459540/140002775-b5a4bde9-7385-4da6-a5fe-8f2924d10749.png">

Thank you

**Comment by slarse** [comment]
Hi @zhiwenluo0802,

It appears as if it doesn't print the return types of method invocations. You probably need to go into the code and alter it to get that behavior.
