### ISSUE TITLE
[Bug] Test failure in TestModule.testModuleNames()

### ISSUE THREAD

**Issue by xzel23** [INRIA/spoon#4285]
**Describe the bug**
Test fails in `testModuleNames()` when doing `assertTrue(list.contains("bar"))`.

**To Reproduce**
Check out Spoon; run `mvn compile` then `mvn test`

**Notes**
In that test case, an array of compilation units is retrieved and then the names of the two first entries of that list are inserted into a list. Then a test is made to check if both "foo" and "bar" are contained in that list. When I run this test on my machine, the list contains four entries, two with a module name of "bar" and two with a module name of "foo", so the test result depends on the ordering of rresults.

An easy fix would be to create a list consisting of all four module names, so instead of creating the list like this:

		List list = new ArrayList<>(Arrays.asList(new String[]{String.copyValueOf(cu[0].module),String.copyValueOf(cu[1].module)}));

it should be done like this:

		List<String> list = Arrays.asList(cu).stream().map(CompilationUnit::getModuleName).map(String::copyValueOf).collect(Collectors.toList());

However I am not familiar enough with the Spoon source to know if there really should be four compilation units in that list, or if it should be two.

Path to the test files: `src/test/resources/spoon/test/module/code-multiple-modules`

**Operating system, JDK and Spoon version used**

* OS: MacOS 12.0.1
* JDK: openjdk 17.0.1 2021-10-19 GraalVM CE 21.3.0 (build 17.0.1+12-jvmci-21.3-b05)
* Spoon version: Source on Github, revison 15bd93f5a685474f39a8957ffa4cb94bfe171eea

**Comment by SirYwell** [comment]
Seems like the order can be tracked down to depend on `File#listFiles()` which does indeed not guarantee any specific order.

I think your suggestion is a reasonable solution. That said, you can use [`Arrays.stream(cu)`](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/Arrays.html#stream(T%5B%5D)) to make it even simpler.
