### ISSUE TITLE
Rewrite `SpoonPom.guessMavenHome` so that it correctly looks up the path to `mvn` executable

### ISSUE THREAD

**Issue by algomaster99** [INRIA/spoon#4290]
`SpoonPom.guessMavenHome` abruptly stopped working on Windows in sorald (one of spoon's user). Its reason has been documented [here](https://github.com/INRIA/spoon/pull/4272#issuecomment-968293590) and for now, we have implemented a [workaround](https://github.com/SpoonLabs/sorald/pull/617) in sorald which lets our tests pass. However, we could re-implement `guessMavenHome` and overall improve [SpoonPom.java](https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/support/compiler/SpoonPom.java) in terms of [error messages](https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/support/compiler/SpoonPom.java#L568) and how it fetches the path. We can follow how it is implemented in [Java Language Server](https://github.com/georgewfraser/java-language-server/commit/40b76143b17f9b0fcd3d09106d621f45f6c61cea). This would perform the exact look up of the executable and won't rely on executing `mvn -version`.

**Comment by slarse** [comment]
> SpoonPom.guessMavenHome abruptly stopped working on Windows in sorald (one of spoon's user).

Correction: It never worked on Windows in the presence of a `SecurityManager` :)
