### ISSUE TITLE
[Bug] NPE in Launcher.prettyPrint() due to not checking return of File.getParent()

### ISSUE THREAD

**Issue by xzel23** [INRIA/spoon#4302]
**Describe the bug**
Program throws NPE in `Launcher.prettyPrint()` when the path to the current resource has no parent.

**To Reproduce**

Input:
I think the actual input doesn't matter much because the problem lies in manipulating Strings to create paths instead of using the JDK classes for that purpose. I ran into this bug with the following input:
```java
package nested_generic_class;

import java.util.function.Consumer;

public class Foo implements Consumer<Foo.Bar> {
    enum Bar {
        A, B;
    }

    @Override
    public void accept(Bar bar) {
        System.out.println(bar.name());
    }
}
```

Processing with Spoon:
```java
        Launcher launcher = new Launcher();
        launcher.addInputResource(new VirtualFile(code));
        launcher.getEnvironment().setComplianceLevel(16);
        launcher.getEnvironment().setNoClasspath(true);
        launcher.getEnvironment().setAutoImports(true);
        launcher.getEnvironment().setPreserveLineNumbers(true);
        
        launcher.prettyprint();
```

Output:
```java
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "String.substring(int)" because "resourceParentPath" is null
	at spoon.Launcher.prettyprint(Launcher.java:816)
	at spoon_issues.Main.main(Main.java:27)
```

Note that you can also open a pull request reproducing the issue and reference that, instead of writing additional information here.

**Operating system, JDK and Spoon version used**

* OS: MacOS 12.0.1 (Monterey)
* JDK: 17 - OpenJDK Runtime Environment GraalVM CE 21.3.0 (build 17.0.1+12-jvmci-21.3-b05)
* Spoon version: current Github

**Comment by slarse** [comment]
Using Strings for paths is a known bad habit in Spoon. A lot of it predates Java 1.7 and then I'd imagine a lot has just been a continuation of what it already looks like.

A PR replacing the use of `String` with `Path/File` is welcome.

**Comment by xzel23** [comment]
Ah, I see. So this PR fixes my current problem first. I still face several problems in Spoon that prevent me using it for a gradle plugin that I am developing. I focus on fixing those bugs first, to get the plugin working. Once that is done, I can look into this again.

**Comment by slarse** [comment]
To clarify, I didn't mean "one PR to replace all uses of `String` with `Path`", that would be a huge PR. I just meant that replacing those parts (as long as it's not in the public API) is fair game.

A more clear statement would be "PRs that replace the use of `String` with more appropriate abstractions are welcome"

**Comment by xzel23** [comment]
Ah, OK. Done that.

**Comment by xzel23** [comment]
Wait, I'll also provide a unit test for this.

**Comment by xzel23** [comment]
OK, added a unit test to the PR, made sure it fails without the change and succeeds when the change is applied. Please review the linked PR.
