### ISSUE TITLE
bug in line numbers 

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#431]
line numbers are now wrong, because of a corner case of 4b3aa3a83a2457ffa9d3affc3046c8d9cf2bdcf8

**Comment by GerardPaligot** [comment]
Can you give more info about this issue? Your explanations are vague.

**Comment by monperrus** [comment]
Thomas will keep us updated on this

**Comment by tdurieux** [comment]
This is not a bug. 
However, the specification is not intuitive: getPosition().getLine() currently return the first line of an element. In the case of method, this is the first line of the javadoc.

**Comment by monperrus** [comment]
another more intuitive contract could be: "if the element is a named
element the line number is the line of the name"

**Comment by GerardPaligot** [comment]
All solutions exposed here are hacks. For me, JDT don't make the job. I created an issue on their bugtracker: https://bugs.eclipse.org/bugs/show_bug.cgi?id=483576.

**Comment by monperrus** [comment]
to me, the contract is clearly specified and is intuitive.

to this extent, this is not a hack.

**Comment by GerardPaligot** [comment]
The contract is good, the implementation will be a hack.

**Comment by monperrus** [comment]
I see. We're along the same line.

Since we currently have a regression (the line number was correct
before, incorrect now), I propose to first set up the hack and to remove
it once the bug is fixed upstream in JDT.
