### ISSUE TITLE
[Bug] Spoon removes super class name when printing nested class name resulting in invalid output

### ISSUE THREAD

**Issue by xzel23** [INRIA/spoon#4313]
**Describe the bug**
Spoon sometimes removes the super class name when  printing a nested class name which in some cases leads to incorrect output. In this example, `public class Foo implements Iterable<Foo.Bar<?>>` is changed by Spoon to `public class Foo implements Iterable<Bar<?>>`. Note the missing `Foo.` in the generic argument. While it is sufficient to use `Bar<?>` when *inside* the class declaration of `Foo`, it `Bar`  has to be qualified as `Foo.Bar` when used as the generic parameter to its own super class. 

Note that I use `VirtualFile`in the example code which might fail before #4302 is fixed/#4303 is applied - I actually opened that one  while trying to create this minimal example. ;-) 

I will look into this later and if I find out what's wrong hopefully create a unit test and a patch.

**To Reproduce**

Input:
```java
    package nested_generic_class;
                    
    import java.util.ArrayList;
    import java.util.Iterator;
    import java.util.List;
                    
    public class Foo implements Iterable<Foo.Bar<?>> {
        private final List<Bar<?>> bars = new ArrayList<>();

        public static final class Bar<T> {
        }
                    
        @Override
        public Iterator<Foo.Bar<?>> iterator() {
            return bars.iterator();
        }
                    
    }
```

Processing with Spoon:
```java
        Launcher launcher = new Launcher();
        launcher.addInputResource(new VirtualFile(code));
        launcher.getEnvironment().setComplianceLevel(16);
        launcher.getEnvironment().setAutoImports(true);
        launcher.getEnvironment().setNoClasspath(true);
        launcher.getEnvironment().setPreserveLineNumbers(true);

        launcher.getEnvironment().setOutputType(OutputType.NO_OUTPUT);

        launcher.buildModel();

        CtCompilationUnit cu = launcher.getFactory().Type().get(qualifiedName)
                .getPosition().getCompilationUnit();

        PrettyPrinter autoImportPrettyPrinter = launcher.getEnvironment().createPrettyPrinterAutoImport();
        String output = autoImportPrettyPrinter.prettyprint(cu);
        
        System.out.println(output);
```

Output:
```java
package nested_generic_class;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

public class Foo implements Iterable<Bar<?>> {
    private final List<Bar<?>> bars = new ArrayList<>();

    public static final class Bar<T> {
    }

    @Override
    public Iterator<Bar<?>> iterator() {
        return bars.iterator();
    }

}
```

Note that you can also open a pull request reproducing the issue and reference that, instead of writing additional information here.

**Operating system, JDK and Spoon version used**

* OS: MacOs 12.0.1
* JDK: 17
* Spoon version: current Git (as of Nov 27 2021)

**Comment by slarse** [comment]
Oh, that's bad. In the default printer no less. This is a high-priority bug.

Will you be working on a fix for this?

Just to be very clear on the bug, the problem is that the simple name for `Bar` is used in the header for `Foo`.

```java
public class Foo implements Iterable<Bar<?>> {
```

This won't compile, the name must be qualified as `Foo.Bar`.

Printing the simple name `Bar` only inside the body of `Foo` is not a bug, because `Bar` exists in that namespace.

**Comment by xzel23** [comment]
Yes, I will look into this in the coming week. I have encountered another bug like this, but I currently cannot tell if it's really the same cause.

**Comment by slarse** [comment]
Great, thanks!

**Comment by xzel23** [comment]
This is much harder than I thought. IMHO Spoon is not really maintenance friendly with classes directly accessing and sometimes even modifying other classes members. After spending lots of time debugging, and doing some refactoring to make ContextBuilder a little bit friendlier to debug, I still have not proceeded very much.

I step through the code for hours, and all the time the type is `Iterable<Foo.Bar<?>>` until suddenly `Iterable<Bar<?>>` appears out of nowhere. I then restart the debug session and delve into the last satement I stepped over, and it feels like zooming in on a fractal: same happens again.

I now think the wrong type parameter appears first in a SourceTypeBinding, which lives in the package `org.eclipse.jdt.internal.compiler.lookup`. So I think this might be an ecj bug after all. I looked at the ecj issue tracker and saw some issues concerning generics but nothing obvious.

As I don't have any experience with ecj, can anybody point me to how to have ecj parse the example java file to AST and then write out the java code generated from the AST again?

**Comment by xzel23** [comment]
Finally found something and changed some lines of code that make my test case pass. But I have to look into this further because it makes an unrelated test case fail. I think that test case should be changed as it is based on a wrong assumption, but I need some more time to analyse further. Currently super busy with my day job but should be able to finish this on the next weekend at the latest.

**Comment by slarse** [comment]
There's no rush, take it in your own time. I'm preoccupied with non-coding things outside of work right now, which is why I've been silent here.

**Comment by xzel23** [comment]
I made a PR for this, please review and comment.

**Comment by xzel23** [comment]
PR is merged
