### ISSUE TITLE
[Bug] StandardEnvironment does not work if path contains spaces

### ISSUE THREAD

**Issue by xzel23** [INRIA/spoon#4357]
**Describe the bug**
StandardEnvironment does not work if classpath contains spaces.

**To Reproduce**

check out spoon from git to a location where the path contains a space character and run `mvn compile test`.  test will fail in: 
 - JDTImportBuilderTest because of an issue in StandardEnvironment
 - JavaReflectionTreeBBuilderTest because of incorrectly converting URL to String
 
I think, the correct fix would be to refactor *all* methods taking a String argument for a path or filename should  be refactored to use Path, in a first step by introducing a Path overload and deprecating the String versions.

Input: N/A

Processing with Spoon: N/A

Output: N/A

**Operating system, JDK and Spoon version used**

* OS: MacOS Monterey (12.1)
* JDK: GraalVM CE (JDK 17.0.1)
* Spoon version: current github (2021-12-16)

**Comment by xzel23** [comment]
I submitted a PR for this, please review and comment.

**Comment by algomaster99** [comment]
Hi @xzel23 !

Could you please elaborate what you mean by "check out spoon from git to a location where the path contains a space character and run mvn compile test"? Maven commands can be run only in paths where a `pom.xml` is also present so I am unable to reproduce this issue.

```bash
spoon/directory with spaces$ mvn compile test
The goal you specified requires a project to execute but there is no POM in this directory
```

**Comment by xzel23** [comment]
Yes, of course:
```
mkdir "folder with spaces"
cd "folder with spaces"
git clone ...
mvn compile test
```

**Comment by xzel23** [comment]
IMHO https://github.com/INRIA/spoon/pull/4358 is ready for merging so that this can be closed after the PR is applied.
