### ISSUE TITLE
[Bug] Spoon adds invalid assignments in record compact constructor

### ISSUE THREAD

**Issue by xzel23** [INRIA/spoon#4377]
**Describe the bug**
Spoon adds invalid assignments in compact record constructor. See example code: all assignments are rejected by javac.

**To Reproduce**

Input:
```java
package records;

public record Rectangle(float x, float y, float width, float height) {
    public Rectangle {
        assert width>=0;
        assert height>=0;
    }
}
```

Processing with Spoon: 

I use the following script for quick tests)
```java
#!/usr/bin/env bash
DIR=`dirname $0`
rm -r issue/processed
java -classpath ${DIR}/lib/*.jar spoon.Launcher -i "${DIR}/issue" -o "${DIR}/issue/processed" --compliance 16
```

Output:
```java
package records;
public record Rectangle(float height, float x, float width, float y) {
    public Rectangle {
        assert width >= 0;
        assert height >= 0;
        this.height = height;
        this.width = width;
        this.x = x;
        this.y = y;
    }
}
```

Note that you can also open a pull request reproducing the issue and reference that, instead of writing additional information here.

**Operating system, JDK and Spoon version used**

* OS: MacOS 12.1
* JDK: GraalVM CE 21.3 (JDK 17.0.1)
* Spoon version: current Git

**Comment by xzel23** [comment]
I just could reproduce this with the current CtRecordTest.testCompactConstructor(), so no new test case is needed:

```java
package records;
public record Rational(int num, int denom) {
    private static int gcd(int a, int b) {
        if (b == 0)
            return java.lang.Math.abs(a);
        else
            return records.Rational.gcd(b, a % b);

    }

    public Rational {
        int gcd = records.Rational.gcd(num, denom);
        num /= gcd;
        denom /= gcd;
        this.denom = denom;
        this.num = num;
    }
}
```

That's interesting because `head(head(records).getConstructors()).toString()` yields valid code for the constructor.

**Comment by xzel23** [comment]
This is getting mysterious. The compact constructor is generated correctly as long as the filename does not match the record name. If I leave the input file unchanged, i. e. the filename is `CompactConstructor.java` and the declared rcord is `Rational`, I get this output for the constructor:

```java
public Rational {
    int gcd = records.Rational.gcd(num, denom);
    num /= gcd;
    denom /= gcd;
}
```

But if I change the type name to match the filename (or filename to match the record name), I get this:
```java
public CompactConstructor {
    int gcd = records.CompactConstructor.gcd(num, denom);
    num /= gcd;
    denom /= gcd;
    this.denom = denom;
    this.num = num;
}
```

These results are obtained by evaluating `head(head(records).getConstructors()).toString()` in `CtRecordTest.testCompactConstructor()`, so it's not an issue of the PrettyPrinter as I had first thought.

**Comment by xzel23** [comment]
assignments are added during call to `unit.analyseCode();` in `TreeBuilderCompiler.buildUnits(CompilationUnit[] sourceUnits)`.

**Comment by xzel23** [comment]
Somewhere deep inside the eclipse compiler, `CompactConstructorDeclaration.checkAndGenerateFieldAssignment()` is called. I still have not found out where the filename comes into play, but this looks like an eclipse JDT bug to me.

**Comment by xzel23** [comment]
Can anybody confirm my findings and ideally is somewhat more familiar with spoon and the eclipse jdt than I am so that we could open an eclipse ticket?

**Comment by SirYwell** [comment]
<https://git.eclipse.org/c/jdt/eclipse.jdt.core.git/tree/org.eclipse.jdt.core/compiler/org/eclipse/jdt/internal/compiler/ast/CompactConstructorDeclaration.java#n75> The assignments should be correctly marked as implicit and therefore ignored by the printer.

I wasn't able to reproduce this issue for some reason, but you'll need to look into why the assignments aren't implicit anymore when printing I guess.

**Comment by xzel23** [comment]
@SirYwell Thank you, I will create a test case first and then look into this.

**Comment by xzel23** [comment]
@SirYwell You probably couldn't reproduce the issue because the original file not only had a differing filename, but also an invalid compact constructor declaration: the record `Rational` was declared public, but the compact constructor was package private. This leads to a compile error for the file.

Because of the compilation error, the field `CompilationUnitDeclaration.ignoreFurtherInvestigation` is set to true. It's the same thing that happens, when the file name doesn't match the name of the publicly declared record.

Then, in CompilationUnitDeclaration.analyseCode(), the analysis is simply skipped:
```java
    public void analyseCode() {
        if (!this.ignoreFurtherInvestigation) {
            ...
        }
    }
```

**Comment by xzel23** [comment]
The JDT compiler correctly marked the assignments as implicit, but this information was not propagated to the model. I created PR #4389 that fixes this.

**Comment by xzel23** [comment]
PR is merged.
