### ISSUE TITLE
Join the OpenJDK Quality Outreach Program

### ISSUE THREAD

**Issue by SirYwell** [INRIA/spoon#4395]
The OpenJDK has a program that lists open source software that is tested with current OpenJDK builds. As spoon is actively tested with modern java versions, it might be interesting to get the project added to the list.

See https://wiki.openjdk.java.net/display/quality/Quality+Outreach for more information

**Comment by MartinWitt** [comment]
This mean we should send an email with more or less these content: 

> Project name: 

Spoon
> Project Contact:

@monperrus, @slarse or anyone who wants to be the contact?

> Actively Tested on: JDK version

JDK 11 linux, JDK 11 windows, JDK 17 linux

> Previously tested on and actively using features from JDK version

Tested JDKs: JDK 8, any more I forgot?
Features: I have no clue what the want to be honest

**Comment by monperrus** [comment]
Good idea. @SirYwell would you be contact yourself?

**Comment by SirYwell** [comment]
I can do that too, if you don't want to. I'd also check locally if all tests are running with the Java 18 early access builds too.

**Comment by slarse** [comment]
Hmm, should a non-integrator have to bear that kind of responsibility? You sure you're okay with that, @SirYwell?

If accepting, @SirYwell should at the very least be bumped to issue triage rights. Actually, imo that should be done regardless. Let me find that issue ...

**Comment by SirYwell** [comment]
If someone of the integrators wants to do it, that would be probably better I guess.

However, if none of you wants to do it, I could do it.

**Comment by SirYwell** [comment]
Linking #4931 for context here.

**Comment by MartinWitt** [comment]
I wrote the mail see https://mail.openjdk.org/pipermail/quality-discuss/2022-October/001097.html.

**Comment by MartinWitt** [comment]
Spoon is now officially part of the quality outreach program, see https://wiki.openjdk.org/display/quality/Quality+Outreach

**Comment by monperrus** [comment]
Excellent :fireworks:

**Comment by slarse** [comment]
That's cool, thanks @MartinWitt !
