### ISSUE TITLE
add some javadoc for getType()

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#442]

**Comment by GerardPaligot** [comment]
I don't understand. A `CtTypeAccess` represents an access to a type available by `getType()`.

**Comment by GerardPaligot** [comment]
ping to know what you want here. @monperrus

**Comment by GerardPaligot** [comment]
Well, after discussion with Martin, we will remove `CtTypeAccess` to use directly `CtTypeReference`. I rename the issue.
