### ISSUE TITLE
[Bug] Brackets omitted for arrays of generic types

### ISSUE THREAD

**Issue by seintur** [INRIA/spoon#4421]
Dear all,

The Inria CI for project Juliac bumped into an issue 2 days ago. By figuring out what is going out, the issue can be trimmed down to the following simple case.

**To Reproduce**

Input:
```java
class C { Class<?>[] foo; }
```

Processing with Spoon:
```java
System.out.println( Launcher.parseClass("class C { Class<?>[] foo; }") );
```

Output:
```java
class C {
    Class<?> foo;
}
```

Note that the issue does not arise with array of raw types, e.g. Class[] is correctly pretty-printed.

**Operating system, JDK and Spoon version used**

* OS: macOS
* JDK: 13
* Spoon version: latest from github

**Comment by algomaster99** [comment]
Hi! Thanks for the bug report. I am able to reproduce the issue. I worked on it a few days ago. See https://github.com/INRIA/spoon/pull/4341. I may have missed the case for `parametrizedTypeReference`s. I can work on a fix for this one.
