### ISSUE TITLE
How to declare a generic variable？ 

### ISSUE THREAD

**Issue by coderstory** [INRIA/spoon#4480]
java code
```
public Map<String,String> methodName(){}

```
to create it
```
  CtMethod<String> method = getFactory().createMethod(clazz,new HashSet<ModifierKind>(){{add(ModifierKind.PUBLIC);}}
                    ,reference,"methodName",parameters, new HashSet<>(),ctBlock);
```

Method definition
```
CtMethod createMethod(CtClass<?> target, Set<ModifierKind> modifiers, CtTypeReference returnType, String name, List<CtParameter<?>> parameters, Set<CtTypeReference<? extends Throwable>> thrownTypes, CtBlock body);
```

how to the define the parameter **returnType** 
```
CtTypeReference returnType = ???
```

**Comment by algomaster99** [comment]
Hi @coderstory !

You can use the [TypeFactory](https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/reflect/factory/TypeFactory.java) to create the return type. `factory.Type().MAP` creates a reference to `java.util.Map` and `factory.Type().STRING` creates a reference to `java.lang.String`. For example,

```java
CtTypeReference<Map> returnType = factory.Type().MAP;
returnType.addActualTypeArgument(factory.Type().STRING);
returnType.addActualTypeArgument(factory.Type().STRING);
```
Finally, you can pass the `returnType` as an argument to `createMethod`.
