### ISSUE TITLE
CtClass#addField(CtField) need to add the CtField at the beginning of the class

### ISSUE THREAD

**Issue by sofianekabylino** [INRIA/spoon#455]
The CtClass#addField(CtField), applies to a class, adds a field at the end of the class. The drawback is for the static fields : a static variable cannot use another that is already defined after. A solution is to add this field at the beginning of the class.

**Comment by GerardPaligot** [comment]
Hi @sofianekabylino,

Sorry for the delay of this answer. I'm not sure that is the better solution for this problem but we can propose a new method to specify an index for your new field like: `CtClass#addField(index, field)`.

PR coming soon.
