### ISSUE TITLE
Question about extracting overridden initializer in constructor call

### ISSUE THREAD

**Issue by jiseongg** [INRIA/spoon#4571]
I have a question about parsing a specific kind of code element with Spoon APIs. It's `CtConstructorCall`, whose initializer is directly overridden by call site. (Sorry for ambiguity in describing it, if any. I'm not sure about exact vocabulary)

The code I'm scanning looks like below.
```java
Map map = new HashMap()
{
  {
    put("one", 1);
    put("two", 2);
    put("three", 3);
  }
};
```

I want to extract `CtConstructorCall`s in local variable declarations, which don't have overridden initializer like above. However, I couldn't find the APIs to filter this. (Such as, `hasOverriddenInitializer`). Is there any way to differentiate such pattern with normal constructor calls, e.g. `new HashMap<>();`?

**Comment by SirYwell** [comment]
The initializer block belongs to the anonymous class. In spoon, it is represented by a `CtAnonymousExecutable`.

For example, the following code
```java
    public static void main(String[] args) {
        Launcher launcher = new Launcher();
        launcher.addInputResource(new VirtualFile("""
                class A {
                    public void a() {
                        Map map0 = new HashMap() {};
                        Map map1 = new HashMap() {{
                            put("one", 1);
                            put("two", 2);
                            put("three", 3);
                        }};
                    }
                }
                """));
        launcher.buildModel();
        List<CtLocalVariable<?>> variables = launcher.getModel().getElements(new TypeFilter<>(CtLocalVariable.class));
        for (CtLocalVariable<?> variable : variables) {
            System.out.println(variable.getSimpleName());
            boolean hasInitializerBlock = variable.getElements(new TypeFilter<>(CtAnonymousExecutable.class)).size() > 0;
            System.out.println("hasInitializerBlock = " + hasInitializerBlock);
            System.out.println();
        }
    }
```
will yield the output
```
map0
hasInitializerBlock = false

map1
hasInitializerBlock = true
```

Does that help you?

**Comment by jiseongg** [comment]
Hi @SirYwell,

Thank you for detailed example. It helped a lot! :) Now I can filter out the expression which has initializer block. Similar to what you told me, I've written following code. (I applied filter on `CtConstructorCall`)
```java
boolean hasInitialzierBlock = !constructorCall.getElements(
        new TypeFilter<>(CtAnonymousExecutable.class)).isEmpty();
```

One more thing I wanna ask is, whether there is a way to remove initializer block from the expression. I tried to do it with `setValueByRole` and `CtRole.ANONYMOUS_EXECUTABLE`. (e.g. `.setValurByRole(CtRole.ANONYMOUS_EXECUTABLE, null)`).
So at first, I tried to view initializer block with calling `.getValueByRole(CtRole.ANONYMOUS_EXECUTABLE)` on the elements under `CtConstructorCall` but I couldn't find out where it is.

Converting
```java
new HashMap() { { /* initializer block */ } };
```
to 
```java
new HashMap();
```
, is it possible?

**Comment by SirYwell** [comment]
This is a little bit more tricky I think.

The problem is that your `CtConstructorCall` is actually a `CtNewClass` in this case, as you're declaring a new anonymous class.

If you want to get rid of the anonymous class declaration, you need to replace the `CtNewClass` with a new `CtConstructorCall`. Adding to my previous example (in the for loop, with a check if it has an initializer block):
```java
CtNewClass<?> expression = (CtNewClass<?>) variable.getDefaultExpression();
CtConstructorCall<?> constructorCall = launcher.getFactory().createConstructorCall(expression.getAnonymousClass().getSuperclass());
constructorCall.getType().setImplicit(false);
constructorCall.setArguments(expression.getArguments());
expression.replace(constructorCall);
System.out.println(variable);
```
will print `Map map1 = new HashMap()`.

If you want to remove *only* the initializer block, you can do
```java
CtNewClass<?> expression = (CtNewClass<?>) variable.getDefaultExpression();
expression.getAnonymousClass().setAnonymousExecutables(List.of());
System.out.println(variable);
```
instead.

(in your case, you need to cast your `CtConstructorCall` to a `CtNewClass` to get access the the `getAnonymousClass()`)

**Comment by jiseongg** [comment]
On, I didn't know there was `CtNewClass`. The second one is exactly what I wanted. Thank you :)

**Comment by slarse** [comment]
@jiseongg If @SirYwell answered your question to your satisfaction, could you close this issue? :)

**Comment by jiseongg** [comment]
@slarse I forgot to close it. It helped a lot. :)  I'll close this issue.
