### ISSUE TITLE
How to report vulnerabilities?

### ISSUE THREAD

**Issue by xzel23** [INRIA/spoon#4603]
As the title says: I don't know how to report issues that might impact security? I think it's not advisable to open a publicly visible issue for such things, so how should the maintainers be contacted?

**Comment by monperrus** [comment]
That's important, thanks for reaching out.

> how to report issues that might impact security?

By contacting one of the integrators over email: https://github.com/INRIA/spoon/blob/master/CONTRIBUTING.md

For encrypted channels, I've just added my GPG key id to my Github profile: https://github.com/monperrus

**Comment by slarse** [comment]
I realize that we don't have a security policy setup. I'll add that tonight.

**Comment by monperrus** [comment]
(cross-posting @intrigus-lgtm's suggestion at  https://github.com/INRIA/spoon/pull/4606#issuecomment-1040505859)

FTR, GitHub security advisories are also welcome., reference https://docs.github.com/en/code-security/security-advisories/
