### ISSUE TITLE
Replace the imports statement of java files

### ISSUE THREAD

**Issue by rahulresult1** [INRIA/spoon#4648]
how to change the import statement using spoon framework.

**Comment by algomaster99** [comment]
@MartinWitt I think you have another application for laughing-train here :)

**Comment by MartinWitt** [comment]
> @MartinWitt I think you have another application for laughing-train here :)

Migration of frameworks seems really like a hot topic. Never thought about it tbh. I will add it to my list of possible future features.

@rahulresult1 As the answer more or less dependents on a single question, how do you print the source code after the transformation? SniperPrinting or DefaultJavaPrettyPrinter?
