### ISSUE TITLE
A question regarding how CtTypeReferenceImpl retrieves its type.

### ISSUE THREAD

**Issue by raghav-deepsource** [INRIA/spoon#4668]
I was going through the code of CtTypeReferenceImpl to see how it resolves its type declaration, and I noticed that there is a lock operation going on in the `findClass` method:

https://github.com/INRIA/spoon/blob/17e000b58363dee4ee1687e582f13ef993b387e0/src/main/java/spoon/support/reflect/reference/CtTypeReferenceImpl.java#L163-L169

The `lastClassLoader` and `classByQName` fields are static, but the lock itself is not, meaning there will be a different lock for each type reference created...

https://github.com/INRIA/spoon/blob/17e000b58363dee4ee1687e582f13ef993b387e0/src/main/java/spoon/support/reflect/reference/CtTypeReferenceImpl.java#L56-L59

I feel like this may cause multithreading issues. Was this intended?

**Comment by slarse** [comment]
I agree, that looks like a bug. It was introduced in #4183

Ping @MartinWitt, confirm?

**Comment by MartinWitt** [comment]
I tried to fix the more or less awful global state, but have overseen the threading issue. There are 2 solutions, either make the lock static and ruin more or less every existing multithreading performance, or remove the global state. I can't see any good reason for this global state and looking into the old PR (https://github.com/INRIA/spoon/pull/2591), I don't see any good reason to cache something the class loader is internal caching. I hope no one uses any JVM without caching inside the class loader(I doubt the existence of such a bad class loader implementation). How about removing this caching mechanism?

**Comment by slarse** [comment]
We can try to remove it and see what happens with performance.

**Comment by I-Al-Istannen** [comment]
> see what happens with performance.

@slarse That's an optimistic statement ;) Do you have any example workload that uses `getActualClass` or related methods?

**Comment by slarse** [comment]
I don't have a specific workflow, but it's used absolutely everywhere. Note that `getActualClass` is deprecated in favor of `getTypeDeclaration` (but the latter delegates to the former in the current implementation). Any real-world benchmark should be affected if there's a notable difference in performance. We could build a synthetic benchmark that just builds a model and fetches a lot of types that are available and that are not available a couple of times to see the worst case, that would be very simple to construct.

A simple quick solution here before we do any performance measures is to do thread-local caching. That would fix the bug, at least, and will have minimal impact. I'll give it a go.

**Comment by I-Al-Istannen** [comment]
Ah yea, not everybody has the full JDK in their source path... While indexing paper-api, the `buildModel` call resulted in `13.831` calls to it and my indexer produced `1.823.716` in total. So I guess that method *is* hot.

As an aside: I can reliably get my indexer to deadlock when trying to acquire the lock: The unlock is not in a `finally` block and if a class can not be loaded an exception is thrown, skipping the unlocking.
This only happens with my type adaption PR present which I find highly unpleasant. Maybe it is just fast enough to actually race the same instance from two threads...

A simple reproduction is
```java
	@Test
	void ohNo() throws InterruptedException {
		Factory factory = new Launcher().getFactory();
		CtTypeReference<Object> ref = factory.Type().createReference("ThisClassDoesNotExistDotCom");
		Thread murderer = new Thread(() -> {
			System.out.println("Second thread calling in");
			System.out.println(ref.getTypeDeclaration());
			System.out.println(
				"Second thread permanently locked recursive instance lock. " +
					"No other thread can ever again call getTypeDeclaration"
			);
		});
		murderer.start();
		murderer.join();
		System.out.println("Main thread trying to get declaration...");
		System.out.println(ref.getTypeDeclaration());
		System.out.println("Done");
	}
```
I think your PR fixes that though by eliding locks altogether.

**Comment by slarse** [comment]
Yeah, I thought about the unlocking part, too. I think the docs for `ReentrantLock` actually advises to put it in a finally to avoid badness.

If we could get rid of the cache completely, that'd be great, but in the meantime I think #4668 is a decent enough quick-fix.
