### ISSUE TITLE
[Bug] The scope of variable in switch blocs is not properly parsed

### ISSUE THREAD

**Issue by dhmoclex** [INRIA/spoon#4696]
**Describe the bug**
When a variable is declared within a switch bloc of code, its scope extends to the whole switch bloc, for instance the declaration of a second variable with the same name will raise a compilation error.

**To Reproduce**
1. Parse the following code with spoon ;
2. Check the resulting model.

Input:
```java
public class A {

  public void function(int value) {

    switch (value) {
      case 1:
        String test;
        test = "first";
        break;
      case 2:
      case 3:
      default:
        test = "not first";
    }

  }

}
```

Processing with Spoon:
```java
spoon = new Launcher();
spoon.addInputResource(path);
spoon.getEnvironment().setComplianceLevel(11);
spoon.getModel()
```

Output:
When parsing the model with a custom scanner, the local variable reference of the assignment ```test = "first"``` is properly defined, that is referencing the preceding declaration ```String test```, but the local variable reference of the assignment ```test = "not first"``` is null instead of referencing the declaration ```String test```.

**Operating system, JDK and Spoon version used**

* OS: Windows 10
* JDK: 11
* Spoon version: 10.0.0

**Comment by slarse** [comment]
Hi @dhmoclex,

I can't reproduce the reference itself to be `null`, but attempting to get the declaration of the reference returns `null`. Is this what you meant?

From a quick glance it looks like the code that resolves a reference to its declaration does so by naively walking up the tree, which obviously does not work in the case of switch cases without blocks.

**Comment by dhmoclex** [comment]
> I can't reproduce the reference itself to be null, but attempting to get the declaration of the reference returns null. Is this what you meant?

Yes, the declaration of the reference is null, exactly.

**Comment by slarse** [comment]
This has been resloved now, thanks @dhmoclex for reporting the bug (and @SirYwell for fixing it).
