### ISSUE TITLE
Javadoc parsing and representation in spoon

### ISSUE THREAD

**Issue by I-Al-Istannen** [INRIA/spoon#4717]
## What is this about?
Spoon has a superficial understanding of javadoc elements. We might want to widen support and cover more of the current javadoc specification. Maybe we even want to resolve javadoc references, such as `@link`, directly in spoon.

## Current state
Spoon only supports a small subset of inline tags. Parsing mistakes in the basic support were partially fixed in #4157 and #4165, but there are still many unrepresentable tags in spoon's model.

Some block tags (such as `@see`) and some inline tags (such as `@link`) reference other java elements. These references are not resolved by spoon and instead presented as a string, forcing clients to resolve references manually. This process is quite complex and re-implementing it in your own programs is cumbersome and requires decent knowledge of quite a few internals.
Inline tags in javadoc are often structured in `name argument1 argument2`, which spoon does not expose currently.

Java 18 added javadoc snippets (https://openjdk.java.net/jeps/413) which are not handled at all by spoon currently.

## Wishlist
- Javadoc is represented as a tree structure. Some inline tags (like `@return`) can contain nested tags.
- All inline tags in the current javadoc specification are supported
- Arguments for inline tags are structured (e.g. `{@link String#contains this is a label for the link}` should be split into a reference and a label)
- Block tags contain a structured representation of their contents
- References in `@link` or `@see` and similar are resolved correctly to CtType / CtExecutable / CtField elements
- Rename refactorings adjust javadoc link tags
- javadoc snippets provide a structured and/or rendered view. If javadoc is represented as a tree, the structured form might emerge naturally

## Constraints 
- **Performance** javadoc reference resolving will be quite costly as the standard javadoc doclet is **extremely** lenient when parsing links and references. It sometimes even completely disregards part of the written tag and instead heuristically chooses a *sensible* interpretation. This forces us to do costly lookups.
- **Correctness** A good chunk of existing javadoc is broken in more-or-less subtle ways. We want to implement some heuristics to fix it where possible as the standard doclet does the same.

This probably means we need to fully resolve javadoc references either lazily or as an opt-in toggle when building the model.

## Scope
- We likely do not want to provide facilities to render javadoc to HTML or markdown
- We likely do not want to clean and normalize javadoc (e.g. collapsing `<code>{@pre` or similar constructs)

## Discussion
All of this is up for debate, this is just a rough draft to gather some more opinions.

**Comment by monperrus** [comment]
That's a good direction; wrt performance we can make this optional, behind a configuration parameter.

**Comment by slarse** [comment]
> That's a good direction; wrt performance we can make this optional, behind a configuration parameter.

I think we could possibly make it lazy instead of optional. I.e. we parse the Javadoc only if a method that fetches the Javadoc is used.

IMO Spoon is already too configurable, so I think making optional features lazy instead of locked behind configuration parameters is a more intuitive way to go about it.
