### ISSUE TITLE
Variable lineage from Collector-Sahab

### ISSUE THREAD

**Issue by bhatnagar444** [INRIA/spoon#4724]
@algomaster99 Opening new issue for variable lineage. Please also refer the email where I have provided 3 attachments. 

**Problem :** So Oracle seems to be quite expensive to some of the companies so they convert their databases from oracle to Postgres.
Now after the database is converted, the queries written inside the code might be in oracle JDBC or oracle hibernate so there the need will come to convert the code queries also into respective database queries.
From  oracle JDBC or oracle hibernate queries to Postgres JDBC or Postgres hibernate queries.

**Goal :** We need to make a tool/plugin/java application so that it takes the client's projects/java files as input and remediates the queries.

**My Efforts :** Have researched on some of the below mentioned tools/libraries for the same -
_AWS SCT (Schema Conversion Tool) -_ Which finds the lineage/assignments of the variable and converts static query but not dynamically made query.
_Spoon library -_ Which is helping me to get all the variables and its values defined in a java file (Maybe after that we can make a custom logic for the goal we want to achieve but that would be very difficult).
 _Java eclipse AST (Abstract Syntax Tree) -_ Eclipse plugin which helps to get the tree type structure of the java file but not able to know how to proceed next.
Attaching a sample JDBC code will try to make you understand what is that task. This attached file contains 7-8 possible ways which I could think a developer can make a dynamic SQL query.

Also writing a piece of code consisting of dynamically made query and what needs to be achieved from the same.

*******************************************
```java
package spoon;

import java.sql.*;

public class DynamicCodeForJDBC {
static final String DB_URL = "jdbc:mysql://localhost/TUTORIALSPOINT";
static final String USER = "guest";
static final String PASS = "guest123";

static final String QUERY2 = "FROM Employees";
static final String QUERY3 = "id,first,last";
static final String QUERY1 = "SELECT";


public void execute() {
	StringBuffer sb = new StringBuffer();
	sb.append(QUERY1);
	sb.append(QUERY2);
	sb.append(QUERY3);
	String dynamic_query = sb.toString();
try (Connection conn = DriverManager.getConnection(DB_URL, USER, PASS);
	Statement stmt = conn.createStatement();
	ResultSet rs = stmt.executeQuery(dynamic_query);) {
	while (rs.next()) {
		System.out.print("ID: " + rs.getInt("id"));
		System.out.print(", Age: " + rs.getInt("age"));
		System.out.print(", First: " + rs.getString("first"));
		System.out.println(", Last: " + rs.getString("last"));
	}
} catch (SQLException e) {
	e.printStackTrace();
	}
}
}
```

*******************************************

**Understanding of the above code and our goal -** Now if we will run the above file then the value of "dynamic_query" will be "SELECT id,first,last FROM Employees" but running the above is not what we want instead we will feed/give the above .java extension (not .class) file as an input and we want the output as  "SELECT id,first,last FROM Employees".

**Stepwise understanding**

1. Dynamic_query is passed inside executeQuery method.
2. Dynamic_query is formed by "sb".
3. sb is formed with the StringBuffer append method.
4.  StringBuffer accepts QUERY1,QUERY2 and QUERY3. 

So, in this way we need to find out the lineage of a variable and give "SELECT id,first,last FROM Employees" as the final output.

**NOTE :** Every code and query is subjective to change as per different applications so we need to make a generic tool for the same.

**Comment by I-Al-Istannen** [comment]
## Generic advice to make your posts readable
Could you post code as a markdown **code block**? See [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting=) for how to do this. This makes the code a lot easier to read:

<details>
<summary>A sample code block.</summary>

```java
package spoon;

import java.sql.*;

public class DynamicCodeForJDBC {
    static final String DB_URL = "jdbc:mysql://localhost/TUTORIALSPOINT";
    static final String USER = "guest";
    static final String PASS = "guest123";

    static final String QUERY2 = "FROM Employees";
    static final String QUERY3 = "id,first,last";
    static final String QUERY1 = "SELECT";

    public void execute() {
        StringBuffer sb = new StringBuffer();
        sb.append(QUERY1);
        sb.append(QUERY2);
        sb.append(QUERY3);
        String dynamic_query = sb.toString();
        try (Connection conn = DriverManager.getConnection(DB_URL, USER, PASS);
                Statement stmt = conn.createStatement();
                ResultSet rs = stmt.executeQuery(dynamic_query);) {
            while (rs.next()) {
                System.out.print("ID: " + rs.getInt("id"));
                System.out.print(", Age: " + rs.getInt("age"));
                System.out.print(", First: " + rs.getString("first"));
                System.out.println(", Last: " + rs.getString("last"));
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}
```

</details>

## My understanding of the problem (and some pointers)
If I understood you correctly, you want to find all `executeQuery` invocations and statically figure out their argument values? Then you want to transform that (e.g. by using [JOOQs translate](https://www.jooq.org/translate/)) and write back the adjusted query? Note that at least all the tools I am aware of, including JOOQs, might not produce faithful query translation if your target database does not support given features.

## Why this is not possible in the general case and why it might not matter
With that out of the way, your current focus seems to be *statically* finding the argument values and where they are set. As far as I can see, this problem is theoretically undecidable, I am pretty sure you can reduce it to the halting problem. So any solution you will may find will not *always* work, but maybe your codebase is simple enough, that you can still solve it in practice.  

## How to approach your problem
For this, I'd start with noting down the way queries are constructed, i.e. the patterns your codebase uses. One you show above is a simple string builder with compile-time constants. You can then find these patterns in the source code using spoon, reconstruct the string *as you know how StringBuilder works* and go on with translation and replacement. Once the arguments are read from a non-final instance variable or a local variable with a redefinition based on control flow (e.g. behind an `if`) or even read at runtime from some other place, the problem gets a lot harder and you might not be able to make progress.

## Figuring out where you are at
I believe you have already identified one such pattern: using a string builder. I am not sure where exactly your problem with this lies and what "making a generic tool" means to you. Have you already built a collection of patterns you want to handle? It'd be nice to find out whether you agree with my statements above or my understanding of your problem and position is incomplete or even wrong.

## Alternatives
You could also instrument the code (through spoon) to *save* the argument computed at runtime. This would eliminate all the static guesswork and pattern matching and you can then use the captured value, translate it and just add a dummy static variable or constant and replace the invocation with it. This leaves some dead code around though. Whether this is sufficient for you depends on the patterns you want to handle.

**Comment by bhatnagar444** [comment]
> ### Generic advice to make your posts readable
> Could you post code as a markdown **code block**? See [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting=) for how to do this. This makes the code a lot easier to read:
> 
> A sample code block.
> ### My understanding of the problem (and some pointers)
> If I understood you correctly, you want to find all `executeQuery` invocations and statically figure out their argument values? Then you want to transform that (e.g. by using [JOOQs translate](https://www.jooq.org/translate/)) and write back the adjusted query? Note that at least all the tools I am aware of, including JOOQs, might not produce faithful query translation if your target database does not support given features.
> 
> ### Why this is not possible in the general case and why it might not matter
> With that out of the way, your current focus seems to be _statically_ finding the argument values and where they are set. As far as I can see, this problem is theoretically undecidable, I am pretty sure you can reduce it to the halting problem. So any solution you will may find will not _always_ work, but maybe your codebase is simple enough, that you can still solve it in practice.
> 
> ### How to approach your problem
> For this, I'd start with noting down the way queries are constructed, i.e. the patterns your codebase uses. One you show above is a simple string builder with compile-time constants. You can then find these patterns in the source code using spoon, reconstruct the string _as you know how StringBuilder works_ and go on with translation and replacement. Once the arguments are read from a non-final instance variable or a local variable with a redefinition based on control flow (e.g. behind an `if`) or even read at runtime from some other place, the problem gets a lot harder and you might not be able to make progress.
> 
> ### Figuring out where you are at
> I believe you have already identified one such pattern: using a string builder. I am not sure where exactly your problem with this lies and what "making a generic tool" means to you. Have you already built a collection of patterns you want to handle? It'd be nice to find out whether you agree with my statements above or my understanding of your problem and position is incomplete or even wrong.
> 
> ### Alternatives
> You could also instrument the code (through spoon) to _save_ the argument computed at runtime. This would eliminate all the static guesswork and pattern matching and you can then use the captured value, translate it and just add a dummy static variable or constant and replace the invocation with it. This leaves some dead code around though. Whether this is sufficient for you depends on the patterns you want to handle.

Can you please let me know something about how to instrument the code through spoon. As you said it correctly, I want  to eliminate most of the guesswork in the code and do coding as per that.

**Comment by algomaster99** [comment]
> With that out of the way, your current focus seems to be statically finding the argument values and where they are set. As far as I can see, this problem is theoretically undecidable

I agree that deciding this statically may be hard and you may also not get the correct answer. @I-Al-Istannen has mentioned some solutions like "as you know how StringBuilder works and go on with translation and replacement", but of course, he has also listed a huge caveat in the next sentence.

> You could also instrument the code (through spoon) to save the argument computed at runtime.

I am interested to know about this too.

I suggest you could instead do a _dynamic analysis_ on your files and then record the values of `dynamic_query`, `finalquery`, etc. By dynamic analysis, I mean that you actually execute your program and find the values of variables inside it. We were dealing with a research problem which required us to collect data at runtime, and we have built a tool for that called [Collector Sahab](https://github.com/algomaster99/collector-sahab). Like I said [here](https://github.com/INRIA/spoon/issues/4715#issuecomment-1113168300), it is still in its development stages, but it may be suitable for solving your task.

### What exactly Collector Sahab does?

It does two things as of the time of writing this comment:
1. Collect values of fields and local variables at a give breakpoint
2. Collect return values of provided methods

### How does it achieve this?

![image](https://user-images.githubusercontent.com/35191225/167378226-539c1b8f-0b70-4fc8-91ee-b966acdb4731.png)

The best way to execute your program is to run tests against it, and that is what this tool does.
1. Launches a process which executes **JUnit** tests.
2. Attaches to the process to listen for breakpoint events and method exit events.
3. Whenever the event it comes across, the tool collects the data and finally serialises it into a nice JSON format. See example output in the README.

### How to use Collector Sahab?

Read its [README](https://github.com/algomaster99/collector-sahab#readme).

### How to use the tool specific to your use case?

I will use case 1 from the files you sent me on my email.

1. Create an input file (let's call it `input.json`) like so:
    ```json
    {
        "fileName": "spoon.PossibleDynamicCodesForJDBC",
        "breakpoints": [17]
    }
    ```
2. Find a test in your test suite that you are sure that it runs the provided line number (17) of the provided file (spoon.PossibleDynamicCodesForJDBC). 
3. Execute the collector sahab like so:
   ```bash
   java -jar jar/target/collector-sahab-1.0-SNAPSHOT-jar-with-dependencies.jar \
       -p target/classes target/test-classes target/dependency
       -t  org.TestClass::test_method
       -i input.json
       -o output.json
   ```
4. You should find the data for the variables in the `output.json` file.

> You can deal with all cases like above. I am just not sure if case 8 will work. I have not tested that in my tool yet. Thanks for inspiring me to test one more feature.

**Comment by algomaster99** [comment]
Continuing our conversation on LinkedIn whose summary is as follows:

> @bhatnagar444 does not have access to tests so using collector-sahab is out of scope. Hence, static analysis is the only way out.

Focus on @I-Al-Istannen 's comment:
> For this, I'd start with noting down the way queries are constructed, i.e. the patterns your codebase uses. One you show above is a simple string builder with compile-time constants. You can then find these patterns in the source code using spoon, reconstruct the string as you know how StringBuilder works and go on with translation and replacement.

What he is trying to suggest is that if you have something like this:
```
sb.append(Constants.QUERY1);
sb.append(Constants.QUERY2);
sb.append(Constants.QUERY3);
String dynamic_query = sb.toString();
```
You could look for an instance of string builder and see where all `sb.append` has been called. You can use Spoon APIs to do so. 

More the cases you have, more pattern you need to come up with and that is what @I-Al-Istannen is saying here.
> I believe you have already identified one such pattern: using a string builder. I am not sure where exactly your problem with this lies and what "making a generic tool" means to you. Have you already built a collection of patterns you want to handle?

**Comment by algomaster99** [comment]
For the record, these are some of the cases @bhatnagar444 has outlined:
```
//**************************************************************************************************************//
//Possible case - 1 (Taking query parts from Constant.java or properties file) - AWS SCT FAILED

//package spoon;
//
//import java.sql.*;
//
//public class PossibleDynamicCodesForJDBC {
//
//	public void execute() {
//
//		StringBuffer sb = new StringBuffer();

//		sb.append(Constants.QUERY1);
//		sb.append(Constants.QUERY2);
//		sb.append(Constants.QUERY3);
//		String dynamic_query = sb.toString();
//		try (Connection conn = DriverManager.getConnection(Constants.DB_URL, Constants.USER, Constants.PASS);
//				Statement stmt = conn.createStatement();
//				ResultSet rs = stmt.executeQuery(dynamic_query);) {
//			while (rs.next()) {
//				System.out.print("ID: " + rs.getInt("id"));
//				System.out.print(", Age: " + rs.getInt("age"));
//				System.out.print(", First: " + rs.getString("first"));
//				System.out.println(", Last: " + rs.getString("last"));
//			}
//		} catch (SQLException e) {
//			e.printStackTrace();
//		}
//	}
//}

//**************************************************************************************************************//

//Possible case - 2 and 3 (Directly from the same file using String buffer or builder) - AWS SCT FAILED

//package spoon;
//
//import java.sql.*;
//
//public class PossibleDynamicCodesForJDBC {
//	static final String DB_URL = "jdbc:mysql://localhost/TUTORIALSPOINT";
//	static final String USER = "guest";
//	static final String PASS = "guest123";
//
//	static final String QUERY2 = "FROM Employees";
//	static final String QUERY3 = "id,first,last";
//	static final String QUERY1 = "SELECT";
//	
//
//	public void execute() {
//		StringBuffer sb = new StringBuffer();
//		StringBuilder sb=new StringBuilder();
//		sb.append(QUERY1);
//		sb.append(QUERY2);
//		sb.append(QUERY3);
//		String dynamic_query = sb.toString();
//		try (Connection conn = DriverManager.getConnection(DB_URL, USER, PASS);
//				Statement stmt = conn.createStatement();
//				ResultSet rs = stmt.executeQuery(dynamic_query);) {
//			while (rs.next()) {
//				System.out.print("ID: " + rs.getInt("id"));
//				System.out.print(", Age: " + rs.getInt("age"));
//				System.out.print(", First: " + rs.getString("first"));
//				System.out.println(", Last: " + rs.getString("last"));
//			}
//		} catch (SQLException e) {
//			e.printStackTrace();
//		}
//	}
//}

//**************************************************************************************************************//

//Possible case - 4 and 5 (String concatenation using "+" or using concat method) - AWS SCT FAILED

//package spoon;
//
//import java.sql.*;
//
//public class PossibleDynamicCodesForJDBC {
//	static final String DB_URL = "jdbc:mysql://localhost/TUTORIALSPOINT";
//	static final String USER = "guest";
//	static final String PASS = "guest123";
//
//	static final String QUERY2 = "FROM Employees";
//	static final String QUERY3 = "id,first,last";
//	static final String QUERY1 = "SELECT";
//
//	public void execute() {
//		String finalquery = "";
//		finalquery = QUERY1 + QUERY2 + QUERY3;
//		finalquery = QUERY1.concat(QUERY2).concat(QUERY3);
//		try (Connection conn = DriverManager.getConnection(DB_URL, USER, PASS);
//				Statement stmt = conn.createStatement();
//				ResultSet rs = stmt.executeQuery(finalquery);) {
//			while (rs.next()) {
//				System.out.print("ID: " + rs.getInt("id"));
//				System.out.print(", Age: " + rs.getInt("age"));
//				System.out.print(", First: " + rs.getString("first"));
//				System.out.println(", Last: " + rs.getString("last"));
//			}
//		} catch (SQLException e) {
//			e.printStackTrace();
//		}
//	}
//}

//**************************************************************************************************************//

//Possible case - 6 and 7(Statically written query)

//package spoon;
//
//import java.sql.*;
//
//public class PossibleDynamicCodesForJDBC {
//	static final String DB_URL = "jdbc:mysql://localhost/TUTORIALSPOINT";
//	static final String USER = "guest";
//	static final String PASS = "guest123";
//	static final String STATIC_QUERY = "SELECT id,first,last FROM Employees";
//
//	public void execute() {
//		try (Connection conn = DriverManager.getConnection(DB_URL, USER, PASS);
//				Statement stmt = conn.createStatement();
//				Any one rs from below.
//				ResultSet rs = stmt.executeQuery(STATIC_QUERY); - AWS SCT SUCCESS
//				ResultSet rs = stmt.executeQuery("SELECT id,first,last FROM Employees"); - AWS SCT SUCCESS
//				) {
//			while (rs.next()) {
//				System.out.print("ID: " + rs.getInt("id"));
//				System.out.print(", Age: " + rs.getInt("age"));
//				System.out.print(", First: " + rs.getString("first"));
//				System.out.println(", Last: " + rs.getString("last"));
//			}
//		} catch (SQLException e) {
//			e.printStackTrace();
//		}
//	}
//}

//**************************************************************************************************************//

//Possible case - 8 (Statically written query in Constants file)

//package spoon;
//
//import java.sql.*;
//
//public class PossibleDynamicCodesForJDBC {
//	static final String DB_URL = "jdbc:mysql://localhost/TUTORIALSPOINT";
//	static final String USER = "guest";
//	static final String PASS = "guest123";
//	static final String STATIC_QUERY = "SELECT id,first,last FROM Employees";
//
//	public void execute() {
//		try (Connection conn = DriverManager.getConnection(DB_URL, USER, PASS);
//				Statement stmt = conn.createStatement();
//				Any one rs from below.
//				ResultSet rs = stmt.executeQuery(Constants.QUERY); - AWS SCT FAILED
//				) {
//			while (rs.next()) {
//				System.out.print("ID: " + rs.getInt("id"));
//				System.out.print(", Age: " + rs.getInt("age"));
//				System.out.print(", First: " + rs.getString("first"));
//				System.out.println(", Last: " + rs.getString("last"));
//			}
//		} catch (SQLException e) {
//			e.printStackTrace();
//		}
//	}
//}
```

**Comment by algomaster99** [comment]
@bhatnagar444 Trying fiddling around a bit after referring to https://spoon.gforge.inria.fr/pattern.html. The more precise questions you ask, the more precise answers you get. :)

**Comment by algomaster99** [comment]
@bhatnagar444 is your issue resolved?

**Comment by bhatnagar444** [comment]
Hi
Yes this one is resolved.
Vardhaman from my team is in chat with you for another issue

we can close this one
Thanx
