### ISSUE TITLE
[Bug] Parsing method invocations from method body

### ISSUE THREAD

**Issue by castuardo** [INRIA/spoon#4732]
Hello Guys,

I have a simple question. I am trying to parse all the method invocations given the body of a method for which I am using a CtScanner and overriding visitCtInvocation. For a method like:

int A () {
  B();
  C();
}

seems to work fine, since it visits both calls to B and C. But in a case like:

int A () {
  Object x = new SomeObject(  B(), C() );
  Object y = new OtherThing(  otherMethod ( D(), E() )  );
}

my scanner is not visiting the method calls inside the constructor nor the method calls that are parameters of other method calls. What causes this, and more importantly, is there a way to visit ALL method calls given a method body regardless of if they are located inside a constructor or are arguments to a  method being called?

**Comment by SirYwell** [comment]
Hi, could you please elaborate on both the code you're scanning and the the code you wrote to scan it? Also, make sure that the sources containing the called methods are on the classpath aswell (if `otherMethod` is visited but `D` and `E` aren't, that's most likely the cause).

**Comment by slarse** [comment]
As your actual scanning code isn't shared I can really only guess. It might be a bug in the version of Spoon you are using, which is rather old. I would absolutely recommend updating to a more recent version of Spoon as you are two major versions behind.

The only way I can reproduce the behavior you describe with the latest version of spoon is to not recurse in `visitCtInvocation` by omitting a call to the super class' method. I'll provide an example.

Given this source:

```java
class Test {
    int A () {
        Object x = new SomeObject( B(), C() );
        Object y = new OtherThing( otherMethod ( D(), E() ) );
    }
}
```

And this scanning code (imports omitted):

```java
public class Main {
    public static void main(String[] args) {
        var launcher = new Launcher();
        launcher.addInputResource("Test.java");
        CtModel model = launcher.buildModel();

        new MethodInvocationScanner().scan(model.getRootPackage());
    }

    private static class MethodInvocationScanner extends CtScanner {
        @Override
        public <T> void visitCtInvocation(CtInvocation<T> invocation) {
            System.out.println(invocation);
            super.visitCtInvocation(invocation);
        }
    }
}
```

I get the following output:

```
super()
B()
C()
otherMethod(D(), E())
D()
E()
```

FYI the `super()` call in the output is from inside of the implicitly created constructor.

If I remove the call to `super.visitCtInvocation(invocation);`, I instead get this output:

```
super()
B()
C()
otherMethod(D(), E())
```

I.e. no recursion into the `otherMethod()` invocation containing the invocations to `D()` and `E()`. So that's my best guess as to what the problem is.

**Comment by castuardo** [comment]
Ah, thats very interesting, and I think that clarifies my issue, as your approach works in my code and now I can see the calls. 

Just curiosity here, is this the way Scanners should be built, by considering that the last method call in a visit* method should be a call to the super variant of the method? (Because if so, it was not very clear to me and I apologize).  For example, other possible nested structures could include loops. I havent tested to see if visitCtLoop (its specific variants for every type of loop)  will also suffer from the same issue, but i think ill take a look.

Thx again!!!

**Comment by slarse** [comment]
No need to apologize for anything, your question was entirely understandable. I agree that it's not particularly obvious how this all works.

Technically you don't have to call `CtScanner`'s implementation of any given `visit` method, but if you don't you have to know exactly what you're looking for in terms of child nodes you probably should. The whole `CtScanner` functionality relies on inheritance, so you get these rather obscure and implicit behaviors.

I happen to know that the only child node in an invocation that might contain another invocation is the argument list, so we could change the scanning code like so:

```java
public class Main {
    private static class MethodInvocationScanner extends CtScanner {
        @Override
        public <T> void visitCtInvocation(CtInvocation<T> invocation) {
            System.out.println(invocation);
            scan(CtRole.ARGUMENT, invocation.getArguments());
        }
    }
}
```


But yeah, just calling `CtScanner`'s implementation of any visit method is the easiest way to traverse further down the tree as it call `scan()` on all of the child nodes. if you have a look inside of the `CtScanner` code it will make more sense, and perhaps run the debugger and follow the code execution to get some deeper understanding.

Also, you don't need to make the recursive call to `scan()` at the end of the method, you can do it at the beginning too. This just determines the order of traversal.

@monperrus I looked in the docs and it doesn't appear as if this behavior from extending `CtScanner` is documented at all. Am I looking in the wrong place or have we simply forgotten about it?

**Comment by slarse** [comment]
Closing as the question has been addressed.
