### ISSUE TITLE
Creates CtEnumValue and its access.

### ISSUE THREAD

**Issue by tdurieux** [INRIA/spoon#474]
The values of enums are listed with the fields, this is completely counterintuitive because an enum value does not have: type, visibility and default expression.

The only solution to differentiate classic fields and enum values is to check that the type is null.

**Comment by monperrus** [comment]
another solution is to check that the parent is a CtEnum?

**Comment by tdurieux** [comment]
an enum can have classic field and value such as:
```java
enum {
  VAL;

 private int i = 0;
}
```

**Comment by monperrus** [comment]
What's your use case?

To get/process all enum values? Or to process all fields but enum values?

**Comment by GerardPaligot** [comment]
If you want process all fields of an enumeration but only state field, you need to make this:

```java
class MyProcessor extends AbstractProcessor<CtEnum> {
  public isToBeProcess(CtEnum candidate) {
  }
}
```

**Comment by GerardPaligot** [comment]
If you want process all fields of an enumeration but only state fields, you need to make this:

```java
class MyProcessor extends AbstractProcessor<CtField> {
  public isToBeProcess(CtField candidate) {
    return candidate.getType() == null; // If true, the field is a state field of an enum.
  }
}
```
