### ISSUE TITLE
how to get the CtElement of  specific line in Java source code?

### ISSUE THREAD

**Issue by zqudm** [INRIA/spoon#4742]
```java
  class ScannerByLine extends CtScanner {

    List<CtElement> _node = new ArrayList<CtElement>();

    int _line;

    public ScannerByLine(int line) {
      _line = line;
    }

    public List<CtElement> getResult() {
      return _node;

    }

    private boolean isChildren(CtElement e, int loc) {
      try {
        if (e.getParent().getPosition().isValidPosition() == true && e.getParent().getPosition().getLine() == loc) {
          return true;
        }

      } catch (Exception ex) {

        return false;
      }

      return false;
    }

    protected void enter(CtElement e) {
      if (e.getPosition().isValidPosition()) {
        int current_Line = e.getPosition().getLine();
        if (current_Line == this._line && isChildren(e, this._line) == false) {
          _node.add(e);
        }
      }
    }
  }
```
//////////////////////////////////////////////////////////////////////////////////
I used the scanner defined above to find the CtElement of specific line,  some CtElements can not be found.

**Comment by MartinWitt** [comment]
Hello and Welcome to the Spoon Project, if you're going to share code snippets, consider using github markdown to make them more readable. I've added these to your post.

**Comment by I-Al-Istannen** [comment]
Can you also post a small example input which is not processed correctly? And explain what elements you think are missing?

**Comment by zqudm** [comment]
///  the following Class is a scanner, which aim  to  get the CtElement of specific line number. What is more, i want to get the root  
of CtElement and neglect its children. 

class ScannerByLineCode extends CtScanner {
 List<CtElement> _node=new ArrayList<CtElement>();
 int _line;
 public ScannerByLineCode(int line){
           _line =line;
       }
 public List<CtElement> getResult()
 {
    return _node;
 }
 private boolean isChildren(CtElement e,int loc)
 {           try{
                 if (e.getParent().getPosition().isValidPosition()==true && e.getParent().getPosition().getLine()==loc)
                      return true;
               }catch(Exception ex){
               return false;
               }
             return false;
 }
 protected void enter(CtElement e){
             if (e.getPosition().isValidPosition()) {
              int current_Line=  e.getPosition().getLine();
              if(current_Line==this._line && isChildren(e,this._line)==false)
             _node.add(e);
                  }
             }
 }
//  the following code is the main class  
package com.xy.infrastructure;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Collection;
import java.util.List;
import java.util.Scanner;
import spoon.reflect.declaration.CtType;
import spoon.reflect.declaration.CtExecutable;
import spoon.Launcher;
import spoon.reflect.visitor.filter.TypeFilter;
import spoon.reflect.visitor.filter.NamedElementFilter;
import spoon.reflect.declaration.CtPackage;
import spoon.reflect.declaration.CtMethod;
import spoon.reflect.factory.Factory;
import spoon.reflect.visitor.DefaultJavaPrettyPrinter;
import spoon.reflect.visitor.CtScanner;
import spoon.reflect.declaration.CtElement;
import spoon.reflect.declaration.CtClass;
import spoon.reflect.code.CtInvocation;
import spoon.reflect.reference.CtExecutableReference;
import spoon.reflect.visitor.filter.LineFilter;
import spoon.reflect.code.CtStatement;
import com.xy.util.JavaFile;
public class AppManager {
        public static void main(String[] args) throws Exception {
                String javaFile="./src/test/java/Example.java";
                Launcher launcher = new Launcher();
                launcher.addInputResource(javaFile);
                launcher.getEnvironment().setAutoImports(true);
                launcher.getEnvironment().setNoClasspath(true);
                launcher.buildModel();
                ScannerByLineCode scan = new ScannerByLineCode(6);
                launcher.getFactory().getModel().getRootPackage().accept(scan);

                 List<CtElement> lstElement= scan.getResult();

                 for ( int i=0;i<lstElement.size();i++)
                 System.out.println("---" + lstElement.get(i).toString());
                 System.out.println(lstElement.size());
        }
}

//   the  java file to be analyzed is shown as follows and line numbers in code is also displayed.

1 public class Example {
2        public static void main(String args[]){
3               // declare an int array
4                int[] intArr;
5                // initialize an int array
6               intArr = new int[5];
7               // assign some values
8               intArr[0] = 100;
9               intArr[1] = 200;
10               intArr[2] = 300;
11                for(int i=0;i<5;i++)
12                       System.out.println("at index "+i+" :"+intArr[i]);
13        }
14    }

The following is the output of the example, 

---// initialize an int array       
intArr = new int[5]
---int 
2   // the scanner returns two CtElement, however, one CtElement is expected.    Specifically, only intArr=new int[5]; is the expected CtElement we want as that the line number is set to 6.   

So how to understand the output?

What is more,  if i change  the value of  line number   to  13.  The output is the following.

0    // output 

In other word, no CtElement is found. But,  at  line  13 , there is a special symbol "}".

**Comment by MartinWitt** [comment]
Hi, 
> The following is the output of the example,

What is the result of the first query? It's a bit tough to read your post. Markdown makes it much easier to understand code and text in lengthy comments and problems. Please see https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax/basic-writing-and-formatting-syntax for further information.

> What is more, if i change the value of line number to 13. The output is the following.

Only relevant java elements are included in Spoon's AST. AST elements are not brackets, whitespaces, or newlines. If you wish to look at all of the accessible elements, there is an overview of the metamodel on the spoon webpage.

**Comment by zqudm** [comment]
`1 public class Example {
  2         public static void main(String args[]){
  3                 int[] intArr;
  4                 intArr = new int[5];
  5                 if(intArr ==null)
  6                         System.out.println("hello");
  7                  else   
  8                         System.out.println("world");
  9                         
 10                 intArr[0] = 100;
 11                 intArr[1] = 200;
 12                 intArr[2] = 300;
 13                 for(int i=0;i<5;i++)
 14                         System.out.println("at index "+i+" :"+intArr[i]);
 15         }               
 16 }
`

Given the example code above,  when the line number 7 is given, how to write Filter or CtScanner to find the "else"  CtElement with Spoon?   I have tried them , but nothing return.
Thanks.

**Comment by I-Al-Istannen** [comment]
You can't. Spoon builds an AST and not a CST, losing some information about where superfluous elements were in the source file. The "else" keyword has no semantic meaning besides starting a new block and is therefore not explicitly modeled in the AST. There is no `CtElse` AST element. The closest AST element you will get is the `if` itself (or its `else` branch, though that might start in the next line as nothing of relevance is in line 7).
