### ISSUE TITLE
[Bug] Bug description

### ISSUE THREAD

**Issue by khwbilal** [INRIA/spoon#4745]
**Describe the bug**
I cannot build the project from the source 

**To Reproduce**
using JDK 11

Output:
[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   MavenLauncherTest.testSystemDependency:149 expected: <1> but was: <0>
[ERROR] Errors:
[ERROR]   FluentLauncherTest.testMavenLauncher:98 » Spoon Maven invocation failed to build a classpath.
[ERROR]   MavenLauncherTest.mavenLauncherTestMultiModulesAndVariables:198 » Spoon Maven invocation failed to build a classpath.
[ERROR]   MavenLauncherTest.mavenLauncherTestWithVerySimpleProject:185 » Spoon Maven invocation failed to build a classpath.
[ERROR]   MavenLauncherTest.multiModulesProjectTest:125 » Spoon Maven invocation failed to build a classpath.
[ERROR]   MavenLauncherTest.spoonMavenLauncherTest:73 » Spoon Maven invocation failed to build a classpath.
[ERROR]   MavenLauncherTest.testForceRefresh:164 » Spoon Maven invocation failed to build a classpath.
[ERROR]   MavenLauncherTest.testPomSourceDirectory:191 » Spoon Maven invocation failed to build a classpath.
[ERROR]   MavenLauncherTest.testRebuildClasspath:179 » Spoon Maven invocation failed to build a classpath.
[ERROR]   LogTest.testMavenLauncherLogs:81 » Spoon Maven invocation failed to build a classpath.
[INFO]
[ERROR] Tests run: 2174, Failures: 1, Errors: 9, Skipped: 13
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  09:23 min
[INFO] Finished at: 2022-06-11T13:03:46+05:00
[INFO] ------------------------------------------------------------------------
[INFO] 7 goals, 7 executed
[INFO]
[INFO] Publishing build scan...
[INFO] https://gradle.com/s/zohrrge6kkqhk
[INFO]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M6:test (default-test) on project spoon-core: There are test failures.
[ERROR]
[ERROR] Please refer to D:\Projects\spoon-master\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

* OS: Windows 10
* JDK: 11
* Spoon version: master

**Comment by MartinWitt** [comment]
Hi,

I will have a look. Meanwhile, you may build spoon without executing the test cases by using'mvn install -DskipTests'. Is maven included in your Windows path?

**Comment by MartinWitt** [comment]
The more I think about it, it seems like simply maven is missing. The tests run fine in my setup.

**Comment by MartinWitt** [comment]
Closing this issue because stale. Please have no hesitation to reopen it.
