### ISSUE TITLE
implicit this access

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#476]
(follow up of http://lists.gforge.inria.fr/pipermail/spoon-discuss/2016-January/001843.html)

current behavior: when this is implicit getTarget() returns null.

following the work on CtTypeAccess for static fields and methods, we can add a contract
''getTarget() never returns null'' and "getTarget() returns a CtThisAccess when this is implicit."

**Comment by GerardPaligot** [comment]
I don't know yet for invocations but for fields, it is already specified here: https://github.com/INRIA/spoon/blob/master/src/test/java/spoon/test/targeted/TargetedExpressionTest.java#L78

**Comment by monperrus** [comment]
We would then change the assert there.
