### ISSUE TITLE
Stop a processor in run time

### ISSUE THREAD

**Issue by abdelrhamaneben** [INRIA/spoon#478]
it would be interesting to be able to stop a processor at any time during its execution

**Comment by GerardPaligot** [comment]
Hi @abdelrhamaneben,

That could be interesting but, to do this, we need to implement transactional transformations first (in the [roadmap](https://github.com/INRIA/spoon/blob/master/ROADMAP.md)) to rollback the AST at the state before application of the processor.

Maybe can you tell us how do you plan to stop the processing of a processor given?

**Comment by abdelrhamaneben** [comment]
I spoke with @monperrus, I think it would be a good idea to create a new exception (StopExecutionException) and catch it to the spoon runner.

**Comment by GerardPaligot** [comment]
Without any rollback in the AST?

**Comment by monperrus** [comment]
> Without any rollback in the AST?
>
Without. It would be a way to interrupt processing when you're done (for
instance once you found the element you're interested in). This is both
an optimization (goes faster) and a feature (client code does not have
to maintain a boolean AmIDone).

**Comment by GerardPaligot** [comment]
I don't see the interest on this feature when it is so easy to do it by his own means. You can maintain a boolean or throw an exception to interrupt the processor.

**Comment by monperrus** [comment]
> when it is so easy to do it by his own means. 
No you can't
> You can maintain a boolean 
Doing so you continue to traverse the tree and you loose time
> or throw an exception to interrupt the processor.
Doing so breaks the Launcher. The try-cactch (ProcessInterrupt e) has to
be inside the processing engine.

**Comment by monperrus** [comment]
Re-opening this issue following the comment of @tdurieux 

> If ProcessInterrupt is thrown in processingDone the method processingDone will be called two times. 

if interrupt supported in `istobeprocessed` and`processingDone`?

If yes you can close the issue again

**Comment by GerardPaligot** [comment]
How you can see [here](https://github.com/INRIA/spoon/pull/485/files), I change my code to avoid to call two times `processingDone`.
