### ISSUE TITLE
[Discussion] Add IntelliJ files for inspections and code style to the project

### ISSUE THREAD

**Issue by SirYwell** [INRIA/spoon#4788]
IntelliJ locally stores information about the used inspection profile and code style in the `.idea` folder. This folder is currently ignored, means every contributor has to configure their IDE accordingly. In pull requests from new contributors, we therefore often see things like wildcard imports (that's probably the most annoying issue, and it takes time for everyone involved to fix it). 
Besides code style, the inspection profile is also picked up by Qodana, means we have consistent inspections for both the IDE and the CI if we add those files to git.

**Alternatives**

There are other common code style formats like [editorconfig](https://editorconfig.org/) or [CheckStyle](https://checkstyle.sourceforge.io/).
Those can also be imported in IntelliJ and are supported by other IDEs aswell, however I don't know if Qodana can deal with them correctly. Using CheckStyle would have the advantage that we already use it, but it's less powerful.

**Comment by slarse** [comment]
IMO it's about time we add some automatic formatting that can be enforced in the build. It would just ease the burden of reviews by _a lot_ to have code style be a non-issue. The slight issue is that you get a "nuke commit" on the first run of the automatic formatter, but both Git and GitHub have support for [ignoring such commits when using `git-blame`](https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view), so I think it's kind of a non-issue nowadays.

I've had a really good experience using [spotless](https://github.com/diffplug/spotless) together with [google-java-format](https://github.com/google/google-java-format). You can both format the source code and check that it is properly formatted. Very convenient.

I dislike relying placing any kind of explicit dependency on a particular IDE. I much prefer standalone solutions for stuff like this.
