### ISSUE TITLE
CompilationUnit prevents Serialization

### ISSUE THREAD

**Issue by fanlong** [INRIA/spoon#480]
CompilationUnitImpl is not Serializable but there are non transient reference to it in MetaModel. This prevents the sterilization of MetaModel objects which are declared as Serializable.

**Comment by monperrus** [comment]
could you write a failing test case?

**Comment by fanlong** [comment]
I have sent a pull requests which include a test case and my own fix for the stable branch. Please check and merge to the master branch if you see fit.
