### ISSUE TITLE
How to pass environment Variables to MavenLauncher

### ISSUE THREAD

**Issue by AryanMansani** [INRIA/spoon#4817]
I have a project, where I am fetching code from a rep and then building a CtModel from it that repo.

Now in some project there are some environment variables in dependencies like - 

```
<dependency>
<groupID>common-annotation</groupID>
<artifactID>common-annotation</artifactID>
<version>${revision}<version>
</dependency>
```

Here, revision is that variable, now when building a model, spoon gives an error.

Is there a way I can pass this variable to Maven Launcher or any other work around.

**Comment by I-Al-Istannen** [comment]
Probably not the best solution, but if they are present as environment variables, the spawned `mvn` process will inherit them. This means that `revision=foo java YourProgram` should work.

Setting that from inside your program is not really portable though. The maven launcher would need to expose an interface and use the `addShellEnvironment` method to pass that along to the invocation request.

**Comment by I-Al-Istannen** [comment]
Ah, I just thought of another slightly more realistic workaround:
You could edit the pom to add them to the `properties` section. Either using an XML library or some well-placed regular expressions :)

**Comment by AryanMansani** [comment]
That's a really good idea, but for it, we need to beforehand identify either manually or by XML parser if this variable is not present in the properties, so for a single module it sounds okay but for a multi-modular project it sounds like a lot of work, is there a way we can automatically identify which variables are not present using any library?

**Comment by I-Al-Istannen** [comment]
You need to know which environment variables need to be set in any case. I guess we could also add that to the MavenLauncher API, setting environment variables sounds useful enough.

See #4830.

**Comment by I-Al-Istannen** [comment]
The new API you want to look at is `setEnvironmentVariable` in the `MavenLauncher`. Do let us know if this does not solve your issue @AryanMansani :)
