### ISSUE TITLE
[doc bug]: how to determine two methods are equal (all upto sigature) in the sense of what javac believe?

### ISSUE THREAD

**Issue by mw66** [INRIA/spoon#4821]
I saw this:

https://spoon.gforge.inria.fr/mvnsites/spoon-core/apidocs/spoon/reflect/declaration/CtExecutable.html#getSignature()

it returns a string, can I compare the returned string to determine if two methods are equal (all upto sigature) in the sense of what javac believe?

BTW, according to the doc:
"""
 The signature is composed of the method name and the parameter types, all fully-qualified, eg "int foo(java.lang.String)".
"""

But I tried some simple code, the method's return type is not part of the returned string, e.g.:

```
equals(java.lang.Object)
```

Is this a bug?

**Comment by I-Al-Istannen** [comment]
> Is this a bug?

In the documentation probably. The return type is not part of the signature (see https://docs.oracle.com/javase/specs/jls/se18/html/jls-8.html#jls-8.4.2). If you read a bit further in the documentation than the first sentence, it explains this as well though:
```java
	/**
	 * Gets the signature of this method or constructor.
	 * The signature is composed of the method name and the parameter types, all fully-qualified, eg "int foo(java.lang.String)".
	 * The core contract is that in a type, there cannot be two methods with the same signature.
	 *
	 * Note that the concept of method signature in Java is not well defined (see chapter "8.4.2 Method Signature" of the Java specification, which defines what relations between signatures but not what a signature is exactly).
	 *
	 * Note also that the signature of a method reference is the same as the signature of the corresponding method if and only if the method parameters does not involve generics in their types. Otherwise, one has eg m(String) (reference) and m(T) (declaration)
	 *
	 * Reference: "In the Java programming language, a method signature is the method name and the number and type of its parameters. Return types and thrown exceptions are not considered to be a part of the method signature."
	 * see https://stackoverflow.com/questions/16149285/does-a-methods-signature-in-java-include-its-return-type
	 * see https://en.wikipedia.org/wiki/Type_signature
	 */
	String getSignature();
```

I am not sure what your goal is, so maybe the method will work for you.

**Comment by mw66** [comment]
ok, together with `getType()`, I can live with it.
