### ISSUE TITLE
[Bug]: reverse order for classes in source file that declares multiple classes 

### ISSUE THREAD

**Issue by joelmo** [INRIA/spoon#4827]
### Describe the bug

The order of AST nodes does not seem right when a class declares multiple classes. I tried to correct the order in my CtScanner but was not able to do it.

I tried all combinations and enabled/disabled these methods:
```java
    @Override
    public void visitCtCompilationUnit(CtCompilationUnit compilationUnit) {
        var declared = compilationUnit.getDeclaredTypes();
        Collections.reverse(declared);
        compilationUnit.setDeclaredTypes(declared);
        super.visitCtCompilationUnit(compilationUnit);
    }
    @Override
    public void visitCtPackage(CtPackage ctPackage) {
        var declared = ctPackage.getTypes().stream().toList();
        Collections.reverse(declared);
        ctPackage.setTypes(new HashSet<>(declared));
        super.visitCtPackage(ctPackage);
    }
```

### Source code you are trying to analyze/transform

```Java
// Main.java
class Main { }
class Shape { }
class Rectangle extends Shape { }
```

### Actual output

```Java
// AST:
RootPackage
  Rectangle
  Shape
  Main
```

### Expected output

```Java
// AST:
RootPackage
  Main
  Shape
  Rectangle
```

### Spoon Version

10.1.0

### JVM Version

11

### What operating system are you using?

Windows

**Comment by algomaster99** [comment]
@joelmo Hi! The order of types in a package is not relevant for an AST, so we do not maintain it. See [`CtPackage#getTypes`](https://github.com/INRIA/spoon/blob/faebd19cd5f90988ac3afe7a08111948cd5e8aa0/src/main/java/spoon/reflect/declaration/CtPackage.java#L96) API.

Moreover, a package can have multiple Java files, and each file will have at least one `CtType`, so defining an order for all the types in a package does not make sense.

**Comment by joelmo** [comment]
Types seem to be in alphabetical order. "Main" in my example is actually "SourceSourceTests". I needed the order to be exactly how the parser read the source which I think is alphabetical order with exception on Java files that define multiple types, those will just be appended to the list in the order they are parsed (from top and downwards).
So if I have these files:
```
// AAA.java
class AAA {}
// BBB.java
class BBB {}
class AAB {}
class AAC {}
```
I think the AST should be:
```
root:
  AAA
  BBB
  AAB
  AAC
```
I dont see how `CtPackage#getTypes` help me here, I already tried it. I think I need to use another parser.

**Comment by slarse** [comment]
There actually is a problem here. While the API technically doesn't make any promises about the order of the types, we do ourselves want them (and, in fact, _everything_) in declaration order for the sniper printer to work as expected. The fact that they are currently sorted is an unfortunate side effect of #4076 meant to fix a `ConcurrentModificationException`.

I'm considering how to restore the declaration order.

**Comment by slarse** [comment]
@I-Al-Istannen FYI

**Comment by I-Al-Istannen** [comment]
Uff, this is indeed unfortunate. The element map is an internal implementation detail, we *could* theoretically also seed its keys with an incrementing LongAdder or sth, to ensure the skip list maintains insertion order. This won't help when a class is removed and re-inserted, but that is probably acceptable.

I don't think that is a result of my PR to be honest though, as the previous implementation used a `TreeSet` which *also* maintains a specific order (based on the qualified name). I might have missed how insertion order was maintained previously?

**Comment by slarse** [comment]
You're probably right that this was already broken.

But I have an idea for how to maintain insertion order, PR coming up within the hour :)

**Comment by slarse** [comment]
@joelmo You can try out my branch at #4832 to see if it meets your expectations.

**Comment by joelmo** [comment]
@slarse thanks a lot for fixing! I can't test at the moment but based on the test it should work for my case.

**Comment by slarse** [comment]
@joelmo Cool, thanks for the feedback!
