### ISSUE TITLE
Is `setType` expected to type coerce parent elements?

### ISSUE THREAD

**Issue by algomaster99** [INRIA/spoon#4857]
I had a question about behaviour [`setType`](https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/reflect/declaration/CtTypedElement.java#L30) API. Consider the following code snippet:

```java
float x = 1.0f;
float y = 2.0f;
float z = 3.0f;

double c = x + y + z + 4.0f;
```

If I set the type of `(y + z)` as `double` using `setType(double)`, should one expect that the `type` of the expression `((x + y) + z)` is also changed to `double` given that JVM type coerces all entities to `double`? I have an intuition that this is not Spoon's job because type coercion happens at compile time and we never compile after the AST is built. However, I would appreciate some insights into this.

**Comment by I-Al-Istannen** [comment]
Hey,

in its current state spoon takes accurate information (more or less) from JDT when building the model and entrusts the developer with adjusting it as needed. If you only transform the model to print it out again, compatible type mismatches are not a big deal — and they do not occur if you are just analyzing it. The only usecase it impacts is transforming the model and then analyzing it without rebuilding.

Therefore, I would advocate against it as well. Spoon does not fix other places where the types would need to be adjusted and I don't believe you can even do it properly without re-implementing type inference yourself here. It is also not always possible to adjust the types without spreading out conflicts (e.g. consider changing a method return type from `String` to `Object`, invalidating almost all callsites without an automatic fix). You would need to match JDTs behaviour in all cases here, or else you will introduce inconsistencies between a freshly built model and your adapted one.

Doing type coercion/inference in a few special cases sounds more perplexing than helpful IMHO.

**Comment by algomaster99** [comment]
Hi @I-Al-Istannen!

>  consider changing a method return type from String to Object, invalidating almost all callsites without an automatic fix

The example makes it very clear why we want to invalidate this feature request. Thank you!
