### ISSUE TITLE
[Bug]: Inconsistency in modelling of invocations of signature polymorphic methods

### ISSUE THREAD

**Issue by SirYwell** [INRIA/spoon#4863]
### Describe the bug

*Another sweet, very specific edge case*
Java has a few [signature polymorphic methods](https://docs.oracle.com/javase/specs/jls/se18/html/jls-15.html#jls-15.12.3).

In my opinion, there are two ways how spoon could model invocations of such methods:

1. Use the return type and the the `Object...` (or `Object[]`) type parameter of the declared method
2. Use the return type and the parameters from the invocation context as described in the JLS.

However, spoon currently picks the third one: The return type is invocation-specific but the parameter is always `Object[]`.

Both solutions are possible as JDT provides the needed information. This issue is rather for discussion which solution is more appropriate for spoon.

### Source code you are trying to analyze/transform

```Java
package invoke;

import spoon.Launcher;
import spoon.reflect.CtModel;
import spoon.reflect.code.CtInvocation;
import spoon.reflect.declaration.CtMethod;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.MethodHandles;

public class SignaturePolymorphic {
  private static final MethodHandle MH = MethodHandles.identity(String.class);
  public static void main(String[] args) throws Throwable {
    Launcher launcher  = new Launcher();
    launcher.addInputResource("src/main/java/invoke/SignaturePolymorphic.java");
    launcher.getEnvironment().setComplianceLevel(17);
    CtModel ctModel = launcher.buildModel();
    for (CtMethod<?> method : ctModel.getAllTypes().iterator().next().getMethodsByName("a")) {
      CtInvocation<?> lastStatement = method.getBody().getLastStatement();
      lastStatement = (CtInvocation<?>) lastStatement.getArguments().get(0);
      System.out.println(lastStatement.getType());
      System.out.println(lastStatement.getExecutable().getParameters());
    }
  }

  private void a() throws Throwable {
    System.out.println((String) MH.invoke("Hello World"));
  }
}
```

### Source code for your Spoon processing

```Java
(contained in the example above)
```

### Actual output

```Java
java.lang.String
[java.lang.Object[]]
```

### Expected output

```Java
Either

java.lang.String
[java.lang.String]

or

java.lang.Object
[java.lang.Object[]]
```

### Spoon Version

10.2.0-beta-16

### JVM Version

17

### What operating system are you using?

Windows 11

**Comment by I-Al-Istannen** [comment]
I don't think I want to know from what abyss you dragged this up, but I would be for Option 2: Using the correct type in an invocation but `Object` for the executable declaration itself. That seems to be how the JLS suggests to handle it and I don't know why we wouldn't follow, if JDT provides all necessary details.

*Unless* that requires us to hardcode all signature polymorphic methods, as keeping that list up to date with the JLS sounds like something that will be forgotten in no time.

**Comment by SirYwell** [comment]
> _Unless_ that requires us to hardcode all signature polymorphic methods, as keeping that list up to date with the JLS sounds like something that will be forgotten in no time.

JDT tags such invocations accordingly, I think depending on that would be as safe as it gets.

The current issue is basically here https://github.com/INRIA/spoon/blob/67bd4f13dfce573770142aa0bf2a9a3eae8e5837/src/main/java/spoon/support/compiler/jdt/ReferenceBuilder.java#L431

If the original() branch is taken, it reads the parameters from the method instead of the MethodBinding. I didn't why this is needed for generic methods.

If the else branch is taken, the parameters are provided as required for option 2.

I think this would still need some investigation (e.g. `getExecutableDeclaration()` should still work).

**Comment by SirYwell** [comment]
In my PR, I currently implemented option 1. Option 2 caused too many issues with the declaration lookup - as no method with the signature exists.

I'm still not sure which approach is more practical for usage in spoon, so I'd like your input on that @monperrus @slarse @MartinWitt. What do you think should be the behavior here?

**Comment by slarse** [comment]
@SirYwell Sorry I've been moving to a new apartment over the past month and am a wee bit preoccupied :s 

This one is a bit of a brain twister so I'm not sure I've completely understood what these special methods even are. I agree that the current behavior is wrong as it's inconsistent. Based on reading up on this for about 10 minutes, option 2 seems somewhat _more correct_ to me than option 1. Both the JLS and the docs for `MethodHandle` describe that the compiler determines the types of the formal parameters and the return type if a signature polymorphic method based on the actual arguments and the cast on invocation (if one exists). Based on that I would expect option 2.

That being said, I also believe this is such a massive corner case that we should just do whichever one is easiest, which I believe your current solution is.

**Comment by monperrus** [comment]
> I also believe this is such a massive corner case that we should just do whichever one is easiest,

:+1:

**Comment by SirYwell** [comment]
> Sorry I've been moving to a new apartment over the past month and am a wee bit preoccupied :s

Understandable, but we're also not in hurry with this one anyway I guess :)


> Based on reading up on this for about 10 minutes, option 2 seems somewhat _more correct_ to me than option 1. Both the JLS and the docs for `MethodHandle` describe that the compiler determines the types of the formal parameters and the return type if a signature polymorphic method based on the actual arguments and the cast on invocation (if one exists). Based on that I would expect option 2.

Yes, that's why I first tried to implement option 2, but that just opened a can of worms, and it looked like without properly addressing the caused issues, it would be rather harmful than useful.

As it seems like we can agree on option 1 as it's easier to implement, I'll get the PR ready for review soon.

**Comment by slarse** [comment]
Yeah, I think that easy is the way to go for this one.
