### ISSUE TITLE
Javadoc quality check does not work with checkstyle-maven-plugin 3.2.0

### ISSUE THREAD

**Issue by slarse** [INRIA/spoon#4869]
After merging #4859 CI started failing on the master branch. So something about it is incompatible with the javadoc style script. Here's the output:

```
Run ./chore/check-javadoc-regressions.py COMPARE_WITH_MASTER
$ git rev-parse --show-toplevel
$ git checkout master
$ mvn -B checkstyle:check --fail-never -Dcheckstyle.config.location=/tmp/tmppz3dbyx5.xml
$ git checkout -
$ mvn -B checkstyle:check --fail-never -Dcheckstyle.config.location=/tmp/tmppz3dbyx5.xml
The Checkstyle run for the reference branch did not yield any result.
Error: Process completed with exit code 1.
```

https://github.com/INRIA/spoon/runs/8057134947?check_suite_focus=true#step:9:21

So we had to roll back for the moment

**Comment by I-Al-Istannen** [comment]
The checkstyle version has changed and a property we used (visibility of methods) was renamed. I PRed a fix in #4870.
