### ISSUE TITLE
Getting extra parenthesis on variable assignments with concatenation of other variables.

### ISSUE THREAD

**Issue by Vardhamansankar** [INRIA/spoon#4881]
For example in my java code, I am having a **String query = query1 + query2 + query 3;**
 When I am using **CtLocalVariable.getAssignment()**, its giving **((query1 + query2) + query 3)** as **String query** variable assignment. It is adding extra parenthesis in that output.

I want output as query1 + query2 + query 3 as it is without any extra parenthesis added.

**Comment by I-Al-Istannen** [comment]
Have you tried setting `setMinimizeRoundBrackets(true)` on your printer?

You sadly did not post any example code that triggers the bug for you, but the following might still help you:
```java
        launcher.getEnvironment().setPrettyPrinterCreator(() -> {
            DefaultJavaPrettyPrinter printer = new DefaultJavaPrettyPrinter(launcher.getEnvironment());
            printer.setMinimizeRoundBrackets(true);
            return printer;
        });
```

Alternatively you could try using the *SniperPrinter*, which tries its best to only modify *needed* elements instead of reformatting the whole file.

**Comment by algomaster99** [comment]
@I-Al-Istannen, `setMinimizeRoundBrackets` is `protected` and is not open to public. However, we had a similar issue raised before and this was a working solution for it - https://github.com/INRIA/spoon/issues/4807#issuecomment-1202263121.

**Comment by I-Al-Istannen** [comment]
Ah, neat. Missed that discussion, thanks :)

**Comment by Vardhamansankar** [comment]
Heya @I-Al-Istannen @algomaster99 , I tried this way while creating launcher as follows,
```
Launcher launcher = new Launcher();
		launcher.addInputResource("./src/test/java/spoon/test/ctLocalVariables/Foo.java");
		Environment e = launcher.getEnvironment();
		RoundBracketPrinter printer = new RoundBracketPrinter(launcher.getEnvironment());
		e.setPrettyPrinterCreator(() -> printer);
		launcher.buildModel();
		CtModel model = launcher.getModel();
List<CtLocalVariable> variables =   model.getElements(new TypeFilter<>(CtLocalVariable.class));
		for(CtLocalVariable variable: variables) {
			System.out.println(variable.getSimpleName().toString()+" --------- "+variable.getAssignment().toString());
		}

```

And having an explicit class as **RoundBracketPrinter**
`class RoundBracketPrinter extends DefaultJavaPrettyPrinter {
public RoundBracketPrinter(Environment env) {
super(env);
this.setMinimizeRoundBrackets(true);
}
}`

My inputResource is of this code, 
`public class Foo {

	public void method1() {

		String QUERY = "A"+"B"+"C"+"D";
		String QUERY1 = "A1"+"B1"+"C1"+"D1";
	}

}`

When executing the above code, my output is **QUERY --------- "A" + "B" + "C" + "D"
QUERY1 --------- "A" + "B" + "C" + "D""A1" + "B1" + "C1" + "D1"**

If you see for **QUERY** its giving proper assignment, but for **QUERY1** its giving **"A" + "B" + "C" + "D""A1" + "B1" + "C1" + "D1"** instead of **"A1" + "B1" + "C1" + "D1"**. 
Likewise, it's adding each previous variable assignment with other variable assignments.

Another Scenario: 
If I have code like this `public class Foo {

	public void method1() {

		String QUERY = "A"+"B"+"C"+"D";
		String QUERY1 = "A1"+"B1"+"C1"+"D1";
		String QUERY2 = "A2"+"B2"+"C2"+"D2";

	}`
the output is coming as **QUERY --------- "A" + "B" + "C" + "D"
QUERY1 --------- "A" + "B" + "C" + "D""A1" + "B1" + "C1" + "D1"
QUERY2 --------- "A" + "B" + "C" + "D""A1" + "B1" + "C1" + "D1""A2" + "B2" + "C2" + "D2"**
each assignment keeps adding in the following variable assignments.

**Comment by I-Al-Istannen** [comment]
@Vardhamansankar That happens because you re-use the same printer instance and the default printer is stateful in spoon. To fix this, you need to always return a new printer:

```java
		e.setPrettyPrinterCreator(() -> new RoundBracketPrinter(launcher.getEnvironment()));
```

Using this, the output becomes:
```
QUERY --------- "A" + "B" + "C" + "D"
QUERY1 --------- "A1" + "B1" + "C1" + "D1"
```

Which sounds nicer :)

**Comment by Vardhamansankar** [comment]
Thanks, much @I-Al-Istannen @algomaster99, the issue got resolved.

**Comment by zqudm** [comment]
I have the similar problem. the following code is provided which is to be analyzed.

```
public CtBehavior where() {
    MethodInfo mi = thisMethod;
    CtBehavior[] cb = thisClass.getDeclaredBehaviors();
    for (int j = 0, i = cb.length - 1; i >= 0; --i) {
        if (cb[i].getMethodInfo2() == mi) {
            return cb[i];
        }
    }
    for (CtBehavior cd : cb) {
        java.lang.System.out.println("s");
    }
    double myDouble = 9.78;
    int myInt = (int) myDouble;
    CtConstructor init = thisClass.getClassInitializer();
    if ((init != null) && (init.getMethodInfo2() == mi)) {
        return init;
    }
    for (int i = cb.length - 1; i >= 0; --i) {
        if (thisMethod.getName().equals(cb[i].getMethodInfo2().getName()) && thisMethod.getDescriptor().equals(cb[i].getMethodInfo2().getDescriptor())) {
            return cb[i];
        }
    }
    throw new java.lang.RuntimeException("fatal: not found");
}

```
After tried SniperJavaPrettyPrinter, DefaultJavaPrettyPrinter, and RoundBracketPrinter, but the type cast expression would contain extra parenthesis still as shown in below. 


```
public CtBehavior where() {
    MethodInfo mi = thisMethod;
    CtBehavior[] cb = thisClass.getDeclaredBehaviors();
    for (int j = 0, i = cb.length - 1; i >= 0; --i) {
        if (cb[i].getMethodInfo2() == mi) {
            return cb[i];
        }
    }
    for (CtBehavior cd : cb) {
        java.lang.System.out.println("s");
    }
    double myDouble = 9.78;
    int myInt =( (int) (myDouble));
    CtConstructor init = thisClass.getClassInitializer();
    if ((init != null) && (init.getMethodInfo2() == mi)) {
        return init;
    }
    for (int i = cb.length - 1; i >= 0; --i) {
        if (thisMethod.getName().equals(cb[i].getMethodInfo2().getName()) && thisMethod.getDescriptor().equals(cb[i].getMethodInfo2().getDescriptor())) {
            return cb[i];
        }
    }
    throw new java.lang.RuntimeException("fatal: not found");
}

```
How to solve this problem? Thanks!

**Comment by algomaster99** [comment]
Hi @zqudm !

I tried reproducing it, and it seems like a bug. I am also getting `int myInt =( (int) (myDouble));` even if I minimise bracket printing. I am taking a look at it.

**Comment by algomaster99** [comment]
This error is probably emanating from lines: https://github.com/INRIA/spoon/blob/b8ee5e9cd598add13b1580fc50259a9dcdfeff22/src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java#L403-L405
It simply assumes that the bracket should be set if an expression has typecasts.

**Comment by zqudm** [comment]
@algomaster99 ,   i have replaced "return true" with "return false" , the output is   " int myInt = (int) (myDouble)"  ,  it also produce extra parenthesis, that is ,  (myDouble).
 if (!e.getTypeCasts().isEmpty()) { 
 	return true; 
 }

**Comment by algomaster99** [comment]
I tried something like `!e.getTypeCasts().isEmpty() && !isMinimizeRoundBrackets()` and I got the same output - extra parenthesis around `myDouble`. I will take a look at it tomorrow. I am busy with some things today - one of them is moving into a new place :)

**Comment by zqudm** [comment]
@algomaster99 , Hi, i found another case that extra parenthesis is produced . That is,  lambda expression would print extra parenthesis too. For  example ,

```
private float foo(int i, int j) {
    java.util.List l = new java.util.ArrayList();
    l.stream().map( x -> {
        return x.toString();
    });
  }
```

```
private float foo(int i, int j) {
    java.util.List l = new java.util.ArrayList();
    l.stream().map(( x) -> {
        return x.toString();
    });
  }
```
Is this a bug ?  Thanks!
