### ISSUE TITLE
[Bug]: Pretty printing issue for array type variable

### ISSUE THREAD

**Issue by jiseongg** [INRIA/spoon#4887]
### Describe the bug

When calling `toString` method on `CtLocalVariable<?>` of array type, it prints type declaration of component type, not the array of the component type.

### Source code you are trying to analyze/transform

```Java
// This is issue in creating code element.
// I'm trying to create the following code
int[] intArray = new int[]{ 3 };
```

### Source code for your Spoon processing

```Java
Launcher launcher = new Launcher();
Factory factory = launcher.getFactory();

CtArrayTypeReference<Integer> arrayTypeReference = factory.createArrayTypeReference();
arrayTypeReference.setComponentType(factory.Type().INTEGER_PRIMITIVE);
CtNewArray<Integer> newArray = factory.createNewArray();

newArray.setValueByRole(CtRole.TYPE, arrayTypeReference);
List<CtLiteral<Integer>> elements = new ArrayList<>(List.of(factory.createLiteral(3)));
newArray.setValueByRole(CtRole.EXPRESSION, elements);
CtLocalVariable<Integer> localVariable = factory.createLocalVariable(arrayTypeReference, "intArray", newArray);
System.out.println(localVariable);
```

### Actual output

```Java
int intArray = new int[]{ 3 }
```

### Expected output

```Java
int[] intArray = new int[]{ 3 }
```

### Spoon Version

10.2.0-SNAPSHOT
(current master)

It happened after I recently upgraded my local Spoon to the version above, and with some trial I figured out this doesn't occur in 10.0.0, and does occur in 10.1.0.

### JVM Version

15

### What operating system are you using?

macOS Monterey Version 12.5.1

**Comment by I-Al-Istannen** [comment]
I bisected it and git thinks it was (not surprisingly probably) broken by https://github.com/INRIA/spoon/pull/4341. I haven't looked further into it, but that might be helpful if anybody gets to it before me.

**Comment by algomaster99** [comment]
@I-Al-Istannen you can assign it to me. I can have a look at it latest by tomorrow.
