### ISSUE TITLE
Getting null in CtType when the code having try..catch {} block 

### ISSUE THREAD

**Issue by Vardhamansankar** [INRIA/spoon#4890]
I am trying to get the method name using CtType and CtMethod, but it's giving null in CtType if the code is inside try... catch block.

For example This is the code I am trying to scan using a spoon

`@Override
	public List<Suggestion> listProject() {
		// TODO Auto-generated method stub
		List resultList = new ArrayList<Suggestion>();
		Session session = this.getSessionFactory().getCurrentSession();
		Connection connection = session.connection();
		try{
			StringBuffer sql = new StringBuffer(); 
			sql.append("select A.REF_KEY, A.SHORT_DESC ");
			sql.append("from ip_master_table A ");
			sql.append("where ref_table = 'LOCATION' ");
			sql.append("ORDER BY A.SHORT_DESC ");
			Statement stmt = connection.createStatement();
			ResultSet rs = stmt.executeQuery(sql.toString());
			while(rs.next()){
				resultList.add(new Suggestion(rs.getString("REF_KEY"),rs.getString("SHORT_DESC")));
			}
			rs.close();
			stmt.close();
		} catch (Exception ex){
			ex.printStackTrace();
		}
		return resultList;
	}`

I wrote a method like this to get the method name from the input resource code like this way:

`CtType<?> type = model.getRootPackage().getType(currentFileName);
Set<CtMethod<?>> methods = type.getMethods();`

Here **type** is null for the above example code given, only because there we have a try .... catch {} block. I need to have the CtMethod to get CtStatements of this particular function which given above.

But I can get **type** if that method does not have a try ... catch {} block in it.

@I-Al-Istannen @algomaster99 , will be helpful if you give me some solution or idea to resolve this problem.

**Comment by algomaster99** [comment]
Hi @Vardhamansankar !

I tried reproducing your issue, but it seems that the behaviour does not change depending upon the presence of a `try-catch` block. However, you are getting `null` possibly because the type is _not_ in the root package, but a subpackage. If a file has no `package` declaration, then Spoon, by default, puts the type corresponding to it in the root package which is called `"unnamed package "`. So let's say you have the above method in a type called "A" and it is in a package called `foo.bar`, you would need to fetch the package first and they query that package for the type.

You can filter the package using `model.getAllPackages()` or you could also try `model.getRootPackage.getPackage("foo").getPackage("bar")`.

**Comment by I-Al-Istannen** [comment]
Also @Vardhamansankar, is there any reason you did not use the "Bug" issue template (i.e. what you get when you click on [new issue](https://github.com/INRIA/spoon/issues/new/choose))? It was designed to give us any important information we might need, so I was wondering why you thought it didn't fit. Maybe because you thought it was more of a question than a bug?

Would be interesting to know what your thought process was so we can improve the templates :)

**Comment by Vardhamansankar** [comment]
Yes, @I-Al-Istannen , I thought this is more of a question where I am missing to get some details, so not raised as a bug issue....

**Comment by algomaster99** [comment]
@I-Al-Istannen If I had such an issue, I would probably choose no template as well. There are many times I am unsure if my question would result in a bug being surfaced.

**Comment by slarse** [comment]
It seems we need another issue template :)

**Comment by Vardhamansankar** [comment]
Hey @algomaster99 , As you suggested we tried the way, but yet we cant get CtType for this particular java file. Please suggest us any other way to get type if the file having try...catch() block

**Comment by I-Al-Istannen** [comment]
@Vardhamansankar 
I can not reproduce your error using the following minimal example:
```java
	@Test
	void foo() {
		Launcher launcher = new Launcher();
		launcher.addInputResource(new VirtualFile(
			"public class Test {\n" +
				"  @Override\n" +
				"  public List<Suggestion> listProject() {\n" +
				"    // TODO Auto-generated method stub\n" +
				"    List resultList = new ArrayList<Suggestion>();\n" +
				"    Session session = this.getSessionFactory().getCurrentSession();\n" +
				"    Connection connection = session.connection();\n" +
				"    try {\n" +
				"      StringBuffer sql = new StringBuffer();\n" +
				"      sql.append(\"select A.REF_KEY, A.SHORT_DESC \");\n" +
				"      sql.append(\"from ip_master_table A \");\n" +
				"      sql.append(\"where ref_table = 'LOCATION' \");\n" +
				"      sql.append(\"ORDER BY A.SHORT_DESC \");\n" +
				"      Statement stmt = connection.createStatement();\n" +
				"      ResultSet rs = stmt.executeQuery(sql.toString());\n" +
				"      while (rs.next()) {\n" +
				"        resultList.add(new Suggestion(rs.getString(\"REF_KEY\"), rs.getString(\"SHORT_DESC\")));\n" +
				"      }\n" +
				"      rs.close();\n" +
				"      stmt.close();\n" +
				"    } catch (Exception ex) {\n" +
				"      ex.printStackTrace();\n" +
				"    }\n" +
				"    return resultList;\n" +
				"  }\n" +
				"}\n"
		));
		launcher.getEnvironment().setComplianceLevel(17);
		launcher.buildModel();
		System.out.println(launcher.getFactory().Type().get("Test").getMethods());
	}
```

In order to help you further I'd likely need an actual failing example from you.

**Comment by Vardhamansankar** [comment]
Hi @I-Al-Istannen ,

I am providing the file which i am taking as inputResource(), 

`
package th.co.abc.rgtb.dao.hibernate;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import org.hibernate.Hibernate;
import org.hibernate.Session;

import th.co.ais.ipfm.dao.IMainMenuDao;
import th.co.ais.ipfm.domain.Suggestion;
import th.co.ais.ipfm.domain1.IpFunction;

public class HibernateExample extends HibernateGenericDao<IpFunction> implements IMainMenuDao {

	@Override
	public List<IpFunction> listMenuByUserID(String userId) throws Exception{
		Session session = this.getSessionFactory().getCurrentSession();
		List<IpFunction> result = new ArrayList<IpFunction>();
		try {
			StringBuffer sqlBuff = new StringBuffer();
			sqlBuff.append("select distinct f from IpRoleFunction t , IpRoleMember m , IpFunction f " +
					"where t.id.roleId = m.id.roleId " +
					"and t.id.funcId = f.funcId " +
					"and m.id.userId = '"+userId+"' order by f.menuLevel,f.menuSeq");
			result = session.createQuery(sqlBuff.toString()).list();
			
		}catch (Exception e) {
			e.printStackTrace();
			throw e;
		} finally {
		}
		return result;
	}



	@Override
	public List<Suggestion> listProject() {
		// TODO Auto-generated method stub
		List resultList = new ArrayList<Suggestion>();
		Session session = this.getSessionFactory().getCurrentSession();
		Connection connection = session.connection();
		try{
			StringBuffer sql = new StringBuffer(); 
			sql.append("select A.REF_KEY, A.SHORT_DESC ");
			sql.append("from ip_master_table A ");
			sql.append("where ref_table = 'LOCATION' ");
			sql.append("ORDER BY A.SHORT_DESC ");
			
			Statement stmt = connection.createStatement();
			ResultSet rs = stmt.executeQuery(sql.toString());
			while(rs.next()){
				resultList.add(new Suggestion(rs.getString("REF_KEY"),rs.getString("SHORT_DESC")));
			}
			rs.close();
			stmt.close();
		} catch (Exception ex){
			ex.printStackTrace();
		}
		return resultList;
	}

	@Override
	public List<IpFunction> findAllMenu() {
		List<IpFunction> resultList = new ArrayList<IpFunction>();
		Session session = this.getSessionFactory().getCurrentSession();
		try{
			StringBuffer sql = new StringBuffer(); 
			sql.append("select t ");
			sql.append("from IPFunction t ");
			sql.append("order by t.funcId asc ");
			
			resultList = session.createQuery(sql.toString()).list();
			Hibernate.initialize(resultList);
			System.out.println("IPFunction size = "+ resultList.size());
			if (resultList==null || resultList.size()==0) {
				resultList = new ArrayList<IpFunction>();
			}else{
//				
			}
			
		} catch (Exception ex){
			ex.printStackTrace();
		}finally{
		}
		return resultList;
	}

	@Override
	public IpFunction findMenuByRowId(Integer rowId) {
		IpFunction result = new IpFunction();
		Session session = this.getSessionFactory().getCurrentSession();
		try{
			StringBuffer sql = new StringBuffer(); 
			sql.append("select t ");
			sql.append("from IpFunction t ");
			sql.append("where t.rowId = '"+rowId+"' ");
			sql.append("order by funcId asc ");
			
			List<IpFunction> resultList = session.createQuery(sql.toString()).list();
			
			if (resultList==null || resultList.size()>0) {
				result = resultList.get(0);
			}
		} catch (Exception ex){
			ex.printStackTrace();
		}finally{
			//session.close();
		}
		return result;
	}

	@Override
	public List<IpFunction> findMenuLevel1ByUserId(String userId) throws Exception{
		Session session = this.getSessionFactory().getCurrentSession();
		List<IpFunction> result = new ArrayList<IpFunction>();
		try { 
			StringBuffer sqlBuff = new StringBuffer();
			sqlBuff.append("select distinct f from IpRoleFunction t , IpRoleMember m , IpFunction f " +
					"where t.id.roleId = m.id.roleId " +
					"and t.id.funcId = f.funcId " +
					"and f.menuLevel = '0' " +
					"and m.id.userId = '"+userId+"' order by f.menuSeq");
			result = session.createQuery(sqlBuff.toString()).list();
		
		}catch (Exception e) {
			e.printStackTrace();
			throw e;
		} finally {
		}
		return result;
	}

	
	


}

`


And I am trying to get type for this above code using 

`

			CtType<?> type = model.getRootPackage().getType(currentFileName);
			Set<CtMethod<?>> methods = type.getMethods();
			for (CtMethod<?> method : methods) {
				List<CtStatement> statements = method.getBody().getStatements();
				for (CtStatement statement : statements) {
					if (statement.getReferencedTypes().contains(factory.createCtTypeReference(StringBuffer.class))) {
						al.add(method);
						break;
`

**Comment by I-Al-Istannen** [comment]
@Vardhamansankar I reformatted your post. Please use triple-backticks for code :)

The problem is that your file has a `package` declaration of `th.co.abc.rgtb.dao.hibernate`. Therefore, this type is placed in the package `th.co.abc.rgtb.dao.hibernate`. Most importantly, it is **NOT** in the root package. It is in the subpackage `hibernate` of a subpackage `dao` of a subpackage `rgtb` of a subpackage `abc` of a subpackage `co` of a subpackage `th` of the root package. The `getType` function on a package does *not* perform recursive lookups.

You can use e.g. `launcher.getFactory().Type().get("th.co.abc.rgtb.dao.hibernate.HibernateExample")` to perform a search across all modules and go down the package hierarchy.

**Comment by algomaster99** [comment]
> The getType function on a package does not perform recursive lookups.

Yeah, I was wondering why it does not, but good to know we can do that using `TypeFactory` so it is sufficient.

**Comment by Vardhamansankar** [comment]
Hi @algomaster99 ,


We tried this way and now getting type for that file, 
```
List<CtType<?>>` pack = javaFileLauncher.getFactory().Type().getAll();
CtType<Object> a = pack.get(0).getTopLevelType();
```

but we getting empty array in these place as,

```
Set<CtMethod<?>> methods = a.getMethods();
List<CtStatement> sbStatements = methods.getBody().getStatements();
```

Any way to tackle this would be helpful :)

**Comment by algomaster99** [comment]
Hello @Vardhamansankar !

> ```
>	Set<CtMethod<?>> methods = a.getMethods();
>	List<CtStatement> sbStatements = methods.getBody().getStatements();```

The usage of `getBody` is incorrect here. `getBody` is an API provided by Spoon to fetch the body of an instace of `CtMethod`. You have called `getBody` **on a set of methods**. This would result in a compilation error because `Set` interface does not have a public API by that name.

Inferring from your second statement, I guess you need to fetch statements inside every method's body? To do so, you need to first get the method whose statements you need, and then you can call `.getBody().getStatements()` on **the instance of `CtMethod`**. You could do this in a `for-loop` like so:

```java
for (CtMethod<?> method: a.getMethods()) {
	List<CtStatement> statements = method.getBody().getStatements();
}
```

**Comment by Vardhamansankar** [comment]
Hi @I-Al-Istannen @algomaster99 ,

I created a way to get methods as set using CtMethod. I wrote the code in this way 
```
for (CtMethod<?> requiredMethod : requiredMethods) {
				String lineNumber = "";
				if (queryMethodFunctionName.equalsIgnoreCase(requiredMethod.getSimpleName().toString())) {
					List<CtStatement> sbStatements1 = requiredMethod.getBody().getStatements();
					List<CtStatement> sbStatements = requiredMethod.getBody().getStatements().stream()
							.filter(st -> st instanceof CtInvocation && ((CtInvocation<?>) st).getTarget().toString()
									.equalsIgnoreCase(stringBufferVariableName.strip()))
							.collect(Collectors.toList());
					for (CtStatement sbStatement : sbStatements) {
						List<String> queryPartDetailsList = new ArrayList<String>();
						CtInvocation<?> sbInvocation = (CtInvocation<?>) sbStatement;
						queryPartDetailsList.add(sbInvocation.getArguments().get(0).toString().replaceAll("\"", ""));


```


trying to get all CtInvocation in CtStatements. But I need to filter if any CtTryImpl is present in that CtStatement, Please suggest to me a good way to achieve this.

**Comment by algomaster99** [comment]
If you are iterating statements in a for-loop, you can simply add an `if` condition like so:
```java
if (statement instance CtTry) {
	continue;
}
```
