### ISSUE TITLE
How to get variable assignment if its initiated seperately

### ISSUE THREAD

**Issue by Vardhamansankar** [INRIA/spoon#4892]
I am trying to get a variable assignment using CtLocalVariable.getAssignment() for the below code,

` public List<TempIpLevel2> findTempIpLevel2(Integer maxSearchResult) throws Exception {
Session session = getSessionFactory().getCurrentSession();
List<TempIpLevel2> result = new ArrayList<TempIpLevel2>();
StringBuffer sql = new StringBuffer();
sql.append(" select t ");
sql.append(" from TempIpLevel2 t ");
sql.append(" order by t.binary2Start, t.binary2Start ");  
result =  session.createQuery(sql.toString()).setMaxResults(maxSearchResult).list();
return result;
}`

For **result** I am not able to whats there after **=** as I am expecting to get  **session.createQuery(sql.toString()).setMaxResults(maxSearchResult).list();** for **result** variable. 
Is that because it's defined separately and assigned separately? If so please help me if any alternatives are available for this.

**Comment by Vardhamansankar** [comment]
Hi,
We tried a solution with [CtAssignment](https://spoon.gforge.inria.fr/mvnsites/spoon-core/apidocs/spoon/reflect/code/CtAssignment.html) and it is working based on our requirement. So currently closing this issue.

**Comment by algomaster99** [comment]
That seems the way to go.

I also have a suggestion. Whenever you post code snippet in an issue, you could enclose them in between [` ``` `s](https://www.markdownguide.org/extended-syntax/#fenced-code-blocks). This makes the snippet more readable.
