### ISSUE TITLE
Not able to get the data from some particular code lines - Need Information

### ISSUE THREAD

**Issue by Vardhamansankar** [INRIA/spoon#4914]
I am trying to get the data from the code as follows,

```java

public void updateNatIP(String ip, String natIP) throws DataAccessException {
		Session session = getSessionFactory().getCurrentSession();		
		StringBuffer sql = new StringBuffer();
		sql.append("update IP_INFO set NAT_IP = ? where ip_address = ? " );
		session.createSQLQuery(sql.toString()).setString(0, (natIP==null?"":(natIP.trim()))).setString(1, ip).executeUpdate();		
	}



```

where i want the total last line **session.createSQLQuery(sql.toString()).setString(0, (natIP==null?"":(natIP.trim()))).setString(1, ip).executeUpdate();**.

Is there any way to achieve this? Since the session is not assigned with any variable, I can't use CtLocalVariable.

**Comment by MartinWitt** [comment]
```java
    CtMethod<?> method = null;
    // check for null body
    if (method.getBody() != null) {
      List<CtStatement> statements = method.getBody().getStatements();
      statements.stream().filter(/* do your filter to find the statement you want e.g*/ v -> v.getPosition().getLine() == 5)
          .forEach(v -> {
            // do your assertions
          });
    }
```
The code above should work for your case. You more or less want the body of the method and then get the list of statements. In this list, you need to filter for the wanted statement. A `CtStatement` is more or less a line finished by a `;`.

**Comment by Vardhamansankar** [comment]
Hey @MartinWitt , As per your suggestion I need to know the line number right, but as per my requirement I don't know those details. I want to take only lines where there are Session objects present with createSQLQuery() methods. So is there any way to get it based on this requirement.

**Comment by MartinWitt** [comment]
```java
    CtMethod<?> method = null;
    // create the reference to `createSQLQuery`
    var ctExecutableReference = method.getFactory().Executable().createReference(null, false, null, null);
    InvocationFilter invocationFilter = new InvocationFilter(ctExecutableReference);
    var result = method.getElements(new TypeFilter<>(CtInvocation.class))
		.stream()
		.filter(v -> invocationFilter.matches(v))
        .collect(Collectors.toList());
```
> I want to take only lines where there are Session objects present with createSQLQuery() methods.

The above should do the trick then. You only need to create a reference of the method you want, and the `InvocationFilter` should find all `createSQLQuery` methods. You also could simply filter a `CtInvocations` by their `SimpleName` and `TargetType`.
