### ISSUE TITLE
policy for creating submodules

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#4919]
This issue documents our policy for  creating submodules.

By default, we prefer to keep everything in spoon-core, in order to have the easiest possible integration.

We create submodules when

1) the functionality would bloat the spoon-core binary too much

OR

1) the functionality is too experimental / too unstable to meet the quality standard of spoon-core

**Comment by monperrus** [comment]
Comments welcome! We'll update the top comment afterwards.

**Comment by slarse** [comment]
Stuff like this should IMO go into `CONTRIBUTING.md`, as this is all about how to contribute. I don't think anyone would think to look for this kind of information in an issue, and I think issues should be actionable (and subsequently closed).

But we can discuss it here before we put it anywhere more permanent (and discoverable). What I feels is missing is our (the Spoon integrators') commitment to maintaining submodules. It ties into the "experimental" part, but it's not only about stability, it's also about the fact that we might entirely drop the submodule if we end up feeling like we can't maintain it. I felt that was @MartinWitt's motivation for makeng #4748 a submodule in the first place.

**Comment by monperrus** [comment]
Thanks @slarse superseded by https://github.com/INRIA/spoon/pull/4930
