### ISSUE TITLE
Apply custom Checkstyle to a file

### ISSUE THREAD

**Issue by Namyalg** [INRIA/spoon#4960]
I wanted to understand more about how custom Checkstyle can be applied to a given java file.
In my understanding on supplying a custom `xml` file, spoon will apply the changes and generate and output file

Does this handle the **formatting** as well as **rules** like `remove unused imports` ? 

I would like some references if this is possible

**Comment by I-Al-Istannen** [comment]
Hey,

I am not quite sure if you are talking about spoon or more generally about checkstyle itself. In spoon you can check for checkstyle violations using `mvn checkstyle:check`. Looking at the [plugin goals](https://maven.apache.org/plugins/maven-checkstyle-plugin/plugin-info.html), there is no way to automatically fix the issues it finds — many of them can not be fixed automatically anyways.

You can tell your IDE to set its style according to checkstyle (e.g. using the checkstyle plugin for IntelliJ and then importing a formatter profile from a checkstyle config). You can also use something like [spotless](https://github.com/diffplug/spotless), which can automatically reformat your code and remove unused imports according to its own configuration.

**Comment by Namyalg** [comment]
Thanks for the clarification, Im basically looking for a CLI based tool that can automatically fix checkstyle violations.
I did find `sorald` from the `SpoonLabs` page

**Comment by algomaster99** [comment]
Hi @Namyalg !

I am one of the maintainers of [Sorald](https://github.com/SpoonLabs/sorald) and I am glad you stumbled upon it. I just wanted to correct you that Sorald is not a formatter. It fixes [some static analysis violations](https://github.com/SpoonLabs/sorald/blob/master/docs/HANDLED_RULES.md) of the many outlined by [SonarSource](https://rules.sonarsource.com/java). I am not aware of any tool that automatically fixes checkstyle violations.

There is another tool called [logifix](https://github.com/lyxell/logifix), maintained by @lyxell , that deals with fixing violations raised by PMD, SonarSource, and SpotBugs.

**Comment by Namyalg** [comment]
Thank you @algomaster99, `logifix` works like a charm!

**Comment by algomaster99** [comment]
@Namyalg you can see [Styler](https://github.com/KTH/styler). This repairs checkstyle violation. :)

**Comment by slarse** [comment]
Closing as it seems like the initial question has been adequately answered. Feel free to reopen if you disagree with that assessment.
