### ISSUE TITLE
[Bug]: static initializers are forbidden in a record and throw an JLSViolation

### ISSUE THREAD

**Issue by RaphaelJenni** [INRIA/spoon#4961]
### Describe the bug

Java Records allow the inclusion of static fields, static initializers, and static methods. (https://docs.oracle.com/en/java/javase/17/language/records.html or https://openjdk.org/jeps/395)

When programmatically creating a record and adding a static initializer, a JLSViolation Error gets thrown.
The static initializer is wrapped in a CtAnonymousExecutable and is therefore not allowed (See location in code below).

https://github.com/INRIA/spoon/blame/master/src/main/java/spoon/support/reflect/declaration/CtRecordImpl.java#L120

### Source code you are trying to analyze/transform

```Java
record Test(int x) {
    static {
        println("test");
    }
}
```

### Source code for your Spoon processing

```Java
/**
     * Copies all statements that do not need special record treatment.
     */
    private fun copyUnhandledStatements() {
        baseClass.typeMembers
            .filter { d -> d !is CtField<*> && d !is CtMethod<*>}
            .forEach { record.addTypeMember<CtType<Any>>(it) }
    }
```

### Actual output

```Java
Exception in thread "main" spoon.JLSViolation: Anonymous executable is not allowed in a record
	at spoon.JLSViolation.throwIfSyntaxErrorsAreNotIgnored(JLSViolation.java:38)
	at spoon.support.reflect.declaration.CtRecordImpl.addTypeMemberAt(CtRecordImpl.java:120)
	at spoon.support.reflect.declaration.CtTypeImpl.addTypeMember(CtTypeImpl.java:122)
	...
```

### Spoon Version

10.1.1

### JVM Version

17

### What operating system are you using?

Ubuntu 22.04

**Comment by SirYwell** [comment]
Thanks for the report, this is indeed a bug. I provided a PR to fix it, feel free to take a look at it.

**Comment by RaphaelJenni** [comment]
Thanks for the quick response and the very fast fix. Looks good to me.
