### ISSUE TITLE
feature: one liner test infrastructure

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#499]
(suggested by @rouvoy)
Spec:

    assertThat('Foo.java').transformWith(MyProcessor.class).is('FooTransform.java')

What do you think?

**Comment by GerardPaligot** [comment]
There isn't any assert on the model, only on the pretty printing but the API is cool and it is a good starting point.

**Comment by monperrus** [comment]
it should indeed be the equality of the model. The `is` method would do:

    model(transform('Foo')) equals model('FooTransform')
