### ISSUE TITLE
[Bug]: Not all children of implicit elements are marked implicit

### ISSUE THREAD

**Issue by algomaster99** [INRIA/spoon#5009]
### Describe the bug

Some children on implicit elements are not `implicit`. I imagine that if an element is implicit, all its children are also. In the example below, the `body` of the default constructor and `java.lang.Object()` (called by the implicit `super`) are not implicit.

### Source code you are trying to analyze/transform

```Java
public class A {
    public static void main(String[] args) { }
}
```

### Source code for your Spoon processing

```Java
Launcher l = new Launcher();
l.addInputResource("src/test/resources/printer-test/A.java");
CtConstructor<?> implicitConstructor = l.buildModel().getElements(new TypeFilter<>(CtConstructor.class)).get(0);

new CtScanner() {
	@Override
	public void scan(CtElement element) {
		if (element != null) {
			assertTrue(element.isImplicit(), element.toString());
		}
		super.scan(element);
	}
}.scan(implicitConstructor);
```

### Actual output

```Java
org.opentest4j.AssertionFailedError: {
} ==> 
Expected :true
Actual   :false
```

### Expected output

```Java
Tests should pass
```

### Spoon Version

master

### JVM Version

11

### What operating system are you using?

Ubuntu 20.04 LTS

**Comment by SirYwell** [comment]
I guess this is related to https://github.com/INRIA/spoon/issues/4944

**Comment by slarse** [comment]
> Some children on implicit elements are not implicit. I imagine that if an element is implicit, all its children are also. 

Well, they are implicit. Implicitly.

I believe I encountered this problem as well during my work on Spork, and I have a vague recollection that after looking into it it "kind of made sense". But that was a very long time ago so I can't recall any details.
