### ISSUE TITLE
Variable from unresolved super-classes recognized as type

### ISSUE THREAD

**Issue by worblehat** [INRIA/spoon#501]
Consider the following code:

```
import example.Foo;

public class Demo extends Foo {

    void doSomething() {
        System.out.println(bar);
    }

}
```

Variable `bar` is declared in the super class `example.Foo` which is not in Spoon's class path and I analyse the code with `setNoClasspath(true)` using this processor to get all referenced types of class `Demo`:

```
private static class TypeReferenceProcessor extends AbstractProcessor<CtType<?>> {

   @Override
    public void process(CtType<?> spType) {
        for (CtTypeReference<?> spRef : spType.getReferencedTypes()) {
            System.out.println(spRef.getQualifiedName());
        }
    }
}
```

The output contains `bar` although it is not a type name, but a name of a variable. When using `this.bar` to access it, it is not in the list of referenced types.

**Comment by monperrus** [comment]
Tobias, out of curiosity, what kind of heavy duty are you doing in
noclasspath mode to find so many tricky bugs?

**Comment by worblehat** [comment]
I am using spoon to analyse large OSGi-based projects as part of my master thesis. The goal is to visualize the architecture of those projects and I use Spoon to get the necessary information from the sources.

OSGi applications are divided into "bundles" that run in the same JVM but have their own classpath each. So I can't just add all the bundles to Spoon's classpath as this would cause chaos.

I considered writing my own classloader for Spoon to handle this (see mailinglist post [1]) but decided to enable the noclasspath-option and handle resolution of inter-bundle references by myself (after Spoon analysed each bundle on it's own).

The project I currently analyse has about 180k lines of code so I guess I hit on some corner cases that are not encountered often with Spoon.

[1] http://lists.gforge.inria.fr/pipermail/spoon-discuss/2015-November/001832.html

**Comment by monperrus** [comment]
I would love to read about your methodology and results when you'll be
done. --Martin

**Comment by monperrus** [comment]
bar should be an instance of `CtUnboundVariableReference`?

**Comment by worblehat** [comment]
Thank you very much for this fast fix! You guys do an awesome job :)

@monperrus I will gladly show you my work when it's finished. I don't know how exactly, as I am going to write my thesis in german. ;) Maybe I'll summarize it in englisch...

**Comment by worblehat** [comment]
@GerardPaligot:
You only handle the situation where the unknown field is used as an argument, but not when it is used to access one of its members like this:

```
import example.Foo;

public class Demo extends Foo {

    void doSomething() {
        bar.spam();
    }

}
```

**Comment by worblehat** [comment]
I encountered another problem within the lines added in 9194c8c in this situation:

```
import example.A;
import example.B;

public class Demo extends B {

    A a;
    private void doSomething() {
        a.foo().bar(b);
    }
}
```

When `A` and `B` are not in the classpath and `b` is a member of `B` I get a NPE:

```
Exception in thread "main" java.lang.NullPointerException
	at spoon.support.compiler.jdt.JDTTreeBuilder.visit(JDTTreeBuilder.java:3086)
	at org.eclipse.jdt.internal.compiler.ast.SingleNameReference.traverse(SingleNameReference.java:1046)
	at spoon.support.compiler.jdt.JDTTreeBuilder.visit(JDTTreeBuilder.java:2643)
	at org.eclipse.jdt.internal.compiler.ast.MessageSend.traverse(MessageSend.java:1031)
	at spoon.support.compiler.jdt.JDTTreeBuilder.visit(JDTTreeBuilder.java:2723)
	at org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.traverse(MethodDeclaration.java:327)
	at spoon.support.compiler.jdt.JDTTreeBuilder.visit(JDTTreeBuilder.java:3456)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.traverse(TypeDeclaration.java:1319)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.traverse(CompilationUnitDeclaration.java:748)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.traverse(CompilationUnitDeclaration.java:709)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildSources(JDTBasedSpoonCompiler.java:228)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:481)
	at analysis.Analyzer.main(Analyzer.java:19)
```

**Comment by GerardPaligot** [comment]
Well, we shouldn't have a NullPointerException (a fix will come soon for that) but that will be hard to fix your new issues.

In no classpath and for your cases, JDT (our compiler) give us only a string typed `ProblemBinding` means "I don't know what it is, handles it by your own". I can try to parse the string and make the job of JDT but I don't know if we want that. 

@monperrus your opinion? :)

**Comment by worblehat** [comment]
I see. And I totally understand that handling all those cases in Spoon is probably not what you want to do. As long as no unexpected exceptions are thrown I would be happy if you just silently ignore them (or somehow log them to make them traceable).

A suggestion: Maybe you could maintain a documentation for the user with a list of known cases that cannot be properly handled in noclasspath-mode.

**Comment by monperrus** [comment]
> As long as no unexpected exceptions are thrown
This is the design goal.


> I would be happy if you just silently ignore them 
For us, ignoring means that they are instance of CtUnboundReference,
which makes them traceable.

**Comment by worblehat** [comment]
Sounds good!
