### ISSUE TITLE
[question] how to get all callees of the given method 

### ISSUE THREAD

**Issue by zqudm** [INRIA/spoon#5010]
I have two questions:

The first one is how to efficiently find the method given a signature, For example "org.eclipse.jdt.internal.compiler.lookup.TypeBinding.genericTypeSignature()".
Should we definitely scan all packages and all classes of the input project source code?

The second question is how to extract all called method  given a method.
For example, the following method code is given, i want to get the code of signature().

```
org.eclipse.jdt.internal.compiler.lookup.TypeBinding.genericTypeSignature() {
    return signature();
}
```
The more complext code is given as follows

```
org.eclipse.jdt.internal.compiler.flow.ConditionalFlowInfo.unconditionalInits()  {
    return initsWhenTrue.unconditionalInits().copy().mergedWith(initsWhenFalse.unconditionalInits());
}
```
Thanks

**Comment by I-Al-Istannen** [comment]
### 1
I think currently the easiest way to do this is to lookup the type using `Factory.Type().get("fully.qualified.name")` and then iterating over its methods and checking if `getSignature()` matches. You can get a factory using `getFactory()` on most spoon elements. This is not the most performant, but most types do not have that many methods. If it becomes a bottleneck you probably need to parse the signature yourself into a name and parameter list and then match against all methods of the type.


### 2
You can visit the method with a CtScanner:
```java
	@Test
	void foo2() {
		CtClass<?> ctClass = Launcher.parseClass("class Foo {" +
			"  public int answer() { return 42; }\n" +
			"  public void foo() {\n" +
			"    this.answer();\n" +
			"  }" +
			"}");
		CtMethod<?> method = ctClass.getMethodsByName("foo").get(0);
		method.getBody().accept(new CtScanner() {
			@Override
			public <T> void visitCtInvocation(CtInvocation<T> invocation) {
				System.out.println("Visited: " + invocation.getExecutable().getSignature());
				CtExecutable<T> executable = invocation.getExecutable().getExecutableDeclaration();
				// now you can look at the code of `executable` if you wish to.
				// might be null if it is not in the classpath
				super.visitCtInvocation(invocation);
			}
		});
	}
```

**Comment by zqudm** [comment]
thanks

**Comment by slarse** [comment]
@zqudm I'm closing this as the question seems answered, feel free to reopen if you disagree.
