### ISSUE TITLE
[Question] Is there a specific reason the CompilationUnit type exists?

### ISSUE THREAD

**Issue by raghav-deepsource** [INRIA/spoon#5039]
Compilation unit, defined in `spoon/reflect/cu/CompilationUnit.java` is marked as deprecated, is there any use for it within spoon code itself? I have tried removing it on my local branch and I don't see any effect on the operation of Spoon as such...

**Comment by raghav-deepsource** [comment]
is it kept around for backwards compatibility reasons?

**Comment by slarse** [comment]
Hi @raghav-deepsource,

Yes, it's there for backwards compatibility. There's some history about it that you can trace from #2702. In particular, see https://github.com/INRIA/spoon/pull/2702#issuecomment-431681355.
