### ISSUE TITLE
bootclasspath compiler option

### ISSUE THREAD

**Issue by mehdijk** [INRIA/spoon#505]
I need to use -bootclasspath option for SpoonCompiler.  How can I do that?
Thank you

**Comment by GerardPaligot** [comment]
Hi @mehdijk,

Do you talk about the bootclasspath argument in JDT? Because, we don't have this kind of argument in `SpoonCompiler`. You can specify [your classpath](https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/SpoonModelBuilder.java#L212) but not a specific classpath at the boot of the compilation.

**Comment by mehdijk** [comment]
Hi dear @GerardPaligot 
Yes. I have problem at the building model from old source codes. For example some interfaces in java.sql package are changed and when I compile them with spoon compiler it produces error that some methods were not implemented. is there a way to solve this problem?

**Comment by GerardPaligot** [comment]
What is the Java version used to write the old source codes?

**Comment by tdurieux** [comment]
Hi,

@GerardPaligot You probably don't want to know...

@mehdijk You can try these "easy" solutions

* The easiest way is to use the noclasspath mode but you will lose readability.
* You can change your JAVA HOME to use Java 6 (Spoon is compiled in Java 6)
* Change the Java compliance level of Spoon

**Comment by GerardPaligot** [comment]
> Change the Java compliance level of Spoon

This solution should be the best one.

**Comment by tdurieux** [comment]
Yes but that does not work for API change, which is the issue of mehdijk

**Comment by mehdijk** [comment]
@GerardPaligot  This source code uses Java 5
@tdurieux Yes I temporary have used noclasspath mode to continue my work
I use Spoon in eclipse and I think it uses eclipse compiler API and JAVA_HOME can not change the option. 
The compliance level option doesn't work in this situation.
Is there a way to add this option to Spoon compiler by extending some classes or ...

**Comment by tdurieux** [comment]
It's complicate because you need to add "--bootclaspth <value>" in args at this line: https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/support/compiler/jdt/JDTBasedSpoonCompiler.java#L212

By the way: you can change the JDK used by Eclipse in the project properties

**Comment by mehdijk** [comment]
Dear @tdurieux 
I checked also with JDK 6 and I was faced with the same error. I think my test-case  program class which uses java.sql  is only compatible with java 5. However I will try the difficult way. Thanks @tdurieux  and @GerardPaligot
