### ISSUE TITLE
NPE is noclasspath

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#506]
if you spoon the attached file in noclasspath there is an NPE with 5.0.0.
[TestBot.java.txt](https://github.com/INRIA/spoon/files/108312/TestBot.java.txt)

**Comment by GerardPaligot** [comment]
Not with 4.4.1?

**Comment by monperrus** [comment]
with 5.0.0. seems to be a regression.

**Comment by monperrus** [comment]
still an NPE with attached filed
[left_TestBot_1.48.java.txt](https://github.com/INRIA/spoon/files/111896/left_TestBot_1.48.java.txt)

**Comment by GerardPaligot** [comment]
@monperrus I don't have a NPE with the stable branch. The patch developed in my previous PR will come in the master branch as soon as the version 5.0.1 will be released.
