### ISSUE TITLE
[Bug]: Parsing vallid java files with package name containing $ symbol throws "Invalid package name" exception

### ISSUE THREAD

**Issue by rahulbhamre** [INRIA/spoon#5140]
### Describe the bug

While trying to parse a file having a package name containing $, the code throws an exception

"Invalid package name com.xxx.public$"

This is due to INNERTYPE_SEPARATOR being set as $ in CtType<T> interface. As this cannot be changed there is no way to parse a file with $ in the package name and the program crashes with the above mentioned exception.

Note package names with $ symbol are valid in java and I do not have control over the source files I am trying to parse. Is there any workaround to parse these files?

### Spoon Version

10.3.0

### JVM Version

17

### What operating system are you using?

Windows

**Comment by MartinWitt** [comment]
Hey,

This is an error in our implementation, you are correct. You can always disable JLS checks with `Environment#setIgnoreSyntaxErrors` (https://spoon.gforge.inria.fr/mvnsites/spoon-core/apidocs/spoon/compiler/Environment#setIgnoreSyntaxErrors(boolean)). I will create a fix for this soon.

**Comment by honghao12** [comment]
> Hey,
> 
> This is an error in our implementation, you are correct. You can always disable JLS checks with `Environment#setIgnoreSyntaxErrors` (https://spoon.gforge.inria.fr/mvnsites/spoon-core/apidocs/spoon/compiler/Environment#setIgnoreSyntaxErrors(boolean)). I will create a fix for this soon.

this setting of `setIgnoreSyntaxErrors(true) ` can't exclude this problem

![image](https://github.com/INRIA/spoon/assets/51260721/d07ac51c-fbd4-444f-b2b0-b729c59c4bdb)
![image](https://github.com/INRIA/spoon/assets/51260721/2fd51ada-7184-42d9-a4a6-2bc64dfac2e3)
![image](https://github.com/INRIA/spoon/assets/51260721/de5ab1b7-dd0e-43c6-88b8-f5184591beee)
![image](https://github.com/INRIA/spoon/assets/51260721/5a50f004-80d3-4be3-a4e0-9d7c9e2812db)
spoon version : 10.3.0  
window  jdk11
