### ISSUE TITLE
[Question] dependency graph building on JShell scripts

### ISSUE THREAD

**Issue by cyrilou242** [INRIA/spoon#5148]
Hey, thanks for the nice library.  I’m very new to spoon, I’d like to understand if it could be used for my little side project. 

  I’m working with [jshell](https://docs.oracle.com/javase/9/docs/api/jdk/jshell/package-summary.html) files `jsh`. 
   A jsh file contains a series of valid, invalid or incomplete java statements and comments.  Let’s say there are only valid statements. The jshell cli jshell reads a jsh file, and executes all statements in a top to bottom fashion.   A [JShell](https://docs.oracle.com/javase/9/docs/api/jdk/jshell/JShell.html) instance can evaluate statements. 
   I don’t think there are utils/support for jshell in spoon, and when a jsh file is executed by a JShell, the JShell execution environment will put everything in a single class, statement by statement:  
   So for instance this:  

```
      int x = 3;
  int r = x + 4;
```

Would be wrapped into something like this:  
```
class NotImportant() {
  int x = 3;
  int r = x + 4;
}
```

So let’s consider code is wrapped in a class like above.   From a Jshell file, I’d like to build a dependency graph between the different statement. 

For instance, a file
```
int a = 3;         // statement 1
int b = 0;         // statement 2
int c = a;         // statement 3
int d = a*10;      // statement 4
int e = b + 4;     // statement 5
```

Would be represented as a dependency graph: 
```
   1          2
  /  \        |
 3    4       5
```
 This should work for all valid statements (ie with class/enum declaration, with objects, etc…)
JShell.eval() can execute a statement.

Then, the jsh file can be updated.  When it is updated, I need to 
- Identify removed, added, edited statement nodes. For this I understand I can use gumtree and get back through parents to a jshell level statement.

Then statements that need to be (re-)computed should be computed, in top to bottom order.
 For instance; if 
 ```
  int b =0; 
   ```
   is changed to  int 
    ```
int    b = 1;
    ```
 then statements `2` then `5` should be executed.

Few questions:  
- does it look like Spoon can be used to solve this ? (I think yes :)) 
- is this a common use case, something already done before?  Will I have to build a custom Visitor to build the dependency graph or are there some higher level methods? I think I only need to do: for a given top level statement node, if in any subnode a ref to a top level node is found, then the top level depends node being visited depends on the other top level nodes.
- overall, does it sounds like a reasonable approach to build such dependency graph ? I could use an implementation like this one https://docs.oracle.com/middleware/1221/jdev/api-reference-esdk/oracle/javatools/util/DependencyGraph.html but maybe it’s possible to do everything on the CtModel directly? 
- any recommendation on the diffing? I understand gumtree spoon ast diff could work ? 

  It’s a bit involved and I need to do work on my side, but just want to make sure I’m choosing the good tool.
Thanks for reading through!

**Comment by I-Al-Istannen** [comment]
Hey,

sounds interesting :) Yes to the first, but I haven't really seen that before. I think building a dependency graph by grabbing all statements and then checking them for `CtLocalVariableReference`s is probably the easiest. It also depends a bit on how you want to handle block statements (i.e. `{whatever}`) and larger ones like `try`, `for` and so on.

You can use gumtree for an AST diff. I haven't used it myself, but from what I *heard* the API is supposed to be usable for mere mortals.

Something like this might be a starting point. It outputs a mermaid representation of your code:
```mermaid
stateDiagram-v2
  1: int a = 3
  4: int b = 0
  0: int c = a
  2: int d = a * 10
  3: int e = b + 4
  5: java.lang.System.out.println(e + d)
  0-->1
  2-->1
  3-->4
  5-->2
  5-->3
```

<details>

<summary>The code for this</summary>

```java
package analysable.pack;

import com.google.common.graph.EndpointPair;
import com.google.common.graph.GraphBuilder;
import com.google.common.graph.MutableGraph;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.junit.jupiter.api.Test;
import spoon.Launcher;
import spoon.reflect.code.CtLocalVariable;
import spoon.reflect.code.CtStatement;
import spoon.reflect.declaration.CtClass;
import spoon.reflect.declaration.CtMethod;
import spoon.reflect.reference.CtLocalVariableReference;
import spoon.reflect.visitor.CtScanner;
import spoon.support.compiler.VirtualFile;

public class DependenciesTest {

  @SuppressWarnings("UnstableApiUsage") // yes guava...
  @Test
  void foo() {
    Launcher launcher = new Launcher();
    launcher.getEnvironment().setComplianceLevel(17);
    launcher.getEnvironment().setNoClasspath(true);
    launcher.getEnvironment().setCommentEnabled(false);

    launcher.addInputResource(new VirtualFile(
        """
            class $Synthetic$ {
              public static void $synthetic$() {
                int a = 3;                  // statement 1
                int b = 0;                  // statement 2
                int c = a;                  // statement 3
                int d = a*10;               // statement 4
                int e = b + 4;              // statement 5
                System.out.println(e + d);  // statement 6
              }
            }
            """
    ));

    CtClass<?> ctClass = (CtClass<?>) launcher.buildModel().getAllTypes().iterator().next();
    CtMethod<?> method = ctClass.getMethod("$synthetic$");

    MutableGraph<CtStatement> dependencies = GraphBuilder.directed().allowsSelfLoops(false).build();
    Map<CtLocalVariable<?>, CtStatement> variablesToStatements = new HashMap<>();

    for (CtStatement statement : method.getBody().getStatements()) {
      dependencies.addNode(statement);
      statement.accept(new CtScanner() {
        @Override
        public <T> void visitCtLocalVariable(CtLocalVariable<T> localVariable) {
          super.visitCtLocalVariable(localVariable);
          variablesToStatements.put(localVariable, statement);
        }

        @Override
        public <T> void visitCtLocalVariableReference(CtLocalVariableReference<T> reference) {
          super.visitCtLocalVariableReference(reference);
          CtStatement source = Objects.requireNonNull(
              variablesToStatements.get(reference.getDeclaration())
          );
          dependencies.putEdge(statement, source);
        }
      });
    }

    StringBuilder mermaidEdges = new StringBuilder();
    Map<CtStatement, Integer> stateIds = new HashMap<>();
    for (EndpointPair<CtStatement> edge : dependencies.edges()) {
      Integer sourceId = stateIds.computeIfAbsent(edge.source(), ignored -> stateIds.size());
      Integer targetId = stateIds.computeIfAbsent(edge.target(), ignored -> stateIds.size());
      mermaidEdges
          .append(sourceId)
          .append("-->")
          .append(targetId)
          .append(System.lineSeparator());
    }

    System.out.println("stateDiagram-v2");
    for (CtStatement node : dependencies.nodes()) {
      String nodeLine = stateIds.computeIfAbsent(node, ignored -> stateIds.size()) + ": " + node;
      System.out.println(nodeLine.indent(2).stripTrailing());
    }

    System.out.println(mermaidEdges.toString().indent(2));
  }

}
```

</details>

Let me know if you have any questions :)

**Comment by cyrilou242** [comment]
Hey @I-Al-Istannen thanks! 
I got something similar but I didn't think of a mermaid viz, very cool! 

Indeed I'd like to support as much as possible of the grammar.
In particular I'd like to manage imports, function definitions, and "top-level expression"
```
int x = 3;

// out of order import
import java.util.List;

// method
List<String> aList(String s1, String s2) {
  return List.of(s1, s2);
}

// "top level expression" are interpreted in jshell
x;

```

I now think the jshell should be seen as a different syntax as java. 
In antlr4 this would mean smthing like: 
[java grammar](https://github.com/antlr/grammars-v4/blob/eb476b29a227bb56c63ab06be39c13b2be3fc270/java/java/JavaParser.g4) looks like: 
```
compilationUnit
    : packageDeclaration? importDeclaration* typeDeclaration*
    | moduleDeclaration EOF
    ;

typeDeclaration
    : classOrInterfaceModifier*
      (classDeclaration | enumDeclaration | interfaceDeclaration | annotationTypeDeclaration | recordDeclaration)
    | ';'
    ;
    
// and then other things inside class Declaration
```

whereas jshell is: 
```
compilationUnit
    : jshellSnippet*
    ;

jshellSnippet
    : importDeclaration
    | typeDeclaration
    | modifier* memberDeclaration
    | block
    | blockStatement
    ;
```

Is it complex to use a different grammar for spoon? 
The kotlin one looks a bit scary but for jshell it should be much simpler.
Given it's very close to the java grammar.

The other option is to build a class that spoon will be able to parse in a smarter way. 
Jshell provides JShell.sourceCodeAnalysis to help for this, I'll explore this.

**Comment by I-Al-Istannen** [comment]
> Is it complex to use a different grammar for spoon?

Yes. Spoon uses the eclipse java compiler to build its model, which does not understand what you are doing. It has error recovery, so it will probably still build a model — but I am not sure what it would look like. If you have your own language, you need to write your own model building code.
It is probably easier to keep around a CtClass and add class variables for variable statements, an (or multiple) auxiliary methods or non-static blocks for expressions, add imports for imports and methods for methods.

>  Jshell provides JShell.sourceCodeAnalysis to help for this, I'll explore this.

This provides a [`dependents`](https://docs.oracle.com/en/java/javase/17/docs/api/jdk.jshell/jdk/jshell/SourceCodeAnalysis.html#dependents(jdk.jshell.Snippet)) method, isn't that already what you want?

**Comment by cyrilou242** [comment]
Ok thanks, 

For the moment I have this, which is pretty nice: 
https://gist.github.com/cyrilou242/2449030c76e22dbf48ba16f9b5af03d0 

```mermaid
stateDiagram-v2
  1: int x = 3&#59
  0: double y = x&#59
  2: int r = x + 4&#59
  5: double p2(int x) {</br>    return x * x&#59</br>}
  3: double perR(int x) {</br>    return x * r&#59</br>}
  4: int z = p2(2) + perR(4)&#59
  8: class MyObj {</br>    int lol = 3&#59</br>}
  6: public Object synth10() {</br>    System.out.println(x)&#59</br>}
  7: MyObj obj = new MyObj()&#59
  12: List<?> noway = List.of(3)&#59
  9: public Object synth13() {</br>    for (int i = 0&#59 i < 4&#59 i++) {</br>        int x = i + 1&#59</br>        System.out.println(x + r)&#59</br>    }</br>}
  10: public Object synth14() {</br>    x = $missing$&#59</br>}
  13: public Object synth16() {</br>    MyObj.class = $missing$&#59</br>}
  11: int haha = obj.lol + 4&#59
  0-->1
  2-->1
  3-->2
  4-->3
  4-->5
  6-->1
  7-->8
  9-->2
  10-->1
  11-->7
```

Somehow the link between those 2 snippets
```
class MyObj() {...}
MyObj.class;
```

is not resolved, I'm not sure to understand why yet. May be it's caused by the incomplete implem of the CtScanner.

For edits and diffing I think I can now manage this by keeping a set of CtTypeMember, and at each edits I can compare the old set and the new set to see what changed. I don't really need a full tree diff.

Overall I think my question is solved :) 
Thanks a lot for your help!

**Comment by cyrilou242** [comment]
> This provides a [dependents](https://docs.oracle.com/en/java/javase/17/docs/api/jdk.jshell/jdk/jshell/SourceCodeAnalysis.html#dependents(jdk.jshell.Snippet)) method, isn't that already what you want?

it's something else, the definition of "which might need updating if the given Snippet is updated" is different and related to out of order capabilities of jshell. 
It allows to define methods/class that use methods/class that are not defined yet, and tracks changes for this. But it only does this.

Eg of not working:
```
JShell sh = JShell.create();
jshell> var s1 = sh.eval("int x = 3;")
s1 ==> [SnippetEvent(snippet=Snippet:VariableKey(x)#1-in ... iableKey(x)#1-int x = 3;)]

jshell> var s2 = sh.eval("System.out.println(x);")
3
s2 ==> [SnippetEvent(snippet=Snippet:StatementKey#4-Syst ... e,causeSnippetnullvalue=)]

jshell> sh.sourceCodeAnalysis().dependents(s1.get(0).snippet());
$20 ==> []

jshell> sh.sourceCodeAnalysis().dependents(s2.get(0).snippet());
$21 ==> []
```

**Comment by I-Al-Istannen** [comment]
> it's something else

Ah, sad :/


> class MyObj() {...}
MyObj.class;

You are exploring the limits of the JDT error recovery, your whole input is bascially a single semantical error. I am honestly surprised it is good enough to almost work with it here.

The problem you have is because your generated class in that place is slightly *too broken* though. Using this patch
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/20284688/229095438-18ab73ce-e41e-4e39-b3df-29a0ca5ac7b5.png">

I get
```mermaid
stateDiagram-v2
  1: int x = 3&#59
  0: double y = x&#59
  2: int r = x + 4&#59
  5: double p2(int x) {</br>    return x * x&#59</br>}
  3: double perR(int x) {</br>    return x * r&#59</br>}
  4: double z = p2(2) + perR(4)&#59
  8: class MyObj {</br>    int lol = 3&#59</br>}
  6: public Object synth10() {</br>    var $reserved$ = System.out.println(x)&#59</br>}
  7: MyObj obj = new MyObj()&#59
  13: List<?> noway = List.of(3)&#59
  9: public Object synth13() {</br>    for (int i = 0&#59 i < 4&#59 i++) {</br>        int x = i + 1&#59</br>        System.out.println(x + r)&#59</br>    }</br>}
  10: public Object synth14() {</br>    var $reserved$ = x&#59</br>}
  11: public Object synth16() {</br>    var $reserved$ = A.MyObj.class&#59</br>}
  12: int haha = obj.lol + 4&#59
  0-->1
  2-->1
  3-->2
  4-->3
  4-->5
  6-->1
  7-->8
  9-->2
  10-->1
  11-->8
  12-->7
```

This probably happens because `MyObj.class = whatever` is complete garbage and JDT refuses to interpret `MyObj` as the class here. Changing that to `var whatever = MyObj.class` (as expressions always produce values) placates it.

It is a bit weird though that Jshell thinks the println is an expression, but JDT can work with that apparently.

----

I also would recommend using the Launcher + virtual file API I showed in my previous example. `Launcher.parseClass` uses the default language level of `8` — not quite what you want.

**Comment by cyrilou242** [comment]
Hey @I-Al-Istannen, thanks for all your help! 


> You are exploring the limits of JDT error recovery, your whole input is bascially a single semantical error. I am honestly surprised it is good enough to almost work with it here.

I'm also pretty surprised and I end up with a lot of String manipulation. But it's fine, it's still less work than building a grammar and all tools on top of it. 

I incorporated all your feedbacks. 

For my edit use case,
`toString` on the `CtTypeMember`s works well as a hash key to find which snippet is new and which is not. So I don't need a full tree-diff.
I now have a system than can evaluate a jshell script, and partially re-evaluate it when it is updated, always ensuring in-order evaluation. Similar to what [Clerk](https://github.com/nextjournal/clerk) does in Clojure.
Will share once it's ready if you're interested.

Thanks again!

**Comment by I-Al-Istannen** [comment]
> So I don't need a full tree-diff.
> I now have a system than can evaluate a jshell script, and partially re-evaluate it when it is updated, always ensuring in order evaluation.

Nice!

>  Will share once it's ready if you're interested.

Please do! Sounds cool :)

**Comment by cyrilou242** [comment]
Hey @I-Al-Istannen, took me some time but I think the project is ready enough to be shared :)  
https://jnotebook.catheu.tech/
https://github.com/cyrilou242/jnotebook

**Comment by cyrilou242** [comment]
@I-Al-Istannen 
Thanks for the feedback, I guess the project was not ready enough then x) 

> It did not recognize the hello_world.jsh it created (even after touching it), which made for a slightly confusing onboarding experience.
The `hello_world.jsh` is created before the file watch is setup. 
`touch` won't trigger a reload, the system looks at "real" changes in the file text. This is because some OS and some IDEs have weird behaviours in how they edit metadata of a file, and I want to avoid refreshing results when it's not necessary. 
Understand it's confusing though, I'll think about this.

I'm planning to add a list of files in the welcome screen. Clicking on a file will trigger the rendering it will make things easier. I think it'll solve the hello_world.jsh use case.
