### ISSUE TITLE
having immutable CtTypeRef

### ISSUE THREAD

**Issue by GerardPaligot** [INRIA/spoon#521]
remove field declaringType and setDeclaringType
remove field package and setPackage

introduce qualification?

doc/contract of CtTypeRef.getQualifiedName

**Comment by GerardPaligot** [comment]
I worked on this issue. The idea behind is good but there is a big problem with generics.

For now, when we write this:

```java
my.package.A<String>.B<String>
```

We have a `CtTypeReference` named B with one actual type argument and a declaring type with another actual type argument. If we remove the `declaringType` field and compute it each time we call `getDeclaringType` with this algorithm:

```java
@Override
public CtTypeReference<?> getDeclaringType() {
	if (CtTypeReference.NULL_TYPE_NAME.equals(getSimpleName())) {
		return null;
	}
	final CtType<T> declaration = getDeclaration();
	// Spoon.
	if (declaration != null) {
		if (declaration.isTopLevel()) {
			return null;
		}
		return declaration.getParent(CtType.class).getReference();
	}
	// Runtime.
	final Class<T> actualClass = getActualClass();
	if (actualClass != null) {
		return getFactory().Type().createReference(actualClass.getEnclosingClass());
	}
	// No classpath.
	return null;
}
```

We can't get the actual type arguments of the declaring type. This information is available only in JDTTreeBuilder when we build the reference.

**Comment by monperrus** [comment]
hum, you're right. Adieu immutability :-(
