### ISSUE TITLE
[Bug]: Fix warnings when using the Spoon Maven plugin

### ISSUE THREAD

**Issue by vmassol** [INRIA/spoon#5217]
### Describe the bug

Maven reports the following problems:

```
[WARNING] Plugin validation issues were detected in 4 plugin(s)
[WARNING] 
[WARNING]  * fr.inria.gforge.spoon:spoon-maven-plugin:3.5
...
[WARNING]   Plugin issue(s):
[WARNING]    * Plugin is a Maven 2.x plugin, which will be not supported in Maven 4.x
[WARNING]    * Plugin mixes multiple Maven versions: [3.8.2, 3.3.9, 2.2.1]
[WARNING]    * Plugin should declare these Maven artifacts in `provided` scope: [org.apache.maven:maven-settings-builder:3.3.9, org.apache.maven:maven-repository-metadata:3.3.9, org.apache.maven:maven-artifact:3.3.9, org.apache.maven:maven-builder-support:3.3.9, org.apache.maven:maven-plugin-api:3.8.2, org.apache.maven:maven-core:3.3.9, org.apache.maven:maven-aether-provider:3.3.9, org.apache.maven:maven-settings:3.3.9, org.apache.maven:maven-model-builder:3.3.9, org.apache.maven:maven-model:3.3.9]
[WARNING]    * Plugin depends on plexus-container-default, which is EOL
```

### Spoon Version

core: 10.3.0
maven plugin version: 3.5

### JVM Version

11

### What operating system are you using?

MacOS

**Comment by monperrus** [comment]
thanks for the report @vmassol

**Comment by yogyagamage** [comment]
FYI I'm working on this.

**Comment by vmassol** [comment]
@yogyagamage I got it with Maven 3.9.2 and executing maven with `-Dmaven.plugin.validation=verbose`. See https://maven.apache.org/docs/3.9.2/release-notes.html

**Comment by monperrus** [comment]
FYI, this will be fixed by #5274

**Comment by monperrus** [comment]
@vmassol we have a new release, 3.6 
https://central.sonatype.com/artifact/fr.inria.gforge.spoon/spoon-maven-plugin/3.6

let us know if it works for you

**Comment by vmassol** [comment]
We have upgraded to 3.6 a few days ago but I've just checked now and indeed, I don't see spoon in the list of plugins with warnings anymore, thanks!
