### ISSUE TITLE
option --compile does not support compliance level 

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#524]
if you use --compile and --compliance-level 6 within a JDK 8, the resulting bytecode does not run in JDK6.

should  --compliance-level also specify the resulting bytecode or do we introduce another option?
(at least it should be clearly documented)

**Comment by GerardPaligot** [comment]
From my opinion, that should be an issue on the bug tracker of JDT.

**Comment by monperrus** [comment]
after discussion with Vincenzo, closing
