### ISSUE TITLE
[Bug]: Several tags of the spoon-maven-plugin seem broken

### ISSUE THREAD

**Issue by tmortagne** [INRIA/spoon#5246]
### Describe the bug

3.5 and 3.4.1 tags at https://github.com/SpoonLabs/spoon-maven-plugin contains "3.5-SNAPSHOT" as version instead of the expected released version:
*  https://github.com/SpoonLabs/spoon-maven-plugin/blob/spoon-maven-plugin-3.4.1/pom.xml#L14
* https://github.com/SpoonLabs/spoon-maven-plugin/blob/spoon-maven-plugin-3.5/pom.xml#L14

Also, there is no tag at all for the 3.4.2 version available on Maven central.

### Spoon Version

3.5

### JVM Version

11

### What operating system are you using?

Ubuntu Linux

**Comment by monperrus** [comment]
will be fixed in #5302 , so closing this one.

thanks @tmortagne for the report
