### ISSUE TITLE
renovate should automerge spoon-maven-plugin

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#5247]
renovate should automerge spoon-maven-plugin

cc/ @yogyagamage

**Comment by MartinWitt** [comment]
According to the config it should automerge them already. Maybe you need to rebase the old pull requests before we copied the config from spoon to there. See https://github.com/SpoonLabs/spoon-maven-plugin/pull/121.

**Comment by MartinWitt** [comment]
We don't automerge major dependencies updates automatic for spoon. We could enable it for spoon-maven-plugin. We decided against it for spoon.

**Comment by yogyagamage** [comment]
Renovate do automerge now (https://github.com/SpoonLabs/spoon-maven-plugin/pull/125) except for major version updates. It seems that, previously automerge did not happen because there were no checks.

**Comment by monperrus** [comment]
thanks
