### ISSUE TITLE
Inject source code from jar

### ISSUE THREAD

**Issue by maxcleme** [INRIA/spoon#525]
Hi,

I currently working on a project with Spoon.

During the workflow of my application, I have to inject one of my package inside the instrumented project. Everything is working well when I'm working inside my IDE. In order to inject my package, I simply had the source folder  as input source folder to the Spoon Launcher, then the prettyprinter add them to the output folder.

However, when I build the jar of my application, even if I put sources into it, how can I pass them to spoon ?

**Comment by tdurieux** [comment]
I think that you can do something like this
```Java
launcher.getCompiler().addInputSource(new ZipFolder(new File("path to the jar that contains the sources")));
```

**Comment by maxcleme** [comment]
Hi @tdurieux ,

Will try this tonight, I keep you in touch.

**Comment by maxcleme** [comment]
Work pretty well, thank you.
