### ISSUE TITLE
release Spoon 10.4.0

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#5257]
FYI, we're trying the new release pipeline now, see #3890

**Comment by MartinWitt** [comment]
Okay next fix should be #5263. I'm not certain why we have this plugin, maybe for the beta releases? JReleaser handles the signing by itself, but lets see.

**Comment by MartinWitt** [comment]
Okay the next problem with the GPG plugin is that we have to pass the name of the envvar for the password and not the password itself, see https://stackoverflow.com/questions/74909075/unable-to-decrypt-gpg-passphrase-with-org-apache-maven-pluginsmaven-gpg-plugin.

> gpgPassphrase should be the name of the env var that is going to contain the GPG passphrase and in the release/deploy stages you need to include that formerly mentioned env var in the env section, and set its value (in your case the secrets.MAVEN_GPG_PASSPHRASE).

**Comment by monperrus** [comment]
Next run is https://github.com/INRIA/spoon/actions/runs/5256363593

**Comment by MartinWitt** [comment]
As an update the FF-merge works for maven-lockfile now. Time to part all knowledge to our spoon script. <https://github.com/chains-project/maven-lockfile/blob/main/.github/workflows/jreleaser.yml>

**Comment by MartinWitt** [comment]
https://github.com/INRIA/spoon/pull/5279 this is the next step in the CD release fixing.

**Comment by MartinWitt** [comment]
Related #5272.

**Comment by MartinWitt** [comment]
> Error:  Failed to execute goal org.sonatype.plugins:nexus-staging-maven-plugin:1.6.13:deploy (injected-nexus-deploy) on project spoon-core: Execution injected-nexus-deploy of goal org.sonatype.plugins:nexus-staging-maven-plugin:1.6.13:deploy failed: Server credentials with ID "ossrh" not found! -> [Help 1]

Okay progress, we somehow have a second deploy plugin in the spoon parent pom see error message. We can just skip this or remove this plugin even.

**Comment by MartinWitt** [comment]
Okay partial success. Spoon 10.4.0, the parent and javadoc is now on maven-central. We also have tag and a commit on the master. But the master is currently red. The changelog generation searched for a tag in the same format and didn't found any. As a result there was a changelog from the start of spoon. This changelog was too large for the release.

I finished the release process manually (creating a GitHub release, update to 10.4.1-SNAPSHOT and FF-merge master).

**Comment by monperrus** [comment]
good progress on this important item, thanks @MartinWitt

**Comment by monperrus** [comment]
see https://github.com/INRIA/spoon/releases/tag/v10.4.0 thanks @MartinWitt
