### ISSUE TITLE
[Question]- What's the difference between Launcher and MavenLauncher?

### ISSUE THREAD

**Issue by honghao12** [INRIA/spoon#5266]
Through MavenLauncher parsing, it is not possible to parse the type that uses another module

**Source code you are trying to analyze/transform：**
![image](https://github.com/INRIA/spoon/assets/51260721/bed6c63f-75b4-48ca-99b1-840fb698e1d4)

`module demo1`
```
package p1;

import p2.DemoClassT2;

public class DemoClass1 {
    public void fun(){
        DemoClassT2 demoClass2 = new DemoClassT2();
        String s = demoClass2.fun1();
    }
}
```

`module demo2`
```
package p2;

public class DemoClassT2 {
    public String fun1(){
        return "123";
    }
}
```

**Source code for your Spoon processing**
```
  Launcher launcher = new Launcher();
  launcher.getEnvironment().setComplianceLevel(11);
  launcher.getEnvironment().setAutoImports(true);
  launcher.getEnvironment().setIgnoreDuplicateDeclarations(true);
  launcher.addInputResource("./javademo/demo1");
  model = launcher.buildModel();
  int typeNum = model.getAllTypes().size();
```
expect:
```
size:  1
```
actual:
```
size:  1
```

```
       MavenLauncher mavenLauncher = new MavenLauncher("./javademo/demo1", 
       MavenLauncher.SOURCE_TYPE.APP_SOURCE);
        mavenLauncher.getEnvironment().setNoClasspath(true);
        mavenLauncher.getEnvironment().setComplianceLevel(11);
        mavenLauncher.getEnvironment().setAutoImports(true);
        mavenLauncher.getEnvironment().setIgnoreDuplicateDeclarations(true);
        model = mavenLauncher.buildModel();
        int typeNum = model.getAllTypes().size();
```
expect:
```
size:  2
```
actual:
```
size:  1
```
The DemoClassT2 of the module demo2 was not resolved using MavenLauncher

**Comment by MartinWitt** [comment]
Hey,

the launcher builds a model best effort for a given folder containing java files.
The goal of the `MavenLauncher` is to build a model best effort thanks to maven. It resolves the complete classpath with maven commands. Can you push your example to a github repository so we can have a look. My current guess it that is a snapshot version in demo2 and not installed with `maven install`

**Comment by honghao12** [comment]
> Hey,
> 
> the launcher builds a model best effort for a given folder containing java files. The goal of the `MavenLauncher` is to build a model best effort thanks to maven. It resolves the complete classpath with maven commands. Can you push your example to a github repository so we can have a look. My current guess it that is a snapshot version in demo2 and not installed with `maven install`

Thanks for your answer,this is my github repository`https://github.com/honghao12/javademo`

**Comment by I-Al-Istannen** [comment]
> The DemoClassT2 of the module demo2 was not resolved using MavenLauncher

There are a few problems:
- Your parent pom does not exist, so the build fails (unless you `mvn install`ed it before)
- demo01 has a dependency on demo02, but this is not a reactor build so it will not find the dependency (unless you `mvn install`ed it before)
- `MavenLauncher` fetches all dependencies and puts them on the *classpath*, so they can be used for the *shadow* model. They will never be part of the built source-code model. This would not be feasible, as most dependencies are only shipped as pre-compiled jar files.

Feel free to re-open, if you have any questions :)
