### ISSUE TITLE
[Bug]: spoon-pom not updated in maven-central

### ISSUE THREAD

**Issue by egore** [INRIA/spoon#5272]
### Describe the bug

Right now the spoon-pom 1.0 release in [maven-central](https://search.maven.org/search?q=a%3Aspoon-pom) is from 26-Nov-2018. The version in git is much more recent but the version number is still 1.0 and it is not published to maven-central.

Please create a new release for spoon-pom and make spoon-core use the new version.

Also I'd suggest to use the maven-release-plugin for spoon-pom, too. This way the version published to maven-central matches a tagged version in the git repository.

**Comment by MartinWitt** [comment]
Hey,

thank you for the bug report. We are currently working on a new CD solution and will publish updated versions of the spoon-parent too. It should be fixed soonish.

**Comment by MartinWitt** [comment]
Hey we had a new release and the parent is now on maven central with the new version.
