### ISSUE TITLE
Dropping java 11 support

### ISSUE THREAD

**Issue by MartinWitt** [INRIA/spoon#5280]
As JDT moved to java 17 #5268 we also need to move. Our current migration plan is to make the 10.4 release soon, when the CD script works. Then we start working on the java 20/21 features on a different branch. On this branch, we also start the cleanup we need to do while dropping java 11. Then there will be a last spoon release with 10.5(?). Merging the java20/21 branch will result in the first spoon release for JDK 17+. Spoon **can still** analyze older source code. As a user, you only need a newer java version. There will be no back porting of fixes to older java 11 releases.

**Comment by monperrus** [comment]
OK with the plan, we are married to JDT anyway.

**Comment by MartinWitt** [comment]
Next step is to create a branch called java17 which is a valid PR target for the meantime. We will start working there for all the upgrade we need to do for this switch.

**Comment by MartinWitt** [comment]
Java 11 support is now dropped in the latest Spoon 11 release.
