### ISSUE TITLE
Broken output with Gradle parallel build of a multi module project

### ISSUE THREAD

**Issue by mictaege** [INRIA/spoon#5321]
### Describe the bug

Using Spoon in a gradle multi module project leads sometimes to broken output if the gradle build is run in parallel.

If the gradle build is run in no-parallel mode everthing works fine, but if the build is run in parallel some pieces of source code from one module (red) are mixed into the output of another module (green). 

![grafik](https://github.com/INRIA/spoon/assets/4046390/e17a326d-54ea-405f-b48f-405dc5bfb4a5)

As a result the build fails with a compiler error since the output is not a valid Java source.

This error doesn't always happen, only occasionally, with different sources and when the build takes longer than a minute.

### Spoon Version

10.1.0

### JVM Version

openjdk 11.0.12 2021-07-20

### What operating system are you using?

Linux/Mac

**Comment by MartinWitt** [comment]
Hey,

The sad reality is spoon isn't really designed with parallel usage in mind. As reproduction with Gradle is difficult, could you provide a smaller reproduction? Maybe we can fix this with https://github.com/openjdk/jcstress. What kind of printing do you use? The default or sniper printing?

**Comment by mictaege** [comment]
> Hey,
> 
> The sad reality is spoon isn't really designed with parallel usage in mind. As reproduction with Gradle is difficult, could you provide a smaller reproduction? Maybe we can fix this with https://github.com/openjdk/jcstress. What kind of printing do you use? The default or sniper printing?

Hi Martin,

It may not be easy to provide a reproducer, but I'll give it a try. However, this will probably take some time. I will then report back.

Best regards, Michael

**Comment by mictaege** [comment]
> Hey,
> 
> The sad reality is spoon isn't really designed with parallel usage in mind. As reproduction with Gradle is difficult, could you provide a smaller reproduction? Maybe we can fix this with https://github.com/openjdk/jcstress. What kind of printing do you use? The default or sniper printing?

Hi Martin,

when I started to create a reproducer I figured out what went wrong. Also your hint with the printing was very helpful.

In the Gradle build scripts I do create a `Launcher` and then configure the printing like this.

```Groovy
launcher.environment.setPrettyPrinterCreator {
    PrettyPrinterCreator.createPrettyPrinter(launcher.environment)
}
```

```Java
public class PrettyPrinterCreator {

    private static DefaultJavaPrettyPrinter printer;

    public static PrettyPrinter createPrettyPrinter(final Environment environment) {
        if (printer == null) {
            final DefaultJavaPrettyPrinter printer = new DefaultJavaPrettyPrinter(environment);
            ...
        }
        return printer;
    }
}
```
The problem was that the `DefaultJavaPrettyPrinter` has been created as a singleton and is not thread safe by itself.

In a Gradle multi module project a new launcher is created for each module and therefore all launchers shared the same printer instance. Therefore when running in parallel, the printer got confused.

Simply changing the creation of the `Default Java PrettyPrinter` as follows did the trick for me.

```Java
public class PrettyPrinterCreator {

    public static PrettyPrinter createPrettyPrinter(final Environment environment) {
        final DefaultJavaPrettyPrinter printer = new DefaultJavaPrettyPrinter(environment);
        ...
        return printer;
    }
}
```
So in my opinion this ticket could be closed, as the `DefaultJavaPrettyPrinter` doesn't need to be thread-safe necessarily.

Best regards, Michael
