### ISSUE TITLE
What is a `CtReference`? Should be explained in the documentation.

### ISSUE THREAD

**Issue by Luro02** [INRIA/spoon#5338]
Suppose I search for all direct references to a variable in the model:
```java
CtModel ctModel = /* ... */;
CtVariable<?> ctVariable = /* ... */;

System.out.println(ctModel.getElements(new DirectReferenceFilter<>(ctVariable.getReference())));
```
what would I get?

I assumed that I would obtain all uses of the variable in the code, but this is not the case:
```java
import java.util.ArrayList;

public class Graph {
    private ArrayList<String> root;

    public String getRoot() {
        return this.root.get(0);
    }
}
```
Querying for all references of the `root` field only returns a reference for the field declaration, but not the method invocation.
<details>
  <summary>Reproducer</summary>

  ```java
import spoon.Launcher;
import spoon.reflect.CtModel;
import spoon.reflect.declaration.CtField;
import spoon.reflect.declaration.CtVariable;
import spoon.reflect.reference.CtReference;
import spoon.reflect.visitor.filter.DirectReferenceFilter;
import spoon.reflect.visitor.filter.TypeFilter;
import spoon.support.compiler.VirtualFile;

import java.util.List;

public final class Main2 {
    private Main2() {
    }

    private static CtModel createModel() {
        Launcher launcher = new Launcher();

        launcher.getEnvironment().setComplianceLevel(17);

        launcher.addInputResource(new VirtualFile("""
            import java.util.ArrayList;

            public class Graph {
                private ArrayList<String> root;
                        
                public String getRoot() {
                    return this.root.get(0);
                }
            }
            """));

        return launcher.buildModel();
    }

    private static void run() {
        CtModel ctModel = createModel();

        CtVariable<?> ctVariable = ctModel.getElements(new TypeFilter<CtField<?>>(CtField.class))
            .stream()
            .filter(ctField -> ctField.getSimpleName().equals("root"))
            .findAny()
            .orElseThrow();

        CtReference thisReference = ctVariable.getReference();
        List<CtReference> ctReferences = ctModel.getElements(new DirectReferenceFilter<>(thisReference));

        for (CtReference ctReference : ctReferences) {
            System.out.println(ctReference);
        }
    }

    public static void main(String[] args) {
        run();
    }
}
  ```
</details>

Because of the above I noticed that a reference is not what I thought it is. The documentation is not helpful: [`CtReference`](https://spoon.gforge.inria.fr/mvnsites/spoon-core/apidocs/spoon/reflect/reference/CtReference.html), [`CtVariable`](https://spoon.gforge.inria.fr/mvnsites/spoon-core/apidocs/spoon/reflect/reference/CtVariableReference.html)

Next question would be what a "direct" reference is and what an indirect would be? Should be part of the documentation for [`DirectReferenceFilter`](https://spoon.gforge.inria.fr/mvnsites/spoon-core/apidocs/spoon/reflect/visitor/filter/DirectReferenceFilter.html).

**Comment by MartinWitt** [comment]
Hey,

A `CtReference` is simple a root interface, and you should only use the subtypes of `CtReference`. You could compare `CtReference` to `Object`. The filter simply checks if the references are equal. But for a given CtVariable there are different kinds of references, so the filter does not work for your usecase.
