### ISSUE TITLE
Failed to read artifact descriptor for Spoon 10.4.1-SNAPSHOT

### ISSUE THREAD

**Issue by seintur** [INRIA/spoon#5340]
Dear all,

Since 10.4.1-SNAHPSHOT my projects that use Spoon fail with 

Failed to read artifact descriptor for fr.inria.gforge.spoon:spoon-core:jar:10.4.1-SNAPSHOT: Failure to find fr.inria.gforge.spoon:spoon-pom:pom:10.4.1-SNAPSHOT in https://repository.ow2.org/nexus/content/repositories/snapshots/ was cached in the local repository, resolution will not be reattempted until the update interval of [ow2.org](http://ow2.org/)-snapshot has elapsed or updates are forced

For those with access to the Spoon Inria CI server, basically all projects are down with this issue.

Are we missing something? Or is it related to the (new?) way the snapshot is deployed?

Thanks,
Lionel.

**Comment by MartinWitt** [comment]
Hey,

yeah sorry we upgraded/changed our CI script and did some testing with snapshot releases. I wasn't aware these are used in production. I will make a new snapshot release which resolves this issue.

**Comment by seintur** [comment]
Good for me, thanks.

**Comment by seintur** [comment]
Hi,

Sorry for reopening the issue, I though it was ok, but it is not.

The deployed snapshot on https://repository.ow2.org/nexus/content/repositories/snapshots/fr/inria/gforge/spoon/spoon-core/10.4.1-SNAPSHOT/spoon-core-10.4.1-20230812.224327-77.pom refers to the parent artifact

<parent>
<groupId>fr.inria.gforge.spoon</groupId>
<artifactId>spoon-pom</artifactId>
<version>10.4.1-SNAPSHOT</version>
<relativePath>spoon-pom</relativePath>
</parent>

Unless I am missing something there is not such fr.inria.gforge.spoon:spoom-pom:10.4.1-SNAPSHOT deployed. The maven resolution fails on this.

Thanks,
Lionel.

PS: this is not that I am using "in production". I am running a project that uses Spoon with the latest snapshot to ensure that it is still running with the latest snapshot.

**Comment by monperrus** [comment]
There are different options:
- set up snapshot CD for `spoon-parent`
- ensuring that spoon-core does not depend on snapshots, that's  #5395
- removing the parent, that's #5397

**Comment by monperrus** [comment]
@MartinWitt says that the parent pom snapshot will be CDed and deployed to https://oss.sonatype.org/content/repositories/snapshots/fr/inria/gforge/spoon/spoon-pom/ once #5394 is merged

**Comment by monperrus** [comment]
@seintur the fix is to change the snapshot repo, see https://github.com/SpoonLabs/npefix/commit/b8b2e6e34f137e387a9c827225766796f6c6bbb2

**Comment by seintur** [comment]
Good, thanks Martin, it works for me. I am closing the issue.
