### ISSUE TITLE
[Question]: Is there a way to set the character encoding of processed source code?

### ISSUE THREAD

**Issue by tenax66** [INRIA/spoon#5343]
When processing source code as follows, the character encoding of output files depends on the environment.

```java
Launcher l = new Launcher();
l.addInputResource("src/main/java");
l.run();
```

For example, when working in Windows (Japanese setting), the encoding of processed source code is [CP932](https://en.wikipedia.org/wiki/Code_page_932_(Microsoft_Windows)), I wanted UTF-8 code though.
Is there any simple way to set the encoding of processed source code?

In the case above, I created my own FileGenerator (which outputs files in UTF-8)  from `JavaOutputProcessor` and set it to `Environment` as a work-around. like the following:

```java
l.getEnvironment().setDefaultFileGenerator(new SomeUTF8OutputProcessor());
```

But I don't think this is a good approach.

**Comment by MartinWitt** [comment]
Hey, 

have you tried using https://spoon.gforge.inria.fr/mvnsites/spoon-core/apidocs/spoon/compiler/Environment.html#setEncoding(java.nio.charset.Charset) to set the charset?

**Comment by tenax66** [comment]
Yes, I tried `Environment.setEncoding(StandardCharsets.UTF_8)`.
But it only set the encoding of source code that spoon parses, not the output.

**Comment by MartinWitt** [comment]
Oh, you are correct. It looks like we have no API, or I am not aware of any method for this use case. Your solution might be the correct one.
