### ISSUE TITLE
[Question]: what should i do when this situation

### ISSUE THREAD

**Issue by sretake** [INRIA/spoon#5345]
### Describe the bug

![image](https://github.com/INRIA/spoon/assets/44957231/ff18e829-abb8-4ccf-a26a-a5a4df55cf56)
![image](https://github.com/INRIA/spoon/assets/44957231/f00ebb09-032f-4f97-8c61-fddc210a010e)

### Spoon Version

10.3.0

### JVM Version

11

### What operating system are you using?

windows

**Comment by MartinWitt** [comment]
Hey, thank you for the bug report. Could you provide more context or a reproduction unit test for your issue? Otherwise it is hard to debug.

**Comment by sretake** [comment]
Perhaps it is because we cannot use the getPath method when it comes to basic data types,like int ,boolean
![image](https://github.com/INRIA/spoon/assets/44957231/f6d5ac9f-77ed-4a30-87e8-46ec6a8d8101)
