### ISSUE TITLE
`CtUnaryOperator`s `getOperand` and `setOperand` should return/set `CtExpression<?>`

### ISSUE THREAD

**Issue by Luro02** [INRIA/spoon#5349]
The `setOperand` method of a `CtUnaryOperator<T>` requires that a `CtExpression<T>` is passed.

This is confusing, because one can for example write this:
```java
short s = (short) 1;
int i = ~s;
```
Here `~s` is `CtUnaryOperator<Integer>`, but the operand `s` is a `CtExpression<Short>`.

Except for being confusing, this does not result in code crashing, because generics are erased at runtime.

For example this test-case shows that the types are really `Integer` for the `CtUnaryOperator` and `Short` for the operand:
```java
class Example {
    @Test
    void testsCtUnaryOperatorExpressionType() {
        CtUnaryOperator<Integer> ctUnaryOperator = Launcher.parseClass(
            "public class Test { public void f() { short s = (short) 1; int i = ~s; } }"
        ).getElements(new TypeFilter<CtUnaryOperator<Integer>>(CtUnaryOperator.class)).get(0);

        assertEquals(
            ctUnaryOperator.getFactory().Type().INTEGER_PRIMITIVE,
            ctUnaryOperator.getType()
        );

        assertEquals(
            ctUnaryOperator.getFactory().Type().SHORT_PRIMITIVE,
            ctUnaryOperator.getOperand().getType()
        );
    }
}
```
and IntelliJ marks the `assertEquals` as problematic, because the generics are differing:
![image](https://github.com/INRIA/spoon/assets/24826124/43dc6d22-680b-4618-bd17-5c0a59d52ffe)

One should note that for `CtBinaryOperator` a `CtExpression<?>` is returned and set (which is correct).
[See here](https://spoon.gforge.inria.fr/mvnsites/spoon-core/apidocs/spoon/reflect/code/CtBinaryOperator.html#setLeftHandOperand(spoon.reflect.code.CtExpression))

**Comment by MartinWitt** [comment]
Hey,

could you provide a pull request and see if some test case breaks?

**Comment by I-Al-Istannen** [comment]
This breaks source compatibility for `getOperand`, but binary compatibility should be preserved. That breakage is likely acceptable though and does not occur in spoon-core. I would imagine that it is assigned to `CtExpression<?>` or a rawtype most of the time, but I don't know, of course.
