### ISSUE TITLE
[QUESTION] How does Spoon rank on the hacky scale?

### ISSUE THREAD

**Issue by Mechite** [INRIA/spoon#5364]
This is a pretty simple question but could also demonstrate that I haven't actually tried building anything with Spoon yet (I was hoping for some kind of community chat but it seems like this is the intended support mechanism).

- Can Spoon literally transform code, e.g. the way Lombok does
- Does this rely on any compiler hacks
- Is there any way to do crazy stuff and make IDEs support it? e.g. if I made my own version of the Lombok `@Getter` with Spoon, how could I not display an error for method calls, get tab-completion etc.

**Comment by MartinWitt** [comment]
As all the questions are somewhat related, I answer them in a single paragraph:

Spoon transform `.java` and can do the same transformations as lombok does. Generating and printing source code is possible with spoon. Spoon itself is build on top of JDT and does not produce .class files. Lombok, on the other hand, hooks in the java compiler and transforms the files (to my knowledge).
But you can achieve the same. In gradle you could have a task that is run before the javacompile task https://docs.gradle.org/current/dsl/org.gradle.api.tasks.compile.JavaCompile.html, which transforms the .java files with the generated code. IDEs should use the gradle javacompile task to get the class files and all information like methods etc. As a fair warning this needs more research and I have never implemented this. Spoon is strong at analyzing and printing source code if you don't need to preserve formatting. 
An example is this method https://github.com/INRIA/spoon/blob/981571557d3d5cb0120827887e987ca9ee75c4c2/src/main/java/spoon/support/reflect/declaration/CtRecordComponentImpl.java#L36. For a `CtRecordComponent` we create the implicit getter here.
