### ISSUE TITLE
[Question] analysis method caller

### ISSUE THREAD

**Issue by loyispa** [INRIA/spoon#5387]
Thank you for providing such a great work, currently i have a question about spoon:

For such a callstack:
    mehtodA ->  methodC
    mehtodB ->  methodC 

Could i use spoon to known methodC has two callers (methodA and methodB)?

**Comment by tenax66** [comment]
Yes. you can do it by using `MethodInvocationSearch` class,  for example.
```java
public class Main {

	public static void main(String[] args) {
		Launcher l = new Launcher();
		l.addInputResource("<path_to_source>");
		l.buildModel();
		CtModel model = l.getModel();

		MethodInvocationSearch processor = new MethodInvocationSearch();
		model.getElements(new TypeFilter<>(CtExecutable.class)).forEach(processor::scan);
		
		for (MethodCallState m : processor.getInvocationsOfMethod()) {
			// do something
		} 
	}

}
```
Using `MethodInvocationSearch` as a processor, we can get `MethodCallState` of processed  classes by `MethodInvocationSearch.getInvocationsOfMethod()`.

`MethodCallState` is defined for each method, and has the following information:

- the method itself
- methods calling the method
- fields calling the method

> Could i use spoon to known methodC has two callers (methodA and methodB)?

You can know methods calling methodC from this.

**Comment by loyispa** [comment]
@tenax66  Thank you, i w'll try it.

**Comment by I-Al-Istannen** [comment]
Hey @loyispa, did you find the time to try this? :)

**Comment by loyispa** [comment]
@I-Al-Istannen   Yes,  it works perfectly.
