### ISSUE TITLE
Query regarding support for Java 21 features

### ISSUE THREAD

**Issue by anto-christo** [INRIA/spoon#5527]
Hi,

I tried parsing a Java code with some features that were finalised in Java 21 like Switch Pattern Matching and String Templates.
Spoon was unable to parse it and threw an exception.
On checking the documentation, I see that Spoon supports versions upto Java 20.

Is there any plan for supporting Java 21 features (including the preview features)? 
Even though an exception was thrown in the code that I tested with, is Spoon capable of working with any of the new Java 21 features?

Thank you!

**Comment by SirYwell** [comment]
There is work ongoing for Java 21 support. Note that this depends on #5280, and we still need to wait for a JDT release with full Java 21 support.

**Comment by anto-christo** [comment]
Got it, thank you.

**Comment by MartinWitt** [comment]
@SirYwell this is fixed now or?

**Comment by SirYwell** [comment]
Yes, support for Java 21 is integrated.
