### ISSUE TITLE
[Bug]: CtAnnotation Type in Annonymous Class is null

### ISSUE THREAD

**Issue by Ruil1n** [INRIA/spoon#5543]
### Describe the bug

When I run ctAnnotation.getType(),it cause NPE.

### Source code you are trying to analyze/transform

```Java
public class Controller{
    public Response query(Request request) {
        return execute(new A.SecureService<Request>() {
            @Override
            public void check() {

            }
        });
    }
}
```

### Source code for your Spoon processing

```Java
import spoon.Launcher;
import spoon.reflect.declaration.CtAnnotation;
import spoon.reflect.declaration.CtClass;
import spoon.reflect.declaration.CtMethod;

import java.util.Map;

public class SpoonTest {
    public static void main(String[] args) {
        CtClass l = Launcher.parseClass("public class Controller{\n" +
                "    @Request\n" +
                "    public Response query(Request request) {\n" +
                "        return execute(new A.SecureService<Request>() {\n" +
                "            @Override\n" +
                "            public void check() {\n" +
                "\n" +
                "            }\n" +
                "        });\n" +
                "    }\n" +
                "}");
        CtAnnotation ctAnnotation = ((CtMethod)((CtClass)((Map)l.getMetadata("spoon.reflect.factory.TypeFactory-AnnonymousTypeCache")).get("110")).getTypeMembers().get(0)).getAnnotations().get(0);
        System.out.println(ctAnnotation.getType().getQualifiedName());

    }
}
```

### Actual output

```Java
Exception in thread "main" java.lang.NullPointerException
	at SpoonTest.main(SpoonTest.java:22)
```

### Expected output

```Java
java.lang.Override
```

### Spoon Version

spoon-core-10.4.3-beta-6

### JVM Version

11.0.2

### What operating system are you using?

Mac

**Comment by SirYwell** [comment]
This metadata is an implementation detail, there is no guarantee that it will be present at any time.

What exactly are you trying to achieve? Most likely there's a better way.

**Comment by Ruil1n** [comment]
> This metadata is an implementation detail, there is no guarantee that it will be present at any time.
> 
> What exactly are you trying to achieve? Most likely there's a better way.

I hope to get the annotation of the "check" method  -> "@Override"

**Comment by SirYwell** [comment]
You can achieve that by using e.g. [`CtClass#getMethodsByName`](https://spoon.gforge.inria.fr/mvnsites/spoon-core/apidocs/spoon/reflect/declaration/CtType.html#getMethodsByName(java.lang.String)) and [`CtMethod#getAnnotations`](https://spoon.gforge.inria.fr/mvnsites/spoon-core/apidocs/spoon/reflect/declaration/CtElement.html#getAnnotations()).

(Note in your example, you should use `CtClass<?>` instead of `CtClass`, otherwise you might encounter confusing compilation errors)

**Comment by Ruil1n** [comment]
> You can achieve that by using e.g. [`CtClass#getMethodsByName`](https://spoon.gforge.inria.fr/mvnsites/spoon-core/apidocs/spoon/reflect/declaration/CtType.html#getMethodsByName(java.lang.String)) and [`CtMethod#getAnnotations`](https://spoon.gforge.inria.fr/mvnsites/spoon-core/apidocs/spoon/reflect/declaration/CtElement.html#getAnnotations()).
> 
> (Note in your example, you should use `CtClass<?>` instead of `CtClass`, otherwise you might encounter confusing compilation errors)

I'm looking to directly find the 'check' method rather than by name. Is there another way? I tried CtClass#getAnonymousExecutables and CtClass#getMethods but it didn't work.

**Comment by SirYwell** [comment]
> I'm looking to directly find the 'check' method rather than by name. Is there another way? I tried CtClass#getAnonymousExecutables and CtClass#getMethods but it didn't work.

You can also loop through the `CtClass#getMethods` list and check for methods that have that annotation present. Alternatively, you could [query the model](https://spoon.gforge.inria.fr/filter.html#filters) for the annotation and check if `getParent()` is a `CtMethod`.

If you have any problem with that, it would be helpful to see your code, the input, the result, and the expected result.
