### ISSUE TITLE
How to visit a node before and after processing?

### ISSUE THREAD

**Issue by retuxx** [INRIA/spoon#557]
I need to visit a node *before* its children are processed and *after*. Currently, spoon only provides the strategies [PRE_ORDER](https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/processing/TraversalStrategy.java#L33) and [POST_ORDER](https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/processing/TraversalStrategy.java#L40) allowing me to either visit nodes before or after. Is there a method to combine these strategies?

**Comment by GerardPaligot** [comment]
Hi @retuxx,

For now, it isn't possible but that could be interesting to integrate this kind of feature in Spoon. PR welcome or I'll work on it soon.

**Comment by retuxx** [comment]
I think in order to add this feature the [Processor](https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/processing/Processor.java) interface needs to be extended because the method [process](https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/processing/Processor.java#L69) does not know whether it is called pre or post order. Do you have any suggestions what to do? I could try to add this feature and making a pr if you are busy at the moment.

**Comment by GerardPaligot** [comment]
I think that the better way is to add a new state in [TraversalStrategy](https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/processing/TraversalStrategy.java#L24) and update the logical in [ProcessingVisitor](https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/support/visitor/ProcessingVisitor.java#L81-L94). That seems pretty easy. :)

**Comment by retuxx** [comment]
Yes, but how should I know whether [process](https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/processing/Processor.java#L69) (which gets called by [scan](https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/support/visitor/ProcessingVisitor.java#L81-L94)) is called in pre- or in post-order step?

**Comment by GerardPaligot** [comment]
Ok, I see your issue.

In the [Processor](https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/processing/Processor.java#L30) interface, you can add 2 methods named `preProcess(CtElement)` and `postProcess(CtElement)` with an empty default implementation in `AbstractProcessor`.

In the [scan](https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/support/visitor/ProcessingVisitor.java#L77) method of `ProcessorVisitor`, you call `preProcess` and `postProcess` after each `process` invocation (to be retro-compatible).

**Comment by retuxx** [comment]
I think that is a good point to start with. Now, how do I apply this idea to the [CtVisitor](https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/reflect/visitor/CtVisitor.java)? I could add a pre and post version of each visit function to the interface.

**Comment by GerardPaligot** [comment]
> Now, how do I apply this idea to the CtVisitor?

Why do you want apply this to the `CtVisitor`? `ProcessingVisitor` is the only one which is used to apply a processor.

**Comment by retuxx** [comment]
Maybe I misunderstand the usage of Processors and Visitors. Actually, I would like  calculate some metrics for classes/functions and so on. The general idea is to use a visitor in order to get access to the structure of a class/function. In my scenario I would like to initialize a value before *accepting* (in the context of the visitor patter) a node and read this value afterwards. This value will be modified by other visit methods handling the children nodes.

Extending the `ProcessingVisitor` by applying your suggested patches does not give me the ability to visit a node before and after its accepting, right?

**Comment by alcides** [comment]
> On 15 Mar 2016, at 14:32, Marcel <notifications@github.com> wrote:
> 
> Maybe I misunderstand the usage of Processors and Visitors. Actually, I would like calculate some metrics for classes/functions and so on. The general idea is to use a visitor in order to get access to the structure of a class/function. In my scenario I would like to initialize a value before accepting (in the context of the visitor patter) a node and read this value afterwards. This value will be modified by other visit methods handling the children nodes.
> 
> 

I believe this is the same case I had with a) calculating a cost-model for each node, and then b) performing modifications based on the cost-model analysis. This lead me to write two different processors and pass the results of the first processor to the second.

— Alcides Fonseca

**Comment by retuxx** [comment]
> This lead me to write two different processors and pass the results of the first processor to the second.

I would like to avoid the usage of two processors as it makes things more complex than it should (You have to add some sort of 'book keeping' code)

**Comment by retuxx** [comment]
A simple solution might be the addition of a 'state' attribute to either `Processor` or `CtVisitor` or both indicating that the process/visit method has been called in pre- or post-order step.

**Comment by GerardPaligot** [comment]
> Extending the ProcessingVisitor by applying your suggested patches does not give me the ability to visit a node before and after its accepting, right?

Yes. With my solution: 

- `preProcessor` is called before its acceptings.
- [`super.scan(e)`](https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/support/visitor/ProcessingVisitor.java#L88) calls the [`accept` method of the current node](https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/reflect/visitor/CtScanner.java#L145).
- `postProcessor` is called at the end of the node processing.

It isn't what you want?

**Comment by retuxx** [comment]
> super.scan(e) calls the accept method of the current node.

Thats right, determining the state (pre or post) from within the Processor should work but how do I get the state from within the actual visitor? The visit methods get called by both the, pre order and the post order step (similar to the process method of the Processor class).

**Comment by retuxx** [comment]
After playing with the code I see what our misunderstandings are. So let me try to clarify things.

a) I want to use a visitor to calculate a metric `m`.
b) The visitor implements one of the visit methods, for instance the [visitCtMethod](https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/reflect/visitor/CtVisitor.java#L293).
c) Within this visit method, I would like to initialize `m` with a value, for instance 0, **before** the `CtMethod` is processed. By processing an element I mean applying the recursive descent.
d) Now the recursive descent starts.
e) In order to calculate `m` my visitor implements other visit methods as well, for instance [visitCtReturn](https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/reflect/visitor/CtVisitor.java#L350).
f) If the method mentioned in e) gets called `m` is updated (for example by incrementing `m`) .
g) At some point the element mentioned in c) (our method element) has been processed. That is, all its children have been visited. At this point I would like to have a function which behaves like a `postVisit`, `afterVisit`, `endVisit`, or whatever you would like to name it. JDT, for instance, provides [this](http://help.eclipse.org/luna/topic/org.eclipse.jdt.doc.isv/reference/api/org/eclipse/jdt/core/dom/ASTVisitor.html#endVisit-org.eclipse.jdt.core.dom.MethodDeclaration-) method.

So what do I need. I need a visit function that definitely gets called **before** processing and a visit function that definitely gets called **after** processing.

My suggestion is to extend the `CtVisitor` interface providing the functions `beforeVisit...` and `afterVisit...` for each `visit` method. Afterwards, the `ProcessingVisitor` makes usage of these methods by extending the `scan` method like:

```java
	@Override
	@SuppressWarnings("unchecked")
	public void scan(CtElement e) {
		if (e == null) {
			return;
		}

               // call the beforeVisit method of e

		Processor<CtElement> p = (Processor<CtElement>) processor;
		if (p.getTraversalStrategy() == TraversalStrategy.PRE_ORDER
				&& canBeProcessed(p, e)) {
			if (p.isToBeProcessed(e)) {
				p.process(e);
			}
		}
		super.scan(e);
		if (p.getTraversalStrategy() == TraversalStrategy.POST_ORDER
				&& canBeProcessed(p, e)) {
			if (p.isToBeProcessed(e)) {
				p.process(e);
			}
		}

                // call the afterVisit method of e
	}
```

**Comment by GerardPaligot** [comment]
Ok, I think I understand what do you want (I hope...) and what do you want to do can be done with a subclass of a `CtScanner` like this one:

```java
public class MetricScanner extends CtScanner {
	Map<CtMethod, Integer> metrics = new HashMap<CtMethod, Integer>();

	@Override
	public <T> void visitCtMethod(CtMethod<T> m) {
		// Before visiting the content of the method.
		metrics.put(m, 0);

		super.visitCtMethod(m);

		// After visiting the method.
		// TODO Do stuff.
	}

	@Override
	public <R> void visitCtReturn(CtReturn<R> returnStatement) {
		// Before visiting the content of the return.
		// TODO Do stuff.

		super.visitCtReturn(returnStatement);

		// Before visiting the content of the method.
		// TODO Do stuff.
	}

	@Override
	public <T> void visitCtInvocation(CtInvocation<T> invocation) {
		CtExecutable<T> target = invocation.getExecutable().getDeclaration();
		if (metrics.containsKey(target)) {
			metrics.put((CtMethod) target, metrics.get(target) + 1);
		}

		super.visitCtInvocation(invocation);
	}

	public static void main(String[] args) {
		Launcher launcher = new Launcher();
		// Initialize launcher...
		launcher.buildModel();

		new MetricScanner().scan(launcher.getFactory().Package().getRootPackage());
	}
}
```

**Comment by retuxx** [comment]
Thank you @GerardPaligot. That is exactly what I was looking for. I thought the recursive descent is handled by the Processor only. Thus, I did not consider to wrap my code around `super.visitCtMethod` (or any visit method).

I've added an example in pr #560. Maybe it helps others requesting this feature. Feel free to merge to to discard :)
