### ISSUE TITLE
compile changes

### ISSUE THREAD

**Issue by mehdijk** [INRIA/spoon#562]
After we build a spoon model and make some changes in classes or methods, how we can test it and be sure that the generated source code would be compiled successfully?
Should we generate source code and rebuild model with new souce code to be sure about compilation? or is there other way?
Thank you

**Comment by GerardPaligot** [comment]
Hi @mehdijk,

It seems that you searches the `--compile` argument (or `launcher.getEnvironnement().shouldCompile(true)`).

**Comment by mehdijk** [comment]
This a sample:
`Launcher spoon = new Launcher();
spoon.getEnvironment().setNoClasspath(true);		
spoon.addInputResource(inputResources);
spoon.buildModel();
CtPackage rootPack=spoon.getFactory().Package().getRootPackage();
CtClass<?> ctClazz = spoon.getFactory().Class().get("clazzA");
ctClazz.removeMethod(ctClazz.getAllMethods().iterator().next());`
Now, I want to check whether this project be compiled with this change?

**Comment by GerardPaligot** [comment]
Call `spoon.getModelBuilder().compile()`.

**Comment by GerardPaligot** [comment]
@mehdijk It is ok? :)

**Comment by mehdijk** [comment]
Yes, thank you

**Comment by GerardPaligot** [comment]
Nice! :)
