### ISSUE TITLE
Java Compatibility with Older Versions of Spoon

### ISSUE THREAD

**Issue by CPTXAzDevOps** [INRIA/spoon#5639]
We are using an older version of Spoon (8.3 and we will be updating soon). Our infrastructure team wants to update java on the server that Spoon lives on. Currently the java version is 8_333b2 and the infra team wants to go to the latest 8 which I believe is 8_391. I would assume Spoon would be just fine but wanted to check with the community first to be sure. Thanks in advance!

**Comment by MartinWitt** [comment]
Hey,

We dropped java 8 support in spoon 10.0. So we are not actively testing with java 8 anymore. Spoon can still analyze java 8 code, but needs java 11 for the newest versions.
> Spoon 9.1.0 is the final Spoon release compatible with Java 8.

So Spoon 9.1.0 will be your version.
