### ISSUE TITLE
SpoonClassNotFoundException in `unbox()` after class rename

### ISSUE THREAD

**Issue by fedorov-s-n** [INRIA/spoon#565]
Exception arises when one tries to `CtTypeReferenceImpl#unbox` type reference of a type that was renamed.

	Exception in thread "main" spoon.support.reflect.reference.SpoonClassNotFoundException: cannot load class: com.my.MyClass.$Inner with class loader sun.misc.Launcher$AppClassLoader@4e25154f
		at spoon.support.reflect.reference.CtTypeReferenceImpl.findClass(CtTypeReferenceImpl.java:143)
		at spoon.support.reflect.reference.CtTypeReferenceImpl.getActualClass(CtTypeReferenceImpl.java:131)
		at spoon.support.reflect.reference.CtTypeReferenceImpl.unbox(CtTypeReferenceImpl.java:315)
		...

I wrote example and stored it here: https://github.com/fedorov-s-n/SpoonClassNotFoundIssue

I read sources and understand that the reason is Spoon uses `Class` references for resolving unboxed types. The reason is that there's no required type in classpath because class was just renamed and wasn't compiled. So options are:

  1. Make possible to dynamically compile changed classes to memory and change class loader to (memory + URL) loader from just URL
  2. Stop using `Class` references, act like in `CtTypeReferenceImpl#box`
  3. Allow automatic dynamic compile of in-memory file in `CtTypeReferenceImpl#getActualClass` in case given file exists in ast representation

Personally I think that all options worth implementing but the second one requires much less resources.

BTW, `CtTypeReferenceImpl#getActualClass` is also used in other method implementations that can cause the same problem, for example, `CtTypeReferenceImpl#isSubtypeOf`.

**Comment by fedorov-s-n** [comment]
I use Spoon v5.0.2.

**Comment by monperrus** [comment]
unbox on non-primitive types throws a IllegalStateException('cannot unbox a non-primitive exception"))

**Comment by fedorov-s-n** [comment]
doesn't that break a contract? docs says that it

> Returns the primitive type for a boxing type (unchanged if the type does not correspond to a boxing type).

**Comment by fedorov-s-n** [comment]
Can I get a snapshot?
I want to test that the issue is fixed. I tried to build master branch with `mvn package` but faced a build issue.

**Comment by GerardPaligot** [comment]
Yes: https://github.com/INRIA/spoon#download

> faced a build issue

What is your system and the error?

**Comment by fedorov-s-n** [comment]
sfedorov@sfedorov:/opt/work/spoon$ uname -a
Linux sfedorov 4.2.0-30-generic #36-Ubuntu SMP Fri Feb 26 00:58:07 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
sfedorov@sfedorov:/opt/work/spoon$ lsb_release -irc
Distributor ID:	Ubuntu
Release:	15.10
Codename:	wily
sfedorov@sfedorov:/opt/work/spoon$ mvn package
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 1 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 1 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Spoon Core 5.2.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ spoon-core ---
[INFO] 
[INFO] --- maven-resources-plugin:2.3:resources (default-resources) @ spoon-core ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 4 resources
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ spoon-core ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 389 source files to /opt/work/spoon/target/classes
[WARNING] /opt/work/spoon/src/main/java/spoon/support/reflect/declaration/CtElementImpl.java: Some input files use or override a deprecated API.
[WARNING] /opt/work/spoon/src/main/java/spoon/support/reflect/declaration/CtElementImpl.java: Recompile with -Xlint:deprecation for details.
[WARNING] /opt/work/spoon/src/main/java/spoon/support/reflect/declaration/CtElementImpl.java: Some input files use unchecked or unsafe operations.
[WARNING] /opt/work/spoon/src/main/java/spoon/support/reflect/declaration/CtElementImpl.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- maven-resources-plugin:2.3:testResources (default-testResources) @ spoon-core ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 54 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ spoon-core ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 356 source files to /opt/work/spoon/target/test-classes
[WARNING] /opt/work/spoon/src/test/java/spoon/test/targeted/TargetedExpressionTest.java:[3,50] com.sun.org.apache.bcel.internal.classfile.InnerClass is internal proprietary API and may be removed in a future release
[WARNING] /opt/work/spoon/src/test/java/spoon/test/imports/testclasses/ClassWithInvocation.java:[3,30] sun.reflect.annotation.TypeAnnotation is internal proprietary API and may be removed in a future release
[WARNING] /opt/work/spoon/src/test/java/spoon/test/targeted/TargetedExpressionTest.java:[184,30] com.sun.org.apache.bcel.internal.classfile.InnerClass is internal proprietary API and may be removed in a future release
[WARNING] /opt/work/spoon/src/test/java/spoon/test/targeted/TargetedExpressionTest.java:[185,39] com.sun.org.apache.bcel.internal.classfile.InnerClass is internal proprietary API and may be removed in a future release
[WARNING] /opt/work/spoon/src/test/java/spoon/test/targeted/TargetedExpressionTest.java:[196,36] com.sun.org.apache.bcel.internal.classfile.InnerClass is internal proprietary API and may be removed in a future release
[WARNING] /opt/work/spoon/src/test/java/spoon/test/targeted/TargetedExpressionTest.java:[343,30] com.sun.org.apache.bcel.internal.classfile.InnerClass is internal proprietary API and may be removed in a future release
[WARNING] /opt/work/spoon/src/test/java/spoon/test/targeted/TargetedExpressionTest.java:[344,39] com.sun.org.apache.bcel.internal.classfile.InnerClass is internal proprietary API and may be removed in a future release
[WARNING] /opt/work/spoon/src/test/java/spoon/test/targeted/TargetedExpressionTest.java:[355,36] com.sun.org.apache.bcel.internal.classfile.InnerClass is internal proprietary API and may be removed in a future release
[WARNING] /opt/work/spoon/src/test/java/spoon/test/imports/testclasses/ClassWithInvocation.java:[10,14] sun.reflect.annotation.TypeAnnotation is internal proprietary API and may be removed in a future release
[WARNING] /opt/work/spoon/src/test/java/spoon/test/delete/DeleteTest.java: Some input files use or override a deprecated API.
[WARNING] /opt/work/spoon/src/test/java/spoon/test/delete/DeleteTest.java: Recompile with -Xlint:deprecation for details.
[WARNING] /opt/work/spoon/src/test/java/spoon/test/template/LoggerTemplateProcessor.java: Some input files use unchecked or unsafe operations.
[WARNING] /opt/work/spoon/src/test/java/spoon/test/template/LoggerTemplateProcessor.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- maven-surefire-plugin:2.17:test (default-test) @ spoon-core ---
[INFO] Surefire report directory: /opt/work/spoon/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.187 s
[INFO] Finished at: 2016-04-26T16:14:11+03:00
[INFO] Final Memory: 27M/413M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.17:test (default-test) on project spoon-core: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.17:test failed: There was an error in the forked process
[ERROR] java.lang.NoClassDefFoundError: MoveOption
[ERROR] at java.lang.Class.getDeclaredMethods0(Native Method)
[ERROR] at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
[ERROR] at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
[ERROR] at java.lang.Class.getMethod0(Class.java:3018)
[ERROR] at java.lang.Class.getMethod(Class.java:1784)
[ERROR] at org.apache.maven.surefire.util.ReflectionUtils.tryGetMethod(ReflectionUtils.java:57)
[ERROR] at org.apache.maven.surefire.common.junit3.JUnit3TestChecker.isSuiteOnly(JUnit3TestChecker.java:64)
[ERROR] at org.apache.maven.surefire.common.junit3.JUnit3TestChecker.isValidJUnit3Test(JUnit3TestChecker.java:59)
[ERROR] at org.apache.maven.surefire.common.junit3.JUnit3TestChecker.accept(JUnit3TestChecker.java:54)
[ERROR] at org.apache.maven.surefire.common.junit4.JUnit4TestChecker.accept(JUnit4TestChecker.java:52)
[ERROR] at org.apache.maven.surefire.util.DefaultScanResult.applyFilter(DefaultScanResult.java:97)
[ERROR] at org.apache.maven.surefire.junit4.JUnit4Provider.scanClassPath(JUnit4Provider.java:206)
[ERROR] at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:103)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
[ERROR] Caused by: java.lang.ClassNotFoundException: MoveOption
[ERROR] at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[ERROR] at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[ERROR] at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
[ERROR] at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[ERROR] ... 16 more
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

**Comment by GerardPaligot** [comment]
That doesn't seem to come from Spoon.

What is the result of `mvn -v`?

**Comment by fedorov-s-n** [comment]
sfedorov@sfedorov:/opt/work/spoon$ mvn -v
Apache Maven 3.3.3
Maven home: /usr/share/maven
Java version: 1.8.0_72, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.2.0-30-generic", arch: "amd64", family: "unix"

**Comment by fedorov-s-n** [comment]
I checked snapshot and found that this issue is fixed. But it has another issue: `CtCatchVariableReference` often (or very frequently) have `null` declaration after document parsing. Is it a known bug? Is it reasonable to file it against snapshot version?
