### ISSUE TITLE
feature: add support for runtime reflection of binary classes

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#566]
idea: create shadow objects for runtime classes using the reflection API

so that a new contract holds:
unless in noclasspath, getFactory().Type().get() never returns null .

by default, the shadow spoon objects should not be processed 

would solved #563 and corresponds to solution 2 of #565

**Comment by leventov** [comment]
This would be super cool, because it effectively makes Spoon a "better reflection API" and allows runtime analysis and manipulation.

**Comment by GerardPaligot** [comment]
Fixed by #569
