### ISSUE TITLE
CtTypeReference::getSuperclass in NoClasspath Mode

### ISSUE THREAD

**Issue by Tallic** [INRIA/spoon#572]
CtTypeReference::getSuperclass throws SpoonClassNotFoundException even though it should return a reference which should be safe in the no classpath mode.

Spoon Version 5.1.0
Options: noClasspath <- true

**Comment by GerardPaligot** [comment]
Can you give us more context? I can't reproduce your bug with this snippet:

```java
class A extends B {
}
```

When I call `aClass.getSuperclass()`, it returns a `CtTypeReference` of `B` (this latest class doesn't exist in my spoon path).

**Comment by Tallic** [comment]
The error occurs when you want to traverse the inheritance tree up in possible unknown class space as it might not be on the classpath.

Here is a minimal example in form of a Gist:
[Gist of Issue 572](https://gist.github.com/Tallic/7cf48cc68cfe95c360efdf7604bf0411)

As a API user i would expect in the _noclasspath_ mode to get a null at some point instead of an exception.
The current behavior forces me to either wrap the traversal into a try/catch, or to try to get the superclass declaration beforehand and look whether it exists.
First one is undesirable as it stand in the face of the expectation (we choose intentionally _noclasspath_ so we know that there might be missing parts) of the _noclasspath_ mode (despite being slow and ugly^^), second uses knowledge about the implementation of _getSuperclass_, thus is fragile.

As a sidenote: This "wrong" behavior occurs on all methods that involve inheritance traversal;
Confirmed cases for classes are _isSubtypeOf()_  and for methods _isOverriding()_ which i stumbled across.

The problem is that _CtTypeReferenceImpl#findClass_ is called and will throw independent of the mode spoon is in.

**Comment by GerardPaligot** [comment]
For now, references work like that : First, we try to get the element from the AST. Then, we try it via the reflection. This is done for all methods like you said.

And for the reflection part, we use the method `getActualClass()` which is specified in the file test case `NoClasspathTest`. The test case in this file specifies the behavior of `getActualClass()` in noclasspath mode : [throws an SpoonClassNotFoundException](https://github.com/INRIA/spoon/blob/master/src/test/java/spoon/test/api/NoClasspathTest.java#L48-L53).

**Comment by Tallic** [comment]
Ok than it is not a direct issue rather a design question. 
It would be good to enhance the API or the documentation to clarify when a method returns null or throws an exception, optimally consistent with the return type (declaration or reference).
