### ISSUE TITLE
Invocation of an annotation field references an executable.

### ISSUE THREAD

**Issue by GerardPaligot** [INRIA/spoon#578]
Assuming you have this annotation:

```java
@interface Parameter {
  String value();
}
```

If you invocate the field `value`, Spoon build a `CtExecutableReference` and you can't get the field declaration cause of this reference.

**Comment by monperrus** [comment]
CtAnnotationType contains implicit methods for each field 
OR
CtAnnotationTypeField implements CtField,CtMethod

**Comment by monperrus** [comment]
TODO remove if check in MainTest for this
