### ISSUE TITLE
I don't detect files which contains declaration of an annotatio 

### ISSUE THREAD

**Issue by nassimb92** [INRIA/spoon#579]
Hi,
When i launch my processor to analyse a project which contains files where i declare annotations. 
The processor does not accede to this files. 
when i put @interface instead the keyword class, my processor stop analysing this file.

I have also an other problem, i have a NullPointerException when i launch my processors to analyse the project  https://github.com/larsgrefer/pocket-hub

**Comment by GerardPaligot** [comment]
Hi @nassimb92,

What is the declaration of your processor?

**Comment by nassimb92** [comment]
public void process(CtClass element)

**Comment by GerardPaligot** [comment]
An annotation isn't a `CtClass` but a `CtAnnotationType`. You should have this kind of processor:

```java
class MyProcessor extends AbstractProcessor<CtAnnotationType> {
  // code here.
}
```

**Comment by nassimb92** [comment]
Thanks @GerardPaligot
