### ISSUE TITLE
Unable to start JavaFX UI

### ISSUE THREAD

**Issue by thron7** [INRIA/spoon#5795]
### Describe the bug

First off, thanks for Spoon!

I'm new to Spoon and  tried to start the new JavaFX UI following the description in `spoon-visualisation/README.md`. After running `mvn clean package` and changing into the `target` folder, there is no `visualisation*.jar` (recursively), and I haven't figured out how to build it, so I couldn't run the documented `java ... -jar visualisation-1.1.jar`  command.

ping @arnobl 

Thanks, Thomas

### Spoon Version

11.0.1-SNAPSHOT  (It's the Git "master" branch at commit `36610b433bf16`)

### JVM Version

17

### What operating system are you using?

Linux

**Comment by I-Al-Istannen** [comment]
The Javafx build is a bit fiddly, it would really benefit from somebody cleaning it up.

Currently you need to:
1. Fix the version of the spoon-pom parent.
2. `mvn clean package`
3. `cd target/modules`
4. Run
  ```sh
  mkdir output
unzip ecj-3.37.0.jar -d output
unzip org.eclipse.jdt.core-3.37.0.jar -d output # overwrite
rm ecj-3.37.0.jar
rm org.eclipse.jdt.core-3.37.0.jar
cd output
zip -r ../org.eclipse.jdt.core-3.37.0.jar *
cd ..
java --module-path . --add-modules=ALL-MODULE-PATH -jar visualisation-1.1.jar
  ```

**Comment by I-Al-Istannen** [comment]
This should be fixed with https://github.com/INRIA/spoon/pull/5963.
