### ISSUE TITLE
CtTypeParameterReferenceImpl shouldn't extend CtTypeReferenceImpl

### ISSUE THREAD

**Issue by leventov** [INRIA/spoon#581]
Because actually it doesn't use any part of `CtTypeReferenceImpl` state: actualTypeArguments, declaringType, or package reference. To share some logic they could have a common parent like `CtAbstractTypeReferenceImpl` with no fields but some methods implemented.

**Comment by GerardPaligot** [comment]
`CtTypeParameterReference` must extend `CtTypeReference` because we can have:

```java
List<T> list;
List<String> list;
```

Both are saved in a list of `CtTypeReference` (`getActualTypeArguments`).

**Comment by leventov** [comment]
Yes, that's true, but I talk about CtTypeParameterReference**Impl**, it could implement `CtTypeParameterReference` while not extending CtTypeReference**Impl**

**Comment by GerardPaligot** [comment]
Why do you want to do this?

**Comment by monperrus** [comment]
Closing this. Don't hesitate to reopen it if there is a major problem there.
