### ISSUE TITLE
Processing import Statements

### ISSUE THREAD

**Issue by thron7** [INRIA/spoon#5818]
I want to work with import statements in the analyzed code. My Spoon processor looks basically like this:
```
public class MyImports extends AbstractProcessor<CtImport> {
  public void process(CtImport element) {
      System.out.println("Import found: " + element.getPosition().toString());
  }
}
```
But the process method is never called, running the processor on Java files that do have imports. (I've cross-checked with a similar processor for `catch` elements which does get called.). Also, looking at the classical Spoon UI for a simple class with an import statement, the import statement is nowhere represented in the tree (while e.g. a class comment is), so I have no clue which kind of tree node is actually used for an import declaration in the parse tree.

It is also no use to scan the parse tree for e.g. `CtTypeReference` nodes and then try to infer if the type might be imported, as this way I would miss unused import statements, the types of which are never referenced in the code.

What am I doing wrong? How to get hold of import declarations in my processor? - Thanks

**Comment by Luro02** [comment]
Spoon doesn't visit `CtImport`, don't ask me why, but I think it was explained in https://github.com/INRIA/spoon/issues/5168.

This is the code I am using to visit all imports in a model:
```java
    private static void visitCtCompilationUnit(CtModel ctModel, Consumer<? super CtCompilationUnit> lambda) {
        // it is not possible to visit CtCompilationUnit through the processor API.
        //
        // in https://github.com/INRIA/spoon/issues/5168 the below code is mentioned as a workaround:
        ctModel
            .getAllTypes()
            .stream()
            .map(CtType::getPosition)
            .filter(SourcePosition::isValidPosition)
            .map(SourcePosition::getCompilationUnit)
            // visit each compilation unit only once
            .distinct()
            .forEach(lambda);
    }

    public void visitAllImports(CtModel ctModel) {
        visitCtCompilationUnit(ctModel, ctCompilationUnit -> {
            for (CtImport ctImport : ctCompilationUnit.getImports()) {
                this.checkImport(ctImport, ctCompilationUnit);
            }
        });
    }

    private void checkImport(CtImport ctImport, CtCompilationUnit ctCompilationUnit) {
        // write your code for imports here
    }
```

**Comment by thron7** [comment]
Great, thanks for the help.
