### ISSUE TITLE
Too many type parameters

### ISSUE THREAD

**Issue by leventov** [INRIA/spoon#583]
Spoon uses method type parameters very extensively, for example:
```java
interface CtType<T> {
    <S, C extends CtType<T>> C addSuperInterface(CtTypeReference<S> interfac);
}
```

1. I have never found `CtType`, `CtBlock`, `CtMethod`, `CtExpression`, etc. useful to be parameterized with actual type, I *always* use them with unbound wildcard. But probably my use cases are not representative.

2. Having `S` parameter over simply
 ```java
     <C extends CtType<T>> C addSuperInterface(CtTypeReference<?> interfac);
 ```
 add absolutely nothing to type safety or any other aspect.

3. `<C extends CtType<T>>` part is supposed to support chaining pattern, e. g.
 ```java
 ctClass.addInteface().callSomeCtClassSpecificMethod();
 ``` 
 This is a valid goal, but the approach is not type-safe, because I can write
 ```java
 ctClass.addInteface().callSomeCtInterfaceSpecificMethod();
 ```
 absolutely fine, because `C` is just a method type parameter. Also, this approach makes type inference to fail often and force a user to specify pointless method type parameters explicitly before method name, that is ugly and painfully verbose.

 A more type safe approach which requires no type inference is
 ```java
 inteface CtType<T, I extends CtType<T, I>> {
     I addSuperInterface(CtTypeReference<?> interfac);
 }
 ```

 Downsides:
  - A massive refactoring of the whole library is required to implement this;
  - User code that doesn't care will now need to have two wildcards instead of one, e. g. `CtType<?, ?>`. But see item 1, IMHO the first type param is not needed;
  - There shouldn't be `*Impl` classes which are non-abstract and have subClasses. All concrete classes should be "leaves" of inheritance tree, to be parameterized with themselves as `I` parameter, i. e. "tie the knot".

**Comment by monperrus** [comment]
Hi @leventov ,

Your analysis is just fine and impressively accurate. However, as you say, it would break **a lot of client code**. I'm not in favor of this right now, there are other items of higher priority on the roadmap that are backward compatible.

Would you add a PR on the roadmap about this?

**Comment by GerardPaligot** [comment]
PR on the roadmap today.
