### ISSUE TITLE
Incremental model building

### ISSUE THREAD

**Issue by leventov** [INRIA/spoon#584]
Is it possible to build source code model iteratively? I. e.

 1. Feed some inputResources to a spoon compiler
 2. Build model
 3. Do something with that model..
 4. Feed some new inputResources to the model
 5. Build models of newly added classes/packages and attach them to the existing model.

Documentation to `FactoryImpl.getParentFactory()` mentions something like this but since this method is never used inside the Spoon library, I think it is not implemented now

**Comment by GerardPaligot** [comment]
Fixed by #589
