### ISSUE TITLE
Spelling mistake in AnnotationProcessor API

### ISSUE THREAD

**Issue by PinkMoustacheMan** [INRIA/spoon#5934]
In the [AnnotationProcessor](https://github.com/INRIA/spoon/blob/15c8bb35e034a4d553cb1a87f413e686a06b2544/src/main/java/spoon/processing/AnnotationProcessor.java#L66) class, the "shoudBeConsumed" method is misspelled and should be called "shouldBeConsumed".

This change has an effect on the [AbstractAnnotationProcessor](https://github.com/INRIA/spoon/blob/15c8bb35e034a4d553cb1a87f413e686a06b2544/src/main/java/spoon/processing/AbstractAnnotationProcessor.java#L159) as well as all projects using this API.

The spelling is also incorrect for the "shoudBeProcessed" method in the [AbstractAnnotationProcessor](https://github.com/INRIA/spoon/blob/15c8bb35e034a4d553cb1a87f413e686a06b2544/src/main/java/spoon/processing/AbstractAnnotationProcessor.java#L163) but due to it being private, this should have a smaller impact.

**Comment by monperrus** [comment]
Thanks for the bug report @PinkMoustacheMan .

I suggest to add a new method with correct spelling, and keep the previous one for backward compatibility `@Deprecated`

A pull-request is welcome!
