### ISSUE TITLE
configure renovate to only use chore(deps)

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#5952]
renovate creates PR with both `chore(deps)` and `fix(deps)` as commit message.

this pollutes our changelogs eg https://github.com/INRIA/spoon/releases/tag/v11.1.1-beta-2

I would argue that dependency updates are not fixes is the sense we mean it, and that all renovate PRs in our changelogs should be under `Tasks`

task: configure renovate to only use `chore(deps)`

reference documentation: https://docs.renovatebot.com/semantic-commits/

cc/ @rarkins FYI

**Comment by rarkins** [comment]
In semantic versioning, chore commits don't increment a version while fix ones do. Technically speaking a production dependency update can change functionality and therefore should trigger a new version. I prefer to use `build` than `fix` for my own projects, but still to trigger a version.

**Comment by monperrus** [comment]
I understand that you're referring to "dependency-aware semver", where a major/minor change in a dependency triggers a corresponding version update in the project, as a ripple effect. That's an interesting pov to discuss.

Also, we agree that `fix` is not the best prefix for commit messages and changelog generation, I like your proposal of having `build`, it's even better than `chore`.

**Comment by monperrus** [comment]
PR at https://github.com/INRIA/spoon/pull/5953
