### ISSUE TITLE
push package checskums to sigstore/rekor as part of CD

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#5957]
the Spoon workflows are meant to be state-of-the-art.

What's missing today is to push package checskums to sigstore/rekor as part of our CD pipelines (both beta and stable).

**Comment by monperrus** [comment]
potential option: https://github.com/actions/attest-build-provenance

**Comment by MartinWitt** [comment]
@RafDevX you have to write any comment here before I can asign you in the github UI.

**Comment by RafDevX** [comment]
Hi, confirm I'm also working on this
