### ISSUE TITLE
Question: difference between `getModifiers` and `getExtendedModifiers` in `CtModifiable`

### ISSUE THREAD

**Issue by algomaster99** [INRIA/spoon#5979]
I am wondering about the difference in the purpose of [`getModifiers()`](https://github.com/INRIA/spoon/blob/c60af45512223894e32a5fd2963079a88d22c388/src/main/java/spoon/reflect/declaration/CtModifiable.java#L24-L33) and [`getExtendedModifiers()`](https://github.com/INRIA/spoon/blob/c60af45512223894e32a5fd2963079a88d22c388/src/main/java/spoon/reflect/declaration/CtModifiable.java#L78-L83). I understand that extended modifiers are spoon elements and they also hold source positions. However, it explicitly says that implicit modifiers are included. Does it mean that `getModifiers` are supposed to ignore them? If yes, the `abstract` modifier is returned for an interface by `getModifiers` even though it is implicit.

**Comment by SirYwell** [comment]
`ModifierKind` doesn't hold information about whether the modifier is implicit. `CtExtendedModifier` holds that information in addition to the kind. So, if you only interested in which modifiers an element has, `getModifiers()` might be enough, but if you want to know which explicit or implicit modifiers an element has (or whether it has a specific explicit modifier), you need `getExtendedModifiers()`.

**Comment by algomaster99** [comment]
> ModifierKind doesn't hold information about whether the modifier is implicit.

so `getModifiers` could also return implicit modifiers?

**Comment by SirYwell** [comment]
> so `getModifiers` could also return implicit modifiers?

Yes, they should both contain the same modifiers (i.e. `getModifiers()` is equal to `getExtendedModifiers().stream(CtExtendedModifier::getKind()).collect(...)`)

**Comment by algomaster99** [comment]
Thanks for answering!
