### ISSUE TITLE
CtTargetedExpression.getTarget() doc is not correct

### ISSUE THREAD

**Issue by leventov** [INRIA/spoon#598]
It says "Gets the target expression. The target is null for static methods.", but actually for static methods the target is `CtTypeAccess`.

This is also probably a source of some bugs which think that `null` target is an indication of static method call indeed.

**Comment by GerardPaligot** [comment]
Thanks for this report. It is a mistake from me when I refactor all targets. PR soon.

**Comment by GerardPaligot** [comment]
PR today.
