### ISSUE TITLE
[Bug]: Source length of `CtVariableRead` and `CtLiteral` is subtracted by 1

### ISSUE THREAD

**Issue by algomaster99** [INRIA/spoon#5980]
### Describe the bug

The `getSourceStart` and `getSourceEnd` are returning incorrect value for at least `CtVariableRead` and `CtLiteral`. For example, consider this snippet below.
`CtLiteral(1).getSourceEnd() == 76`
`CtLiteral(1).getSourceStart == 76`
Here the difference should be 1 not 0.
If the literal is of length 2, then the difference is 1.

### Source code you are trying to analyze/transform

```Java
class Sample {
    public static void main(String[] args) {
        int x = 1;
        System.out.println(x+5);
    }
}
```

### Source code for your Spoon processing

```Java
@Test
	void test() {
		Launcher spoon = new Launcher();
		spoon.addInputResource("src/test/resources/Sample.java");
		spoon.buildModel();
		CtType<?> sample = spoon.getModel().getRootPackage().getType("Sample");
		CtMethod<Void> main = (CtMethod<Void>) sample.getTypeMembers().get(1);

		CtLiteral<Integer> intX = (CtLiteral<Integer>) ((CtLocalVariable)main.getBody().getStatement(0)).getAssignment();
		assertNotEquals(intX.getPosition().getSourceStart(), intX.getPosition().getSourceEnd());

		CtVariableRead<Integer> x = ((CtVariableRead<Integer>)((CtBinaryOperator)((CtInvocation<String>)main.getBody().getStatement(1)).getArguments().get(0)).getLeftHandOperand());
		assertNotEquals(x.getPosition().getSourceStart(), x.getPosition().getSourceEnd());

	}
```

### Actual output

```Java
Tests should pass because neither the literal nor the variable read is 0 length.
```

### Expected output

```Java
CtLiteral(1).getSourceEnd() == 76
CtLiteral(1).getSourceStart == 76

CtVariableRead(x) == 106
CtVariableRead(x) == 106
```

### Spoon Version

c60af45512223894e32a5fd2963079a88d22c388 (15th September 2024)

### JVM Version

openjdk version "17.0.10" 2024-01-16 OpenJDK Runtime Environment Temurin-17.0.10+7 (build 17.0.10+7) OpenJDK 64-Bit Server VM Temurin-17.0.10+7 (build 17.0.10+7, mixed mode, sharing)

### What operating system are you using?

Ubuntu 22.04

**Comment by algomaster99** [comment]
`CtTypeParameter` has the same issue.

**Comment by SirYwell** [comment]
My understanding of the javadocs is that `getSourceEnd()` returns the last position that is still part of the element (i.e. it is inclusive). That means an element of length 1 will have `getSourceEnd() == getSourceStart()`.

**Comment by algomaster99** [comment]
Ah, okay, Then this will apply to everything probably. So, `String` will have a length of 5 instead of 6. Thanks!
