### ISSUE TITLE
ActualTypeArguments are duplicated in CtConstructorCall and CtExecutableReference

### ISSUE THREAD

**Issue by leventov** [INRIA/spoon#599]
In the same situation `CtExecutableReferenceExpression` doesn't have "own" actualTypeArguments in addition to type args incapsulated in it's `CtExecutableReference`.

**Comment by leventov** [comment]
Seems that I confuse `CtExecutableReferenceExpression` and `CtInvocation`, but it applies to the latter as well.

**Comment by GerardPaligot** [comment]
I'll check that today.

**Comment by GerardPaligot** [comment]
> doesn't have "own" actualTypeArguments

@leventov Do you want to make something like `ctInvocation.getActualTypeArguments()` ?

**Comment by leventov** [comment]
@GerardPaligot I don't need that.
