### ISSUE TITLE
It should be impossible to configure actual type arguments for CtTypeParameterReference

### ISSUE THREAD

**Issue by leventov** [INRIA/spoon#600]
methods like `addActualTypeArgument()` should throw exception, because this is illegal things to do. But they have some logic currently in `CtTypeParameterReferenceImpl`.

**Comment by monperrus** [comment]
I'm not in favor of throwing an exception because it would require client code to add ugly try/catch.

however, you're right, and there should not be be code in  CtTypeParameterReference.addActualTypeArgument. We'll try to remove it and replace it by an appropriate comment.
