### ISSUE TITLE
CtElements.equals() returns true for elements which are not equal

### ISSUE THREAD

**Issue by leventov** [INRIA/spoon#602]
The new `HashCodeVisitor` presented here: https://github.com/INRIA/spoon/pull/601#issuecomment-212035743 produces different hash codes for ctElements that are considered equal by current `equals()` implementation. I can hardly imagine how the referenced `HashCodeVisitor` may produce different hash codes for elements that are _actually_ equal.

**Comment by monperrus** [comment]
The HashCodeVisitor you propose is too specific. Could you give a precise example of elements that should be considered equal?

**Comment by monperrus** [comment]
closing this issue, see #674
