### ISSUE TITLE
[Bug]: Problem with processing javax.persistence.* imports on Java 17 jakarta.persistence

### ISSUE THREAD

**Issue by GooDer** [INRIA/spoon#6026]
### Describe the bug

I encouter sort of bug / missing feature when trying to process domain classes with wildcard imports of javax.persistence which was replaced in java 17 with jakarta.persistence.

Since javax is no longer on classpath in Java 17 it can't be resolved and imports will fallback to package of actual class.
It works correctly  when imports are explicitly named and I understand the limitation in this case.

Would it be possible to provide some mapping for packages which are not available on class path so we will not get path to actual class?

Something like:

```java
Launcher spoon = new Launcher();
spoon.setPackageMapping("javax.persistence", "jakarta.persistence");
....
```

### Source code you are trying to analyze/transform

```Java
package com.some.package;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.*;

@Entity
@Table(name = "some_table")
public class SomeEntity {

}
```

### Source code for your Spoon processing

```Java
Launcher spoon = new Launcher();
spoon.getEnvironment().setNoClasspath(true);
spoon.getEnvironment().setComplianceLevel(17);
spoon.run();
```

### Actual output

```Java
package com.some.package;

import java.io.Serializable;
import java.util.Date;

@com.some.package.Entity
@com.some.package.Table(name = "some_table")
public class SomeEntity {

}
```

### Expected output

```Java
package com.some.package;

import java.io.Serializable;
import java.util.Date;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;

@Entity
@Table(name = "some_table")
public class SomeEntity {

}
```

### Spoon Version

11.1.0

### JVM Version

17

### What operating system are you using?

Windows 10

**Comment by I-Al-Istannen** [comment]
Is putting the class on the classpath (maybe even with the input class loader) not on the table for you? That would be the cleanest solution, as spoon can then actually introspect the classes.

**Comment by GooDer** [comment]
You are right, I didn't realiaze it would be the easiest :)
