### ISSUE TITLE
CtScanner.visitCtAnnotation() shouldn't iterate over annotation.getElementValues().values() manually

### ISSUE THREAD

**Issue by leventov** [INRIA/spoon#603]
Instead, it should delegate to genetic `scan(Collection)` method. This allows to override just `scan(Collection)` in some subclass of `CtScanner` and enjoy same behaviour for any elements (e. g. hashCodeVisitor from here: https://github.com/INRIA/spoon/pull/601#issuecomment-212035743 do this).

In `CtScanner`, `visitCtAnnotation()` is the only method where this rule is violated.

**Comment by monperrus** [comment]
Could you write a PR? Thanks.

**Comment by GerardPaligot** [comment]
I found this bug too when I developed my refactoring of replacing elements. @leventov you can write a PR or wait for my PR.
