### ISSUE TITLE
Distinguish between TypeParam declaration (types, methods) and TypeParamRefs

### ISSUE THREAD

**Issue by leventov** [INRIA/spoon#606]
With ability to search by refs like getDeclaration().

Currently code analysis and manipulation capabilities are limited because it's impossible to detect type parameter shadowing.

**Comment by monperrus** [comment]
I agree. This would be regular with the method parameter modeling. Interestingly, I guess this was partially the case in the past because we recently removed `CtTypeParameter`. I propose to reintroduce it named `CtFormalTypeParameter` (to make it more explicit).
