### ISSUE TITLE
Regarding recent PRs

### ISSUE THREAD

**Issue by leventov** [INRIA/spoon#618]
#607, #608, #609, #610, #611, #612, #613, #614, #615, #616, #617 

Also #596, #601 

 1. I'm not going to write tests for bug fixing commits (I don't have time for that.) IMO just review by Spoon maintainers is OK, each bug fix shouldn't be accompanied with a new test. It's your right not to accept those commits; but it is your interest to bet bugs fixed. I don't mind if you get my changes and commit yourself with tests, not preserving me as commit author. My goal is to merge bug fixes into Spoon master, not glory of being an author of any commits.

 2. Despite I didn't write tests, bug fixing commits represent real bugs, because I faced problems while using Spoon in real application and those fixes resolved that problems.

 3. Optimization fixes do make difference. Total `buildModel()` reduced 2-3 times (however, with some more optimizations, not yet PRed).

 4. All commits are independent so far, but I have more bug fixes and optimizations which depend on those PRs, and supporting them in all different branches is a hell. So I ask you to merge existing PRs as soon as possible and as many of them as possible, to give me ability to make more PRs.

**Comment by alcides** [comment]
I can confirm that I have been bitten by some of these bugs, and my test case is too large and still ongoing to include here.

**Comment by GerardPaligot** [comment]
@leventov You should create a new one with your name here: https://github.com/INRIA/spoon/blob/master/pom.xml#L49 :)

(You too @alcides)

**Comment by monperrus** [comment]
Thanks a lot for the many high quality PRs.

Note that optimization and refactoring PRs are the only one where no functional tests have to be written.

**Comment by GerardPaligot** [comment]
Excepting this PR https://github.com/INRIA/spoon/pull/616, all of your PRs have been merged. Again, thanks a lot for these contributions!
