### ISSUE TITLE
TypeInformation.getAllExecutables() is underspecified and unusable

### ISSUE THREAD

**Issue by leventov** [INRIA/spoon#621]
Specification says
```java
	/**
	 * Gets the executables declared by this type and by all its supertypes if
	 * applicable.
	 */
```

It doesn't say about destinction between static and instance executables, constructors, and what happens when overriding occurs.

`CtTypeImpl.getAllExecutables()` just puts everything into a hashSet, (relying on executable.equals(other), that is *not* the same as executable.overrides(other)), also it doesn't take into account default methods defined in super interfaces.

I would deprecate this method (or remove, depends on your compatibility rules).

**Comment by monperrus** [comment]
It should indeed be stated in the API doc:

* static and instance executables
* constructors
* what happens when overriding occurs.
* what about Java 8 default methods
