### ISSUE TITLE
SpoonClassNotFoundException : Cannot load class X with class loader ClassRealm

### ISSUE THREAD

**Issue by ttben** [INRIA/spoon#622]
Hi,

I'm trying to generate getter and setter methods for each field of an annotated Class.
I wrote a AbstractProcessor<CtClass<?>> implementation.

`List<CtField<?>> fields = ctClass.getFields();`

	for(CtField f : fields) {
		CtTypeReference returnType = getFactory().Code().createCtTypeReference(f.getType().getActualClass());
		//build method ...
	}

The `f.getType().getActualClass()` raise a `spoon.support.reflect.reference.SpoonClassNotFoundException: cannot load class: example.VariationPoint with class loader ClassRealm` exception.

I currently analyze a maven module from another maven module. But since the annotated Class are properly found (since the processor is triggered) I don't understand why the `getActualClass` method call fails.

The doc specify

> /** Spoon-specific ClassNotFoundException (simply encapsulates a ClassNotFoundException as a runtime exception) */

How can the class can be found and not found at the same time ?

Is there any workaround ? Did I do something wrong ?

**Comment by GerardPaligot** [comment]
Hi @ttben,

I have several questions:

1. Why do you need `getActualClass`? You can use methods in the `TypeFactory` (`getFactory().Type()`).
2. The type `example.VariationPoint` is in your current class loader?

**Comment by ttben** [comment]
Hi @GerardPaligot 

Thanks for your quick answer.

I'm trying to build getter and setter methods for each field. Since the `MethodFactory.create` expect a `CtTypeReference<T> returnType` parameter, I'm trying to build a method that has the return type of the field's type, therefore I'm trying to build a `CtTypeReference` from a the field's type. 

**But Thanks a lot ! I applied your advice and I worked fine.**

**Comment by GerardPaligot** [comment]
I didn't see it but `getFactory().Code().createCtTypeReference(f.getType().getActualClass());` is useless because you already have the `CtTypeReference` expected with `f.getType()`. If you really want a new object for your `CtTypeReference`, you can clone it with `getFactory().Core().clone(...)`.

Btw, everything seems ok now for you. Can we close your issue?

**Comment by ttben** [comment]
Yeah sure, thanks a lot :+1:
