### ISSUE TITLE
processor divides classes to different files

### ISSUE THREAD

**Issue by kribo852** [INRIA/spoon#626]
applying the processor:
public class TestErrorProcessor extends AbstractProcessor<CtClass> {

	@Override
	public void process(CtClass element) {
		System.out.println(element.getSimpleName());
	}
}

to the file SpoonErrorTest:
----------------------------------------
class A{}

public class SpoonErrorTest {

	public class E{
		A a;
	}
	B b;
	C c;
}

class B{}

class C{
 
	public class D{}
	
	D d;
}
---------------------------------
divides spoonErrorTest into 4 separate files:
---------------------------------
class A {}
class B {}
---------------------------------
class C {
    public class D {    }

    C.D d;
}
---------------------------------
public class SpoonErrorTest {
    public class E {
        A a;
    }

    B b;
    C c;
}
----------------------------------

It would be helpful if the structure was kept intact or if SpoonErrorTest imported A,B and C automatically after the restructuring.

**Comment by GerardPaligot** [comment]
Hi @kribo852,

Rewrite every class in separated class is a choice made by Spoon and shouldn't generate any error. Your classes `A`, `B` and `C` have a visibility `package` and can be accessed without import in `SpoonErrorTest`.

**Comment by monperrus** [comment]
you can change this behavior with `--output-type compilationunits`

**Comment by kribo852** [comment]
okay, thanks, we'll do that:)
