### ISSUE TITLE
Build model of source file(s) with missing dependencies

### ISSUE THREAD

**Issue by retuxx** [INRIA/spoon#628]
I want to analyze several medium to large size software projects with spoon. I've implemented a tool that automatically fetches all relevant files from a repository (SVN or GIT) and adds them to the launcher (`runLaunch.addInputResource(file);`). However,  I get the following error if one of the source code files imports a third party library:

`spoon.compiler.ModelBuildingException: The import <name> cannot be resolved`.

Is it possible to configure spoon such that imports of third party libraries are ignored when the library itself is not available (I think you already do this for classes of the standard library, such as String)? This is very important to me because I'm unable to make all libraries available at runtime.

The following listing gives a short example:

```java
// File: ImportBug.java
import gnu.getopt.Getopt;

public class ImportBug {

}
```

```Java
// My tool
private Launcher runLaunch = new Launcher();
runLaunch.addInputResource(file.getPath()); // file = ImportBug.java
runLaunch.buildModel(); // throws ModelBuildingException
```

**Comment by GerardPaligot** [comment]
You can use the no classpath mode : `runLaunch.getEnvironment().setNoClasspath(true);`.

**Comment by retuxx** [comment]
That is exactly what I was looking for, thank you!
