### ISSUE TITLE
Ternary Operator in Constructors Fails.

### ISSUE THREAD

**Issue by retuxx** [INRIA/spoon#631]
The following example does not work with spoon 5.1.0 (The code itself is not useful, it's for demonstration purpose only):

```java
import java.util.Date;

public class TernaryOperator {

    private Date currentDate;

    public TernaryOperator(Date date) {
        currentDate = new Date(date == null ? null : date);
    }
}
```

If I build the model with `Launcher#buildModel()` the following exception is thrown:

```java
java.lang.RuntimeException: arg
```

I found that spoon does not correctly handle ternary operators used in constructors. The exception is thrown in `CtReferenceImpl#setSimpleName(String simplename)`.

**Comment by tdurieux** [comment]
I don't know witch version of Java you use but in `Java 1.8` the constructor of `java.util.Date` does not accept a `java.util.Date` as parameter.

This error appears because the source code does not compile.
