### ISSUE TITLE
Bump Spoon source and binary compatibility to Java 7

### ISSUE THREAD

**Issue by leventov** [INRIA/spoon#643]
FYI

eclipse.jdt.core (at least the version this project depends on) is already incompatible with Java 6.

`java.lang.UnsupportedClassVersionError: org/eclipse/jdt/internal/compiler/batch/Main : Unsupported major.minor version 51.0`

**Comment by GerardPaligot** [comment]
Nice... We don't have any changelog since the version 3.4 of JDT (latest version is 4.6) and I thought that our source java version was enough. Bad point for me.

Btw, if JDT is no more compatible with Java 6, I don't know what I can say you @leventov. Do you need this compatibility?

**Comment by leventov** [comment]
BTW -- why you switched from `ecj` artifact to the current? `ecj` is only 2.3 MB while the new one is 5.8 MB.

New ecj version clearly points to 1.7 compat -- https://repo1.maven.org/maven2/org/eclipse/jdt/core/compiler/ecj/4.5.1/ecj-4.5.1.pom

**Comment by leventov** [comment]
@GerardPaligot I don't need that much.

**Comment by GerardPaligot** [comment]
> BTW -- why you switched from ecj artifact to the current? ecj is only 2.3 MB while the new one is 5.8 MB.

When I [updated JDT](https://github.com/INRIA/spoon/commit/ca6344cc06d17db456ca6437d84b4edfac3e12c7) in Spoon (we needed a fix), JDT 4.5 wasn't published in Maven Central (see the [date of the deploy](https://repo1.maven.org/maven2/org/eclipse/jdt/core/compiler/ecj/) between 4.4.2 and 4.5). The main maintainer of the dependency said me that they lost credentials to publish it on Maven Central and they don't push anymore the dependency in standalone on their Maven repository and on Maven Central.

> New ecj version clearly points to 1.7 compat

Yes.

**Comment by leventov** [comment]
I tried  to change dep back to `ecj:4.5.1`, but it didn't compile.

**Comment by tdurieux** [comment]
The class `CommentRecorderParser` used to parse comment is not packaged in ecj.
But this class depends  only on ecj.

**Comment by monperrus** [comment]
Since JDT has dropped support for Java 6, I'm fine with bumping Spoon compatibility to Java 1.7. If anybody is against this, please tell us before May 15.

**Comment by leventov** [comment]
I'm against abandoning support of _analyzed_ source compilanceLevel. I. e. I want `Environment.setCompilanceLevel(6)` to continue to work correctly.

**Comment by GerardPaligot** [comment]
No problem for that. We can continue to analyse Java 6 (even 5 or 4) source code.

**Comment by leventov** [comment]
When translating to Java 7 source compat don't forget about https://github.com/INRIA/spoon/blob/cddf400c69d5bfb08b01fdaf672175a8c5dbc193/src/main/java/spoon/reflect/factory/FactoryImpl.java#L290

**Comment by GerardPaligot** [comment]
Good to know. Thanks.
