### ISSUE TITLE
Adds a check about binary compatibility of dependencies

### ISSUE THREAD

**Issue by GerardPaligot** [INRIA/spoon#644]

**Comment by leventov** [comment]
Basically the way to do this is to actually run tests with old JDKs. Travis CI allows to do this pretty easily: https://github.com/OpenHFT/Zero-Allocation-Hashing/blob/master/.travis.yml

**Comment by GerardPaligot** [comment]
I can't use this solution, we need Java 8 for test cases. I'll integrate a maven plugin about this.
