### ISSUE TITLE
environment/factory option to skip sanity checks

### ISSUE THREAD

**Issue by leventov** [INRIA/spoon#649]
In production, it is crucial to have an option like `Launcher.skipSelfChecks = true`, which

 - disables AstParentConsistencyChecker
 - disables contract check in CtElement.equals/hashCode
 - disables contract signature checks in `CtTypeImpl.addMethod()` (however, as I mentioned here: https://github.com/INRIA/spoon/pull/646#issue-153078874 this check is always at least not useful, sometimes harmful)

**Comment by monperrus** [comment]
I'm OK with such an option, however, we would keep the checks enabled by default.

**Comment by leventov** [comment]
Yes, of cause default setting should checks=on.
