### ISSUE TITLE
ClassCastException: spoon.support.reflect.code.CtLambdaImpl cannot be cast to spoon.reflect.declaration.CtConstructor

### ISSUE THREAD

**Issue by arnobl** [INRIA/spoon#664]
Hi,
I just want to get the parameter references of a lambda using this code: 
`lambda.getParameters().stream().map(param -> param.getReference()).collect(Collectors.toList())`

The following exception then occurs:
```
java.lang.ClassCastException: spoon.support.reflect.code.CtLambdaImpl cannot be cast to spoon.reflect.declaration.CtConstructor
	at spoon.reflect.factory.ExecutableFactory.createReference(ExecutableFactory.java:105)
	at spoon.reflect.factory.ExecutableFactory.createParameterReference(ExecutableFactory.java:86)
	at spoon.support.reflect.declaration.CtParameterImpl.getReference(CtParameterImpl.java:63)
```

Here is a code example that produces the crash.
```
class Foo {
	public void foo() {
		JButton b = new JButton();
		b.addActionListener( e -> {
			System.out.println(e);
		});
	}
}
```

The problem appears with both 5.1 and 5.2-SNAPSHOT

**Comment by GerardPaligot** [comment]
Hi @arnobl,

Thanks for your report. A PR is done here with a fix: https://github.com/INRIA/spoon/pull/665.

**Comment by monperrus** [comment]
looks good, I wait for Travis and merge
