### ISSUE TITLE
put comments as ctstatement only if -j flag is present

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#666]
Discussion for @arnobl use case

Proposal: widen the scope of -j flag as follows:
put comments as ctstatement only if -j flag is present
and update the documentation of the -j flag:
-j consider documentation:
this flags enables the documentation handling: adds statement comments in the model, rewrite comments on pretty-printing

**Comment by tdurieux** [comment]
I don't think it is a good idea to use the `-j` flag for enabling/disabling both parsing and printing comments.
From my point of view it's much better to have two options: 1. parsing, 2. printing. Basically the option that you asked my to remove.
