### ISSUE TITLE
Spoon remove parenthesis in ternary operator with assigment

### ISSUE THREAD

**Issue by dima74** [INRIA/spoon#668]
Hello, thank you for Spoon!
There is a little problem, if I run Spoon on this class
```
public class Main {
	public static void main(String[] args) {
		boolean a;
		int x = (a = true) ? 7 : 666;
	}
}
```
then I have next:
```
public class Main {
    public static void main(java.lang.String[] args) {
        boolean a;
        int x = a = true ? 7 : 666;
    }
}
```
So, parenthesis are missing and resulting code doesn't compile.

**Comment by GerardPaligot** [comment]
Nice. Spoon puts too much parenthesis everywhere, except here. :)

PR as soon as possible.

**Comment by dima74** [comment]
Thank you!
