### ISSUE TITLE
NPE at JDTTreeBuilder:415

### ISSUE THREAD

**Issue by tdurieux** [INRIA/spoon#671]
Last week I encounter a NPE when I spoon Closure Compiler at [JDTTreeBuilder:415](https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java#L415).
Because I some case `context.compilationunitdeclaration.imports` is `null`.
I fix the problem by putting the `if` at [JDTTreeBuilder:2232](https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java#L2232) in the `else` of the previous `if`.
@GerardPaligot  Do you remember why it is not currently the case?

I did not succeed to reproduce the NPE in a test.

**Comment by GerardPaligot** [comment]
@tdurieux Linked with this PR? https://github.com/INRIA/spoon/pull/633 :)

**Comment by tdurieux** [comment]
I suppose   :)

Do you have an answer to this question:
> @GerardPaligot Do you remember why it is not currently the case?
