### ISSUE TITLE
add support for empty statements

### ISSUE THREAD

**Issue by tdurieux** [INRIA/spoon#673]
Example:

```java
public class M {
   public void m() {
     label:;
   }
}
```

The line in the method `m` is ignored by spoon.

**Comment by GerardPaligot** [comment]
For me, shouldn't be supported by Spoon.

**Comment by retuxx** [comment]
> For me, shouldn't be supported by Spoon.

Why?

**Comment by GerardPaligot** [comment]
It implies that we should support source code like this:

```java
class Test {
  ;
  void m() {
    ;
  }
}
```

**Comment by seintur** [comment]
And so what?

**Comment by retuxx** [comment]
I think there is a difference between a `;` and a `label`. `;` are ignored by concept because of being delimiters. A `label`, on the other hand, is an actual element of the programming language, IMHO.

**Comment by GerardPaligot** [comment]
I don't see use cases where it is interesting to make analysis with an empty statement. Here:

```java
public class M {
   public void m() {
     label:;
   }
}
```

@retuxx Labels are already supported by Spoon, but empty statement not and labels are attached to a statement.

**Comment by retuxx** [comment]
> [...] and labels are attached to a statement.

I see.
