### ISSUE TITLE
feature: add support for analysis of binary code with a decompiler and shadow classes

### ISSUE THREAD

**Issue by msteinbeck** [INRIA/spoon#675]
It would be nice to have some sort of decompiler in spoon. This way visitors that gather metrics for entities (for instance the ATFD metric of particular classes) could access functions of libraries.

**Comment by monperrus** [comment]
I agree this would be nice,  this point is indeed already in the roadmap. if you'd like to work on it soon, we can give you some hints.

**Comment by retuxx** [comment]
>  if you'd like to work on it soon, we can give you some hints.

What do you mean by that. Is there some code available already?

**Comment by tdurieux** [comment]
I used several month ago a decompiler in order to improve the usage of the templates:
https://github.com/INRIA/spoon/pull/464/files

@GerardPaligot checks several java decompiler but none are perfect.

**Comment by GerardPaligot** [comment]
After my researches, the best one seems to be CFR (http://www.benf.org/other/cfr/) but yes, it isn't perfect.

**Comment by retuxx** [comment]
> [...] but yes, it isn't perfect.

It doesn't have to be perfect IMHO.

**Comment by retuxx** [comment]
So do you have plan to integrate one of the mentioned decompiler into spoon?

**Comment by GerardPaligot** [comment]
We made some researches but we don't have any plan to integrate it at the short term.

**Comment by monperrus** [comment]
Reopening this issue, because it's relevant and @nharrand is interested in it

**Comment by monperrus** [comment]
as decompiler, I had good results in the past with CFR: http://www.benf.org/other/cfr/

**Comment by nharrand** [comment]
We might also want to consider these:
[Krakatau](https://github.com/Storyyeller/Krakatau)
[Procyon](https://bitbucket.org/mstrobel/procyon/wiki/Java%20Decompiler)
[fernflower](https://github.com/fesh0r/fernflower)

**Comment by monperrus** [comment]
Actually, @gluckzhang may use such a feature also!

**Comment by nharrand** [comment]
I guess this issue could be closed now that we have a `spoon-decompiler` module.

**Comment by monperrus** [comment]
yes!

**Comment by monperrus** [comment]
Food for thought:
Beyond Binary Program Transformation
https://pdfs.semanticscholar.org/e5c2/9d46c1300ab5353bb4df08ed04a0ea9ec80a.pdf

**Comment by SeanCoek** [comment]
It seems JarLauncher only support jar files analysis. Is other kind of format be support? say "war" file or just the original bytecode files with project directory.

**Comment by nharrand** [comment]
Since #3124  `DecompiledResource` can be used to handle any file the decompiler accept.

**Comment by monperrus** [comment]
FYI
Flybytes is an intermediate language between JVM bytecode and software languages (DSLs, PLs), for compilation and decompilation. 
https://github.com/cwi-swat/flybytes
