### ISSUE TITLE
Wrong SourcePositionImpl#getSourceEnd()

### ISSUE THREAD

**Issue by maxcleme** [INRIA/spoon#687]
To reproduce :

Build model from this [file](https://github.com/petitpre/iosched/blob/Ready/android/src/main/java/com/google/android/apps/iosched/ui/SessionDetailFragment.java) with "-x" flag.

Then access to all CtField and inspect positions,

For the field "mGlobalLayoutListener", it return : 

> sourceStart : 7610
> sourceEnd : 7905

Start is right, but end is wrong.

**Comment by tdurieux** [comment]
I cannot reproduce, as you can see in this test the position of the field is correct.
https://github.com/tdurieux/spoon/commit/4e5e021fc8dd7cd289d385547fd17b61e4b8ce0c#diff-e09c079157c689c149987c4c52abdcbeR245

**Comment by tdurieux** [comment]
To clarify, I obtain the same sourceStart, sourceEnd but for my the sourceEnd is correct.

The sourceEnd represent the end of the default value of the field.

**Comment by maxcleme** [comment]
> The sourceEnd represent the end of the default value of the field.

Actually, that's why I tought it was wrong. Thanks for clarification.

**Comment by tdurieux** [comment]
sourceStart and sourceEnd of a element contains all sub elements:
* the javadoc
* the default value of field and variable 
* annotations
* the ";" when the element is a line 
* the body of methods

**Comment by GerardPaligot** [comment]
@maxcleme We can close or this PR https://github.com/INRIA/spoon/pull/691 is linked?

**Comment by maxcleme** [comment]
@GerardPaligot Yes you can close it, thank.
