### ISSUE TITLE
Bug on array types

### ISSUE THREAD

**Issue by mehdijk** [INRIA/spoon#690]
Sometimes, when a method type is an array of a class, calling the `ctMethod.getType()`  get `java.lang.reflect.Array` instead of `package.className[]`

**Comment by GerardPaligot** [comment]
Hi @mehdijk,

Assuming we have this method:

```java
int[] m() {
  return new int[0];
}
```

You got this:

```java
final CtMethod<Object> m = aType.getMethod("m");
System.err.println(m.getType());  // int[]
System.err.println(m.getType().getSimpleName()); // Array
System.err.println(m.getType().getQualifiedName()); // java.lang.reflect.Array
System.err.println(m.getType().getClass()); // CtArrayTypeReference
System.err.println(((CtArrayTypeReference) m.getType()).getComponentType()); // int
```

**Comment by mehdijk** [comment]
Hi
I use `m.getType().tostring()`. Just now I couldn't find the counterexample.
However It is OK with me.
Thanks for explanation.
