### ISSUE TITLE
Innet types

### ISSUE THREAD

**Issue by mehdijk** [INRIA/spoon#692]
When a method return type is an inner class, the output of  `ctMethod.getType().toString()` is `package.class.innerclass` but I expect the `package.class$innerclass` because when we try to get `CtClass` by name `factory.Class().get(clazzName)`, we should use this format `package.class$innerclass`

**Comment by GerardPaligot** [comment]
Use `ctMethod.getType().getQualifiedName()` to get the qualified name of your `CtTypeReference`.
The qualified name isn't the contract of the `toString()` method.

**Comment by mehdijk** [comment]
Ok
It works, except for array of inner class. I handle it.  
Thanks
