### ISSUE TITLE
Which filter

### ISSUE THREAD

**Issue by mehdijk** [INRIA/spoon#693]
I want to find all of the executable which access to an item of a `ctType` as local variable, parameter, return type, field type,... . Which filter should I use? 
I use this command but It gets other results:
```
List<CtElement> elementList = rootPack.getElements(new RegexFilter(typeName));
for( CtElement elementItem:elementList)
     ctexe = elementItem.getParent(CtExecutable.class);
```

**Comment by tdurieux** [comment]
```java
ctType = expectedType;
List<CtTypedElement> elementList = rootPack.getElements(new TypeFilter<CtTypedElement>(CtTypedElement.class) {
	@Override
	public boolean matches(CtTypedElement element) {
		return super.matches(element) && element.getType().equals(ctType);
	}
});
```

**Comment by mehdijk** [comment]
Thanks @tdurieux 
It works. But I use `element.getType().equals(ctClazz.getReference())` for the second part of condition.  The program freezes on that part.

**Comment by GerardPaligot** [comment]
Freeze? Maybe you should create the reference of your `ctClazz` only one time?

**Comment by mehdijk** [comment]
Hi @GerardPaligot
I used this command  `return super.matches(element) && ctType.equals(element.getType());` but the program freezes on it and I waited for several minutes. So I replaced it with this command:    `return super.matches(element) && element.getType().equals(ctClazz.getReference());` It works. But I don't know what is the difference.

**Comment by GerardPaligot** [comment]
What is the difference between `ctType` and `ctClazz`?

**Comment by mehdijk** [comment]
No difference. That was my typo error.

**Comment by GerardPaligot** [comment]
Ok, I see the performance issue.

`ctType` (or `ctClass`) is typed by `CtType` (or `CtClass`) and `ctType.getReference()` creates a `CtTypeReference`. The difference is big because a `CtTypeReference` is only a name and a `CtType` is your Java class.

In your case, `element.getType()` returns a `CtTypeReference` so you should use `ctType.getReference()`.

btw, can we close your issue?

**Comment by mehdijk** [comment]
Yes. Thank you
