### ISSUE TITLE
Why not use javac & compiler tree api?

### ISSUE THREAD

**Issue by leventov** [INRIA/spoon#697]
are there reasons why you prefer ECJ over javac? I suppose when spoon was started compiler tree api didn't exist yet, but now it seems to be a better option.

**Comment by tdurieux** [comment]
Personal opinion: I thing such big change will not append soon because it means to create a new JavaCTreeBuilder to replace the current JDTTreeBuilder. This change will be long, complex and the capital gain is unclear.

Last time a check JavaC AST API, I did not find the way to bind expressions between files (compute unit). I feel that the compute units are independent.

Did you investigate JavaC?

**Comment by monperrus** [comment]
Back in 2006 the JDT API was much better.

Since we now have a strong test suite and JavaC has much evolved, I'd be
happy to consider a PR replacing JDTTreeBuilder by JavaCTreeBuilder.

What advantage would you expect?

**Comment by leventov** [comment]
@monperrus could you please elaborate on this? How it was "much better"?

JdtTreeBuilder is unsupportable. Recently I've tried to commit some of my changes, but it simply doesn't work. Depending on changes, one or another test cases fail (builder stops to parse certain cases correctly). I also think that javac has less bugs itself.

**Comment by petitpre** [comment]
In the first release if spoon, we use javac to build spoon model. But in
2006, the javac ast was really difficult to use.

At this time, we worked on a spoon eclipse plugin that should compile
partial source files. We decide to use jdt, which was really simplier to
use.

I agree with you, jdttreebuilder is really complexe (and ugly), but it will
be difficult to replace it soon...

**Comment by retuxx** [comment]
I think there is no reason to switch the AST library. JDT works great and is actively developed by a huge community. Unlike other libraries such as `javaparser`, spoon supports cross referencing. That is, you are able to get node of elements located in other compilation unit. Thats a great feature. I'm unsure whether you can realize this feature with other libs.

**Comment by retuxx** [comment]
> JdtTreeBuilder is unsupportable. Recently I've tried to commit some of my changes, but it simply doesn't work.

So we should try to enhance its maintainability rather than replacing the module.

**Comment by GerardPaligot** [comment]
I agree, `JDTTreeBuilder` is unsupportable but @petitpre resumed well the situation, it'll be difficult to change it.

For me, the better solution is a big refactoring of the actual `JDTTreeBuilder` but it is a lot of work too (less than change JDT to javac).

**Comment by retuxx** [comment]
> I agree, JDTTreeBuilder is unsupportable [...]

Maybe analyzing spoon with SonarQuebe gives some hints how to enhance its maintainability.
