### ISSUE TITLE
Running tests locally -- random fails due to "File .\Tmp.java is missing"

### ISSUE THREAD

**Issue by leventov** [INRIA/spoon#706]
snippet compilation error while compiling: class Wrapper ... Caused by java.lang.IllegalArgumentException: File .\Tmp.java is missing

-- I often experience such errors when running tests locally from within my IntelliJ and command line. Am I the only one who has such fails?

**Comment by GerardPaligot** [comment]
All 747 tests passed with IntelliJ and Maven on master branch.

But I'm on OS X. Maybe there is an issue with paths on Windows in our test cases.

**Comment by leventov** [comment]
@monperrus @tdurieux also using OS X or Linux?

**Comment by tdurieux** [comment]
Me and monperrus are on Linux, all 747 tests passed with IntelliJ, Maven. I did not try with Eclipse.

**Comment by monperrus** [comment]
when we'll identify the problem, we'll update the appveyor config to catch this kind of issue, it's its job!

**Comment by monperrus** [comment]
it seems we have no way to diagnose this one, hence closing it, don't hesitate to propose a PR if you identify the issue.
