### ISSUE TITLE
Code duplication between CtScanner, CtBiScanner and ReplacementVisitor

### ISSUE THREAD

**Issue by leventov** [INRIA/spoon#708]
Currently logic is duplicated in three places that is dangerous from support POV, especially considering that CtScanner is a permanent source of bugs.

CtBiScanner could be implemented via CtScanner without duplicating logic, e. g. see https://github.com/INRIA/spoon/issues/636#issuecomment-216770223

IIRC @GerardPaligot mentioned that ReplacementVisitor is auto-generated from CtScanner, however for me it doesn't work. I should fix ReplacementVisitor manually. Also, if it is auto-generated, why it is checked into git in the first place?

**Comment by GerardPaligot** [comment]
> especially considering that CtScanner is a permanent source of bugs.

Yes, we should generate it too.

> IIRC @GerardPaligot mentioned that ReplacementVisitor is auto-generated from CtScanner, however for me it doesn't work.

Why? You have a replace which doesn't work?

> I should fix ReplacementVisitor manually. Also, if it is auto-generated, why it is checked into git in the first place?

I agree with you but to do that, we should have a multi-module project or a new project in dependency in this one to apply some processors and generate source code wanted.

**Comment by monperrus** [comment]
> Also, if it is auto-generated, why it is checked into git in the first place?

because it is required by the current lean build process.

note that there is a test that checks that the generated code is not overwritten by hand (see `CtScannerTest.testGenerate*`)

**Comment by leventov** [comment]
> Why? You have a replace which doesn't work?
I mean that I need to pay attention that if I change something I should change some other place of code also, it is not automatic.

**Comment by monperrus** [comment]
closing this one, don't hesitate to reopen if appropriate.
