### ISSUE TITLE
Deprecate CtInvocation/CtConstructorCall/CtNewClass.get/set/addActualTypeArgs

### ISSUE THREAD

**Issue by leventov** [INRIA/spoon#714]
Because they now delegate to executable.get/set/addActualTypeArgs, i. e. left for compatibility, but for unambiguity and least astonishment, the new code should use ctInvocation.getExecutable.xxxActualTypeArgs.

Also I think it's a good practice for all such situations, when setters/getters/adders are left for compatibility but doesn't change/access own node's fields (but rather fields of the fields or syntetic), to mark such compatibility proxy methods as deprecated.

**Comment by monperrus** [comment]
I'm not in favor of deprecating them because they can be useful, but more for documenting the delegation in the interface `CtActualTypeContainer`. what do you think?
