### ISSUE TITLE
Comments not included in pretty print unless both generateJavadoc and commentsEnabled are set

### ISSUE THREAD

**Issue by seanf** [INRIA/spoon#721]
I had to set the option `generateJavadoc` (which is deprecated), not just `commentsEnabled`, to have all comments printed. (I think the problem was only triggered if there was a class-level javadoc.)

I think the boolean logic in the `getComment`/`printComment` methods of `DefaultJavaPrettyPrinter` like this:

    if (!env.isGenerateJavadoc() || !env.isCommentsEnabled() || e == null)

should probably be something like this:

    if (!(env.isGenerateJavadoc() || env.isCommentsEnabled()) || e == null)

SNAPSHOT version: spoon-core-5.2.0-20160622.235104-91

**Comment by seanf** [comment]
Thanks!

**Comment by GerardPaligot** [comment]
you're welcome! :)
