### ISSUE TITLE
Bug with setVisibility when cloning a method

### ISSUE THREAD

**Issue by seintur** [INRIA/spoon#726]
Dear spooners,

When cloning a method and setting the visibility of the clone, the visibility is also modified on the original method. It looks like the original and the clone are entangled and share the same visibility.

The spoon.test.method.MethodTest#testClone test in the branch https://github.com/seintur/spoon/tree/ctmethodclone_bug illustrates the issue.

Lionel.

**Comment by GerardPaligot** [comment]
The bug occurs even with your second commit https://github.com/seintur/spoon/commit/b42ebf377d93a06c4f5f28256e12c729ab77415a?

**Comment by seintur** [comment]
Yes, you can try.

My guess is that the set of modifiers is not copied when cloning the method, just referenced in the clone as it is in the original method.
