### ISSUE TITLE
Enum Value as annotation type value not possible

### ISSUE THREAD

**Issue by red-hood** [INRIA/spoon#750]
I am trying to annotate a field via the annotation factory, and would like to set the value of an annotation element to an enum value, e.g.

`annoFactory.annotate(field, BoundNumber.class, "byteOrder", ByteOrder.LittleEndian);`

where ByteOrder.LittleEndian is the enum value. Running the annoation processor, I get the error message

> "Please, submit a valid value."

In CtAnnotationImpl.java, starting at line 88, the annotation values passed in are converted to CtExpression values, but I can not find any clause that would match en enum value. What is the proper way to convert an enum value as shown above to the according CtExpression instance?

**Comment by monperrus** [comment]
in method `annotate`, there is some magic to transform , but not  is wrongly typed, the last element should indeed be a CtExpression. 

In this case, a workaround is that the last element is a CtFieldRead that corresponds to ByteOrder.LittleEndian. It's cumbersome, I agree. 

We have to improve convertValueToExpression to handle enum vaues.

**Comment by red-hood** [comment]
Thank you, I tried a CtVariableRead, but that did not work for me. It would be good to have an overview, which elements in the Java language actually correspond to which Ct element wrappers, I think.

**Comment by red-hood** [comment]
Thank you for the quick fix!
