### ISSUE TITLE
exception in noclasspath with ternary expressions due to PolyTypeBinding

### ISSUE THREAD

**Issue by retuxx** [INRIA/spoon#751]
Hi @GerardPaligot,

Finally I found a (more ore less) short example which shows the bug reported in PR #635. The attached zip archive contains the two directories `data` and `transformators` that, in turn, contain several Java files. I'm using the following code to build a Spoon model:

```java
Launcher runLaunch = new Launcher();
runLaunch.getEnvironment().setNoClasspath(true);
runLaunch.addInputResource(projectPath);
runLaunch.buildModel();
return runLaunch.getFactory().Package().getRootPackage();
```

with `projectPath` being the path to the unzipped directory, for example, `/home/GerardPaligot/ternary-bug`. Unfortunately, the code listed above results in an exception:

```
Exception in thread "main" spoon.SpoonException: A reference can't have a "?" in its name.
```

You will find the ? operator in `transformators/IssueTransformator.java` line 86. However, if you delete one of the files contained in `data`, for instance, `data/entities/User.java` the exception is not thrown, though, `transformators/IssueTransformator.java` has not been modified.

I hope this examples helps to understand the issue.

[ternary-bug.zip](https://github.com/INRIA/spoon/files/369278/ternary-bug.zip)

**Comment by retuxx** [comment]
As far as I can see, the difference when deleting one of the mentioned files is that:

[if (allocationExpression.binding != null)](https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java#L2139)

becomes `true` and, thus:

[references.getTypeReference(b)](https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java#L2149) is omitted.

**Comment by GerardPaligot** [comment]
The bug doesn't come from Spoon but JDT.

I create a test case with your zip file and the source code impacted by the bug is this part:

```java
return new TOIssue(
		issue.getId(),
		issue.getIdentifier(),
		issue.getTitle(),
		issue.getDescription(),
		issue.getUrl(),
		issue.getAuthor().getRepresentativeName(),

		labels,
		versions,

		Date.from(issue.getCreatedAt().toInstant()),
		closedAt == null ? null : Date.from(issue.getClosedAt().toInstant()),

		issue.getIssueType().toString());
```

In `JDTTreeBuilder`, we build the `CtConstructorCall` and we iterate on all arguments. All types of these arguments are good, except for `closedAt == null ? null : Date.from(issue.getClosedAt().toInstant())`.

See all these types on the capture below:

![capture d ecran 2016-07-27 a 16 12 51](https://cloud.githubusercontent.com/assets/1913901/17178340/61922a22-5415-11e6-80f4-57ff324f6733.png)

I can create an issue on the JDT bug tracker but I'm not very optimistic... They don't like bug report on noclasspath errors.

**Comment by monperrus** [comment]
what about simply removing the throw exception?

**Comment by retuxx** [comment]
I'm not entirely sure if this really is a JDT related issue. I found that the parameter `closedAt == null ? null : Date.from(issue.getClosedAt().toInstant())` is a `PolyTypeBinding` (as we can see in your screenshot) which holds a `ConditionalExpression`. This `PolyTypeBinding` gets processed by `JDTTreeBuilder` in [line 930](https://github.com/INRIA/spoon/blob/f57cd71363273703a8b31364fb206eb50df75f4e/src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java#L930) by utilizing the `ReferenceBuilder` to retrieve the type reference (`parameters.add(references.getTypeReference(b));`) of the parameter. The `CtTypeReference` is created by calling [binding.readableName()](https://github.com/INRIA/spoon/blob/76b364813dc954edee1eb75c2d712a833731bcc1/src/main/java/spoon/support/compiler/jdt/ReferenceBuilder.java#L682) which returns the String "closedAt == null ? null : Date.from(issue.getClosedAt().toInstant())". This String is passed to `ref.setSimpleName` which finally throws the mentioned exception.

So, I think the issue results from `binding.readableName()` returning a String containing a "?". Although this function is part of JDT, the returned String makes sense since the readable name of a `ConditionalExpression` actually contains a "?". I'm not sure how to fix the issue yet, but I think it should be fixed by Spoon not by JDT.

**Comment by retuxx** [comment]
> what about simply removing the throw exception?

I will try it.

**Comment by GerardPaligot** [comment]
@retuxx JDT shouldn't return a `PolyTypeBinding` but a `BinaryTypeBinding` of a `Boolean` type. The type isn't evaluated by JDT and returns a bad type. `allocationExpression.argumentTypes` should returns all types evaluated by JDT for the constructor call and a `PolyTypeBinding` with `closedAt == null ? null : Date.from(issue.getClosedAt().toInstant())` isn't a type.

@monperrus You want to remove a production check? You? :)

**Comment by retuxx** [comment]
@GerardPaligot Doesn't this imply that the provided source code is not compilable with Eclipse?

**Comment by GerardPaligot** [comment]
@retuxx Not necessarily but there may be strange behavior.

**Comment by retuxx** [comment]
Could Spoon evaluate the type by its own?

**Comment by GerardPaligot** [comment]
Unfortunately, not. Maybe @tdurieux or @monperrus have an idea to know how we can do this without removing the production check?

**Comment by retuxx** [comment]
What about finding the common base type of the `if` and `else` expression and use its name to setup the simple name?

**Comment by tdurieux** [comment]
It's not a bug of JDT.
The correct fix is to create a CtMultiTypeReference in spoon.

A workaround will be to create a CtTypeRefence of a object.
You can do it by adding the following snippet in https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/support/compiler/jdt/ReferenceBuilder.java#L678
```java
                else if (binding instanceof PolyTypeBinding) {
			ref = this.jdtTreeBuilder.getFactory().Core().createTypeReference();
			ref.setImplicit(isImplicit || !this.jdtTreeBuilder.getContextBuilder().isLambdaParameterImplicitlyTyped);
			ref.setDeclaringType(this.jdtTreeBuilder.getFactory().Type().objectType());
			ref.setSimpleName(Object.class.getCanonicalName());
		}
```

**Comment by retuxx** [comment]
Ok, `Object` should always be a common base type :)

**Comment by retuxx** [comment]
Any progress here? I'm really looking forward to have this work.

**Comment by tdurieux** [comment]
We are trying to figure out when JDT uses PolyTypeBinding, in order to create the best patch.
But there is no doc for PolyTypeBinding...

Did you try my snippet?

**Comment by retuxx** [comment]
> Did you try my snippet? 

Not yet. I thought this is more a quick hack than a proper fix.

**Comment by tdurieux** [comment]
We suspect that the PolyTypeBinding is a class only used in noclasspath mode.
We don't went to introduce a new element in the spoon Model to support this JDT element.
And we don't have a lot information to be more intelligent (due to no classpath). 

In this case we can be more intelligent because the left element of the ternary expression is `null` but in general case we do not know the smallest parent class.

**Comment by retuxx** [comment]
> We don't went to introduce a new element in the spoon Model to support this JDT element.

Sounds like you don't want to fix this issue in general, right?

**Comment by tdurieux** [comment]
I want this fix the issue without creating a new element.
I don't really like the idea of creating an element that is used only in noclasspath, especially for an element that we don't know the usage.

**Comment by retuxx** [comment]
Ok. Nice to see you are working on it.

**Comment by retuxx** [comment]
> In this case we can be more intelligent because the left element of the ternary expression is null but in general case we do not know the smallest parent class.

I think it is perfectly fine to assume that `Object` is the common base class. It's the best bet you can make in `noclasspath` mode.
