### ISSUE TITLE
Support for easily updating the model with addTypes

### ISSUE THREAD

**Issue by retuxx** [INRIA/spoon#752]
Is it possible to update individual input files of an already build model? For instance, I created a Spoon model for a Java project. After running some visitors I want to update the content of a single file and update the model rather than create a new one (which may take some time in case of large sized projects).

**Comment by monperrus** [comment]
> I  want to update the content of a single file

it looks like feature #456

**Comment by monperrus** [comment]
> After running some visitors I want to update the model rather than create a new one 

Do the visitors change the model?

**Comment by retuxx** [comment]
No, its an external change. For instance, someone opens the file with a text editor,  adds some lines of code, and saves it.

**Comment by monperrus** [comment]
then, you can create a partial model in noclasspath mode of the changed files and add it to existing model. Something like:

```
SpoonAPI update = new Launcher();
update.addInputResource("changed.java");
update.buildModel();
oldModel.addTypes(update.getModel().getAllTypes())
```
(you may have to manually remove the previous version of updated types first)

**Comment by retuxx** [comment]
@monperrus Sorry, but I can't find the method `addTypes`. Which class provides this method?

**Comment by GerardPaligot** [comment]
Hi @retuxx,

`oldModel` (in the snippet of Martin) is a variable typed by `CtModel` and you can also find the method `addTypes` in `CtPackage`.

Hope that help you! :)

**Comment by retuxx** [comment]
If I update, for instance, a single file and update its corresponding type(s) according to your approach, will the updated type(s) know about all other types of the (main) model?

**Comment by monperrus** [comment]
yes, it should be the case, since the lookup of declarations is dynamic.

**Comment by retuxx** [comment]
So, will you add a convenience method for updating files to Spoon, or do I have to implement it on my own? I'm fine with both.

**Comment by monperrus** [comment]
you can have a look at `testCtModel` and `testIncrementalModel` in
FactoryTest, it does something close to what you need.

if the API can be improved according to your needs, your suggestions and
pull requests are welcome.

**Comment by retuxx** [comment]
@monperrus 
> (you may have to manually remove the previous version of updated types first)

How do I get all types of a specific Java file?

**Comment by GerardPaligot** [comment]
From the compilation unit of your Java file: `compilationUnit.getTypes()`.

**Comment by monperrus** [comment]
@retuxx do you work on this on can we close the issue?

**Comment by retuxx** [comment]
Currently, I'm not working on this issue, though,  I'm planning to do. Close this issue if you want. I will reopen it if necessary. You hints should be enough to implement a proper fix.

**Comment by monperrus** [comment]
OK, I'm closing it for now.
