### ISSUE TITLE
Bad smell in ExpressionTemplate: (im)possible null reference?

### ISSUE THREAD

**Issue by red-hood** [INRIA/spoon#754]
Hi,

in https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/template/ExpressionTemplate.java#L68
c is checked for being null after first calling

`targetType.getFactory().Class().get(this.getClass());`

, if it is null, the same method is called again, without checking the return value once. Is that a bug, or is this method supposed to have some strange side effects, which would make it return the actual object on the 2nd call?

**Comment by GerardPaligot** [comment]
@red-hood Thanks to report this code smell. :)

**Comment by red-hood** [comment]
@GerardPaligot Sure, thank you for the quick reply. I stumbled over that part, when analysing an NPE, so I thought it was a good idea to report it.
