### ISSUE TITLE
happy wedding to top Spoon contributor @GerardPaligot 

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#757]
<img src="http://img2.timeinc.net/people/i/2015/news/150216/star-wars-800.jpg"/>

**Comment by retuxx** [comment]
Congratulations!

**Comment by GerardPaligot** [comment]
Big thanks @monperrus! :)

Of course, my wedding wasn't a geek wedding (my wife wouldn't be happy :D) but it was wonderful!

See you all soon, I see there is a lot of work for me! héhé
