### ISSUE TITLE
Preserve import ordering?

### ISSUE THREAD

**Issue by jhspaybar** [INRIA/spoon#774]
I'm using the --with-imports flag as I am using spoon to do a change of source which I expect to check back into source control and have developers continue to use.  My change is to migrate code from a deprecated class to a non-deprecated alternative.  This works pretty well except that the imports in the file end up a jumbled mess compared to the nicely formatted import blocks that previously existed.  Is there a way to preserve the imports that previously existed minus the class I've replaced and plus the class I replaced it with?

**Comment by tdurieux** [comment]
Unfortunately it is not possible, because spoon computes the imports instead of using the import written by the developer.

**Comment by jhspaybar** [comment]
Sounds good.  I suppose it's not the end of the world to have a developer just run Optimize Imports in their IDE after the generated code is emitted.

**Comment by retuxx** [comment]
> I suppose it's not the end of the world to have a developer just run Optimize Imports in their IDE after the generated code is emitted.

IMHO importing `*` is a code smell anyway as it hides concrete dependencies.

**Comment by monperrus** [comment]
It's not possible right now and not implementable with the current design.
However, this will be handled in the mid-term with the sniper mode.
Closing this issue, don't hesitate to reopen if appropriate.
