### ISSUE TITLE
Spoon doesn't support generating local classes within methods

### ISSUE THREAD

**Issue by lukemerrick** [INRIA/spoon#786]
Although it's not usually best practice to do so, it is legal in Java to declare a class `InnerClass` as such:

>     class MainClass {
        public foo () {
            class InnerClass {}
            // method body that initializes and uses objects of type InnerClass
        }
    }

However, when generating a CtClass object via the `Core()` factory, the type seems to default to `MainClass.InnerClass` which is incorrect if `InnerClass` is inserted into the method `foo`. The [`create`](http://spoon.gforge.inria.fr/mvnsites/spoon-core/apidocs/spoon/reflect/factory/ClassFactory.html#create-spoon.reflect.declaration.CtClass-java.lang.String-) method of the `Class()` factory (meant to create inner classes) also requires a declaring class and thus also only seems to support code of the structure:

>     class MainClass {
        class InnerClass {}
        public foo () {
            // method body
        }
    }

**Comment by tdurieux** [comment]
It's related to #776.
Unfortunatelly, we don't yet a valid solution for this issue

**Comment by monperrus** [comment]
One possible solution is to prefix the internal class name by a digit. Does this work?

**Comment by monperrus** [comment]
by the way, should you find a fix for this problem, a pull request would be welcome

**Comment by monperrus** [comment]
closing this one, #776 is the reference issue.
