### ISSUE TITLE
Spoon Error logs are printed when called from a gradle plugin.

### ISSUE THREAD

**Issue by aveuiller** [INRIA/spoon#788]
When using a spoon project with logLevel to _OFF_ directly from java, no logs are shown, as expected.
But when this project is integrated in a gradle plugin, error logs are shown during the build process.

This project environment uses `noclasspath`, thus those errors are not relevant.

```
$ ./gradlew compileDebugJava
Parallel execution is an incubating feature.
Incremental java compilation is an incubating feature.
:dartJavaTask
:dartApiTask
error: Dependency cannot be resolved to a type at /project/build/generated/source/generation/debug/package/GenClass.java:12
[...] // Similar errors
######################################################
Spoon logger level: OFF
Gradle logger level (debug?): false // Spoon debug log aren't shown even if gradle log is to debug
Gradle logger level (error?): true

[...]

BUILD SUCCESSFUL
```

**Comment by aveuiller** [comment]
No resolution found yet, will close until further info.

**Comment by aveuiller** [comment]
After investigation, [this line](https://github.com/INRIA/spoon/blob/stable/src/main/java/spoon/support/compiler/jdt/JDTBasedSpoonCompiler.java#L673) is logging the JDT errors. (side note: The ternary operator is useless on this line since you already have a condition on `isError()`)

The problem seems to come from the gradle build process, which completely overrides `log4j` logger levels to comply with the one given on gradle command, e.g. `gradle task --debug` will force spoon to log everything above debug level. So there is no bug with Spoon loggers. ;)

Having said that, Would that be possible to filter out this specific kind of error since they are not relevant to the noClasspath mode?

To do so we could use the `CategorizedProblem` _ID_ which will return an [UndefinedType](http://help.eclipse.org/mars/index.jsp?topic=%2Forg.eclipse.jdt.doc.isv%2Freference%2Fapi%2Fconstant-values.html&anchor=org.eclipse.jdt.core.compiler.IProblem.UndefinedType) in this case.

**Comment by monperrus** [comment]
excellent idea, would you create a PR?
