### ISSUE TITLE
invocation.getExecutable().getExecutableDeclaration() returns null in case of enum methods call

### ISSUE THREAD

**Issue by fedorov-s-n** [INRIA/spoon#793]
Docs say `getExecutableDeclaration()` should return `CtExecutable` even if Spoon should use reflection to do it.  There is an example it doesn't and `invocation.getExecutable().getExecutableDeclaration()` returns `null`. 
Steps to reproduce:
Create

    enum E {
    }

Create call to `E.values()` and assign `invocation` to `CtInvocation` of it. Now `invocation.getExecutable().getExecutableDeclaration()` returns `null`.

Possible reason is that class `E` is not recognized as subclass of `java.lang.Enum` because `E` is in source path and  `java.lang.Enum` isn't and there are no `extends` declaration on `E`.

**Comment by monperrus** [comment]
I agree this is a real problem for end users. I've proposed a solution in #661 , what do you think?

**Comment by fedorov-s-n** [comment]
I wonder why `java.lang.Enum` isn't reflected as all `enum`'s parent? It actually is! Imho, enum methods aren't different from any other method that is recovered by reflection

**Comment by fedorov-s-n** [comment]
Well, got it, issue is these are synthetic methods of `Enum`. Yes, looks like generating implicit methods is the only available solution.

**Comment by fedorov-s-n** [comment]
https://github.com/INRIA/spoon/issues/793
