### ISSUE TITLE
Is `CtElementImpl#setParent` set after `Launcher#buildModel?

### ISSUE THREAD

**Issue by retuxx** [INRIA/spoon#807]
Is the parent of an element set by any function after `Launcher#buildModel` and, therefore, after the model has been created? I'm struggling with a `ParentNotInitializedException` exception thrown by `CtElementImpl#getParent`. I'm using several visitors in parallel (multiple threads) to examine some Java code. When I try to debug my code the error disappears. I'm not explicitly changing the model, though, it looks like it is modified indirectly by one of my visitors.

**Comment by retuxx** [comment]
It looks like `CloneVisitor` is missing to copy some references. More investigation is required.

**Comment by monperrus** [comment]
> Is the parent of an element set by any function after Launcher#buildModel and, therefore, after the model has been created?

yes, all elements should have a parent.

**Comment by retuxx** [comment]
I was able to avoid the exception. I'm not entirely sure whether I abused the API or whether it is a bug in spoon. I will close this issue for now, however.
