### ISSUE TITLE
Misleading architecture moments

### ISSUE THREAD

**Issue by fedorov-s-n** [INRIA/spoon#812]
I've got some questions about architecture:

  1. Why does `CtScanner` scan value of `CtLiteral` but doesn't scan name of `CtNamedElement`?
  2. Why does `CtClass` extend `CtStatement`?

Is there an "architecture spec" that states answers to questions like these?
As I think these two are bugs. Please answer to the questions above if they aren't.

**Comment by monperrus** [comment]
>  1. Why does |CtScanner| scan value of |CtLiteral| but doesn't scan
>     name of |CtNamedElement|?
>
Because it's not its responsibility. If you want to scan
|CtNamedElement, see CtInheritanceScanner.

|
>
>  1. Why does |CtClass| extend |CtStatement|?
>
Because you can have internal classes in a method.

|We'd be happy to accept pull requests on the API doc of any class to
clarify the design.|

**Comment by fedorov-s-n** [comment]
1. I wonder why does it scan a value? Literal value isn't part of AST, imho. 
  2. Thanks, got it. BTW, it turns out that `CtEnum` is `CtStatement` too,  though you cannot have local enum.

**Comment by monperrus** [comment]
> I wonder why does it scan a value? 

Which method are you referring to?

**Comment by fedorov-s-n** [comment]
`CtScanner.visitCtLiteral(.)` contains `scan(literal.getValue());`

**Comment by monperrus** [comment]
>  why does it scan a value? 

because, a scanner always scans the content of AST nodes. The literal value is considered as content.

**Comment by fedorov-s-n** [comment]
Thanks, got it.
