### ISSUE TITLE
Process with CtModelImpl implementation

### ISSUE THREAD

**Issue by lukot** [INRIA/spoon#815]
Hello,
I use your library for Android project processing and I found that when I call [CtModelImpl.processWith(...)](https://github.com/INRIA/spoon/blob/603665683d35acd72d6ead85d6b748effd1a2a91/src/main/java/spoon/reflect/CtModelImpl.java#L101) nothing happens.
Shouldn't CtModelImpl.processWith(...) add processor for `QueueProcessingManager` object? I see that parameter passed to `CtModelImpl.processWith(...)` is ignored .
Should thix be fixed?

**Comment by monperrus** [comment]
yes, this looks like a bug in a should-be-tested feature. A fix and a test case in a pull request are highly welcome :-)
