### ISSUE TITLE
DefaultJavaPrettyPrinter.visitCtThisAccess

### ISSUE THREAD

**Issue by leventov** [INRIA/spoon#826]
I think it shouldn't rely on getTarget().isImplicit() when printing this qualifier, because classes could be moved around, and Implicit flag is usually not modified.

Such implementation work better for me, probably it should be adapted for DefaultJavaPrettyPrinter itself (+ corner cases, which I omitted in my code because not the case for me):

``` java
    class MyPrinter extends DefaultJavaPrettyPrinter {

        Deque<CtClass<?>> currentThis = new ArrayDeque<>();

        public MyPrinter(Environment env) {
            super(env);
        }

        @Override
        public <T> void visitCtClass(CtClass<T> ctClass) {
            currentThis.push(ctClass);
            super.visitCtClass(ctClass);
            currentThis.pop();
        }

        @Override
        public <T> void visitCtThisAccess(CtThisAccess<T> thisAccess) {
            enterCtExpression(thisAccess);
            if (!thisAccess.isImplicit()) {
                if (thisAccess.getType().getDeclaration() != currentThis.peek()) {
                    visitCtTypeReferenceWithoutGenerics(thisAccess.getType());
                    write(".");
                }
                write("this");
            }
            exitCtExpression(thisAccess);
        }
    }
```

**Comment by monperrus** [comment]
if it's a bug, could you provide us with a failing test case? thanks.

**Comment by monperrus** [comment]
Hi @leventov , any news on this? is this really a bug?

**Comment by leventov** [comment]
@monperrus probably I can pay some time for this, as well as other issues I've reported, next weekend.

**Comment by monperrus** [comment]
OK, thanks.

**Comment by monperrus** [comment]
ping @leventov 
do you work on this? 
(to know whether we wait for your issues for the next release)

**Comment by leventov** [comment]
@monperrus please don't wait for issues opened by me.
