### ISSUE TITLE
UnresolvableClass::new -> CtExecutableReferenceImpl.declaringType is null

### ISSUE THREAD

**Issue by leventov** [INRIA/spoon#827]
If in code there is an unresolvable class (e. g. it is generated by annotation processor later), and `::new` construct is used against it, Spoon builds `CtExecutableReferenceImpl` with `declaringType=null`. This causes NPE at https://github.com/INRIA/spoon/blob/25f9202a4ee6e77a9d0c4ad5060c88ba2506f50a/src/main/java/spoon/support/visitor/SignaturePrinter.java#L53

**Comment by monperrus** [comment]
should be fixed by 39919e3fdb5bea8fc2c17520e7a77053bdd732dd

**Comment by leventov** [comment]
Thank you very much :)

When to expect the next release?

**Comment by monperrus** [comment]
pretty soon, once the snapshot has been well tested. It will probably be a 6.0.

**Comment by leventov** [comment]
@monperrus probably, but declaringType=null is definitely a bug, somewhere in treeBuilder. This field should never be null
