### ISSUE TITLE
Upgrading Apache Commons IO to 1.4

### ISSUE THREAD

**Issue by retuxx** [INRIA/spoon#845]
I'm using Spoon along with [zt-exec](https://github.com/zeroturnaround/zt-exec/blob/master/pom.xml), a library allowing me to run system commands from within Java. Unfortunately, Spoon and zt-exec are using incompatible versions of Apache's commons-io - Spoon in version 1.3.2 and zt-exec in version 1.4. In particular, Apache's class `NullOutputStream` does not provide the field `NULL_OUTPUT_STREAM` in 1.3.2 but does in 1.4. I could exclude commons-io of Spoon and pull the transitive dependency from zt-exec but maybe you are willing to upgrade commons-io to 1.4.

**Comment by retuxx** [comment]
Thanks

**Comment by GerardPaligot** [comment]
You're welcome! (:
