### ISSUE TITLE
executableRef.getDeclaration() doesn't work in case of specialized constructor call.

### ISSUE THREAD

**Issue by leventov** [INRIA/spoon#856]
This is apparently because CtClassImpl.getConstructor() uses simple .equals() on parameters, while should probably use CtTypeImpl.isSameParameter(). However isSameParameter() is "approximate" and allows false positives, more systemic approach would be to properly _generalize_ parameter types at CtTypeImpl.getMethod().

**Comment by monperrus** [comment]
does it return null or the wrong constructor?

**Comment by leventov** [comment]
@monperrus null. Btw I use intellij, but often build with maven cli as well and see the same.

**Comment by tdurieux** [comment]
Do you have a test case? 
Thanks

**Comment by monperrus** [comment]
seems similar to this problem and fix 366bcc02ae4a178ee761531e401fc9ace285e9e3

**Comment by monperrus** [comment]
Friday's cleaning, closing this one, don't hesitate to reopen with a test case.
