### ISSUE TITLE
performance bug: shadow classes should be cached

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#867]
shadow classes are neither put in the factory nor cached

**Comment by tdurieux** [comment]
It seams voluntary: https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/reflect/factory/TypeFactory.java#L467

**Comment by monperrus** [comment]
but shadow shouldn't be pretty-printed

**Comment by GerardPaligot** [comment]
3 solutions:

- Put everything in one factory and, in the pretty printer, check we don't print a shadow element. Think that all queries will be make on these shadow elements too, that seems a bad solution.
- Create a factory for shadow elements and have an API to get them when it is necessary (with all checks necessary).
- Retain the current solution.
