### ISSUE TITLE
getDeclaration of CtLocalVariable does not find declarations in for loops

### ISSUE THREAD

**Issue by retuxx** [INRIA/spoon#868]
I have the following (stripped version) code:

```java
package net.sf.jabref.collab;

import java.io.*;
import java.util.*;
import javax.swing.*;
import javax.swing.tree.DefaultMutableTreeNode;
import net.sf.jabref.*;
import net.sf.jabref.groups.*;
import net.sf.jabref.imports.*;


public class ChangeScanner extends Thread {
    
    
    /**
     * Finds the entry in neu best fitting the specified entry in old. If no entries get a score
     * above zero, an entry is still returned.
     * @param old EntrySorter
     * @param neu EntrySorter
     * @param index int
     * @return BibtexEntry
     */
    private BibtexEntry bestFit(EntrySorter old, EntrySorter neu, int index) {
        double comp = -1;
        int found = 0;
        loop: for (int i=0; i<neu.getEntryCount(); i++) {
            double res = Util.compareEntriesStrictly(old.getEntryAt(index),
            neu.getEntryAt(i));
            if (res > comp) {
                comp = res;
                found = i;
            }
            if (comp > 1)
                break loop;
        }
        return neu.getEntryAt(found);
    }
    
}
```

As you can see, `i` is a for loop variable that is referenced multiple times, for example by `neu.getEntryAt(i)`. I'm using a `CtScanner` to find declarations that are not referenced, also known as unused code. Nevertheless, if my visitor visits any variable reference referencing `i`, `getDeclaration()` is not able to `i's` declaration. The reason for this error is obvious, [CtLocalVariableReferenceImpl](https://github.com/INRIA/spoon/blob/f1baa5b9da2c7657f958ec73446db5412801e0d2/src/main/java/spoon/support/reflect/reference/CtLocalVariableReferenceImpl.java#L46) traverses all parent blocks one after another and [checks](https://github.com/INRIA/spoon/blob/f1baa5b9da2c7657f958ec73446db5412801e0d2/src/main/java/spoon/support/reflect/reference/CtLocalVariableReferenceImpl.java#L51) whether a statement of the current examined block is a CtLocalVariable and, if true, whether the variable is the one we are looking for. In case of a CtForLoop (let's call it `loop`), this code is missing `loop`'s declarations (`i` in our example). One solution to fix this error is to check whether a statement is a for loop (or any other statements allowing to declare variables in a new scope-lambdas maybe). However, you may have a better idea that is less brittle.

**Comment by monperrus** [comment]
> One solution to fix this error is to check whether a statement is a for loop (or any other statements allowing to declare variables in a new scope-lambdas maybe).

Seems reasonable.
