### ISSUE TITLE
How to write Spoon model to source file?

### ISSUE THREAD

**Issue by smiklosovic** [INRIA/spoon#871]
Hello, sorry for hijacking this issues "forum" but I have just a question I have not found answer for at the web.

I want to use Spoon to programmatically construct some code (this even sounds funny :) ) and once done, I want to write that to regular java file so I can compile that afterwards.

I want to basically make a program which parses some input file of custom structure and it will generate respective java file to be compiled and used.

Could you tell me how to get string representation of Spoon model?

Thanks!

**Comment by retuxx** [comment]
I think [JavaOutputProcessor](https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/support/JavaOutputProcessor.java) is what you are looking for.

**Comment by monperrus** [comment]
or simply:

```
ctClass.toString();
ctMethod.toString();
ctBlock.toString();
```

**Comment by tdurieux** [comment]
@monperrus  ```ctClass.toString();``` does not print neither the package nor the imports. The output is thus not compilable.

**Comment by smiklosovic** [comment]
How is that code formatted? Could I influence how that generated code looks like?

**Comment by retuxx** [comment]
JavaOutputProcessor requires a [PrettyPrinter](https://github.com/INRIA/spoon/blob/ae4eb952a9f16cf9ff6f5b7355e124a499a8d6ff/src/main/java/spoon/reflect/visitor/PrettyPrinter.java) that is supposed to create the actual layout of the generated source. [DefaultJavaPrettyPrinter](https://github.com/INRIA/spoon/blob/ae4eb952a9f16cf9ff6f5b7355e124a499a8d6ff/src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java) is a default implementation that allows you to subclass certain prints.
