### ISSUE TITLE
I can not use this project in Gradle

### ISSUE THREAD

**Issue by smiklosovic** [INRIA/spoon#875]
I have to use this as a dependency.

I am running this in Gradle.

[buildinfo] Not using buildInfo properties file for this build.
Download https://repo1.maven.org/maven2/fr/inria/gforge/spoon/spoon-core/5.3.0/spoon-core-5.3.0.pom
Download https://repo1.maven.org/maven2/com/martiansoftware/jsap/2.1/jsap-2.1.pom

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':runtimeCopy'.
> Could not find org.eclipse.jdt:org.eclipse.jdt.core:3.12.0.v20160516-2131.
  Searched in the following locations:

**Comment by monperrus** [comment]
do you mean in gradle (message) or in maven (title)?

**Comment by monperrus** [comment]
What if you add in your gradle config file?
```
repositories {
            mavenLocal()
            maven {
              url 'http://spoon.gforge.inria.fr/repositories/'
           }
}
```

**Comment by smiklosovic** [comment]
Yes! Works, I have to read the docs better ...

**Comment by monperrus** [comment]
thanks  @aveuiller for the solution.
