### ISSUE TITLE
exclude subdirectories or files from the SpoonCompiler

### ISSUE THREAD

**Issue by arturbosch** [INRIA/spoon#877]
We have some cases where we want to exclude classes based on their name e.g. "*Test.java". Is this possible?

**Comment by monperrus** [comment]
Do you mean excluding them from the model? or when rewriting the code?

**Comment by arturbosch** [comment]
Exclude them from the model. Even don't create CtElements for them at all.

**Comment by arturbosch** [comment]
Our approach would be to extend FileSystemFolder and override getAllJavaFiles() ?

**Comment by monperrus** [comment]
> Our approach would be to extend FileSystemFolder and override getAllJavaFiles() ?

It looks like a really good idea.

**Comment by monperrus** [comment]
you're right. Don't hesitate to propose a pull request for this.

**Comment by monperrus** [comment]
what do you think of the example in https://github.com/INRIA/spoon/pull/884/files#diff-d8eeb63cece97806d7fc56c55fc32088R169?

**Comment by arturbosch** [comment]
Does `super.getCompilationUnits()` mean, a compilation unit is firstly created for everyfile and then we filter them?

My solution for spoon would be to add 
```java	
public void addFilenameFilter(final List<FilenameFilter> pFilters) {
	Validate.notNull(pFilters, "null argument `pFilters`");
	filters = new ArrayList<>(pFilters);
}
```  for Launcher.

addInputResource would pass the filters to the FileSystemFile/-Folder.
```java
	@Override
	public void addInputResource(String path) {
		File file = new File(path);
		if (file.isDirectory()) {
			getModelBuilder().addInputSource(new FileSystemFolder(file, filters));
		} else {
			getModelBuilder().addInputSource(new lFileSystemFile(file, filters));
		}
	}
```

In this classes we use something like `!filters.stream().anyMatch(filter -> filter.accept(f, f.getName())))` in getAllFiles() and a new method `isNotIgnored() in isJava().

What is your opinion on this approach?

**Comment by monperrus** [comment]
One question: since you can add resources one by one (up to a single Java file), you already have full control over the model that is built. Why is it not satisfactory in your use case?

**Comment by retuxx** [comment]
Because it is much easier to say: include everything in `src`except of files in `src/java/test`.
