### ISSUE TITLE
SpoonClassNotFoundException and ClassNotFoundException

### ISSUE THREAD

**Issue by gnom7** [INRIA/spoon#894]
Hello, please, help me to figure out whether there is a way to pass data between two (or more) spoon annotation processors. I'd like to use one of my annotations just to mark some classes -- thus in compile time I can conveniently retrieve them and use in other processors.
I have tried to use filters -- 1. get root package; 2. filter by annotation type and get all I need; but later when I try to guess about type compatibility (using whether java's Class.forName() or spoon's ctClass.getActualClass() I get ClassNotFoundException or SpoonClassNotFoundException respectively).
To compile my code I use maven with Spoon Maven Plugin.

**Comment by monperrus** [comment]
In Spoon, it is not recommended to use `Class.forName()` or `ctClass.getActualClass()` (only there for debugging).

The API gives you everything to reason about type compatibility, see in particular `getTypeDeclaration()`

**Comment by gnom7** [comment]
Oh, you are right, thank you so much!
