### ISSUE TITLE
jdt with ecj, wrong extension

### ISSUE THREAD

**Issue by gnom7** [INRIA/spoon#903]
Hello, I use in my project `querydsl-apt`.
Due to it's transitive dependency `querydsl-apt -> querydsl-codegen -> codegen -> ecj` spoon's `JDTBatchCompiler` gets wrong superclass.

Doesn't matter/help in this case:

> // we use a fully qualified name to make it clear we are extending jdt

**Comment by monperrus** [comment]
Do you put `querydsl-codegen, codegen, ecj` in the Java classpath or do you use Spoon's option `source-classpath`?

**Comment by gnom7** [comment]
I use `maven` for my dependencies managment and as a build tool, if you meant it.
I just have an dependency to `spoon-core` and another to `querydsl-apt`.
I use `spoon` directly from my code via `Launcher` (without spoon maven plugin).
When I use `run()` method on my `Launcher` instance, I get an error -- something like unrecognized `option -1.8` from `JDTBatchCompiler`.

**Comment by monperrus** [comment]
>  I just have one dependency to spoon-core and another to querydsl-apt.

The order may matter. Is the dependency to spoon-core before in the pom.xml?

**Comment by gnom7** [comment]
I can't remember at the moment, sorry. I will answer you on monday.

**Comment by gnom7** [comment]
Hello. Setting `spoon-core` as first dependency resolved the problem. Also it is possible to me to pick out all functionality related on `spoon` in different maven-module without interfering dependency to `ecj`, but I thought that this behavior should be fixed, shouldn't?
Thank you for your help.

**Comment by monperrus** [comment]
Happy to see that this is fixed. This is more a Java/Maven problem than a Spoon problem.
