### ISSUE TITLE
feature: add support for Java9 constructs in the metamodel

### ISSUE THREAD

**Issue by GerardPaligot** [INRIA/spoon#904]
Hi,

From 25 to 27 october, there will be the [EclipseCon 2016](https://www.eclipsecon.org/europe2016/) and for this occasion, the Eclipse team works hard to release JDT 4.7 with the support of Java 9.

That could be awesome if Spoon will be the first one who supports this new version of Java! (:

**Comment by monperrus** [comment]
Hi @GerardPaligot , what do you recommend as document that lists the new features to be put in Spoon?

**Comment by GerardPaligot** [comment]
You have the project page [here](https://jdk9.java.net/). You should find everything you need there.

**Comment by retuxx** [comment]
Does have Java 9 any language extensions like Java7's multi-catch or Java8's lambdas?

**Comment by GerardPaligot** [comment]
@retuxx Yes, [module](http://openjdk.java.net/projects/jigsaw/quick-start).

**Comment by monperrus** [comment]
ongoing work on the runtime side (not the model side) #1585

**Comment by monperrus** [comment]
now that #1585 is done, we can do this one.

@petitpre you told me that you're about to start working on adding the Java9 concepts in the metamodel, is that correct?

**Comment by monperrus** [comment]
closed per #1730
