### ISSUE TITLE
release 5.4: Oct 27 2016

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#905]
Hi all, 
the next release is planned for Oct 27 2016.
4 days to test the SNAPSHOT!

# Changelog

# Important changes

* CtElement are not comparable anymore (no natural order), they cannot be put in raw TreeSet (PR: #844)
* The processing and scanning order has changed, it now follows the source code order (Issue: #681) (PR: #841) 

# New feature

* **ast**
  * Always a block for CtIf and CtLoop. (PR: #805)
* **cttype** : New method to know whether a given method is part of a CtType. (PR: #880)
* **position** : Defines a default source position for all elements. (PR: #861)

# Fixes

* **factory** : Handles null parameter in Type#createReference(Class) and isSubTypeOf. (Closes #825). (Issue: #825) (PR: #837)
* **getDeclaration** : Incorrect between getReference and getDeclaration for local variables. (PR: #888)
* Fixes potential NullPointerException in JDTTreeBuilderQuery. (PR: #887)
* Enables parallel tests. (PR: #838)
* GetAllMethods in noclasspath return when encounter an unknown class. (PR: #864)
* Better getDeclaration of CtLocalVariable  (Fixes #868). (Issue: #868) (PR: #873)
* **compilation** : Always uses the content of the ast to compile the ast (fixes #878). (Issue: #878) (PR: #879)
* **exception** : Improves snippet compilation error message. (PR: #858)
* **if** : Print the else body when the body is not a block (closes #881). (Issue: #881) (PR: #883)
* **isLocalType** : Proper support for creating internal classes (fixes #776). (Issue: #776) (PR: #860)
* **literal**
  * Fix literal type. (PR: #891)
  * Set the type of the CtLiteral via the CodeFactory. (PR: #829)
* **loop** : Always use CtBlock in CtForeach. (PR: #847)
* **method** : Avoid Concurrent modification with CtType#addMethod. (PR: #850)
* **position** : Add default compilation unit when pretty-printing a new CtClass (closes #885). (Issue: #885) (PR: #886)
* **travis** : The logs of Travis are not polluted by Javadoc warnings. (PR: #866)

# Documentation

* Add missing paper information. (PR: #889)
* Adds doc about architecture checking. (PR: #843)
* Update papers.md. (PR: #834)
* Update on release doc. (PR: #830)
* **gradle** : Improves Gradle doc (fixes #875). (Issue: #875) (PR: #876)
* **support** : Improves support documentation. (PR: #865)
* **release** : Update release number. (PR: #831)

# Refactoring

* Allow Launcher to use an existing Factory (Closes #862). (Issue: #862) (PR: #863)
* Fix a test that fails on Eclipse due to its classloader. (PR: #859)
* Removes all useless conditions with CtReference. (Closes #824). (Issue: #824) (PR: #836)
* **ast** : Improves generic parameter type of setActualTypeReferences. (Closes #823). (Issue: #823) (PR: #835)
* **release** : Remove deprecated code. (PR: #833)

# Other

* **jenkins** : Clean. (PR: #848)
* **pom** : Updates commons-io from 1.3.2 to 1.4. (Closes #845). (Issue: #845) (PR: #851)
* **release**
  * Scripts to publish automatically a release. (PR: #852)
  * Adds nodejs script to generate changelog. (PR: #832)
* **travis** : Avoid running several times the tests on Travis. (PR: #839)
* **version** : Update spoon maven plugin version. (PR: #849)
* **website** : Add a link checker (fixes #797). (Issue: #797) (PR: #872)

--Martin

**Comment by retuxx** [comment]
Thank you for your work!
