### ISSUE TITLE
NPE in ExplicitConstructorCall of JDT

### ISSUE THREAD

**Issue by arturbosch** [INRIA/spoon#908]
When running newest spoon on argouml in noClasspathMode we get a strange NP in the attached file 
[npe.zip](https://github.com/INRIA/spoon/files/556834/npe.zip)

Line 266 in code says `if (Dbg.on) Dbg.__assert__(i >= 0 && i < _npoints, "point not found");`
but JDT interprets it as `if (Dbg.on) Dbg.__super__(i >= 0 && i < _npoints, "point not found");`

Best way to observe this behaviour is to set a conditional breakpoint in JDTTreeBuilder in Line 1027 with the condition `inv.getExecutable() == null`

**Comment by tdurieux** [comment]
The jdt binding of the constructor is null, it is very strange...

**Comment by tdurieux** [comment]
The method name assert is not present in the jdt data, I don't know how to fix this bug.
May be there is an option in JDT to prevent this change.
I did not yet look the JDT code to understand what going on.

**Comment by surli** [comment]
I just investigate and `assert` is a keyword for Java since version 1.4, then you're not allowed to create a method name `assert` which means JDT considers it is a keyword and failed on the token. 

Then the fix is really simple: you have to force the compliance level of Spoon to version 3, to accept the keyword.
Just tested on the attached file and it works fine for me.

**Comment by surli** [comment]
Thanks for the bug report. The problem is fixed to me as shown in my commit.

**Comment by retuxx** [comment]
Thank you @surli for your work. Does setting the compliance level also fix #925?

**Comment by surli** [comment]
As explained in #925 I did not manage to reproduce the bug there. Do you have more inputs about it?

**Comment by retuxx** [comment]
Oh, didn't notice, sorry. I'll test latest Spoon and see if the error has gone. Will give you feedback the next days.
