### ISSUE TITLE
Duplicity in package-info.java when templates are used

### ISSUE THREAD

**Issue by pvojtechovsky** [INRIA/spoon#921]
The package-info.java with this content

``` java
/**
 * This is test
 * JavaDoc.
 */
@Deprecated
package spoon.test.pkg;
```

prints this not compilable output

``` java
/**
 * This is test
 * JavaDoc.
 *//**
 * This is test
 * JavaDoc.
 */@java.lang.Deprecated
@java.lang.Deprecated
package spoon.test.pkg;
```

when templates are added to the Launcher

See this [branch with test](https://github.com/pvojtechovsky/spoon/tree/duplicitiesInPackageInfo) to reproduce the problem.

What way do you prefer to contribute new test? 
A) branch like this?
B) branch like this + PR?

**Comment by monperrus** [comment]
If you have a PR with a fix, it's always better :-)

**Comment by pvojtechovsky** [comment]
It looks like FileCompiler.getCompilationUnits() always compiles sources and templates
```java
	public CompilationUnit[] getCompilationUnits() {
		List<SpoonFile> files = new ArrayList<>();
		files.addAll(jdtCompiler.sources.getAllJavaFiles());
		files.addAll(jdtCompiler.templates.getAllJavaFiles());
```
but may be it should compile only the required java *files* - these which are sent as input to 
```java
JDTBatchCompiler.getUnits(List<SpoonFile> files)
```
I mean stacktrace like this
```
	at spoon.support.compiler.jdt.FileCompiler.getCompilationUnits(FileCompiler.java:54)
	at spoon.support.compiler.jdt.JDTBatchCompiler.getUnits(JDTBatchCompiler.java:117)
	at spoon.support.compiler.jdt.FileCompiler.getUnits(FileCompiler.java:1)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.****buildSources OR buildTemplates****(JDTBasedSpoonCompiler.java:380)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:116)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:99)
	at spoon.Launcher.buildModel(Launcher.java:712)
	at spoon.test.pkg.PackageTest.testAnnotationInPackageInfoWhenTemplatesCompiled(PackageTest.java:120)
```

**Comment by monperrus** [comment]
> but may be it should compile only the required java files - these which are sent as input to 

it makes sense

**Comment by pvojtechovsky** [comment]
@monperrus could you please explain the comment "they have to be done all at once"?
```java
class JDTBatchCompiler {
...
	public CompilationUnitDeclaration[] getUnits(List<SpoonFile> files) {
...
		// they have to be done all at once
		final CompilationUnitDeclaration[] result = treeBuilderCompiler.buildUnits(getCompilationUnits());
```
Or can I found some concept of compiler in some documentation/issue/PR?
I am trying to understand how compilation works. But it changes a lot in history and it is hard for me to understand, what is feature and what is a bug.

On one side You agree that "it makes sense" to compile only required java files, but on the other side, there is comment `they have to be done all at once`. So I have feeling like compiler needs all sources and all templates together at one time, otherwise (I am guessing!) it will produce compilation errors - missing classes, etc. What is your experience please?

**Comment by monperrus** [comment]
Hi Pavel,

Are you trying to travel from the surface of Spoon to the deepest and
darkest parts in a few days? You're brave :-)

As far as I remember, I put this comment after having tried to put the
buildUnits inside the for loop after and realized that this was not an
option. Why? I don't remember.

What's sure is that "all at once" referred to the model, not to the
templates. They are conceptually separated and should be parseable
separately.
