### ISSUE TITLE
CtClass.getSuperClass() returns invalid CtTypeReference

### ISSUE THREAD

**Issue by pvojtechovsky** [INRIA/spoon#959]
The `spoon.test.imports.ImportTest.testSpoonWithImports` fails with PR #913, because it now calls `CtTypeReference.getActualClass()` on invalid `CtTypeReference` to child class 

```java
spoon.test.imports.testclasses.internal.SuperClass$InnerClassProtected
```
which has wrong qualified name
```java
spoon.test.imports.testclasses.internal.ChildClass$InnerClassProtected
```
I will provide PR with simplified failing test.

**Comment by pvojtechovsky** [comment]
The wrong declaringType of that inner class is caused by this code in `JDTTreeBuilderHelper` method `createType(TypeDeclaration typeDeclaration)`
```java
				// Sorry for this hack but see the test case ImportTest#testImportOfAnInnerClassInASuperClassPackage.
				// JDT isn't smart enough to return me a super class available. So, I modify their AST when
				// superclasses aren't in the same package and when their visibilities are "default".
				List<ModifierKind> modifiers = Arrays.asList(ModifierKind.PUBLIC, ModifierKind.PROTECTED);
				final TypeBinding resolvedType = typeDeclaration.superclass.resolvedType;
				if ((resolvedType instanceof MemberTypeBinding || resolvedType instanceof BinaryTypeBinding)//
						&& resolvedType.enclosingType() != null && typeDeclaration.enclosingType.superclass != null//
						&& Collections.disjoint(modifiers, getModifiers(resolvedType.enclosingType().modifiers))) {
					typeDeclaration.superclass.resolvedType = jdtTreeBuilder.new SpoonReferenceBinding(typeDeclaration.superclass.resolvedType.sourceName(),
							(ReferenceBinding) typeDeclaration.enclosingType.superclass.resolvedType);
				}
```
@GerardPaligot please have a look. As author you can fix it probably the fastest. Thank You!

@monperrus By the way, how do you manage assignment of issues to contributors? May be somebody is already fixing it and I was just wasting my time ;-)

**Comment by monperrus** [comment]
> By the way, how do you manage assignment of issues to contributors?

I don't assign anything. If somebody starts working on an issue, she/he can simply drop a comment on it to let the others know.

**Comment by tdurieux** [comment]
I don't know how to fix this.
With the current implementation we use the qualified name as an access path not the path to the declaration.
In the current metamodel of spoon we cannot store the these informations.
We already discuss this when @GerardPaligot implements this hack.

**Comment by monperrus** [comment]
The current behavior is correct, see #971
