### ISSUE TITLE
test APITest.testSetterInNodes() does not work at all

### ISSUE THREAD

**Issue by pvojtechovsky** [INRIA/spoon#972]
The API contract which should be enforced by the APITest.testSetterInNodes() IS NOT CHECKED, because this test is actually doing NOTHING.

Put the breakpoint on line 359
```java
assertTrue("Check the method " + statement.getParent(CtMethod.class).getSignature() ...
```
and you will see it NEVER enters the loop.

I have made a PR #968, which fixes that bug.... 

Yes Travis reports the errors, but it is not bug in the PR #968, it is report about broken API contracts!

I am not going to fix PR #968, because I have no idea how to do it. But I guess it is good idea to fix it to avoid merging more and more invalid APIs.

**Comment by monperrus** [comment]
> I am not going to fix PR #968, because I have no idea how to do it.

OK we'll look at it. Closing #968. Don't hesitate to reopen it before if you have a fix idea.
