### ISSUE TITLE
EqualsVisitor Does Not Consider Comments

### ISSUE THREAD

**Issue by retuxx** [INRIA/spoon#978]
I found that the `EqualsVisitor` doesn't validate comment tokens. That is, two elements are equal even though their comments are different. A simple c0.getContent().equals(c1.getCotent()) should be sufficient.

**Comment by danglotb** [comment]
Hi @retuxx , this is actually done in purpose: see [here](https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/reflect/declaration/CtElement.java#L268).
Maybe, the `EqualsVisitor` could be take the comment in account.

**Comment by retuxx** [comment]
> Maybe, the EqualsVisitor could be take the comment in account.

I think it makes perfectly sense to take a comment into account because a comment is a token which may or may not be equal to another comment token.

**Comment by monperrus** [comment]
I'm fine with removing the @IgnoreByEquals to consider all properties incl comments in equality.
This is less surprising, easier to maintain, and removes a hidden bug between `equals` and `hashCode` wrt comments.
@retuxx do you want to give this a try?

**Comment by retuxx** [comment]
@monperrus: I will create a PR later this day.

**Comment by retuxx** [comment]
Do I have to copy the file `EqualsVisitor.java` from `target/generated/spoon/support/visitor/equals/EqualsVisitor.java` to `src/main/java/spoon/support/visitor/equals/EqualsVisitor.java` manually? The test case `CtGenerationTest.testGenerateEqualsVisitor` fails because the generated and commit files differ.
