### ISSUE TITLE
Get Package Of a String Containing Java Code

### ISSUE THREAD

**Issue by retuxx** [INRIA/spoon#981]
I would like to create a compilation unit from a string containing Java code and retrieve its package in order to get its (relative) file system path. I know that I could parse the file by my own, search for `package` keyword (if any) and translate the package declaration to a path but maybe Spoon provides such a features already.

**Comment by monperrus** [comment]
very easy, see #982. WDYT?

**Comment by retuxx** [comment]
Thanks, didn't know the class `VirtualFile`.
