### ISSUE TITLE
[SpoonModelBuilder] Create a Model for Subset of Input

### ISSUE THREAD

**Issue by retuxx** [INRIA/spoon#985]
Creating a Spoon model from large size software systems takes several minutes due to the amount of analyses performed while parsing all input compilation units. Sometimes - for example when individual files have been updated (#752) - I want to create model describing a subset of the input sources only. I could add the desired files only but using noclasspath mode having a more complete classpath a very useful since, otherwise, existing references may be missing. Therefore, I'm looking for a feature that allows me to create a model for a subset of my input sources. 

My suggestion is to add a method to `SpoonModelBuilder` allowing me specify a filter that is applied **after** creation of the compilation units (in order to have more complete classpath) but **before** the traversal of a particular unit in order to minimize the required time to create a model.

**Comment by monperrus** [comment]
It seems a very good idea. Would you propose a pull request for this?

**Comment by retuxx** [comment]
Currently working on it.
