### ISSUE TITLE
Problems when parsing a file with comments

### ISSUE THREAD

**Issue by amuse38** [INRIA/spoon#998]
Hi,

I'm developping a gradle plugin using Spoon 5.4.
The first task I insert, generates an interface and an abstract class with JavaPoet (Sorry, I didn't find how to generate a new class from Spoon and make it persistent on disk, moreover I had lots of code written with Poet).
Then, a second task will transform some existing classes by adding the abstract class as superclass and making each of them implementing the interface.
When considering the following file (the interface)
```
package myproject;

import android.content.Context;
import java.lang.String;
import lombok.NonNull;

public interface IStorable<T> {
  /**
   * Converts a byte array into an instance of the stored object
   *
   * @param anContentArg The byte array containing the object
   *
   * @return The deserialized object
   */
  T fromByteArray(@NonNull final byte[] anContentArg);

  /**
   * Converts the instance into a byte array to store it
   *
   * @return A byte array containing the instance
   */
  byte[] toByteArray();

  /**
   * Gets the key of the instance to store
   *
   * @return The key associated with the instance
   */
  String key();

  /**
   * Setter for the Android application context
   *
   * @param contextArg The Android application context
   *
   * @return The instance of this object
   */
  IStorable<T> context(@NonNull final Context contextArg);
}

```
The following exception has bee raised:
Caused by: java.lang.NoSuchFieldError: forStartPosition
        at org.eclipse.jdt.internal.core.util.CommentRecorderParser.checkComment(CommentRecorderParser.java:85)
        at org.eclipse.jdt.internal.compiler.parser.Parser.consumeModifiers(Parser.java:5447)
        at org.eclipse.jdt.internal.compiler.parser.Parser.consumeRule(Parser.java:7306)
        at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:11112)
        at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:11360)
        at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:11317)
        at org.eclipse.jdt.internal.compiler.parser.Parser.dietParse(Parser.java:9732)
        at spoon.support.compiler.jdt.JDTBatchCompiler.getUnits(JDTBatchCompiler.java:151)
        at spoon.support.compiler.jdt.FileCompiler.getUnits(FileCompiler.java:28)
        at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildSources(JDTBasedSpoonCompiler.java:380)
        at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:116)
        at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:99)
        at spoon.Launcher.buildModel(Launcher.java:712)

When I parse the same file from the command line by using
`java -classpath spoon-core-5.4.0-jar-with-dependencies.jar spoon.Launcher -i test -x`
Everything seems to work fine.

I have tried to replace `spoon.run()` with `spoon.run(new String[]{ "-i", "test", "-x"})` but the result is the same.

I'm stuck and run out of idea ;) The problem starts with `buildModel`.

Many thanks for your help,

Best regards,

Alain

**Comment by pvojtechovsky** [comment]
Hi Alain,

> Caused by: java.lang.NoSuchFieldError

Looking at java doc of this exception there is following comment

> Thrown if an application tries to access or modify a specified field of an object, and that object no longer has that field. 
> Normally, this error is caught by the compiler; this error can only occur at run time if the definition of a class has incompatibly changed.

You mentioned that if you run it normally from command line, then it works. But you did not mentioned how do you run it, when it does not work. It looks like the spoon classes used it your environment are modified by something specific to your environment... 

- try to clean and build your development workspace again
- may be you processed the spoon classes by spoon or by gradle compiler by mistake.
- ...

Anyway it looks like problem of Your environment and not problem of the spoon code.

Best regards,
Pavel

**Comment by tdurieux** [comment]
I did not succeed to reproduce your issue.
I am not sure that the exception is related to the interface that you provide because the exception message is related to an unknown field `forStartPosition` but your interface does not contain that field.

 ```java
		Launcher spoon = new Launcher();
		spoon.addInputResource("<path to IStorable>");
		spoon.getEnvironment().setCommentEnabled(true);
		spoon.getEnvironment().setNoClasspath(true);
		spoon.buildModel();

		System.out.println(spoon.getFactory().Interface().get("myproject.IStorable"));
```

**Comment by amuse38** [comment]
Hi all,

Many thanks for your quick feedback.
Pavel is right.
I was spoon-ing already spoon-ed files as tdurieux pointed out, I added the generation folder as input folder.

Many thanks for your precious help !

Best regards,

Alain
